### ISSUE TITLE
slingshot@jfarthing84: Slingshot menu too small to cover search bar since Linux Mint 18.2 Installation

### ISSUE THREAD

**Issue by MPE2016** [linuxmint/cinnamon-spices-applets#1011]
@jfarthing84

Hi there,

- You can reproduce this by installing the applet after updating to Linux Mint 18.2.
- I expected the search bar to be within the area of the menu.
- The title explains it as best as I could, but the picture is probably more telling. Look at the top right corner of the menu; it no longer covers the search bar area (or perhaps the other way around: the search bar is no longer within the boundaries of the menu area.)
- This happens consistently.
- Cinnamon 3.4.3, Linux Mint 18.2

Should you have any more questions, feel free to ask. 

All the best,

MPE

P.S. I am otherwise a very happy user of your applet.
P.P.S. I did my best to follow the Bug Reporting guidelines. I am not sure, however, if mentioned the author correctly. 

![slingshot](https://user-images.githubusercontent.com/15818884/27992728-094d3c98-649b-11e7-9914-8ca0668c7afd.jpg)

**Comment by NikoKrause** [comment]
You mentioned the authore wrong. You used the UUID not the author.
Author is mentioned here https://cinnamon-spices.linuxmint.com/applets/view/197

**Comment by jaszhix** [comment]
@jfarthing84

**Comment by wudip** [comment]
Hi, it works okay on my Mint. What desktop theme and font are you using? Does it look same when you change it?

**Comment by MPE2016** [comment]
Hi, I'm using Noto Sans Regular 9.If I switch to 10 the problem persists.

On Mon, 10 Jul 2017 15:17:35 +0000 (UTC), Petr Wudi wrote:

> Hi, it works okay on my Mint. What desktop theme and font are you
using? Does it look same when you change it?

**Comment by MPE2016** [comment]
thanks, changed it.

**Comment by NikoKrause** [comment]
Which theme are you using?

**Comment by MPE2016** [comment]
Icons: Papirus

Gtk: adapta

But it also happens when using Mint-X&Y as icon themes and gtk.

**Comment by NikoKrause** [comment]
For me it looks like this on Cinnamon 3.4 with Mint-X theme:
![screenshot-cinnamon-2017-09-15-125659](https://user-images.githubusercontent.com/8415124/30479418-68e0cf62-9a15-11e7-9a5d-6f9ef74a99a1.png)

Is your applet up to date? Right click on applet, open `About ...` dialog, it should say:
 `2017-09-12 06:15:06 UTC`

**Comment by MPE2016** [comment]
You were right! I just checked Slingshot with Mint-X, and that looks
exactly the same as yours. So the "problem" most likely is the in the gtk
theming.

So the workaround for now would be to using Mint-X, in which case I will
probably use the normal mint menu (which of course doesn't look as nice).

On Fri, 15 Sep 2017 11:01:02 +0000 (UTC), NikoKrause wrote:

> For me it looks like this on Cinnamon 3.4 with Mint-X theme:
>
![screenshot-cinnamon-2017-09-15-125659](https://user-images.githubusercontent.com/8415124/30479418-68e0cf62-9a15-11e7-9a5d-6f9ef74a99a1.png)
>
> Is your applet up to date? Right click on applet, open `About ...`
dialog, it should say:

**Comment by NikoKrause** [comment]
It's a themeing issue. You can report this to the theme maintainer. Maybe he/she fixes it.
