### ISSUE TITLE
Feature request: make the 'recent documents' applet more useful by adding 'open containing folder'

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-spices-applets#1026]
The 'recent documents' applet - which, I believe, is built into Cinnamon - does not enable one to open the folder containing a recent document. That feature is available in, for instance, the Firefox download window - and it is very useful.

**Comment by jaszhix** [comment]
Since that applet is inside the Cinnamon repository, this issue should be [opened there](https://github.com/linuxmint/Cinnamon/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20recent%20documents).
