### ISSUE TITLE
Updating applets to latest version automatically

### ISSUE THREAD

**Issue by mcarans** [linuxmint/cinnamon-spices-applets#1034]
I am sorry if this is obvious, but applets do not seem to automatically update when new versions come out. Is it an option I have to set somewhere or is it the case that once you have installed an applet through the built in applet browser, you have to uninstall and reinstall the applet (thus losing your settings)?

**Comment by jaszhix** [comment]
This shouldn't be changed within the spices applets, but Cinnamon controls this. Please open an issue there.
