### ISSUE TITLE
Icing Task Manager: Show version number in About menu

### ISSUE THREAD

**Issue by mcarans** [linuxmint/cinnamon-spices-applets#1035]
@jaszhix 

[Issue]: <> 
The About menu of Icing Task Manager should contain the current version number. At the moment it says: 2017-07-07 08:25:06 UTC which doesn't help much as when I updated from an older version the date did not change.

**Comment by jaszhix** [comment]
They changed this in Cinnamon. Please open an issue there.

**Comment by mcarans** [comment]
I have done that here: https://github.com/linuxmint/Cinnamon/issues/6705
