### ISSUE TITLE
[multicore-sys-monitor@ccadeptic23] Add panel size responsiveness: vertical centering, scaling

### ISSUE THREAD

**Issue by BBric** [linuxmint/cinnamon-spices-applets#104]
When the height is less than the panel's height, the applet stays anchored to the top. 
A vertical centering would be more interesting.

**Comment by NikoKrause** [comment]
Please notify the author. @ccadeptic23

**Comment by NikoKrause** [comment]
The new author now is @jaszhix

**Comment by BBric** [comment]
A refresh rate per tab could be interesting too, per instance 0.8s for cpu, 5.0s for memory etc.
