### ISSUE TITLE
[ShutdownApplet@DeathMD/ShutdownApplet@shelley] dbus commands of the two ShutdownApplets don't work 

### ISSUE THREAD

**Issue by solarjoe** [linuxmint/cinnamon-spices-applets#1053]
@DeathMD
@shelley

Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
Cinnamon 3.0.7

[Issue]: 
Some of the dbus commands do not seem to work, e.g.
the suspend command

`dbus-send --print-reply --system --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Suspend`

executed in the applets as

`Util.spawnCommandLine("dbus-send --print-reply --system --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Suspend");`

When I run 

`dbus-send --print-reply --system --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Suspend`

in the terminal I get the following message

> Error org.freedesktop.DBus.Error.UnknownMethod: No such method 'Suspend'

[This thread](https://askubuntu.com/a/780990) says that the command has changed with systemd to

`systemctl suspend`

**Comment by solarjoe** [comment]
> because UPower 
> has been superseded by Systemd.Logind. So the fix I found is to make the 
> following call instead:

```
dbus-send --print-reply --system --dest=org.freedesktop.login1 \
    /org/freedesktop/login1 org.freedesktop.login1.Manager.Suspend \
    boolean:true
```


https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=729659#24

https://tanguy.ortolo.eu/blog/article130/sudo-pm-suspend#c1421030528-1

**Comment by icarter09** [comment]
@smurphos Thanks for the heads up! I didn't realize the ticket was addressing both applets. I just pushed a PR that should fix the other shutdown applet as well.
