### ISSUE TITLE
The inbuilt launcher applet silently replaces user-choosen icons with icons from current them

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-spices-applets#1055]
**What happens / to reproduce**: add an instance of the launcher applet to the panel; chose an icon for that instance - an icon not in the current icon theme; see what happens.

**What should happen:** _either_ the user should be told the chosen icon has been rejected _or_ the chosen icon should be accepted _or_ (best?) the user should be told the chosen icon is not in the theme but offered the option to use it anyway.

Cinnamon: 3.4.4.

**Comment by jaszhix** [comment]
Issues opened for any applets included with Cinnamon should be opened on the [Cinnamon repository](https://github.com/linuxmint/Cinnamon/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20launcher).
