### ISSUE TITLE
Inbuilt launcher applet's launch-in-terminal option does not honour the terminal chosen in Preferred Applications

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-spices-applets#1056]
Mint 18.2.
Cinnamon 3.4.4

To see/reproduce: set the Preferred terminal to something other than Gnome; create a launcher; tell the launcher to use the terminal; run the launcher.

I imagine that this irritation would be simple to fix.

**Comment by jaszhix** [comment]
Issues opened for any applets included with Cinnamon should be opened on the [Cinnamon repository](https://github.com/linuxmint/Cinnamon/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20launcher).
