### ISSUE TITLE
Mailnag (mailnagapplet@ozderya.net) - Issues with translation

### ISSUE THREAD

**Issue by Gena95** [linuxmint/cinnamon-spices-applets#1062]
Hello! Can anyone help me with translation trouble Cinnamon Mailnag Applet?

I have an issue. I fully translated Mailnag but some strings in applet remained untranslated. Such as "Configure Mailnag", "No unreaded mails" etc. But I translated this string in my .po file and .mo file was generated. Can you tell my why this happaned?
I think this is a bug. I heard that @NikoKrause might help me:)

Sorry fo my bad english:)

**Comment by NikoKrause** [comment]
Can you describe the steps you did? And add some screenshots?

**Comment by Gena95** [comment]
I'm very sorry! I restarted Cinnamon and translation applied fully:)
