### ISSUE TITLE
Icing Task Manager: Constant refresh

### ISSUE THREAD

**Issue by aberts10** [linuxmint/cinnamon-spices-applets#110]
[Have you read the guidelines for contributing?]: <> (Before opening an issue, please read the guidelines for contributing linked above. Else the issue will be closed. Also don't forget to notify the author.)
@AppletAuthor

[Issue]: <> (Describe your issue below.)
I am using antergos linux with cinnamon 
3.2.8 and cinnamon was hanging and slowing down drastically after installing this applet and i odly couldn't access the right click menu for icing... I restarted cinnamon and then decided to enable the setting "titles" in the applet, and thats when i noticed that the panel was refreshing constantly which in turn also caused the right click menu to stop functioning.

**Comment by jaszhix** [comment]
I need some more info so I can try to reproduce it.

  - Cinnamon version
  - Extension version
  - Linux distribution
  - Pastbin the outputs of:
    - ~/.cinnamon/configs/IcingTaskManager@json/*.json
    - ~/.cinnamon/glass.log
    - ~/.xsession-errors

**Comment by JosephMcc** [comment]
Keep in mind I believe we have logging to glass.log disabled by default. You can enable it Cinnamon settings->General

**Comment by collinss** [comment]
@JosephMcc No, we changed the default to true a while back. I can't remember which version, but the default is true for 3.2, and I'm pretty sure it was the case for at least 2 or 3 versions prior to that as well.

**Comment by JosephMcc** [comment]
Ah, ok. I missed that. I always had it enabled and never really run the official release version.

**Comment by aberts10** [comment]
http://pastebin.com/D1hC1adS - cinnamon glass log
http://pastebin.com/PuAftsLN - json settings for icingtaskmanager

[xsession_errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/769523/xsession_errors.txt)

**Comment by aberts10** [comment]
I am going to have to restart cinnamon now after starting icing task manager, Cinnamon is using 7% - 11% cpu according to gnome's system monitor... And the system is quite laggy, essentially unusable.

**Comment by jaszhix** [comment]
I reproduced it, and the label errors happen when the title display option is not "None". If you switch it to none in the interim of a fix, it will probably help. I would also suggest removing/disabling the classicMenu applet, its not initializing correctly. I'm seeing other St errors related to ```get_theme_node```, so I'll be looking at it.

**Comment by jaszhix** [comment]
The freezing context menu issue has been addressed - can you test this version and see if it helps? Extract it to ```~/.local/share/cinnamon/applets/IcingTaskManager@json/```, and overwrite the files.

[ITM-dist-1486959003675.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/770070/ITM-dist-1486959003675.zip)

**Comment by jaszhix** [comment]
By the way, I'm seeing a lot of errors in your .xsession-errors files I've never seen before, and from libs ITM doesn't use. So I wouldn't immediately pin Cinnamon's performance issues on ITM.

**Comment by aberts10** [comment]
Much better, Cinnamon is running fine, Though i did restart it after adding the applet and configuring it (couldv'e helped) ... When i first added it cinnamon starting spiking up in cpu usuage, but the system wasn't unresponsive like last time, the labels weren't refreshing constantly on the taskbar, and after the restart the cpu usuage for cinnamon went down and is back to normal levels.

**Comment by aberts10** [comment]
After testing this version of Icing Task Manager, While it does fix the issue that i had, I've noticed two new ones. One is that i cannot add programs to the panel, Instead it enables the default cinnamon launcher applet. Second is that Spotify does not show in the list, When opening it, it will quickly display a question mark icon with "Unkown" and then disappear, Though i can still access spotify using Alt + Tab.

**Comment by jaszhix** [comment]
@aberts10  Weird. I'll try to track those issues down. Thanks.

**Comment by aberts10** [comment]
@jaszhix I have further information on the refreshing issue, and spotify. Appearently after messing around i managed to get spotify listed on the panel using IcingTaskManager, But if it is running it would not show most of the time, It would simply show the pinned icon, And when it did show spotify as active with the window and all, The refresh issue would come back, And it would only list one instance in the window preview and number count, Even if you had two or more running.

**Comment by jaszhix** [comment]
@aberts10 Spotify and LibreOffice currently have workarounds applied to them, so they show anything at all. There is already an [issue](https://github.com/jaszhix/icingtaskmanager/issues/97) open for this regarding LibreOffice, but it applies to Spotify as well - so I don't want to group that into this issue of freezing menus.

**Comment by jaszhix** [comment]
>> i cannot add programs to the panel, Instead it enables the default cinnamon launcher applet

I'm not reproducing this. Adding apps from the menu pins them in ITM. I'm not using the panel launcher applet though, and I think only one applet can use the panel launcher role.
