### ISSUE TITLE
redshift@marvel4u Spanish translation

### ISSUE THREAD

**Issue by Martin1887** [linuxmint/cinnamon-spices-applets#1102]
I want to contribute providing Spanish translations. Below are all labels in format 'English: Spanish', could you please add this translations to po files? Thanks in advance.

Settings for Redshift applet: Ajustes para el applet Redshift
Enabled: Activado
Brightness: Brillo
Redshift Day colour temperature: Temperatura de color durante el día
Redshift Day Brightness: Brillo de Redshift durante el día
Change temperature colour between day and night: Cambiar temperatura de color entre el día y la noche
Redshift Night colour temperature: Temperatura de color durante la noche
Redshift Night Brightness: Brillo de Redshift durante la noche
Latitude: Latitud
Longitude: Longitud
If not entered Redshift would use GeoClue2 provider: Si no se introduce Redshift usará el proveedor GeoClue 2
Redshift colour: Color de Redshift
Redshift brighness: Brillo de Redshift
Change on night: Cambiar de noche
Redshift night colour: Color de Redshift por la noche
Redshift night brightness: Brillo de Redshift por la noche

**Comment by NikoKrause** [comment]
Please use the applications poedit.
Open the .pot file and translate it with poedit. It'll create a .po while, which you can create a pull request for.

**Comment by Martin1887** [comment]
Ok, I will do it when @Marvel4U accepts pull request and he add the new labels to pot file.
