### ISSUE TITLE
"Desktop capture" applet not more available after upgrade to Cinnamon 3.4.4

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-applets#1104]
Hi. I use Fedora 24 X64 Cinnamon edition & already installed a an applet called "Desktop capture".

Yesterday, I upgraded my Fedora to Fedora 26 x64 & as a result my Cinnamon upgraded to 3.4.4

After launched loptop, I received error message: Cinnamon start O.K but one of applet fail to start ! Uninstall it or contact developer"

I investigated this & discovered that Desktop capture applet now not working ! It is now incompatible with Cinnamon version.

But I tried to find it in applet site, but it never appeared to me on searching this site !! & for that this thread have not UUID & other name. 

Please do not delete this issue before investigating it.  What have been happened to this applet ?

Best.

**Comment by NikoKrause** [comment]
The author of this applet has deleted it from the cinnamon spices repo.
You can find the newest version of the applet here https://github.com/rjanja/desktop-capture
Installation instructions are in the README

**Comment by Nokia808** [comment]
Thank you very much. It working. Sorry for delay in response.

Best.
