### ISSUE TITLE
feeds@jonbrettdev.wordpress.com : Not working in linux mint 18.2 

### ISSUE THREAD

**Issue by MuhmdRaouf** [linuxmint/cinnamon-spices-applets#1110]
- Distribution: Distributor ID: LinuxMint,  Description: Linux Mint 18.2 Sonya, Release: 18.2, Codename: Sonya
- Cinnamon version: Cinnamon 3.4.4
- Applet version :     "version": 0.28,     "last-edited": 1501117807,
- ~/.cinnamon/glass.log : https://pastebin.com/pEkPjVas
- ~/.xsession-errors : https://pastebin.com/DMLjyW3V
Issue: this applet used to work when in run Mint 18.1 and kept working even after updating to the newer version Min 18.2, I have made fresh install of Mint 18.2 and the applet doesn't work now anymore on Mint 18.2, I tried to installed in VM to double check it's the (http://imgur.com/a/ciw37) still no luck, so maybe the maintainers could do any thing about it, one more thing the Manage feed button not working though, I can't add or remove or manage any thing at all, Thanks in advance.

**Comment by two-dogs** [comment]
System:    Host: linux-fcke Kernel: 4.11.8-2-default x86_64 bits: 64 Desktop: Cinnamon 3.4.4            Distro: openSUSE Tumbleweed 2017073

installed https://cinnamon-spices.linuxmint.com/applets/view/149 via dowloaded https://cinnamon-spices.linuxmint.com/files/applets/feeds@jonbrettdev.wordpress.com.zip
and added the two https://git.io/v72qE prerequisites called from https://cinnamon-spices.linuxmint.com/applets/view/149

got exactly same results as MuhmdRaouf

**Comment by NikoKrause** [comment]
@jake1164

**Comment by jake1164** [comment]
I will have to look at it this weekend.

**Comment by jake1164** [comment]
I pushed an update this morning, let me know if you still have any issues.

**Comment by MuhmdRaouf** [comment]
@jake1164 Works like a charm mate, thanks a lot
