### ISSUE TITLE
brightness-and-gamma-applet@cardsurf: can you kindly make lower limit 20 not 30 ?

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-applets#1112]
brightness-and-gamma-applet@cardsurf

Hi. I have suggestion to make lower limit value 20 not 30.
I'm on Fedora 26 X64 bit Cinnamon edition.
Best.

**Comment by NikoKrause** [comment]
@cardsurf

**Comment by cardsurf** [comment]
@Nokia808 
To change the lower limits from 30% to 20%:
1. Right click on the applet and select `Configure`
3. Set the following values:
* Minimum brightness: 20%
* Minimum gamma: 20%
