### ISSUE TITLE
weather@mockturtl: Open Applet Settings on Applet Click if No Weather ID is Set

### ISSUE THREAD

**Issue by feren** [linuxmint/cinnamon-spices-applets#1129]
This is a Feature Request for @mockturtl 's Weather Applet, that'd make it less confusing for the beginner users who may be wondering why the Applet is Refreshing and isn't telling the Weather at all when they don't realize it's because it's not configured.

Basically, it would be nice if, when NO Location is set, when clicking on Weather to open it, instead of opening, it would be handy for it to instead open up its Applet Settings Window, or at least say something about the fact it's not Configured and must be Configured through Settings first...

**Comment by icarter09** [comment]
@Gr3q

**Comment by Gr3q** [comment]
We obtain location automatically with default settings, so this is no longer an issue for new users.

Also, now the applet label will say if no location is set, and the popup menu explains it with a little  bit more detail.
![image](https://user-images.githubusercontent.com/22377521/75630037-21bb9e80-5bdf-11ea-8f79-24418a450910.png)
