### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: Unable to show on multiple panels

### ISSUE THREAD

**Issue by pinealan** [linuxmint/cinnamon-spices-applets#1161]
- Linux Mint 18.2 Sonya
 - Cinnamon 3.4.4
 - Applet 1.6.0

I have a dual monitor setup with a bottom panel on each monitor. The applet works perfectly on all workspaces and my main monitor, but I can't find a way to add/show it on my other monitor's panel.

If this simply is an unimplemented feature, I don't mind contributing as long as someone gives me a pointer or two.

**Comment by NikoKrause** [comment]
I don't have a second monitor, but have you tried to right click on the panel, which you want to have the applet in, and select `Add applet to panel`. In the settings, which open choose the applet and add it. ?

**Comment by pinealan** [comment]
Yes I have tried. In the Applets menu that pops up after I `Add applet to panel`, there is no option for `Add to panel` when I right click on Multi-Core System Monitor. The same is not true for some other applets such as the Icing Task Manager, Calendar, or Menu, of which I can add multiple instances onto even the same panel.

**Comment by NikoKrause** [comment]
I looked at the code. You can have only one instance of this applet.

Some apps have issues, when you allow them to add more than one instance. I'm not sure if it's one of those applets.

The author of this applet is @jaszhix, he surely knows it.

**Comment by jaszhix** [comment]
Yeah, it doesn't have the ```max-instances``` property set in metadata.info. The applet makes use of libraries that are a bit on the heavier side, so I am reluctant to make it available for multiple panels. Its doing a lot for just one instance, it is gathering system info and updating four graphs in real-time. I would say this isn't likely to happen until I get more refactoring done, and fix some [usability issues](https://github.com/linuxmint/cinnamon-spices-applets/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20multicore).

**Comment by jaszhix** [comment]
I'm going to skip this for now because the applet is a little CPU demanding since it runs a series of functions on a timer indefinitely. If more people become interested in this feature, I can re-open this and consider it again.
