### ISSUE TITLE
SpicesWebsite - Can we add a Downloaded (or maybe Installed) statistic like other app stores

### ISSUE THREAD

**Issue by jake1164** [linuxmint/cinnamon-spices-applets#117]
In order to help users decide if they want to install an spice, can an additional statistic be added to count the number of downloads / installs.  Also Instead of # of stars it would perhaps be a better indication and fairer representation to do # of stars.

For instance an spice with 4 stars and 40 downloads vs 4 stars and 40,000 downloads would give users a better idea of an spices's quality than # of likes.  

I understand this is more than an applet or website request but I am not sure where those types of issues should be posted.

**Comment by NikoKrause** [comment]
I think there's something planned to use something different than stars.

But you should file this issue here
https://github.com/clefebvre/cinnamon-spices/issues

**Comment by collinss** [comment]
@jake1164 the problem with number of stars is that you have to have an account with the spices website to rate. This means that a relatively small number of people are actually rating them. Also, having any sort of ranking system like that means that any new applet that might be better gets buried under the older applets that have accumulated stars over a much longer period of time. These have been problems for quite a while. Using social media to track recent likes solves both of those issues. In the end, I think it will be much more helpful than the stars ever will be.

Downloads would be good, though.

**Comment by collinss** [comment]
@NikoKrause beat me by a few seconds!
