### ISSUE TITLE
redshift@marvel4u: Settings broken

### ISSUE THREAD

**Issue by Martin1887** [linuxmint/cinnamon-spices-applets#1183]
I have noticed that settings have been broken in my system. It is strange because nothing has changed in relation with configuration and JSON files are correct (metadata and installed settings). In glass.log a settings successful installation is also written.

However, I had two settings files, and settings didn't refresh the applet values. After deleting them, only one file is created but when configuration window is open Cinnamon is restarted.

Maybe it is due to Cinnamon update in Fedora. @Marvel4U, @jaszhix, could you check if settings work well in your systems?

Thanks and regards.

**Comment by Martin1887** [comment]
I have revised settings-schema history and nothing has changed in this file. Maybe a change in applet.js could break settings, but it does not seem to be the problem.

My version of Cinnamon is 3.4.6-3.

@Marvel4U, @jaszhix, could you check if settings work well in your systems? If it does, maybe should we report a bug to Cinnamon team?


Thanks and regards.

**Comment by jaszhix** [comment]
The settings appear to work when changed from the applet's menu, but this happens when trying to open it with xlet settings:

```
~ $ /usr/share/cinnamon/cinnamon-settings/xlet-settings.py applet redshift@marvel4u
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 113, in _on_proxy_ready
    proxy.highlightXlet('(ssb)', self.uuid, self.selected_instance["id"], True)
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 415, in quit
    proxy.highlightXlet('(ssb)', self.uuid, self.selected_instance["id"], False)
TypeError: 'NoneType' object is not subscriptable
```

It just opens an empty window. Of course I'm on the git version of Cinnamon, and xlet-settings has been changed a lot compared to what's on v3.4.x. I think if its not working on either, it might have something to do with the applet config. I'll see if I can find anything later.

**Comment by Martin1887** [comment]
Any updates about this issue?

I have inspected the applet.js changes and nothing has changed about settings. I have also tried to change settings in the settings file and it works well, updating applet values.

The only thing that does not work is the rendering of the settings in applet settings window, and I don't figure why.

The only possible options I find are:

- Something has changed since Cinnamon 3.4.6 in xlet-settings.
- Something is missing in pot files.

I have recreated pot file and Spanish po file and the problem persists.

That NoneType error in xlet-settings is really strange. Maybe any attribute has been made required and before it was optional?


Thanks and regards.

**Comment by jaszhix** [comment]
I'm not sure, maybe @collinss has a better idea, since he rewrote a fair bit of it on Cinnamon git. I'm thinking its something in applet.js though.

**Comment by Martin1887** [comment]
Good and bad news. I have just try to remove panelHeight param in applet invocation and settings issue has been fixed.

I have never though that this could break settings... I will investigate and try to fix this issue.


Thanks and regards.

**Comment by Martin1887** [comment]
Really curious... removing panelHeight parameter creates 68.json file. If this file is not removed and panelHeight parameter is again inserted, 25.json file is again created and 68.json and 25.json exist.

However, settings are strangely binded to 68.json instead 25.json: changes in applet settings are reflected in 25.json but panel configuration settings window shows 68.json. If 68.json is removed, then settings window is empty.

This seems really strange to me, have you any idea why settings file has changed but settings window remains binded to old JSON configuration file?


Thanks and regards.

**Comment by Martin1887** [comment]
Sorry, my mistake.

I have noticed that panelHeight parameter was missing in two lines of applet.js I'm going to do a pull request and close this issue now.
