### ISSUE TITLE
CinnVIIStarkMenu@NikoKrause "run_with_nvidia_gpu" broken

### ISSUE THREAD

**Issue by berturion** [linuxmint/cinnamon-spices-applets#1210]
# CinnVIIStarkMenu@NikoKrause menu@cinnamon.org "run_with_nvidia_gpu" broken

 * menu@cinnamon.org
 * Cinnamon 3.4.4
 * Antergos, kernel 4.12.8-2-ARCH
 * Intel/Nvidia GT630M with Bumblebee (optirun + primusrun) with driver package nvidia-dkms 384.59-5

**Notify author of applet**
@Alan01 @NikoKrause 

**Issue**
In Cinnamon main menu, when `optirun` is installed on the system, users have an option to launch any app with the GPU using the right click and selecting "Run with NVidia GPU".
This option launch the command:

    optirun gtk-launch %program%

But this command doesn't do anything. In fact, trying to launch `retroarch`, using this option, nothing happens. Process monitor doesn't show any retroarch process.
I tried to run manually this command and it doesn't work neither.
But, `gtk-launch retroarch` works.

**Steps to reproduce**
Right click on an application in the cinnamon main menu, click on "Run with NVidia GPU".

**Expected behaviour**
Runs the selected program with NVida GPU.

**Other information**
...

**Comment by berturion** [comment]
[journalctl.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/1272388/journalctl.txt)
Logs to help diagnose the problem. It is probably a problem with Bumblebee itself on this kernel... Not sure thow.

**Comment by NikoKrause** [comment]
I guess it doesn't work with the default Cinnamon menu as well as with CinnVIIStarkMenu.
I use the same code in CinnVIIStarkMenu as the default menu.
I can't help with this issue, because I don't have an Intel/NVidia GPU with bumblebee.

Since this is an upstream issue, you report it better here: https://github.com/linuxmint/Cinnamon

**Comment by pdcurtis** [comment]
I have an Intel/NVidia GPU with bumblebee and the bumblebee@pdcurtis applet installed so I can see when bumblebee is activated.
I can confirm that it works the same with the default Cinnamon menu as well as with CinnVIIStarkMenu.

The following are after a cinnamon restart and in terminal
`optirun xed` runs xed with bumblebee enabled until the program is closed
`optirun gtk-launch xed` runs xed - bumblebee is enabled for a few seconds only but xed continues to run

Using CinnVIIStarkMenu and `Run with Nvidia GPU` - bumblebee is enabled for a few seconds only but xed continues to run as in a terminal.
Using Menu and `Run with Nvidia GPU` - bumblebee is usually enabled for a few seconds only but xed always continues to run as in a terminal.

I also tried a couple of more complex programs and 
CinnVIIStarkMenu with `Run with Nvidia GPU` and firefox caused a segfault every time I tried.
CinnVIIStarkMenu with `Run with Nvidia GPU` and vlc was not run but
    `optirun vlc` in a terminal ran with bumblebee enabled

A little confusing but I agree with @NikoKrause that this is not an issue with CinnVIIStarkMenu alone and suggest this is closed after @berturion transfers it to https://github.com/linuxmint/Cinnamon or wherever is appropriate.

For reference `inxi -F && dmesg | grep -i seg`
System:    Host: defiant Kernel: 4.4.0-21-generic x86_64 (64 bit) Desktop: Cinnamon 3.4.6
           Distro: Linux Mint 18.2 Sonya
Machine:   System: Notebook (portable) product: W230ST
           Mobo: Notebook model: W230ST Bios: American Megatrends v: 4.6.5 date: 11/18/2013
CPU:       Quad core Intel Core i7-4700MQ (-HT-MCP-) cache: 6144 KB 
           clock speeds: max: 3400 MHz 1: 2399 MHz 2: 2399 MHz 3: 2400 MHz 4: 2627 MHz 5: 2538 MHz 6: 2457 MHz
           7: 2400 MHz 8: 2400 MHz
Graphics:  Card-1: Intel 4th Gen Core Processor Integrated Graphics Controller
           Card-2: NVIDIA GK106M [GeForce GTX 765M]
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa) Resolution: 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel Haswell Mobile GLX Version: 3.0 Mesa 11.2.0
Audio:     Card-1 Intel 8 Series/C220 Series High Definition Audio Controller driver: snd_hda_intel
           Card-2 Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.4.0-21-generic
Network:   Card-1: Intel Centrino Advanced-N 6235 driver: iwlwifi
           IF: wlp3s0 state: up mac: c4:d9:87:0a:df:a2
           Card-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller driver: r8169
           IF: enp4s0f1 state: down mac: 00:90:f5:f7:1d:5b
Drives:    HDD Total Size: 1000.2GB (59.5% used) ID-1: /dev/sda model: ST1000LM014 size: 1000.2GB
Partition: ID-1: / size: 39G used: 9.3G (25%) fs: ext4 dev: /dev/sda6
           ID-2: /home size: 193G used: 46G (25%) fs: ext3 dev: /dev/sda7
           ID-3: swap-1 size: 16.78GB used: 0.00GB (0%) fs: swap dev: /dev/sda3
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 62.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 293 Uptime: 4 days Memory: 3206.1/7903.7MB Client: Shell (bash) inxi: 2.2.35 
[    0.156305] acpi PNP0A08:00: _OSC: OS supports [ExtendedConfig ASPM ClockPM Segments MSI]
[362899.876458] firefox[2770]: segfault at 0 ip 00007fefdb4269b9 sp 00007ffd5286fe48 error 6 in libxul.so[7fefd8c21000+4066000]
[362973.075545] firefox[5301]: segfault at 0 ip 00007f72cbd269b9 sp 00007ffc520cb0b8 error 6 in libxul.so[7f72c9521000+4066000]
[389204.297306] firefox[18791]: segfault at 0 ip 00007f994a9269b9 sp 00007fff57091c28 error 6 in libxul.so[7f9948121000+4066000]
[389339.851732] firefox[23053]: segfault at 0 ip 00007f2a253269b9 sp 00007ffd8e9b96e8 error 6 in libxul.so[7f2a22b21000+4066000]
[389376.359552] firefox[24211]: segfault at 0 ip 00007f81fe4269b9 sp 00007ffd2a5c9058 error 6 in libxul.so[7f81fbc21000+4066000]
[389647.117577] firefox[491]: segfault at 0 ip 00007f1e3d0269b9 sp 00007ffe291fee78 error 6 in libxul.so[7f1e3a821000+4066000]
[389686.524454] firefox[1744]: segfault at 0 ip 00007f6ddf5269b9 sp 00007ffcc6578c98 error 6 in libxul.so[7f6ddcd21000+4066000]

**Comment by berturion** [comment]
Hello, ok.
You are right, the problem it seems to be only with retroarch program. And the problem is not directly with CinnVIIStarkMenu.
I  close this issue. I will post it on retroarch.
Sorry for having bothered you.
And thanks for your support.
