### ISSUE TITLE
[axos88@countdown-timer] Icon does not scale with panel size

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#1223]
```
 * Applet version/Build date: 2017-07-26
 * Cinnamon version: 3.4.6
 * Distribution: Mint 18.2

 ```

**Notify author of applet**
@axos88

**Issue**
The applet's icon does not scale if the panel size is increased.

**Steps to reproduce**
Increase the panel size. The icon is not increased.

**Expected behaviour**
The icon's size should follow the panel's size.

**Other information**

- redshift@marvel4u had the same or similar problem: #1128.
- location-detection@heimdall has the same or similar problem: #1222

**Comment by axos88** [comment]
Sorry, I'm not using linux mint anymore, and i'm not maintaining this project. If you submit a pr, i can take a look, or if you are interested, you can take over the project.
