### ISSUE TITLE
windowlist@cobinja.de: Some apps aren't displayed

### ISSUE THREAD

**Issue by tabakowy** [linuxmint/cinnamon-spices-applets#1230]
```
 * Version: 1501240207
 * Cinnamon 3.4.6
 * Mint 18.2
 ```

**Notify author of applet**
@Cobinja

**Issue**
Spotify app isn't displayed on window list. I've noticed the same bug for Libre Office documents launched from Nemo.

**Steps to reproduce**
Run Spotify from menu or console.

**Comment by Cobinja** [comment]
This was already reported in https://github.com/Cobinja/CobiWindowList/issues/3
Will be fixed in the next version
