### ISSUE TITLE
[commandLauncher@scollins] notification with error

### ISSUE THREAD

**Issue by cardsurf** [linuxmint/cinnamon-spices-applets#1234]
**Author**
@collinss 

**Operating system**
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya

**Description**
After a successfull execution of a command there is a notification with error:

![ls](https://user-images.githubusercontent.com/3139729/30282754-7f22ea3c-9716-11e7-8ae2-360b75f78f8d.png)

**Details**
The bug is caused by passing `null` as the function parameter to `GLib.child_watch_add `function:
`GLib.child_watch_add(pid, Lang.bind(this, this.onClosed), null);`
A possible solution is to pass the priority parameter to `GLib.child_watch_add `function:
`GLib.child_watch_add(GLib.PRIORITY_DEFAULT_IDLE, pid, Lang.bind(this, this.onClosed));`

**Steps to reproduce**
1. Set a command to `ls`
2. Click on the applet to run the command

**Expected result**
The command executes successfully and the are no notifications with errors.

**Actual result**
The command executes successfully and there is a notification with error.

**Comment by collinss** [comment]
Not sure why it stopped working. All the documentation and code points to the function in question working the way it was already written in my applet, but I changed it anyway, and it seemed to fix the issue.

**Comment by cardsurf** [comment]
Signatures of `GLib.child_watch_add` function are different in [Gjs](https://wiki.gnome.org/Projects/Gjs) and in [GLib C library](https://developer.gnome.org/glib/). In Gjs `function` is declared as the [3rd parameter](https://people.gnome.org/~gcampagna/docs/GLib-2.0/GLib.child_watch_add.html) and in GLib C library as the [2nd parameter](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-child-watch-add).
