### ISSUE TITLE
betterlock: Notification not appear in screen when using full screen mode !

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-applets#125]
@entelechy

Hi. Today I noticed that notification of this applet not appear if I use full screen mode of program:

- I open GIMP
- switch GIMP to full screen mode
- start to activate/deactivate CapLock/NumLuck
I did not saw notification appearing no screen.

I repeat test on LibreOffice & firefox got same result.

There is important note: I'm already activated "sound effect" for "show notification" from control of Cinnamon. When I switch to full screen mode notification not appear on screen but I still hear sound effect of show notification each time I activated/deactivated CapLock/NumbLock key !

I'm on Cinnamon version 3.2.8

Issue always existing.

If I switch back to non-full screen mode, notification will reappear in screen.

**Comment by JosephMcc** [comment]
This isn't a bug in the applet. It's the way cinnamon handles fullscreen notifications. Hiding notifications when fullscreen is intentional at the moment. Playing the sound effect when they don't show probably shouldn't happen though. 

https://github.com/linuxmint/Cinnamon/issues/1646
