### ISSUE TITLE
radio@driglu4it: Show, which radio station is playing right now

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/cinnamon-spices-applets#1258]
```
 * Build date: 2017-08-03 17:45 UTC
 * Cinnamon version: 3.4.6
 * Distribution - Linux Mint 18.2
 ```

**Notify author of applet**
@driglu4it

**Feature request**
Show which radio station is playing right now, e.g. with a dot.

**Other information**
The dot can be similar like in the network applet it's showing, which network you are connected to. Or like the keyboard applet is showing, which keyboard language is selected right now:
![screenshot-cinnamon-2017-09-16-012850](https://user-images.githubusercontent.com/8415124/30506709-706f051e-9a7e-11e7-8787-20ba7854f001.png)

**Comment by Driglu4it** [comment]
Hello, it's fine idea! I want to try do it!

**Comment by NikoKrause** [comment]
@Driglu4it 
You're using `radio` as applet icon. There are some themes, which don't have any `radio.png` icons, e.g.  Adwaita.

Set your icon theme to Adwaita and restart Cinnamon. The applet is in the panel, but without any icon.
