### ISSUE TITLE
sessionManager@scollins: suspend problem with systemd

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-spices-applets#127]
@collinss: I use and enjoy this applet a long time, but since LM 18.0 (introducing systemd) suspend is broken (may be hibernate also).

It seems to be that
```
    suspend: function() {
        if ( has_upower ) Util.spawnCommandLine("dbus-send --print-reply --system --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Suspend");
        else if ( has_systemd ) Util.spawnCommandLine("systemctl suspend");
    },
```
uses has_upower instead of has_systemd, because when I just use the systemd part it works.
The upower part in command line gives
`org.freedesktop.DBus.Error.UnknownMethod: no such method »Suspend«`

**Comment by collinss** [comment]
I'll look into to it. I don't use suspend or hibernate much right now, which is probably why I didn't notice this before.

**Comment by collinss** [comment]
I just pushed some changes which should fix this issue. Let me know if you're still having problems.

**Comment by Mintulix** [comment]
Thanks a lot, Stephen, for this and all the other stuff you do. Works now like it should.
I testet all systemd actions but sleep and hibernate (not available for my notebook).
