### ISSUE TITLE
force-quit@cinnamon.org: Does not work in Manjaro/Arch

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/cinnamon-spices-applets#1294]
**Issue**
@fixer1234 says:
> [The applet works in Mint but not Manjaro.](https://cinnamon-spices.linuxmint.com/applets/view/4)

@fixer1234
This applet uses the `xkill` command. I guess it's not installed in Arch/Manjaro by default.

Can you install it and try if it works?

**Comment by SamBurgos** [comment]
Apologies if this issue is no longer relevant, in the case of Archlinux/Manjaro/Any Arch derivative, the package is named "xorg-xkill", once you install this package the applet works as intended
