### ISSUE TITLE
windowlist@cobinja.de [FEATURE REQUEST] Add to Panel from Menu should pin it to "the Workspace" in Window List

### ISSUE THREAD

**Issue by feren** [linuxmint/cinnamon-spices-applets#1295]
@Cobinja 

IcingTaskManager has this feature, not sure if it's still broken though, but when using 'Add to Panel' in the menu, on Icing, it pins it using Icing's applet, rather than those App Shortcut Things, but sadly, with your applet, such integration is not yet achieved, can you please add such functionality, along with the ability to resize thumbnails, please?
Recap: 'Add to Panel' should mean the App gets pinned to CobiWindowList instead of spawning a Panel Launchers to pin it on.

**Comment by Cobinja** [comment]
I'll think about it.
In the meantime, you can already drag applications from the menu an drop them onto this applet (also from the builtin panel launcher applet).
