### ISSUE TITLE
[axos88@countdown-timer] Persistent timer?

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#1330]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") 2017-09-15
 * Cinnamon version (cinnamon --version): Cinnamon 3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 18.1

 ```

**Notify author of applet**
@axos88 

**Issue**
It would be great for the countdown timer to remember it's alarm setting across reboots.

**Steps to reproduce**
1. Set the timer to a longer interval.
2. Log out/log in or reboot the computer
3. The timer lost its "target" date and does not remind me at the specified time.

**Expected behaviour**
It would be great to have a persistence across log outs and reboots, so that the time where the message appears is not lost.

**Other information**
This is not a bug but a wish.

**Comment by jaszhix** [comment]
Just a heads up, axos88 indicated he is no longer maintaining this applet, and the author is set to `none` now.

**Comment by jake1164** [comment]
I Forked this timer to create a new applet named cinnamon-timer@jake1164 and it will be replacing this applet. 

I implemented this functionality that if you restart cinnamon or reboot Linux the timer will resume if the timer is has not expired. 

I few other notable improvements: 
- Display on a vertical panel.
- Moved the settings to the configuration panel
- Changed the audio to use the full path like other applets
- Clearing the timer will remove the notification
- Clicking the window prompt will clear the alarm.

**Comment by NikoKrause** [comment]
This applet has been removed. Please use the new (and improved) fork by @jake1164 instead.
https://cinnamon-spices.linuxmint.com/applets/view/302
