### ISSUE TITLE
[multicore-sys-monitor@ccadeptic23] Disk IO does not work

### ISSUE THREAD

**Issue by fluancefg** [linuxmint/cinnamon-spices-applets#1385]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

- v1.6.0

- `inxi -F && dmesg | grep -i error`
Resuming in non X mode: xdpyinfo not found. For package install advice run: inxi --recommends
System:    Host: archfg Kernel: 4.11.9-1-ARCH x86_64 bits: 64 Desktop: Cinnamon 3.4.4  Distro: Arch Linux
Machine:   Device: laptop System: LENOVO product: 20FBCTO1WW v: ThinkPad X1 Carbon 4th serial: N/A
           Mobo: LENOVO model: 20FBCTO1WW v: SDK0J40705 WIN serial: N/A
           UEFI: LENOVO v: N1FET38W (1.12 ) date: 03/30/2016
Battery    BAT0: charge: 48.2 Wh 98.3% condition: 49.0/52.3 Wh (94%)
CPU:       Dual core Intel Core i7-6600U (-HT-MCP-) cache: 4096 KB
           clock speeds: max: 3400 MHz 1: 1671 MHz 2: 1372 MHz 3: 1153 MHz 4: 1471 MHz
Graphics:  Card: Intel HD Graphics 520
           Display Server: N/A drivers: modesetting (unloaded: fbdev) tty size: 316x78
Audio:     Card Intel Sunrise Point-LP HD Audio driver: snd_hda_intel Sound: ALSA v: k4.11.9-1-ARCH
Network:   Card-1: Intel Ethernet Connection I219-LM driver: e1000e
           IF: enp0s31f6 state: down mac: 54:ee:75:9f:b5:5c
           Card-2: Intel Wireless 8260 driver: iwlwifi
           IF: wlp4s0 state: up mac: a4:34:d9:ff:69:5a
Drives:    HDD Total Size: 3024.6GB (6.1% used)
           ID-1: /dev/nvme0n1 model: SAMSUNG_MZSLW1T0HMLH size: 1024.2GB
           ID-2: USB /dev/sda model: My_Passport_0748 size: 2000.4GB
Partition: ID-1: / size: 20G used: 17G (88%) fs: ext4 dev: /dev/nvme0n1p2
           ID-2: /boot size: 511M used: 69M (14%) fs: vfat dev: /dev/nvme0n1p1
           ID-3: /home size: 919G used: 90G (11%) fs: ext4 dev: /dev/nvme0n1p3
Sensors:   System Temperatures: cpu: 49.0C mobo: N/A
           Fan Speeds (in rpm): cpu: 3219
Info:      Processes: 214 Uptime: 5:57 Memory: 12792.8/15919.6MB Init: systemd Client: Shell (bash) inxi: 2.3.40

- ~/.xsession-errors:
`(cinnamon:871): Cjs-WARNING **: JS ERROR: TypeError: _gsmApp is null`
`MyApplet.prototype._runSysMon@/home/fgos/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/applet.js:161:5`
`MyApplet.prototype.on_applet_clicked@/home/fgos/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/applet.js:165:5`
`Applet.prototype._onButtonPressEvent@/usr/share/cinnamon/js/ui/applet.js:282:21`

**Notify author of applet**
@jaszhix

**Issue**
Disk IO never displays any activity at all

**Steps to reproduce**
Nothing. Just start a session and the behaviour is always the same.

**Expected behaviour**
I should work ;-)

**Other information**

**Comment by jaszhix** [comment]
Are you sure you're not running the 3.2/3.0 versions of this applet? `_gsmApp` was renamed to `gnomeSystemMonitor` for brevity in the version I've been working on.

**Comment by fluancefg** [comment]
How can I confirm that ? If I list the content of the directory, it shows 3 different versions:
`ll .local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/`
`drwxr-xr-x 2 fgos fgos 4.0K  5 jun 09:45 3.0`
`drwxr-xr-x 2 fgos fgos 4.0K  5 jun 09:45 3.2`
`drwxr-xr-x 2 fgos fgos 4.0K 10 jun 04:35 3.4`

**Comment by jaszhix** [comment]
Okay, please update the applet then, there have been several updates since June 9th.

**Comment by jaszhix** [comment]
If you still have issues after testing the correct version, I will re-open.
