### ISSUE TITLE
All Applets - Installing Dependencies

### ISSUE THREAD

**Issue by jake1164** [linuxmint/cinnamon-spices-applets#1387]
General Question - Is there any provided standard way to install dependencies? 

For instance I have one applet that requires sox (sudo apt/dnf install sox)  and another that requires the python module feedparser (pip install feedparser).

**Comment by jaszhix** [comment]
I don't think there is. My applets all use gulp to watch the files and reload the extension on change. I just list the instructions to install it in the readme. For dependencies that are needed for the applet to run, its probably just a matter of ensuring the user can opt-in to installing them once the applet loads.

**Comment by NikoKrause** [comment]
There's no standard way. Problem is that Cinnamom is available for Ubuntu based, Arch, etc Distributions. 

You can check this applet:
https://cinnamon-spices.linuxmint.com/applets/view/204

It has a way to check with apt (works at least for Debian based distros)

**Comment by jake1164** [comment]
This can be marked as answered, however, this is a good example of a question that could be documented in the wiki if it was turned on.
