### ISSUE TITLE
[cinnamon-timer@jake1164] Make "Presets" configurable (again)

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#1409]
```
 * Applet version/Build date: 2017-10-13 20:06:51 UTC
 * Cinnamon version (cinnamon --version): 3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 18.2

 ```

**Notify author of applet**
@jake1164 Thank you for taking the timer under your wings!

**Issue**

In the version by @axos88, the Presets were configurable (well, by editing the configuration file). It looks like this setting has moved back into the `~.local/share/cinnamon/applets/cinnamon-timer@jake1164` directory and I guess this file will be overwritten with every update. Could you please make it configurable again via the configuration dialog (best option) or via a configuration file?

**See also**
#1408 Make "SliderIntervals" configurable (again)

**Comment by jake1164** [comment]
This has been added to v1.1.0.  

To configure right click on the applet and select configure to go into Cinnamon-Settings then select the 'Slider Intervals' tab.  Add / Delete / Modify the slider settings.  Once you make the change the settings will take effect.

**Comment by sphh** [comment]
Thanks!!!!
