### ISSUE TITLE
CinnVIIStarkMenu@NikoKrause some elements are not translated

### ISSUE THREAD

**Issue by spacy01** [linuxmint/cinnamon-spices-applets#1417]
```
* Applet version/Build date - Version: 1.11 / Date: 23-09-2017
 * Cinnamon version - 3.4.6 
 * Distribution - Linux Mint 17.2
 * Integrated Intel Video

 ```
@NikoKrause

**Issue**
The headers of the lists, contains apps and folders added in quicklauncher and the pop-up windows for add/edit elements in quicklauncher remain untranslated.

Untranslated strings a present in settings-schema.json, sections 'quicklauncher-places' and 'quicklauncher-apps'.

**Steps to reproduce**
Try to change the applet language, for instance - bulgarian, open settings > quicklauncher and try to add/edit element.

**Other information**
Screenshot
![2017-10-27 22-13-28](https://user-images.githubusercontent.com/1469262/32121463-5ab78efa-bb65-11e7-84e1-ab17f6fab3d0.png)

**Comment by NikoKrause** [comment]
Hey,

I noticed this too. It's a bug in Cinnamon itself. I fixed it a few weeks ago. The fix will be available in Cinnamon 3.6 (Linux Mint 18.3)

**Comment by NikoKrause** [comment]
That's the fix here https://github.com/linuxmint/Cinnamon/commit/94cf79f4155d1c0be99f7cd485b57c028350c404

**Comment by spacy01** [comment]
@NikoKrause, thank you, for the fix!
