### ISSUE TITLE
[tor-button@shatur] Can't launch application with pkexec

### ISSUE THREAD

**Issue by Goodevil95** [linuxmint/cinnamon-spices-applets#1418]
I'm developer of [this applet](https://github.com/linuxmint/cinnamon-spices-applets/tree/master/tor-button%40shatur) and I trying to make launching `tor` with `pkexec` (instead of `gksu`) by this command:
`GLib.spawn_command_line_async('pkexec -u tor tor');`
But auth message not showing. Can applets launch `pkexec`? I tried to launch `pkexec` with any programs. For example this don't work too:
`GLib.spawn_command_line_async('pkexec nemo');`
When I type in terminal `pkexec nemo`, auth message showing.

**Comment by NikoKrause** [comment]
Have a look at this applet here https://cinnamon-spices.linuxmint.com/applets/view/139

This seems to work using pkexec

**Comment by Goodevil95** [comment]
@NikoKrause Thank you for good example!

**Comment by NikoKrause** [comment]
You're welcome
