### ISSUE TITLE
multicore-sys-monitor@ccadeptic23 incompatibility with Cinnamon 3.6.0

### ISSUE THREAD

**Issue by BenjaminNavarro** [linuxmint/cinnamon-spices-applets#1430]
```
 * Applet version: 1.7.1
 * Cinnamon version (cinnamon --version): 3.6.0
 * Distribution - Arch
 * Graphics hardware *and* driver used: GTX1060 with nvidia driver (387.22)
 * Snippet or attachment of ~/.cinnamon/glass.log: https://pastebin.com/Six51MCQ
 * Snippet or attachment of ~/.xsession-errors: https://pastebin.com/mZJ5s1m4
 ```
@jaszhix 

**Issue**

The applet is incompatible with Cinnamon 3.6.0.
After a uninstalling and reinstalling the applet, only a few pixels wide invisible bar is present in the panel. It can be clicked to open System Monitor (as intended with this applet).
Right clicking it and selecting preferences doesn't open the preference pane.
If I check `.cinnamon/configs/multicore-sys-monitor@ccadeptic23/prefs.json`, everything is enabled.

If I copy/paste `/home/idhuser/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4` to `/home/idhuser/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.6` then remove/add the applet, it shows up correctly but the preference pane still can't be opened. 

**Steps to reproduce**
Have Archlinux up-to-date and installing the applet

**Expected behaviour**
The applet shows and displays system information

**Other information**

**Comment by jaszhix** [comment]
Well, I've been running it with the latest Cinnamon git for months - let's try to figure out what's causing it first before asserting that... Cinnamon will run with the latest version folder in the applet directory, so a `3.4` folder should work. Icing Task Manager works the same way, Cinnamon serves 3.2, 3.4, and 3.6 users from files in the 3.2 directory. I re-tested installing this applet with a clean installation a couple times today. 

Do you have `gir1.2-gtop-2.0` installed? What other applets are you running? Check with `gsettings get org.cinnamon enabled-applets`.

I'm reproducing the issue with opening Preferences. Its kind of weird:

```
(cinnamon:3095): Cjs-WARNING **: JS ERROR: Exception in callback for signal: activate: GLib.SpawnError: Failed to execute child process "prefs.js" (Permission denied)
ProcessSpawnHandler.prototype._init@/home/jason/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/SpawnProcess.js:15:49
ProcessSpawnHandler@/home/jason/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/SpawnProcess.js:8:3
anonymous/MyApplet.prototype.launchPreferences@/home/jason/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/applet.js:226:34
_emit@resource:///org/cinnamon/cjs/modules/signals.js:142:27
PopupBaseMenuItem.prototype.activate@/usr/share/cinnamon/js/ui/popupMenu.js:178:9
PopupBaseMenuItem.prototype._onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:151:9
```

When I check the permissions on the file:

```
drwxrwxr-x  2 jason jason 4096 Oct 31 09:50 .
drwxr-xr-x 64 jason jason 4096 Oct 31 09:50 ..
-rw-rw-rw-  1 jason jason 6356 Oct 31 09:50 prefs.json
```

I'll see what I can find.

**Comment by BenjaminNavarro** [comment]
I have libgtop (v2.38.0) installed though pacman and everything was working fine with it before the cinnamon update. 

Here are the other applets:
```
['panel1:left:1:menu@cinnamon.org:0', 'panel1:left:2:panel-launchers@cinnamon.org:1', 'panel1:left:3:window-list@cinnamon.org:2', 'panel1:right:14:removable-drives@cinnamon.org:3', 'panel1:right:11:notifications@cinnamon.org:14', 'panel1:right:12:keyboard@cinnamon.org:4', 'panel1:right:13:systray@cinnamon.org:7', 'panel1:right:15:power@cinnamon.org:8', 'panel1:right:16:network@cinnamon.org:6', 'panel1:right:17:sound@cinnamon.org:9', 'panel1:right:18:calendar@cinnamon.org:10', 'panel1:right:19:windows-quick-list@cinnamon.org:13', 'panel1:right:0:multicore-sys-monitor@ccadeptic23:28']
```

chmod the prefs.js solves the preference pane issue when using a 3.6 folder. Doing it on the 3.4 folder of a fresh install gives me a `Something went wrong ...` message in the applets manager.

**Comment by jaszhix** [comment]
Not reproducing that. Do you see anything new in .xsession_errors when this occurs?

**Comment by BenjaminNavarro** [comment]
Well, don't bother, it seems that I haven't rebooted my computer in a while and doing so solves the problem. 

So there's just the preference pane bug to fix

**Comment by grande-mephistopheles** [comment]
@jaszhix Hello, I'm facing the same issue. I'm on Fedora 33 Cinnamon. Preferences not showing when clicking on it. It does show up when clicking on it for the first time after system boot. But afterwards it does not work any more. It also happened sometimes in Linux Mint 20 but it's more relevant in Fedora 33.
