### ISSUE TITLE
UUID: multicore-sys-monitor@ccadeptic23 - how to add disks to display

### ISSUE THREAD

**Issue by dhdurgee** [linuxmint/cinnamon-spices-applets#1442]
**Notify author of applet**
@

**Issue**

I separate my data from my boot partition, so only the boot(root) partition displays on my system.  I assume there is a way to add my data partition, but I see no way to add it in the preferences.  I assume that it can be added by editing your prefs.json, but I have no documentation on how to do so.  Would the additional disk display in the same area as the root?  If so, I would need to change colors to distinguish them from one another.

Dave

**Comment by NikoKrause** [comment]
You ignored the issue template. Most importantly you didn't notified the author

**Comment by dhdurgee** [comment]
I am a very infrequent user of this service and as such was unaware that it was necessary to notify the author.  As I came to this point from the applet page I had assumed that such would have been done automatically.  I am still unaware of this procedure, so I would much appreciate your assistance in such notification for both this issue and the next one.

As this one is only a request for additional documentation and the other a request for feature enhancement as opposed to a bug report I did not see the need for details of my particular environment.  I will happy to provide any further information the author might require upon request.

**Comment by NikoKrause** [comment]
All info is provided, when you create a new issue

**Comment by dhdurgee** [comment]
OK, I took a stab at it from the template.  Let me know if I got it right.

**Comment by NikoKrause** [comment]
@dhdurgee 
You specified no author. Look at how I notify you with this message.

**Comment by jaszhix** [comment]
Please provide

 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

Since this is related to your hardware, please also provide the output of ` inxi -F && dmesg | grep -i error` and `cat /etc/fstab`.

**Comment by dhdurgee** [comment]
MultiCore System Monitor v1.7.1
[27d765be90b7181fd014609b0be5babb-0b9e692682a8133f027ccbe169b60aa3f7a857ef.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/1447710/27d765be90b7181fd014609b0be5babb-0b9e692682a8133f027ccbe169b60aa3f7a857ef.zip)
[.xsession-errors.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/1447718/default.xsession-errors.zip)


[glass.log](https://github.com/linuxmint/cinnamon-spices-applets/files/1447672/glass.log)

dhdurgee@Z560 ~/Downloads $ inxi -F && dmesg | grep -i error
System:    Host: Z560 Kernel: 4.8.0-53-generic x86_64 (64 bit) Desktop: Cinnamon 3.4.6
           Distro: Linux Mint 18.2 Sonya
Machine:   System: LENOVO product: 0914 v: Ideapad Z560
           Mobo: LENOVO model: N/A Bios: LENOVO v: 29CN40WW(V2.17) date: 04/13/2011
CPU:       Dual core Intel Core i5 M 480 (-HT-MCP-) cache: 3072 KB 
           clock speeds: max: 2667 MHz 1: 1999 MHz 2: 1333 MHz 3: 1733 MHz 4: 1466 MHz
Graphics:  Card: Intel Core Processor Integrated Graphics Controller
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.00hz, 1366x768@59.79hz
           GLX Renderer: Mesa DRI Intel Ironlake Mobile GLX Version: 2.1 Mesa 17.0.7
Audio:     Card Intel 5 Series/3400 Series High Definition Audio driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.8.0-53-generic
Network:   Card-1: Broadcom BCM4313 802.11bgn Wireless Network Adapter driver: wl
           IF: wlp5s0 state: up mac: ac:81:12:a4:5e:43
           Card-2: Realtek RTL8101/2/6E PCI Express Fast/Gigabit Ethernet controller driver: r8169
           IF: enp6s0 state: down mac: b8:70:f4:2c:6b:9f
Drives:    HDD Total Size: 500.1GB (21.2% used) ID-1: /dev/sda model: HGST_HTS725050A7 size: 500.1GB
Partition: ID-1: / size: 16G used: 7.1G (45%) fs: jfs dev: /dev/sda12
           ID-2: swap-1 size: 17.18GB used: 0.01GB (0%) fs: swap dev: /dev/sda9
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 83.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 217 Uptime: 1 day Memory: 2205.9/3751.7MB Client: Shell (bash) inxi: 2.2.35 
[    0.544086] acpi PNP0A08:00: _OSC failed (AE_ERROR); disabling ASPM
[76371.930965] mce: [Hardware Error]: Machine check events logged
[76371.930966] mce: [Hardware Error]: Machine check events logged
[91208.428643] perl[30913]: segfault at 5 ip 00007fe097a80663 sp 00007ffdb5788bf0 error 4 in CSV_XS.so[7fe097a78000+a000]
[91333.328221] perl[32180]: segfault at 5 ip 00007fc1345ae663 sp 00007ffe32a884b0 error 4 in CSV_XS.so[7fc1345a6000+a000]
[91389.723736] perl[32183]: segfault at 5 ip 00007fc59a7a1663 sp 00007ffdb3de0d10 error 4 in CSV_XS.so[7fc59a799000+a000]
[92130.574493] perl[32393]: segfault at 5 ip 00007efecf419663 sp 00007ffc2898a280 error 4 in CSV_XS.so[7efecf411000+a000]
[98035.532476] mce: [Hardware Error]: Machine check events logged
[98035.533515] mce: [Hardware Error]: Machine check events logged
dhdurgee@Z560 ~/Downloads $ cat /etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda12 during installation
UUID=ca243458-1407-4740-8bb6-9ef96ca59a00 /               jfs     errors=remount-ro 0       1
/dev/sda9       none            swap    sw              0       0
UUID=bfb39ed3-9f2d-42aa-86af-0e6fa7fab64e /perm jfs errors=remount-ro 0 2
UUID=8a345ea6-0590-40f9-abda-51fcd0b8f98b /rosa jfs errors=remount-ro 0 2

dhdurgee@Z560 ~/Downloads $

**Comment by NikoKrause** [comment]
Please notify the author

**Comment by jaszhix** [comment]
@dhdurgee Is the failing hard drive you mentioned in #1443 still in use? I see these errors, not sure what they're about, from dmesg:

`
[ 0.544086] acpi PNP0A08:00: _OSC failed (AE_ERROR); disabling ASPM
[76371.930965] mce: [Hardware Error]: Machine check events logged
[76371.930966] mce: [Hardware Error]: Machine check events logged
[91208.428643] perl[30913]: segfault at 5 ip 00007fe097a80663 sp 00007ffdb5788bf0 error 4 in CSV_XS.so[7fe097a78000+a000]
[91333.328221] perl[32180]: segfault at 5 ip 00007fc1345ae663 sp 00007ffe32a884b0 error 4 in CSV_XS.so[7fc1345a6000+a000]
[91389.723736] perl[32183]: segfault at 5 ip 00007fc59a7a1663 sp 00007ffdb3de0d10 error 4 in CSV_XS.so[7fc59a799000+a000]
[92130.574493] perl[32393]: segfault at 5 ip 00007efecf419663 sp 00007ffc2898a280 error 4 in CSV_XS.so[7efecf411000+a000]
`

**Comment by dhdurgee** [comment]
Failing hard drive is no longer connected.  I am trying to track down the perl errors, might relate to copying a damaged file from the dying drive.  Thank you for bringing it to my attention.

Dave

**Comment by dhdurgee** [comment]
**Notify author of applet**
@

As I had heard nothing from you in a few days, I started poking around and located your applet code on my system.  I have never programmed an applet and have very little experience with such coding languages, so I may be utterly mistaken in my understanding of the code.  So take my input for what it is worth.

Looking at the file DataProviders.js I see a function GetDiskDevices which, if I am correctly reading the code, is to return a list of all mounted disk devices.  If this is indeed the case, it is not working as designed on my system.  The root system is hard coded in this function, as of course it is always mounted.  But as you can see from my fstab in an earlier comment I also have two other disk devices mounted, /perm and /rosa, that are not being returned.

If I am correct in my understanding of this, how can this function be corrected?  Can I provide any additional information or run any test code that would assist?

**Comment by jaszhix** [comment]
My first guess was it had to do with the partitions using the JFS filesystem, which I haven't tested with. Are you able to format an ext4 partition and test if this is the case? I'll try to look at it this weekend.

**Comment by dhdurgee** [comment]
**Notify author of applet**
@

As this is a multiboot system I have a few NTFS partitions for Windows 7 already present.  I created a mountpoint for one of them and mounted it as:

sudo mount -t ntfs /dev/sda2 /w7

mount | grep /dev/sda

/dev/sda12 on / type jfs (rw,relatime)
/dev/sda13 on /rosa type jfs (rw,relatime)
/dev/sda10 on /perm type jfs (rw,relatime)
/dev/sda2 on /w7 type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)

I then went into your applet preferences and still only the root partition shows.  Do I need to restart the app somehow?  Perhaps a cinnamon restart?

**Comment by jaszhix** [comment]
The path to the mounted partition shouldn't matter. It is always a good idea to restart Cinnamon when debugging applets.

**Comment by dhdurgee** [comment]
**Notify author of applet**
@

As suggested, I restarted Cinnamon.  No impact, the NTFS w7 mount was still not offered in the preferences dialog window for Disk I/O here.  Is there more information I can provide?

**Comment by NikoKrause** [comment]
You don't have to add 
Notify author of applet
@
every time. Once is enough. And you didn't notify anyone with that,

Looking at the Spices Website:
![screenshot-area-2017-11-10-221026](https://user-images.githubusercontent.com/8415124/32678784-22b58a8e-c664-11e7-9d30-d4c03d7b938b.png)

The author is jaszhix. So to notify him here on GitHub you do:
@jaszhix

**Comment by jaszhix** [comment]
I would actually be surprised if NTFS was supported. I don't have any plans to. It may need to be in your /etc/fstab as I have never seen removable drives show up in the applet. Are the JFS drives being seen? The documentation for the API behind fetching the volumes to monitor can be found on [devdocs](http://devdocs.baznga.org/gio20~2.50p/gio.volumemonitor).

**Comment by dhdurgee** [comment]
@jaszhix 

The NTFS partition are on the same drive as the JFS partitions.  As I commented previously:

dhdurgee@Z560 ~/Downloads $ mount | grep /dev/sda
/dev/sda12 on / type jfs (rw,relatime)
/dev/sda13 on /rosa type jfs (rw,relatime)
/dev/sda10 on /perm type jfs (rw,relatime)
/dev/sda2 on /w7 type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
dhdurgee@Z560 ~/Downloads $ 

In the above listing the NTFS partition appears to be supported via type fuseblk, whatever that is.  All of these partitions can be viewed in mc and other file managers, so they are certainly being seen there.

If you have a diagnostic program you would like me to run for you and post the output here please let me know.

**Comment by dhdurgee** [comment]
@jaszhix 

I should note, in case I didn't before,  I do see disk activity reported on the root drive, which as you can see above is JFS formatted.

**Comment by jaszhix** [comment]
Can you try this version?

[multicore-sys-monitor@ccadeptic23.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/1462882/multicore-sys-monitor.ccadeptic23.zip)

**Comment by dhdurgee** [comment]
@jaszhix 

That is interesting.  I now see my gigolo mounted network shares as well as the root drive, but not the other locally mounted partitions.  I see the gigolo shares in the preferences dialog and can disable them, but even when I do so they show up with 0 values in the hover-over listing.  I also notice that my network activity graph shows activity, but all networks in the hover-over listing show zero values.

I noticed you only changed the DataProviders.js, so that was all I replaced.

**Comment by jaszhix** [comment]
I think I know where the confusion is, the partitions that show up in the list each represent a drive. We are pulling all the available drive information because we are mapping the drive list by the info from 
 the `get_drive` call. If there is I/O activity occurring in /rosa or /perm, it should be reflected under the `/` root partition, because we can't get per-partition I/O numbers. The version I gave you simply gets the mounts instead of the volume, but that's broken for removable drives so it won't be used.

Maybe the default label for the system drive should be "System" not "/", as that is confusing.

**Comment by dhdurgee** [comment]
@jaszhix 

If this is indeed data at the drive, then it would likely make more sense to label it, for example, as "/dev/sda" instead of as a partition name at all.  To label it as "/" or even "System" might confuse.  I assume that the device name is part of the data you have access to, which would allow this to be a single loop as opposed to special casing "/" as you do now.

**Comment by jaszhix** [comment]
Actually, I think I'll leave it as is because the values are cached in JSON. Since this applet uses its own settings mechanism entirely, its probably not worth writing logic to migrate everybody over a text label. Sorry for the misunderstanding.
