### ISSUE TITLE
It doesn't group windows for /home/[user]/.local/share/applications

### ISSUE THREAD

**Issue by alienator** [linuxmint/cinnamon-spices-applets#1454]
Fedora 26, Cinnamon 3.6.0

Hi, for those .desktop files under /home/[user]/.local/share/applications doesn't group windows, I see the same behaviour with the dash of gnome, doesn't group windows for those files

**Comment by Cobinja** [comment]
Please use the issue template that is offered when creating a new issue (including the applet's UUID in the issue title).

**Comment by NikoKrause** [comment]
Please provide the missing infos as requested.
The issue will be reopened then.
