### ISSUE TITLE
General: System Settings - Applets do not update

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#1455]
**Issue**

I have no idea if this is the right place (it could be the problem of the `cinnamon-common` package), but I noticed lately that on two of my computers the applet list do not update.

**Steps to reproduce**

I open `System Settings` > `Applets`, click on `Available updates (online)` and then `Refresh list`. When I change the display order to `Date`, I get the following order:
1. Cinnamenu
2. Icing Task Manager
3. Multi-Core System Monitor
4. ...

When I go to the website [https://cinnamon-spices.linuxmint.com/applets/latest](https://cinnamon-spices.linuxmint.com/applets/latest), I see the following ranking:
1. Places
2. Timer with notification
3. Tor Button
4. ...

**Expected behaviour**

I would expect these two list to be identical.

**Other information**

I tried to run `/usr/bin/python2 /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py applets panel1` from the terminal, but did not get any error message.

Observation: As already mentioned, this happens on two computers (both on the same network), but not on a third (on a different network).

Another observation: Whenever I press the `Refresh list` button, the progress bar seems to hang for a moment at 25% (it still shows 100% as text) on the effected computers.

```
$ zcat /usr/share/doc/cinnamon-common/changelog.gz
cinnamon (3.4.6) sonya; urgency=medium

  * Remove strict dependency on libcjs-dbg

 -- Clement Lefebvre <root@linuxmint.com>  Wed, 09 Aug 2017 12:46:49 +0200
```

**Comment by NikoKrause** [comment]
I can't reproduce this here. It matches as expected:
![screenshot-area-2017-11-13-144142](https://user-images.githubusercontent.com/8415124/32728534-f69af834-c880-11e7-83c3-94b9568f4c24.png)

You can try to delete the cache:
```
~/.cinnamon/spices.cache
```

**Comment by NikoKrause** [comment]
Also you didn't told us, which Cinnamon Version and Distro you are running.

**Comment by jaszhix** [comment]
Its working for me too. Are you behind a firewall? It could be blocking the spices server. Anyway, I think this should be opened in the Cinnamon repository since it has to do with cinnamon-settings.

**Comment by jake1164** [comment]
Could we store the released versions of applets under releases as they are updated?
So under releases would be  UUID_version.tar / zip  allowing users to download the latest zip file and install it from github (in cases like this when its blocked / not working).  

This would also allow users to downgrade an app easily, ie troubleshooting a new issue since an older release.

Example of the Cinnamon repo's releases:
![selection_107](https://user-images.githubusercontent.com/1832491/32783964-78e62332-c91b-11e7-8a11-b595127d6f5b.png)

**Comment by NikoKrause** [comment]
The releases in github are for the whole repo.
Even if you somehow automate to create releases for certain applets (not sure if it's possible), we have already almost 2500 commits in less than a year. Try to find a specific applet release in GitHubs release list with 2500 releases. It's already annoying in Cinnamo. Repo with just 140 releases.

You can download the latest zip file for an applet on the spices website and install it manually.

And if you really have to install an old version of a specific applet (not sure if it happens that offen), you can search for it in the applets github history and download the ZIP there, e.g.
https://github.com/linuxmint/cinnamon-spices-applets/tree/4470d1b35368bbd0cd5a83efccfde08223a754a1
There's a button: "Browse this repo at this point of the history"

**Comment by sphh** [comment]
Sorry for the late reply. I will try supply the missing information:

Cinnamon Version: 3.4.6
Distribution: Linux Mint 18.2 Cinnamon 64-bit

Screenshot after `Refresh list`:
![image](https://user-images.githubusercontent.com/4856462/32800041-447979b8-c971-11e7-9d95-87b25526f8b9.png)

`~/.cinnamon/spices.cache/applet/index.json`
[index.json.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/1472246/index.json.zip)

```
$ ll index.json 
-rw-rw-r-- 1 sph sph 68797 Nov 14 19:13 index.json
```
(which is the current date, so the index.json got updated)

After I purged the cache with `rm ~/.cinnamon/spices.cache/applet/*`, I started the applet manager again. It downloaded 149 files, but the result is the same as above.

Tomorrow I will take my laptop (one of the two computers with exactly the same symptoms) into work and will try to update the list there (it's a different ISP). I will post the results.

**Comment by sphh** [comment]
I brought my laptop into work and everything works fine. After returning home and refreshing the list I get the list as displayed in my [post](#issuecomment-344405514l), hence I entertain the suspicion that my ISP caches the file https://cinnamon-spices.linuxmint.com/json/applets.json (at least that's the file name mentioned in `/usr/share/cinnamon/cinnamon-settings/bin/Spices.py`). Therefore I close this issue.

One curiosity: If I download the file https://cinnamon-spices.linuxmint.com/json/applets.json with `wget` I get a different file from opening it with waterfox...

Thank you all for your comments and help!

**Comment by sphh** [comment]
I opened a new topic in the Linux Mint Forum “Software & Applications”: https://forums.linuxmint.com/viewtopic.php?f=47&t=257991, but have not received any responses yet.

@NikoKrause @jaszhix : Does anybody know who is responsible for the Sucuri firewall settings of https://cinnamon-spices.linuxmint.com, so that I can contact him/her directly?
