### ISSUE TITLE
cingTaskManager@json Bug with LibreOffice

### ISSUE THREAD

**Issue by Faust30000** [linuxmint/cinnamon-spices-applets#1487]
When LibreOffice is opened, two open tabs are displayed. After LibreOffice closure, one tab is displayed until you restart Cinnamon.
Linux Mint 18.2.

**Comment by jaszhix** [comment]
Please review the [issue template](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/ISSUE_TEMPLATE) and finish completing this bug report. A similar bug is being tracked on the [ITM repo](https://github.com/jaszhix/icingtaskmanager/issues/166).
