### ISSUE TITLE
cinnamon-timer@jake1164 does not work in 18.0 or 18.1 (Sarah / Serena)

### ISSUE THREAD

**Issue by jake1164** [linuxmint/cinnamon-spices-applets#1499]
Adding the applet in Sarah does not load due to "Problem initializing settings" and specifically the bind function not being found.  

Serena loads but does not include any presets or a slider to set the timer. The error "invalid setting type 'list' for setting key 'slider_intervals'.  The timer functionality does not work even if you manage to set a time.

**Comment by NikoKrause** [comment]
You added the list type in your applet. This type is a new feature in 18.1. Hence the error in 18.0.

If you want, you can make your applet support multiple Cinnamin versions. E.g. I do it in CinnVIIStarkMenu.

Also here are some instructions on how to do this:
http://developer.linuxmint.com/reference/git/cinnamon-tutorials/xlet-versioning.html

**Comment by jake1164** [comment]
This is resolved with version 1.1.2
