### ISSUE TITLE
Feature request: Function to tag applets

### ISSUE THREAD

**Issue by Piiit** [linuxmint/cinnamon-spices-applets#15]
It would be nice to be able to tag applets, or organize them in categories.

**Comment by anandrkris** [comment]
Yeah - I too had requested for this originally here
https://github.com/linuxmint/Cinnamon/issues/2813

**Comment by JosephMcc** [comment]
I don't see the point in this. I don't see being able to tag all of these diverse applets into a small number of categories. Once you add more than a few (or things like misc.) categories, it becomes useless.
