### ISSUE TITLE
[[Feature]] Add Settable/Customizable Key Command to Launch Applet – gpaste-reloaded@feuerfuchs.eu

### ISSUE THREAD

**Issue by WammKD** [linuxmint/cinnamon-spices-applets#1503]
I had added this myself on Cinnamon 18 but, after upgrading to 18.3, that method/code doesn't seem to work, anymore (otherwise, I'd offer up a pull request, instead.

The premise is simply offering the user the ability to choose a key command to call up the applet's history list.

The configuration screen would (probably?) change to something like this:
![image](https://user-images.githubusercontent.com/10533934/33300880-422b983e-d3b8-11e7-8236-2e15d3bf4606.png)
and pressing said key command brings up the history.

Also, thanks a ton, @Feuerfuchs, for all the work you've done on this; this app. is one of the best (if not the only…?) clipboard applets for Cinnamon and it's a joy having the feature so seamlessly fit into my desktop environment.

```
 * Applet version/Build date: 2.5/2017-10-21 04:59 UTC
 * Cinnamon version: 3.6.6
 * Distribution: Mint 18.3
 ```

**Comment by Feuerfuchs** [comment]
Thanks for your suggestion! I implemented it and it should go live soon. :)
