### ISSUE TITLE
[[Bug]] Applet Height is No Longer Respected – multicore-sys-monitor@ccadeptic23

### ISSUE THREAD

**Issue by WammKD** [linuxmint/cinnamon-spices-applets#1513]
```
 * Applet version/Build date          : 1.7.2/2017-11-21 03:17 UTC
 * Cinnamon version                   : 3.6.6
 * Distribution                       : Mint 18.3
 * Graphics hardware *and* driver used: VGA compatible controller [0300]: Intel Corporation Sky Lake Integrated Graphics [8086:1916] *and* Intel Open Source Technology Center (0x8086) (I believe…)
 ```

**Notify author of applet**
@jaszhix

**Issue**
While I used to be able to adjust the height of the applet from the settings (pictured here:
![image](https://user-images.githubusercontent.com/10533934/33356852-65c25b58-d484-11e7-9c64-6519a9e4ed4f.png)
), that option no longer seems to have any affect. I have my height set to the lowest option but it looks like:
![image](https://user-images.githubusercontent.com/10533934/33356901-b259598a-d484-11e7-9116-8a5a9087c383.png)

It sort of blends in with the background but the half-circle in the middle is RAM usage while the waves to the right are Network.

I'm _guessing_ that it's doubling the panel height but I can't be certain. My computer does have HD and is at a resolution of 2560x1440 so perhaps it's related to #1187?

Hope all of this is helpful; let me know if there's any other information you need that I can supply.

And thanks so much for the applet. It's the only one I've found that blends into the scheme of the user's Cinnamon theme and it's super helpful to have at a glance. Always one of the first applets I download on any new install.

**Steps to reproduce**
Pretty much just install the applet; it may be computer specific.

**Expected behaviour**
Adjusting the height causes the applet to resize in real-time on the panel or, at least, after the Save button is hit.

**Other information**

**Comment by jaszhix** [comment]
Is it scaling the height correctly for you? I think it would be best to remove that option since the height is now responsive to panel height.

**Comment by WammKD** [comment]
Definitely not; I think it's doubling the height of the panel, given I can only see half the circle of the RAM monitoring.

**Comment by jaszhix** [comment]
I didn't see that until clicking the image, yeah that's weird. Are you using high DPI mode? Did you try changing your panel height to see if that helped? And restart Cinnamon, etc.

**Comment by WammKD** [comment]
Ahh, yeah; it's pretty light. Sorry about that.

Restarting Cinnamon/my-computer, yes. I haven't tried changing the panel height yet, though.

I am using high DPI mode.

I can try adjusting the panel size once I get home from work.

**Comment by WammKD** [comment]
Aaaand I'm not able to get into my panel setting due to:

```Loading Panel module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 610, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 322, in __init__
    self.go_to_sidepage(cat, path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 130, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 143, in on_module_selected
    self.on_panel_list_changed()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 222, in on_panel_list_changed
    panel_page = PanelSettingsPage(panel_id, self.settings, position)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 49, in __init__
    section.add_reveal_row(widget, "org.cinnamon", "panels-autohide", check_func=can_show)
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 428, in add_reveal_row
    revealer = SettingsRevealer(schema, key, values, check_func)
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 322, in __init__
    self.on_settings_changed(self.settings, key)
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 333, in on_settings_changed
    self.set_reveal_child(self.check_func(value, self.values))
TypeError: Argument 1 does not allow None as a value```

I'm going to open an issue for Cinnamon and get back to you once I get this cleared/cleaned up.

**Comment by oxben** [comment]
I confirm the height setting is not taken into account in latest version of the applet (I'm not not using high DPI mode).
I've installed Mint 18.3 update two days ago and reinstalled the applet from scratch.
