### ISSUE TITLE
Network Manager applet

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-spices-applets#1514]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json"): no information in either the 'about' window or in the json file.
 * Cinnamon version (cinnamon --version) 3.6.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Intel on-board graphics with 2.1 Mesa 17.0.7
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**

The new, and desirable 'rescan for wireless networks' gives no indication that it is working except a slight flicker in the wifi list.

**Steps to reproduce**

Click the option.

**Expected behaviour**

The button should flash or the window should visibly redraw; some sort of (more than negligible) indication should be given that the user's action has been acted upon.

**Other information**

**Comment by jaszhix** [comment]
Please file against [Cinnamon](https://github.com/linuxmint/Cinnamon/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+network+applet).
