### ISSUE TITLE
vnstat@linuxmint.com doesn't detect wireless device

### ISSUE THREAD

**Issue by NathanSalapat** [linuxmint/cinnamon-spices-applets#152]
Using the latest version of the network usage monitor (vnstat@linuxmint.com) and cinnamon 3.2.7 the wireless interface is never properly selected. Ifconfig reports the wireless as being wlp3s0 on my laptop. I looked at the code and found that a fallback is used as eth0. It would appear to me as if the error is in _updateDevice: function() starting on line seventy. I unfortunately do not know javascript or I could probably be more helpful.

Also I feel like I should mention that this works fine on my desktop which has a wireless interface of wlp5s2.

**Comment by NikoKrause** [comment]
Can you take a screenshot of the applet?
Also what's the output of `vnstat`?

**Comment by NathanSalapat** [comment]
I manually corrected the applet so it works, by simply entering the wlp3s0 string where it calls the variable that should have the interface name, but it would just display a small gray box, without the image created by vnstati.

vnstat output is this:
                      rx      /      tx      /     total    /   estimated
 wlp3s0:
       Jan '17     78.42 GiB  /   97.28 GiB  /  175.70 GiB
       Feb '17     29.95 GiB  /   79.02 GiB  /  108.97 GiB  /  136.28 GiB
     yesterday    814.86 MiB  /    3.34 GiB  /    4.13 GiB
         today    450.38 MiB  /    1.72 GiB  /    2.16 GiB  /    5.56 GiB

 enp2s0: Not enough data available yet.

**Comment by NikoKrause** [comment]
Could you use a non modified version of the applet and create a screenshot?

**Comment by NathanSalapat** [comment]
Ya, I can do that, could try and get the output from looking glass too. Not at my computer now, so will be several hours.

**Comment by NikoKrause** [comment]
The first time I used the applet, I had to set up vnstat. I used this tutorial
https://www.howtoforge.com/tutorial/vnstat-network-monitoring-ubuntu/

I have wlp5s0. After ging through the steps there, it showed up for me.

**Comment by NathanSalapat** [comment]
![vnstat](https://cloud.githubusercontent.com/assets/8930456/23289221/f8b1dcf6-fa0d-11e6-8a58-085cebc120e7.png)

Here is a picture of the network monitor when it's not working. I checked out that link you provided, and everything seems to be just fine. I can run the vnstat command without any args and get the output for my active interface.

Looking at the looking glass under the extensions tab is shows that the network usage monitor loaded, and doesn't mention any errors there, but in the log tab it does mention (error t=2017-02-23T21:13:52Z device: eth0) which seems to show up every time I click on the applet.

**Comment by NathanSalapat** [comment]
Alright, so I just updated the applet and restarted cinnamon, still worked fine, thought maybe it would break when I restarted my computer, nope still works fine. Here's the kicker though, the looking glass log still gives the "error t=2017-02-28T21:31:18Z device: wlp3s0" message, and the last updated just added Croatian language support.

I double checked and the code for the applet, and my changes were certainly written over, and it's back to the '.this_device' variable for the vnstati code. No idea what's going on anymore. :D feel free to close this though.

**Comment by pdcurtis** [comment]
@NikoKrause I discovered I have the same problem with vnstat@linuxmint.com when I volunteered  to update it to have an asynchronous call for @clefebvre #420. 

**I think you should reopen the issue if that is possible**.

The problem seems to be in the `_updateDevice()` function and errors show in the glass log file.

It looks as if it only worked if the interface was eth0 because that was set in the catch (e) at the end of the routine. It can be made to sort of work if the device is set to the interface one is using at that point.
I will try to have a look over the next few days and in the limit I may be able to patch in the function I use in NUMA which does work and allows me to display the vnstati output.

I will also go back and checkout an earlier version from cinnamon-spices-applets.

**Comment by pdcurtis** [comment]
@NikoKrause @clefebvre 

I have run it again from the initial commit into cinnamon-spices-applets (`ba0627d3dc21f86994771dc65a5022889741a662`) and it now picks up the correct device but is still putting errors into the glass log:
```
info t=2017-04-27T08:29:25.114Z Hiding systray: network
error t=2017-04-27T08:29:28.183Z device: eth0
error t=2017-04-27T08:29:28.183Z null has no properties
trace t=2017-04-27T08:29:28.183Z 
<----------------
MyApplet.prototype._updateDevice@/home/pcurtis/.local/share/cinnamon/applets/vnstat@linuxmint.com/applet.js:66
MyApplet.prototype._update@/home/pcurtis/.local/share/cinnamon/applets/vnstat@linuxmint.com/applet.js:52
MyApplet.prototype.on_applet_clicked@/home/pcurtis/.local/share/cinnamon/applets/vnstat@linuxmint.com/applet.js:46
Applet.prototype._onButtonPressEvent@/usr/share/cinnamon/js/ui/applet.js:270
---------------->
error t=2017-04-27T08:29:58.990Z device: eth0
error t=2017-04-27T08:29:58.991Z null has no properties
trace t=2017-04-27T08:29:58.991Z 
<----------------
```
I think I need to learn about `git blame`!
