### ISSUE TITLE
weather@mockturtl: Temperature not translated

### ISSUE THREAD

**Issue by szekeres2016** [linuxmint/cinnamon-spices-applets#1524]
Good day,

I hasve been using the weather tray applet for many years now but for some reason I never reported this before. Anyway it always bugged me a bit that the ˝Temperature˝ text is not translated when using the application in hungarian (or any other language?). Can you please look into this? Every other text is properly localised other than this.

Many thanks in advanced!

![kep](https://user-images.githubusercontent.com/20751590/33515850-aeb7352c-d768-11e7-8d6a-393a367cb763.png)

**Notify author of applet**
@mockturtl

**Comment by NikoKrause** [comment]
Hey,

I just checked. And it's translated in other languages.
In Hungarian there are 25 missing translated strings. The "Temperature:" string is marked as `fuzzy`, which means it's translated automatically, which most of the time means, it's a bad translation. And Cinnamon ignores fuzzy translations.

You can help by translating this applet: https://github.com/linuxmint/cinnamon-spices-applets/blob/master/weather%40mockturtl/files/weather%40mockturtl/po/hu.po

You can translated it with the `poedit` application (which can be installed with the software center) and create a pull request.

If you have any questions feel free to ask.

**Comment by szekeres2016** [comment]
Dear NikoKrause

I filled out the missing parts in the translation file. since I have no experience with this platform whatsoever I upload the file here.

Have a nice rest of the day!

[hu.mo.tar.gz](https://github.com/linuxmint/cinnamon-spices-applets/files/1524612/hu.mo.tar.gz)

**Comment by mockturtl** [comment]
@szekeres2016  Köszönöm!

Can you upload the new .po file with your changes, instead of the "compiled" .mo file?

**Comment by NikoKrause** [comment]
@szekeres2016 The `.mo` file is a binary, which is not useful at all. We need the `.po` file
