### ISSUE TITLE
weather@mockturtl. The city button is set to direct to us.rd.yahoo.com. Link is dead.

### ISSUE THREAD

**Issue by VasilisKos** [linuxmint/cinnamon-spices-applets#1547]
* 1.14.0 (22-10-2017
 * Cinnamon version 4.6
 * Distribution - Mint 18.3
 * Intel 3rd Gen Core processor Graphics Controller, modesetting driver

**Issue**
The city button is set to direct to http://us.rd.yahoo.com/dailynews/rss/weather/Country__Country/*https://weather.yahoo.com/country/state/city-*** which is not working.
Just the https://weather.yahoo.com/country/state/city-*** works fine. It needs to be changed.

**Comment by jaszhix** [comment]
Ping author @mockturtl.

**Comment by mockturtl** [comment]
Confirmed in my location.  

The link is read from the Yahoo response data here: [applet.js#L585](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/weather%40mockturtl/files/weather%40mockturtl/applet.js#L585).

----

[Test](https://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20weather.forecast%20where%20woeid=%22MY_WOEID%22%20and%20u=%22c%22) (replace your WOEID)

Output:

```json
{
"query": {
"count": 1,
"created": "2017-12-06T00:53:24Z",
"lang": "en-US",
"results": {
"channel": {
...
"link": "http://us.rd.yahoo.com/dailynews/rss/weather/Country__Country/*https://weather.yahoo.com/country/state/city-1234567/",
...
```

I'm tempted to delete everything before the asterisk, but maybe the data format is different for other locations?
