### ISSUE TITLE
Global-AppMenu

### ISSUE THREAD

**Issue by enep** [linuxmint/cinnamon-spices-applets#1548]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**
Hello I have stopped working applet global menu https://github.com/lestcape/Global-AppMenu

**Comment by jaszhix** [comment]
That extension is not in the Spices repo, and the author has discontinued work on it.
