### ISSUE TITLE
Click in grouped windows

### ISSUE THREAD

**Issue by bigbruno** [linuxmint/cinnamon-spices-applets#1557]
Is possible add resource to click in icon with windows groupped and this switch window?

Like work in deepin desktop.

**Comment by NikoKrause** [comment]
Which applet are you talking about?

**Comment by bigbruno** [comment]
CobiWindowList

**Comment by NikoKrause** [comment]
Then please write it in the title as all other open issues do. And notify the author. You'll find him here:
https://cinnamon-spices.linuxmint.com/applets/view/287
