### ISSUE TITLE
The Recent Docs applet shows no error when trying to open a non-existing file

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-spices-applets#1562]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") Info not available
 * Cinnamon version (cinnamon --version) 3.6.6.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3

 ```

**Issue**

The Recent Docs applet shows no error when trying to open a non-existing file. On a slow computer, and especially if two items in the recent list have the same name - because one version of a file is on a USB drive, and one on the hard drive, say - this lack of response is confusing and irksome.

**Steps to reproduce**

Create a text file. Open it. Delete it. Try to open it in the Recent docs applet.

**Expected behaviour**

An error message should be shown. This should be easy to arrange!

**Other information**

**Comment by NikoKrause** [comment]
Hey,

do you mean the applet `recent@cinnamon.org`? It's not part of this repo (this repo contains only 3rd party applets). The `recent@cinnamon.org` applet is part of Cinnamon itself.

The menu shows a notification for non-existing files. I guess this could be adapted to the recent applet.
Good idea.

**Comment by CottonEaster** [comment]
@NikoKrause 

I'm afraid I don't know; what I mean is that applet that appears (under my themes, anyway) thus:

![image](https://user-images.githubusercontent.com/9998846/34064748-723d0bd6-e1f3-11e7-9cd9-70e8bcb32c95.png)


So, should I move this to github.com/linuxmint/cinnamon?

**Comment by jaszhix** [comment]
When you go to Applet Settings, all applets with a lock icon next to them are system installed. You can also check with `ls /use/share/cinnamon/applets`. There's no "recent docs" applet here, so please file your feature request on the [Cinnamon repo](https://github.com/linuxmint/Cinnamon/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+recent+applet).

**Comment by NikoKrause** [comment]
@CottonEaster 
Does the About... dialog say `recent@cinnamon.org`?

**Comment by CottonEaster** [comment]
NikoKrause: yes. It says this:

![image](https://user-images.githubusercontent.com/9998846/34067105-550b520e-e214-11e7-8626-fa867a541df4.png)

**Comment by NikoKrause** [comment]
So you want a message to be shown like in the menu for non-existent files?

**Comment by CottonEaster** [comment]
Well, one option (call it I) would be for the applet's entry for a non-existent file to read something like

> file1 [deleted]

Another option would be (II) simply to remove the file from the list.

A third option (III) is as follows. Leave the list as it is, but produce a error message if, when the user clicks the name of a recent but now non-existent file.

**Comment by NikoKrause** [comment]
Have you even tried the menu as I mentioned?

**Comment by NikoKrause** [comment]
Oh, I mean the default Cinnamon menu. It has a category `Recent files`:
![](https://i.stack.imgur.com/uSkwL.jpg)

**Comment by CottonEaster** [comment]
Aha! I find that the MintMenu (which I do not normally use, because of bug #6110) gives an informative error when I try to open a non-existent file. So, that's good behaviour. It seems desirable to me that the 'recent documents' applet replicate that behaviour.

**Comment by NikoKrause** [comment]
Shouldn't be too hard to adapt. Since Cinnamon 3.6 is feature freeze release, I'll look into it for Cinnamon 3.8.

**Comment by CottonEaster** [comment]
@NikoKrause 

Thank you, though it occurs to me that what we have here at least arguably _is_ a bug, in that - at least compared to the MintMenu - the Recent applet fails to give any response when the user tries to re-open a non-existent file.
