### ISSUE TITLE
Cinnamenu@json - Tooltip persists after selecting a search provider result

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon-spices-applets#1567]
Applet version 3.1.0
Cinnamon 3.6.7 or 3.6.6
Mint 18.3
Intel 2nd Generation Core Processor Family Integrated Graphics Controller
Display Server: X.Org 1.18.4 drivers: (unloaded: fbdev,vesa)
Resolution: 1366x768@60.03hz
GLX Renderer: Mesa DRI Intel Sandybridge Mobile GLX Version: 3.0 Mesa 17.0.7

@jaszhix 

Anomalous search box left visible on screen after menu closed when a search provider entry has been present in menu.

To consistently reproduce, enable search providers and a provider, open menu, type some text into search box, and select the search provider entry in the menu.

![screenshot from 2017-12-21 04-36-44](https://user-images.githubusercontent.com/29017677/34240794-db1f0ff0-e608-11e7-8f3c-e2b669669801.png)

**Comment by jaszhix** [comment]
To fix this temporarily, just open and close the menu again - probably caused by search provider results returning asynchronously.

**Comment by smurphos** [comment]
Thanks @jaszhix - all good having updated.
