### ISSUE TITLE
[text-to-speech-applet@cardsurf] Add keyboard shortcuts to Start/Stop reading aloud

### ISSUE THREAD

**Issue by al-mission-2016** [linuxmint/cinnamon-spices-applets#1568]
**[text-to-speech-applet@cardsurf]**
{
    "last-edited": 1507154251, 
    "uuid": "text-to-speech-applet@cardsurf", 
    "version": "1.1.0", 
    "description": "A text reading applet", 
    "name": "Text to speech applet"
}

Please add keyboard shortcuts to allow user to start/stop reading aloud a text. 

For instance, the "settings-schema.json" could be extended as this:
    **"keybinding": {
        "type": "keybinding",
        "description": "Set the keybinding for Start/Stop reading",
        "default": "<Super><Shift>s",
        "tooltip": "Shortcut to start/stop speaking"
    },**
...

**Comment by NikoKrause** [comment]
@cardsurf
