### ISSUE TITLE
Certificate error when updating cache (applet list)

### ISSUE THREAD

**Issue by carlosribeiro1987** [linuxmint/cinnamon-spices-applets#1569]
```
 * Cinnamon version - Cinnamon 3.6.7
 * Distribution - Linux Mint 18.3  64 bit
 ```

**Issue**
Getting error when trying to access applet list for download. A message box asks for cache updating, but return this error message when I try to update:
``` <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> ```

**Steps to reproduce**
Update cache to get the list of online applets.

**Print of the error message (pt-BR)**

![image](https://user-images.githubusercontent.com/15783413/34260959-aa2c0f06-e64e-11e7-88ef-8ef4c459bb88.png)

**Comment by carlosribeiro1987** [comment]
When I tried to open the Spices website, I've got certificate error.

**Comment by jaszhix** [comment]
Looks like a new cert was issued today, should be fixed.

**Comment by carlosribeiro1987** [comment]
Yes. It's working now.

**Comment by rwpreece** [comment]
and it's broke again.  After 19.1 update and/or approximately December 21, 2018 I'm getting the SSL:CERTIFICATE_VERIFY_FAILED.
