### ISSUE TITLE
BgRadio@spacy01 TV Stream for BNT* wouldn't work

### ISSUE THREAD

**Issue by wankata** [linuxmint/cinnamon-spices-applets#1571]
**Version from metadata.json**
"last-edited": 1508561972

**Notify author of applet**
@spacy01 

**Issue**
The "at" param of the BNT Stream (bnt.stream?at=b0d1270b39e08ad9c78dc53f43a1ba5c) depends on the location you are playing it from. So you need to parse the BNT online web page to obtain the current param, based on the user's location, or remove the links for the BNT* streams, because they wouldn't work for anyone else but you.

**Steps to reproduce**
Just try to play the stream from another network.

**Comment by spacy01** [comment]
Yes, i already notice that... :( Still thinking for simple solution.

**Comment by wankata** [comment]
I can give you the console commands you need to execute, so you can retrieve the user's hash, but I don't know how to obtain the command's result from the Cinnamon's API.

So first we need to get the HTML page (with the player's iframe):
`$ wget -r -l1 -H -Dcdn.bg -O /tmp/bnt.txt http://tv.bnt.bg/bnt1/16x9/
`
Than we need to grep for the hash:
`$ grep playlist.m3u8 /tmp/output.txt |cut -c84-115`

If we assume that the result of the previous is assigned to a variable x, your rtmpdump should look like this:
`Main.Util.spawnCommandLine("bash -c \"rtmpdump -r 'http://ios.cdn.bg:2020/fls' -a 'fls' -f 'WIN 11,5,502,149' -p 'http://cdn.bg/live/8W5GA2ujvB' -W 'http://cdn.bg/eflash/jwplayer510/player.swf' -y 'bnt.stream?at=" + x + "' -b '0' | vlc --meta-title 'BNT' -\"");`

and at the end we want to remove the wget file:
`$ rm -fv /tmp/bnt.txt`

If you can manage to retrieve the command results from the javascript, it should be a piece of cake. I've tried it but with no luck for some reason.

**Comment by spacy01** [comment]
Thank you for the help!

First command - `wget -r -l1 -H -Dcdn.bg -O /tmp/bnt.txt http://tv.bnt.bg/bnt1/16x9/`, working like a charm! And is very helpful.

But second one, returns me error. Here is the console output:

wget -r -l1 -H -Dcdn.bg -O /tmp/bnt.txt http://tv.bnt.bg/bnt1/16x9/grep playlist.m3u8 /tmp/bnt.txt | cut -c84-115
WARNING: combining -O with -r or -p will mean that all downloaded content
will be placed in the single file you specified.

--2017-12-23 09:50:04--  http://tv.bnt.bg/bnt1/16x9/grep
Преобразувам tv.bnt.bg (tv.bnt.bg)... 89.252.246.202, 89.252.246.200, 89.252.246.201, ...
Свързване към tv.bnt.bg (tv.bnt.bg)|89.252.246.202|:80... успешно свързване.
HTTP изпратено искане, чакам отговор... 404 Not Found
2017-12-23 09:50:04 ГРЕШКА: 404: Not Found.

--2017-12-23 09:50:04--  http://playlist.m3u8/
Преобразувам playlist.m3u8 (playlist.m3u8)... неуспя: Не е известно името на услугата.
wget: unable to resolve host address ‘playlist.m3u8’
/tmp/bnt.txt: Scheme missing.

And the result is empty /tmp/bnt.txt file

**Comment by wankata** [comment]
What you've pasted here is wrong. The grep seems to be attached to the previous command.
Try this one:
`$ wget -qr -l1 -H -Dcdn.bg -O /tmp/bnt.txt http://tv.bnt.bg/bnt1/16x9/; grep playlist.m3u8 /tmp/bnt.txt | cut -c84-115`

I've added -q to the wget so to suppress it's console output. And there is a semicolon between the two commands. The previous line should return only the hash and nothing else.

**Comment by spacy01** [comment]
@wankata, yes you are right, of course! Silly me! :)
Again, thank you for your help, i figured out. The applet will have update, very soon.

**Comment by wankata** [comment]
No worries! Please let me know, when you update it – I am currious how you manage to retrieve the output of the commands through the JS API :) I got lost yesterday and I am pretty sure that I've made some obvious mistake but too late at night to see it :)

And Marry Christmas!

**Comment by spacy01** [comment]
@wankata, here is:

Main.Util.spawnCommandLine("bash -c \"wget -r -l1 -H -Dcdn.bg -O '/tmp/bnt.txt' 'http://tv.bnt.bg/bnt1/16x9/'; grep playlist.m3u8 '/tmp/bnt.txt' | cut -c27-115 > '/tmp/bnt1.txt'; mpv --title=BNT $(cat /tmp/bnt1.txt)\"");

Bash only. I replace vlc with mpv, also. 

Marry Christmas!

**Comment by wankata** [comment]
Thank you!

Haha, this is nice hack. So you don't need to retrieve it in the js :) I knew that it was easy :)

What is the advantage of mpv?

**Comment by spacy01** [comment]
Seems that mpv load streams faster and with better quality. Also, sometimes vlc start with sound only. May be it depend from graphic card, but on my opinion mpv handle it better with streams.

**Comment by spacy01** [comment]
@wankata, the applet has been updated. You may want to test it. :)

**Comment by wankata** [comment]
@spacy01 
Works like a charm! Good work!
