### ISSUE TITLE
Color picker: use smaller default icon

### ISSUE THREAD

**Issue by orschiro** [linuxmint/cinnamon-spices-applets#1578]
Only a minor detail to the otherwise excellent color picker. I suggest to use a slightly smaller default icon that integrates better into the panel. All other icons are smaller (e.g. see the round Telegram icon):

![image](https://user-images.githubusercontent.com/170947/34405896-225af3e0-ebb6-11e7-986a-e297ab2711f0.png)

**Comment by NikoKrause** [comment]
Colored icons in applets do have a different size than symbolic icons or those indicator icons.
I can use a symbolic icon instead:
![screenshot-area-2018-02-05-002931](https://user-images.githubusercontent.com/8415124/35783697-b1d102f8-0a0b-11e8-90d5-7ac003aa5203.png)

**Comment by orschiro** [comment]
> I can use a symbolic icon instead:

Your screenshot looks very good to me!
