### ISSUE TITLE
weather@mockturtl -Forecast Starts from Yesterday...

### ISSUE THREAD

**Issue by cevadoztug** [linuxmint/cinnamon-spices-applets#1592]
weather@mockturtl

```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
Version 1.14.0

 * Cinnamon version (cinnamon --version)


 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux Mint 18.3 Cinnamon

  
**Issue**
Forecast Starts from Yesterday


**Steps to reproduce**
Nothing special. Default usage scenario


**Expected behaviour**
Forecast Starts from TODAY

https://github.com/mockturtl

@mockturtl

**Comment by jaszhix** [comment]
@cevadoztug Make sure you ping the author so they know about the issue.

@mockturtl

**Comment by cevadoztug** [comment]
Thank you

**Comment by mockturtl** [comment]
> **Steps to reproduce**
> Nothing special. Default usage scenario

I can't reproduce.  The Yahoo server may have old data for your location.  What's your WOEID?

**Comment by cevadoztug** [comment]
Hello. Thank you for your attention.

WOEID: 2337920

Two attached screen shots can demonstrate the "yesterday" issue.

The problem is there for months for several locations.

If it may help, my settings as follows.
Weather Location: Turkey
OS Locale: English Australia
First Day of Week: Monday.

Regards,




*Cevad ÖZTUĞ*
Yönetim Kurulu Başkanı / Chairman of the Board
İnşaat Yüksek Mühendisi - ODTÜ / Civil Engineer (M.Sc.) - METU
*EGE A.Ş.* Co. Inc.
www.egeas.com

**Comment by cevadoztug** [comment]
Forgotten screenshots attached...



*Cevad ÖZTUĞ*
Yönetim Kurulu Başkanı / Chairman of the Board
İnşaat Yüksek Mühendisi - ODTÜ / Civil Engineer (M.Sc.) - METU
*EGE A.Ş.* Co. Inc.
www.egeas.com

**Comment by Sadi58** [comment]
I use two instances of this applet.
I have the same issue with WOEID: 2347289 but no issue with the location.
Sometimes it might be useful to see how the weather was yesterday though ;-)

**Comment by cevadoztug** [comment]
The issue seems to be vanished. Everyting works fine. Magic?
