### ISSUE TITLE
Show Desktop++: Preview of Desktop does not restore after Menu opening

### ISSUE THREAD

**Issue by Piiit** [linuxmint/cinnamon-spices-applets#16]
How to reproduce?
- Configure "Show Desktop" with preview of desktop enabled
- Open any window
- Move mouse cursor to the applet "Show Desktop" > Window gets half-transparent
- Press "Super" on keyboard or any other keyboard-shortcut to open the Cinnamon Menu

Windows remain transparent, but should restore instead.

**Comment by NikoKrause** [comment]
I can reproduce it. You can restore it by hovering over the Show Desktop applet.
This should also be filed against Cinnamon repo.
You can leave this here open, because it's the same problem with the "Show Desktop ++" applet.

**Comment by NikoKrause** [comment]
@mohammad-sn

**Comment by Piiit** [comment]
@NikoKrause and @JosephMcc Actually I was talking about show-desktop@cinnamon.org... The default show-desktop applet!

**Comment by NikoKrause** [comment]
I know. But:

1. That's the wrong repo for that applet to report.
2. The Show-Desktp++ Applet has this issue as well.

**Comment by NikoKrause** [comment]
No. The default applets are shipped with Cinnamon. You don't want Cinnamon ship without any applets preinstalled. They are installed in the root directory, so you don't delete them by accident.

All apps, which are here are optional and are installed into the local repo.

**Comment by NikoKrause** [comment]
https://github.com/linuxmint/Cinnamon/pull/6317
