### ISSUE TITLE
Wrong indicator for swap usage UUID:multicore-sys-monitor@ccadeptic23

### ISSUE THREAD

**Issue by KES777** [linuxmint/cinnamon-spices-applets#1600]
```
 * v1.8.1/2017-12-26 07:50
 * Cinnamon 3.6.7
 * Mint 18.3; Linux work 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 ```

**Issue**
Swap usage is 0 bytes, but idicator shows that (see # 3 on picture)
```
$ top

top - 10:17:50 up 9 min,  1 user,  load average: 0,08, 0,31, 0,21
Tasks: 222 total,   1 running, 221 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0,8 us,  0,2 sy,  0,0 ni, 99,1 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem : 12093532 total,  8720360 free,  1192012 used,  2181160 buff/cache
KiB Swap:  1999868 total,  1999868 free,        0 used. 10024212 avail Mem 
```
![delete](https://user-images.githubusercontent.com/799021/34904264-12536468-f84b-11e7-91a2-9f90162aaaba.jpg)

**Steps to reproduce**

**Expected behaviour**

Indicator should be zero

**Comment by mad73923** [comment]
same problem here!
Running version 1.8.1

**Comment by mad73923** [comment]
This fix doesn't solve the problem!
Issue still exists in version 1.8.2! Please reopen!

**Comment by jaszhix** [comment]
@mad73923 It solved it for me. Provide the same issue template info as the original opener, or open a new issue. Thanks.

**Comment by mad73923** [comment]
```
 * v1.8.2/2018-01-30 07:59
 * Cinnamon 3.6.7
 * Mint 18.3; Kernel: 4.11.0-14-generic x86_64 (64 bit gcc: 5.4.0)
```

## Issue
same as above: Swap usage is 0 bytes, but idicator shows random value
```
top - 20:50:17 up 1 day,  1:59,  1 user,  load average: 0,71, 0,78, 0,68
Tasks: 244 gesamt,   1 laufend, 243 schlafend,   0 gestoppt,   0 Zombie
%CPU(s): 11,4 be,  2,1 sy,  0,0 ni, 84,9 un,  1,6 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Spch :  7761096 gesamt,   240340 frei,  2934488 belegt,  4586268 Puff/Cache
KiB Swap:  9763324 gesamt,  9763324 frei,        0 belegt.  3571208 verfü Spch 
```
![bildschirmfoto vom 2018-02-01 20-52-04](https://user-images.githubusercontent.com/6280987/35699945-d184b92c-0791-11e8-9f03-ca03e5a299f8.png)

## Expected behaviour
Indicator should be zero

**Comment by jaszhix** [comment]
Please check the [issue template](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/ISSUE_TEMPLATE).

Cinnamon 3.6 doesn't reload applets correctly, you need to restart Cinnamon after upgrading applets.

**Comment by mad73923** [comment]
sorry, didn't know I have to restart. Thanks for your work.
