### ISSUE TITLE
IcingTaskManager@json: Bug while touch with cursor #BUG

### ISSUE THREAD

**Issue by PedePanoOriginal** [linuxmint/cinnamon-spices-applets#1610]
Hello guys!
I'm running Linux Mint 18.3 and I'm using this applet. I think its really cool and useful! I'm using the 6.2.2 version, found in Linux Mint applets store. The problem I'm facing is that sometimes, with some specific prgorams i get a unexpected behaviour from the applet. I usually like to just pass my cursor on the icon from an specific program, without clicking at all, just to check what is happening in there. But, sometimes it bugs and, what ending up happening is that the cursor just select the program, just like if I was trying to move it, remember i'm not clicking on the icon:

![image](https://user-images.githubusercontent.com/35506956/35547197-ca0b4f88-055e-11e8-96cf-134597dd6546.png)

Unpinning it from pannel, closing and opening the program, and then pinning it again, fix the problem. I'm a new linux User, so if U could give me some detailed help, i would appreciate.

**Comment by jaszhix** [comment]
Do you have the app button scroll option enabled? That could be switching apps or an app's windows on mouse wheel scroll, but its disabled by default. Not sure I understand what the bug is.

Also be sure to check the [issue template](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/ISSUE_TEMPLATE) next time so we know which applet you're talking about (IcingTaskManager@json). Providing your `~.xsession-errors` file might lead to some clues.

**Comment by PedePanoOriginal** [comment]
Yo man I tried to follow it to discribe my problem,sorry it wasn't enought. 
What happens is that sometimes, with some specific programs, when i pass the cursor on top of it, it selects it as if i'm clicking to move the icon. In the print u cant see my cursor because print screen hides it. But if u look there's a terminal icon flying in there. That happened after i just passed my cursor on top of the terminal icon. At the time terminal was open, and it just was happening with the terminal icon. I've got this bug with chorme icon aswell...

There's the requested file...
[xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/1680159/xsession-errors.txt)

**Comment by jaszhix** [comment]
What's the output of `cat ~/.cinnamon/configs/IcingTaskManager@json/*.json`? Thanks.

**Comment by rianneogi** [comment]
I'm had the same problem recently. Fixed it my closing and reopening the program.

**Comment by jaszhix** [comment]
ITM has a lot of settings, and without a follow up (and reply to my [question](https://github.com/linuxmint/cinnamon-spices-applets/issues/1610#issuecomment-361480087)), I can't look into this any further. I suspect settings were configured for scrolling, which is disabled by default.
