### ISSUE TITLE
clipboard-qr@wrouesnel --- feature request: add export to file (ex. *.svg)

### ISSUE THREAD

**Issue by new-on-github** [linuxmint/cinnamon-spices-applets#1625]
**feature-request**
It would be nice to have a export-to-file-feature. Maybe this is possilble.

@NikoKrause Thanks a lot for the applet.

**Comment by NikoKrause** [comment]
Oh, you don't have to thank me, it's the applet from @wrouesnel

**Comment by new-on-github** [comment]
Oh, sorry, this was my fault. 

Than big thanks to  @wrouesnel
