### ISSUE TITLE
IcingTaskManager@json: Causing a cinnamon crash when closing multiple images

### ISSUE THREAD

**Issue by HuntZero** [linuxmint/cinnamon-spices-applets#1626]
I can't be sure if the issue is to do with Cinnamon or Icing, or if said issue can be reproduced on all systems. Basically, to trigger this crash (consistently without fail) all I need to do is open several high quality images using either the built in picture viewer or a program such as Nomacs, until I've got a stack of say 10 images on the taskbar. Then when I close them all at once, Cinnamon crashes. The first crash always takes about 5 minutes to recover (which lead me to believe the system had frozen before, forcing a hard boot). After that it just instantly tells you Cinnamon has crashed.

The problem only occurs with the 'close all' command, and it doesn't occur with any other programs I've tested so far. Only with images (specifically high quality ones). 

Using Linux Mint 18.3 with a nVidia graphics card, driver version 384.

**Comment by jaszhix** [comment]
Can you reproduce the crash again and then attach `~/.xsession-errors` and `~/.cinnamon/glass.log`?

**Comment by HuntZero** [comment]
Sure, here you go.
[logs.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/1714988/logs.zip)

**Comment by jaszhix** [comment]
Thanks. Can you test this version? Extract it to `~/.local/share/cinnamon/applets`.

[IcingTaskManager@json.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/1721060/IcingTaskManager.json.zip)

**Comment by HuntZero** [comment]
It seemed to work at first, but the problem persists :(

**Comment by jaszhix** [comment]
Please re-open this issue at https://github.com/jaszhix/icingtaskmanager.

**Comment by jaszhix** [comment]
Kamino cloned this issue to [jaszhix/icingtaskmanager](https://github.com/jaszhix/icingtaskmanager/issues/213)
