### ISSUE TITLE
Cheaty applet: Integrate shell cheat sheet

### ISSUE THREAD

**Issue by perette** [linuxmint/cinnamon-spices-applets#1627]
I offer the attached shell cheat sheet covering shell parameter/variable substitution formats and test forms for addition to the Cheaty applet included in LinuxMint 18.3.

[shell-cheatsheet.json.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/1718269/shell-cheatsheet.json.txt)

Thanks.

**Comment by perette** [comment]
How does this file get into the build?  Should I be sending it to the applet's developer via e-mail instead?

**Comment by NikoKrause** [comment]
You can create a PR or ask the author @centurix, if he does that for you.
But you have to ask the author anyway, if he wants this sheet in his applet.

**Comment by Centurix** [comment]
Thanks! I'll add this in with an icon. Which I've just noticed aren't being loaded into the menu properly for some reason. Some St.icon/addActor() thing I suspect.

**Comment by perette** [comment]
Thanks, Centurix!

**Comment by Centurix** [comment]
#1634 Added, plus a couple of other fixes. Made an icon for it too. Thanks @perette !
