### ISSUE TITLE
Fix for multiple similar entries in crontab - rwall@typicalfoobar

### ISSUE THREAD

**Issue by brecciasf** [linuxmint/cinnamon-spices-applets#1628]
rwall@typicalfoobar
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

    "max-instances": -1, 
    "last-edited": 1506905803, 
    "description": "Random Wallpaper Changer\nVersion: 1.0.1", 
    "uuid": "rwall@typicalfoobar", 
    "name": "rwall"


 ```

**Notify author of applet**
@

**Issue**
My 'crontab -l' looks like this:
# During Peak 17:00 (5pm) - 00:59 (1am)
*/5 17-23 * * * DISPLAY=:0.0 /home/holmesd/.local/share/cinnamon/applets/rwall@typicalfoobar/bin/rwall
*/5 00 * * * DISPLAY=:0.0 /home/holmesd/.local/share/cinnamon/applets/rwall@typicalfoobar/bin/rwall
# Every Hr otherwise
0 01-16 * * * DISPLAY=:0.0 /home/holmesd/.local/share/cinnamon/applets/rwall@typicalfoobar/bin/rwall

the current code will remove all entries in the crontab. I have a fix:
=========================Start of Patch ================================
--- rwall.original	2018-02-12 19:24:15.598783248 +0800
+++ rwall	2018-02-13 14:04:43.627252970 +0800
@@ -10,7 +10,9 @@
 if [[ $1 == "cron-toggle" ]];
 then
     # Check if rwall is already installed in crontab
-    crontabGrepRwall="$(crontab -l | grep 'rwall')"
+    cronFreqStr="$(grep cron-frequency= $rwall_root_directory/etc/rwall.ini | cut -f2- -d '=')"
+    crontabGrepRwall=$(crontab -l | grep -e "$cronFreqStr.*rwall$")
+ 
     
     # If the string is empty, then rwall is not in crontab
     if [[ $crontabGrepRwall == "" ]];
@@ -28,7 +30,7 @@
         touch $rwall_root_directory/etc/USING-CRON.lock
     else
         # Remove the cron entry
-        crontab -l | sed "\|$rwall_root_directory/bin/rwall$|d" | crontab -
+        crontab -l | grep -ve "$cronFreqStr.*rwall$" | crontab -
         rm $rwall_root_directory/etc/USING-CRON.lock
     fi
     
@@ -113,7 +115,7 @@
 res=$(grep res= etc/rwall.ini | cut -f2- -d '=')
 
 # Download the html based on our search parameters
-wget "http://alpha.wallhaven.cc/search?q=$q&categories=111&purity=100&resolutions=$res&sorting=random&order=asc" -O tmp/wallhaven.html
+wget "https://alpha.wallhaven.cc/search?q=$q&categories=111&purity=100&resolutions=$res&sorting=random&order=asc" -O tmp/wallhaven.html
 
 # grep the image ID
 #id=$(grep -o -m 1 '<a href="javascript:;" data-id=".*" ' tmp/wallhaven.html | grep -o [0-9].*[0-9])
@@ -126,7 +128,7 @@
 # JPG
 if [ $image_found -eq 1 ];
 then
-	wget_image=$(wget http://alpha.wallhaven.cc/wallpapers/full/wallhaven-$id.jpg -O tmp/wallpaper-$id.jpg)
+	wget_image=$(wget https://alpha.wallhaven.cc/wallpapers/full/wallhaven-$id.jpg -O tmp/wallpaper-$id.jpg)
 	if [ $? -eq 0 ]
 	then
 		image_found=0
@@ -137,7 +139,7 @@
 # PNG
 if [ $image_found -eq 1 ];
 then
-	wget_image=$(wget http://alpha.wallhaven.cc/wallpapers/full/wallhaven-$id.png -O tmp/wallpaper-$id.png)
+	wget_image=$(wget https://alpha.wallhaven.cc/wallpapers/full/wallhaven-$id.png -O tmp/wallpaper-$id.png)
 	if [ $? -eq 0 ]
 	then
 		image_found=0

=========================End of Patch ================================

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
Basic info not provided

**Comment by brecciasf** [comment]
do what you want with the info. just trying to help.
