### ISSUE TITLE
sysmonitor@orcus: Added missing translation for German

### ISSUE THREAD

**Issue by swingnjazz** [linuxmint/cinnamon-spices-applets#1635]
* Applet version/Build date: 1.6.2/2017-10-06 00:40:00 UTC
 * Cinnamon version:
[de.po.gz](https://github.com/linuxmint/cinnamon-spices-applets/files/1752416/de.po.gz)

 Cinnamon 3.4.6
 * Distribution: Debian GNU/Linux buster/sid
 
**Notify author of applet**
@orcuscz

**Issue**
The applet's translation for German is missing. I have added file **de.po** to applet sysmonitor@orcus on my local computer. All parts of the GUI are looking fine for me now.

Please merge it into the code base. I've appended the file to this issue as **de.po.gz** .

Thanks,
swingnjazz

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by OrcusCZ** [comment]
Hi, thanks for the translation. I'll merge it.
