### ISSUE TITLE
sticky@scollins: Add a Restart option to the Menu. 

### ISSUE THREAD

**Issue by thadeupenna** [linuxmint/cinnamon-spices-applets#1636]
* Applet version/Build date 1.2
 * Cinnamon version  3.67
 * Distribution - Mint 18.3

**Notify author of applet**
@collinss 

**Issue**
Please add a option to restart the applet. I have used a symbolic link to Drive in order to synchronize my desktop and my notebook. It works nicely but I have to restart cinnamon in order to update the changes. I think a manual restart would serve for some users rather than periodically check to changes.   

Keep it up the nice work.

**Comment by NikoKrause** [comment]
@thadeupenna How do you restart Cinnamon?

**Comment by thadeupenna** [comment]
There is an applet for that.

**Comment by thadeupenna** [comment]
I can confirm that 
dbus-send --session --dest=org.Cinnamon.LookingGlass --type=method_call /org/Cinnamon/LookingGlass org.Cinnamon.LookingGlass.ReloadExtension string:'sticky@scollins' string:'APPLET'

restart the applet without restarting Cinnamon

**Comment by NikoKrause** [comment]
You can restart Cinnamon with Ctrl+Alt+Esc

**Comment by thadeupenna** [comment]
But I do not want restart Cinnamon as a whole, just the applet.

**Comment by jaszhix** [comment]
Restarting applets broke in Cinnamon 3.6. Sorry. It will be fixed in 3.8.

**Comment by thadeupenna** [comment]
Great news ! Should  I close the issue ?

**Comment by jaszhix** [comment]
Sure, I think this is a Cinnamon bug unfortunately.
