### ISSUE TITLE
betterlock: switch OFF "Show Notification" option does not saved at new boot, please fix !

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-applets#164]
@entelechy

UUID: betterlock

Hi. I test new option that you added recently "Show Notification". It work O.K apart from one bug: when I chose to switch OFF "Show Notification" option it switched OFF O.K but only till reboot !! At reboot or next launching of PC, it will return switched ON !!

Please your kind fix.

**Comment by Nokia808** [comment]
Hi. Just few minutes ago, I received new update of this applet but bug still existing without any improvement! I'm still need to disable notification each time launching or reboot my PC.

**Comment by collinss** [comment]
@Nokia808 This applet has been abandoned for years, the update you saw was due to some translations updates. It will probably be a while before someone fixes this.
