### ISSUE TITLE
IcingTaskManager@json: (cinnamon:120285): Cjs-WARNING **: JS ERROR: Exception in callback for signal: changed::pinned-apps: TypeError: currentAppList.appList.findIndex is not a function

### ISSUE THREAD

**Issue by dcolascione** [linuxmint/cinnamon-spices-applets#1645]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") 
6.3.0
 * Cinnamon version (cinnamon --version)
Cinnamon 3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Debian buster
 * Graphics hardware *and* driver used
Intel driver
 * Snippet or attachment of ~/.cinnamon/glass.log
info t=2018-03-01T09:19:10.232Z Loaded applet IcingTaskManager@json in 264 ms
 * Snippet or attachment of ~/.xsession-errors
(cinnamon:120285): Cjs-WARNING **: JS ERROR: Exception in callback for signal: changed::pinned-apps: TypeError: currentAppList.appList.findIndex is not a function
PinnedFavs.prototype.triggerUpdate@/home/dancol/.local/share/cinnamon/applets/IcingTaskManager@json/3.4/applet.js:101
PinnedFavs.prototype._onFavoritesChange@/home/dancol/.local/share/cinnamon/applets/IcingTaskManager@json/3.4/applet.js:154
_emit@resource:///org/gnome/gjs/modules/signals.js:140
XletSettingsBase.prototype._checkSettings@/usr/share/cinnamon/js/ui/settings.js:585
 ```

**Notify author of applet**
@jaszhix

**Issue**
currentAppList.appList.findIndex doesn't exist

**Steps to reproduce**
Run the applet

**Expected behaviour**
No errors in xsession-errors

**Other information**

**Comment by jaszhix** [comment]
Looks like you're using CJS 3.2, are you able to upgrade to CJS 3.4 on Debian? Because that is what is causing it. Most people are on at least 3.4 at this point.

**Comment by dcolascione** [comment]
I think I'll have to wait for upstream to package it. In the meantime, locally hacking IcingTaskManager to use the two-argument free-function version of findIndex seems to work. Would you take a PR?

**Comment by jaszhix** [comment]
Sure, are you talking about the [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex#Polyfill)? It was in beginning of applet.js at one point, but removed it without realizing some Cinnamon 3.4 users were using it with cjs 3.2.
