### ISSUE TITLE
netusagemonitor@pdcurtis, vnstat@linuxmint.com, and turbonote@iksws.com.br all need to be updated to support new NM library

### ISSUE THREAD

**Issue by coderforlife** [linuxmint/cinnamon-spices-applets#1647]
Distribution: Fedora 27
Author of `netusagemonitor`: @pdcurtis 
Others are unclaimed

All three of these applets cannot be loaded on Fedora 27 (and possibly future versions of Linux Mint or other distros) due to the move from `NMClient` and `NetworkManager` libraries to `NM`. Attempting to add this applet will cause Cinnamon to continually crash on Fedora 27.

More about the issue is discussed in #1616 which talks about it for multicore-sys-monitor@ccadeptic23 and has a fix in PR #1646. A similar fix would be required for each of these applets as well.

**Comment by pdcurtis** [comment]
As a holding action, I have added warnings about issue #1647 to the README.md  for netusagemonitor@pdcurtis in #1729

I have not yet had time to investigated the changes needed to the code to address the problem of the move from NMClient and NetworkManager libraries to NM in Fedora 27.

 @jaszhix and @coderforlife This may take some time as I am going to be away shortly and without fast internet access for over a month. Assistance from those who have contributed to the changes on other applets would be welcome as I have no way to check under Fedora and I believe blind changes are an unacceptable risk

Do we have any idea if and when Mint will change  to NM and if any other distributions are planing a change - I have found nothing with internet searches?

**Comment by NikoKrause** [comment]
> Do we have any idea if and when Mint will change to NM and if any other distributions are planing a change - I have found nothing with internet searches?

You can follow the discussion here:
https://github.com/linuxmint/Cinnamon/pull/6993

**Comment by coderforlife** [comment]
I believe Ubuntu is also in the process or has already migrated, but there is maybe the possibility that it can actually load both libraries simultaneously meaning no crash, but this is word of mouth.

**Comment by pdcurtis** [comment]
This is a holding action which adds warnings about issue #1647 to the README.md 

The original author of this applet was Clem but I made the most recent modifications in response to a bug which prevented it identifying the active device. The solution used code based on the code in netusagemonitor@pdcurtis so I feel responsible for eventually helping to sorti it out! In fact this is much simpler and shorter code so will be ideal for testing the changes required.

@NikoKrause Thanks for the information - it has enabled trace a lot more of the background. It is more complex and urgent than I realised but I will do what I can.

**Comment by coderforlife** [comment]
The fix I created for `multicore-sys-monitor@ccadeptic23` ended up not being so bad and supports both old and new libraries. Near the beginning of the JS file an if statement is used that checks if old or new libraries were previously loaded. In each case the proper library is loaded and then variables are created to map each of the used features from the necessary libraries. It is likely to bit worse in a more network-focused applet, but hopefully isn't too bad.

**Comment by pdcurtis** [comment]
@coderforlife I have already used your code with a few minor changes to update vnstat@linuxmint.com and it works under Mint 18.3 but I have no way to test under Fedora or any other system not using  the new NM libraries.
My plan is to produce a PR with [WIP] flag and hope I could persuade someone to test it under Fedora before it is merged.
I will then do the slightly more difficult task on netusagemonitor@pdcurtis. The only extra unknown is whether the method I have used to stop the network in a hurry will work with NM `this._client.networking_enabled = false;`

I have also had a quick look at turbonote@iksws.com.br and I do not think the library is actually used so it can be fixed by deleting a couple of lines. I have no idea whether it actually works or what it is supposed to do so I am loath to get involved.

**Comment by pdcurtis** [comment]
@coderforlife It would be great if you can test it. Many thanks. I will get it up as soon as possible but I would prefer to wait until the existing PR has been merged as the two pieces of work are in different branches. 

There seem to be very few people who rate Applets these days, even the best only seem to gain a star a month and there are even fewer comments.

**Comment by jaszhix** [comment]
@pdcurtis As far as I know, this is only a Fedora issue with backwards compatibility. I have been running Bionic for months using the old API and testing the new API - but if the old binding lib is unmaintained it makes sense to migrate, though I have trouble finding specific context about the new lib myself - I learned about it through the PR linked earlier.

Site ratings - the stars drop off after a set amount of time with the intention of the ratings being fresh. We have been discussing ways to improve it on Slack (@nyrrad, @collinss, @NikoKrause) - I suspect people don't realize the star ratings depreciate with time, and currently can't be re-cast - which is a bug.

**Comment by pdcurtis** [comment]
I have created a Pull Request for the changes required to vnstat@linuxmint.com based on the fix by @coderforlife

I have marked it Work in Progress  only been able to do very basic checks using a Fedora 27 Cinnamon Spin LiveUSB so any further checks on Fedora 27 or other distros using the libnm library would be very welcome.

In the case of vnstat@linuxmint.com it is possible to check the important part of the code without installing vnstat by commenting out the call to` this._updateGraph(); `on about line 85 and un-commenting the Error Log output at about line 116 in applet.js and using Looking Glass to inspect the log.

**Comment by pdcurtis** [comment]
I have been reading #6993 Network applet: Port to libnm) again and it raises an interesting issue of relevance here - to quote Clem " It's a requirement for Cinnamon to work in major distributions. If libnm isn't properly supported in Debian, it's hard to consider migrating to it."

It seems clear that 'system' applets such as the Network applet must also work in all major distributions but what about the rest of the applets which we are providing? The existence of this issue shows an expectation that the rest of the applets should also be designed to work on all major distributions and be updated when necessary!

I therefore ask the question of some of the writers of the most popular and important applets such as @NikoKrause  and @jaszhix if this is the case and if so what provisions they take to ensure their applets work on all major distributions? In fact which are counted as major distributions by Cinnamon? 

For myself; I have to admit I have done little to check in the past and can see the potential for several problems areas in my applets, especially if backward compatibility is also taken into account. Fortunately some quick checks using a Fedora 27 LiveUSB showed most of my fears were groundless but installation instructions and package requirements certainly need addressing.

**Comment by pdcurtis** [comment]
@coderforlife I have fixed netusagemonitor@pdcurtis and vnstat@linuxmint.com using the code developed by @jaszhix for #1780 which has been tested on fedora 27, debian, mint 19 dev and several other distributions. 
How does one close this issue at least for those two applets? 
Do we need to fix turbonote@iksws.com.br  by removing the reference as you suggested earlier assuming we understand enough of how it is supposed to work or could you edit the title to reflect that only one applet has not had the issue fixed?

**Comment by jaszhix** [comment]
turbonote@iksws.com.br has no maintainer, and we probably don't want to group several applets into one issue. I'll close.

**Comment by coderforlife** [comment]
Thanks!
