### ISSUE TITLE
calendar@simonwiles.net: using %e to show date without a leading zero results in a space before the #

### ISSUE THREAD

**Issue by vertigo220** [linuxmint/cinnamon-spices-applets#1648]
```
 * Applet version/Build date: 2017-10-22
 * Cinnamon version (cinnamon --version): 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 18.3
 * Graphics hardware *and* driver used: i3 540 integrated, not sure of driver
 * Snippet or attachment of ~/.cinnamon/glass.log
[glass.log](https://github.com/linuxmint/cinnamon-spices-applets/files/1782184/glass.log)
 * Snippet or attachment of ~/.xsession-errors: Has lots of info, most seems unrelated, if needed let me know

 ```

**Notify author of applet**
@simonwiles

**Issue**

When showing the day part of the date with %e, it puts a space before it. So instead of 03/5 it says 03/ 5. When showing the leading zero there is no space (03/05).

**Steps to reproduce**

Put %m/%e in the date format box

**Expected behaviour**

It should say 03/5, NOT 03/ 5

**Other information**

**Comment by vertigo220** [comment]
Doesn't look like glass.log uploaded, so here it is:
[glass.log](https://github.com/linuxmint/cinnamon-spices-applets/files/1782208/glass.log)

**Comment by NikoKrause** [comment]
```
%-d
```

**Comment by NikoKrause** [comment]
You seem to have a lot of problems formatting your calendar.
What you are searching for is called *strftime*.
Google is your friend here, e.g. is one result:
http://pubs.opengroup.org/onlinepubs/007908799/xsh/strftime.html

**Comment by vertigo220** [comment]
Thanks. I was just going off of the website linked from the applet (https://www.foragoodstrftime.com/). Maybe the link you provided should be included in addition to or in place of that link. I didn't realize it was it's own thing, thought it was just specific to this calendar and those were the only options. Anyways, got it all set up and it's perfect now, so thanks again!
