### ISSUE TITLE
IcingTaskManager@json: Pinned app arrangement is not saving

### ISSUE THREAD

**Issue by moel85** [linuxmint/cinnamon-spices-applets#1656]
```
 * Applet version/Build date: IcingTaskManager@json: 6.3.0 (#1637) 
 * Cinnamon version 3.4.6
 * Distribution -Linux Mint LMDE 2  cinnamon 64 bit
 * Graphics hardware Card: Intel 2nd Generation Core Processor Family Integrated Graphics
                                            Controller
 * Snippet or attachment of ~/.cinnamon/glass.log -- nothing shows up
 * Snippet or attachment of ~/.xsession-errors -- same as above

 ```

**Notify author of applet**
@jaszhix 

**Issue**
pinned icons don't stay at the place after rearranging them and refreshing cinnamon or the applet itself

**Steps to reproduce**
every time i rearrange the already pinned icons the way i want them to be and refresh the applet or the whole cinnamon they are moved back to their default arrangement.

**Expected behavior**
that they just stay the way i rearranged them :D

**Other information**
-no error or anything else is showing up in "Looking Glasses"

-maybe it helps you finding the issue, when i tell you that i found a ##WORKAROUND :

**BEFORE** i pin the Icons to the task-manager, i just opened the apps in the exact same order i would have arranged their icons anyway. When i pin them **AFTER** that, they stay in that order even after refreshing the extension, cinnamon or restarting my laptop.

Thanks for that great extension btw :)

**Comment by moel85** [comment]
maybe it helps you finding the issue that i found a workaround:

before i pinn the Icons to the taskmanager, i just openened the apps in the exact same order i would have arrangend their icons anyyway. When i pinn them After that, they stay in that order.

**Comment by jaszhix** [comment]
Can you check `~/.xsession-errors` instead? Errors will more likely appear there for Cinnamon 3.4. Thanks.

**Comment by moel85** [comment]
found it :)
Ps.: It shows only thous for 4 errors even though i have more than 4 icons pinned to my taskmanager. Don't know if thats important for you. or thouse erros can appear in different sektions of the xxsession-error-logfile.

(cinnamon:5961): Cjs-WARNING **: JS ERROR: Exception in callback for signal: changed::pinned-apps: TypeError: currentAppList.appList.findIndex is not a function
PinnedFavs.prototype.triggerUpdate@/home/moel/.local/share/cinnamon/applets/IcingTaskManager@json/3.4/applet.js:101
PinnedFavs.prototype._onFavoritesChange@/home/moel/.local/share/cinnamon/applets/IcingTaskManager@json/3.4/applet.js:154
_emit@resource:///org/gnome/gjs/modules/signals.js:140
XletSettingsBase.prototype._checkSettings@/usr/share/cinnamon/js/ui/settings.js:585


(cinnamon:5961): Cjs-WARNING **: JS ERROR: Exception in callback for signal: changed::pinned-apps: TypeError: currentAppList.appList.findIndex is not a function
PinnedFavs.prototype.triggerUpdate@/home/moel/.local/share/cinnamon/applets/IcingTaskManager@json/3.4/applet.js:101
PinnedFavs.prototype._onFavoritesChange@/home/moel/.local/share/cinnamon/applets/IcingTaskManager@json/3.4/applet.js:154
_emit@resource:///org/gnome/gjs/modules/signals.js:140
XletSettingsBase.prototype._checkSettings@/usr/share/cinnamon/js/ui/settings.js:585


(cinnamon:5961): Cjs-WARNING **: JS ERROR: Exception in callback for signal: changed::pinned-apps: TypeError: currentAppList.appList.findIndex is not a function
PinnedFavs.prototype.triggerUpdate@/home/moel/.local/share/cinnamon/applets/IcingTaskManager@json/3.4/applet.js:101
PinnedFavs.prototype._onFavoritesChange@/home/moel/.local/share/cinnamon/applets/IcingTaskManager@json/3.4/applet.js:154
_emit@resource:///org/gnome/gjs/modules/signals.js:140
XletSettingsBase.prototype._checkSettings@/usr/share/cinnamon/js/ui/settings.js:585


(cinnamon:5961): Cjs-WARNING **: JS ERROR: Exception in callback for signal: changed::pinned-apps: TypeError: currentAppList.appList.findIndex is not a function
PinnedFavs.prototype.triggerUpdate@/home/moel/.local/share/cinnamon/applets/IcingTaskManager@json/3.4/applet.js:101
PinnedFavs.prototype._onFavoritesChange@/home/moel/.local/share/cinnamon/applets/IcingTaskManager@json/3.4/applet.js:154
_emit@resource:///org/gnome/gjs/modules/signals.js:140
XletSettingsBase.prototype._checkSettings@/usr/share/cinnamon/js/ui/settings.js:585
