### ISSUE TITLE
[bash-sensors@pkkk] Feature request

### ISSUE THREAD

**Issue by tux2000** [linuxmint/cinnamon-spices-applets#1664]
It would be nice if multiple instances of the bash-sensors@pkkk applet could be added to cinnamon, each running a different command.

```
 * Applet version: 0.6
 * Cinnamon version: Cinnamon 3.6.7
 * Distribution: Mint 18.3

 ```

No author assigned to applet according to : https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/CODEOWNERS 

**Issue**
If one instance is added to cinnamon, no second instance can be added.

**Steps to reproduce**
Add one instance through the applet manager. Try to add a second one. The "+" button is not active.

**Expected behaviour**
It would be nice if several independent instances could be active.

**Other information**

**Comment by NikoKrause** [comment]
Some applets do have issues with using multiple instances. I never used this applet. Maybe you can try and checkout if multiple instances create issues. It's very easy to activate this feature.
Open the file `metadata.json` in the directory `~/.local/share/cinnamon/applets/bash-sensors@pkkk` and add the line
```
    "max-instances": -1, 
```
Save the file and restart Cinnamon. After that you'll be able to add as many instances as you want.

Please report, if this causes any issues or not, so this feature can be added here.

**Comment by tux2000** [comment]
Thanks for looking into this, @NikoKrause 
Indeed it is possible to add more instances when adding `max-instances: -1` to the `metadata.json`. However, the new instances show the same information as the first one (i.e. the same command is executed) and the configure dialog is completely blank with no configurable options for all instances. So I guess how this applet retrieves and saves configurations is not compatible yet with multiple instances...

**Comment by NikoKrause** [comment]
Then it's one of those applets I mentioned, which has issues with multiple instances.

**Comment by tux2000** [comment]
Too bad, but maybe an expert can easily fix the storage process to be instance specific... Lets hope somebody has the time since I think this applet can be quite powerful.

**Comment by tux2000** [comment]
I think I fixed it... Its working for me at least. I submitted a pull request to allow integration in the main branch.

**Comment by NikoKrause** [comment]
Thanks for the PR. I merged it.
