### ISSUE TITLE
IcingTaskManager@json Some apps appear in window list even after being closed

### ISSUE THREAD

**Issue by jsalatiel** [linuxmint/cinnamon-spices-applets#1668]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") : 6.3 
 * Cinnamon version (cinnamon --version): 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) : Mint 18.3
 * Graphics hardware *and* driver used/: Intel
 ```

**Notify author of applet**
@jaszhix 

**Issue**
There are a few application that are kept in window list even after them being closed.
Unfortunatelly this does not happen everytime, but when it does, i cant see the process in the 'ps' output and if i hover the mouse over the window list i see no thumbnail for that application.
Examples: LibreOffice , VirtualBox.

**Comment by jaszhix** [comment]
Please pastebin:

 * Output of `dpkg -s cjs`
 * ~/.cinnamon/configs/IcingTaskManager@json/*.json
 * Snippet or attachment of ~/.xsession-errors after the error occurs
 * Version of CJS in use

Thanks.

**Comment by jsalatiel** [comment]
Output of dpkg -s cjs
```
# dpkg -s cjs
Package: cjs
Status: install ok installed
Priority: optional
Section: interpreters
Installed-Size: 45
Maintainer: Linux Mint <root@linuxmint.com>
Architecture: amd64
Version: 3.6.1+sylvia
Depends: libc6 (>= 2.2.5), libcjs0-libmozjs-38-0, libcjs0f (>= 3.6.1+sylvia), libglib2.0-0 (>= 2.42.0), libstdc++6 (>= 4.1.1)
Description: Mozilla-based javascript bindings for the Cinnamon platform
 Makes it possible for applications to use all of Cinnamon's platform
 libraries using the JavaScript language. It's mainly based on the
 Mozilla JavaScript engine and the GObject introspection framework.
 .
 This package contains the interactive console application.

```
\# cat ~/.cinnamon/configs/IcingTaskManager@json/*.json
https://gist.github.com/15cd8dc7f0a2a066d63948bc97da0c44

\# cat ~/.xsession-errors
https://gist.github.com/87f3ac8a17131fe0ba162d3bf4fad1eb

**Comment by jsalatiel** [comment]
Forgot to say that if i right click the window list. enter the preferences and change ANY setting of IcingTaskManager, the "ghost" window list entry will vanish.

**Comment by jsalatiel** [comment]
Do you need any more info ?

**Comment by jsalatiel** [comment]
So,  i did a clean linux mint 18.3 install and tried again.
i found out a easy way top replicate the problem
1) open any ODS file in libreoffice calc ( try this: http://file-examples.com/wp-content/uploads/2017/10/file_example_ODS_100.ods)
2) close libreoffice calc
3) open gnome-terminal (to see any errors)
4) run sofffice from the terminal
6) On the opened window, pick up the file from item 1 in RECENT and open it ( Calc will open )
7) Click NEW -> Spreadsheet
8) Close the first window (With the file already open)
9) Close the new blank spreadsheet window
10) The empty icon will be in task list.

**Comment by jaszhix** [comment]
Let's move the discussion into https://github.com/jaszhix/icingtaskmanager/issues/186, its hard to keep track of the same issues in two places. ;)
