### ISSUE TITLE
betterlock: Russian language

### ISSUE THREAD

**Issue by Faust30000** [linuxmint/cinnamon-spices-applets#167]
Hello. I did applet translation into Russian.
[ru.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/818937/ru.po.zip)

**Comment by NikoKrause** [comment]
Which applet?

**Comment by Faust30000** [comment]
betterlock

**Comment by NikoKrause** [comment]
Could you create a pull request for that?

**Comment by Faust30000** [comment]
It does not work to create.

**Comment by NikoKrause** [comment]
@Faust30000 
https://github.com/NikoKrause/CinnVIIStarkMenu/issues/28
