### ISSUE TITLE
weather@mockturtl: Get WOEID problem (502 Bad Gateway)

### ISSUE THREAD

**Issue by lossurdo** [linuxmint/cinnamon-spices-applets#1671]
**Information**

* Version 1.14.0
* Cinnamon 3.6.7
* Mint 18.3

@mockturtl

**Issue**
When trying to get the WOEID code the page is not loading. URL is: http://woeid.rosselliot.co.nz/

**Steps to reproduce**
1. Right-click on Applet
2. Configure...
3. Click Get WOEID button

**Expected behaviour**
Page loading correctly.

**Other information**
I tried another WOEID site and I found this one http://www.woeidlookup.com/ which works perfectly.
I can change the code and pull request this new WOEID website.

![screenshot from 2018-03-13 20-17-33](https://user-images.githubusercontent.com/3332736/37375544-d358ea8e-26fe-11e8-8d92-4ef4e00526da.png)

**Comment by mockturtl** [comment]
Thanks for the report.  I've emailed the owner of rosselliot.co.nz, hopefully it will be fixed soon.

> I tried another WOEID site and I found this one http://www.woeidlookup.com/ which works perfectly.

I get no results there. (London, New York, etc)

**Comment by mockturtl** [comment]
> I've emailed the owner of rosselliot.co.nz, hopefully it will be fixed soon.

It's fixed now.

**Comment by lossurdo** [comment]
Great! Tests ok. Thanks.
