### ISSUE TITLE
BOGUS: gputemperature@silentage.com

### ISSUE THREAD

**Issue by TriMoon** [linuxmint/cinnamon-spices-applets#1715]
```
 * Applet version/Build date: The version that is available at writing this
 * Cinnamon version 3.4.6
 * Distribution - Debian
 * Graphics hardware: not relevant
 * Snippet or attachment of ~/.cinnamon/glass.log: Nothing mentioned about this applet
 * Snippet or attachment of ~/.xsession-errors: Nothing mentioned about this applet

 ```

**Notify author of applet**
{
    "author": "none",
    "original_author": "silentage.com"
}

**Issue**
Nothing happens when unzipping under homedir as instructed and restarting cinnamon
It isn't even shown in the applets listing...

**Comment by jaszhix** [comment]
From the readme:
> Decompress the zip file to ~/.local/share/cinnamon/applets

If you are installing it to the root of your home directory it won't work.

The recommended way to install applets is through Cinnamon settings. Go to Settings -> Applets -> Download tab -> Click download icon next to "GPU Temperature" -> Manage tab -> Select the applet and click the + icon at the bottom. Its working for me.

**Comment by NikoKrause** [comment]
![screenshot-area-2018-03-21-220047](https://user-images.githubusercontent.com/8415124/37737205-6531a446-2d53-11e8-9583-2e96761f917d.png)
