### ISSUE TITLE
clipboard-qr@wrouesnel  applet does not generate qr code for numbers

### ISSUE THREAD

**Issue by v-pionnier** [linuxmint/cinnamon-spices-applets#1718]
clipboard-qr@wrouesnel 

```
 * Applet version 1.12/2018-03-05
 * Cinnamon version 3.6.7
 * Distribution - Mint 18.3
  ```

Copy some number to clipboard, like 1234567 or 3.1415926, and click the applet - you'll find out that no QR code is generated.

**Comment by NikoKrause** [comment]
@wrouesnel

**Comment by marvinwankersteen** [comment]
Similar problem.
I tried to copy a tracking number of DHL:
```
Works:      JJD0003900
Dont works: JJD00039001
```

```
Applet:   1.12
Cinnamon: 3.6.7
OS:       Mint 18.3
```

**Comment by icarter09** [comment]
Cinnamon 3.8.9
Linux Mint 19 64bit
Last modified: 2018-03-05 22:04 UTC

Verified that this is still a bug on latest version of Cinnamon and Mint.
