### ISSUE TITLE
All spices: it is unclear how one can add comments on a spice webpage.

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/cinnamon-spices-applets#172]
I arrived at the webpage pictured (in part) below ([ur](https://cinnamon-spices.linuxmint.com/extensions/view/24)l), having used the 'more info' button in Cinnamon. So far as I can tell, the page gives no indication of how one can add a comment. (Also, the spice's strapline - in this case, 'Compiz shall live again!' itself rather looks like a user comment.)

![image](https://cloud.githubusercontent.com/assets/9998846/23637205/43fa400a-02d2-11e7-88c4-640eb04832b0.png)

Compare e.g. [this webpage](https://cinnamon-spices.linuxmint.com/extensions/view/25) for (i.e.: of) another spice. Now, it seems to me that, in order to encourage participation, _some sort of login and/or signup link or field would be appropriate._

_If this is the incorrect place to report this problem / request this enhancement, please direct me to the right place._ Thank you.

**Comment by Odyseus** [comment]
Hello, @ACinnamonUserInUK.

Spices website doesn't have a comment system as of yet. They are working on it.

#### Quote from the last monthly news on [Linux Mint blog](http://blog.linuxmint.com/?p=3228)

> Work continues in the design team on revamping the authentication, comments and rating systems to make the website compatible with the Facebook, Google and Github APIs.

**Comment by ACinnamonUserInUK** [comment]
@Odyseuss: aha; thanks for the information. (And that site does look nice, aside from the problem I pointed out.) Should I just leave my comment here, then?

**Comment by MrElectroNick** [comment]
@ACinnamonUserInUK comments and new rating system code is ready and waiting for deployment. Spices website will be updated quite soon.

**Comment by NikoKrause** [comment]
The website has now oauth login with GitHub, Facebook and Google+ and it's possible to leave comments. So I'm closing this.
