### ISSUE TITLE
sticky@scollins: Not show translated text in applet description

### ISSUE THREAD

**Issue by xearonet** [linuxmint/cinnamon-spices-applets#1745]
sticky@scollins
```
 * Applet version/Build date: 1.2
 * Cinnamon version: 3.6.7
 * Distribution - Mint 18.3 Cinnamon 64bit
 * Graphics hardware *and* driver used : AMD Radeon 6850
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@collinss 
@jaszhix 

**Issue**
Translated to polish text not appear in describe box in "About..." window of applet. I check twice .po file and everything is good. 
Box showing only "rski".

Other problem: add strings for new options to .pot file so we may update translation

**Steps to reproduce**

Open "About..." window.

**Expected behaviour**
Full polish translation of desciption of applet.

**Other information**
![sshot](https://user-images.githubusercontent.com/22504894/38455235-8febd970-3a75-11e8-97a1-e22e9948164d.png)

**Comment by NikoKrause** [comment]
Please restart Cinnamon and check out, if the problem still persists. It looks good here on the same system as yours LM 18.3.
![screenshot-cinnamon-2018-04-07-170710](https://user-images.githubusercontent.com/8415124/38456573-30c2b7be-3a86-11e8-976c-5a65112694db.png)

If you find untranslated strings, you can update the translation template (.pot file) with the following command in the applets directory:
```
cinnamon-json-makepot --js po/sticky.pot
```

**Comment by xearonet** [comment]
OK. Restart Cinnamon works. Sorry by that.
BR
