### ISSUE TITLE
hamster@projecthamster.wordpress.com - schema not found

### ISSUE THREAD

**Issue by vlatkoB** [linuxmint/cinnamon-spices-applets#1755]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
0.2
 * Cinnamon version (cinnamon --version)
3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
error t=2018-04-08T14:14:00Z Schema "org.cinnamon.hamster-applet" not found.
error t=2018-04-08T14:14:00Z [Applet "hamster@projecthamster.wordpress.com"]: Failed to evaluate 'main' function on applet: hamster@projecthamster.wordpress.com/28
error t=2018-04-08T14:14:00Z Could not load applet hamster@projecthamster.wordpress.com
 * Snippet or attachment of ~/.xsession-errors
hamster not mentioned in .xsession-errors
 ```

**Issue**
Hamster applet unable to start (or just show icon) due to missing schema. Files `org.cinnamon.hamster-applet.gschema.xml` and `gschemas.compiled` present in `~/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com/schemas` directory.
On restarting cinnamon, two `hamster` processes are started: `hamster-service` and `hamster-window-service`, so it seems just the icon display is not working.

**Steps to reproduce**
Install applet via `+ Add applets to panel`

**Expected behaviour**

**Other information**

**Comment by vlatkoB** [comment]
I tried to use the old code from https://github.com/linuxmint/cinnamon-spices-applets/commit/bcd6d7e1987354ae2d981b5f232fee693c675a16 in `convenience.js` and entered fixed path value to `~/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com/schemas`  and I'm getting
`error t=2018-04-08T20:45:47Z Failed to open file “~/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com/schemas/gschemas.compiled”: open() failed: No such file or directory`
but when I copy that path to `ll` in shell, seems the path is correct and file exists.
`-rw-r--r-- 1 vlatko users 356 Apr  8 13:58 '/home/vlatko/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com/schemas/gschemas.compiled`

However, if I put the absolute path `/home/vlatko/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com/schemas`, the error changes to 

`error t=2018-04-08T20:53:32Z GSettings schema not found: [boxed instance proxy GIName:Gio.SettingsSchema jsobj@0x7febc6c9e250 native@0x5622fa1b90f0]
`

**Comment by vlatkoB** [comment]
Tried solution to identical issue form old original repo at https://github.com/projecthamster/cinnamon-applet/issues/18, but the error now is
```
error t=2018-04-08T22:27:52Z redeclaration of formal parameter schema
error t=2018-04-08T22:27:52Z [Applet "hamster@projecthamster.wordpress.com"]: Error importing applet.js from hamster@projecthamster.wordpress.com
```

**Comment by Odyseus** [comment]
Hello, @vlatkoB.

There are several problems clashing in here. Follow the bellow steps to make the applet work.

1. Completely remove the applet and re-install it from Cinnamon's applets manager (do not edit anything from the applet's code).
2. Install the settings schema with the following command (It will ask for password): `pkexec cinnamon-schema-install /full/path/to/schemas/org.cinnamon.hamster-applet.gschema.xml`
3. And lastly, set execution permissions to the **prefs.js** file (located inside the xlet folder).
4. Now place it in any panel and it should work immediately.

### Problems with xlets installation process

@collinss (?)

1. Schema files found inside sub-folders are ignored (not installed when an xlet is installed).
2. Xlet's file permissions aren't retained. If I [download the applet](https://cinnamon-spices.linuxmint.com/applets/view/140) mentioned in this issue from its Spices page and extract it, the **prefs.js** file has execution permissions. But the downloaded (and ultimately installed) package from the applets manager has all permissions changed.

**Comment by vlatkoB** [comment]
Hi @Odyseus,
thanks, that solved the problem. :-)

A note for __Arch__ users. 
`cinnamon-schema-install` (and `cinnamon-schema-remove`) are not installed with cinnamon package, so to use this method, you must create that file(s) in `/user/bin` directory manually. Script code for both can be found at https://github.com/linuxmint/Cinnamon/tree/master/files/usr/bin.

**Comment by NikoKrause** [comment]
I moved the gschema.xml file to the parent directory, so Cinnamon installs it properly.
The missing permission has to be investigated.
