### ISSUE TITLE
gpaste-reloaded@feuerfuchs.eu, todo@threefi crashes cinnamon

### ISSUE THREAD

**Issue by timabell** [linuxmint/cinnamon-spices-applets#1757]
gpaste reloaded puts cinnamon into a crash loop even after a reboot.

This is pretty serious as it makes the computer completely unusable. I think this applet should be pulled from the applet installer until this is fixed.

I have installed gir1.2-gpaste-4.0 as instructed to no effect.

    sudo apt install gir1.2-gpaste-4.0

I now have to work out how to fix my broken cinnamon without re-installing the OS.

$ cinnamon --version
Cinnamon 3.6.7
$ cat /etc/issue
Linux Mint 18.3 Sylvia \n \l

dell xps13 9350

[glass.log](https://github.com/linuxmint/cinnamon-spices-applets/files/1890642/glass.log)
[xsession-errors.log](https://github.com/linuxmint/cinnamon-spices-applets/files/1890645/xsession-errors.log)

@Feuerfuchs 

---
Issue #370 was mentioned this but is a year old and closed so opening a new issue.
This behaviour was also reported in the comments here https://cinnamon-spices.linuxmint.com/applets/view/237 so not it's just me.

**Comment by timabell** [comment]
I got out of the crash loop by uninstalling the gir package, logging out and in again which stopped the crash, and then removing the applet.

**Comment by claudiux** [comment]
I had the same problem. Then I tried this : https://winaero.com/blog/how-to-add-a-clipboard-history-applet-to-cinnamon/
It works perfectly now.

**Comment by KeyJoo** [comment]
I installed today this applet "Cinnamon applet todo" in Linux Mint 18.3 Cinnamon, and edit todo.list then my desktop was freezed (( only mouse cursor can move. After restart system I try login. I see only black screen and mouse cursor. How delete this applet from my system?

**Comment by KeyJoo** [comment]
I can't `startx` << No GUI ((

**Comment by timabell** [comment]
@KeyJoo try ctrl-alt-f1 to switch to a non-gui terminal
then log in
then `sudo apt remove` the gir package you installed

**Comment by claudiux** [comment]
@KeyJoo To remove an applet:
ctrl-alt-F1 to switch to a real console.
After login:
`cd ~/.local/share/cinnamon/applets`
`ls -1A`
The list of the installed applets appears. The 'todo' applet is in 'todo@threefi' directory.
Remove this directory:
`rm -rf todo@threefi`

Then restart mdm and logout from the console:
`sudo service mdm restart && logout`

**Comment by icarter09** [comment]
Cinnamon 3.8.8
Linux Mint 19 64bit
AMD RS780M

Installed the todo applet, edited the todo.list and did not experience the desktop freezing. 

@timabell @KeyJoo @claudiux: are you still experiencing this issue?

**Comment by claudiux** [comment]
It works perfectly for me on:
Cinnamon 3.8.8
Linux Mint 19 64 bits
i7-5500U

**Comment by icarter09** [comment]
@jaszhix can this issue be closed?
