### ISSUE TITLE
[windowlist@cobinja.de] Selected app are not clickable

### ISSUE THREAD

**Issue by KevinNadaud** [linuxmint/cinnamon-spices-applets#1777]
```
 * Applet version: 2.2
 * Cinnamon version: 3.6.7
 * Distribution: Mint 18.3
 * Graphics hardware *and* driver used, Intel 4th Gen Core Processor Integrated Graphics Controller GLX Renderer: Mesa DRI Intel Haswell Mobile GLX Version: 3.0 Mesa 17.2.8 
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```
[bug_cobininja.tar.gz](https://github.com/linuxmint/cinnamon-spices-applets/files/1915592/bug_cobininja.tar.gz)

**Notify author of applet**
@Cobinja 

**Issue**
The app you selected using the task bar is not clickable, you cannot do anything with it

. If you re-selected it using the applet of using alt-tab, you can click on it. 

**Steps to reproduce**
The bug is quite random, so it is hard to reproduced it.

**Expected behaviour**
The selected app should be clickable/usable.

**Other information**

**Comment by Marfisc** [comment]
I seem to have hit the same bug. Once you hit a "streak", apps freeze often, but apparently randomly. The app does not react to keyboard input or clicks. But the computer does not hang. Applets and global hotekys can be interacted with.

Differently to the OP, I have to select a *different* app. Just re-selecting does not help. I have to select a different app through the applet or alt-tab.

* Linux Mint 18.3
* Cinnanom 3.6.7
* Intel Skylake Integrated Graphics, (afaik driver is i915)

**Comment by Cobinja** [comment]
I will continue tracking this bug in https://github.com/Cobinja/CobiWindowList/issues/12
