### ISSUE TITLE
[Cinnamenu@json] Search field line-height should be greater

### ISSUE THREAD

**Issue by Martin1887** [linuxmint/cinnamon-spices-applets#1781]
```
* Last applet version
* Linux Mint 18.3 and Fedora 27
 ```

@jaszhix I have experimented problems visualizing letters like 'g' and 'j' in the search field. I think that the problem is the `line-height` property of the search field, although the problem could be the GTK theme or the fond used too. I think that a value proper for all themes and fonts should exist. You can test the problem easily using Fira Sans Regular 10 as font and Arc as GTK theme. Thanks.

**Steps to reproduce**
Open menu and write in the search field. Letters with down gliphs like 'j' and 'g' are not fully visible.
![captura de pantalla de 2018-04-22 12-24-34](https://user-images.githubusercontent.com/4211771/39093981-c0e61784-4628-11e8-9320-e03c145d90fb.png)

**Expected behaviour**
Text is correctly visualized, with letters as 'j' and 'g' fully visible.

**Other information**
Tested on Fedora 27 with Fira Sans font and Arc theme and Linux Mint with default font and Windows 10 GTK theme.

**Comment by Martin1887** [comment]
The issue has been partially resolved but still the letters are not fully visible.

![imagen](https://user-images.githubusercontent.com/4211771/39590963-9f899cb8-4f02-11e8-9b1c-49fe7c51d0a5.png)

In addition, with a `cursor: text` in the search box it will be better.


Thanks.

**Comment by jaszhix** [comment]
I'm using Mint Y, which is based on Arc, and it shouldn't be too different. I was reproducing this myself, and this is how it looks for me now. Are you sure you're on 3.2.1?

![screenshot from 2018-05-03 15-58-24](https://user-images.githubusercontent.com/6859057/39602555-1a7776e2-4eeb-11e8-82b6-319c38acbb9b.png)

**Comment by germanfr** [comment]
I had a similar issue with notification labels with a particular theme. We never found a solution, the bug fixed itself in some update. See the discussion here, maybe it helps: https://github.com/zagortenay333/numix-cinnamon/issues/19

**Comment by Martin1887** [comment]
Hello.

I have found that the problem is not the GTK theme, but the Cinnamon theme. My theme is a modified Arc-Dark-Red that uses Fira Sans font of 10.5 pt. I think that the problem can be in the adjustment of the search box height using pixels instead `line-height`. Maybe setting the search box `height` to `auto` and the `line-height` to for instance `1.25` would fix the problem.

This is the font settings of my Cinnamon theme:
```
stage {
  font-family: "Fira Sans", sans-serif;
  font-size: 10.5pt;
  color: #a4a4a4; }
```

Thanks.

**Comment by Martin1887** [comment]
@jaszhix, has you planned to apply the @smurphos fix?

Thanks.

**Comment by jaszhix** [comment]
Merged https://github.com/jaszhix/applets/commit/7a560669e8d5724814bf309ae2fb191758be1f92. I think I originally did this to work around around a layout issue when the search entry was on the top of the menu, but stale code now.

**Comment by Martin1887** [comment]
Sadly, this fix has worsened the problem in my theme:

![imagen](https://user-images.githubusercontent.com/4211771/39714417-4da8790c-522a-11e8-9bc5-11eace33d0ac.png)

If you want, @jaszhix, I can send to you the theme to debug the CSS issue. This is not a big problem for me, but I think that this issue can be happened to other users, and it dirties an awesome applet.

**Comment by jaszhix** [comment]
Which theme is it? Maybe this is a theme issue? It looks fine on Mint Y.

**Comment by jaszhix** [comment]
![screenshot from 2018-05-07 12-24-45](https://user-images.githubusercontent.com/6859057/39715110-c91cc5ae-51f1-11e8-815e-ca8c6289c99d.png)

It looks like this for me... @JosephMcc recently fixed this in Mint Y. https://github.com/linuxmint/mint-themes/commit/634411248d2f55122a561493709d03e6cf997101

**Comment by Martin1887** [comment]
Sorry, since that screenshot does not seem my theme I have compared it and I don't know which changes I did.

I have fixed it changing the padding of `#menu-search-entry` from `7px` to `1px 4px`. If you have not found the issue in other themes probably this is only a problem in my theme and this issue can be definitely closed.

Thanks.
