### ISSUE TITLE
CinnVIIStarkMenu@NikoKrause: invisible item

### ISSUE THREAD

**Issue by germanfr** [linuxmint/cinnamon-spices-applets#1791]
```
 * Applet version: latest
 * Cinnamon version 3.8
 ```
@NikoKrause 

**Issue**
There is a piece of what seems to be dead code [here](https://github.com/linuxmint/cinnamon-spices-applets/blob/5b6904e5da3b50950307ce2ef4ed4c15067672bb/CinnVIIStarkMenu%40NikoKrause/files/CinnVIIStarkMenu%40NikoKrause/3.4/applet.js#L1088) that is creating a `StTable` with no use I can see, but it creates a bug in that the side panel gets extra padding because of this (note the big left padding in the hovered item).

![screenshot from 2018-05-01 00-56-33](https://user-images.githubusercontent.com/10391266/39454289-c07888aa-4cda-11e8-9b67-93282084bcf6.png)

It is a table with a `media-playback-start` icon and a label, but I haven't seen that icon anywhere in the applet.

**Steps to reproduce**
The issue appears when you use a theme that separates the icon from the label using _spacing_ instead of just _padding_ on the label. Doing that effectively creates an extra space between the icon and the invisible table.

**Other information**
I've commented it out and I've seen no issue.

**Comment by germanfr** [comment]
Oh, also @NikoKrause please add 3.8 to the `metadata.json` or this won't load :(

**Comment by NikoKrause** [comment]
Hey, the St.Table is indeed dead code. I'll try to update this soon.

I added 3.8 a few days ago to the metadata.json. (The cache doesn't seem to update here.)

**Comment by NikoKrause** [comment]
Took a while ;)
