### ISSUE TITLE
Cinnamenu@json: Context menu item labels are truncated

### ISSUE THREAD

**Issue by ssspacez** [linuxmint/cinnamon-spices-applets#1793]
Cinnamenu@json

```
 * Cinnamenu 3.2
 * Cinnamon 3.6.7
 * Linux Mint 18.3
 ```

**Notify author of applet**
@jaszhix

**Issue**
The box with options that opens when you click on a icon **cut the text**, it should be bigger or adjust automatically.

Notice the "..." on each item:
![box](https://user-images.githubusercontent.com/34775187/39556778-3d1fe98c-4e59-11e8-8761-34372e158f46.png)

**Steps to reproduce**
Right-click on an icon inside the menu.

**Expected behaviour**
You can read the whole thing.

**Comment by jaszhix** [comment]
@ssspacez I think I have a fix, but not sure if it will truncate text outside English locales, can you test this?

[Cinnamenu@json-3.2.1.tar.gz](https://github.com/linuxmint/cinnamon-spices-applets/files/1970468/Cinnamenu.json-3.2.1.tar.gz)

**Comment by ssspacez** [comment]
Sorry I'm not a dev, I think you(or someone else) could test this on a VM with all the languages and check if it's working.

**Comment by jaszhix** [comment]
No, but its an issue you want fixed, you don't have to know how to program to help fix something. This isn't my job...

**Comment by ssspacez** [comment]
Sorry I thought I had to compile it and do more complex stuff, it's just a reinstall to test it.

**3.2.1**: the issue is not fixed yet, nothing has changed, it's just the when the **icons** are big, list mode works fine:

Icons:
![box2](https://user-images.githubusercontent.com/34775187/39601475-658364b8-4ef8-11e8-83cc-3121e532edf1.png)


List:
![box3](https://user-images.githubusercontent.com/34775187/39601400-26617838-4ef8-11e8-8d3d-1c8583f24bf5.png)

**Comment by jaszhix** [comment]
That styling from the first crop looks like the old styling. I'm using the same theme it looks like.

![screenshot from 2018-05-03 15-54-45](https://user-images.githubusercontent.com/6859057/39602399-a8443a56-4eea-11e8-871f-4d71daa4a38c.png)
