### ISSUE TITLE
placesCenter@scollins

### ISSUE THREAD

**Issue by ssspacez** [linuxmint/cinnamon-spices-applets#1797]
```
 * Version 2.1
 * Cinnamon version 3.6.7
 * Linux Mint 18.3
 ```

**Notify author of applet**
@collinss

**Issue**
Search is not working.

I get an error notification with "Fail to execute (...) permission denied (...) /home/.../**search.py**."

**Steps to reproduce**
Click on the search icon.

**Comment by collinss** [comment]
Can you please check the permissions of the file ```~/.local/share/cinnamon/applets/placesCenter@scollins/search.py```? It sounds like the executable bit in the file permissions isn't getting retained when the applet is installed through cinnamon-settings. If so, the issue will be resolved by https://github.com/linuxmint/Cinnamon/pull/7546. In the mean time you should be able to fix the issue by changing the permissions on this file.

**Comment by ssspacez** [comment]
Yes, after **checking the box to make it executable** it's working, thank you!

**Comment by collinss** [comment]
You're welcome
