### ISSUE TITLE
[windowlist@cobinja.de] No Active-Application/Window Indicator

### ISSUE THREAD

**Issue by khatamnejad** [linuxmint/cinnamon-spices-applets#1798]
```
 * Applet version: 2.2
 * Cinnamon version: 3.4.6
 ```
The default Window List applet has an indicator for the current active application in form of a line under the application icon+name. It would be a nice feature for CobiWindowList as well.

**Comment by khatamnejad** [comment]
I am using Carta.

**Comment by NikoKrause** [comment]
Author of the Carta theme is @andr35

**Comment by khatamnejad** [comment]
The problem is not the theme though I believe as the default window list applet works without any problem with this theme; I also used to use another window list (deprecated now) which does not have problem showing active application in this theme.

**Comment by Cobinja** [comment]
![carta](https://user-images.githubusercontent.com/1781127/39710024-e709e0d6-521b-11e8-97db-bd1eee0fc396.png)
As far as i can tell, Carta works fine with my applet

**Comment by khatamnejad** [comment]
It does not work for me.

**Comment by NikoKrause** [comment]
Is your applet and theme up to date?
Applet version right now is 2018-04-11, 08:55 UTC
and Carta: 2018-04-17, 16:01 UTC

**Comment by NikoKrause** [comment]
Maybe your panel height is too small and the indicators disappear. Try to change the height of your panel.

**Comment by khatamnejad** [comment]
Okay! I change the panel height and a very thin line appeared under the active app item. However I think there are three issues here:

1. As said before, the line is thinner (I think its height is one pixel) than what it should be comparing to the screenshot above and standard window list applet.
2. When I move the height selector scroller, the line appears and disappears for every other step.
3. Before start to manually changing the height of the panel, I was using the **default** and **non-customized** value of it; One expect that the applet works perfectly with default values, is that right?

**Comment by NikoKrause** [comment]
@khatamnejad Can you post the output from the following two commands?
```
date -u -d "@$(grep "last" ~/.local/share/cinnamon/applets/windowlist@cobinja.de/metadata.json | cut -d " " -f6)"

date -u -d "@$(grep "last" ~/.themes/Carta/metadata.json | cut -d " " -f6)"
```

**Comment by khatamnejad** [comment]
@NikoKrause

Both commands return with error; The first one returns `date: invalid date ‘@1523436915,’` and the second one returns `date: invalid date ‘@’` error.

**Comment by Cobinja** [comment]
Do you mean it's not fixed in the downloadable version there or the changelog on the page?
The fix is there

**Comment by khatamnejad** [comment]
Yes. It is fixed in the last version. However I think it would have been great to have a 2.2.x version or something to avoid confusion.

**Comment by Cobinja** [comment]
I will update the changelog with the next patch/release
