### ISSUE TITLE
[show-hide-applets@mohammad-sn]  Always showing on hover even when not set

### ISSUE THREAD

**Issue by donlencho** [linuxmint/cinnamon-spices-applets#1801]
show-hide-applets@mohammad-sn
```
 * Applet version/Build date: 2018-2-24
 * Cinnamon version: 3.6.7
 * Distribution: Mint 18.3
 ```

**Notify author of applet**
@mohammad-sn 

**Issue**
The option to NOT show on hover doesn't seem to work any more, it's always showing on hover even when not chosen in the config.

**Comment by jaszhix** [comment]
Please share your settings file located in `~/.cinnamon/configs/show-hide-applets@mohammad-sn/show-hide-applets@mohammad-sn.json`. Any errors in ~/.xsession-errors or ~/.cinnamon/glass.log would be helpful, too.

**Comment by donlencho** [comment]
`
{
"head": {
        "type": "header",
        "description": "Settings for show-hide-applets@mohammad-sn"
    },
    "autohide": {
        "type": "checkbox",
        "default": true,
        "description": "Autohide",
        "tooltip": "check if you want to hide applets automatically, unless you should click on applet to do so",
        "value": true
    },
    "disablestarttimeautohide": {
        "type": "checkbox",
        "default": false,
        "description": "Disable start time autohide",
        "tooltip": "if not in autohide mode",
        "value": false
    },
    "hidetime": {
        "type": "spinbutton",
        "default": 2,
        "min": 0.25,
        "max": 10,
        "step": 0.25,
        "units": "seconds",
        "dependency": "autohide",
        "description": "Autohide after ",
        "tooltip": "",
        "value": 2
    },
    "hoveractivates": {
        "type": "checkbox",
        "default": true,
        "description": "Activate on hover",
        "tooltip": "show applets on mouse hover",
        "value": false
    },
    "hoveractivateshide": {
        "type": "checkbox",
        "default": false,
        "dependency": "hoveractivates",
        "description": "Hide on hovering again",
        "tooltip": "toggle visibility of applets on mouse hover",
        "value": false
    },
    "hovertime": {
        "type": "spinbutton",
        "default": 75,
        "min": 10,
        "max": 500,
        "step": 5,
        "units": "miliseconds",
        "dependency": "hoveractivates",
        "description": "Hover activates/hides after ",
        "tooltip": "",
        "value": 75
    },
    "autohiders": {
        "type": "checkbox",
        "default": true,
        "description": "Autohide reshowing applets",
        "tooltip": "",
        "value": true
    },
    "autohiderstime": {
        "type": "spinbutton",
        "default": 1.25,
        "min": 0,
        "max": 5,
        "step": 0.25,
        "units": "seconds",
        "dependency": "autohiders",
        "description": "Reshowers' autohide delay: ",
        "tooltip": "",
        "value": 1.25
    },
    "__md5__": "912b5887ae406da2d6613a37a9a2c3db"
}
`

Apart from this line in glass.log, I don't see anything related:
`
info t=2018-05-06T08:40:00.887Z Loaded applet show-hide-applets@mohammad-sn in 15 ms
`

**Comment by donlencho** [comment]
(sorry the indentation of the code got lost when posting, for some reason)

**Comment by icarter09** [comment]
Cinnamon 3.8.8
Linux Mint 19 64bit 
Applet version 2018-02-24 09:13 UTC

Was able to confirm the issue that @donlencho is getting. 

@jaszhix I checked the .json file you asked about and saw nothing out of the ordinary. I did do some debugging through the .xsession-errors file, but have nothing yet to post. Will continue to look further into this issue.

**Comment by icarter09** [comment]
@jaszhix I did some debugging through the .xsession-errors log file and believe I found the problem. I tagged the author and put up a PR for the fix.

**Comment by donlencho** [comment]
thanks, fixed with your modification indeed!
