### ISSUE TITLE
Feature request for download-and-upload-speed@cardsurf: Sum of all network interfaces

### ISSUE THREAD

**Issue by Fabian42** [linuxmint/cinnamon-spices-applets#1842]
@cardsurf 

Originally I wanted to suggest automatic interface switching, because I use different ways to connect to the internet and don't want to switch manually every time. But why not just monitor them all and display the sum? That has the additional advantage that if multiple connections can be active at once (don't know if that's possible), it would still show the correct amount.

This could be an additional option in the interfaces option list.

**Comment by cardsurf** [comment]
Sounds like a good idea. I would prefer a more generic option to show a sum of values of selected network interfaces. Checking all of the interfaces would show total network traffic.
