### ISSUE TITLE
Application's Button Gets Lost When Moving the Application to Another Screen

### ISSUE THREAD

**Issue by khatamnejad** [linuxmint/cinnamon-spices-applets#1844]
```
 * Applet version: 2.2
 * Cinnamon version: 3.4.6
 ```
When I move an application from one screen to another, its button disappears. The button won't appear again if I move the application back to the original screen.

**Comment by Cobinja** [comment]
@khatamnejad I just assume you mean windowlist@cobinja.de, right?
Have you installed the latest version via cinnamon-settings? It should be fixed there (https://github.com/linuxmint/cinnamon-spices-applets/commit/2c6076165bba36f215d9d7ea4614ffdfbca2bb71#diff-965f8c5027606813dd26322b9b844de3).

**Comment by khatamnejad** [comment]
Yes. It is fixed in the last version. However I think it would have been great to have a 2.2.x version or something to avoid confusion because I already had the 2.2 version on my machine and didn't expect I had to install it once again to fix the issues.
