### ISSUE TITLE
CommandRunner@appdevsw Freezes at "Starting…"

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/cinnamon-spices-applets#1846]
CommandRunner@appdevsw

Everything lates version (archlinux)

**Issue**
Applet shows ```Starting…```

**Steps to reproduce**
Use it.

**Expected behaviour**
Show output of script

**Comment by icarter09** [comment]
Cinnamon 3.6.7
Linux Mint 18.3 64bit
Applet version 2017-06-26 19:05 UTC

Downloaded and added applet with no problems. Was able to run several commands through the applet and results were reflected in the toolbar.

**Comment by G4Zz0L1** [comment]
Same problem here, on Mint 19 with cinnamon 3.8.7+tara

Applet doesn't change from `Starting...`

**Comment by icarter09** [comment]
I thought this applet was working at one point in time, but getting the same problem that @ManuelSchneid3r and @G4Zz0L1 are referencing. I put a PR that should fix this issue.
