### ISSUE TITLE
IcingTaskManager@json: Restart cinnamon applet destroy icon from snaps and appimages apps from taskbar, every  time is used.

### ISSUE THREAD

**Issue by Lvaskz** [linuxmint/cinnamon-spices-applets#1848]
<  restart-cinnamon@kolle>

```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --3.6)
 * Distribution - (Mint 18.3)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

 * Cinnamon version (cinnamon --version 3.6)
 * Distribution - (Mint 18.3)
 * Graphics hardware *and* driver used
 * 64 bit

Issue
Every time I use restart cinnmon applet, the applications icons( appimages, snaps) from taskbar disappear, or image icon missing. I must to exit application and reopen it to see the icon again.

Steps to reproduce
Install Icing Task Manager applet.
Install snapd, open a terminal and type: sudo apt install snapd
Install any snap app, open a terminal and type: sudo snap install inkscape
Download any appimage app( https://es.libreoffice.org/descarga/appimage/)
Open Inkscape and/or appimage
Use restart cinnamon applet, you'll see icon is missing from the taskbar.

Expected behaviour
It is expected that after refreshing the desktop, the icons of the applications on the desktop will not disappear, but will continue appearing normally.

Other information

**Comment by jaszhix** [comment]
@Lvaskz Can you please attach your settings JSON? Also, please check the issue template, you didn't notify me, or check ITM's readme.

**Comment by Lvaskz** [comment]
"Can you please attach your settings JSON?" I'm not programmer, and I really don't know what are you asking me. How can I find out?

**Comment by jaszhix** [comment]
In the issue template. If you read the readme, you would see it is preferred to open issues on the dedicated repo.

**Comment by Lvaskz** [comment]
I'm going to close this, now I'm on Ubuntu 18.04.
