### ISSUE TITLE
Error with Add Logo section

### ISSUE THREAD

**Issue by pathaknitesh** [linuxmint/cinnamon-spices-applets#1849]
Applet Version 1.1.1
```
 * Applet version : 1.1.1
 * Cinnamon version (cinnamon --version): 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3 64 bit
 * Graphics hardware *and* driver used : nouveau.modeset=0 is used
 * Snippet or attachment of ~/.cinnamon/glass.log 
[glass.log](https://github.com/linuxmint/cinnamon-spices-applets/files/2050319/glass.log)


 * Snippet or attachment of ~/.xsession-errors
[xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/2050346/xsession-errors.txt)
 ```

**Notify author of applet**
@

**Issue**
VLC throws an error saying that the image file path is not found (image file which is used for adding logo to the video). This image file is configured in the "Add Logo" section of the applet's configuration settings.

**Steps to reproduce**
go to settings of the applet--> enable Add logo --> browse the image file.
Start recording the desktop and the VLC throws the error of file not found or no such file or directory.
After stopping the recording, when you play the recorded video, there is no logo.

**Expected behaviour**
Recorded video must show the image file as an overlayed logo in the video.

**Other information**

**Comment by jaszhix** [comment]
No applet in the title, no way to know what this issue is about. Please take a look at the issue template.
