### ISSUE TITLE
IcingTaskManager@json Arrangement of applications only to the end

### ISSUE THREAD

**Issue by Martin1887** [linuxmint/cinnamon-spices-applets#1851]
```
 * Version 6.3.5
 * Cinnamon 3.8.1
 * Fedora 28
 * NVIDIA RPMFusion driver
 ```
 @jaszhix

**Issue**
When an application is dragged, it is moved to the end if it is dragged to the right, and it is not moved if it is dragged to the left.

The dragged application should be moved to the position it is dropped (a position to the left for instance).

**Steps to reproduce**
For instance, rag last application one position to the left.

**Expected behaviour**
The application is moved one position to the left, and the application that were to the left is moved to the right of the dragged application.

Thanks.

**Comment by jaszhix** [comment]
@Martin1887 Please open this at the ITM repo, and attach the settings JSON. I can't reproduce this.
