### ISSUE TITLE
IcingTaskManager@json Current active application indicator disappears when its contextual menu or preview is shown

### ISSUE THREAD

**Issue by Martin1887** [linuxmint/cinnamon-spices-applets#1852]
```
 * Version 6.3.5
 * Cinnamon 3.8.1
 * Fedora 28
 * NVIDIA RPMFusion driver
 ```
 @jaszhix

**Issue**
The current active application has an indicator (for instance, a horizontal line in the top of the title).

This indicator disappears when the preview or that window or its contextual menu is shown.

**Steps to reproduce**
Open two applications, the last of them will be the active.

Right click or hover in the active application. The indicator will disappear and none of open applications will have indicator.

**Expected behaviour**
The indicator does not disappear.

Thanks.

**Comment by jaszhix** [comment]
Not able to support custom modified themes, sorry. Ref https://github.com/jaszhix/icingtaskmanager/issues/199#issuecomment-394099653 #1781
