### ISSUE TITLE
IcingTaskManager@json: Preview empty after supspend/resume

### ISSUE THREAD

**Issue by MegaV0lt** [linuxmint/cinnamon-spices-applets#1869]
```
 * Applet version/Build date (2.3.7)
 * Cinnamon version (Cinnamon 3.6.7)
 * Distribution - (Mint 18.3 Sylvia)
 * Graphics hardware *and* driver used
Graphics:  Card-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics driver: i915 
           v: kernel bus ID: 00:02.0 
           Card-2: NVIDIA driver: nvidia v: 384.130 bus ID: 01:00.0 
           Display: x11 server: X.Org 1.18.4 driver: intel,nvidia 
           unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1200~60Hz 
           OpenGL: renderer: GeForce GTX 1050 Ti/PCIe/SSE2 v: 4.5.0 NVIDIA 384.130 
           direct render: Yes 

 * Snippet or attachment of ~/.cinnamon/glass.log
https://www.dropbox.com/s/mo4zz4cqiz22kg3/glass.log?dl=0
 * Snippet or attachment of ~/.xsession-errors
https://www.dropbox.com/s/v9uo9kw87rpu6n8/.xsession-errors?dl=1

 ```

**Notify author of applet**
@jaszhix

**Preview empty after supspend/resume**
Preview of window in taskbar is empty after resume

**Steps to reproduce**
Open libreoffice. Enter suspend (RAM) reactivate PC. Preview of the windows is empty in libreoffice previews. Sample:
![menu_20180609_08 21 30](https://user-images.githubusercontent.com/2804301/41583576-3e723c74-73a5-11e8-83c5-d8690726b963.png)

**Expected behaviour**
Preview should survive the supsend/resume process

**Other information**
After activating the window the preview is available until the next suspend/resume

**Comment by jaszhix** [comment]
What does ~/.xsession-errors show?

**Comment by MegaV0lt** [comment]
I put it im my dropbox
https://www.dropbox.com/s/v9uo9kw87rpu6n8/.xsession-errors?dl=1

**Comment by jaszhix** [comment]
Looks like a driver issue. Chrome is logging some hardware rendering problems too, presumably after resume. Suspend doesn't always work right on Linux. See any errors in ~/.cinnamon/glass.log? Is it just LibreOffice? If there's nothing in glass.log I probably can't do anything about this, resuming from suspend is known to be unstable, add optimus in the mix and the possible causes grow.

**Comment by MegaV0lt** [comment]
Updated links in first post. You can look there for the glass .log.

i make a new suspend and resum now and post it in a few minutes...

**Comment by MegaV0lt** [comment]
Nemo, FF and TB are Ok after resume. So probably is only affecting LibreOffic...
Updated the two logfiles in case you want take a look again

**Comment by jaszhix** [comment]
You could try switching to the other GPU, Intel is generally better supported and consumes less power. It wasn't long ago Nvidia fixed freezing issues in driver 384.

```glxinfo | grep OpenGL```

**Comment by jaszhix** [comment]
This is outside the scope of ITM, sorry. Can't prevent Nvidia issues with suspend.
