### ISSUE TITLE
Download fails (temperature@fevimu)

### ISSUE THREAD

**Issue by Fabian42** [linuxmint/cinnamon-spices-applets#1871]
```
 * Cinnamon version (cinnamon --version)
   * 3.2.7
 * Distribution
   * Debian 9.4 (x86-64)
 * Snippet or attachment of ~/.cinnamon/glass.log
[glass.log](https://github.com/linuxmint/cinnamon-spices-applets/files/2129327/glass.log)

 * Snippet or attachment of ~/.xsession-errors
[xsession-errors (copy).txt](https://github.com/linuxmint/cinnamon-spices-applets/files/2129331/xsession-errors.copy.txt)
```

**Notify author of applet**
@fevimu

**Issue**
When trying to download the applet, I get this error:
![image_2018-06-23_00-40-18](https://user-images.githubusercontent.com/10481506/41801974-07beca40-767e-11e8-9bac-afbd0acc6a1e.png)

**Other information**
It has definitely worked at some point in the past, I don't know when it broke.

**Comment by jaszhix** [comment]
The applet is [only compatible with Cinnamon 3.6 and 3.8](https://github.com/linuxmint/cinnamon-spices-applets/commit/0bbb4a140d633af2e0d9376dca89889e49e3a30e).

**Comment by jaszhix** [comment]
Looks like Debian stable is still using Cinnamon 3.2. Testing/unstable has 3.6. Experimental has 3.8. Its probably stuck at 3.2 because they only have mozjs24 in the repos. Debian often lags behind on Cinnamon packaging.
