### ISSUE TITLE
Icing Task Manager: "only list windows from the monitor displaying this instance" option 

### ISSUE THREAD

**Issue by mauro-miatello** [linuxmint/cinnamon-spices-applets#1883]
```
 * Applet version/Build date: 6.3.8
 * Cinnamon version: 3.8.7
 * Distribution: Mint 19
 * Graphics hardware *and* driver used: NVIDIA GTX 1060 3G and nvidia-driver-390
 * Snippet or attachment of ~/.cinnamon/glass.log: i cant find where is it ?
 * Snippet or attachment of ~/.xsession-errors: attached

 ```

**Notify author of applet**
@jaszhix

**Issue**
i added 2 instances of applet and checked the option "only list windows from the monitor displaying this instance": i want that applet shows on monitor 1 the programs opened in monitor 1 and same thing for monitor 2: is it possible or maybe i've misundersanded the meaning of this option?

**Steps to reproduce**
add 2 applets on 2 panels on 2 monitors

**Attachments**
[xsession-errors.log](https://github.com/linuxmint/cinnamon-spices-applets/files/2173906/xsession-errors.log)

**Comment by jaszhix** [comment]
Did you enable the per-monitor windows option on both ITM instances? If you can, please attach the output of `cat ~/.cinnamon/configs/IcingTaskManager@json/*.json`.

**Comment by jaszhix** [comment]
Kamino cloned this issue to [jaszhix/icingtaskmanager](https://github.com/jaszhix/icingtaskmanager/issues/210)
