### ISSUE TITLE
Cinnamenu - Feature Request: Compact Mode

### ISSUE THREAD

**Issue by snhv** [linuxmint/cinnamon-spices-applets#1884]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - Mint 19
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@jaszhix

**Issue**
Hi author, could you add a compact mode please? I think the current layout has too much white space. Thank you.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by jaszhix** [comment]
There is already a list layout option, and in grid mode you can reduce the number of columns to 3.
