### ISSUE TITLE
IcingTaskManager@json wrong focus when target is in another workspace

### ISSUE THREAD

**Issue by memeplex** [linuxmint/cinnamon-spices-applets#1888]
```
 * Applet version: 6.3.9
 * Cinnamon version: 3.8.6
 * Distribution: Arch
 * Graphics hardware *and* driver used: xf86-video-intel 1:2.99.917+829+gd7dfab62-1
 ```

 @jaszhix I configured ITM to show windows from all workspaces. Now I want to activate a window in another workspace using the numerical shortcut, say Super-N. ITM changes the workspace but, in general, the focused window is not the one in position N. I didn't find a pattern tough, sometimes no window in the target workspace is focused, sometimes ahother window is. If I press Super-N again, since I'm already in the target workspace, focus is set to the right window.

**Comment by jaszhix** [comment]
Kamino closed and cloned this issue to [jaszhix/icingtaskmanager](https://github.com/jaszhix/icingtaskmanager/issues/214)
