### ISSUE TITLE
feeds@jonbrettdev.wordpress.com: Feeds Don't Appear in Feeds Reader Applet of Linux Mint 19 (x86_64)

### ISSUE THREAD

**Issue by gnulinuxnovice** [linuxmint/cinnamon-spices-applets#1898]
```
Feeds Reader v. 0.29
feeds@jonbrettdev.wordpress.com
```
**System Info:**
[http://termbin.com/jrto](http://termbin.com/jrto)
Linux Mint 19 (x86_64) with Cinnamon 3.8.8

**Notify author of applet**
@jake1164 

**Issue**
Previously worked in Linux Mint 17.1-17.3 (64 bit). But after doing a clean install of Mint 19 (64 bit), it no longer shows the feeds. Feeds with no name or title simply say "Loading feed" in the applet (left-click window).

I've tried manually inputting the addresses and I've tried importing the data, and neither method works. If you require more information on my end, please let me know.

#

**Comment by gnulinuxnovice** [comment]
> Hmm... I fixed this on my end a while back, but I guess I never pushed my fixes.

Hello collinss,
Was it an easy fix? Is it something I can do quickly on my end?
Regards.

**Comment by gnulinuxnovice** [comment]
> Try apt install python3-feedparser

I installed the program, but still no effect even after rebooting the computer.

**Comment by collinss** [comment]
Sorry, it's python-feedparser you need.

**Comment by gnulinuxnovice** [comment]
> Sorry, it's python-feedparser you need.
Yup, that did it! Thank you @collinss I'll close this thread and mark it solved.
