### ISSUE TITLE
batterymonitor@pdcurtis: charging icon hard to see with color-deficient vision

### ISSUE THREAD

**Issue by focusaurus** [linuxmint/cinnamon-spices-applets#1907]
```
 * Applet version/Build date: 1.3.2/2018-01-06
 * Cinnamon version: Cinnamon 3.8.8
 * Distribution - Mint 19
 ```
**Notify author of applet**
@pdcurtis 

**Issue**
With the display set to "Classic Plus", due to my color deficient vision, the yellow lightning icon on top of light green background color is nearly invisible to me. I have two requests/suggestions:

1. Make the icon color more contrasting to the background color
2. Perhaps use a power plug icon instead of lightning which I feel is more clear in meaning, and also could be black like the percentage text, which is easy to read.

**Comment by pdcurtis** [comment]
@focusaurus There are so many different forms of deficient colour vision that i am not sure that it would be possible to satisfy all of them by default. You can however customise by changing the icons in ~/.local/share/cinnamon/applets/batterymonitor@pdcurtis/icons to suit yourself. 
The applet also has a red border when discharging which should be be clear to most people with a yellow/green deficiency.
The only other way to be sure is to not use colours at all as is the case with much of the Mint standard themes and applets but I find a bright colour 'traffic light' is much more effective for applets where there are 'warnings' etc which need to be heeded. 
Yours is however a useful point and one I will keep in mind in any major updates or new applets.
Out of interest, do you (and others with colour deficiencies) use any special themes and sets of icons?

**Comment by focusaurus** [comment]
Thanks for your response. I will look for the lack of red border to confirm my power cord is plugged in and working.

To be clear, I'm not asking you to satisfy all forms of color deficient vision. I'm just asking for a specific change.

As to themes and icons, the only change I have made for vision is using the Mint-X-Aqua desktop theme because it has more contrast between the active window button in the window list and the inactive buttons.
