### ISSUE TITLE
batterymonitor@pdcurtis - BAMS applet error with LM 19.0

### ISSUE THREAD

**Issue by CJConline** [linuxmint/cinnamon-spices-applets#1913]
```
 * Applet version/Build date 1.3.2
 * Cinnamon version  3.8.8
 * Distribution: Mint 19.0
 * Graphics Intel HD Graphic 520 (Dell Inspiron 15 5000 series laptop)
  

<!-- Author list: https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/CODEOWNERS -->

**Notify author of applet**
@pdcurtis

**Issue**
When installing the BAMS applet and also when you login after you first boot up, a screen pops up that shows a red minus sign and the error "Some Dependencies not Installed".
Error did not happen with LM18.3.
Also the percentage charge displayed doesn't update after resuming from suspend if the charge has dropped below the critical (red) level even after you plug the power in and even when the battery gets to 100%, it still remains stuck incorrectly at the critical level it was originally on.
See the attached screenshot.
![bams error screenshot](https://user-images.githubusercontent.com/27131265/43318634-12803952-91d4-11e8-9cdb-c5a72fb876e4.png)



**Steps to reproduce**



**Expected behaviour**



**Other information**

**Comment by icarter09** [comment]
@CJConline the reason for the install message is that since version 1.3.2, both sox and zenity are needed for the battery monitor applet to function correctly. I got the message warning message that you stated, then installed sox (zenity was already at the latest version). After install, I removed and added the battery monitor applet back and the warning message no longer appeared. 

Let me know if installing both sox and zenity fixi the warning issue.

**Comment by CJConline** [comment]
Thank you so much.  Works well now.  Will check the other issue I had with
it not updating percentage charge once it had fallen to critical when
suspended when time permits.  Chris

PS: Would be good it the need to install sox and zenity was mentioned in
the description on the Cinnamon Spices pages for less experienced user like
me.  NB:  zenity was already installed on LM 19.0 Tara (upgraded from the
beta) but not sox.   Both sox and zenity must have already been install
with LM18.3.  Cheers.

**Comment by icarter09** [comment]
@CJConline Let me know if the other issue is still present. I'll try to put in a PR tonight with an updated message informing the user of how to correct the dependency problem.

**Comment by pdcurtis** [comment]
I have only just found this - neither of you put the @pdcurtis in you comments so it did not reach me until #1931 alerted me!
@icarter09 I have agreed the PR you put forwards.
@CJConline The description does mention the requirements for sox and zenity under the section marked requirements.

I have seen a similar problem returning from suspend on a different applet which cleared with a cinnamon reset. It came sometime after I installed Mint 19 but it went away with one of the recent cinnamon updates on my machine so I hope it was a Cinnamon issue. I am watching for it.
I also have a couple of minor updates in the pipeline to improve compatibility with systems other than Mint so I will update the version log when I put the next PR in.

**Comment by icarter09** [comment]
@pdcurtis you were tagged in the original comment for this issue, but it looks like the formatting caused github to not ping you as intended. Sorry about that!

**Comment by pdcurtis** [comment]
@icarter09 Yes I can see that but it does not seem to have gone into bold and I did not get it - how odd, as you say it must be the formatting. No problem and thanks.

**Comment by CJConline** [comment]
Thank you everyone.  I can't seem to replicate the other problem I
mentioned so it might have had something to do with the missing
dependencies.

**Comment by jerkey** [comment]
this problem is still here as far as i can tell.  Turn on laptop from suspend, SOC is below minimum, applet does nothing.  Computer runs out of power and shuts off.

Linux raz 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID: Linuxmint
Description:    Linux Mint 21.1
Release:        21.1
Codename:       vera
