### ISSUE TITLE
Wont index application after installing and uninstalling xfce

### ISSUE THREAD

**Issue by AnimatedProgrammer** [linuxmint/cinnamon-spices-applets#1914]
Obscure bug and probably not high priority or critical really but thought I should report it.
Was trying out some different desktop environments in this case XFCE. Didn't like it and returned to Cinnamon
I uninstalled xfce and all of it's applications when I saw that the tracker plugin was no longer indexing my applications. Only files. I tried to hard reset tracker and reinstalling it and it's dependancies but nothing worked.
I did fix it by searching and deleting every file on my system tagged with xfce as I was no longer using any of it and then restarting. So it must have been some kind of configuration file from xfce that the tracker plugin based it's indexing priority on. 

```
 * Applet version/Build date (2018-04-25, 00:19 UTC)
 * Cinnamon version (3.6.7)
 * Distribution - (Debian buster/sid)
 * Graphics hardware Nvidia GeForce GTX 760 OEM with the Linux-x86-64-396.45 drivers 
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
The Plugin no longer indexing applications after having xfce installed. 

**Steps to reproduce**
Install XFCE side by side with cinnamon (maybe also install the vala global menu plugin as I did do that too)

**Expected behavior**
After switching back to Cinnamon the plugin will no longer index applications. At least not after XFCE is uninstalled as in my experience. 

**Other information**

**Comment by collinss** [comment]
You didn't tell us what the uuid of the applet is, nor notify the author (if any). You also didn't attach the contents of ~/.xsession-errors or ~/.cinnamon/glass.log (pastebin works well for this). Please provide this additional info and I'll reopen the issue. Without it, there's not much anyone can do.
