### ISSUE TITLE
Cinnamenu@json: more than 1 instance

### ISSUE THREAD

**Issue by mmiat** [linuxmint/cinnamon-spices-applets#1921]
```
 * Applet version/Build date: 3.2.2
 * Cinnamon version: 3.8.8
 * Distribution: Mint 19 Tara
 * Graphics hardware *and* driver used: GeForce and Nvidia
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors
 ```

**Issue**
i've 2 monitors, is it possible to have an instance of cinnamenu in each of them?

**Steps to reproduce**
dual monitor, try adding a second cinnamenu

**Expected behaviour**
2 cinnamenu

**Comment by jaszhix** [comment]
Probably by editing metadata.json with the max-instances key, but its untested and not something I plan on supporting.
