### ISSUE TITLE
workspace-grid@hernejj Cannot move up/down workspaces in Cinnamon 3.8.8

### ISSUE THREAD

**Issue by sn0w75** [linuxmint/cinnamon-spices-applets#1930]
```
 * version 0.8 (commit dadb2c8b)
 * Cinnamon version 3.8.8
 * Debian Linux 10 Buster (testing branch)
 * RX 580, Mesa 18.1.6

 ```

**Notify author of applet**
@hernejj

**Issue**
In Cinnamon 3.8.8, this applet runs into errors when installing- the keyboard shortcuts to move up/down workspaces no longer work, and cannot be set manually.

**Comment by icarter09** [comment]
@sn0w75 can you provide the steps to reproduce this issue? I'm currently not able to duplicate this issue, but probably because I'm not following the steps correctly. Thanks.

**Comment by sn0w75** [comment]
@icarter09 The steps to reproduce are simply to, with Cinnamon version 3.8.8, install the applet, create some rows, then try to use Ctrl+Alt+Up and Ctrl+Alt+Down to go up/down a row. Neither keyboard shortcut will work.
I made a short video demonstrating the issue to make it easier to see and understand what's going on: https://youtu.be/R8vTqnIL9_4

**Comment by icarter09** [comment]
@sn0w75 thanks for the video.  I created several rows and columns and was able to use 'Ctrl+Alt+Up' and 'Ctrl+Alt+Down' to traverse them all with no problems. I'm using Linux Mint 19 64bit with Cinnamon 3.8.8. The applet version is 2018-05-05 18:03 UTC.

**Comment by sn0w75** [comment]
@icarter09 Hmmm, I wonder what the difference is between your setup and mine.
At the very least, I've seen one other user in the comments section who ran into this same issue when debian picked up Cinnamon 3.8.8 here in the past week:
https://cinnamon-spices.linuxmint.com/applets/view/116
![image](https://user-images.githubusercontent.com/4862240/44461856-2e1d6f00-a5d8-11e8-9cbd-2557c2419482.png)

I'm not familiar with applet development, but if I knew how to get some actual error output when using an applet, I might be able to dig around a bit and figure something out.

**Comment by sn0w75** [comment]
So, when I tried fiddling around with the Workspace Grid today, it worked perfectly fine for some reason!
In fact, I even went back to look at the comments, and the other individual who ran into this issue seems to have experienced the exact same thing:
![image](https://user-images.githubusercontent.com/4862240/44610064-228c9c80-a7c0-11e8-8b26-6f0e252a964a.png)

It's truly strange, because you would think that if uninstalling and re-installing the applet didn't work before, it wouldn't work now, but clearly something has changed between my last attempt and my attempt today.

I think it's probably fine to close this issue, unless someone wants to investigate the sort of strange issue that only (temporarily?) crops up during a package transition (from Cinnamon 3.6.x to 3.8.8).

**Comment by icarter09** [comment]
@sn0w75 awesome news that it is working correctly for you now! Thanks also for updating this ticket with your findings.

@jaszhix I believe this issue can be closed out now.
