### ISSUE TITLE
weather@mockturtl: Show forecasts on incorrect days

### ISSUE THREAD

**Issue by jjf-zero** [linuxmint/cinnamon-spices-applets#1933]
Version del applet: 1.14.0/ 2018-07-02 14:14 UTC
Cinnamon version: Cinnamon 3.8.8
Distribution: Fedora release 28 (Twenty Eight)
@mockturtl

**Issue**
shows the outdated forecast one day. Today is Wednesday and the first day shown is Tuesday.
The info for today is showed as yesterday and so on.

**Steps to reproduce**
Configure UID:349859 Santiago de chile, in spanish.

**Expected behaviour**
Show de forecast for the day as correspond

**Comment by mockturtl** [comment]
The Yahoo weather service is returning [stale data for your location](http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20weather.forecast%20where%20woeid=%22349859%22%20and%20u=%22c%22):

```json5
"forecast": [
{
"code": "28",
"date": "21 Aug 2018",  // stale!
"day": "Tue",
"high": "13",
"low": "7",
"text": "Mostly Cloudy"
},
```

We can't do anything about this, but the data for several US locations I tested is current.  For example, try NYC: `2459115`.

Hopefully it will fix itself soon.

https://github.com/mockturtl/cinnamon-weather/wiki/Test-my-city

**Comment by germanfr** [comment]
Same or similar issue here with no proxy. My woeid is `766273`.

The first day in the forecast is _today_, when it is supposed to be _tomorrow_. It is repeating the information above. I know the API provides it like that, but I guess you could skip the first one.

**Comment by mockturtl** [comment]
> The first day in the forecast is _today_,  when it is supposed to be _tomorrow_

Starting from "today" is the expected behavior.  (For example, you want to know today's forecast high temperature.)

When the issue was reported (Aug 22), the data for Santiago was incorrectly showing the _previous_ day (Aug 21).

I think this issue can be closed.

**Comment by jjf-zero** [comment]
Yes. Is Ok now.El 8 sep. 2018 3:48 PM, mockturtl <notifications@github.com> escribió:
The Yahoo weather service is returning stale data for your location:

It looks like the problem with this WOEID has cleared up.
"pubDate": "Wed, 05 Sep 2018 12:00 AM CLST",
"condition": {
  "code": "31",
  "date": "Wed, 05 Sep 2018 12:00 AM CLST",
  "temp": "10",
  "text": "Clear"
},
"forecast": [
{
  "code": "32",
  "date": "05 Sep 2018",   // fresh!
  "day": "Wed",
  "high": "16",
  "low": "8",
  "text": "Sunny"
},
@jjf-zero Does it look OK now?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


AVISO DE CONFIDENCIALIDAD: La información de este documento y sus anexos es confidencial. Está dirigida únicamente para el uso por parte del destinatario que se indica. Debido a que las comunicaciones por Internet no son seguras, Inventa SA. no acepta responsabilidad legal por el contenido de este mensaje. Si recibe este mensaje por error, notifique al remitente y elimine el mensaje.  La violación al mandato de este aviso puede dar lugar a responsabilidades legales.CONFIDENTIALITY NOTICE: The information in this document and its attachments are confidential. It is intended only for the use of the named recipient. Internet communications are not secure and therefore, Inventa SA. do not accept legal responsibility for the contents of this message. If you are not the intended recipient, please notify the sender immediately and  delete this document permanently from your computer. Violation of this notice may be unlawful.
