### ISSUE TITLE
Feature Request: Drag and Drop Reorder Menu Items

### ISSUE THREAD

**Issue by paulsrch** [linuxmint/cinnamon-spices-applets#1934]
Love the menu, but it would be great if we could reorder items in the menu using drag and drop, just we can for categories.

**Comment by paulsrch** [comment]
Sorry, CinnaMenu

**Comment by jaszhix** [comment]
Ok, I maintain that one. You can drag and drop re-order menu items in the favorites category, but everything else is alphabetical. I think it would add too much complexity to enforce ordering per-category.

**Comment by carlosepcc** [comment]
> Ok, I maintain that one. You can drag and drop re-order menu items in the favorites category, but everything else is alphabetical. I think it would add too much complexity to enforce ordering per-category.

Jaszhix, What about drag and drop for category editing in the menu UI?
