### ISSUE TITLE
multicore-sys-monitor@ccadeptic23 broken on Fedora with v 1.8.3

### ISSUE THREAD

**Issue by coderforlife** [linuxmint/cinnamon-spices-applets#1939]
multicore-sys-monitor@ccadeptic23

 * Distribution - Fedora 27

**Notify author of applet**
@jaszhix

**Issue**
Switching the NM library check from 

```
let nm_index = GIRepository.Repository.get_default().get_loaded_namespaces().indexOf('NetworkManager')
if (nm_index == -1) {
```

to using `tryFn` breaks usage on Fedora and maybe other systems since `tryFn` will still attempt to load the library which is what causes the segfault! That code was very carefully constructed the way it was before that commit to prevent this. That part of the change in commit 42203853baf198c7cc1b090e8b4e2a303df28048 must be reverted.

**Comment by coderforlife** [comment]
Additionally, the `newNM` variable is unnecessary in that commit and the old code handled the situation in a cleaner fashion by defining a wrapper for the function.

**Comment by coderforlife** [comment]
(it is possible that the last change using the `newNM` is possibly necessary due to needing to use `apply` later, but I am unsure about that as it wasn't needed on Mint or Fedora that way, and in either case it could still use the old system with a slight modification).

**Comment by jaszhix** [comment]
I think I changed it because the original fix didn't work on Debian. Does this occur on Fedora 28?

**Comment by coderforlife** [comment]
It does not crash in Fedora 28 but doesn't show anything at all.

**Comment by coderforlife** [comment]
Correction. I don't know what was hiding it, but it actually still is crashing in Fedora 28 and Cinnamon v3.8.8.

**Comment by jaszhix** [comment]
Can you provide logs?

**Comment by coderforlife** [comment]
The relevant .xsession-error log:

(cinnamon:23082): libnm-util-ERROR **: 22:04:30.637: libnm symbols detected; Mixing libnm with libnm-util/libnm-glib is not supported

This is exactly the error I was getting before introducing that fix. Basically it is saying that you are trying to load libnm even though libnetworkmanager (or whatever) is already loaded.

**Comment by coderforlife** [comment]
My guess is that it is somewhat random based on the order in which things load and I randomly was able to boot once without it crashing but typically (i.e. almost always) it crashes.

It is also possible that if the default Network Manager applet is disabled  this error can also be avoided.

**Comment by jaszhix** [comment]
Does reverting the change fix it for you? This was changed because of #1735. I have a hard time spinning up two VMs to test this at the moment, but will look into it when I can. I think there's been a [network manager](https://github.com/linuxmint/Cinnamon/pull/7699) [applet](https://github.com/linuxmint/Cinnamon/pull/7668) [fix](https://github.com/linuxmint/Cinnamon/pull/7536) in limbo for a while now because of breaking Debian.

**Comment by leigh123linux** [comment]
@coderforlife A quick fix would be to remove the NetworkManager-glib package

**Comment by leigh123linux** [comment]
@coderforlife  or reverse the code in ~/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/DataProviders.js


```
let CONNECTED_STATE, NMClient_new, newNM;
// Fallback to the old version.
tryFn(function() {
  const NM = imports.gi.NM;
  CONNECTED_STATE = NM.DeviceState.ACTIVATED;
  NMClient_new = NM.Client.new;
  newNM = true;
}, function() {
  const NMClient = imports.gi.NMClient;
  const NetworkManager = imports.gi.NetworkManager;
  CONNECTED_STATE = NetworkManager.DeviceState ? NetworkManager.DeviceState.ACTIVATED : 0;
  NMClient_new = NMClient.Client.new;
  newNM = false;
});
```

**Comment by leigh123linux** [comment]
FTR multicore-sys-monitor@ccadeptic works fine on f29 as NetworkManager-glib doesn't exist.

**Comment by coderforlife** [comment]
@leigh123linux Removing `NetworkManager-glib` (and the only dependent package `libnm-gtk`) worked! It is likely that that package was still around since I have been doing upgrades and not clean installs. Thanks for noticing that it could be removed easily.

Also, I was the one who wrote the original code to manage the Fedora system that had both. But I guess it wasn't quite complete on systems that only had the newer version.
