### ISSUE TITLE
Cinnamenu@json New Translate

### ISSUE THREAD

**Issue by TeknoMobil** [linuxmint/cinnamon-spices-applets#1942]
Hi
I have completed the Turkish language translation for the application
What do I have to do to add this ?
Thanks

**Language File**:
[tr.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/2341995/tr.po.zip)

**Comment by jaszhix** [comment]
Hi, thanks for translating it. :) If you're familiar with git you can open a pull request, otherwise I can.

**Comment by TeknoMobil** [comment]
I just started, I do not have much knowledge, please do it :)
