### ISSUE TITLE
Adding new note with Cinnamon 3.8.8 under mint 19 is not working

### ISSUE THREAD

**Issue by broadcastyourseb** [linuxmint/cinnamon-spices-applets#1946]
```
 * Applet version/Build date: 1.2
 * Cinnamon version: 3.8.8
 * Distribution: Mint 19 Cinnamon 64bit
 * Graphics hardware *and* driver used: NVIDIA Corporation GK106 [GeForce GTX 650 Ti] with nvidia-driver-390
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@collinss 

**Issue**
Adding new note is not working

**Steps to reproduce**
Install the applet with the standard way (ie desklet menu)
Click on new note or new note with option button. Nothing appends. Only one note appears on the desktop

**Expected behaviour**
Add a new note on the desktop

**Other information**
![image](https://user-images.githubusercontent.com/8392947/45020253-be26d400-b02e-11e8-9385-667722507912.png)

**Comment by collinss** [comment]
It's working fine for me, and has been. Please pastebin the contents of your ~/.xsession-errors log like you were asked to in the issue template. Otherwise I'll have no idea what's causing the issue for you, and therefore have no way of fixing it.

**Comment by broadcastyourseb** [comment]
Oh sorry, I totally forget this point...

[xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/2356250/xsession-errors.txt)
No glass.log found in my home folder.
I think I found the bug. If you select random color in the option menu, you can't add a new note. With a predefined color, it's working for me.

**Comment by collinss** [comment]
Thanks. With your log I was able to quickly pinpoint the issue and fix it. I wasn't seeing that issue because the code path that was erroring out is only reached when the default theme is set to random (which mine wasn't).

**Comment by broadcastyourseb** [comment]
Great work. Thank you.
