### ISSUE TITLE
weather@mockturtl: Can't get weather info behind HTTP Proxy

### ISSUE THREAD

**Issue by maurom** [linuxmint/cinnamon-spices-applets#1947]
```
 * Applet version: 1.14.0
 * Cinnamon version: Cinnamon 3.2.7
 * Distribution: Debian GNU/Linux 9.5 (stretch)
 ```
**Notify author of applet**
@mockturtl

**Issue**

When using a http proxy to access Internet servers, the weather applet does not fetch data from remote endpoint (QUERY_URL).

**Steps to reproduce**

- Filter internet access, allowing only access via proxy server.
- Set proxy info via control panel and/or http_proxy & https_proxy environment variables.
- Add weather@mockturtl applet to the cinnamon panel.
- It shows "Loading ..." and never shows weather info.

**Expected behaviour**

- Sunny or at least cloudy ~24º C  (I hope, or at least any other forecast)

**Other information**

- Seems introduced in baa54f976ddb1c2ee683e2dcfdc63fc553f456e4
- Works fine when [line 182](https://github.com/linuxmint/cinnamon-spices-applets/blame/master/weather%40mockturtl/files/weather%40mockturtl/applet.js#L182) is uncommented

**Comment by mockturtl** [comment]
> Other information
> - Seems introduced in baa54f9
> - Works fine when line 182 is uncommented

Thanks for tracking it down!  Many users have [reported](https://github.com/mockturtl/cinnamon-weather/search?utf8=%E2%9C%93&q=proxy&type=) proxy issues over the years.  ([more](https://github.com/mockturtl/cinnamon-weather/issues/14#issuecomment-233716053))

pinging @jaszhix re: #59
