### ISSUE TITLE
screen-inhibit@mtwebster screen goes blank when should not

### ISSUE THREAD

**Issue by focusaurus** [linuxmint/cinnamon-spices-applets#1987]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version 3.8.9
 * Distribution - Mint 19
 * Graphics hardware *and* driver used: Intel Corporation UHD Graphics 620
 ```

**Notify author of applet**
@mtwebster 

**Issue**
Screen goes blank after ~5m of no input even with inhibit preventing power management.

**Steps to reproduce**

1. Click Inhibit applet, set "Power Management" slider to the left "O" position
1. Leave laptop idle for 5 minutes with no keyboard/mouse input

**Expected behaviour**

Screen stays on

**Other information**

UI could be clearer about whether the slider toggles mean "Power Management is inhibited from operating" or "Power management is enabled"

**Comment by icarter09** [comment]
Cinnamon 3.8.9
Applet version 2017-10-02 00:57 UTC
Linux Mint 19 64bit

I'm not able to duplicate this issue. If I set the applet to block the screen saver, it does so, and if I set it to allow the screen saver, it does so as well too.

**Comment by focusaurus** [comment]
It happens on my thinkpad but not my system76 laptop. I'm wondering if it's the bios turning off the screen. Will have a look at bios settings.

**Comment by icarter09** [comment]
@focusaurus can you update the ticket with your findings whenever you have a look at bios settings? Thanks.

**Comment by focusaurus** [comment]
I didn't find a relevant BIOS setting but I can't reproduce after a reboot either.
