### ISSUE TITLE
[windowlist@cobinja.de] not all preview windows shown

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#1994]
```
 * Applet version/Build date: 2018-07-18 13:17 UTC
 * Cinnamon version: Cinnamon 3.8.9
 * Distribution: Mint 19
```

**Notify author of applet**
@Cobinja 

**Issue**

When I open more than 4 windows in one group, the previews 5+ are not visible, because they spill over the right side.

**Steps to reproduce**
1. Open more than 4 windows in the same group, e.g. open `Thunderbird` and open four compose windows.
2. The last compose window cannot be seen, because it is already outside of the screen.

**Expected behaviour**
I would expect to see all open windows, either by making the previews smaller or by using additional rows.

**Other information**

I noticed that the number of windows visible is related to the setting `Number of unshrunk previews (Windows)` which is currently set to `8`.

It looks to me, as if `windowlist` thinks, the screen is twice as wide as it actually is. If I open more than 8 windows, the preview windows become smaller (but still do not completely show on my screen).

FYI I have 4 virtual workspaces set up.

**Comment by Cobinja** [comment]
I may need additional info about your setup. Do you have multiple monitors? Do you use Xinerama?

**Comment by sphh** [comment]
- Single monitor 2736x1824.
- [WindowList's Configuration file](https://github.com/linuxmint/cinnamon-spices-applets/files/2455244/windowlist.config.zip)
- This is a standard Linux Mint installation. How do I find out, if Xinerama is used? There is a file `/usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0` on the system ...

I am happy to send you some logfiles. Please just tell me what you need!

**Comment by jaszhix** [comment]
Issue template:

>  Snippet or attachment of ~/.xsession-errors

**Comment by Cobinja** [comment]
Does the newest version that I just releases fix this?

**Comment by sphh** [comment]
Yes, it does fix it. Thanks a lot for the very quick fix!!!!
