### ISSUE TITLE
[windowlist@cobinja.de] not able to select window in same window group when drag'n'dropping

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#1995]
```
 * Applet version/Build date: 2018-07-18 13:17 UTC
 * Cinnamon version: Cinnamon 3.8.9
 * Distribution: Mint 19
 ```

**Notify author of applet**
@Cobinja 

**Issue**

**Steps to reproduce**
1. Open `Thunderbird` and maximize it.
2. Select an email with an attachment.
3. Open a new composer window.
4. Select and drag the attachment from the main window to the new composer window.

There seems to be no way to activate the new composer window with the mouse "holding" the attachment.

**Expected behaviour**
If you move the mouse cursor over another window preview, this window is moved to the foreground and you can drop the attachment. If you try the same within the `Thunderbird` group, the preview windows do not pop up, so you cannot "select" another window in the same group.

**Other information**
As a workaround, I make the composer window to stay on top. I could also minimize the main `Thunderbird` window, so that the drop area of the composer window is visible. But these are only clumsy workarounds.

**Comment by Cobinja** [comment]
This a known limitation at the moment. This feature may get extended in one of the next versions

**Comment by jaszhix** [comment]
This is an issue on ITM as well, may be a limitation of how Cinnamon handles input focus - the thumbnail menu is a modal and grabs input, and it doesn't work when in the middle of a DND operation originating outside the actor that has key focus. https://github.com/jaszhix/icingtaskmanager/issues/140

**Comment by Cobinja** [comment]
That's what I noticed as well when implementing it. The menu items for windows don't even get mouse events on DND operations, so this would have to somehow emulate them.

**Comment by sphh** [comment]
I just upgraded to Linux Mint 19.1 and tried the new Grouped Window List. I noticed that the drag'n'drop stuff works there. Do you think it's possible to port it to your windowlist? (Which I still prefer to the Grouped Window List!) Thanks.

**Comment by sphh** [comment]
I just re-installed CobiWindowList and noticed that this issue was resolved. Thanks.
