### ISSUE TITLE
[batterymonitor@pdcurtis] can't replace contents of batteryscript.sh without breaking

### ISSUE THREAD

**Issue by luerhard** [linuxmint/cinnamon-spices-applets#1997]
Hey there,
i know this might not be the right place to ask this, but i don't know where to go. I run batterymonitor@pdcurtis on an Thinkpad T440s which has two batteries. Since the batterymonitor only shows the Percentage Remaining of one of the Batteries, i decided to write a python script to replace the number. It works like a charm and is based on the console output of `inxi -Bxx`. (The complete code is on the bottom.)

My problem starts when i try to change the contents of batteryscript.sh to:
```
#upower -i $(upower -e | grep BAT) | grep -E percentage | xargs | cut -d' ' -f2|sed s/%// > /tmp/.batteryPercentage
#upower -i $(upower -e | grep BAT) | grep -E state | xargs | cut -d' ' -f2|sed s/%// > /tmp/.batteryState

python replace_battery_values.py
```

If i invoke the script manually it works fine, but the applet.js seems not to start the script.

PATH_TO_APPLET/replace_battery_values.py (same directory as applet.js and batteryscript.sh)
```
#!/usr/bin/python
from subprocess import check_output
import re

#read command-prompt
raw_out = check_output(["inxi", "-Bxx"]).decode("utf-8")

#remove ansi colors:
raw_out = re.sub(r'\x1B\[[0-?]*[ -/]*[@-~]','', raw_out)

# Calculate Percentage
batteries = re.findall(r"charge: ([0-9\.]{1,4}) Wh (?:.*?) condition: ([0-9\.]{1,4})/", raw_out)
currents, capables =zip(*batteries)
current = sum(float(c) for c in currents)
capable = sum(float(c) for c in capables)
percentage = int(current / capable * 100)

with open("/tmp/.batteryPercentage", "w") as file:
    file.write(str(percentage)+"\n")

#Get status
statuses = re.findall(r"status: (.*?)\n", raw_out)
status = ", ".join([s for s in statuses if s != "N/A"])

with open("/tmp/.batteryState", "w") as file:
    file.write(status + "\n")
 ```

**Notify author of applet**
@pdcurtis 

**Issue**

Maybe if someone sees my error rightaway - i would be very thankful for a solution! I am probably doing something super obvious wrong. Otherwise if you have a better solution to get a accurate Battery-Percentage with multiple batteries, i would also be glad to know !

**Other information**
```
Applet-Version: 1.3.2
Cinnamon-Version: Cinnamon 3.8.9
Distribution: Linux Mint 19
```

**Comment by luerhard** [comment]
for those who are interested, This script works as long as it is invoked with its full path in the batteryscript.sh:
```
#!python

from subprocess import check_output
import re

#read command-prompt

raw_out = check_output(["inxi", "-Bxx"]).decode("utf-8")

raw_out = repr(raw_out)

# Calculate Percentage
batteries = re.findall(r"charge\\x03 ([0-9\.]{1,4}) Wh (?:.*?) \\x0312condition\\x03 ([0-9\.]{1,4})/", raw_out)

print(batteries)
print(repr(raw_out))
currents, capables =zip(*batteries)
current = sum(float(c) for c in currents)
capable = sum(float(c) for c in capables)
percentage = int(current / capable * 100)

with open("/tmp/.batteryPercentage", "w") as file:
    file.write(str(percentage)+"\n")

#Get status

statuses = re.findall(r"status\\x03 (.*?)\\x03\\n", raw_out)

status = ", ".join([s for s in statuses if s != "N/A"])

with open("/tmp/.batteryState", "w") as file:
    file.write(status + "\n")

```

**Comment by Odyseus** [comment]
Hello, @luerhard.

Just an FYI. You can simplify your regular expressions by disabling the color on the `inxi` output (`c0` option).

```python
raw_out = check_output(["inxi", "-Bxxc0"]).decode("utf-8")
```
