### ISSUE TITLE
bash-sensors@pkkk: menu popup not working

### ISSUE THREAD

**Issue by phodd** [linuxmint/cinnamon-spices-applets#2015]
```
 * Applet version: 0.7 / 1537552578
 * Cinnamon version: 2.8.8
 * Distribution: Mint 17.3
 ```

**Notify author of applet**
@pkkk

**Steps to reproduce**

Install the above version of bash-sensors in Cinnamon 2.8.8 (possibly other versions). Click on the applet to bring up the 'menu' with status information from the menu command.

Nothing appears. In fact it seems the menu script does not even run.

**Expected behaviour**

A styled version of the menu should appear, or at the very least, the menu should appear without any style as a failover.

**Other information**

This is as a result of older Cinnamon versions apparently not having the same stylesheet features as newer versions. Pull request #2014 contains a potential fix.

**Comment by jaszhix** [comment]
This extension is unmaintained, but working for me on git Cinnamon. 2.8.8 is very old, please upgrade Cinnamon.
