### ISSUE TITLE
Redshift: incomplete german translation

### ISSUE THREAD

**Issue by Etamuk** [linuxmint/cinnamon-spices-applets#2035]
Hello,

i noticed the german translation of redshift cinnamon-spices-applet is incomplete. 
I would like to complete it. So you can use it for an update.

On [this site](https://github.com/linuxmint/cinnamon-spices-applets/tree/master/redshift%40marvel4u/files/redshift%40marvel4u/po) i noticed some language files. But the file for german translation seems to miss some strings. 

If you can send me a complete translation file i will translate it into german.

Best regards from Germany.

**Notify author of applet**
@Marvel4U

**Comment by icarter09** [comment]
@Etamuk I don't know if you'll be getting the complete translation file any time soon. Feel free to start adding any and all strings that are missing or should be present. Thanks.

**Comment by NikoKrause** [comment]
Here's the file: 
[de.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/2574053/de.po.zip)

Please use the application `poedit` for translation.

**Comment by sphh** [comment]
@icarter09 , please find a German translation in this file:
[de.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/4008361/de.po.zip)

BTW I noticed, many duplicate strings in the original applet, e.g. "Redshift Day Brightness" and "Redshift day brightness" or "Redshift day colour" and "Redshift Day colour temperature" just to name two. Also capitalizing is not consistent …
