### ISSUE TITLE
sticky@scollins: Unpinned notes are always lowered

### ISSUE THREAD

**Issue by jonathanwin** [linuxmint/cinnamon-spices-applets#2062]
```
 * Applet version/Build date: v1.2
 * Cinnamon version : 3.2.7 
 * Distribution : debian stretch
 * Graphics hardware :
    * VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
    * i915, xserver-xorg-video-intel 2:2.99.917+git20161206-1; libdrm-intel1 2.4.74-1
    * VGA compatible controller: NVIDIA Corporation GK107GLM [Quadro K1100M] (rev a1)
    * nouveau , xserver-xorg-video-nouveau 1:1.0.13-3; libdrm-nouveau2 2.4.74-1
 ```

**Issue**
Hi @collinss, first of all, Thanks for developing this applet! :)
Now on to the problem :
When the notes are unpinned, they are lowered to the background, rather than the 'lower on click' behaviour that seems to be intended.

**Steps to reproduce**
Set the notes mode to 'Unpin notes (lower on click)'

**Result**
All notes are immediately lowered to the background, and hide behind all apps.
Dragging a note by an exposed area works, and temporarily brings the note to the foreground, but it  lowers again as soon as the drag is released.
I'm unsure how the '(lower on click)' behaviour is intended to work, as it seems it would make editing the note impossible

Clicking on a note, or mousedown of a drag, cause the following message in .xsession-errors:
```(cinnamon:2453): Clutter-WARNING **: Attempting to remove actor of type 'StEntry' from group of class 'StBin', but the container is not the actor's parent.```

**Expected Behaviour**
I would expect unpinned notes to behave like normal windows : stay where they are in the stack unless they are forcibly lowered.
There would need to be a separate "lower this note" button on each note, if clicking anywhere on a note is supposed to lower it at the moment, but I'm unsure if the function is truly needed.

A separate "pin this note" toggle button could be useful, though (possibly along with an "unpin all notes" notification button command)

Cheers!

**Comment by collinss** [comment]
The sticky notes aren't actually windows, and there really isn't any way to make them behave that way short of a complete rewrite of the applet. I have no intention of doing that at this point.

**Comment by jonathanwin** [comment]
Just to be clear, the way the notes are supposed to behave right now is:
Pinned: Above all other windows
Unpinned: Below all other windows
Is that correct, or am I hitting some kind of bug?

**Comment by collinss** [comment]
Pinned means notes are _always_ above windows. Unpinned means that they are only above windows when you click the applet, and they lower again when you click anything that isn't a note.

**Comment by jonathanwin** [comment]
OK; that seems OK but slightly buggy here:
* Pinned works fine.
* Unpinned, I must click the applet on the panel to raise the notes:
  * Clicking a note isn't enough to raise the notes (By design? it would be very useful)
    * Clicking in the text area of a note does allow editing the note, but does not raise the notes.
    * In this edit while unraised mode, clicking another app focuses that app, but it can then be hard to return to the note simply by clicking the text area, or to drag the notes (changing focused window/ clicking the desktop/panel seems to help getting this 'feature' to work again)
  * Clicking the panel applet opens the applet menu, and raises the notes.
  * Clicking any other window now lowers the notes.
  * However, once the notes are raised, if I click in the text area of a note, clicking other windows does nothing (I cannot return to other windows), the only way to lower the notes seems to be to click the panel or applet menu.

Allowing any click on a note to raise them would be great, since it is really annoying to go searching for the 0.5cm applet icon, when there is a large piece of note visible.
Fixing unraising in edit mode would be good, too.

Short of rewriting the applet to use actual windows for the notes, it would be great if the notes could behave as a window as a whole: all the notes stay together, but when another window is raised above them, the notes do not fall behind /all/ windows but just the focused one (and any later focused windows): the notes' canvas has a position in the stack of windows.
Not sure if that is easily doable either, though.

I have tested this with the latest version: 86703c4d @2018-09-06 "fix undeclared variable issue ..."

Thanks for your work! :)

**Comment by collinss** [comment]
Yeah, there is a bug where sometimes the notes become unresponsive and wont lower. I've 'fixed' this kind of focus issue many times and they keep coming back. A lot of the issues you mentioned above are actually limitations of the toolkit and the window manager, and I can't really make it work like a normal window. If I ever end up spending a large amount of time on this, I'll probably end up rewriting the notes in Gtk, and it will fix a lot of these issues.
