### ISSUE TITLE
Cinnamenu bug - Under Mint 19/grid view there is no app right-click context menu, unable to add to favorites

### ISSUE THREAD

**Issue by Sven71** [linuxmint/cinnamon-spices-applets#2072]
Used to work, and does work just fine with Mint 18.3, but not with Mint 19, the right-click menu does not appear at all. Thus unable to add apps to favorites.

**Comment by jaszhix** [comment]
Hi @Sven71, I loaded Cinnamenu in a fresh Mint 19 VM with Cinnamon 3.8, and unable to reproduce the context menu not appearing. Before doing anything, make sure Cinnamenu is up to date in Settings -> Applets.

If that doesn't resolve the issue, please provide the info requested in the [issue template](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/ISSUE_TEMPLATE).

**Comment by Sven71** [comment]
Hi @jaszhix , updated everything.
* Cinnamenu ver. 4.0.0 (installed via Mint applet installer app)
* Cinnamon version 3.8.9
* Distribution Linux Mint 19 Cinnamon 64bit
* Graphics hardware Intel Corporation 3rd Gen Core processor Graphics Controller

Experimented a little now and noticed that the context menu becomes unavailable when custom height is switched ON and increased so it comes close (5px) to the screen edge. Funny thing, that's exactly how I wanted it to be.
Hope that bit of info helps.

**Comment by smurphos** [comment]
@Sven71 What cinnamon desktop theme are you using? Can you reproduce the issue with the default Cinnamon theme?

**Comment by Sven71** [comment]
Hi Steve!
I'm actually using OSX-Arc-Darker theme. Tried with default theme, the ability to use context menu disappears 2px from the edge of the screen, so yes, it's theme-dependent :)  Feels like the system is drawing some kind of a transparent frame all around the menu beyond which some weird stuff begins to happen. As for me personally, once I figured out the reason for the behavior (thanks for the tips guys!) it stopped being a problem for me, I just keep the menu a bit farther from the edge that's all.

**Comment by smurphos** [comment]
@jaszhix I think this is a manifestation of #7427 which effects all the menus when the menu height is close to the monitor height. I had thought Cinnamenu was immune but clearly not.

**Comment by jaszhix** [comment]
Not sure if this is theme dependent or not, I can reproduce it in the default, Mint Y, and the X-Arc-Dark themes. Seems to only occur in the grid view. The easiest fix would be to prevent the menu from becoming too tall, there's logic in place for that for cinnamon 4.0, but its still letting the menu reach the exact height of the monitor (minus panel height).
