### ISSUE TITLE
pa-equalizer@jschug.com: Not working b/c wrong access to `pulseaudio-equalizer` config files

### ISSUE THREAD

**Issue by faneca** [linuxmint/cinnamon-spices-applets#208]
[Have you read the guidelines for contributing?]: <> (Before opening an issue, please read the guidelines for contributing linked above. Else the issue will be closed. Also don't forget to notify the author.)
@clefebvre @NikoKrause
(the author is "jschug.com", but it seems a corresponding github account doesn't exist; I'm sorry if I notified the wrong people)

[Issue]: <> (Describe your issue below.)
**TL;DR**: Simply put, the applet doesn't work at all in its current form (Mint 18.1 Mate ed. here). I have a solution (see below) but I'm concerned about its (non-)portability, so no PR provided (but a diff).

--

The problem is already described on the [applet's homepage](https://cinnamon-spices.linuxmint.com/applets/view/176), on a comment by user "copecu" (2016-10-21 16:23) which I copy here. Emphasis is mine:
> Hi,
>
> I am on Linux Mint Cinnamon 18 and it seems that this nice applet doesn't work. I can add them to the panel but **toggle equalizer doesn't work and no presets are showed**.

I'm on LinuxMint 18.1 Serena Mate Edition and can confirm the problem.

To reproduce it, just install `pulseaudio-equalizer` and this applet, and check that while the former works as expected the latter exhibits the aforementioned behavior.

I **found the root of the issue and have a working solution for my system**, but I'm unsure if it'd be portable to other distributions (or even to older Mint versions) as-is, so I won't do a pull request (but provide the diff below).

The cause is two-fold:

1. **New versions of `pulseaudio-equalizer` move `pulseaudio`'s config directory** from `~/.pulse` to `~/.config/pulse`. Pulseaudio itself doesn't seem to care if its config is put in either of them; when both are present, it prefers the latter.

2. The calls to `monitor()` and `replace()` on Gio File objects pass **wrong `flags` parameters**: they both use `null` instead of the corresponding constant.

Here's the diff:
`cinnamon-spices-applets/pa-equalizer@jschug.com/files/pa-equalizer@jschug.com/applet.js`
```diff
@@ -9,7 +9,7 @@
 const Gettext = imports.gettext.domain('cinnamon-applets');
 const _ = Gettext.gettext;
 
-const CONFIG_DIR = GLib.get_home_dir() + "/.pulse";
+const CONFIG_DIR = GLib.get_home_dir() + "/.config/pulse";
 const EQCONFIG = CONFIG_DIR + "/equalizerrc";
 const EQPRESETS = EQCONFIG + ".availablepresets";
 const PRESETDIR1 = CONFIG_DIR + "/presets/";
@@ -26,7 +26,7 @@
     load: function() {
         try {
             GLib.spawn_command_line_sync("pulseaudio-equalizer interface.getsettings");
-            this._monitor = Gio.file_new_for_path(EQCONFIG).monitor(null, null);
+            this._monitor = Gio.file_new_for_path(EQCONFIG).monitor(Gio.FileMonitorFlags.NONE, null);
             this._monitor.connect("changed", Lang.bind(this, function(self, file, otherFile, eventType) {
                 if (eventType == Gio.FileMonitorEvent.CHANGES_DONE_HINT) {
                     this._configChanged();
@@ -42,7 +42,7 @@
     },
     save: function() {
         try {
-            let out = Gio.file_new_for_path(EQCONFIG).replace(null, false, null, null);
+            let out = Gio.file_new_for_path(EQCONFIG).replace(null, false, Gio.FileCreateFlags.NONE, null);
             out.write_all(this._rawdata.join('\n'), null);
             out.close(null);
```
maybe the first of the changes could be replaced by a recommendation in the applet's (non-existent) `README` file explaining how to symlink `~/.pulse` to `~/.config/pulse`

**Comment by NikoKrause** [comment]
I'm confused. How do Cinnamon applets work on MATE?

**Comment by collinss** [comment]
To make sure it's always compatible, you could check for the existence of the preferred directory, and then fall back to the other if it doesn't exist.

**Comment by faneca** [comment]
@NikoKrause:
I'm on the Mate Edition *GNU/Linux distribution* (which I guess is irrelevant here, I only have noted it for the sake of completion) but this bug report is about the Cinnamon *desktop environment*. Sorry about the confusion, I though that was obvious but I'm proven wrong. Hope this clarifies it ;-).

@collinss:
Yeah, you're right. I guess checking first for `~/.config/pulse` and then fallback to `~/.pulse` if it doesn't exist would make more sense than any of the above. I wonder why I didn't think of that myself :-(. Thanks for the idea!
I'll read how to make that check with Gio and get back with a PR.

**Comment by faneca** [comment]
Ok, this is a quick hack I've come up with, but I'm not happy about it, as it looks like an ugly one to me. Also, being a cjs newbie, I'm not sure I'm doing "the right thing" about error management (Should I `throw` instead of returning `undefined`? Or maybe something completely different?). Comments are more than welcome...
```diff
@@ -1,6 +1,7 @@
 const Lang = imports.lang;
 const Signals = imports.signals;
 const Applet = imports.ui.applet;
+const Main = imports.ui.main;
 const PopupMenu = imports.ui.popupMenu;
 const GLib = imports.gi.GLib;
 const Gio = imports.gi.Gio;
@@ -9,7 +10,30 @@
 const Gettext = imports.gettext.domain('cinnamon-applets');
 const _ = Gettext.gettext;
 
-const CONFIG_DIR = GLib.get_home_dir() + "/.pulse";
+const UUID = "pa-equalizer@jschung.com";
+
+const CONFIG_DIR = (function() {
+    let homedir = GLib.get_home_dir();
+
+    let paths = [
+        homedir + "/.config/pulse",
+        homedir + "/.pulse",
+    ];
+
+    for (let i = 0; i < paths.length; i++) {
+        let file = Gio.file_new_for_path(paths[i]);
+        if (file.query_file_type(Gio.FileQueryInfoFlags.NONE, null) == Gio.FileType.DIRECTORY) {
+            return paths[i];
+        }
+    }
+
+    let e = "Pulseaudio's configuration directory not found! Applet won't work.\n" +
+        "Directories tried:\n" + paths.join("\n");
+    Main.criticalNotify(UUID, e, null);
+    global.logError(e);
+    global.logTrace(e);
+    return undefined;
+})();
 const EQCONFIG = CONFIG_DIR + "/equalizerrc";
 const EQPRESETS = EQCONFIG + ".availablepresets";
 const PRESETDIR1 = CONFIG_DIR + "/presets/";
@@ -26,7 +50,7 @@
     load: function() {
         try {
             GLib.spawn_command_line_sync("pulseaudio-equalizer interface.getsettings");
-            this._monitor = Gio.file_new_for_path(EQCONFIG).monitor(null, null);
+            this._monitor = Gio.file_new_for_path(EQCONFIG).monitor(Gio.FileMonitorFlags.NONE, null);
             this._monitor.connect("changed", Lang.bind(this, function(self, file, otherFile, eventType) {
                 if (eventType == Gio.FileMonitorEvent.CHANGES_DONE_HINT) {
                     this._configChanged();
@@ -42,7 +66,7 @@
     },
     save: function() {
         try {
-            let out = Gio.file_new_for_path(EQCONFIG).replace(null, false, null, null);
+            let out = Gio.file_new_for_path(EQCONFIG).replace(null, false, Gio.FileCreateFlags.NONE, null);
             out.write_all(this._rawdata.join('\n'), null);
             out.close(null);
```

**Comment by collinss** [comment]
@faneca you could simplify it a lot more. Just do something like this:

    -const CONFIG_DIR = GLib.get_home_dir() + "/.pulse";
    +if (GLib.file_test(GLib.get_home_dir() + "/.config/pulse", GLib.FileTest.EXISTS) {
    +    const CONFIG_DIR = GLib.get_home_dir() + "/.config/pulse";
    +}
    +else {
    +    const CONFIG_DIR = GLib.get_home_dir() + "/.pulse";
    +}

**Comment by faneca** [comment]
`GLib.file_test()` is much simpler, thanks for that.

OTOH, well, as I said before, I'm not cjs expert, but I think I really can't do that: `const` is block-scoped, so after you exit the `if` block `CONFIG_DIR` would be `undefined` (didn't actually try, tho, so maybe I'm wrong about that). That's the reason I'm using a lambda (inline function).
There are other options as well (defining it initially with `let` or `var` and, then, either assign it to a constant or just use it like that, for instance). I'll give it a spin and see what I find more appropriate.

I'm still looking for suggestions about what'd be the best thing to do with the error when no config directory is found.

**Comment by collinss** [comment]
I've seen ```const``` used like that many times before. Unlike c, the only thing in js that's scoped is a function. [This](https://www.sitepoint.com/demystifying-javascript-variable-scope-hoisting/) explains it more.

**Comment by faneca** [comment]
I'll try anyway when I find some time and let you know if it works ;-). But as of ECMAScript 2015 (6th edition), that article is no longer relevant. Extracted from there:
> It’s worth noting that the upcoming [ECMAScript 6 will support block level scopes via the `let` keyword](http://www.sitepoint.com/preparing-ecmascript-6-let-const/).

More info also [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const) (see from lines 20 to 36 in the example).

**Comment by lestcape** [comment]
@faneca i just recommended you the usage of: 
```
GLib.get_user_config_dir()
```
 instead of 
```
GLib.get_home_dir() + "/.config
```
https://developer.gnome.org/glibmm/stable/group__MiscUtils.html#gae517b931f4753abcd48adb2769a8fc48
