### ISSUE TITLE
[multicore-sys-monitor@ccadeptic23] 1.8.7 crashes Cinnamon

### ISSUE THREAD

**Issue by vlatkoB** [linuxmint/cinnamon-spices-applets#2097]
```
 * Applet version: 1.8.7.
 * Cinnamon version: 4.0.2
 * Distribution: Arch
 ```
**Issue**
Cinnamon 4.0.2 crashes with both applet 1.8.7 and its previous version.
Removing only this applet solves the crash issue.

Previous applet version worked with Cinnamon 4.0.1, but not with 4.0.2, so I'd assume something changed in Cinnamon from 4.0.1 -> 4.0.2.

There is still a warning in `Add applets to panel` dialog about `This applet contains functions that could potentially cause Cinnamon to crash or freeze...`.

**Comment by jaszhix** [comment]
This has been fixed, but if you can't start cinnamon:

- Install dconf-editor
- Search for enabled-applets
- Remove `multicore-sys-monitor@ccadeptic23` from the list, take care not to leave a trailing comma.
- Load Cinnamon
- Upgrade the applet before re-adding it to the panel.

**Comment by vlatkoB** [comment]
Interesting, uninstalling and reinstalling solved the issue. Previously I only disabled, upgraded and enabled. And I see it clearly written in the instructions. My bad. :-(
