### ISSUE TITLE
Back-up State: Issues under LinuxMint 19.

### ISSUE THREAD

**Issue by perette** [linuxmint/cinnamon-spices-applets#2102]
```
 * Applet version/Build date ("last-edited"): 1541260271,
 * Cinnamon version (cinnamon --version): 3.8.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): LinuxMint 19
 * Intel something or other with Noveau
 ```

(file indicates no author on file.)

There are several code issues stemming from stricter JavaScript interpretation, which prevent applet loading:

* in function `logError`: `caller`, `callee` not available in strict mode (actual use is `logError.caller.name`)
* in function `refreshLocation`: strict mode doesn't like vaguely scoped variables, so `let` is needed to use variables `shortDate` and `longDate`.
* in function _searchStringInArray: need `let` for variable `k`.
* in function _findDate: need `let` for variable `index`.

Additionally, the configurator panel is storing the pathname as a URL (`file:///foo/bar/whatever`) but Cinnamon.get_file_contents_utf8_sync can't open this.  Editing the config file to strip the URI scheme from the path (now `/foo/bar/whatever`) fixes it.  I'm not sure if this should be configured a bug against the back up checker, but it's probably the faster fix than getting Cinnamon to fix `get_file_contents_utf8_sync` to recogni2ze a `file://` URI scheme and remove it.

**Steps to reproduce**
[Try to] Use applet under LinuxMint 19.

**Expected behaviour**
Applet loads and runs.

**Comment by perette** [comment]
Patch below, if you want it.

```
--- backup.original	2018-11-21 12:45:28.804121771 -0500
+++ back-up_state@natsakis.com/applet.js	2018-11-21 13:21:48.648534283 -0500
@@ -16,7 +16,7 @@
 }
 
 function logError(error) {
-    global.logError(UUID + '#' + logError.caller.name + ': ' + error);
+    global.logError(UUID + ': ' + error);
 }
 
 function main(metadata, orientation, instance_id) {
@@ -61,8 +61,8 @@
             this.set_applet_tooltip(_("Has never run succesfully!"));
           }
           else {
-            shortDate = new Date(this._findDate());
-            longDate = new Date(this._findDate());
+            let shortDate = new Date(this._findDate());
+            let longDate = new Date(this._findDate());
             shortDate.setDate(shortDate.getDate() + this._opt_warningDays);
             longDate.setDate(longDate.getDate() + this._opt_errorDays);
             if (longDate < new Date()) {
@@ -83,7 +83,7 @@
     },
     
     _searchStringInArray: function (str, strArray) {
-      k = null;
+      let k = null;
       for (var j=0; j<strArray.length; j++) {
           if (strArray[j].match(str)) k = j;
       }
@@ -92,9 +92,9 @@
     
     _findDate: function () {
         try {
-          let logs = Cinnamon.get_file_contents_utf8_sync(this._opt_logFile);
+          let logs = Cinnamon.get_file_contents_utf8_sync(this._opt_logFile.replace(/^(file:\/\/)/, ''));
           let lines = logs.split('\n');
-          index = this._searchStringInArray(this._opt_idString,lines);
+          let index = this._searchStringInArray(this._opt_idString,lines);
           
           if (index == null) {
             return _("Has never run successfully!");
```

**Comment by jaszhix** [comment]
Hi, I opened a PR for this. I removed that logError function, since its doing redundant work of `global.logError`. Also removed the try-catch blocks, and incorrect constructor parameters. I'm surprised it loaded at all on <3.8.
