### ISSUE TITLE
IcingTaskManager: Firefox context menu empty

### ISSUE THREAD

**Issue by tcmger** [linuxmint/cinnamon-spices-applets#212]
@jaszhix

[Issue]: <> (Describe your issue below.)
Cinnamon 3.2.7
Icing Task Manager 4.4.0
Linux MInt 18.1. Serena -64bit
Firefox 52.0 (64-Bit)

Context menu ITM empty on each option

**Comment by NikoKrause** [comment]
I'm closing this because you obviously didn't read the guidelines for contribution. I'll reopen it, when you changed the issue properly.

**Comment by jaszhix** [comment]
- Pastbin the outputs of:
    - ~/.cinnamon/configs/IcingTaskManager@json/*.json
    - ~/.cinnamon/glass.log
    - ~/.xsession-errors
  - Describe the steps needed to be taken in order to reproduce this bug.

**Comment by tcmger** [comment]
/home/usr/.cinnamon/glass.log:

info t=2017-03-14T17:27:36.011Z Cinnamon.AppSystem.get_default() started in 327 ms
info t=2017-03-14T17:27:36.018Z loading user theme: /usr/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css
info t=2017-03-14T17:27:36.050Z added icon directory: /usr/share/themes/Mint-Y-Dark/cinnamon
info t=2017-03-14T17:27:36.179Z PlacesManager: Updating devices
info t=2017-03-14T17:27:36.214Z loaded at Tue Mar 14 2017 18:27:36 GMT+0100 (CET)
info t=2017-03-14T17:27:36.760Z Loaded applet menu@cinnamon.org in 541 ms
info t=2017-03-14T17:27:36.813Z Loaded applet show-desktop@cinnamon.org in 50 ms
info t=2017-03-14T17:27:36.925Z Role locked: panellauncher
info t=2017-03-14T17:27:37.198Z Loaded applet panel-launchers@cinnamon.org in 383 ms
info t=2017-03-14T17:27:37.220Z Loaded applet window-list@cinnamon.org in 20 ms
info t=2017-03-14T17:27:37.301Z Loaded applet network@cinnamon.org in 79 ms
info t=2017-03-14T17:27:37.316Z Loaded applet systray@cinnamon.org in 12 ms
info t=2017-03-14T17:27:37.348Z Loaded applet calendar@cinnamon.org in 30 ms
info t=2017-03-14T17:27:37.580Z Loaded applet IcingTaskManager@json in 231 ms
info t=2017-03-14T17:27:37.594Z Loaded applet PDFManager@cinnamon.org in 13 ms
info t=2017-03-14T17:27:37.595Z AppletManager.init() started in 1381 ms
info t=2017-03-14T17:27:37.599Z Cinnamon took 1940 ms to start
info t=2017-03-14T17:27:39.133Z Adding systray: claws-mail (24x24px)
info t=2017-03-14T17:27:39.135Z Adding systray: blueman (24x24px)
info t=2017-03-14T17:27:39.138Z Hiding systray: network
info t=2017-03-14T17:27:41.298Z Adding systray: insync.py (24x24px)
info t=2017-03-15T08:21:47.594Z Adding systray: unknown (24x24px)

**Comment by tcmger** [comment]
~/.cinnamon/configs/IcingTaskManager@json/133.json

{
    "ITM": {
        "type": "header",
        "description": "ITM Settings"
    },
    "seperator0": {
        "type": "separator"
    },
    "autoUpdate": {
        "type": "checkbox",
        "default": false,
        "description": "Update this applet automatically",
        "tooltip": "When enabled, ITM will check the Github releases on init, and will start to upgrade if it finds a newer version.",
        "value": false
    },
    "WindowList": {
        "type": "header",
        "description": "Window List Settings"
    },
    "seperator1": {
        "type": "separator"
    },
    "number-display": {
        "type": "combobox",
        "default": 1,
        "description": "Number display",
        "options": {
            "Smart": 1,
            "Normal": 2,
            "None": 3,
            "All": 4
        },
        "tooltip": "normal: display window number, smart: display window number if more than one window, none: don't display number, all: display window number for favorites too",
        "value": 3
    },
    "title-display": {
        "type": "combobox",
        "default": 1,
        "description": "Title display",
        "options": {
            "None": 1,
            "App": 2,
            "Title": 3,
            "Focused": 4
        },
        "tooltip": "focused: show focused window title, title: display the window title, app: diplay app name, none: don't display anything",
        "value": 3
    },
    "pinned-apps": {
        "type": "generic",
        "default": [],
        "value": []
    },
    "group-apps": {
        "type": "checkbox",
        "default": true,
        "description": "Group apps",
        "tooltip": "Group each app's set of windows.",
        "value": true
    },
    "show-alerts": {
        "type": "checkbox",
        "default": true,
        "description": "Show app alerts and notifications",
        "tooltip": "If enabled, notifications and alerts will appear.",
        "value": true
    },
    "show-pinned": {
        "type": "checkbox",
        "default": true,
        "description": "Show pinned apps",
        "tooltip": "Controls whether or not the pinned apps appear in the panel if they are not open.",
        "value": true
    },
    "arrange-pinnedApps": {
        "type": "checkbox",
        "default": true,
        "description": "Arrange pinned apps",
        "tooltip": "Arrange pinned apps into a different order.",
        "value": true
    },
    "middle-click-action": {
        "type": "checkbox",
        "default": true,
        "description": "Middle clicking app buttons creates new app instances",
        "tooltip": "Determines the behavior of middle mouse button clicks on app buttons. Setting this to false will close the last focused window from the app group on middle click.",
        "value": true
    },
    "cycleMenusHotkey": {
        "type": "keybinding",
        "default": "<Super>space",
        "description": "Global hotkey for cycling through thumbnail menus",
        "tooltip": "This allows you to cycle through the menus without activating a window.",
        "value": "<Super>space"
    },
    "show-apps-order-hotkey": {
        "type": "keybinding",
        "default": "<Super>grave",
        "description": "Global hotkey to show the order of apps",
        "tooltip": "When triggered, the window count label will be replaced with its order in the app list temporarily.",
        "value": "<Super>grave"
    },
    "show-apps-order-timeout": {
        "type": "spinbutton",
        "default": 2500,
        "min": 100,
        "max": 10000,
        "step": 10,
        "units": "milliseconds",
        "description": "Duration of the apps order display on hotkey press",
        "tooltip": "Determines the duration the window count labels are replaced with the app's order number.",
        "value": 2490.0
    },
    "Thumbnails": {
        "type": "header",
        "description": "Thumbnail Settings"
    },
    "seperator4": {
        "type": "separator"
    },
    "thumbnail-timeout": {
        "type": "spinbutton",
        "default": 50,
        "min": 0,
        "max": 5000,
        "step": 5,
        "units": "milliseconds",
        "description": "Thumbnail timeout",
        "tooltip": "Controls how quickly an app's set of window thumbnails will fade out when the mouse leaves the app button.",
        "value": 50
    },
    "thumbnail-size": {
        "type": "spinbutton",
        "default": 6,
        "min": 0,
        "max": 100,
        "step": 1,
        "units": "size",
        "description": "Thumbnail size",
        "tooltip": "Controls the size of the thumbnails.",
        "value": 48.0
    },
    "show-thumbnails": {
        "type": "checkbox",
        "default": true,
        "description": "Show thumbnails",
        "tooltip": "Show window thumbnails when hovering over an app button.",
        "value": true
    },
    "animate-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Animate thumbnails",
        "tooltip": "If enabled, thumbnails will animate when appearing and disappearing.",
        "value": false
    },
    "vertical-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Enable vertical thumbnails",
        "tooltip": "If enabled, thumbnails will stack vertically.",
        "value": true
    },
    "sort-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Sort windows for each app by last focused",
        "tooltip": "Controls whether the order windows appear for an app is by last focused, or the order they were opened.",
        "value": false
    },
    "onclick-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Open thumbnails on click",
        "tooltip": "Open the thumbnails on click if there is more than one window open.",
        "value": false
    },
    "include-all-windows": {
        "type": "checkbox",
        "default": false,
        "description": "Include all app windows",
        "tooltip": "Controls whether or not thumbnails for smalller child windows, such as exit confirmations and file dialogues will be included in the thumbnail list.",
        "value": true
    },
    "AppMenu": {
        "type": "header",
        "description": "Context Menu Settings"
    },
    "seperator5": {
        "type": "separator"
    },
    "show-recent": {
        "type": "checkbox",
        "default": true,
        "description": "Show recent items",
        "tooltip": "Controls whether recent items will appear in the context menu.",
        "value": true
    },
    "menuItemType": {
        "type": "combobox",
        "default": 1,
        "description": "Menu item type",
        "options": {
            "Symbolic icons": 1,
            "Non-symbolic icons": 2,
            "No icons": 3
        },
        "tooltip": "Determines whether menu item icons are symbolic, non-symbolic, or not shown.",
        "value": 1
    },
    "firefox-menu": {
        "type": "combobox",
        "default": 1,
        "description": "Firefox context menu",
        "options": {
            "Most Visited": 1,
            "Recent History": 2,
            "Bookmarks": 3
        },
        "tooltip": "Most Visited: show the sites you visit most, Recent History: display the the last pages you visited, Bookmarks: show your favorite bookmarks.",
        "value": 3
    },
    "autostart-menu-item": {
        "type": "checkbox",
        "default": true,
        "description": "Show autostart option",
        "tooltip": "Shows the autostart toggle option in an app's context menu.",
        "value": false
    },
    "monitor-move-all-windows": {
        "type": "checkbox",
        "default": true,
        "description": "Apply the monitor move option to all windows",
        "tooltip": "When clicking \"Move to monitor\" in the context menu, this option will move all of an app's windows instead of just the last focused window from the app.",
        "value": true
    },
    "HoverPeek": {
        "type": "header",
        "description": "Hover Peek Settings"
    },
    "seperator3": {
        "type": "separator"
    },
    "enable-hover-peek": {
        "type": "checkbox",
        "default": false,
        "description": "Show windows when hovered over",
        "tooltip": "Controls whether or not windows display when hovered over.",
        "value": false
    },
    "hover-peek-time": {
        "type": "spinbutton",
        "default": 150,
        "min": 0,
        "max": 1000,
        "step": 5,
        "units": "milliseconds",
        "description": "Window fade time",
        "tooltip": "Controls how quickly a window will fade on hover.",
        "value": 150
    },
    "hover-peek-opacity": {
        "type": "spinbutton",
        "default": 10,
        "min": 0,
        "max": 100,
        "step": 2,
        "units": "percent",
        "description": "Window opacity",
        "tooltip": "Opacity of the windows on hover.",
        "value": 10
    },
    "ThemeSettings": {
        "type": "header",
        "description": "Theme Settings"
    },
    "seperator2": {
        "type": "separator"
    },
    "show-active": {
        "type": "checkbox",
        "default": false,
        "description": "Show active app indicators",
        "tooltip": "Active app styling will indicate if an app is active.",
        "value": false
    },
    "icon-spacing": {
        "type": "spinbutton",
        "default": 7,
        "min": 0,
        "max": 15,
        "step": 1,
        "units": "px",
        "description": "Icon spacing",
        "tooltip": "Controls how much space is between the icons.",
        "value": 7
    },
    "icon-padding": {
        "type": "spinbutton",
        "default": 0,
        "min": 0,
        "max": 15,
        "step": 1,
        "units": "px",
        "description": "Icon padding",
        "tooltip": "Controls how much horizontal padding is inside the app buttons. Padding is only applied to instances of this applet on horizontal panels.",
        "value": 0
    },
    "themePadding": {
        "type": "checkbox",
        "default": true,
        "description": "Use theme padding to center button icons",
        "tooltip": "If button icons look off-centered, toggling this may help.",
        "value": true
    },
    "enable-iconSize": {
        "type": "checkbox",
        "default": false,
        "description": "Adjust icon size",
        "tooltip": "Adjust icon size independent of Cinnamon's panel scaling.",
        "value": false
    },
    "icon-size": {
        "type": "spinbutton",
        "default": 20,
        "min": 0,
        "max": 150,
        "step": 1,
        "units": "px",
        "description": "Icon size",
        "tooltip": "Set icon size",
        "value": 20
    },
    "hoverPseudoClass": {
        "type": "combobox",
        "default": 1,
        "description": "App button hover pseudo class",
        "options": {
            "hover": 1,
            "focus": 2,
            "active": 3,
            "outlined": 4,
            "selected": 5
        },
        "tooltip": "Overrides the pseudo class for app buttons on hover.",
        "value": 1
    },
    "focusPseudoClass": {
        "type": "combobox",
        "default": 2,
        "description": "App button focus pseudo class",
        "options": {
            "hover": 1,
            "focus": 2,
            "active": 3,
            "outlined": 4,
            "selected": 5
        },
        "tooltip": "Overrides the pseudo class for app button on focus.",
        "value": 2
    },
    "activePseudoClass": {
        "type": "combobox",
        "default": 3,
        "description": "App button active pseudo class",
        "options": {
            "hover": 1,
            "focus": 2,
            "active": 3,
            "outlined": 4,
            "selected": 5
        },
        "tooltip": "Overrides the pseudo class for app buttons when they are active.",
        "value": 3
    },
    "panelLauncherClass": {
        "type": "checkbox",
        "default": false,
        "description": "Use the panel launcher class for pinned apps",
        "tooltip": "Enabling this helps with certain themes.",
        "value": false
    },
    "close-button-style": {
        "type": "checkbox",
        "default": false,
        "description": "Allow themes to control the thumbnail close button",
        "tooltip": "Controls whether or not the theme controls the window thumbnail's close button.",
        "value": false
    },
    "useSystemTooltips": {
        "type": "checkbox",
        "default": false,
        "description": "Use system tooltips for closed apps",
        "tooltip": "Controls whether or not system tooltips are in use when hovering over closed pinned apps.",
        "value": false
    },
    "__md5__": "845df413bb99ccbbf4c1f0b434c99b80"
}

**Comment by jaszhix** [comment]
Pastebin please.

**Comment by tcmger** [comment]
~/.cinnamon/configs/IcingTaskManager@json/133.json:

{
    "ITM": {
        "type": "header",
        "description": "ITM Settings"
    },
    "seperator0": {
        "type": "separator"
    },
    "autoUpdate": {
        "type": "checkbox",
        "default": false,
        "description": "Update this applet automatically",
        "tooltip": "When enabled, ITM will check the Github releases on init, and will start to upgrade if it finds a newer version.",
        "value": false
    },
    "WindowList": {
        "type": "header",
        "description": "Window List Settings"
    },
    "seperator1": {
        "type": "separator"
    },
    "number-display": {
        "type": "combobox",
        "default": 1,
        "description": "Number display",
        "options": {
            "Smart": 1,
            "Normal": 2,
            "None": 3,
            "All": 4
        },
        "tooltip": "normal: display window number, smart: display window number if more than one window, none: don't display number, all: display window number for favorites too",
        "value": 3
    },
    "title-display": {
        "type": "combobox",
        "default": 1,
        "description": "Title display",
        "options": {
            "None": 1,
            "App": 2,
            "Title": 3,
            "Focused": 4
        },
        "tooltip": "focused: show focused window title, title: display the window title, app: diplay app name, none: don't display anything",
        "value": 3
    },
    "pinned-apps": {
        "type": "generic",
        "default": [],
        "value": []
    },
    "group-apps": {
        "type": "checkbox",
        "default": true,
        "description": "Group apps",
        "tooltip": "Group each app's set of windows.",
        "value": true
    },
    "show-alerts": {
        "type": "checkbox",
        "default": true,
        "description": "Show app alerts and notifications",
        "tooltip": "If enabled, notifications and alerts will appear.",
        "value": true
    },
    "show-pinned": {
        "type": "checkbox",
        "default": true,
        "description": "Show pinned apps",
        "tooltip": "Controls whether or not the pinned apps appear in the panel if they are not open.",
        "value": true
    },
    "arrange-pinnedApps": {
        "type": "checkbox",
        "default": true,
        "description": "Arrange pinned apps",
        "tooltip": "Arrange pinned apps into a different order.",
        "value": true
    },
    "middle-click-action": {
        "type": "checkbox",
        "default": true,
        "description": "Middle clicking app buttons creates new app instances",
        "tooltip": "Determines the behavior of middle mouse button clicks on app buttons. Setting this to false will close the last focused window from the app group on middle click.",
        "value": true
    },
    "cycleMenusHotkey": {
        "type": "keybinding",
        "default": "<Super>space",
        "description": "Global hotkey for cycling through thumbnail menus",
        "tooltip": "This allows you to cycle through the menus without activating a window.",
        "value": "<Super>space"
    },
    "show-apps-order-hotkey": {
        "type": "keybinding",
        "default": "<Super>grave",
        "description": "Global hotkey to show the order of apps",
        "tooltip": "When triggered, the window count label will be replaced with its order in the app list temporarily.",
        "value": "<Super>grave"
    },
    "show-apps-order-timeout": {
        "type": "spinbutton",
        "default": 2500,
        "min": 100,
        "max": 10000,
        "step": 10,
        "units": "milliseconds",
        "description": "Duration of the apps order display on hotkey press",
        "tooltip": "Determines the duration the window count labels are replaced with the app's order number.",
        "value": 2490.0
    },
    "Thumbnails": {
        "type": "header",
        "description": "Thumbnail Settings"
    },
    "seperator4": {
        "type": "separator"
    },
    "thumbnail-timeout": {
        "type": "spinbutton",
        "default": 50,
        "min": 0,
        "max": 5000,
        "step": 5,
        "units": "milliseconds",
        "description": "Thumbnail timeout",
        "tooltip": "Controls how quickly an app's set of window thumbnails will fade out when the mouse leaves the app button.",
        "value": 50
    },
    "thumbnail-size": {
        "type": "spinbutton",
        "default": 6,
        "min": 0,
        "max": 100,
        "step": 1,
        "units": "size",
        "description": "Thumbnail size",
        "tooltip": "Controls the size of the thumbnails.",
        "value": 48.0
    },
    "show-thumbnails": {
        "type": "checkbox",
        "default": true,
        "description": "Show thumbnails",
        "tooltip": "Show window thumbnails when hovering over an app button.",
        "value": true
    },
    "animate-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Animate thumbnails",
        "tooltip": "If enabled, thumbnails will animate when appearing and disappearing.",
        "value": false
    },
    "vertical-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Enable vertical thumbnails",
        "tooltip": "If enabled, thumbnails will stack vertically.",
        "value": true
    },
    "sort-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Sort windows for each app by last focused",
        "tooltip": "Controls whether the order windows appear for an app is by last focused, or the order they were opened.",
        "value": false
    },
    "onclick-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Open thumbnails on click",
        "tooltip": "Open the thumbnails on click if there is more than one window open.",
        "value": false
    },
    "include-all-windows": {
        "type": "checkbox",
        "default": false,
        "description": "Include all app windows",
        "tooltip": "Controls whether or not thumbnails for smalller child windows, such as exit confirmations and file dialogues will be included in the thumbnail list.",
        "value": true
    },
    "AppMenu": {
        "type": "header",
        "description": "Context Menu Settings"
    },
    "seperator5": {
        "type": "separator"
    },
    "show-recent": {
        "type": "checkbox",
        "default": true,
        "description": "Show recent items",
        "tooltip": "Controls whether recent items will appear in the context menu.",
        "value": true
    },
    "menuItemType": {
        "type": "combobox",
        "default": 1,
        "description": "Menu item type",
        "options": {
            "Symbolic icons": 1,
            "Non-symbolic icons": 2,
            "No icons": 3
        },
        "tooltip": "Determines whether menu item icons are symbolic, non-symbolic, or not shown.",
        "value": 1
    },
    "firefox-menu": {
        "type": "combobox",
        "default": 1,
        "description": "Firefox context menu",
        "options": {
            "Most Visited": 1,
            "Recent History": 2,
            "Bookmarks": 3
        },
        "tooltip": "Most Visited: show the sites you visit most, Recent History: display the the last pages you visited, Bookmarks: show your favorite bookmarks.",
        "value": 3
    },
    "autostart-menu-item": {
        "type": "checkbox",
        "default": true,
        "description": "Show autostart option",
        "tooltip": "Shows the autostart toggle option in an app's context menu.",
        "value": false
    },
    "monitor-move-all-windows": {
        "type": "checkbox",
        "default": true,
        "description": "Apply the monitor move option to all windows",
        "tooltip": "When clicking \"Move to monitor\" in the context menu, this option will move all of an app's windows instead of just the last focused window from the app.",
        "value": true
    },
    "HoverPeek": {
        "type": "header",
        "description": "Hover Peek Settings"
    },
    "seperator3": {
        "type": "separator"
    },
    "enable-hover-peek": {
        "type": "checkbox",
        "default": false,
        "description": "Show windows when hovered over",
        "tooltip": "Controls whether or not windows display when hovered over.",
        "value": false
    },
    "hover-peek-time": {
        "type": "spinbutton",
        "default": 150,
        "min": 0,
        "max": 1000,
        "step": 5,
        "units": "milliseconds",
        "description": "Window fade time",
        "tooltip": "Controls how quickly a window will fade on hover.",
        "value": 150
    },
    "hover-peek-opacity": {
        "type": "spinbutton",
        "default": 10,
        "min": 0,
        "max": 100,
        "step": 2,
        "units": "percent",
        "description": "Window opacity",
        "tooltip": "Opacity of the windows on hover.",
        "value": 10
    },
    "ThemeSettings": {
        "type": "header",
        "description": "Theme Settings"
    },
    "seperator2": {
        "type": "separator"
    },
    "show-active": {
        "type": "checkbox",
        "default": false,
        "description": "Show active app indicators",
        "tooltip": "Active app styling will indicate if an app is active.",
        "value": false
    },
    "icon-spacing": {
        "type": "spinbutton",
        "default": 7,
        "min": 0,
        "max": 15,
        "step": 1,
        "units": "px",
        "description": "Icon spacing",
        "tooltip": "Controls how much space is between the icons.",
        "value": 7
    },
    "icon-padding": {
        "type": "spinbutton",
        "default": 0,
        "min": 0,
        "max": 15,
        "step": 1,
        "units": "px",
        "description": "Icon padding",
        "tooltip": "Controls how much horizontal padding is inside the app buttons. Padding is only applied to instances of this applet on horizontal panels.",
        "value": 0
    },
    "themePadding": {
        "type": "checkbox",
        "default": true,
        "description": "Use theme padding to center button icons",
        "tooltip": "If button icons look off-centered, toggling this may help.",
        "value": true
    },
    "enable-iconSize": {
        "type": "checkbox",
        "default": false,
        "description": "Adjust icon size",
        "tooltip": "Adjust icon size independent of Cinnamon's panel scaling.",
        "value": false
    },
    "icon-size": {
        "type": "spinbutton",
        "default": 20,
        "min": 0,
        "max": 150,
        "step": 1,
        "units": "px",
        "description": "Icon size",
        "tooltip": "Set icon size",
        "value": 20
    },
    "hoverPseudoClass": {
        "type": "combobox",
        "default": 1,
        "description": "App button hover pseudo class",
        "options": {
            "hover": 1,
            "focus": 2,
            "active": 3,
            "outlined": 4,
            "selected": 5
        },
        "tooltip": "Overrides the pseudo class for app buttons on hover.",
        "value": 1
    },
    "focusPseudoClass": {
        "type": "combobox",
        "default": 2,
        "description": "App button focus pseudo class",
        "options": {
            "hover": 1,
            "focus": 2,
            "active": 3,
            "outlined": 4,
            "selected": 5
        },
        "tooltip": "Overrides the pseudo class for app button on focus.",
        "value": 2
    },
    "activePseudoClass": {
        "type": "combobox",
        "default": 3,
        "description": "App button active pseudo class",
        "options": {
            "hover": 1,
            "focus": 2,
            "active": 3,
            "outlined": 4,
            "selected": 5
        },
        "tooltip": "Overrides the pseudo class for app buttons when they are active.",
        "value": 3
    },
    "panelLauncherClass": {
        "type": "checkbox",
        "default": false,
        "description": "Use the panel launcher class for pinned apps",
        "tooltip": "Enabling this helps with certain themes.",
        "value": false
    },
    "close-button-style": {
        "type": "checkbox",
        "default": false,
        "description": "Allow themes to control the thumbnail close button",
        "tooltip": "Controls whether or not the theme controls the window thumbnail's close button.",
        "value": false
    },
    "useSystemTooltips": {
        "type": "checkbox",
        "default": false,
        "description": "Use system tooltips for closed apps",
        "tooltip": "Controls whether or not system tooltips are in use when hovering over closed pinned apps.",
        "value": false
    },
    "__md5__": "845df413bb99ccbbf4c1f0b434c99b80"
}

**Comment by jaszhix** [comment]
That's the applet configuration again. I just need you to [pastebin](http://pastebin.com/) your log files of the session this bug occured. Paste the link here so people don't have to scroll through miles of page to see the discussion.

**Comment by tcmger** [comment]
~/.xsession-errors

initctl: Verbindung zu Upstart nicht möglich: Failed to connect to socket /com/ubuntu/upstart: Verbindungsaufbau abgelehnt
syndaemon: Kein Prozess gefunden
/etc/mdm/Xsession: Beginning session setup...
localuser:xyz being added to access control list
** Message: couldn't access control socket: /run/user/1000/keyring/control: Datei oder Verzeichnis nicht gefunden
** Message: couldn't access control socket: /run/user/1000/keyring/control: Datei oder Verzeichnis nicht gefunden
** Message: couldn't access control socket: /run/user/1000/keyring/control: Datei oder Verzeichnis nicht gefunden
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
=== xinerama setup Configuration ===
  Clone: false
  Output: (null) attached to DVI-I-1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: Samsung Electric Company 19" attached to VGA-1
     status: on
     width: 1440
     height: 900
     rate: 60
     primary: false
     position: 0 0
=== Applying Configuration Configuration ===
  Clone: false
  Output: (null) attached to DVI-I-1
     status: off
     width: -1
     height: -1
     rate: -1
     primary: false
     position: -1 -1
  Output: Samsung Electric Company 19" attached to VGA-1
     status: on
     width: 1440
     height: 900
     rate: 60
     primary: true
     position: 0 0
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Wed Mar 15 2017 11:54:34 GMT+0100 (CET)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
openGL version 3.3 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
failed to create drawable
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active

(claws-mail:1575): Gdk-CRITICAL **: IA__gdk_window_thaw_toplevel_updates_libgtk_only: assertion 'private->update_and_descendants_freeze_count > 0' failed

(blueman-applet:1576): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(catfish:1826): Gtk-WARNING **: /build/gtk+3.0-PCLr8A/gtk+3.0-3.18.9/./gtk/gtkwidget.c:8456: widget not within a GtkWindow

** (catfish:1826): CRITICAL **: atk_object_set_description: assertion 'ATK_IS_OBJECT (accessible)' failed

(catfish:1955): Gtk-WARNING **: /build/gtk+3.0-PCLr8A/gtk+3.0-3.18.9/./gtk/gtkwidget.c:8456: widget not within a GtkWindow

** (catfish:1955): CRITICAL **: atk_object_set_description: assertion 'ATK_IS_OBJECT (accessible)' failed

(cinnamon-settings-daemon:1450): color-plugin-WARNING **: failed to connect to device: Failed to connect to missing device /org/freedesktop/ColorManager/devices/cups_MFC5890CN

(cinnamon-settings-daemon:1450): color-plugin-WARNING **: failed to connect to device: Failed to connect to missing device /org/freedesktop/ColorManager/devices/cups_PDF

(cinnamon-settings-daemon:1450): color-plugin-WARNING **: failed to connect to device: Failed to connect to missing device /org/freedesktop/ColorManager/devices/cups_Roger_Router_Fax
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1800003 (Legitimier)
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x55d5cd04c7d0  Text: 0

** (claws-mail:1575): WARNING **: [12:04:35] IMAP Fehler auf imap.1und1.de: STATUS-Fehler

**Comment by tcmger** [comment]
steps to reproduce:
nothing but open Firefox 52.0 (64-Bit)

**Comment by jaszhix** [comment]
The context menu is working for me under those settings.

![screenshot from 2017-03-15 06-24-55](https://cloud.githubusercontent.com/assets/6859057/23946446/6e4cdcc4-0948-11e7-848e-0b8443f52c86.png)
![screenshot from 2017-03-15 06-25-04](https://cloud.githubusercontent.com/assets/6859057/23946447/6e4db590-0948-11e7-998b-b467ed67b213.png)

**Comment by tcmger** [comment]
The context menu is working, but it is empty 
![bildschirmfoto vom 2017-03-15 12-32-03](https://cloud.githubusercontent.com/assets/26368647/23946770/0f10659e-097c-11e7-9b52-ad4cae0a6e38.png)

If I mark "Lesezeichen"= "bookmarks", nothing is shown
![bildschirmfoto vom 2017-03-15 12-35-08](https://cloud.githubusercontent.com/assets/26368647/23946796/33f46162-097c-11e7-98f6-b401f5954c11.png)

**Comment by tcmger** [comment]
excuse me, it is my "first time"

how to use pastebin ?

I pasted the text, log file, created a "new paste" and nothing else ?
no address where to send it ?

i do not know anything about the concept of pastebin



Am 15.03.2017 um 11:50 schrieb Jason Hicks:

**Comment by jaszhix** [comment]
```sudo apt install gir1.2-gda-5.0```

Please close.

**Comment by NikoKrause** [comment]
@tcmger 
If the code is very long, you don't copy&paste it directly here, but on pastebin.com.
Then press "create new paste" and write the link/url you get here.

@jaszhix 
Can it be that this is the same problem as in Cinnamenu and you need to install `gir1.2-gda-5.0` to see the booksmarks?

**Comment by NikoKrause** [comment]
Oh I was to slow.

**Comment by tcmger** [comment]
The context menu is working, but it is empty 
![bildschirmfoto vom 2017-03-15 12-32-03](https://cloud.githubusercontent.com/assets/26368647/23946770/0f10659e-097c-11e7-9b52-ad4cae0a6e38.png)

If I mark "Lesezeichen"= "bookmarks", nothing is shown

**Comment by tcmger** [comment]
yes, $ sudo apt install gir1.2-gda-5.0 was the solution, thank you very much for the usefull and fine application.

**Comment by tcmger** [comment]
Am 15.03.2017 um 12:55 schrieb NikoKrause:
>
> @tcmger <https://github.com/tcmger>
> If the code is very long, you don't copy&paste it directly here, but 
> on pastebin.com.
> Then press "create new paste" and write the link/url you get here.
>
excuse me, but where exactly do I write the link/url in pastebin
and which link/url do you mean ?

the link of github page ? 
(https://github.com/linuxmint/cinnamon-spices-applets/issues/214)

**Comment by jaszhix** [comment]
Copy the URL in the address bar in your browser from pastebin.com after you click Create New Paste, and paste it in your comment on Github.

**Comment by tcmger** [comment]
ok thank you

Am 15.03.2017 um 13:24 schrieb Jason Hicks:
