### ISSUE TITLE
 IcingTaskManager@json: VirtualBox icons persist in other workspaces after closing the window

### ISSUE THREAD

**Issue by MasterGeekMX** [linuxmint/cinnamon-spices-applets#2121]
* Applet version/Build date 6.3.13
 * Cinnamon version 4.0.2
 * Distribution - Fedora 29
 * Graphics hardware *and* driver used: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09) (Intel© Core™ i5-2450M)
 * Snippet or attachment of ~/.xsession-errors
```[mgmx@ThinkPad ~]$ tail .xsession-errors
(cinnamon:12511): St-WARNING **: 10:36:25.801: Did not find double property 'opacity'
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cjs-Message: 10:36:30.248: JS LOG: [LookingGlass/warning] [Applet/IcingTaskManager@json] Use of scaleMode is deprecated.
Cjs-Message: 10:36:30.267: JS LOG: [LookingGlass/warning] [Applet/IcingTaskManager@json] Use of scaleMode is deprecated.
Cjs-Message: 10:36:30.281: JS LOG: [LookingGlass/warning] [Applet/IcingTaskManager@json] Use of scaleMode is deprecated.
Cjs-Message: 10:36:30.295: JS LOG: [LookingGlass/warning] [Applet/IcingTaskManager@json] Use of scaleMode is deprecated.
Cjs-Message: 10:36:58.505: JS LOG: [LookingGlass/warning] [Applet/IcingTaskManager@json] Use of scaleMode is deprecated.
Cjs-Message: 10:36:58.524: JS LOG: [LookingGlass/warning] [Applet/IcingTaskManager@json] Use of scaleMode is deprecated.
Cjs-Message: 10:36:58.539: JS LOG: [LookingGlass/warning] [Applet/IcingTaskManager@json] Use of scaleMode is deprecated.
Cjs-Message: 10:36:58.553: JS LOG: [LookingGlass/warning] [Applet/IcingTaskManager@json] Use of scaleMode is deprecated.
```
---

**Notify author of applet**
@jaszhix

**Issue**

If the option "show windows from other workspaces"  is enabled, after closing a window of certian apps (specially VirtualBox VMs), the icon of that window is still visible when switching to another workspaces, and the conextual menu for managing that menu appears on right click

**Steps to reproduce**

 - Enable "show windows from other workspaces" option
 - Open Window of conflicting app
 - Close window of conflicting app. The icon dissapears on the workspace in which the winow was present
 - Switch to another workspace

**Expected behaviour**

Closing the window should make the icon dissaper from all workspaces

**Other information**

Reloading Cinnamon or enabling/disabling the "show windows from other workspaces" deletes the persistent icons. Right clicking a persistent icon, selecting "move to another workspace" and then selecting a workspace crashes Cinnamon

![1](https://user-images.githubusercontent.com/10291989/49238620-62b67900-f3c6-11e8-9988-a5fd8572e246.png)

*window is open, icon is present. Normal behavior. Note thet we are in workspace 2 (bottom left)*

![2](https://user-images.githubusercontent.com/10291989/49238621-62b67900-f3c6-11e8-97f2-3bc8f573e2bd.png)

*Window is closed, icon not present. We switched to workspace 3. Icon is presnet*

![3](https://user-images.githubusercontent.com/10291989/49238624-634f0f80-f3c6-11e8-8ffc-f3e82eab6f78.png)

*context menu appears, even if the widow isn't there. Selecting workspace operations crash Cinnamon*

**Comment by jaszhix** [comment]
Hi, Icing Task Manager is deprecated now because it was forked as Grouped window list in Cinnamon 4.0. I recommend migrating to GWL.

Not able to reproduce the Cinnamon crash, though we probably don't need to show the workspace switching options when showing all windows.

**Comment by MasterGeekMX** [comment]
@jaszhix Already switched to GWL, but the same problemm affects it. Oppening an issue.
