### ISSUE TITLE
multicore-sys-monitor@ccadeptic23 is broken in linux mint 17.3

### ISSUE THREAD

**Issue by Cediddi** [linuxmint/cinnamon-spices-applets#2122]
```
 * Applet version/Build date: 1.8.7
 * Cinnamon version: 2.8.8
 * Distribution: Linux Mint 17.3
 * Graphics hardware: Onboard Intel with default drivers (nvidia is blacklisted)
 * Snippet or attachment of ~/.cinnamon/glass.log: 
    info t=2018-11-30T11:38:03.837Z Error getting Cinnamon backlight power settings true,,Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown:
    error t=2018-11-30T11:38:05.770Z [Applet "multicore-sys-monitor@ccadeptic23"]: File not found: /home/cediddi/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/applet.js
    error t=2018-11-30T11:38:05.770Z Could not load applet multicore-sys-monitor@ccadeptic23

 * Snippet or attachment of ~/.xsession-errors
    Nothing important really.

 ```

**Notify author of applet**

@jaszhix

**Issue**
It doesn't work at all. It used to work, cinnamon applets said that I should update some plugins and I did and now the applet doesn't work. metadata.json says latest version 1.8.7 supports cinnamon 2.8 but seems like it isn't.

**Steps to reproduce**
Travel in time to mid 2017
Install Linux mint 17.3
Install this plugin
Travel in time to today
Update this plugin
Unexpectedly plugin stops working.

**Expected behaviour**
Either cinnamon applets shouldn't prompt me to update this plugin, or plugin should've dropped the 2.8 support altogether.

**Other information**
Because of the design of cinnamon extensions, I can't revert back to an old version of the applet, neither I can find which commit the previous release was nor in which version of the applet 2.8 support was dropped.

I can understand you want to stop supporting 4.5 years old systems but because of my job, I can't update my system to a newer mint/ubuntu release. We're stuck on 14.04 for good :(

**Comment by jaszhix** [comment]
Sorry, I have no plans to back-port this to 17.3, that version will be going end-of-life in April and I suggest you upgrade.
