### ISSUE TITLE
temperature@fevimu is broken in linux mint 17.3

### ISSUE THREAD

**Issue by Cediddi** [linuxmint/cinnamon-spices-applets#2123]
```
 * Applet version/Build date: I don't know, "last-edited": 1543256024 maybe?
 * Cinnamon version: 2.8.8
 * Distribution: Linux Mint 17.3
 * Graphics hardware: Onboard Intel with default drivers (nvidia is blacklisted)
 * Snippet or attachment of ~/.cinnamon/glass.log: 
    error t=2018-11-30T11:16:49.338Z [Applet "temperature@fevimu"]: Extension is not compatible with current Cinnamon version
    error t=2018-11-30T11:16:49.338Z Could not load applet temperature@fevimu

 * Snippet or attachment of ~/.xsession-errors
    Nothing important really.

 ```

**Notify author of applet**

@jaszhix

**Issue**
It doesn't work at all. It used to work, cinnamon applets said that I should update some plugins and I did and now the applet doesn't work. This time metadata.json says this applet doesn't support cinnamon 2.8 but still cinnamon applets prompted me to update. I can't activate the plugin anymore and I can't roll back.

**Steps to reproduce**
Travel in time to mid 2017
Install Linux mint 17.3
Install this plugin
Travel in time to today
Update this plugin
Unexpectedly plugin stops working.

**Expected behaviour**
Either cinnamon applets shouldn't prompt me to update this plugin.

**Other information**
Because of the design of cinnamon extensions, I can't revert back to an old version of the applet, neither I can find which commit the previous release was nor in which version of the applet 2.8 support was dropped.

I can understand you want to stop supporting 4.5 years old systems but because of my job, I can't update my system to a newer mint/ubuntu release. We're stuck on 14.04 for good :( 

PS: Sorry for bothering you twice but I didn't wanted to merge these two issues.

**Comment by jaszhix** [comment]
Sorry, I have no plans to back-port this to 17.3, that version will be going end-of-life in April and I suggest you upgrade.

**Comment by Cediddi** [comment]
I'd love to upgrade but I cannot. Company policies. On the other hand if you can point me to a commit which still supports 17.3 I'll be very very happy. Same goes for my other issue #2122

At home I use mint 19 and I have no problems there.

**Comment by jaszhix** [comment]
For this applet in particular, it had a memory leak, so I would actually suggest you not use it at all on 17.3 even if you could find the old version.

At a minimum you should supply logs (check the issue template). If it's a simple js error, that's fixable easily, but if it's a missing API that requires refactoring I'd rather not do it.

**Comment by smurphos** [comment]
See here for a method of obtaining old versions of applets from the repo https://forums.linuxmint.com/viewtopic.php?p=1443345#p1443345

**Comment by Cediddi** [comment]
@jaszhix I updated the main comment with logs but I couldn't find anything about this applet there. And there's nothing in my applet area.

@smurphos thanks, I'll try that.

**Comment by Cediddi** [comment]
I have reverted to 7aa40ef for this plugin and it worked.
I also reverted to a10b044 fır multicore-sys-monitor and it also worked, albeit a cinnamon --replace was required.
