### ISSUE TITLE
No Context menu in Firefox 52.0 (64-Bit), Cinnamon 3.2.7, Icing Task Manager 4.4.0, Linux MInt 18.1. Serena

### ISSUE THREAD

**Issue by tcmger** [linuxmint/cinnamon-spices-applets#213]
@tcmger
[Issue]: <> Cinnamon 3.2.7
Icing Task Manager 4.4.0
Linux MInt 18.1. Serena
Firefox 52.0 (64-Bit)

Context menu ITM empty on each option

**Comment by NikoKrause** [comment]
You don't need to open a new issue.
You can edit the old one.

**Comment by NikoKrause** [comment]
You get all the needed info, who AppletAuthor and how the UUID is, on the Spices Website.

**Comment by tcmger** [comment]
Am 15.03.2017 um 10:16 schrieb NikoKrause:
>
> You get all the needed info, who AppletAuthor and how the UUID is, on 
> the Spices Website.
>
> —
>
what exactly do you mean with "UUID" and " Spices Website"? I did not 
read anything about that in the guidelines.

**Comment by NikoKrause** [comment]
> It's important to use a proper title when opening new issues. The title must be in the format spice name: simple description of the problem.

You tagged yourself @tcmger. You are obviously not the author of the applet. So to find out who this is you can read the spices website of this applet. https://cinnamon-spices.linuxmint.com/applets/view/269
It's said in the title.

The UUID is also there. You can use the UUID or the spices name. But you have to use it properly in the title, like it's said in the guidelines or like it looks on the other open issues.

**Comment by tcmger** [comment]
thank you i think i have got it.

Am 15.03.2017 um 10:57 schrieb NikoKrause:
