### ISSUE TITLE
Respect locale settings datetime in weather@mockturtl

### ISSUE THREAD

**Issue by glasolin** [linuxmint/cinnamon-spices-applets#2138]
@mockturtl 

Currently applet displays sunraise/susnset, day of week in US locale. Should use user locale for these values.

**Comment by claudiux** [comment]
Which applet are you talking about, please?

**Comment by mockturtl** [comment]
Thanks for the report!  (Please edit the title to include `weather@mockturtl`, per [CONTRIBUTING.md](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/CONTRIBUTING.md))

Can you describe the sunrise/sunset formatting you'd like to see?

**Comment by glasolin** [comment]
> Can you describe the sunrise/sunset formatting you'd like to see?

Probably like date command does this:
`date +"%X"`

> locale’s time representation (e.g., 23:13:48)

same with DOW

**Comment by glasolin** [comment]
May be this helps: https://stackoverflow.com/questions/2507726/how-to-display-locale-sensitive-time-format-without-seconds-in-python

**Comment by Gr3q** [comment]
@glasolin Locale is used to display time above cinnamon version 3.6, it is not possible to do this below.

Please close the issue unless you are still not satisfied how it behaves. Thank you.
