### ISSUE TITLE
IcingTaskManager@json: Libreoffice base no preview of forms and tables

### ISSUE THREAD

**Issue by tcmger** [linuxmint/cinnamon-spices-applets#214]
@jaszhix
Cinnamon 3.2.7
Icing Task Manager 4.4.0
Linux MInt 18.1. Serena
Libreoffice Version: 5.2.3.3 64bit (installed directly from libreoffice web site with deb

Forms or tables in database (base) container windows are not
shown as preview. Only the container window is shown.

To see further windows of the container as preview,you must go to preferences of ITM, change an option, e.G. view "title" to "application", close preferences, then further windows will be shown.

Timing problem ?

**Comment by tcmger** [comment]
hereby simple example 
1) "test.odb" is opened form "Aufgaben" is opened and maximized.
But "Aufagben" is not shown in preview
![bildschirmfoto vom 2017-03-15 11-15-26](https://cloud.githubusercontent.com/assets/26368647/23943753/cce7d3f6-0970-11e7-8433-cd719cfd87e6.png)
2) preferences of ITM was changed from "show title" to show application, then rechanged to "show title". Result:
![bildschirmfoto vom 2017-03-15 11-20-30](https://cloud.githubusercontent.com/assets/26368647/23943963/7739b068-0971-11e7-8cec-12bf5a682f62.png)

**Comment by jaszhix** [comment]
I don't think its a timing issue. LibreOffice will continue to be seen as ```libreoffice-base``` whenever you launch apps from the start center, and the apps are seen by Cinnamon properly when launched individually. I'm not sure what I can do about it, ITM has no way of knowing what apps are being launched from LibreOffice Base.

**Comment by jaszhix** [comment]
When you launch LibreOffice from the start center Cinnamon will sometimes incorrectly identify the app ID. Since the recent fix I haven't had any issues except the wrong app showing under the app buttons when launching two different LO apps. 

The default window list is using a different signal than I am for the window events, so that's possibly something that can be looked into, but in the end I'm getting application info through the same APIs. You may want to double check your version of ITM, the version listed on the website may not necessarily be what you have unless you upgrade in the applet settings.

Please see the other LibreOffice [issues](https://github.com/jaszhix/icingtaskmanager/issues?utf8=%E2%9C%93&q=is%3Aissue%20libreoffice) on my repo.

**Comment by tcmger** [comment]
I do not start LO files from the start center
I start with link,  e.G.

libreoffice5.2  ~/*/test.odb

If I start from the start center another strange behavior occurs:

Now I get 2 entries in the panel

1 entry with  database container only
1 correct entry with container and form

Am 15.03.2017 um 11:27 schrieb Jason Hicks:

**Comment by tcmger** [comment]
Am 15.03.2017 um 12:48 schrieb Jason Hicks:
>
> When you launch LibreOffice from the start center Cinnamon will 
> sometimes incorrectly identify the app ID. Since the recent fix I 
> haven't had any issues except the wrong app showing under the app 
> buttons when launching two different LO apps.
>
verifying the app ids with ps -aux | less gets always the same result. 
Perhaps it could be helpfull to consider, what happens within the ITM 
app, if preferences (title, app, focused, no) are changed.

In Libreoffice calc the behavior is little bit different. If i open 1. 
file, ok, opening the 2. file, results in showing 1 item with 1. file 
and another item combined with 1. file and second file.

Whenever I change the preferences, regardless of after having opened 1 
or 2 files, the previews will be correct.
E.g. I open File 1, then open file 2, I will get two main previews (File 
1 and File2+1)
I change preference
The preview if file 1 disappears and the result is correct.

> The default window list is using a different signal than I am for the 
> window events, so that's possibly something that can be looked into, 
> but in the end I'm getting application info through the same APIs. You 
> may want to double check your version of ITM, the version listed on 
> the website may not necessarily be what you have unless you upgrade in 
> the applet settings.
>
I downloaded and installed yesterday with the download button on 
https://cinnamon-spices.linuxmint.com/applets/view/269.
Files date is march, 7, 2017, I think that should be the latest version.

**Comment by tcmger** [comment]
/.cinnamon/configs/IcingTaskManager@json/*.json: 
http://pastebin.com/RyE2AQE5

~/.cinnamon/glass.log:
http://pastebin.com/5y26Ym19

~/.xsession-errors:
http://pastebin.com/hAUjvPtp

**Comment by tcmger** [comment]
Here another strange behavior: After having switched preferences in ITM sub windows are shown as declared, but in the wrong Libreoffice application (Sub window base is shown in calc)
![bildschirmfoto vom 2017-03-15 17-21-18](https://cloud.githubusercontent.com/assets/26368647/23959116/898217f0-09a4-11e7-991f-260c0612e57c.png)
![bildschirmfoto vom 2017-03-15 17-21-12](https://cloud.githubusercontent.com/assets/26368647/23959121/90478548-09a4-11e7-800a-9aeed02c1753.png)

Excuse if I am insisting on that issue. I am working with lot of libreoffice files and docs, different databases. Opening 5 or more documents at once can be very confusing in classic taskbar.
But grouping wrong is even worse. 
When I tested the former app "windows list with app grouping" I could "work around" that behavior by manually editing the libreoffice .desktop files and enter one single class name for all Libreoffice apps (base, calc etc.).
But at the end I dropped "windows list with app grouping" because of some other hard bugs.
Your app is wonderful, only I am LO Hard-Line-User, may be my problem is not really important for most of the other users.

So don't hesitate to tell me if it is not possible to solve the problem. Then I will close the issue.

**Comment by jaszhix** [comment]
Yes, it occurs when more than one LO app is open. I'm not sure how to work around it yet, and since ITM is getting bad results from the Cinnamon API, I will have to figure out a less easy way to handle it. I've been aware of this issue for a while, but I appreciate the additional info.

**Comment by tcmger** [comment]
I think I found a 1. small work around more by coincidence. In the file 
"/usr/share/applications/Libreoffice" I changed 
"StartupWMClass=libreoffice-startcenter" to "StartupWMClass=libreoffice".

Consequence is: 1) The ODB is correctly shown with window and sub window
                            2) All further LO docs (odb, ods, odt) are 
shown in one group
                            3) The name of the group is the name of the 
last opened window
After several restarts of cinnamon and also system, it seems to be stable.

For me personal this seems to be perfect.

But it is also a little bit "gamble solution". I am not really firm in 
Linux systems (2014 XP changer).
My thing is to do small productivity tools based on commercial and non 
commercial software.

So please decide yourself, if I should close the item.

Perhaps my trial can help you finding a professional solution. Anyway I 
would be glad to here if You
found it.

kind regards
Gert Hoffmann

Am 15.03.2017 um 19:57 schrieb Jason Hicks:

**Comment by tcmger** [comment]
I think, my solution is not so far from the truth. Here another 
interesting observation controlling the results

I. state of /usr/share/applicaions/libre*.desktop original
StartupWMClass=libreoffice-startcenter
StartupWMClass=libreoffice-base
StartupWMClass=libreoffice-calc
etc

I.a)graph1:
result of previews and looking-glass after opening  odb file only:
the 2 odb windows <untracked>, only one shown in preview

I.b) graph2:
result of previews and looking-glass after opening  odb file an then 2 
ods files
1 odb window <untracked>, 1 odb window (form) tracked to 
libreoffice5.2-calc.desktop(!)
all windows shown in preview but wrong alignment (logically)


To realise the following changes I had to restart the system



II. state of /usr/share/applicaions/libre*.desktop changed
changed: StartupWMClass=libreoffice
StartupWMClass=libreoffice-base
StartupWMClass=libreoffice-calc

II.a) graph3:
result of previews and looking-glass after opening  odb file only:
the 2 odb windows tracked to libreoffice5.2.desktop(correct), both shown 
in preview

II.b) graph4:
result of previews and looking-glass after opening  odb file an then 2 
ods files
all windows tracked to libreoffice5.2.desktop(correct), all shown in 1 
preview


Also from interest may be: the results of "xprop WM_CLASS"
allways will asign correctly "WM_CLASS(STRING) = "libreoffice", 
"libreoffice-odsorwhateverending"
in all windows and in any *.desktop configuration.

Further:
The preview alignment in the original configuration 
"StartupWMClass=libreoffice-startcenter" only takes place
at the moment, when a calc app is started together with odb. If I start 
e.G. with a writer document, then odb
all windows are <untracked>, nothing in preview. At the moment I open a 
calc app, all windows are tracked and appear
I tried several  alternative entries for StartupWMClass, but the only 
one with acceptable result was "libreoffice"

I will not comment those observations. But I hope, it can help You.


Am 15.03.2017 um 19:57 schrieb Jason Hicks:

**Comment by tcmger** [comment]
I can confirm the workaround for my system. The problem mantained after upgrading to LO 5.2.6.2.
Solution: 
1) Search libreoffice X.X.desktop and libreoffice-startcenter.desktop 
2) Open them and change " StartupWMClass=libreoffice-startcenter " to " StartupWMClass=libreoffice "
3) save and restart LO, problem solved
