### ISSUE TITLE
"xampp-panel@backids99" applet doesn't work because GKSUDO doesn't exists anymore

### ISSUE THREAD

**Issue by ThiagoNunesBatista** [linuxmint/cinnamon-spices-applets#2147]
* Applet version/Build date (to be found in "About.." or in "metadata.json")
xampp-panel@backids99 
Last modified2018-12-02 09:15 UTC
Version:0.1

 * Cinnamon version (4.0.5)
 * Distribution - (Mint 19.1(Beta))

**Notify author of applet**
@clefebvre 

**Issue**
I installed the "Xampp panel menu" applet in my system, when I active whatever funcionality of the applet I just receive a notification with a text like this "Execution of 'gksudo /opt/lampp/lampp start' failed: Failed to execute child progress "gksudo" (No such file or directory)". 
I think this is happening because the command "GKSUDO"was discontinued in Ubuntu 18.04.

**Other information**
I think the solution it's just to change the "GKSUDO" for another one that works.

**Comment by pyroxar** [comment]
I confirm this bug.
I did know about this before.
I did try to recreate the commands of original applet to use with pkexec but applet do not work correctly still. I am failed because my knowledge of developing applets for cinnamon desktop is not extensive enough.
Here are original commands:
```
//applet command constants
var CommandConstants = new function() {
    this.COMMAND_START_XAMPP = "gksudo /opt/lampp/lampp start";
    this.COMMAND_STOP_XAMPP = "gksudo /opt/lampp/lampp stop";
    this.COMMAND_RESTART_XAMPP = "gksudo /opt/lampp/lampp restart";
    this.COMMAND_PHP_CONFIG_EDIT = "gksudo xdg-open /opt/lampp/etc/php.ini";
    this.COMMAND_LAUNCH_PHPMYADMIN = "xdg-open http://localhost/phpmyadmin/";
    this.COMMAND_LAUNCH_WEBDIR = "xdg-open http://localhost/";
    this.COMMAND_OPEN_WEBDIR = "nemo /opt/lampp/htdocs/";
}
```
and here are 'my' commands:
```
//applet command constants
var CommandConstants = new function() {
    this.COMMAND_START_LINUX_MANAGER = "pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY /opt/lampp/manager-linux-x64.run";
    this.COMMAND_START_XAMPP = "pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY /opt/lampp/lampp start";
    this.COMMAND_STOP_XAMPP = "pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY /opt/lampp/lampp stop";
    this.COMMAND_RESTART_XAMPP = "pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY /opt/lampp/lampp restart";
    this.COMMAND_PHP_CONFIG_EDIT = "xed admin:///opt/lampp/etc/php.ini"; //It works!
    this.COMMAND_LAUNCH_PHPMYADMIN = "xdg-open http://localhost/phpmyadmin/";
    this.COMMAND_LAUNCH_WEBDIR = "xdg-open http://localhost/";
    this.COMMAND_OPEN_WEBDIR = "nemo /opt/lampp/htdocs/";
}
```
This applet of cinnamon do not have an error, pkexec just do not show dialog, which I can enter password. When I execute command in terminal, then dialog is display.
