### ISSUE TITLE
Freezes if you try to setup Custom Icon of the Quickstart Symbols

### ISSUE THREAD

**Issue by jessidevil** [linuxmint/cinnamon-spices-applets#2155]
CinnVIIStarkMenu@NikoKrause

```
 * Applet version/Build date 2018-12-07
 * Cinnamon version 1.17
 * Distribution - Mint 19.1
 * nVidia Driver 390.77 - GeForce GTX 1050 Ti
[glass.log](https://github.com/linuxmint/cinnamon-spices-applets/files/2700874/glass.log)

 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
I tried to setup new Quickstarters and it worked but not the New Symbol Option, if you click it, it freezes. 

[xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/2700892/xsession-errors.txt)

**Steps to reproduce**
Setup a new Quickstarter and try to  set a Symbol for it.

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
@NikoKrause

**Comment by rykiar** [comment]
I experienced exactly the same problem. When I try to choose new icon, it freezes. I am on mint 19.1

**Comment by NikoKrause** [comment]
Sorry for the late reply. Don't have much time lately.
I can reproduce this issue. This is not CinnVIIStarkMenu specific. It's the same issue with the settings-example@cinnamon.org applet, which means there's a bug with the Cinnamon API. I've pointed this out to the Cinnamon API expert.

**Comment by collinss** [comment]
Hi, this was fixed a few weeks ago, but unfortunately it didn't happen in time to make it into 19.1. You'll have to wait until 19.2 unless you want to build xapps from github.

https://github.com/linuxmint/xapps/commit/9291dd0216ed3b7cecf3154ad5eb7abafb208f39
