### ISSUE TITLE
IcingTaskManager@json: Multi Monitor Taskbar

### ISSUE THREAD

**Issue by SciLor** [linuxmint/cinnamon-spices-applets#2159]
```
 * Applet version/Build date 6.3.14
 * Cinnamon version 3.2.7
 * Distribution Debian 9
 * Nvidia 384.130

 ```

**Notify author of applet**
@jaszhix

**Issue**
If you are using multiple monitors with multiple panels (and multiple IcingTastManagers) all windows are replicated to all instances of the ICT.

**Expected behaviour**
As an option: Only show Windows in the IcingTastManagers of the monitor where the window is on.

**Comment by jaszhix** [comment]
https://github.com/jaszhix/icingtaskmanager/issues/236
