### ISSUE TITLE
tracker@glebihan 

### ISSUE THREAD

**Issue by gregorij93** [linuxmint/cinnamon-spices-applets#2161]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
The search results doesn't appear

**Steps to reproduce**

Install needed packages from your page.
After completing install add a aplet.

**Expected behaviour**

Search results will appear 😔

**Other information**

**Comment by icarter09** [comment]
@gregorij93 what version of Cinnamon and Linux Mint are you using?

**Comment by gregorij93** [comment]
Linux Mint 18.2 Cinnamon 64-bit 
Cinnamon ver 3.4.3

**Comment by icarter09** [comment]
@gregorij93 I'm not able to install the needed packages since tracker-gui was removed from Ubuntu 17.10. I'm using Linux Mint 19.1 64bit and Cinnamon 4.0.8

**Comment by icarter09** [comment]
@brownsr this ticket can be closed. Applet has been removed.
