### ISSUE TITLE
Cinnamenu@json: Menu editor is not adding custom entries

### ISSUE THREAD

**Issue by icarter09** [linuxmint/cinnamon-spices-applets#2162]
Applet version/Build date - 2018-11-22 22:23 UTC
Cinnamon version - 4.0.8
Distribution - Linux Mint 19.1
Notify author of applet
@jaszhix

Issue:
Custom menu entries are not appearing in the menu after being added.

Steps to reproduce:

1. Install applet
2. Right click on applet.
3. Select "Configure"
4. Click "Open the menu editor" under "Layout and Content"
5. Click "New Menu"
6. Add new entry.
7. New item appears in list, but does not appear in the Cinnamenu.

Expected behaviour
New item should appear in the Cinnamenu once added.

**Comment by smurphos** [comment]
This is normal behaviour and applies equally to the stock menu.  Categories (user added or not) are not visible in the menu unless they contain at least one visible menu-item.

**Comment by icarter09** [comment]
@smurphos Thanks for the explanation. I'll test this out again and verify it works correctly.

**Comment by jaszhix** [comment]
@smurphos is right, this is just how the menu editor works.
