### ISSUE TITLE
Cinnamenu@json: Unknown entry appearing in the list

### ISSUE THREAD

**Issue by icarter09** [linuxmint/cinnamon-spices-applets#2163]
Applet version/Build date - 2018-11-22 22:23 UTC
Cinnamon version - 4.0.8
Distribution - Linux Mint 19.1
Notify author of applet
@jaszhix

Issue:
When the Custom entry menu is opened, the value "wine-wine" appears. But this entry is not installed on my system or found in the Cinnamenu when searched for.

Steps to reproduce:

1. Install applet
2. Right click on applet.
3. Select "Configure"
4. Click "Open the menu editor" under "Layout and Content"
5. Value of "wine-wine" appears in the list.

Expected behaviour
This item should not be appearing on my system since I do not have WINE installed.

**Comment by smurphos** [comment]
The wine-wine category is set here as far as I know - https://github.com/linuxmint/Cinnamon/blob/master/files/etc/xdg/menus/cinnamon-applications.menu

It appears in the menu-editor irrespective of which menu you are using.

**Comment by icarter09** [comment]
@smurphos Do you think it should be hidden or removed from the Configure list? I don't think it should be too hard to not display it and leaving it there would only confuse a user.

**Comment by jaszhix** [comment]
The menu editor is not a part of Cinnamenu.
