### ISSUE TITLE
Cinnamenu@json: Custom menu entries are being held on to after uninstall

### ISSUE THREAD

**Issue by icarter09** [linuxmint/cinnamon-spices-applets#2164]
Applet version/Build date - 2018-11-22 22:23 UTC
Cinnamon version - 4.0.8
Distribution - Linux Mint 19.1
Notify author of applet
@jaszhix

Issue:
Custom menu entries was added to Cinnamenu. But after uninstalling Cinnamenu, the custom entries are still present.

Steps to reproduce:

1. Install applet
2. Right click on applet.
3. Select "Configure"
4. Click "Open the menu editor" under "Layout and Content"
5. Click "New Menu"
6. Add new entry.
7. Uninstall Cinnamenu.
8. Reinstall Cinnamenu.
9. Repeat steps above and see that the custom entries are still present in list.

Expected behaviour
Custom entries should not be held on to after a uninstall. I also manually deleted the Cinnamenu from the `.local/share/cinnamon/applets` folder, but the Cinnamenu still was showing the custom entries after a reinstall.

**Comment by smurphos** [comment]
The menu editor is a core part of Cinnamon. Cinnamenu only provides a shortcut to launch it. Making changes with it modifies the contents of ~/.local/share/applications and  ~/.config/menus which apply to all freedesktop compliant menus.

See https://github.com/linuxmint/Cinnamon/tree/master/files/etc/xdg/menus & https://github.com/linuxmint/Cinnamon/tree/master/files/usr/share/cinnamon/cinnamon-menu-editor

**Comment by icarter09** [comment]
@smurphos Thanks for the heads up. I'll test it out again with this in mind.

**Comment by jaszhix** [comment]
The menu editor is not a part of Cinnamenu.
