### ISSUE TITLE
vboxlauncher@mockturtl: VBox 6 --startvm change breaks VM startup

### ISSUE THREAD

**Issue by Centurix** [linuxmint/cinnamon-spices-applets#2168]
```
 * Version: 0.4.0
 * Cinnamon version: 4.0.8
 * Distribution: Mint 19.1
 ```

@mockturtl 

It appears VBox have overhauled their command line utilities and moved --startvm to a different command.

**Steps to reproduce**
* Replace v5 VirtualBox install with v6
* Attempt to start a VM from the launcher

Result: "--startvm is an option for the VirtualBox VM runner (VirtualBoxVM) application, not the VirtualBox Manager."

**Expected behaviour**
VM Should start

**Comment by mhosse** [comment]
Hi,

I faced the same issue. As a workaround you can patch ~/.local/share/cinnamon/applets/vboxlauncher@mockturtl/applet.js
with the attached file.
[applet.js.patch.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/2718553/applet.js.patch.txt)

After that you need to restart cinnamon.

**Comment by Centurix** [comment]
PR submitted with vbox major revision check and updated command for V6. Thanks @mhosse
