### ISSUE TITLE
[cinnamon-timer@jake1164] Does not work in Cinnamon 4.0

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#2169]
```
 * Applet version/Build date: 1.1.2
 * Cinnamon version: 4.0.8
 * Distribution: Mint 19.1
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log:
info t=2018-07-08T13:01:11.815Z Loaded applet cinnamon-timer@jake1164 in 22 ms
 * Snippet or attachment of ~/.xsession-errors
Cjs-Message: 18:17:24.236: JS LOG: [LookingGlass/info] Loaded applet cinnamon-timer@jake1164 in 0 ms
 ```

**Notify author of applet**
@jake1164 

**Issue**
Applet does not load on Cinnamon 4.0.8.

**Steps to reproduce**
Add applet to the panel, you will get:
```
Extension cinnamon-timer@jake1164 is not compatible with current version of cinnamon. Using it may break your system. Load anyway?
```
Reply by clicking `Yes`, but applet still does not load.

**Expected behaviour**
Applet should load.

**Other information**
This happened first after upgrade Linux Mint from 19 to 19.1.

**Comment by meysam81** [comment]
same here

**Comment by onceoffgithut** [comment]
error t=2019-01-03T08:34:23Z 
[netusagemonitor@pdcurtis]: Found un-versioned applet netusagemonitor@pdcurtis with known usage of imports.gi.NMClient
[netusagemonitor@pdcurtis]: Error importing applet.js from netusagemonitor@pdcurtis

**Comment by pdcurtis** [comment]
@onceoffgithut  netusagemonitor@pdcurtis had 'versioning' added some time ago and the usage of imports.gi.NMClient fixed for 4.0

But the latest version needs to be downloaded as applets do not yet automatically update even on a system upgrade such as 19.0 to 19.1.

  * System Settings ->  Applets go to Download Tab, find all the applets you use, select and update.

For information - the latest version number of netusagemonitor@pdcurtis is 3.2.8 and the changes were made in 3.2.6

**Comment by sphh** [comment]
@onceoffgithut @pdcurtis : Are you referring to `cinnamon-timer@jake1164`, which this thread originally was about? If not, you might want to open another issue ...

**Comment by pdcurtis** [comment]
@sphh @meysam81  Yours is a real issue, the one from @onceoffgithut is hopefully not an issue which needs to be opened which is why I responded here. 

In your case with cinnamon-timer@jake1164 metadata.json needs to have 4.0 added to cinnamon-version  so the line is  `"cinnamon-version": ["2.6", "2.8", "3.0", "3.2", "3.4", "3.6", "3.8, 4.0"]` otherwise it will not load.

There is however something more serious as even after enabling 4.0 it does not work and @jake1164 will need to have a look. There are no obvious errors in the Looking Glass log.

**Comment by jake1164** [comment]
Sorry, I was on vacation, I can update the app to work with the latest version this week.
________________________________

**Comment by vitaliis** [comment]
Was there some update? It still doesn't work for me (using Cinnamon 4.0.9)

**Comment by jake1164** [comment]
I am Still looking into what is causing the cinnamon-timer to not load in 4.0.
________________________________

**Comment by kluszon** [comment]
In my case the same.

**Comment by claudiux** [comment]
It works perfectly for me (Cinnamon 4.0.9, LM 19.1).

I have edited the `~/.local/share/cinnamon/applets/cinnamon-timer@jake1164/metadata.json` file and changed:
```
"cinnamon-version": [
        "2.6",
        "2.8",
        "3.0",
        "3.2",
        "3.4",
        "3.6",
        "3.8"
    ],
```
to:
```
"cinnamon-version": [
        "2.6",
        "2.8",
        "3.0",
        "3.2",
        "3.4",
        "3.6",
        "3.8",
        "4.0"
    ],
```
Then reload this applet (Super-L -> Extensions tab -> right-click on `Timer with notifications` -> Reload code) or reload Cinnamon (ctrl-alt-esc).

The countdown does not appear on the vertical panel, except by hovering over the icon (displaying the tooltip).

**Comment by jake1164** [comment]
Submitted a PR this morning.
https://github.com/linuxmint/cinnamon-spices-applets/pull/2244

**Comment by jake1164** [comment]
I will have to look into the vertical panel, perhaps add a new issue for that so it doesnt get lost?

**Comment by sphh** [comment]
I tried it again and funnily enough, the timer works again. The only (obvious) difference to my first report is the change of the cinnamon version which is now 4.0.**9** instead of **.8**
```
 * Applet version/Build date: 1.1.2
 * Cinnamon version: 4.0.9
 * Distribution: Mint 19.1
```
Note, this is still the applet not updated...

**Comment by claudiux** [comment]
@jake1164 OK. Thank you.
I have also installed `sox`:

    LinuxMint: apt update && apt install sox libsox-fmt-mp3
    Fedora: sudo dnf update && sudo dnf install sox
    Archlinux: sudo pacman -Syu sox

You can check the code of vpnLookOut@claudiux to check dependencies and propose to install them to the user.

**Comment by jake1164** [comment]
When I made my changes this morning it was on a 4.0.9 VM. I was thinking my development laptop was just hosed up but it looks like it has 4.0.8 which behaves differently with that applet.

I will have to play with it more later.
________________________________

**Comment by jake1164** [comment]
This has been resolved.

**Comment by sphh** [comment]
I can confirm that version 1.1.3 from 25.1.2019 loads again. Thanks!!
