### ISSUE TITLE
weather@mockturtl: Weather details fail to load (expired API?)

### ISSUE THREAD

**Issue by Ranthe24** [linuxmint/cinnamon-spices-applets#2178]
```
 * Applet version/Build date 1.1.40 2018-12-02 09:15 UTC
 * Cinnamon version 4.0.8
 * Distribution - Mint 19.1
 * Graphics hardware *and* driver used NVIDIA Corporation GF119 [GeForce GT 610], 
 * Snippet or attachment of ~/.cinnamon/glass.log (can't locate)
 * Snippet or attachment of ~/.xsession-errors
(cinnamon:1528): Cjs-WARNING **: 17:47:35.358: JS ERROR: TypeError: json is null
anonymous/refreshWeather/<@/home/<user>/.local/share/cinnamon/applets/weather@mockturtl/applet.js:430:11
soupQueue@/home/<user>/.local/share/cinnamon/applets/weather@mockturtl/applet.js:412:7
 ```

**Notify author of applet**
@mockturtl 

**Issue**
Weather details fail to load in applet from Friday 4 Jan 2019. Applet was working fine prior to this date.

**Steps to reproduce**

1. Add applet to Cinnamon taskbar
2. Right click, select "Configure"
3. Enter valid WOEID, close Configuration window.

**Expected behaviour**
Weather details for location associated with WOEID are displayed in the taskbar and in the popup window.

**Actual behaviour**
No weather details are displayed, "refresh" icons are displayed in the taskbar and in the popup window.

**Other information**
This may be caused by the expiration of the Yahoo! weather API - 

> "Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. 
To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Contact yahoo-weather-ydn-api@oath.com for credentials to onboard to this free Yahoo Weather API service."
https://developer.yahoo.com/weather/?guccounter=1

**Comment by sakralbar** [comment]
+1
Cinnamon version 4.0.8
Distribution - Mint 19.1

**Comment by Privacy-Badger-User** [comment]
+1.  Same problem.
Cinnamon 3.8.9 openSUSE Tumbleweed snapshot 20181224

**Comment by thegreatyellow67** [comment]
Also for me Same problem.
Cinnamon 4.0.8 Linux Mint 19.1.

**Comment by jaszhix** [comment]
Please click the thumbs up icon to express interest in a fix, and don't +1 spam. Thanks.

**Comment by Sadi58** [comment]
A good alternative (systray indicator instead of cinnamon applet) until this is fixed:
[https://gitlab.com/bitseater/meteo](https://gitlab.com/bitseater/meteo)

**Comment by mattst** [comment]
+1
Linux Mint 17 Qiana, Cinnamon 64-bit 2.2.16

**Comment by nick-s-b** [comment]
Looks like project WOEID has been discontinued: 

> Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. 
>To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Contact yahoo-weather-ydn-api@oath.com for credentials to onboard to this free Yahoo Weather API service.
>https://developer.yahoo.com/weather/

After Verizon acquired Yahoo!, this has been happening to a lot of their open APIs.

I've been looking for an alternative and there seems to be a few of them but they all require that a user create an account with them and get an API key. There's also an option to scrape websites for temp/weather forecast data.

Some alternatives that we could use to replace Yahoo:

  - https://darksky.net/dev - 1000 calls per day for free, requires an API key & registration.
  - https://openweathermap.org/price - don't let that word 'open' and '.org' fool you.. you still need an API key and you get a 5 day forecast
  - https://www.apixu.com/ - need an API key + registration; limited number of requests
  - https://www.foreca.com/ - I found this after I snooped on Windows 10's weather app in a VM. It's using this service. It's actually one of the most comprehensive weather solutions (i.e. https://www.foreca.com/United_States/California/Oakland ) but I don't see an API so scarping would be the only solution... but a s benefit, you wouldn't need to register.

Anyway, it looks like the new widget will have to be a bit more complicated. :)

**Comment by Phil995511** [comment]
From https://developer.yahoo.com/weather/

"Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. 

To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Contact yahoo-weather-ydn-api@oath.com for credentials to onboard to this free Yahoo Weather API service. "

**Comment by joaoherberto** [comment]
I don't mind https://openweathermap.org, I already have an API key from them...

**Comment by cranes-bill** [comment]
The [Weather Desklet ](https://github.com/linuxmint/cinnamon-spices-desklets/tree/master/bbcwx%40oak-wood.co.uk) uses [BBC Wather](https://www.bbc.com/weather/) by default and seems it works fine, and it requires no API...

**Comment by EdPhere** [comment]
Weather Desklet produces Err 02 No such file or directory: msgfmt .  How to resolve?

**Comment by Phil995511** [comment]
Excuse me, do you think this app fix a day or is it better for us to change? it's been 2 weeks since it does not work anymore ...

**Comment by sakralbar** [comment]
I use my-weather-indicator while this applet does not work.

**Comment by Sadi58** [comment]
@sakralbar Thanks for the tip. It stopped working at some stage and I forgot all about it. I now see it works very well.
[https://launchpad.net/~atareao/+archive/ubuntu/atareao/](https://launchpad.net/~atareao/+archive/ubuntu/atareao/)

**Comment by mockturtl** [comment]
I won't have time to fix this in the foreseeable future.  I'd be happy to see it adopted by the Mint team, or whoever is interested in maintenance.

I'm using the [bbcwx@oak-wood.co.uk desklet](https://cinnamon-spices.linuxmint.com/desklets/view/20) (with OpenWeatherMap) as an alternative.

**Comment by Floyd0122** [comment]
I started to work on the applet to use OpenWeatherMap in a way that it could be extended to support more APIs (or BBC) later on. I'm really busy too, but i will try to get it working this weekend, maybe get a pull request up next week. (Actually I don't really know if I'm allowed to do that but I will work on it nevertheless)

**Comment by Phil995511** [comment]
> I started to work on the applet to use OpenWeatherMap in a way that it could be extended to support more APIs (or BBC) later on.
> 
> I'm really busy too, but i will try to get it working this weekend, maybe get a pull request up next week. (Actually I don't really know if I'm allowed to do that but I will work on it nevertheless)

Excellent news !! Mint puts you in its distribution, it is a duty on your part to honor the trust they place in you. In 7-8 years it is the 2nd major breakdown. Already last time you took too much time to solve problems. I hope that if a problem should happen again in the future you will react more quickly. If not looking for someone to take over the project and take care as if it were her baby :) Excellent year 2019 to all of you, happiness and well being to you.

**Comment by mockturtl** [comment]
> Mint puts you in its distribution, it is a duty on your part to honor the trust they place in you. In 7-8 years it is the 2nd major breakdown. Already last time you took too much time to solve problems.

For [most of the project's history](https://github.com/mockturtl/cinnamon-weather/blob/master/CONTRIBUTING.md#i-have-a-feature-request-or-code-changes), I kept a disclaimer: _"I can't guarantee I will respond to these issues promptly, or ever. Feel free to @mention me in the issue comments if too much time has passed."_

Spices developers are volunteers, and it's a non-transferable skill.  Try not to take their time for granted.

**Comment by Sadi58** [comment]
@Gr3q it will be very much appreciated if you can let us know here when this applet has been updated as a result of your ongoing work (BTW, probably you already know, "my-weather-indicator" also uses OpenWeatherMap and perhaps it might be helpful to this end).
