### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Phil995511** [linuxmint/cinnamon-spices-applets#2187]
Hi,

I work on Linux Mint LMDE 3 and Linux MInt 19.1 on 2 distinct PC.

I have the last version of your software (1.14.0) disponible on Mint.

Since 24 hours your software no longer indicates the weather forecast.

http://woeid.rosselliot.co.nz/ no longer provides the regional codes necessary for the good functioning of your software 

"It appears that WOEID information has been discontinued. I'm pursuing an alternative. Please contact me if you are interested in a custom solution for your business."

http://woeid.rosselliot.co.nz/lookup/geneva%20switzerland

Best regrads

**Comment by jaszhix** [comment]
#2178
