### ISSUE TITLE
[vpnLookOut@claudiux]: Failed to evaluate 'main' function on applet: vpnLookOut@claudiux/65

### ISSUE THREAD

**Issue by Gene-W** [linuxmint/cinnamon-spices-applets#2194]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") 3.3.1~20181122
 * Cinnamon version (cinnamon --version) 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used
00:02.0 VGA compatible controller: Intel Corporation Device 591b (rev 04)
01:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Ti Mobile] (rev a1)
NVIDIA Driver Version: 390.77
 * Snippet or attachment of ~/.cinnamon/glass.log
Attached screenshots
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
The applet is unresponsive and is showing errors in Cinnamon Looking Glass. It will not connect to VPN.

**Steps to reproduce**

**Expected behaviour**
Connects to VPN

**Other information**
I have removed the applet and replaced it with a fresh version but am still receiving the same errors. I just updated to Mint 19.1 from Mint 19 yesterday.

![screenshot from 2019-01-05 19-44-26](https://user-images.githubusercontent.com/19363963/50731157-5f2fb380-1123-11e9-95cf-988808370d6f.png)

![screenshot from 2019-01-05 19-46-07](https://user-images.githubusercontent.com/19363963/50731159-5fc84a00-1123-11e9-9d71-b94f7c0e81e1.png)

**Comment by claudiux** [comment]
Strange. Have you completely uninstalled this applet? (It's not enough to remove it from the panel.)
The applet was downloaded incorrectly: the metadata.json file is missing, as reported by .xsession-errors.

I just did the manipulation. Everything went well. It just took me to connect to the VPN for the first time through the network icon panel.

Would you like to try again, please?

**Comment by Gene-W** [comment]
Ok, I did try that a few times and still had the error. So then I uninstalled the applet, rebooted, and installed it again and it's working great again. That was a strange thing, thank you for the great applet and support!

**Comment by claudiux** [comment]
Very strange, indeed. Happy that everything ends well.

Can you close this issue, please?

If you like this applet, thank you to "Star" it on this page: [VPN Look-Out Applet
](https://cinnamon-spices.linuxmint.com/applets/view/305). It encourages me to continue its development.

**Comment by Gene-W** [comment]
Thanks again, and it's a great applet. I appreciate your work!
