### ISSUE TITLE
timeout: does not work the option "automatically Resume"

### ISSUE THREAD

**Issue by andreevlex** [linuxmint/cinnamon-spices-applets#220]
Hello @NaruTrey

If you enable the option "Resume automatically" in the settings. Upon the occurrence of a break within the lock window, the report reaches 00:00 and the dialog is not closed. Example
![timeout_16032017](https://cloud.githubusercontent.com/assets/20382553/24013254/d8f1b08c-0a91-11e7-9215-aaa5811dd84f.jpg)
When you click "Postpone" the applet stops count down the time.

**Comment by andreevlex** [comment]
`lsb_release -a`

Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena

**Comment by NaruTrey** [comment]
I confirm, in the new version of Cinnamon the automatic continuation of the work does not work. I will issue a fix in the near future.

**Comment by NaruTrey** [comment]
My inattention allowed this bug, I will now fix it
