### ISSUE TITLE
SpicesUpdate@claudiux - customized color is chosen twice

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-spices-applets#2200]
@claudiux
Tiny bug found:
In settings click button to choose an icon color.
Click on the "+"-sign to select a new custom color.
Click "Choose" button -> the chosen color is displayed twice

Another hint:
Concerning the default icon color in case of updates - I made the suggestion to change it from blue to the Cinnemon orange, but unfortunately you chose a quite dark brown tone, also for the applet logo.
If it was intended, it's ok (you're the author and everyone can choose his own color of course), but I meant the orange logo like in the top of https://cinnamon-spices.linuxmint.com/applets/view/309 or similar.
That's #dc682e or #dc6830 or shiny #f57900 or your previous icon.png color #eb9122, and that might be more notable.

Greetings

**Comment by claudiux** [comment]
Hi @Mintulix 
The color chooser is part of Cinnamon. I am not the developer of this tool. But can have all his favorite colors in a line seems to me comfortable for the user.
I'm not very happy with the icon, too. I am working to create a new icon.

**Comment by claudiux** [comment]
@Mintulix Fixed in #2201.
