### ISSUE TITLE
[SpicesUpdate@claudiux] Add support for new packages

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#2202]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") 1.0.3
 * Cinnamon version (cinnamon --version) 4.0.0
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 ```

**Notify author of applet**
@claudiux 

**Issue**
Thank you for your great spice! That's what I wished for for a very long time!!

Personally I also use `Add applets to panel` to check for newly added applets (or Desklets or Extensions or even Themes). Currently I have the following workflow: Start `Applets` (`Desklets`, ...), goto `Download`, change `Sort by` to `Date`, update the list and look for newly added applets. BTW that's how I noticed that `SpicesUpdate` was added to the list of applets ...

If `SpicesUpdate` could also show me newly added applets (desklets, ...) in addition to updated applets (desklets, ...) that would be really great. Maybe this should be a configurable option?

**Comment by claudiux** [comment]
Very good idea! Thank you for this feature request, @sphh. I will do it as soon as possible.

**Comment by sphh** [comment]
Great! Thanks for considering it.

**Comment by sphh** [comment]
Thanks. That's great!

Is there a way to reset the display of new packages?

Currently I have to wait until the next update for the markings in the applet's menu to disappear. Until this update the icon will show "Updated/New packages". Have I missed something?

**Comment by claudiux** [comment]
@sphh Open the Applets manager (clicking in the menu of Spices Update), then Download tab and then Refresh cache.

**Comment by sphh** [comment]
Thanks.

Could this be incorporated in the menu of Spices Update? E.g. `Forget new packages` (just as `aptitude` does on Debian-based system)?

**Comment by claudiux** [comment]
Can you edit and complete the #2210 with this feature request, please? This one is closed.

**Comment by sphh** [comment]
Done. I opened the new issue #2213, because I believe #2210 and this one are not necessarily related.
