### ISSUE TITLE
SW++@mohammad-sn: Warnings and errors in melange/looking glass log

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-spices-applets#2209]
* Applet version/Build date (to be found in "About.." or in "metadata.json")
"last-edited": 1541957752

 * Cinnamon version (cinnamon --version)
4.0.9

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
LM 19.1

 * Snippet or attachment of ~/.cinnamon/glass.log
on start:
warning t=2019-01-13T23:08:44Z Initializing SignalManager with an object is deprecated. Please bind the callback before passing it to SignalManager.
overrideDumpStack/global.dump_gjs_stack@/usr/share/cinnamon/js/ui/overrides.js:103:42
SignalManager@/usr/share/cinnamon/js/misc/signalManager.js:87:13
anonymous/MyApplet.prototype._init@/home/xxx/.local/share/cinnamon/applets/SW++@mohammad-sn/applet.js:132:24
...

after switching workspaces:
warning t=2019-01-13T23:38:21Z Invalid or null source id used when attempting to run Mainloop.source_remove()
overrideDumpStack/global.dump_gjs_stack@/usr/share/cinnamon/js/ui/overrides.js:103:42
overrideMainloop/Mainloop.source_remove@/usr/share/cinnamon/js/ui/overrides.js:127:13
anonymous/MyApplet.prototype._onScrollEvent@/home/xxx/.local/share/cinnamon/applets/SW++@mohammad-sn/applet.js:510:13

error t=2019-01-13T23:38:21Z assignment to undeclared variable TL_Dot
warning t=2019-01-13T23:38:21Z Invalid or null source id used when attempting to run Mainloop.source_remove()
overrideDumpStack/global.dump_gjs_stack@/usr/share/cinnamon/js/ui/overrides.js:103:42
overrideMainloop/Mainloop.source_remove@/usr/share/cinnamon/js/ui/overrides.js:127:13
anonymous/MyApplet.prototype._onLEntered@/home/xxx/.local/share/cinnamon/applets/SW++@mohammad-sn/applet.js:447:13
pushModal@/usr/share/cinnamon/js/ui/main.js:1362:5
_grab@/usr/share/cinnamon/js/ui/popupMenu.js:3398:14
_onMenuOpenState@/usr/share/cinnamon/js/ui/popupMenu.js:3447:17
_emit@resource:///org/cinnamon/cjs/modules/signals.js:142:27
open@/usr/share/cinnamon/js/ui/popupMenu.js:2314:9
toggle@/usr/share/cinnamon/js/ui/popupMenu.js:2048:13
_onButtonPressEvent@/usr/share/cinnamon/js/ui/applet.js:283:17
...
etc.

@mohammad-sn
Are you aware of this? I use your applet for a long time now, just saw these errors and warnings in the log. Nevertheless the applet works fine.

**Comment by Mintulix** [comment]
Hi @jaszhix, are you maintaining this now? Still no reaction from @mohammad-sn...
This is the only applet I know flooding the Melange log (at least when used for switching workspaces).

**Comment by jaszhix** [comment]
Nope, but if he doesn't respond we can switch the author to none, or consider removing it.

**Comment by Mintulix** [comment]
I'd prefer fixing it (sadly beyond my scope). I find it quite useful as 
replacement for Windows Aero Peek at the lower right corner. It's 
configurable and has a suitable touchpad gesture as desktop switcher.

**Comment by Mintulix** [comment]
Hi  @mohammad-sn @jaszhix , I just had time and managed to fix all looking glass entries, and still everything seems to work :-). Should I make a pull request with the changed applet.js?
