### ISSUE TITLE
[SpicesUpdate@claudiux] Forget new spices

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#2213]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") 1.1.0
 * Cinnamon version (cinnamon --version) 4.0.0
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 ```

**Notify author of applet**
@claudiux 

**Issue**
#2207 added the possibility to check for new spices (#2202). If you activate this option, the icon will change colour to indicate that new spices are available. The menu also shows that new spices are available.

These indicators remain active until the SpicesUpdates makes a new check or the cache is updated manually from the settings.

It would be great to have a way to forget these new spices (like `aptitude` can do with the menu item `Forget new packages`). I can think of a menu item and/or a button in the notification(s).

**Comment by claudiux** [comment]
@sphh Solved in #2214.

**Comment by claudiux** [comment]
Hi @sphh. Can you close this issue, please?

**Comment by sphh** [comment]
Thanks for your great work!
