### ISSUE TITLE
[SpicesUpdate@claudiux] Keeps saying Weather Desklet (bbcwx@oak-wood.co.uk) is out of date, but no update available

### ISSUE THREAD

**Issue by kauffy** [linuxmint/cinnamon-spices-applets#2216]
```
 * 1.1.2 / 2019-01-17
 * Cinnamon 4.0.9
 * Mint 19.1
 * GTX 1070 Ti / Proprietary Drivers
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@claudiux 

**Issue**
Each time an update is checked for, I receive a notification that bbcwx@oak-wood.co.uk needs an update, but if I go into the Desklets, this particular Desklet does not show an update is available.

**Steps to reproduce**
Install Weather Desklet (bbcwx@oak-wood.co.uk) and configure. Wait enough time for Spices Update to do its check.

Spices Update reports that an update for bbcwx@oak-wood.co.uk is available. Click the notification to go to Desklets and find "Weather Desklet" in the list in the Download panel. Observe that no update is available for the Desklet.

**Expected behaviour**
Either I would not receive a notification for this Desklet, as it has not really been updated, or that I would be able to update this Desklet.

**Other information**

**Comment by claudiux** [comment]
Hi @kauffy,

Can you give me the answer of the command `cat ~/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/metadata.json` please?

**Comment by claudiux** [comment]
Hi @kauffy,

I can not reproduce this issue. Can you tell me if it's still here, please?

**Comment by claudiux** [comment]
Hi @kauffy,

Can you give me an answer or close this issue, please?

Regards.
Claudiux

**Comment by kauffy** [comment]
Sorry about that. I didn't see the notification that there'd been a response. The issue is still occurring (I tested after I saw this, by re-enabling that Applet).

Here is the output you requested:

`{
    "description": "Display the weather from several web services on your desktop", 
    "last-edited": "1494185621", 
    "name": "Weather Desklet", 
    "uuid": "bbcwx@oak-wood.co.uk",
    "max-instances": "10",
    "version": "2.10",
    "comments":"Please consider translating the Weather Desklet into your language. See the website for more information",
    "website":"http://www.oak-wood.co.uk/oss/other/bbcwx",
    "contributors":"Chris Hastie",
    "prevent-decorations": true
}`

**Comment by claudiux** [comment]
Hi @kauffy,

This is not a bug from this applet. I do not know why, but the last-edited value is between quotation marks. Please replace
`"last-edited": "1494185621",`
by
`"last-edited": 1494185621,`
then retry to update your desklet (Refresh the cache).

**Comment by kauffy** [comment]
@claudiux Ahh, thank you.

Oddly, when I made this change, then the Desklets app _did_ actually show an update was needed. I did the update, and now it appears settled.

**Comment by claudiux** [comment]
@kauffy  I just made a PR to solve this problem in Cinnamon.
