### ISSUE TITLE
[SpicesUpdate@claudiux] Open cinnamon applet (desklet/extension/theme) page on Download tab

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#2230]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") 1.1.3
 * Cinnamon version (cinnamon --version) 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 ```

**Notify author of applet**
@claudiux 

**Issue**
You already mentioned this in https://github.com/linuxmint/cinnamon-spices-applets/pull/2165#issuecomment-450722762: It would be great, if the menu entry opens the cinnamon applet (desklet/extension/themes) page in the `download` tab and in `date` order. Is that possible?

**Comment by claudiux** [comment]
Hi @sphh,

I'm working on this issue and on #2231.

**Comment by sphh** [comment]
Great. Works very well.

Thanks a lot!!!
