### ISSUE TITLE
[SpicesUpdate@claudiux] Show changes for new applets/desklets/extensions/themes

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#2243]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") 1.1.3
 * Cinnamon version (cinnamon --version) 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 ```

**Notify author of applet**
@claudiux 

**Issue**
One more idea: When there is an update available I would love to see what this update includes. Would it be possible to show the last update(s) from the history, e.g. https://github.com/linuxmint/cinnamon-spices-applets/commits/master/SpicesUpdate@claudiux?

This does not have a high priority, but would be nice to have.

Currently I open the `Applets` settings and check for each updated applet with the `More Info` button and then the `Last commit` link in the applet's page.

You could argue that this should be a feature of the `Applets` setting ...

**Comment by claudiux** [comment]
Hi @sphh,

Nice idea. I will think about it. But its realization can not be done before one or two weeks, because I have a lot of work elsewhere.

Best regards.
Claudiux

**Comment by sphh** [comment]
Hi @claudiux,
I certainly keep you busy by pestering you with ideas. I would like to help, but javascript is far beyond my capabilities. And don't worry about the time horizon. This is a "nice to have" and not a "don't do it without" feature.

**Comment by sphh** [comment]
Thank you @claudiux!!
