### ISSUE TITLE
[weather@mockturtl] Sunset and sunrise time appears twice after update to OpenWeatherMap

### ISSUE THREAD

**Issue by devsware** [linuxmint/cinnamon-spices-applets#2247]
* Applet version: 2.0.0
 * Cinnamon version: 3.2.7
 * Distribution: Mint 18.1

@mockturtl

**Issue**
After updating the applet to 2.0.0 version and setting the new parameters (OpenWeatherMap key, coordinates) data is correctly fetched from the service (I double-checked with some of my web applications that use OpenWeatherMap) but sunrise and sunset are displayed twice (see attachments).

I've also restarted Cinnamon to check if it needed something more than just updating the applet but the result is the same as described above.

Turning off the "Show sunrise/sunset times" option leaves visible the second occurrence of the sunrise and sunset times (see attachment)

**Steps to reproduce**
Update the applet to v.2.0.0, insert your API key and location, open applet panel.

**Other information**
With sunrise/sunset times on

![weather](https://user-images.githubusercontent.com/7092708/51743488-09ed1f00-209d-11e9-9efe-7d6fa0234113.jpg)

With sunrise/sunset times off

![weather-2](https://user-images.githubusercontent.com/7092708/51743718-dd85d280-209d-11e9-8eee-45174bc01977.jpg)

**Comment by Gr3q** [comment]
@devsware Did the last update fix the issue?
