### ISSUE TITLE
weather@mockturtl fails to update 2.0.0 - CLOSE

### ISSUE THREAD

**Issue by benchrest** [linuxmint/cinnamon-spices-applets#2252]
Cinnamon 3.8.9 Linux Mint 19.0
NVIDIA Corporation GP107 [GeForce GTX 1050 Ti
Applet fails to update.  If I go to the configuration and change any field, ie Update interval, Forecast length, the App updates to the current temperature. I installed app yesterday and have tested quite a bit including reboot without success.
Rich  

**Steps to reproduce**
do nothing, just watch the temperature in the panel for longer than 5 update cycles, Temperature does not update.

**Expected behaviour**
Expect app to update, perhaps be a bit behind but update occasionally. 

**Other information**

**Comment by benchrest** [comment]
I maybe mistaken, now it seems to be updating but about 1 1/2 hours behind. Doubt that this would be the app. At the openweathermap.org site shows temp for my location 36 degrees F. App shows 33 with update. Weather.com shows 37.  I will observe this a bit more and probably close if I do not discover more.

**Comment by cranes-bill** [comment]
You are wrong. I've added some log lines and can confirm the applet works as expected. It's not mandatory temperature to be changed in "_5 update cycles_"...

**Comment by benchrest** [comment]
I'm sure you are right. But you missed the point about 5 update cycles. I was just giving it long enough to update and it wasn't. Yesterday it never updated, but perhaps I was not waiting long enough before manually updating. To day (with update set to 15 minutes) the temp was rising rapidly. It was 10:30 before it showed the 9 am temp. Now in the afternoon the temp is more stable and not changing as rapidly. But late morning I changed from 15 minute interval to 5 minute and it is doing much better. But that change should not have mattered. Probably because the temp is now more stable it seems more accurate. But also if most of my update request were being rejected it would seem slower to update. By changing to 5 minutes I am making 3x as many request so that might be it.  Not sure to tell if my request are being rejected.  But since no one else has a concern it must be me. I will **close.**
