### ISSUE TITLE
Increased RAM usage while applet sysmonitor@orcus in use

### ISSUE THREAD

**Issue by gaya4** [linuxmint/cinnamon-spices-applets#2253]
sysmonitor@orcus 

```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") - 1.6.3
 * Cinnamon version (cinnamon --version) - Cinnamon 3.6.7
 * Distribution - Ubuntu 18.04.1 LTS
 * Graphics hardware *and* driver used  - 3rd Gen Core processor Graphics Controller driver=i915 (Dell Laptop Latitude, 6230 with 3x Monitors attached, problem happens with 3x external monitors or with single builtin display), another Latitude E7480 has the same behaviour, if needed I'll share the logs.
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors
Not entirely sure what in there is useful. Glass.log is mostly empty and shows some applet adding, settings and hidings, xsession-errors has plenty of errors that I deem not related. But I'll 
attach those.
Also attached is info about the process according to /proc/<pid>/io, maps, numa_maps, smaps, smaps_rollup, status
[proc_cinnamon_cat.log.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/2799387/proc_cinnamon_cat.log.zip)
[xsession-errors.log](https://github.com/linuxmint/cinnamon-spices-applets/files/2799388/xsession-errors.log)
[glass.log](https://github.com/linuxmint/cinnamon-spices-applets/files/2799389/glass.log)

 ```

**Notify author of applet**
 sysmonitor@orcus 

**Issue**

Continuous memory increase, supposedly memory leak. After 8hours 2-3GB usage of Cinnamon process.

**Steps to reproduce**

Leave Cinnamon with the applet running for some time, around 2-3 hours. Cinnamon process will increase its used memory. For the next hours the increase is much less, but the RAM will remain allocated.
On this 1600px screen I use from left to right: CPU (global 755px width), RAM 80px, Net (global 755px width). On the 1920px screen I use it likewise, adapted global values to fit screen (RAM=80px, global ~870px)

**Expected behaviour**

No memory increase, supposedly leak while applet is in use.

**Other information**
For me on 2 different systems; one as described above, another one I have to look up if needed /Dell Latitude e7480) it is the same. This is always reproducible on both systems I use.
As a result: If I work for it over the whole day, Cinnamon is using up to 3GB RAM. System becomes sluggish due to swapping. On above system with 8GB RAM might not be enough, applications fail to start. The other system has 16GB, but those are needed for VMs so the mem-increase is actually worse there. The plugin provides good info in a nice non-disturbing on-top view whether a process or even VM starts misbehaving or creates network traffic for some reason.
I use this applet since around 6 months on the E7480 5days a week and on some days in the evening for some hours on the system described above. Described behaviour happens always-

Workarounds:
- Restart Cinnamon (temporary, but favorite)
- Decrease update time of applet. (memory increases less over time)
- Decrease size of applet (memory increases less over time)
- Uninstall applet (no significant(!) increase of Cinnamon noted - 400-500MB after 8 hours)
->
It seems that the update time is affecting this behaviour, lower update time, lower mem increase.
I love this applet, the only alternative is the icewm Window Manager which seemingly is too outdated. Another promising plugin is the "indicator-multiload" but that immediately freezes my Cinnamon until I kill it.
Normal update time for me is 100ms, other update time settings were 1000ms. mem increase is better (=less) then, but only better in terms of "not 3GB at the end of the day but 2GB".
Likewise it behaves with the size of applet:
My screens are here 1600px in length, at work 1920px. applet fills whole length

See another users comment in applet page:
https://cinnamon-spices.linuxmint.com/applets/view/88

Whatever is needed, I'll try to provide debugs if you let me know how.

Thank you.

**Comment by jaszhix** [comment]
You need to notify github usernames.

@OrcusCZ

**Comment by OrcusCZ** [comment]
Thank you for the report. I'll try to reproduce the problem.
Also, can you tell me what version of libgtop you have?

**Comment by gaya4** [comment]
Hello,

thanks for looking into this! I got the one 2.38.0-2ubuntu0.18.04.1:
https://packages.ubuntu.com/bionic-updates/libgtop-2.0-11
According to release notes this has been around for some time (I update my system every other week).

Thank you - and thanks to @jaszhix for mentioning.

**Comment by gaya4** [comment]
Sounds good. I'll be testing this on both machines, just in case; tomorrow night I'll be reporting back.
Thank you for the quick response and the work in general.

**Comment by gaya4** [comment]
Hello,
earlier than expected. The RAM looks good on both machines, just watched for around 2 hours. This machine was restarted, the other had only cinnamon restarted.
It seems that CPU load is a little higher than before also worse when the updates are faster. I tried to capture this in a screenhistory from the gnome system monitor but it seems to be just an subjective average; difficult to show.
I'll check in tomorrow again with the load experience on these machines.

**Comment by OrcusCZ** [comment]
Hi, I'll look into it. The only change I did was that I now manually call $dispose() at the end of repaint event, so cairo surfaces are properly freed (the same fix as used in [this extension](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/commit/19a382d50265c06ff20b393b2122f0cf73902e67)), so the only thing that could increase CPU usage compared to the current applet version is explicit destroying of cairo context.

If it really comes from that, not sure what to do to avoid both increased RAM and CPU usage. If I understand the problem right, GC won't collect cairo surfaces, I have to explicitly call $dispose() every time I use cairo context, so I can't call it with lower frequency. Maybe I could use only 1 drawing area for the whole applet. Right now, each graph uses its own drawing area, because it simplifies the code for drawing and enabling / disabling specific graphs. I'll change the code to use only 1 drawing area and test if it helps.

**Comment by gaya4** [comment]
Hello,

Don't know if it helps; for years I used the simple iceWM that is 
displaying ram as fixed bar in the middle and cpu+netload in variable 
length around it.
Works similar but has some display bugs. Cinnamon goes better on a laptop 
for intuitive use, navigation is better and I need the 
gnome-online-accounts for Microsoft exchange.
That WMs code might be giving ideas, even the language is different.
But even if it doesn't, more CPU is still better than ram load :)

Thank you.


--- Original message ---

**Comment by OrcusCZ** [comment]
Hi,
I've changed the applet code to use only one drawing area, so if the higher CPU usage comes from $dispose(), it should be better now.

I didn't notice any significant CPU usage increase with my previous fix, but I've tested it only on one device and it was VM, because I don't use Ubuntu and wanted to test the same environment as you have.
I'll most likely update the applet to this new version after I do some more testing and check if everything works.

You can try it and check if you have lower CPU usage with this new version. It's available currently in my fork here [https://github.com/OrcusCZ/cinnamon-spices-applets/tree/sysmon-memoryleak-fix/sysmonitor%40orcus/files/sysmonitor%40orcus/3.2](https://github.com/OrcusCZ/cinnamon-spices-applets/tree/sysmon-memoryleak-fix/sysmonitor%40orcus/files/sysmonitor%40orcus/3.2), you should update all changed files (or all files just to be sure).

**Comment by gaya4** [comment]
Hello,

Thanks again! I tried it, but in my environment I quickly see a line 
dividing the bar from upper left to lower right. The line is drawn and 
seemingly filling the lower half. Until the middle 80px bar seems like 
it would not fully disappear. I'm attaching the small bar screenshot. 
Hope it helps.

Am 04.02.19 um 15:37 schrieb OrcusCZ:

**Comment by OrcusCZ** [comment]
Hi, it looks like the drawing is all broken for some reason. Did you replace all the files including the settings-schema.json?

Could you send me your applet config? It should be in the directory `~/.cinnamon/configs/sysmonitor@orcus`. I didn't see this behavior in my environment and maybe it is something in your config which leads to it and allows me to replicate it. Thanks

**Comment by gaya4** [comment]
Hi OrcuCZ,

I did replace the applet, graph and settings-schema as those were the changed files and overwrote files in
~/.local/share/cinnamon/applets/sysmonitor@orcus/3.2/
That should be OK, I believe. I crosschecked since it was late. But it is late again ;)
The settings are attached "28.json" (renamed from 28.json)

Thank you.

[28.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/2834059/28.txt)

**Comment by OrcusCZ** [comment]
Hi, I think I got it. You have disabled swap, right? From the colors, it looked like swap graph was causing the problem and I found that if I disable swap, I get NaN as a value to plot (used / total = 0 / 0 with disabled swap, division by zero). And the resulting behavior was exactly the same as yours.
I changed only one file [https://github.com/OrcusCZ/cinnamon-spices-applets/blob/8d5b70ab6e7d40cfb19355635f2bd868b3284475/sysmonitor%40orcus/files/sysmonitor%40orcus/3.2/providers.js](https://github.com/OrcusCZ/cinnamon-spices-applets/blob/8d5b70ab6e7d40cfb19355635f2bd868b3284475/sysmonitor%40orcus/files/sysmonitor%40orcus/3.2/providers.js).
I hope this fixes your issue, and if it does, could you please check your CPU usage, if it is better than the first version with fixed memory leak?

**Comment by gaya4** [comment]
Hello,

sorry, I've been busy with work; I'm testing it now locally and it looks good for some minutes. I'll check tomorrow with working laptop and run it for the whole day.

Yes I don't use swap normally.

Thank you!

**Comment by gaya4** [comment]
Hello again. Just shortly checked and compared. I believe the redraw is possibly causing the load directly. Not sure that can be actually fixed?
Subjectively I have the same load; 20%avg with 100ms refresh, and <5% with 1000ms refresh.
![load_diff](https://user-images.githubusercontent.com/13560529/52449423-9f75bd80-2b37-11e9-8101-12e1b3eec38e.png)

**Comment by gaya4** [comment]
Hello,

I noticed that in the files you may have adapted settings, so there were some more/all monitors running off-screen. I disabled them, load is down to around 15-20%; So the drawing is causing the CPU load, in my case 10x per second, but I don't think that this can be changed without rewriting the code. Most people won't need the fast redraw. Behaviour is the same on both of my machines.
So I'd think this issue #2253 (RAM) is resolved nevertheless.
Display also looks fine. If you need something from me, please let me know. Otherwise you or I can close #2253.

Thank you for all your effort and the great plugin. I need this. If it wasn't there, I'd need to dump the optics and features of Cinnamon and go back to iceWM.

**Comment by OrcusCZ** [comment]
Hi, thanks for letting me know. I'll change the code also for older Cinnamon, since my applet is multiversion, and then make a pull request. This issue will be closed after the pull request is accepted, so you don't need to do anything. When I have some more free time, I can check if there is any other way how to draw stuff in applets, which is not so demanding on CPU. Hopefully there is, no promises though.
And thanks for your help with testing

**Comment by gaya4** [comment]
"And thanks for your help with testing" - the least a(ny open source) consumer can do.
Thank you!
