### ISSUE TITLE
Where I can find official network applet of the Linux Mint?

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/cinnamon-spices-applets#2267]
In which repository is the network applet?
![obraz](https://user-images.githubusercontent.com/23406555/51947956-018f3e00-2427-11e9-941b-01b9747d2faf.png)

**Comment by collinss** [comment]
https://github.com/linuxmint/Cinnamon/tree/master/files/usr/share/cinnamon/applets/network%40cinnamon.org
