### ISSUE TITLE
Add Russian language to search-box@mtwebster

### ISSUE THREAD

**Issue by Faust30000** [linuxmint/cinnamon-spices-applets#227]
[ru_RU.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/851704/ru_RU.po.zip)

**Comment by NikoKrause** [comment]
Plesse create a pull request.
I refrenced here a tutorial how to do this https://github.com/linuxmint/cinnamon-spices-applets/issues/167

**Comment by NikoKrause** [comment]
https://github.com/linuxmint/cinnamon-spices-applets/pull/244
