### ISSUE TITLE
Weather@mockturtl 2.1.0 does not work below Cinnamon version 3.8

### ISSUE THREAD

**Issue by Gr3q** [linuxmint/cinnamon-spices-applets#2275]
Opening the issue to get it some visibility.

Indicator: applet does not load, the reason is SyntaxError in the LookingGlass log. (Because of using async functions)

Example of Error:
```
error t=2019-01-30T19:41:59Z missing } after property list 
error t=2019-01-30T19:41:59Z [Applet "weather@mockturtl"]: Error importing applet.js from weather@mockturtl 
error t=2019-01-30T19:41:59Z Could not load applet weather@mockturtl
```

It won't be fixed in the next update, but I will provide version 2.0.1 in the readme.

**Comment by MaxMotovilov** [comment]
Started looking at the code. 1st Q to you: are you sure settings callbacks are supposed to return promises? I can't find anything about it in Cinnamon docs; my suspicion is that the return value is simply ignored. Hence no point in making them async -- nothing will be waiting for completion anyway. I'll proceed on that assumption.

**Comment by MaxMotovilov** [comment]
Here's me with 3.2.7+serena...

**Comment by MaxMotovilov** [comment]
@Gr3q - for the time being I'm stuck with this:
```
const darkSky = require("darkSky");
const openWeatherMap = require("openWeatherMap");
// Location lookup service
const ipApi = require("ipApi");
```
Is CommonJS require one of those things that's been added in 3.6.x? Can't find much in the way of docs w/Google and definitely no time enough to read through Cinnamon code...

**Comment by jaszhix** [comment]
@MaxMotovilov It was added in 3.8. It was added because the CJS importer (the `imports` object getter) cannot reload a file once its loaded, Cinnamon has to be restarted. Files that are imported with require do reload when the applet does. All applets are loaded this way via promises initially.

I opened a PR that makes it a multi-version applet, so 2.0.1 is loaded for Cinnamon <3.8.

**Comment by MaxMotovilov** [comment]
Well. I guess as far as I'm concerned not updating the applet would achieve the same thing. I was hoping to contribute a rewrite back to plain ole ES6, but there's not much I can do about `require()` -- except, I guess, inline the modules (which the code owner isn't likely to accept...)

**Comment by Gr3q** [comment]
@MaxMotovilov I've switched requires to this last night on my dev branch:
```
const AppletDir = imports.ui.appletManager.applets['weather@mockturtl'];
const darkSky = AppletDir.darkSky;
const openWeatherMap = AppletDir.openWeatherMap;
// Location lookup service
const ipApi = AppletDir.ipApi;
```
Instead of using modules.export, regular functions can reside in the other files.
![image](https://user-images.githubusercontent.com/22377521/52162049-13dad780-26c6-11e9-870e-4a4a96e4745e.png)

Check it out [here](https://github.com/Gr3q/cinnamon-spices-applets/tree/dev)

**Comment by MaxMotovilov** [comment]
@jaszhix - `multiversion` does not seem to be working in my 3.2.7. Probably a later addition. Had to basically restore the 2.0.1 directory structure to get it to work.

@Gr3q - debugging anything in this env is a bit more of pain than I appreciated... recovery from lockups only by removing the offending applet. I can send you over my changes as a patch if you care for them, but probably won't have time to complete the PR on my own.

**Comment by Gr3q** [comment]
@MaxMotovilov multiversion was indeed not working because a metadata.json file was accidentally left in the 3.6 folder.

also you shouldn't have lockups, just crashes. the applet was freezing because my incorrect use of Soup. Please try again when the new fixes are in, or I can have a look what you've done so far as well

**Comment by MaxMotovilov** [comment]
> you shouldn't have lockups, just crashes

Heh. Proved to be real easy to get Cinnamon to crash on restart - hence Ctrl+Alt+F1, kill & vi :-). That, and with the latest applet codebase Cinnamon crashes a lot more often than it used to; since I didn't update anything else it's probably attributable to the applet.

> Please try again when the new fixes are in

I will when I get a chance. Meanwhile -- in case you want a look at my rewrite -- I'm attaching a patch.
[async.patch.gz](https://github.com/linuxmint/cinnamon-spices-applets/files/2825865/async.patch.gz)

**Comment by Gr3q** [comment]
@MaxMotovilov  It looks good, although there are more async functions now because I had to make some fixes a few days ago. (bug what was freezing up Cinnamon)

**Comment by Gr3q** [comment]
@MaxMotovilov I've had bit of time to look into it in a Linux Mint VM. 

It was indeed freezing cinnamon because _httpsession.send_message is not async. It was working kinda fine in async functions but I had replaced it with the promisified async equivalent of it.

Here is the version with your changes in what is not crashing: https://github.com/Gr3q/cinnamon-spices-applets/tree/3.8-backport/weather%40mockturtl 

the _httpsession.send_message functions are commented out for now. 
There is a function named LoadPayloadAsync commented out in applet.js what wraps the _httpsession.queue_message. That needs to be used instead of the send_message.

Could you fork my repo and have a look if you can do something with that function I'd appreciate it.

**Comment by MaxMotovilov** [comment]
Will do, as soon as I can get a breather :-)   Perhaps this weekend if I'm lucky enough. Thanx!
