### ISSUE TITLE
weather@mockturtl 2.1.0 freezes the whole screen when it's moved in panel edit mode

### ISSUE THREAD

**Issue by Gr3q** [linuxmint/cinnamon-spices-applets#2287]
@janos-r Took the liberty to open an issue based on your comment on Cinnamon Spices

**Issue**

"Thank you for the update! Loved the app. 

One big bug: System: Linux Mint 19.1 cinnamon Issue: When in "panel edit mode" and dragging the weather app (doesn't happen with other apps) to some other position, just to the right for example, the whole screen freezes. 

Workaround: ctrl + alt + backspace - this restarts Xorg. After login, the weather app is on its new position. Note: ctrl + alt + esc - doesn't unfreeze. "

**Comment by Gr3q** [comment]
I was able to reproduce it consistently.


The problem might be in the refreshWeather function, because binding that to a button clickevent also freezes Cinnamon.
![image](https://user-images.githubusercontent.com/22377521/52165086-da20c580-26f3-11e9-9fcc-5b1963bad2ed.png)

**Comment by feren** [comment]
I've got this issue too, it hardlocks Cinnamon so hard for me that it requires a 'killall **-9** cinnamon' to be killed, it won't even react to a SIGTERM signal anymore at that point and exit whatsoever.

I've also identified that Moving The Panel also triggers the hardlock while the applet is active.

**Comment by Gr3q** [comment]
Update: It has to do with how I'm using libsoup, digging into it now

**Comment by Gr3q** [comment]
Update: It has to do with how I'm using libsoup, digging into it now

**Comment by feren** [comment]
I've still got the issue on the newest version on Spices, but I've now got some output for it:
![img_20190202_210801-1](https://user-images.githubusercontent.com/11057934/52169386-51277f80-272f-11e9-8255-53de9b2a964a.jpg)

**Comment by Gr3q** [comment]
Apologies, the fix is not in this version, the pull request is up for it tho

**Comment by feren** [comment]
Oh, alright.

**Comment by feren** [comment]
This can now be safely closed, from my own experience with the Version 2.1.2.
Fixed by https://github.com/linuxmint/cinnamon-spices-applets/pull/2288
