### ISSUE TITLE
weather@mockturtl: DarkSky observations

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#2298]
@Gr3q

Thanx for the great work done to weather@mockturtl - I really like it !
Here is some minor thoughts on using the DarkSky service. 

 * Applet version/Build date (2.1.3)
 * Cinnamon version (cinnamon 4.0.9)
 * Distribution - (Mint 19.1)
 * No ~/.cinnamon/glass.log
 * No ~/.xsession-errors

When using Data service DarkSky the current/start/first day is shown with yesterdays weekday name and the upcoming days is wrong by one day.

Steps to reproduce:
1. Go to settings and choose DarkSky and enter a valid API Key and a Longitude,Latitude in the Location box. Choose 5 days Forecast length.
2. Wait for the applet to update and then open the applet by clicking it.
3. Move your mouse over/above the top weather text weather condition so a light gray button appears and click it.
3. Your browser now opens the web Darksky.net web with your local forecast. Scroll down on the page to see the 7 day forecast.
4.  Compare the conditions with the ones in the applet.

Expected behaviour: 
The upcoming forecast conditions should be the same in the applet as shown on the web.

**Comment by Gr3q** [comment]
Hello, could you tell me your timezone?

**Comment by jorgenqv** [comment]
Hi there, my timezone is CET (Central European Time) UTC/GMT +1 hour.

**Comment by Gr3q** [comment]
Had a look, indeed it is wrong.
Not even the sunset and sunrise times are right.

I was accessing one variable in the wrong place, I'll submit a pull request tonight

**Comment by jorgenqv** [comment]
Nice! But sunset/sunrise looks alright to me.

**Comment by Gr3q** [comment]
Are you sure? 

I'm positive if you change your location to japan or something you will get obviously wrong sunset/sunrise times

**Comment by jorgenqv** [comment]
Ah yes, just tried Japan and got sunrise late in the evening and sunset in the morning. My own location is the same in the app as on the web.

**Comment by Gr3q** [comment]
@jorgenqv could you check if it's working for you with the new version, and close this if it is?

**Comment by jorgenqv** [comment]
I will taket a look later today.

Den ons 6 feb. 2019 10:32 skrev Attila Greguss <notifications@github.com>:

**Comment by jorgenqv** [comment]
@Gr3q
Yes, works great! Also tried Tokyo and everything looks good. Sunset/Sunrise is correct, my local setting UTC/GMT +1 is the first weekday today, and in Japan tomorrows day is first witch is probably correct.
However:
1) The weekday names is not translated to my local language (everything else is translated, the longer conditions works nicely).
2) If I toggle the button Manual Location the service in the applet jumps over to OpenWeatherMap.
3) It would be nice with some label text on the top link button like Location or something.
Thank you so much for you excellent work so far! :)

**Comment by Gr3q** [comment]
First and third will be fixed in the next update, but I can't reproduce the second.

**Comment by jorgenqv** [comment]
Super. Yes two needs more checking and could be me just clicking around, will open new if it's there after next update. Closing, thanx.
