### ISSUE TITLE
Applets are not working with vertical panel

### ISSUE THREAD

**Issue by DiWa51** [linuxmint/cinnamon-spices-applets#23]
I've just switched on Mint 18.1 to be able to use the vertical panel feature.
Though my existing applet (multicore-sys-monitor@ccadeptic23) is not working anymore.

I've tried 2 others with the same result. While installing from the UI, a nice popup states clearly it's not supporting the vertical panel.

From this comes several things:
- Am I doing smthg wrong as it works for others?

If not then:
- Is there a way to identify applets compatible with vertical panel?
- Are there plans to easily make them compatible? _i.e. without code in the applet itself_.

Thanks

**Comment by jaszhix** [comment]
Yeah, this applet doesn't support vertical panels yet. The applet's code needs to be updated to support them.

**Comment by jaszhix** [comment]
@ccadeptic23 ^

**Comment by JosephMcc** [comment]
Please read the section on reporting issues at the end of the README https://github.com/linuxmint/cinnamon-spices-applets/blob/master/README.md
