### ISSUE TITLE
openweathermap data not accurate for Australia

### ISSUE THREAD

**Issue by Normmron** [linuxmint/cinnamon-spices-applets#2305]
[weather@mockturtl] Include BBC for weather data

```
 * Applet version/Build date 2.1.4
 * Cinnamon version 3.8.9
 * Distribution - Mint 19.1

The weather data for Australia from OpenWeatherMap is not accurate, very different from the local weather forecasts.  Would it be possible to include the BBC weather for the data source - its forecasts are accurate for Australia.

much appreciated and thanks for your great applet, 

Norm

**Comment by Gr3q** [comment]
Hello,

I agree, BBC weather data is accurate, when they provide data.

For example, Cambridge did not have current weather data for the whole last weekend in their rss feed, and the often omit weather conditions from there too.

I'd like to include it but it may end up more unreliable than the others.

The other option is that I can fill up the holes from the forecast, but it won't be accurate then.

Bit more technical:

The best would be get the data from the HTML page (would need care often because webpages change constantly) but I can't find a JS HTML parser, or have hard time convert one to be usable.

Its really easy to do in python, but the only way I know to get the data back into JavaScript atm is write/read files, what I really don't want to do.

**Comment by Odyseus** [comment]
Hello, everybody.

@Gr3q

> ...but the only way I know to get the data back into JavaScript from Python atm is write/read files...

You could look at the Feeds Reader applet for [how does it calls a Python script](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/feeds%40jonbrettdev.wordpress.com/files/feeds%40jonbrettdev.wordpress.com/feedreader.js#L134) to get [the return data](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/feeds%40jonbrettdev.wordpress.com/files/feeds%40jonbrettdev.wordpress.com/getFeed.py#L96).

It basically does this:

```javascript
Util.spawn_async(["python-script.py", "arg1", "arg2"], (aStdout) => {
    let data = aStdout;
});
```

Even Cinnamon does it this way to open a Save/Open file dialog from JavaScript code (the [fileDialog.js](https://github.com/linuxmint/Cinnamon/blob/master/js/misc/fileDialog.js) module uses the [cinnamon-file-dialog Python script](https://github.com/linuxmint/Cinnamon/blob/master/files/usr/bin/cinnamon-file-dialog)).

For my own fork of the weather applet, I looked into the BBC Weather feeds to see if it would be worth it to include a dependency to `feedparser` (the Python module that the Feeds Reader applet uses). But I dimmed it not worthy at all (look at their [Forecast response](https://weather-broker-cdn.api.bbci.co.uk/en/forecast/rss/3day/2643123) and [Current weather response](https://weather-broker-cdn.api.bbci.co.uk/en/observation/rss/2643123)).

**Comment by cranes-bill** [comment]
@Gr3q, you can check out whether [nodejs-htmlparser2](https://github.com/fb55/htmlparser2) could be implemented somehow.

**Comment by Gr3q** [comment]
@cranes-bill Even if I could, I'm not sure if it's not a too big tradeoff. That module has 8 files, and 6+4 dependencies. Include that into the applet would be a huge overkill.
I was actually looking at [this](https://github.com/blowsie/Pure-JavaScript-HTML5-Parser). 

@Odyseus bbcwx has a pure JS XML parser (marknote) so I can use that for RSS feeds. I could live with the thing that BBC's rss feed is utter garbage, as long as they provide data consistently, but they don't even do that

**Comment by cranes-bill** [comment]
>Even if I could, I'm not sure if it's not a too big tradeoff. That module has 8 files, and 6+4 dependencies.

Oh, that makes nonsense...
Also I'm absolutely agree that "_BBC's rss feed is utter garbage_". I was used it for a while when the applet was non working and noticed that they do not provide a correct data, so i failed to realise why @Normmron determines them as "_accurate_".

**Comment by Normmron** [comment]
You need to compare the weather data with the data provided by the Australian Weather Bureau, its almost identical.  I've verified the BBC's accuracy for Australia with the desktop applet over several months (the desktop applet uses the BBC weather as its source).  

The desktop weather applet uses the BBC reference number from the webpage:
"https://www.bbc.com/weather/2158177" for its configuration (ie 2158177).  The panel applet is unusable with openweathermap as its data source - its just too inaccurate (that's comparing it to the local weather forecasts over a couple of months).

Can't say that if the BBC weather is accurate for other locations around the world - its likely that each weather source has its strengths and weaknesses.

**Comment by dilinger** [comment]
I have a similar issue here in Seattle.  Right now the weather applet says light snow.  It is definitely not snowing (or even raining) right now.  Yahoo weather has the right info; cloudy, rain later on.  I've noticed this several times this week; current temperatures and weather conditions were way off. I've verified on the openweathermap site that it's not the app's fault - the source data is incorrect.

**Comment by Gr3q** [comment]
@Normmron @dilinger actually integrated BBC Weather, but I never released because sometimes it does not provide current weather.

 I can try to get Yahoo working again instead now that their website is actually functioning correctly...but it is still a fact that it won't be available below Cinnamon version 3.8 for now as I've got serious issues backporting that version of the app.

**Comment by cranes-bill** [comment]
@Gr3q 
You could also look at [xfce4-weather-plugin](https://git.xfce.org/panel-plugins/xfce4-weather-plugin/). It uses a [data](https://api.met.no/weatherapi/locationforecastlts/1.3/documentation) from **Norwegian Meteorologist institute**, which requires no api key.
**NOTE:** _Just a suggestion, I'm pretty fine with Openweathermap_

**Comment by Gr3q** [comment]
@cranes-bill had a look the Norwegian Met API, the data accuracy is pretty similar to DarkSky's, that's good.
