### ISSUE TITLE
[cinnamon-timer@jake1164] Downloadable applet not updated to 1.2.0

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#2320]
**Notify author of applet**
@jake1164 @jaszhix 

**Issue**

The applet's website https://cinnamon-spices.linuxmint.com/applets/view/302 shows the new version 1.2.0, but the downloaded zip-file from the download link provided (https://cinnamon-spices.linuxmint.com/files/applets/cinnamon-timer@jake1164.zip) still contains version 1.1.3. If I install the applet via the `Applets` program, I also only get the version 1.1.3.

**Steps to reproduce**

Download the zip file from https://cinnamon-spices.linuxmint.com/files/applets/cinnamon-timer@jake1164.zip or install the applet with the `Applets` program. This will result in version 1.1.3 downloaded/installed.

**Expected behaviour**

The new version 1.2.0 should be downloaded/installed.

**Comment by sphh** [comment]
Since the latest update #2337 the new version is installed and downloaded from the link provided.

**Comment by claudiux** [comment]
Add a question mark at the end of the URL. This forces the cache to send you the latest version of the zip file.

**Comment by sphh** [comment]
Thanks, I will try to remember.

Does the `Applets` program also has a cache? And shouldn't the `Applets` program always check if a newer version is available?
