### ISSUE TITLE
nvidiaprime@pdcurtis: not working Linux Mint 19.x series

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/cinnamon-spices-applets#2323]
```
 * Cinnamon version (cinnamon --version) not related with Cinnamon version
 * Distribution - (Linux Mint 19.x )
```

Hi @pdcurtis,

Nvidia-prime application in the Linux Mint 19.x series does not use bbswitch. therefore, following error occurs. The applet is not working properly because Bbswitch is not  in Linux Mint 19.x series.

> Nvidia Prime is not set up correctly - are the nvidia drivers and nvidia-prime installed

**Comment by pdcurtis** [comment]
@kelebek333 I currently have no access to a machine using optimus and will not for seversl months so unless you are in a position to suggest alternative tests to use of bbswitch and /proc/acpi/bbswitch to see if nvidiaprime is enabled I will have to just block use under 19.x - just installing bbswitch may have not be sufficient or have other consequences under 19.x 

There can not be many users if nobody has noticed up till now.

**Comment by kelebek333** [comment]
@pdcurtis ; yes, installation of bbswitch not necassarry on Linux Mint 19.x. Because in this version nvidia-prime does not use bbswitch. 

Most Nvidia-prime users may be using the default applet, so the issue may not have been noticed.

However, the extras in your applet are more useful in my opinion. That's why I wanted to give feedback. Prime-select command in the default applet can be used to query which GPU is enabled.

https://github.com/linuxmint/nvidia-prime-applet/blob/master/usr/share/cinnamon/applets/nvidia-prime%40cinnamon.org/applet.js

`                if (this._doCommand(["prime-supported"]) == "yes") {
                    let active_gpu = this._doCommand(["prime-select", "query"]);
                    if (active_gpu == "nvidia") {
                        this.set_applet_icon_symbolic_name("prime-applet-nvidia");
                        this.set_applet_tooltip(_("Active graphics card: NVIDIA"));
                    }
                    else if (active_gpu == "intel") {
                        this.set_applet_icon_symbolic_name("prime-applet-intel");
                        this.set_applet_tooltip(_("Active graphics card: Intel"));
                    }`

Thank you very much for your effort.

**Comment by pdcurtis** [comment]
@kelebek333 Will have a look over the next few days and see if I can put something together for ypu to test.

**Comment by pdcurtis** [comment]
It looks possible to use code from
https://github.com/linuxmint/nvidia-prime-applet/blob/master/usr/share/cinnamon/applets/nvidia-prime%40cinnamon.org/applet.js as
@kelebek333  suggests but I am not happy about making fairly major changes 'blind' as I have no way to test them as I am using  Bubblebee on my only Optimus machine and nvidia-prime is incompatible.

I have therefore blocked use of the current  applet under Cinnamon 3.8 and higher using "cinnamon version'" in metadata.json .

I have also made it easy for anybody who is using nvidia-prime to modify the applet by using the multiversion facility to provide a framework for a 3.8+ version which they can test and provide via a Pull Request without affecting the current functioning under Mint 18.x.
