### ISSUE TITLE
weather@mockturtl missing OpenWeatherMap conditions

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#2327]
weather@mockturtl

```
 * 2.1.6 / 15 Feb 2019 (to be found in "About.." or in "metadata.json")
 * Cinnamon version 4.0.9
 * Distribution - Linux Mint 19.1 Cinnamon
 * Graphics hardware Intel i915 v: kernel bus ID: 00:02.0
 * No ~/.cinnamon/glass.log
 * No ~/.xsession-errors

 ```
@Gr3q 

**Issue**
- When using OpenWeatherMap some weather conditions are not translated from English to the chosen localized local language.
- Workaround is to manually add the missing conditions in the po language file, but this will be gone when you run the update Bash script ./cinnamon-spices-makepot 

**Steps to reproduce**
- Log in as a user with any language other than English that has not manually added the missing conditions.

**Expected behaviour**
- That all conditions is translated and works when the pot file is updated so translators can update new future versions in a easy way.

**Other information**
I am unsure if the suggested bellow is possible and correct and works in applet.js or is there a better solution? And should it be in all three?

// Open Weather Map Conditions Groups https://openweathermap.org/weather-conditions

const openWeatherMapConditionLibrary = [
    // Group 2xx: Thunderstorm
    _("Thunderstorm with light rain"), 
    _("Thunderstorm with rain"), 
    _("Thunderstorm with heavy rain"), 
    _("Light thunderstorm"),
    //_("Thunderstorm"),
    _("Heavy thunderstorm"), 
    _("Ragged thunderstorm"), 
    _("Thunderstorm with light drizzle"), 
    _("Thunderstorm with drizzle"),
    _("Thunderstorm with heavy drizzle"),
    // Group 3xx: Drizzle
    _("Light intensity drizzle"), 
    //_("Drizzle"), 
    _("Heavy intensity drizzle"), 
    _("Light intensity drizzle rain"), 
    _("Drizzle rain"), 
    _("Heavy intensity drizzle rain"), 
    _("Shower rain and drizzle"), 
    _("Heavy shower rain and drizzle"), 
    _("Shower drizzle"),
    // Group 5xx: Rain
    _("Light rain"), 
    _("Moderate rain"), 
    _("Heavy intensity rain"), 
    _("Very heavy rain"), 
    _("Extreme rain"), 
    _("Freezing rain"), 
    _("Light intensity shower rain"), 
    _("Shower rain"), 
    _("Heavy intensity shower rain"), 
    _("Ragged shower rain"), 
    // Group 6xx: Snow
    _("Light snow"), 
    //_("Snow"), 
    _("Heavy snow"), 
    //_("Sleet"), 
    _("Shower sleet"), 
    _("Light rain and snow"), 
    _("Rain and snow"), 
    _("Light shower snow"), 
    _("Shower snow"), 
    _("Heavy shower snow"), 
    // Group 7xx: Atmosphere
    //_("Mist"), 
    //_("Smoke"), 
    //_("Haze"), 
    _("Sand, dust whirls"), 
    //_("Fog"), 
    //_("Sand"), 
    //_("Dust"), 
    //_("Volcanic ash"), 
    //_("Squalls"), 
    //_("Tornado"), 
    // Group 800: Clear
    //_("Clear"), 
    //_("Clear sky"), 
    //_("Sky is clear"), 
    // Group 80x: Clouds
    _("Few clouds"), 
    _("Scattered clouds"), 
    _("Broken clouds"), 
    _("Overcast clouds")];

**Comment by Gr3q** [comment]
@jorgenqv that is indeed the correct way of doing it (the only way actually as they come from external source). 

I get it done tonight

**Comment by jorgenqv** [comment]
wow great :-)

**Comment by Gr3q** [comment]
@jorgenqv I had a look at the OpenWeatherMap docs, first could I ask for what language was not translating properly, and do you remember which conditions were not translated?

Because I might need to keep both versions in, as OpenWeatherMap has a main condition (short), and a longer condition. Longer Condition comes translated, but the main one is not, and that is not documented properly.

**Comment by jorgenqv** [comment]
Hello. Just as an example I switch to Danish and none of the current conditions is translated.
![skaermbillede fra 2019-02-22 23-07-04](https://user-images.githubusercontent.com/5297223/53274441-90763a00-36f7-11e9-9407-a47a453add89.png)

**Comment by jorgenqv** [comment]
@Gr3q I have been running my Swedish translation for a couple of weeks with all the conditions found on the openweathermap link and they have all been translated this far. But conditions are of course limited to the season of winter right now with a lot oft rain.... ;-)

**Comment by jorgenqv** [comment]
#2331

**Comment by jorgenqv** [comment]
Works fine with the new structure, thanks
