### ISSUE TITLE
Cinnamenu@json - various issues with application descriptions

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon-spices-applets#2333]
```
 * Applet version/Build date 4.1.2
 * Cinnamon version 4.0.9
 * Distribution - Mint 19.1
 * Graphics hardware *and* driver used
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  vendor: Hewlett-Packard driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 18.2.2 
  direct render: Yes 
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@jaszhix 

**Issue**

1) Tooltip mode - in list layout tooltips are rendering way outside of the menu. In grid view in some themes with a bordered tooltip the right hand edge of the tooltip can be cut-off by 1 pixel.

2) Under titles mode is fine but I think it would be better to leave a blank space rather than add the 'No description available text' for entries without a description.

3) In the bottom pane mode occasionally the bottom pane description rapidly flickers between the currently hovered icon description and another unrelated description. I'm not sure what is needed to reproduce this. It's happened both with search providers enabled and disabled. 

4) In bottom pane mode and in list layout the systems buttons don't provide a description. In grid layout they do. 

**Steps to reproduce**
Use Cinnamenu in any of the three description modes.

**Expected behaviour**
It all to work nicely ;-)

**Other information**

**Comment by wrecklass** [comment]
Using _bottom pane_ mode in _List_ view, every time the menu is opened the _bottom pane_ gets larger and larger until the menu itself is moved above the screen. The only way to reset was to click the _Grid_ view button if it was still on the screen. Going back to _bottom pane_ tips was then working, but the problem continues to happen.
