### ISSUE TITLE
Printers(printers@linux-man): not display icon applet

### ISSUE THREAD

**Issue by andreevlex** [linuxmint/cinnamon-spices-applets#235]
@linux-man question.

When an applet is added to the panel, the icon does not appear
![printers_1803](https://cloud.githubusercontent.com/assets/20382553/24072898/0e793e28-0bff-11e7-984f-06e4362367c9.jpg)

Where is the icon located?

`lsb_release -a`
Distributor ID: LinuxMint
Description: Linux Mint 18.1 Serena
Release: 18.1
Codename: serena

**Comment by linux-man** [comment]
Couldn't replicate the bug. Maybe an icon is missing?
Try to change the icon to non-symbolic and see what happens.
The icon used is the system printer-printing-symbolic and printer-printing.
You can find them at /usr/share/icons/Mint-X/status/scalable.

**Comment by andreevlex** [comment]
Icons for found.
The reason is that one of the calls to `Util.spawn_async` does not work and execution does not reach 
`this.setIcon ('');` and the icon is not set.

I suggest before first calling `Util.spawn_async` write
example
`this.setIcon('printer-printing');` // default icon

**Comment by linux-man** [comment]
That explains what happens. My question is what call is failing?
If you don't see the installed printer on the menu, it can be
"python lpstat-a.py" (at the applet folder)
or "/usr/bin/lpstat -d".
The following calls are
"/usr/bin/lpstat -o"
"/usr/bin/lpq -a"

Can you try this commands at the console?

**Comment by andreevlex** [comment]
The problem repeats when I delete all printers
`/usr/bin/lpstat -o` nothing print
`/usr/bin/lpq -a` print "No records"
`python lpstat.py` print "lpstat:No added values"

I made a translation for an applet from a computer where there are no printers. 
Created an error report. 
I tried at work to do the same thing and after removing all the printers on the computer the problem was reproduced.

**Comment by linux-man** [comment]
I still can't replicate your problem, but if it only arise when there are no printers, the solution you proposed is feasible.
Could you please replace applet.js with this one?
[applet.js.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/857845/applet.js.zip)

**Comment by andreevlex** [comment]
Tried, works.

**Comment by linux-man** [comment]
Good. This version has less changes. If it works for you I'll send a pull request.
[applet.js.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/858943/applet.js.zip)

**Comment by andreevlex** [comment]
The new version works.
