### ISSUE TITLE
smallcalc_applet@lerc.sds MathJS is undefined

### ISSUE THREAD

**Issue by Ilis** [linuxmint/cinnamon-spices-applets#2354]
@lerc

After upgrade from Mint 18.3 to Mint 19 and updating applet to latest version I have an error at cinnamon startup

[smallcalc_applet@lerc.sds]: MathJS is undefined
[smallcalc_applet@lerc.sds]: Error importing applet.js from smallcalc_applet@lerc.sds

Cinnamon 4.0.9

**Comment by NikoKrause** [comment]
Fixed by https://github.com/linuxmint/cinnamon-spices-applets/pull/3639
