### ISSUE TITLE
Radio++ : no icon shown in the system tray

### ISSUE THREAD

**Issue by Wikinaut** [linuxmint/cinnamon-spices-applets#2355]
* LinuxMint 19.1

After installation of Radio++ and MOC Player, it works, but no icon is shown for that applet in the tray:
![grafik](https://user-images.githubusercontent.com/1151915/54063504-fd67f480-420c-11e9-83c1-e8b25fc9c2e3.png)

**Comment by claudiux** [comment]
Hi @Wikinaut,

This issue is now solved by #2357.
