### ISSUE TITLE
pomodoro@gregfreeman.org: Duration values are not visible

### ISSUE THREAD

**Issue by jkirk** [linuxmint/cinnamon-spices-applets#2356]
**A few facts**

* Applet version/Build date (to be found in "About.." or in **"metadata.json"**)

"About..." does not show a version or build date. (I think, this should be fixed, too).

`metadata.json`:
```json
{
    "dangerous": false, 
    "uuid": "pomodoro@gregfreeman.org", 
    "last-edited": 1541487177, 
    "name": "Pomodoro Timer", 
    "description": "Great tool for boosted productivity!"
}% 
```
* Cinnamon version (cinnamon --version)
Cinnamon 3.2.7

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Debian/stretch

 * Graphics hardware *and* driver used
_I am not perfectly sure how to answer this question correctly. Maybe someone could improve the template to help us providing the correct info. I used an Ask Ubuntu answer ([How to check the information of current installed video drivers?](https://askubuntu.com/a/28036)) as a guideline._
```
% lspci -v -s "00:02"
00:02.0 VGA compatible controller: Intel Corporation Device 5917 (rev 07) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Device 2256
	Flags: bus master, fast devsel, latency 0, IRQ 156
	Memory at e7000000 (64-bit, non-prefetchable) [size=16M]
	Memory at c0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at e000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915

% lsmod | grep "kms\|drm"
drm_kms_helper        204800  1 i915
drm                   491520  6 drm_kms_helper,i915


% find /dev -group video
/dev/video1
/dev/video0
/dev/fb0
/dev/dri/card0
/dev/dri/renderD128

% glxinfo | grep -i "vendor\|rendering"
direct rendering: Yes
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: Intel Open Source Technology Center (0x8086)
OpenGL vendor string: Intel Open Source Technology Center
```

**Notify author of applet**
@gfreeau

**Issue**

The issue is simple: In the settings window no numeric values are show next to the Duration sliders:
![Screenshot from 2019-03-09 15-05-26](https://user-images.githubusercontent.com/288637/54073268-6f7c2000-4285-11e9-8621-61de99541825.png)

My settings window does not look like the [screenshot](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/pomodoro%40gregfreeman.org/screenshot.png).

**Steps to reproduce**

* Left click applet -> "Settings"
or
* Right click applet -> "Configure..."
or
* Run `cinnamon-settings applets "pomodoro@gregfreeman.org"`

**Expected behaviour**

Show the minutes values of each duration.

**Other information**

Not sure if this is related:

```sh
% cinnamon-settings applets "pomodoro@gregfreeman.org"  

(xlet-settings.py:25361): Gtk-WARNING **: Theme parsing error: <data>:1:41: The style property GtkWidget:wide-separators is deprecated and shouldn't be used anymore. It will be removed in a future version

(xlet-settings.py:25361): Gtk-WARNING **: Theme parsing error: <data>:1:41: The style property GtkWidget:wide-separators is deprecated and shouldn't be used anymore. It will be removed in a future version

(xlet-settings.py:25361): Gtk-WARNING **: Theme parsing error: <data>:1:41: The style property GtkWidget:wide-separators is deprecated and shouldn't be used anymore. It will be removed in a future version
```

**Thank you**
Thank you, @gfreeau! I really like this applet and appreciate your work! I hope you find some time to further improve this applet!

**Comment by gfreeau** [comment]
Not sure if this still an issue, on mine the value shows above the slider, see screenshot.
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/1403669/151fae28-dd8b-4880-8131-a4cc5a313128)

**Comment by jkirk** [comment]
Just checked the settings window and the values are visible in the latest version (1.0.2).

Everything is fine now! Thank you for this cool applet! Closing.
