### ISSUE TITLE
[@SpicesUpdate@claudiux] Crash when adding to panel

### ISSUE THREAD

**Issue by Fabian42** [linuxmint/cinnamon-spices-applets#2360]
```
 * Applet version/Build date: ??? The one in the applets menu.
 * Cinnamon version 3.2.7
 * Distribution - Debian 9.8
 * Graphics hardware *and* driver used: Don't know how to find out. Graphics card is "NVIDIA GeForce GTX 1050".
 * Snippet or attachment of ~/.cinnamon/glass.log:

error t=2019-03-11T13:08:06.597Z class is a reserved identifier
trace t=2019-03-11T13:08:06.597Z 
<----------------
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:155
Extension@/usr/share/cinnamon/js/ui/extension.js:116
loadExtension@/usr/share/cinnamon/js/ui/extension.js:449
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:235
---------------->
error t=2019-03-11T13:08:06.597Z [Applet "SpicesUpdate@claudiux"]: Error importing applet.js from SpicesUpdate@claudiux
error t=2019-03-11T13:08:06.598Z Could not load applet SpicesUpdate@claudiux

 * Snippet or attachment of ~/.xsession-errors: https://drive.google.com/open?id=1OMSgaI94lkRwAqVC8DC6UK2Q-bhDxZ9v
 ```

**Notify author of applet**
@claudiux

**Issue**

When clicking "add to panel" in the applet menu, I get the error message "There was a problem loading the selected item and it has been disabled. Check your system log and the Cinnamon LookingGlass log for any issues. Please contact the developer." I am doing that. ;)

**Steps to reproduce**

1. Install Debian with Cinnamon DE.
2. Open system settings->applets->available applets
3. Install this applet, try to add it to the panel.

**Expected behaviour**

Works.

**Comment by claudiux** [comment]
It's normal, for the moment. This applet is intended to work with Cinnamon 3.8 or 4.0 (Linux Mint 19 or 19.1). Now that the development is finished, I will try to make a multi-version (which is more complicated to maintain for me), but only for Cinnamon version 3.6 and greater.

I encourage you to migrate to a newer version of Cinnamon.

**Comment by Fabian42** [comment]
Synaptic and apt-get give me no updates.

**Comment by claudiux** [comment]
@Fabian42 You can try https://linuxmint.com/download_lmde.php or http://developer.linuxmint.com/reference/git/cinnamon-tutorials/building.html.
(I'm using Debian only on my servers, without GUI.)

**Comment by claudiux** [comment]
@Fabian42 https://blog.linuxmint.com/?p=3615

**Comment by claudiux** [comment]
@Fabian42 You can also use mint-dev-tool to build the latest version of Cinnamon : http://segfault.linuxmint.com/2015/03/introducing-mint-dev-tools-a-collection-of-tools-for-linux-mint-developers/

**Comment by claudiux** [comment]
@Fabian42 A PPA exists to obtain the latest version of Cinnamon (4.2.2 at this time).
```
sudo add-apt-repository ppa:linuxmint-daily-build-team/daily-builds
sudo apt-get update
```
Please, can you tell me if any of these solutions worked for you, or close this issue?

Regards.

**Comment by Fabian42** [comment]
```
fabian@debian:~$ sudo add-apt-repository ppa:linuxmint-daily-build-team/daily-builds
 This PPA provides daily builds for testing purposes.

Note that these packages are built directly from the master branches of Linux Mint's git repositories and are therefore considered UNSTABLE.

Use at your own risk and make sure to perform regular system snapshots.
 More info: https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpxrmvr1id/pubring.gpg' created
gpg: /tmp/tmpxrmvr1id/trustdb.gpg: trustdb created
gpg: key 19C9F090A95304B8: public key "Launchpad PPA for Linux Mint Daily Builds Team" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.browser'
```

**Comment by claudiux** [comment]
Try this:
```
sudo apt-key del 19C9F090A95304B8
gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 19C9F090A95304B8 && (gpg -a --export 19C9F090A95304B8 | sudo apt-key add - )
sudo add-apt-repository ppa:linuxmint-daily-build-team/daily-builds
sudo apt-get update
```
The first line removes the key of this PPA out of your database.

The second line imports this key from the Ubuntu key server.

**Comment by Fabian42** [comment]
Nope. Are you sure you're not giving me instructions for Ubuntu? I'm using
Debian.

fabian@debian:~$ sudo apt-key del 19C9F090A95304B8
OK
fabian@debian:~$ gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key
19C9F090A95304B8 && (gpg -a --export 19C9F090A95304B8 | sudo apt-key add - )
gpg: WARNING: unsafe permissions on homedir '/home/fabian/.gnupg'
gpg: key 19C9F090A95304B8: public key "Launchpad PPA for Linux Mint Daily
Builds Team" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: WARNING: unsafe permissions on homedir '/home/fabian/.gnupg'
OK
fabian@debian:~$ sudo add-apt-repository
ppa:linuxmint-daily-build-team/daily-builds
 This PPA provides daily builds for testing purposes.

Note that these packages are built directly from the master branches of
Linux Mint's git repositories and are therefore considered UNSTABLE.

Use at your own risk and make sure to perform regular system snapshots.
 More info:
https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmp270nuzu6/pubring.gpg' created
gpg: /tmp/tmp270nuzu6/trustdb.gpg: trustdb created
gpg: key 19C9F090A95304B8: public key "Launchpad PPA for Linux Mint Daily
Builds Team" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File
"/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py",
line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line
386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line
273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line
234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory:
'S.gpg-agent.browser'

**Comment by claudiux** [comment]
@Fabian42 OK, I'm installing a new Debian with Cinnamon in a virtual box. I will test all that.

**Comment by claudiux** [comment]
@Fabian42 The best way is to upgrade your Debian  from version 9.8 (stretch) to version 10 (buster): https://linuxconfig.org/how-to-upgrade-debian-9-stretch-to-debian-10-buster

Cinnamon 3.8.8 will be installed.

Previously, remove the key and the list of linuxmint-daily-build-team:
```
sudo apt-key del 19C9F090A95304B8
sudo rm /etc/apt/sources.list.d/linuxmint-daily*
```

**Comment by Fabian42** [comment]
That seems to be a complicated process with many risks. I'll wait until the
official release.

**Comment by claudiux** [comment]
The official release of Debian 10.0 is here: https://www.debian.org/

The detailed method to upgrade from Debian 9 is here: https://www.debian.org/releases/buster/mips/release-notes/ch-upgrading.en.html

**Comment by Fabian42** [comment]
That still seems like a major task. I'll wait until I have more time. I don't need this applet that badly. Thanks for your help so far!

**Comment by claudiux** [comment]
OK. Then, can you close this issue, please? You can re-open it if needed.

Regards.

**Comment by claudiux** [comment]
Thank you, @Fabian42.

**Comment by claudiux** [comment]
@Fabian42 Please try the latest version of Spices Update (3.0.0).

**Comment by Fabian42** [comment]
It works! \o/

**Comment by claudiux** [comment]
@Fabian42 The version 3.0.1 (PR #2532) fixes this issue. If Spices Update suits you, please add a star on its page: https://cinnamon-spices.linuxmint.com/applets/view/309. Thank you.
