### ISSUE TITLE
[Cinnamenu@json] Calculator "search provider" hides other search results

### ISSUE THREAD

**Issue by Fabian42** [linuxmint/cinnamon-spices-applets#2361]
```
 * Applet version/Build date: 4.1.2
 * Cinnamon version: 3.2.7
 * Distribution - Debian 9.8
 * Graphics hardware *and* driver used: "NVIDIA GeForce GTX 1050", nothing special with drivers, just installed the "nonfree" version of Debian.
 ```

**Notify author of applet**
@jaszhix

**Issue**

Entering an equation in the search bar while the "search provider" "Calculator" is active gives the result of the calculation, but also makes all other search results invisible. They can still be selected with the keyboard and they still show their tooltip if that is activated, but they don't react to the mouse and they don't show any text or icon. Seen below is an example with a Wikipedia search result. This issue does not happen with the preinstalled Cinnamon menu.
![image](https://user-images.githubusercontent.com/10481506/54146286-ee14c100-442f-11e9-9c0b-01781b27e0f6.png)

**Steps to reproduce**

1. Install, activate, etc. Cinnamenu.
2. Download the "calc@cinnamon.org" folder from [here](https://github.com/linuxmint/cinnamon/tree/master/docs/search-providers-examples) and place it in `~/.local/share/cinnamon/search_providers`.
3. Restart Cinnamon.
4. Now that the search provider is active, enter any equation that also gives a regular search result. Especially easy with the Wikipedia search provider installed as well.

**Expected behaviour**

Either all search results showing (like in the preinstalled menu) or at least properly disabling them. Showing all is of course preferred.

**Comment by jaszhix2** [comment]
My main account has been banned since June, so I can't work on this.
