### ISSUE TITLE
hwmonitor@sylfurd Not showing new data after system standby

### ISSUE THREAD

**Issue by tcuje** [linuxmint/cinnamon-spices-applets#2371]
```
 * Applet version/Build date Wednesday, 7. November 2018 12:14:54
 * Cinnamon 3.8.9
 * Distribution - Mint 19 Tara
 * Graphics NVIDIA GTX 760 with NVIDIA Driver 390.116
 * ~/.cinnamon/glass.log file does not exist
 ```
 * ~/.xsession-errors [xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/2970660/xsession-errors.txt)

**Issue**

When I send my computer to sleep mode and wake it up again the applet keeps showing the data it had before the sleep. I have to restart Cinnamon to make it update again.

Issue occurrs for CPU and RAM visualization.

before sleep state:
![image](https://user-images.githubusercontent.com/4201214/54427447-cf0d7c00-471a-11e9-8d8b-c1b94ca2ecb8.png)

few seconds after wake up, flat line is already visible
![image](https://user-images.githubusercontent.com/4201214/54427524-07ad5580-471b-11e9-8bed-c72f7c554b79.png)

flat line:
![image](https://user-images.githubusercontent.com/4201214/54427563-2ad80500-471b-11e9-8c90-4a7e5f13daf8.png)

**Steps to reproduce**

* see applet working and updating info/graphs
* send computer to sleep mode (standby)
* wake up computer from sleep mode
* app shows no more CPU activity and alway the same RAM usage

**Expected behaviour**

* applet shows recent data as before sleep state

**Other information**

**Comment by Hultan** [comment]
I have managed to replicate this bug, on my computer though it took 10 seconds or so, and then it worked correctly again (without restarting Cinnamon). I will look into this and see if there is anything that can be done to fix this, or if it is just a result of the computer being busy after the suspend?

**Comment by Hultan** [comment]
@tcuje , I just added a restart function in the popup menu. Choosing **Restart 'Graphical hardware monitor'** solves the problem on my machine at least, can you see if it works on your machine after a suspend?

 A better solution would of course be if the applet restarted automatically after a suspend, but I don't know what event to subscribe to, or if such event even exists.

**Comment by Hultan** [comment]
@brownsr I think this issue can be closed now, I don't have permission to do so. If I ever find a way to make it work automatically I will implement it, but for now, a manual approach will have to do.

**Comment by claudiux** [comment]
@Hultan I have found a solution to this problem.

After a wake up, the delta value in the get_data() function becomes "highly negative". The solution is to store the previous value of delta and to restore it when delta becomes lesser than -50000.

```
CpuDataProvider.prototype = {

    _init: function(){
        this.gtop = new GTop.glibtop_cpu();
        this.current = 0;
        this.last = 0;
        this.usage = 0;
        this.last_total = 0;
        this.last_delta = 0;
        this.name = _("CPU");
        this.type = "CPU";
    },

    getData: function() {
        GTop.glibtop_get_cpu(this.gtop);

        this.current = this.gtop.idle;

        let delta = this.gtop.total - this.last_total;
        //global.log("Moniteur: delta " + delta );
        if (delta < -50000) {
            delta = this.last_delta;
        }
        if (delta > 0) {
            this.usage = (this.current - this.last) / delta;
            this.last = this.current;
            this.last_total = this.gtop.total;
            this.last_delta = delta;
        }

        return 1 - this.usage;
    }
};
```

I will make a PR.

**Comment by Hultan** [comment]
Awesome! Fantastic news.../Hultan
