### ISSUE TITLE
Network usage monitor (vnstat@linuxmint.com): Incorrect title label "mounth" in ru_RU.UTF-8 locale

### ISSUE THREAD

**Issue by andreevlex** [linuxmint/cinnamon-spices-applets#238]
![vnstat_18-3](https://cloud.githubusercontent.com/assets/20382553/24073776/eefb4c62-0c0d-11e7-8284-44d2a8a91e7f.jpg)

Should be the value of "мар '17"

**Comment by andreevlex** [comment]
command `vnstat` print this:
``` bash
                      rx      /      tx      /     total    /   estimated
 enp3s0f1: Not enough data available yet.
 docker0: Not enough data available yet.
 wlp2s0:
    мар '17         3,26 MiB  /    1,20 MiB  /    4,46 MiB  /    6,00 MiB
         today      3,26 MiB  /    1,20 MiB  /    4,46 MiB  /       4 MiB
```

**Comment by NikoKrause** [comment]
I don't think it's a bug in the applet.
This seems more like a bug in vnstat itself.

**Comment by andreevlex** [comment]
![network](https://cloud.githubusercontent.com/assets/20382553/24074135/c73954a2-0c13-11e7-8ecc-ef2bbebf2741.png)
Yes, problem in vnstati util.

**Comment by NikoKrause** [comment]
This is something that has to be fixed by vnstati.

**Comment by andreevlex** [comment]
Ok, send e-mail Ubuntu Maintainers.
