### ISSUE TITLE
[hwmonitor@sylfurd]: Can not add to panel

### ISSUE THREAD

**Issue by jkirk** [linuxmint/cinnamon-spices-applets#2393]
**Facts**
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 N/A (git rev https://github.com/linuxmint/cinnamon-spices-applets/commit/714987a176264c812b3cd41f72b045e0df3236d1 I believe)
 * Cinnamon version (cinnamon --version)
  Cinnamon 3.2.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
  Debian GNU/Linux 9.8 (stretch)

**Notify author of applet**
@sylfurd (not listed in [CODEOWENERS](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/CODEOWNERS)

**Issue**

The applet can not be added to the panel.

  There was a problem loading the selected item, and it has been disabled.

`glass.log` looks like this:
```
error t=2019-03-29T18:05:57.133Z /org/freedesktop/UPower/devices/battery_BAT0:=LGN
error t=2019-03-29T18:06:30.758Z Array(...).fill is not a function
trace t=2019-03-29T18:06:30.758Z 
<----------------
Graph.prototype._init@/home/jkirk/.local/share/cinnamon/applets/hwmonitor@sylfurd/applet.js:154
Graph@/home/jkirk/.local/share/cinnamon/applets/hwmonitor@sylfurd/applet.js:146
GraphicalHWMonitorApplet.prototype._init@/home/jkirk/.local/share/cinnamon/applets/hwmonitor@sylfurd/applet.js:91
GraphicalHWMonitorApplet@/home/jkirk/.local/share/cinnamon/applets/hwmonitor@sylfurd/applet.js:58
main@/home/jkirk/.local/share/cinnamon/applets/hwmonitor@sylfurd/applet.js:310
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:404
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:294
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:59
loadExtension@/usr/share/cinnamon/js/ui/extension.js:451
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:235
---------------->
error t=2019-03-29T18:06:30.758Z [Applet "hwmonitor@sylfurd"]: Failed to evaluate 'main' function on applet: hwmonitor@sylfurd/64
error t=2019-03-29T18:06:30.758Z Could not load applet hwmonitor@sylfurd
```

Thanks for looking into this.

**Comment by fireraiserDE** [comment]
Yep, same issue on my device:
`error t=2019-05-06T10:27:24.612Z [Applet "hwmonitor@sylfurd"]: Failed to evaluate 'main' function on applet: hwmonitor@sylfurd/27
error t=2019-05-06T10:27:24.612Z Could not load applet hwmonitor@sylfurd`

**Comment by Hultan** [comment]
I have looked at the code right where it happened, and that is code that is executed every time the applet is initiated when Cinnamon starts up. It is complaining about a javascript function Array.fill() that should exist without any problems, and it does obviously for almost everyone. If it is not, like in your case, I can only assume that Cinnamon has not started up correctly for some reason, and therefor not given this applet access to Array.fill().

Is this repeatable for you @jkirk and @fireraiserDE? Or did this just happen once and then never again? If it is repeatable, I would love to see a full log, from boot up to the hwmonitor applet load, to see if something happened outside of the applet that have affected it negatively...

At least, I cannot see how this can be a problem with the code in the applet, but I am fairly new to applets in Cinnamon so I can have missed something.

**Comment by jkirk** [comment]
Hi @Hultan, thx for taking time and looking into it.

I just updated the the applet to https://github.com/linuxmint/cinnamon-spices-applets/commit/bad1c72124614c262a0092aab8bc8181c77ce4b2 and still get the same error. After fiddling around a bit I ended up removing `.fill(0)` from that [line](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/hwmonitor@sylfurd/files/hwmonitor@sylfurd/applet.js#L187) - which seems to work. So now I wonder what the constructor is supposed to do. Do you mind to explain?

```
    _init: function (_area, _provider, panel_height) {
        this.width = (panel_height * ScaleRatio) - 3;

        this.datas = Array(this.width).fill(0);

        for (let i = 0; i < this.datas.length; i++) {
            this.datas[i] = 0;
        }

        this.height = panel_height - 2;
        this.provider = _provider;

},
```

Because the `for` block seems to fill the `datas` array with zeros which is - as far as I understand - the same what `fill(0)` is doing.

Disclaimer: I am no JS developer at all, so please don't be to hard if I misinterpret some things.

Another thing which is interesting too, is the question how to check if `fill` is implemented in Cinnamon or in Debian.

**Comment by Hultan** [comment]
Hi @jkirk,

I did not write this plugin originally, I started to add some functionality to it only a few days ago. I think the original author have left the scene, so to speak. At least, I have not heard from him/her...

About the constructor error, I think that you are right: The fill(0) part and the loop following seems to do the same thing. So it can probably be removed, like you suggested:

  this.datas = Array(this.width);

It is weird though, that you get this error but I am not, and obviously most people are not. What version of Cinnamon are you running? You can check this by running:

  cinnamon --version

in a terminal

I am currently working on implementing a mode for vertical panels, but after that I will look at fixing this.

**Comment by Hultan** [comment]
Hello @jkirk,

I just created a new Pull Request that allows for the applet to work in a vertical panel. At the same time I removed the .Fill(0) as we spoke of earlier. Try this version and hopefully it will work better for you.

Please do come back with your Cinnamon version anyway, I want to understand why that bug occurs for you, but not for me. The Cinnamon version might be the reason behind that...I guess...

**Comment by jkirk** [comment]
Hi @Hultan!

My Cinnamon version is 3.2.7 (as stated in the facts of this issue), 

I updated the applet to https://github.com/linuxmint/cinnamon-spices-applets/commit/1c895ee04f67cdd757da9977af1cfa5cddf1e2f8 and adding the applet works without problems. :tada:

So technically this issue is now resolved for me. But yes, I am still curious why this error is/was seen on my system and not on others (except @fireraiserDE I suppose)... I still think it boils down on how to find out where `fill()` is implemented.

**Comment by Hultan** [comment]
Haha, I am sorry, you DID mention your Cinnamon version in your first post. My bad...:-)

Even though I personally have only used Cinnamon 4+ (new to Linux), I do know that something big probably happened around 3.2. Many applets do contain checks if the Cinnamon version is at 3.2, and then do things differently. I have not looked in to what they do differently though, but fill() could be on thing that was added in 3.2, I guess!? And maybe it doesn't work 100% in the early 3.2-versions? I am just guessing here though...

I think we can close this issue now, and if it occurs again, please do open a new issue.

**Comment by Odyseus** [comment]
Hello, everybody.

@Hultan & @jkirk: It doesn't depend so much on the Cinnamon version, but on the version of the JavaScript engine (SpiderMonkey/libmozjs) a Cinnamon version is tied to. If I remember correctly, Cinnamon 3.2.x is still tied to SpiderMonkey 24. And in SpiderMonkey 24 `Array.prototype.fill()` doesn't exist (it was introduced in [Firefox 31](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill#Browser_compatibility)). I think that around Cinnamon 3.4.x or 3.6.x it started to use SpiderMonkey 38 and in Cinnamon 3.8.x it started to use SpiderMonkey 52.

**Comment by Hultan** [comment]
Thanks @Odyseus for the clarification. I think that settles it then, that would explain why @jkirk got this error. I think this issue can be closed now, I don't have permission to do so...

**Comment by jkirk** [comment]
@Odyseus: Cool! Thx for that explanation. And yes, JFTR, Debian/stretch comes with `libmozjs v24`:
```
% dpkg -l | grep libmozjs
ii  libmozjs-24-0:amd64                          24.2.0-5.1+b2                               amd64        Spidermonkey JavaScript engine
```
Thx for the link on how to check in which version a JS-function is implemented. This way it makes some things much easier to debug. 

(I can close the bug. Will do so now. :smiley:)

**Comment by jkirk** [comment]
After updating the applet to the latest version (https://github.com/linuxmint/cinnamon-spices-applets/commit/ad53c5a3), it again can not be added to the panel. I am reopening this issue as my environment (still Cinnamon v3.2.7 and `libmozjs v24`) did not change.

The `glass.log` looks like this when trying to add the applet:
```
error t=2019-10-14T13:39:06.992Z class is a reserved identifier
trace t=2019-10-14T13:39:06.993Z■
<----------------
@/home/jkirk/.local/share/cinnamon/applets/hwmonitor@sylfurd/applet.js:42
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:155
Extension@/usr/share/cinnamon/js/ui/extension.js:116
loadExtension@/usr/share/cinnamon/js/ui/extension.js:449
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:235
---------------->
error t=2019-10-14T13:39:06.993Z [Applet "hwmonitor@sylfurd"]: Error importing applet.js from hwmonitor@sylfurd
error t=2019-10-14T13:39:06.993Z Could not load applet hwmonitor@sylfurd
```

I've bisected the source and found out that the applet broke for me in commit https://github.com/linuxmint/cinnamon-spices-applets/commit/be1ad79874f97c78f6038c37167337cc98bbd472 but there the `glass.log` looked a bit different:

```
error t=2019-10-14T13:40:11.501Z class is a reserved identifier
trace t=2019-10-14T13:40:11.501Z■
<----------------
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:155
Extension@/usr/share/cinnamon/js/ui/extension.js:116
loadExtension@/usr/share/cinnamon/js/ui/extension.js:449
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:235
---------------->
error t=2019-10-14T13:40:11.501Z [Applet "hwmonitor@sylfurd"]: Error importing applet.js from hwmonitor@sylfurd
error t=2019-10-14T13:40:11.501Z Could not load applet hwmonitor@sylfurd
```

Can you help me pinpoint the problem or anything I can do to help to do so?

**Comment by Hultan** [comment]
@jkirk, please try : 

* Remove the applet from all panels
* Remove it from the applet gui (click on the minus sign)
* Do to the download page and download it again
* Add the applet back to your panel
* Give me some hopefully good news :-)

Thanks...

**Comment by jkirk** [comment]
Oh, I did all of this (as I also tried different versions of this applet). For the sake of completeness I did the following:

* Could not remove the applet from the panel (as it did not work anyways)
* "Remove from panel" (minus sign) was grayed out (as the applet was not running on any panel)
* Uninstalled the applet (right click on the applet in the Applet GUI / Installed Applets)
* Clicked "Refresh list" (in the Applet GUI / Availbable applets (online))
* Selected and installed the applet
* Clicked "Add to panel"

I am sorry, no good news :(

The problem seems to start here:

https://github.com/linuxmint/cinnamon-spices-applets/blob/ad53c5a3cbcb53472a74c74c9ab849b171fc0a6e/hwmonitor%40sylfurd/files/hwmonitor%40sylfurd/applet.js#L42

Which lead me to look into [providers.js](https://github.com/linuxmint/cinnamon-spices-applets/blob/ad53c5a3cbcb53472a74c74c9ab849b171fc0a6e/hwmonitor%40sylfurd/files/hwmonitor%40sylfurd/providers.js) but could not find anything suspicious. GTop is installed: 

```
% dpkg -l gir1.2-gtop-2.0  
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-============================================================
ii  gir1.2-gtop-2.0:amd64       2.34.2-1           amd64              gtop system monitoring library (gir bindings)
```

**Comment by Hultan** [comment]
Eh, my bad, the uninstall button is the one to the right of the minus sign (the one with the X). That should completely remove it from your system, and then download it again. Sorry!

**Comment by jkirk** [comment]
I think you are running Cinnamon 4.x (we talked about it :)), but I am running 3.2.7. I believe my applet gui looks a bit different. I only can uninstall the applet via right-click on the applet (which I did)... Let's assume I did the right thing to uninstall / install the applet...

**Comment by jkirk** [comment]
Oh no, it seems so: Browser support since [Spidermonkey JavaScript engine  45](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor#Browser_compatibility) and Debian/stretch is stuck at [Spidermonkey JavaScript engine 24](https://github.com/linuxmint/cinnamon-spices-applets/issues/2393#issuecomment-520147165).

Right, @Odyseus?

**Comment by claudiux** [comment]
The keyword `class` is not recognized before Cinnamon 3.8.

**Comment by Hultan** [comment]
I have removed the new **class** keyword, and hopefully it should work now.

See PR #2631

**Comment by Hultan** [comment]
@jkirk Can you test this applet again? It worked for me in Linux Mint 18.1 (Cinnamon 3.2.6)...

**Comment by jkirk** [comment]
@Hultan Thumbs up was for your work and energy to help to solve my problem! I really, really appreciate it! Thank you very much!

I've just tested the applet from the source and it works! :fireworks: :1st_place_medal: 

Unfortunately I do not get the same version out of the Applet GUI. I removed (actually not, as it was not running on the panel) and uninstalled the applet, refreshed the list and updated, installed and readded the applet again, but still seemingly get an old version... The Applet GUI does not tell me which version/revision is going to be installed/added to the panel. For know it still crashes. I assume that the repository list is not up to date yet (how to check that?). I will try again a few hours later / tomorrow and report back! 

Thanks again!

**Comment by claudiux** [comment]
@jkirk You can use the Spices Update applet to get the latest version of any Spice.

**Comment by jkirk** [comment]
Hmm. Something seems wrong with the Applet Repository. Neither the Applet GUI nor the Spices Update applet finds the latest version of the hwmonitor. Can someone confirm this?

(I am still running Cinnamon version 3.2.7 on Debian/stretch).

**Comment by claudiux** [comment]
@jkirk Please try a manual installation using this link: https://cinnamon-spices.linuxmint.com/files/applets/hwmonitor@sylfurd.zip?12345

Save the obtained zip file into your `~/.local/share/cinnamon/applets/` directory.

Go into this directory. Remove the `hwmonitor@sylfurd` folder.

Extract the zip file. The new `hwmonitor@sylfurd` folder appears. Then remove the zip file and restart Cinnamon.

**Comment by jkirk** [comment]
@claudiux A manual installation with provided link works.

What I noticed is that https://cinnamon-spices.linuxmint.com/files/applets/hwmonitor@sylfurd.zip?12345 provides the latest version whereas https://cinnamon-spices.linuxmint.com/files/applets/hwmonitor@sylfurd.zip gives me the old one. Where does "12345" come from?

What else is funny, that after manually installing the "12345" version, the Applet GUI tells me that there is an "update available" and when installing that it actually downgrades to the broken one... :thinking:

**Comment by claudiux** [comment]
@jkirk 

Adding a random number following a question mark to the url given by the Download button of a Spice web page allows to bypass all proxy: a particular request is sent to the server, which returns the right zip file.

Start over again the procedure above, then replace the content of the `metadata.json` file by this one before restarting Cinnamon:
```
{
    "multiversion": true,
    "cinnamon-version": [
        "3.2",
        "3.4",
        "3.6",
        "3.8",
        "4.0",
        "4.2",
        "4.3"
    ],
    "max-instances": "1",
    "dangerous": false,
    "description": "Displaying realtime CPU and memory load",
    "uuid": "hwmonitor@sylfurd",
    "version": "1.0.0",
    "name": "Graphical hardware monitor",
    "last-edited": 1571339171
}
```

**Comment by jkirk** [comment]
Hmm. I am not exactly sure why that worked or if I even did the right thing but I am happy to say, that I finally have a working applet and the applet does NOT get overridden but the older version. Thanks everyone for the great support!
