### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: Hide new network interfaces by default

### ISSUE THREAD

**Issue by edaubert** [linuxmint/cinnamon-spices-applets#2397]
**Notify author of applet**
@jaszhix 

**Enhancement**
Is it possible to hide new network interfaces by default instead of adding them by default ?

I am using docker on my machine and multiple network interfaces are created with all my containers instantiation.
I'd like to hide all of them.
But each time I create a new container, its interface is added on the applet and I need to manually deactivate it.

**Comment by claudiux** [comment]
This applet does not add or remove network interfaces. The culprit is somewhere else.
