### ISSUE TITLE
Network usage monitor (vnstat@linuxmint.com): not work translation in _updateGraph

### ISSUE THREAD

**Issue by andreevlex** [linuxmint/cinnamon-spices-applets#240]
I added the translation to the Russian language, but after update, the value "Please make sure vnstat and vnstati are installed and that the vnstat daemon is running!" was not translated .
![vnstat_translation](https://cloud.githubusercontent.com/assets/20382553/24074549/f0dab67c-0c1b-11e7-9bc8-eaac064c4eec.jpg)

I change `UUID = "vnstat@linuxmint.com"` -> `UUID = "vnstat@linuxmint"` in file applet.js and change file in ~/.local/share/locale/ru_RU/LC_MESSAGES/vnstat@linuxmint.mo

It work.

With `.com` not work.

**Comment by NikoKrause** [comment]
There is no line `UUID = "vnstat@linuxmint.com"` in the applet.js file

**Comment by NikoKrause** [comment]
It works okay here:
![screenshot-cinnamon-2017-03-18-190511](https://cloud.githubusercontent.com/assets/8415124/24074705/076f996a-0c0e-11e7-92cd-eabc279efa14.png)

Are you sure you updated the applet properly?
Check if the translation file exists in `~/.local/share/cinnamon/applets/vnstat@linuxmint.com/po`.

Also try to uninstall and install the applet again.

**Comment by andreevlex** [comment]
uninstall, restart system, update list applets, install applet, work. thanks.
