### ISSUE TITLE
pomodoro@gregfreeman.org: Sounds not playing

### ISSUE THREAD

**Issue by jkirk** [linuxmint/cinnamon-spices-applets#2407]
**A few facts**
* Applet version/Build date (to be found in "About.." or in **"metadata.json"**)

"About..." does not show a version or build date. (I think, this should be fixed, too).

`metadata.json`:
```json
{
    "dangerous": false, 
    "uuid": "pomodoro@gregfreeman.org", 
    "last-edited": 1541487177, 
    "name": "Pomodoro Timer", 
    "description": "Great tool for boosted productivity!"
}% 
```
* Cinnamon version (cinnamon --version)
Cinnamon 3.2.7

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Debian/stretch

**Issue**
No sounds are played.

**Steps to reproduce**
* Sounds -> Play Break Sound -> ON
* Timer Sound File:  `/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga`

**Expected behaviour**
The sound should be played after the short and/or(?) long break.

**Thank you**
Thank you, @gfreeau! I really like this applet and appreciate your work! I hope you find some time to further improve this applet!

**Comment by JanaFlauschata** [comment]
I had the same issue on Linux Mint 19.1 and managed to solve it with the tips from the [Cinnamon Spices site](https://cinnamon-spices.linuxmint.com/applets/view/131). So `sudo apt install sox` did the trick.

**Comment by somayn** [comment]
does not have sound. linux mint 19.2 64b
the tip from jana did not help. where is help to be found?

**Comment by omvsj** [comment]
> I had the same issue on Linux Mint 19.1 and managed to solve it with the tips from the [Cinnamon Spices site](https://cinnamon-spices.linuxmint.com/applets/view/131). So `sudo apt install sox` did the trick.

It worked for me.
