### ISSUE TITLE
Graphical hardware monitor (hwmonitor@sylfurd): Error add to panel

### ISSUE THREAD

**Issue by andreevlex** [linuxmint/cinnamon-spices-applets#241]
Try to install the applet and in the log appears the following error information.
```log
<----------------
@/home/alex/.local/share/cinnamon/applets/hwmonitor@sylfurd/applet.js:22
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:155
Extension@/usr/share/cinnamon/js/ui/extension.js:116
loadExtension@/usr/share/cinnamon/js/ui/extension.js:449
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:235
---------------->
error t=2017-03-19T16:14:50.322Z [Applet "hwmonitor@sylfurd"]: Error importing applet.js from hwmonitor@sylfurd
error t=2017-03-19T16:14:50.322Z Could not load applet hwmonitor@sylfurd
```

**Comment by Odyseus** [comment]
Hello, @andreevlex.

You need to have installed the package **gir1.2-gtop-2.0**. Or its equivalent for the Linux distribution that you are using.

**Comment by andreevlex** [comment]
We can learn how to make the notification of the dependencies in the applet "system-monitor@pixunil". This beautiful notice.
I want the user applet got an informative answer on the cause of the installation error.
Author @pixunil
