### ISSUE TITLE
weather@mockturtl: custom configuration is ignored when pressed hot key Shift+Super+W

### ISSUE THREAD

**Issue by jpachta** [linuxmint/cinnamon-spices-applets#2422]
Environment:
weather@mockturtl version: "2.1.7" 
Cinnamon 4.0.10
Fedora 29

**Notify author of applet**
@mockturtl

**Issue**
It seems that the hot key opens weather ignoring the custom settings. 

In my case I have set manual location as Brno,CZ and simplified icons, 24-hour format. All of these are working when I click on the panel applet. 
However when I press the key sequence Shift+Super+W to call the menu it shows me London, GB, non symbolic icons, 12-hour format.

My global ISP provider is providing me IP address that is  identified as from London, verified on https://ipapi.co/json . 

So it seems to use kind of default settings instead of the one I set up in the applet configuration.

More over I have the panel on the top of the screen however the hot key loaded menu opens on the bottom of the screen.

**Steps to reproduce**
Set manual location far away from your automatic location.
Press hot key sequence Shift+Super+W .
See the automatic menu - in my case the location and all settings is different from the one can see when manually clicking on the applet in the panel.

**Expected behaviour**
Show same information, ie. location, time format, icons, etc. as like when mouse clicked on the applet in the panel.

**Other information**

**Comment by Gr3q** [comment]
I can't reproduce this on Arch Linux

**Comment by mockturtl** [comment]
reference: 482387d3

> More over I have the panel on the top of the screen however the hot key loaded menu opens on the bottom of the screen.

Do you have multiple instances of the applet?  It sounds like the hotkey may be raising a second, unconfigured copy of it.

**Comment by jpachta** [comment]
Closing the issue since I cannot reproduce it any more. My current settings is Weather 2.4.3 running on Fedora 31 with manual location as coordinates 49.2064775,16.6058333 and all works as expected.
