### ISSUE TITLE
Places applet (places-bookmarks@dmo60.de) only shows menu if positioned on top tray

### ISSUE THREAD

**Issue by szekeres2016** [linuxmint/cinnamon-spices-applets#245]
Good day, today I rearranged my Cinnamon desktop have a single tray at the bottom, and I just noticed that the popular 'places' applet (places-bookmarks@dmo60.de) is not displaying a menu when clicked on. I created a panel at top and moved it there and it worked just fine. I think the menu still draw even if its at the bottom, but it is projected under the tray so its not visible.

I'm on Linux Mint Cinnamon 18.1 64-bit, Cinnamon version 3.2.7.

Top panel:
![top_tray](https://cloud.githubusercontent.com/assets/20751590/24120993/e0b4fb62-0db6-11e7-9d1e-e468f100fb64.png)

Bottom panel:
![bottom_tray](https://cloud.githubusercontent.com/assets/20751590/24121063/1fd66ac4-0db7-11e7-9a65-2d40d524b2e0.png)

**Comment by Odyseus** [comment]
Hello, @szekeres2016.

It works perfectly for me in either panel (top or bottom). Restart Cinnamon after moving your entire panel to the bottom/top.

**Comment by szekeres2016** [comment]
Hello, I even had several reboots but still not working for me. :S Any configuration files I should clear out maybe to have is reset somehow?

**Comment by Odyseus** [comment]
Hello, @szekeres2016.

You are right. I did my tests on Cinnamon 3.0.7, not on 3.2.x. In 3.2.x I see the same behaviour as you.

To fix it, just edit the applet.js file as follows:

Change the line (85) that reads:
```javascript
this.menu = new MyMenu(this, orientation);
```

To this:
```javascript
this.menu = new Applet.AppletPopupMenu(this, orientation);
```

And restart Cinnamon.

Ping to the applet author: @dmo60

**Comment by szekeres2016** [comment]
It worked! Thank you!
