### ISSUE TITLE
gmail@lauritsriple : Not working on Linux Mint 19.1

### ISSUE THREAD

**Issue by basilky** [linuxmint/cinnamon-spices-applets#2453]
```
 * Applet version : 5a0e6b44
 * Cinnamon version : 4.0.10
 * Distribution - Mint 19.1
 * Graphics hardware - Intel Integrated Graphics

 ```

**Notify author of applet**
@lauritsriple

**Issue**

Following message is shown after adding applet to the panel. I have installed all the required dependencies and given correct gmail username and password. I have checked active internet connection also.
![applet](https://user-images.githubusercontent.com/22705230/59578065-14f42a80-90e4-11e9-9ee4-78d7b61fc586.jpg)

**Comment by lauritsriple** [comment]
I am working on a new release with better error handling, but for now, could you try to run `seahorse` and see if your username and password has been added to the keyring? They should be under the default keyring with the description: mailnotifier. You can filter/search for this inside seahorse.

This error comes from the python script (getGmailFeedJson.py) either finding a blank or no password from the keyring or it fails later when it attempts to do the HTTP request. You can run this script manually to test correct username/password after changing the applet settings with `~/.local/share/cinnamon/applets/gmail@lauritsriple/getGmailFeedJson.py yourusername` . Note that the error output is not as descriptive as it should be, but a new release is coming shortly.

If you have 2-step verification enabled follow the steps in the [readme](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/gmail%40lauritsriple/README.md) that was recently updated by @smurphos (Thank you)

From the readme:  _You might have to enable access for less secure apps in gmail_. Test in your browser if you have access with one of these links. https://mail.google.com/mail/feed/atom or https://username:password@mail.google.com/mail/feed/atom

Enabling access for less secure apps can be done here: https://myaccount.google.com/u/0/lesssecureapps

Let me know how it goes.

**Comment by basilky** [comment]
I have enabled access for less secure apps and the issue is still there. I have checked seahorse and my Gmail username and password is available under the default keyring. I have installed the dependencies using apt and not using pip3. Does this create any issue?

**Comment by lauritsriple** [comment]
I can't think of any issues that can come of installed via apt instead of pip.

Which version of the python libraries are you using?

Can you provide python version of your default python?
`python --version`
Hopefully you will get output version which is python3, e.g python 3.7.3

Try the following to see that python can retrieve your password (change yourgmailusername to your gmail username. The part before @gmail.com):
python -c "import keyring; print(keyring.get_password('mailnotifier','yourgmailusername'))"

Please try:
`~/.local/share/cinnamon/applets/gmail@lauritsriple/getGmailFeedJson.py yourgmailusername`
It should output a json message with either an error or the unread emails in your gmail inbox.

**Comment by basilky** [comment]
`python --version` gives `Python 2.7.15+`

Python 3 is also installed on my system and I can access it via `python3` command.

`python3 --version` gives `Python 3.6.8`

I think both versions are installed on Ubuntu 18.04 and I have to use `python3` to use python 3.

`python -c "import keyring; print(keyring.get_password('mailnotifier','mygmailusername'))"` gives following error

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named keyring`

and
`python3 -c "import keyring; print(keyring.get_password('mailnotifier','mygmailusername'))"`  gives my password as output.

I also request you to consider Oauth2 authentication so that users don't have to enable "Less Secure Apps Access" on their Google account.

**Comment by lauritsriple** [comment]
I just tried from a fresh install. Ran the following after the install:
`sudo apt-get install python3 python3-keyring python3-feedparser`

Then I installed the applet, added my username and password. Created a keyring when prompted, and it seems to be working.

Mint 19.1
Cinnamon 4.0.8
Linux 4.15.0.20-generic

I am considering to change to Oauth2.

Please try:
`~/.local/share/cinnamon/applets/gmail@lauritsriple/getGmailFeedJson.py yourgmailusername`
It should output a json message containing your emails.

**Comment by basilky** [comment]
`~/.local/share/cinnamon/applets/gmail@lauritsriple/getGmailFeedJson.py gmailusername`

gives the following error

`{"info": "Search the web or create issue on git", "error": "Python can't import FancyURLopener from urllib.request"}`

**Comment by basilky** [comment]
Found the cause of this issue. My Gmail password contained a question mark and this was causing issues with feedparser. I have changed my password and the extension is working fine now.
