### ISSUE TITLE
sticky@scollins: High CPU usage

### ISSUE THREAD

**Issue by basilky** [linuxmint/cinnamon-spices-applets#2454]
```
 * Applet version : 5a0e6b44
 * Cinnamon version : 4.0.10
 * Distribution - Mint 19.1
 * Graphics hardware - Intel Integrated Graphics

 ```

**Notify author of applet**
@scollins 

High CPU usage when "show shadow behind notes" option is turned on, and notes are visible. This is the CPU usage before enabling this option.
![Screenshot from 2019-06-17 09-53-47](https://user-images.githubusercontent.com/22705230/59578498-10307600-90e6-11e9-97d4-bc6a80fecc00.png)

This is the CPU usage when the option is enabled. Whole desktop feels slow after this option is enabled. 
![Screenshot from 2019-06-17 09-55-02](https://user-images.githubusercontent.com/22705230/59578501-13c3fd00-90e6-11e9-80c9-3ea600c768ee.png)

**Comment by collinss** [comment]
This is a known issue (please note that there is a tooltip for that setting explaining the issue). Unfortunately, there isn't much that can be done to fix the issue in the applet itself. It seems to be a problem with the toolkit and that is outside the scope of this project.
