### ISSUE TITLE
weather@mockturtl: Extension is not compatible with current Cinnamon version

### ISSUE THREAD

**Issue by alicavus** [linuxmint/cinnamon-spices-applets#2465]
```
applet version: 2.2.0
build date: 1558644894 23/05/2019 16:54 (UTC)
cinnamon version: 4.2.0
distrubution: Arch Linux
hardware: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller
driver: mesa; xf86-video-intel
 ```

**Notify author of applet**
@mockturtl 

**Issue**
weather extension is not loading after last system update (pacman -Syyu)

**Steps to reproduce**
Load Cinnamon 4.2.0 and Install the latest version of weather applet if not is installed yet

**Expected behaviour**
Working extension that shows current weather
[lg.log](https://github.com/linuxmint/cinnamon-spices-applets/files/3344950/lg.log)
[xsession-errors.log](https://github.com/linuxmint/cinnamon-spices-applets/files/3344953/xsession-errors.log)

**Other information**

**Comment by Gr3q** [comment]
Yeah, I forgot to include 4.2 as a supported version.

I have a pr open with that, I'll bump the version number on it as well

**Comment by mockturtl** [comment]
Thank you both!
