### ISSUE TITLE
temperature@fevimu incompatible with Cinnamon 4.2

### ISSUE THREAD

**Issue by Zerophase** [linuxmint/cinnamon-spices-applets#2467]
```
 * 2019-02-11, 22:08 UTC
 * Cinnamon version: 4.2
 * Distribution: Arch Linux
 * Nvidia 430.26
 * [glass.log](https://pastebin.com/8VHMBQiR)
 * [.xsession-errors](https://pastebin.com/6hGJJ8s0)

 ```

**Notify author of applet**
@jaszhix 

**Issue**
After updating to 4.2 CPU Temperature Indicator no longer loads.

**Steps to reproduce**
1. Upgrade to Cinnamon 4.2
2. Install CPU Temperature Indicator
3. logout and back in
4. Receive error message about applets failing to load. 

**Expected behaviour**
Applet loads

**Other information**
Also applies to multicore-sys-monitor@ccadeptic23, and weather@mockturtl.

**Comment by schinfo** [comment]
vpnLookOut@claudiux has the same problem with Cinnamon 4.2

**Comment by D1ceWard** [comment]
I added `4.2` version to cinnamon-version in `metadata.json`, seems to work fine. Pull request coming
```json
{
    "uuid": "temperature@fevimu",
    "name": "CPU Temperature Indicator",
    "description": "Shows CPU Temperature",
    "cinnamon-version": [
        "3.6",
        "3.8",
        "4.0",
        "4.2"
    ],
    "last-edited": 1542120515
}
```

**Comment by claudiux** [comment]
@brownsr @Zerophase  Can you close this issue, please?
