### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: Extension is not compatible with current Cinnamon version

### ISSUE THREAD

**Issue by couraudt** [linuxmint/cinnamon-spices-applets#2470]
```
 * Applet version/Build date: 1.8.7
 * Cinnamon version: Cinnamon 4.2.0
 * Distribution: Arch
 ```

**Notify author of applet**
@ccadeptic23

**Issue**

 extension is not loading after last system update (pacman -Syyu)

```
error t=2019-07-03T11:47:34Z [multicore-sys-monitor@ccadeptic23]: Extension is not compatible with current Cinnamon version
trace t=2019-07-03T11:47:34Z 
<----------------
logError@/usr/share/cinnamon/js/ui/extension.js:134:17
Extension.prototype.validateMetaData@/usr/share/cinnamon/js/ui/extension.js:322:19
Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:242:17
---------------->
```

**Steps to reproduce**

 Load Cinnamon 4.2.0 and Install the latest version of weather applet if not is installed yet

**Expected behaviour**

 Working extension that shows monitor in taskbar

**Other information**

Just add new cinnamon version 4.2 into the `metadata.json`

Thanks!

**Comment by odelucca** [comment]
Same issue happens on the Cinnamenu applet.
