### ISSUE TITLE
Make sure metadata last-edited is consistent

### ISSUE THREAD

**Issue by ccprog** [linuxmint/cinnamon-spices-applets#25]
I am raising this here, although this is really an issue with the spices deployment process - no idea where else this should go.

Currently, the `last-edited` entry in metadata.json is not touched when the download .zip is generated, while the entry in the website's `/json/applet.json` is updated. As a consequence, an applet downloaded and installed by hand will be immediately shown as as updatable. (see http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/#comment-349828)

**Comment by NikoKrause** [comment]
@ccprog 
I think this issue should be better reporter here https://github.com/clefebvre/cinnamon-spices
Not totally sure though.
