### ISSUE TITLE
[text-to-speech-applet@cardsurf] Please give support for espeak-ng engine

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-applets#2500]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version: 4.0.10
 * Distribution: Fedora 30
 * Graphics hardware *and* driver used: Hybrid VGA (Intel Corporation HD Graphic 5500 + Radeon R7 M265 2GB)
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**

@cardsurf 

**Issue**

Hi. I'm a Fedora Linux user. I use Fedora Linux 30 X64 bit Cinnamon edition. I installed your applet & activated it, but it show me error message said what mean:

"There is missed package. Please install espeak package"

Dears, on Fedora 30, espeak is not used by default & it is already replaced by new tts engine which is "espeak-ng" that it's repository is:
https://github.com/espeak-ng/espeak-ng

Please can you, kindly, give support for espeak-ng engine ? Currently the applet does not appear in Cinnamon panel at all, inspite of activating it !

**Steps to reproduce**

Install applet on Fedora, then activate it.

**Expected behaviour**

Applet should appear in Cinnamon panel & work with tts engine other than espeak, like espeak-ng

**Other information**

I already opened this issue in original repository of this applet:
https://gitlab.com/cardsurf/text-to-speech-applet/issues/1

**Comment by Nokia808** [comment]
Hi. Great work ! I receive new version & I changed the command from:
"espeak -ven+m5 -a 100 -p 50 -s 175" (the default command) into:
"espeak-ng -ven+m5 -a 100 -p 50 -s 175" & it worked !

Just if you can help me further: does what I did by change espeak" to "espeak-ng" is correct ? What about other parameters: "-ven+m5 -a 100 -p 50 -s 175" ? Leave them without change ? Are they compatible with espeak-ng or some of them need modifications ? 
 
I have no experience with enspeak or enspeak-ng command line options & this is the 1st time to me to use TTS utility on Linux ........

**Comment by cardsurf** [comment]
@Nokia808 Changing from `espeak` to `espeak-ng` is enough. According to [`espeak-ng` project README.md](https://github.com/espeak-ng/espeak-ng#espeak-compatibility) file the command line arguments are compatible with `espeak` command:
> The espeak-ng binaries use the same command-line options as espeak, with several additions to provide new functionality from espeak-ng such as specifying the output audio device name to use.
