### ISSUE TITLE
batterymonitor@pdcurtis: applet doesn't track the battery when I switched to another user

### ISSUE THREAD

**Issue by VijitCoder** [linuxmint/cinnamon-spices-applets#2502]
* Applet version/Build date 1.3.7 2019-04-14
* Cinnamon version 4.0.10
* Distribution - Mint 19.1

**Notify author of applet**

@pdcurtis

**Issue**

Applet doesn't track the battery at all, when I switched to another user.

![Screenshot from 2019-08-02 23-28-04](https://user-images.githubusercontent.com/8523131/62386791-09b96900-b583-11e9-9a3a-2e077fd03f97.png)

_On the screenshot above: the real state of the battery and what shows the applet._

**Steps to reproduce**

1. Login as the user First. Setup applet, unplug the power. Applet tracks battery discharging.
2. Switch to user Second. Applet already setup and worked well earlier there. But now it doesn't track the battery.
3. After some time switch back to the First user. Battery info correctly updated.
4. Switch again go user Second. Voila! Battery info updated but still not tracked.

**Expected behaviour**

Battery info should tracked for all simultaneously logged users.

**Other information**

This strange behavior fixes only after reboot, but only for the first logged user.

**Comment by pdcurtis** [comment]
This strange behaviour had a simple cause. I was using two temporary files in /tmp which had the wrong permissions when switching users. I have now moved them to the home folder so each applet is totally independent. 

I have always logged out then into a new user so I missed it - I have never trusted switching with encrypted folders but you forced me to test it out!

NOTE: you will need to update the applet for each user to version 1.3.8 when the PR is accepted and it  will then also work under cinnamon 4.2

@VijitCoder  Thanks for spotting this.
