### ISSUE TITLE
Battery Applet with Monitoring and Shutdown (BAMS): Add an indicator for when the laptop is charging

### ISSUE THREAD

**Issue by mscheper** [linuxmint/cinnamon-spices-applets#251]
I just switched to BAMS, because I wasn't receiving sufficient warnings for my laptop running out of juice.

The one advantage my previous battery monitor app had was that it showed when the laptop was charging. Unfortunately, my laptop doesn't come with a power LED (it's actually missing a lot of LEDs—stupid that a $2000 laptop couldn't splurge out on a couple of ½c LEDs!) so this is a pretty essential feature. I hope @AppletAuthor will consider adding it.

**Comment by NikoKrause** [comment]
The spices website https://cinnamon-spices.linuxmint.com/applets/view/255 says by pdcurtis. So its not @AppletAuthor but @pdcurtis.

**Comment by pdcurtis** [comment]
@mscheper The background colour of the applet already gave a quick indication of the state of charge and I am planning to enhance that by adding a red border to the 'normal' green background when it is discharging and above the alert level. 

The applet will now show the percentage charge on a coloured background which is:

  * Green when above the alert level (set currently to 1.5 times the 'shutdown' level.)
  * Green has Red Border when discharging (Added in version v32_1.0.0)
  * Orange between the warning and shutdown level
  * Red and flashing at and below the Shutdown level (even when charging).

   When the battery is Discharging the warning and shutdown regions also have a much larger flashing message in the applet which is difficult to miss. 
 
I am also making some other enhancements including:

  -  Adding a short fixed audible alert as well as a modal alert when the Alert Level is reached  which has been requested by @diviney.

The new version will remain under test on my machines for a few days before being made available.

@NikoKrause I am also thinking about adding translation support - can you assist if required with implementation and a German translation in due course?

**Comment by pdcurtis** [comment]
@mscheper I am glad you are happy with the change. 

Can you or @NikoKrause  close this issue now that the feature is included in the applet and is available from the Spices web site.
