### ISSUE TITLE
[text-to-speech-applet@cardsurf] 2 time clicks on hot key for "Reading" needed to work after "Pause" hot key clicking

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-applets#2519]
```
 * Applet version/Build date: 1.3.0
 * Cinnamon version: 4.2.2
 * Distribution: Fedora 30 X 64 bit
 * Graphics hardware *and* driver used: Hybrid VGA (Intel Corporation HD Graphic 5500 + Radeon R7 M265 2GB)
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@cardsurf

**Issue**
I assigned F1 key as a "Pause" hot key & F3 as a "Reading" hot key. 
"Pause" key working without problem. 
"Reading" key work without problem if I use it WITHOUT privious use of "Pause" key - just one click on F3 & applet start to work & read okay.
But if I use "Pause" key (in my case F1), then click "Reading" key (F3) the F3 will not work to activate reading till click it a 2nd click !

**Expected behaviour**
It should be always enough to click one time on "Reading" key to make activate reading.

**Comment by cardsurf** [comment]
@Nokia808  Sounds like a good suggestion. I will take a look at it this week.

**Comment by Nokia808** [comment]
Hi. I received new version & test it. The issue is still existing & not fixed yet ! Please re-open this issue.
Best.

**Comment by cardsurf** [comment]
@Nokia808 It's working as expected on my system. Can you check what version of applet do you have installed ? To check the version right click on the applet and choose `About` from the context menu.

**Comment by Nokia808** [comment]
@cardsurf 
Sorry for this error, it is still 1.3.0 ! It seem that I received update for other applet (or theme) & confused it with this !
