### ISSUE TITLE
color-picker@fmete: Dialogue does not appear

### ISSUE THREAD

**Issue by mscheper** [linuxmint/cinnamon-spices-applets#252]
I've never managed to get 'Color Picker' to work. When I click the icon, the cursor constantly becomes an arrow, so it seems to be active, but when I click something, I don't see a colour information window.

I'm running Cinnamon 2.6.13 under Mint 17.2, but I haven't seen it work in previous releases, either.

The dependencies are installed:
> python-xlib:all/trusty-updates 0.14+20091101-1ubuntu3~trusty uptodate
> xsel:amd64/trusty 1.2.0-2 uptodate

What else can I check?

**Comment by NikoKrause** [comment]
The description says

> Click applet, after click a pixel, its color automatically copied clipboard.
Required Packages: `sudo apt-get install xsel python-xlib`

Install the packages, choose a color with the applet, then open a text editor, rightclick, paste.
The colorcode should appear.

**Comment by mscheper** [comment]
My comment says:

> **The dependencies are installed**:
>
> > python-xlib:all/trusty-updates 0.14+20091101-1ubuntu3~trusty uptodate
> > xsel:amd64/trusty 1.2.0-2 uptodate

I _did_ install the dependencies.

The [screenshot](https://cinnamon-spices.linuxmint.com/git/applets/color-picker@fmete/screenshot.png), however, did mislead me into expecting a dialogue, so thanks for that clarification.

But it's still not working. When I click the applet, and then click somewhere on the screen, it updates neither the select buffer nor the clipboard.

What else can I check?

**Comment by mscheper** [comment]
Ah, I've worked out what's going on. For it to work, I need to do one of two things:

1. Click the applet _before_ the mouseover/tooltip appears ('Click here to pick a color'). In other words, click the applet within about 250ms of moving the mouse over it.
2. If I don't click quickly enough, before the tooltip appears, I need to click three more times: once to get rid of the tool tip, once for the applet to see, and once to select the colour. _However_, I need to move the mouse cursor slightly before that second click; if I don't, it just won't work.

I would call this a bug, a frustrating one that's prevented me from being able to use this applet for years.

Let me know if I can provide more info.

**Comment by NikoKrause** [comment]
Try this:
1. Open the applet.js file of the applet:
```
xed ~/.local/share/cinnamon/applets/color-picker@fmete/applet.js 
```
2. Remove line 66:
```
this.set_applet_tooltip(_("click here to pick a color"));
```
3. Save and restart Cinnamon.

This will remove the tooltip.

**Comment by NikoKrause** [comment]
@mscheper
Does this workaround fix your issue?
If yes, I would create a pull request to solve it generally.
