### ISSUE TITLE
configure to monitor wireguard connection

### ISSUE THREAD

**Issue by leonzon** [linuxmint/cinnamon-spices-applets#2520]
is it possible to configure to monitor a wireguard vpn?
thank you

**Comment by claudiux** [comment]
Hi @leonzon,

Please, when you open an issue, mention the author in the message (@claudiux for me) and write the name of the applet in the title, as : `[vpnLookOut@claudiux] configure to monitor wireguard connection`.

This applet uses NetworkManager to manage connections. Mint 19.2 contains a version of NetworkManager (1.10.14) that does not support wireguard connections.

A plugin has been developed: https://git.ukamnya.ru/mirror/network-manager-wireguard-upstream. I did not test it.

Regards.
Claudiux

**Comment by leonzon** [comment]
Hithank you for replying. In future I will use that methoed of contact.I will try out that applet.Peter

    On Monday, August 5, 2019, 10:35:05 PM GMT+1, claudiux <notifications@github.com> wrote:  
 
 
Hi @leonzon,

Please, when you open an issue, mention the author in the message (@claudiux for me) and write the name of the applet in the title, as : [vpnLookOut@claudiux] configure to monitor wireguard connection.

This applet uses NetworkManager to manage connections. Mint 19.2 contains a version of NetworkManager (1.10.14) that does not support wireguard connections.

A plugin has been developed: https://git.ukamnya.ru/mirror/network-manager-wireguard-upstream. I did not test it.

Regards.
Claudiux

**Comment by claudiux** [comment]
Hi @leonzon,

Finally this issue concerns NetworkManager, but not this applet. Can you close it, please?

Regards.
Claudiux
