### ISSUE TITLE
[IcingTaskManager@json] Need to add support for Linux Mint 19.2 tina

### ISSUE THREAD

**Issue by mubat** [linuxmint/cinnamon-spices-applets#2531]
```
 * Applet version/Build date: 6.3.14
 * Cinnamon version: Cinnamon 4.2.3
 * Distribution: Linux Mint 19.2
 ```
@jaszhix, сan't use applet on Linux Mint 19.2

**Comment by okaestne** [comment]
Is there a reason that you are not using the default "grouped window list" applet (a fork from ITM with lots of improvements by Mint)?

**Comment by mubat** [comment]
@okaestne no, there is not. 
I used IcingTaskManager instead of default manager because it has <Super> shortcuts support. Maybe default applet didn't support them earlier, so I used IcingTaskManager.
Thank you for enlighten me.
