### ISSUE TITLE
Finnish translation attached

### ISSUE THREAD

**Issue by mahtiankka** [linuxmint/cinnamon-spices-applets#2536]
Finnish translation fi.po attached. I hope it is available.
![suomi](https://user-images.githubusercontent.com/48694735/63227621-006e0480-c1f1-11e9-948d-c8b8efc84713.png)
[fi.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/3513305/fi.po.zip)

 * Cinnamon version (Cinnamon 4.2.3)
 * Distribution - (Mint 19.2)

**Comment by claudiux** [comment]
Hi @mahtiankka,

Thank you for your Finnish translation of Spices Update messages!

You can open a PR (Pull Request) to propose it. Here a How-To: https://github.com/claudiux/docs/blob/master/HOW_TO_MAKE_A_CLEAN_REFORK.md

If you prefer, I can use you fi.po file to make myself a PR.

Regards.
Claudiux

**Comment by claudiux** [comment]
@mahtiankka I see you do not have a fork of cinnamon-spices-applets. You can use this Github method:

- Fork https://github.com/linuxmint/cinnamon-spices-applets
- In your fork, create a branch from the master one that you name `SpicesUpdate-fi`.
- In this branch, go into `SpicesUpdate@claudiux / files / SpicesUpdate@claudiux / po`.
- Add your file `fi.po` (not the zip file) and submit it with the Comment: `[SpicesUpdate@claudiux] - Finnish translation`.
- Return to the root of your branch then make a Pull Request.
