### ISSUE TITLE
Terminal window won't open

### ISSUE THREAD

**Issue by dikonov** [linuxmint/cinnamon-spices-applets#2539]
I configured .ssh/config and can see the hosts in the menu. The hosts are up and I can connect by using ssh XXX command. Key auth is set in ssh, so I do not have to enter passwords. Gnome-terminal is installed and runs fine.

However, when I select a host in the applet menu, no terminal window opens. Is there a setting to select, what application should be run?

```
 * Applet version/Build date 2019-01-22
 * Cinnamon version Cinnamon 4.0.9
 * Distribution - ALTLinux
 * Graphics hardware AMD Whistler, radeonfree
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors - Nothing related there

 ```

**Notify author of applet**
@

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
@dikonov what Cinnamon Spices applet is this in reference to?

**Comment by dikonov** [comment]
This bug is outdated. I use 
https://cinnamon-spices.linuxmint.com/applets/view/317
and currently, after many updates, it works fine.

**Comment by dikonov** [comment]
I have no idea what "Cinnamon Spices" refers to.
