### ISSUE TITLE
[SpicesUpdate@claudiux] - fails to import Cinnamon 3.6.x

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon-spices-applets#2545]
@claudiux 

Apologies for the incomplete report. I'm raising this on behalf of a non GitHub using Mint forum member and am away from home at the moment so not able to test/reproduce myself.

The user who is on Mint 18.3 is suffering an import error following a recent update to the applet

https://forums.linuxmint.com/viewtopic.php?p=1676730&sid=aebd7d1c0de5642e110abad97dbca1e5#p1676730

**Comment by claudiux** [comment]
Thank you @smurphos. I will check this bug.

**Comment by claudiux** [comment]
Bug found!!! Just a typo! Grrr.

I will make immediately a new PR.

While waiting for the next update, completely uninstall the applet, then reload it and **before installation** change the line 1050 of the file ~/.local/share/cinnamon/applets/SpicesUpdate@claudiux/2.8/applet.js
from:
`  }; // End of check_dependencies`
to:
`  }, // End of check_dependencies`

Then, install Spices Update on the panel. It works!

Just a semicolon to change to a comma! Stupid mistake!
