### ISSUE TITLE
weather@mockturtl: update sr.po

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon-spices-applets#2551]

**Comment by Gr3q** [comment]
Hello, if you could fill out the translation file it would be greatly appreciated.

The File is located here
https://raw.githubusercontent.com/linuxmint/cinnamon-spices-applets/master/weather%40mockturtl/files/weather%40mockturtl/po/weather%40mockturtl.pot

(just fill out the "msgstr" fields)

If you are not comfortable to create a Pull Request, you can send the ready file to me on floyd0122@gmail.com, or post the contents of the file as a comment here.

**Comment by Knezev** [comment]
i no see applet 
![Снимак екрана од 2019-10-06 16-45-40](https://user-images.githubusercontent.com/38316957/66270902-c6b49400-e858-11e9-8919-b9db520200e7.png)
![Снимак екрана од 2019-10-06 16-45-30](https://user-images.githubusercontent.com/38316957/66270903-cb794800-e858-11e9-8e79-f1bbcf216b11.png)

**Comment by Gr3q** [comment]
Try deleting and installing the app again

**Comment by Knezev** [comment]
I tried, still can't, so i took it with github, works but stayed in english
![Снимак екрана од 2019-10-06 19-22-48](https://user-images.githubusercontent.com/38316957/66272839-d50daa80-e86e-11e9-9c44-804a9cf86e8c.png)

**Comment by Gr3q** [comment]
You need to install the translations.

If you cloned this repo, open a terminal:
```
cd <path/to/cinnamon-spices-applets>
./cinnamon-spices-makepot weather@mockturtl --install
```

This will install the new translations. Then restart cinnamon _(or your computer)_
