### ISSUE TITLE
[disk-read-and-write-speed@cardsurf] Shows always 0B with kernel 5.x

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-spices-applets#2589]
* Applet version 1.0.1
 * Cinnamon version 4.2.4
 * Distribution - Mint 19.2
 * Snippet or attachment of ~/.cinnamon/glass.log
number.toFixed is not a function

**Notify author of applet**
@cardsurf

**Issue**
- When using kernel 5.0.0.29-generic or 5.3.0-050300 the applet always shows 0B for up- and download.
- Looking glass log lists "number.toFixed is not a function".

**Steps to reproduce**
Use applet

**Expected behaviour**
Should work like with kernels 4.x

**Other information**
I managed to get rid of the error using
"(parseInt(number * 100) / 100).toFixed" instead of "number.toFixed"
(several times in applet.js). That works with kernel 4.x and 5.x.
But there's still an error in the mouse-over summary with the 5.x kernels (always 0B). I don't know how to fix that. There's no additional error in looking glass.

**Comment by cardsurf** [comment]
The issue is related to changes in [diskstats](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats) file format in Kernel 4.18+. 
I will work to add support of it this week.

**Comment by Mintulix** [comment]
Great, thank you!

**Comment by cardsurf** [comment]
I have added support for kernel 4.18+ in version 1.1.0 through the [pull request](https://github.com/linuxmint/cinnamon-spices-applets/pull/2595).

**Comment by Nitrooo** [comment]
I still get 0B on kernel 5.0.0-29 and disk-read-and-write-speed version 1.0.1 ("Last modified: 2019-09-28 12:13 UTC").

**Comment by Mintulix** [comment]
@ Nitrooo The fix is merged but still not delivered, so you have to wait a while.
Version 1.0.1 is the old one

**Comment by Nitrooo** [comment]
Oh ok, I've updated the applet today and I thought it already included the 4.18+ fix.
Sorry. :)

**Comment by claudiux** [comment]
You can use Spices Update to get the latest version of this applet (and all other Spices): https://cinnamon-spices.linuxmint.com/applets/view/309

**Comment by Nitrooo** [comment]
@claudiux I already use and love it. Thank you :)

**Comment by Mintulix** [comment]
Perfectly fixed with version 1.1.0, thank you.
The settings have to be reset, otherwise you have doubled entries (Read and Written) in the tooltip.
Or fix it by hand: old setting for Columns was 2,14,15 - now it's just 2.
