### ISSUE TITLE
places-with-terminal@mtwebster

### ISSUE THREAD

**Issue by Beckfield** [linuxmint/cinnamon-spices-applets#2597]
```
 * Applet version/Build date: 2017-09-24, 20:34 UTC
 * Cinnamon version: 4.2.4
 * Distribution - 
[glass.log](https://github.com/linuxmint/cinnamon-spices-applets/files/3665685/glass.log)
[logs.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/3665692/logs.zip)


Mint 19.2
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

 No assigned author

**Notify author of applet**
@

**Issue**
The 'File System' command in this applet won't launch Nemo in Linux Mint 19, because it's trying to use the 'gksudo' command.  That app was removed from Mint and at least some other Debian-based distros because it opens security risks.  It also has been unmaintained for years.

There's no reason this applet should be trying to launch the file browser with elevated privileges anyway. This is the only command on the applet that does so, and it doesn't mention that it is doing so. 

**Steps to reproduce**
Launch 'File System' command from the applet.

**Expected behaviour**
Terminal opened to File System.

**Other information**

**Comment by NikoKrause** [comment]
@mtwebster
