### ISSUE TITLE
Icing Task Manager: Unable to use with LibreOffice

### ISSUE THREAD

**Issue by Sven71** [linuxmint/cinnamon-spices-applets#26]
OS: Linux Mint Cinnamon 18 and 18.1
When opening an existing LibreOffice document and minimising it to taskbar or swiching to another task, the  icon dissapears or, if pinned to taskbar, just sits there as if no doc is in use, rendering the user unable to restore window. Only reappears (sort of) after opening a blank document.

**Comment by jaszhix** [comment]
Can you pastebin the contents of ```~/.cinnamon/configs/IcingTaskManager@json/*.json```?

**Comment by Sven71** [comment]
[17.json.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/732031/17.json.txt)

**Comment by jaszhix** [comment]
I'm not able to reproduce this.

**Comment by Sven71** [comment]
Happens to me every time, on two different computers.

**Comment by jaszhix** [comment]
What theme are you using?

**Comment by Sven71** [comment]
Tried with generic Cinnamon, Mint, Loki, Windows 10 Light etc., still the same

**Comment by jaszhix** [comment]
I'm just going to paste the contents of the issue template for ITM's [dedicated repository](https://github.com/jaszhix/icingtaskmanager) (which I prefer users post issues on as mentioned in the readme on Spices):

If this issue is a bug report, you must list your: 

  - Cinnamon version
  - Extension version
  - Linux distribution
  - Pastbin the outputs of:
    - ~/.cinnamon/configs/IcingTaskManager@json/*.json
    - ~/.cinnamon/glass.log
    - ~/.xsession-errors
  - Describe the steps needed to be taken in order to reproduce this bug.

**Comment by Piiit** [comment]
I had the very same problem, but I am currently not able to reproduce it. However, it shows up once in a while...

**Comment by jaszhix** [comment]
@Sven71 If you could provide the output of ```glass.log``` and ```.xsession-errors``` files when this occurs with LibreOffice, it might give me a better hint at what part of the code to look at.

**Comment by Sven71** [comment]
Sorry, already erased Mint from my computer :( Have to work, You see, too little time to tinker around when having deadlines to consider.
I remembered same thing indeed used to happen to me when using the original "Task manager with app grouping." At the same time it DIDN'T happen when using Redux's version, which was based on the same thing (with its own quite severe issues though) so perhaps You could see into that. Just my .02 cents, I know You're doing Your best.

**Comment by jaszhix** [comment]
That's too bad. If you ever have spare time with a second machine or VM, feel free to follow up when the pressure is off.

**Comment by Piiit** [comment]
@jaszhix It happened to me a minute ago.

glass.log does not show anything, but the .xsession-errors tail is as follows:
```
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x55ba0d065f70  Text: 0
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3e00029 (*Arbeitsfl)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x580001d (South Tyro)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3e00029 (*South Tyr)
Window manager warning: Log level 8: meta_frames_get_borders: assertion 'type < META_FRAME_TYPE_LAST' failed
Window manager warning: Log level 16: STACK_OP_RAISE_ABOVE: sibling window 0x5087601 not in stack
Window manager warning: Log level 8: meta_frames_get_borders: assertion 'type < META_FRAME_TYPE_LAST' failed
Window manager warning: Log level 8: meta_frames_get_borders: assertion 'type < META_FRAME_TYPE_LAST' failed
Window manager warning: Log level 16: STACK_OP_RAISE_ABOVE: sibling window 0x509337b not in stack

(cinnamon:30995): Cjs-WARNING **: JS ERROR: TypeError: this.metaWindowThumbnail is undefined
setStyleOptions@/home/pemoser/.local/share/cinnamon/applets/IcingTaskManager@json/specialMenus.js:935
_refresh/<@/home/pemoser/.local/share/cinnamon/applets/IcingTaskManager@json/specialMenus.js:885
setTimeout/<@/home/pemoser/.local/share/cinnamon/applets/IcingTaskManager@json/__init__.js:13


(cinnamon:30995): Cjs-WARNING **: JS ERROR: TypeError: this.metaWindowThumbnail is undefined
setStyleOptions@/home/pemoser/.local/share/cinnamon/applets/IcingTaskManager@json/specialMenus.js:935
_refresh/<@/home/pemoser/.local/share/cinnamon/applets/IcingTaskManager@json/specialMenus.js:885
setTimeout/<@/home/pemoser/.local/share/cinnamon/applets/IcingTaskManager@json/__init__.js:13

Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x55ba0d051b60  Text: 0
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x55ba0f60c3b0  Text: 0
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x55ba0fef5760  Text: 0
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x55ba0f42af90  Text: 0
```

**Comment by cloudscream** [comment]
Cinnamon version 3.2.7
Linux Mint 18.1 64-bit
Icing Task Manager 4.3.1

16.json: http://pastebin.com/iva5YzZz
glass.log: http://pastebin.com/jiERa6DR
.xsession-errors: http://pastebin.com/30jEP1jp

Two instances:
1. Open LibreOffice Writer/Impress/whatever from the menu and you get the normal response: Libreoffice opens and the process shows up in the window list. However, when you type some text and save it, the active Libreoffice window disappears in the window list.

2. Open a Libreoffice document. The program opens but it does not show up in the Icing Task Manager window list.

The "Windows List with App Grouping" extension do not exhibit the same problems.

**Comment by jaszhix** [comment]
I was finally able to reproduce it thanks to jeweloper's steps [here](https://github.com/jaszhix/icingtaskmanager/issues/92). The problem is depending on how LibreOffice is launched, it will duplicate the app ID, so the script cannot tell one window from another. No, the original fork does indeed have this problem, though it applied a workaround that didn't work reliably.

**Comment by tcmger** [comment]
I have similar problem but only regarding libreoffice base.
Opening an existing database, 2 windows will normaly appear in "database.odb", 1. the odb container window, 2. the preferred form- or table- (opened by macro).
Though libreoffice opens normally (2 windows), ice tea preview only shows the container window (1.)

May be it is a timing problem. If libreoffice opened I switch to to ice tea preferences changing e.g. the option "title" to "focus", the second window preview will be shown instantly.
