### ISSUE TITLE
[temperature@fevimu] add an option to hide the unit symbol

### ISSUE THREAD

**Issue by n-peugnet** [linuxmint/cinnamon-spices-applets#2633]
**Notify author of applet**
@jaszhix

**Feature request**

I use vertical panels and I wish this applet could only use one line. I thought that it could be a good idea to add an option to hide the unit symbol. Indeed, once it is set as Celsius or Fahrenheit it is not really a necessary information.

![systray](https://user-images.githubusercontent.com/23519418/66866588-e4d96d00-ef99-11e9-9848-e752be69be4f.png)

Maybe the `°` symbol could stay if it can fit one line, I am not sure what would be the best behavior.

**Comment by leplastic** [comment]
If you know your way with JavaScript, maybe you can try to develop the functionality by yourself and submit a pull request. Right now the units are hardcoded as "ºC" and "ºF" as you can see here:

https://github.com/linuxmint/cinnamon-spices-applets/blob/731cdece6bd4b09b7e64d02f9ad90ec2cb1ddbee/temperature@fevimu/files/temperature@fevimu/applet.js#L353-L361

Typically the requests are approved within a few days, but even if it's not the case, you still have a customized version for your use case.

**Comment by claudiux** [comment]
@n-peugnet Feature added in #2647.
