### ISSUE TITLE
Cinnamenu@json: on typing show exact matches first

### ISSUE THREAD

**Issue by vitaliis** [linuxmint/cinnamon-spices-applets#2635]
```
 * Applet version: 4.1.3
 * Cinnamon version: 4.2.4
 * Distribution - Mint 19
 ```

@jaszhix thank you for such a great applet!

**Issue**
This is a great feature of this applet to be able to find application even if you skip a symbol or have a partial match in the middle of the name. However usability could be greatly improved, if apps that contain exact matches would be displayed first. 

**Steps to reproduce**
Typing "code" in Cinnamenu search field results in various other matches first, like "ac**co**unt **de**tails", "next**c**l**o**ud **de**sktop", etc. And "Visual Studio Code" appearing somewhere in the middle of the list.

**Expected behaviour**
Apps that contain the given substring appear first in the list. Then all the other partial smart matches.

**Comment by jaszhix2** [comment]
@jaszhix won't receive your notifications because that account has been banned since June. I cannot work on this because of that.
