### ISSUE TITLE
Force Quit applet causes Cinnamon to crash in Linux Mint 19.2

### ISSUE THREAD

**Issue by papioara** [linuxmint/cinnamon-spices-applets#2652]
force-quit@cinnamon.org
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version) 4.2.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.2
 * Graphics hardware *and* driver used Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics driver: i915 v: kernel bus ID: 00:02.0 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1200~60Hz 
           OpenGL: renderer: Mesa DRI Intel Haswell Desktop v: 4.5 Mesa 19.0.8 direct render: Yes 

 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@force-quit@cinnamon.org

**Issue**
Applet causes cinnamon crash when installing or removing a program regardless of installation method (mintupdate, command line, synaptic)

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
Cinnamon 4.4.8
Mint 19.3

I'm unable to reproduce this issue. Force-quit applet works as expected and does not cause Cinnamon to crash.

@papioara if you have upgraded Mint/Cinnamon, can you re-test this issue? Thanks.
