### ISSUE TITLE
cpufreq@mtwebster applet does not load

### ISSUE THREAD

**Issue by ahmadnassri** [linuxmint/cinnamon-spices-applets#2676]
```
 * Applet version: latest installed from Applets manager 
 * Cinnamon 4.2.4
 * Mint 19.2
 * Graphics hardware: Intel / modesetting
 ```

**Notify author of applet**
@mtwebster 

**Issue**

applet fails to load despite having all dependencies installed

**Steps to reproduce**

- install applet through Applets Manager UI
- add applet to panel
- applet prompt to install dependencies `apt-get install --no-install-recommends gnome-applets`
- install dependencies
- remove applet
- add applet to panel again
- no applet present on panel, upon further inspection, the applet is there, but is not displaying any info or responding to left click (screenshot below)

![image](https://user-images.githubusercontent.com/183195/68424692-85bee080-0172-11ea-840c-073b5c0ca463.png)

**Expected behaviour**

- display an error message if issues were found to prevent applet functionality
- applet should load with appropriate cpu info and controls

**Other information**

happy to provide logs / further data if instructed how to provide them / where to fetch them from

**Comment by ahmadnassri** [comment]
I figured out how to get the Melange to show some logs, this is all I see in relation to `cpufreq` applet loading with `trace` level enabled...

```
info t=2019-11-07T15:52:08Z Reloading applet: cpufreq@mtwebster/23
info t=2019-11-07T15:52:08Z Loaded applet cpufreq@mtwebster in 30 ms
info t=2019-11-07T15:52:38Z Reloading applet: cpufreq@mtwebster/23
info t=2019-11-07T15:52:38Z Loaded applet cpufreq@mtwebster in 68 ms
```

this shows me attempting to reload the applet twice, no further debug info is present

**Comment by Extarys** [comment]
Same issue, according to the comments on the page (https://cinnamon-spices.linuxmint.com/applets/view/70) it's been a while since it worked.
