### ISSUE TITLE
Recent documents applet ::: items moved or deleted unresponsive [Bug]

### ISSUE THREAD

**Issue by Sadi58** [linuxmint/cinnamon-spices-applets#2678]
```
 * Cinnamon version: 4.2.4
 * Distribution: Mint 19.2
 ```

**Issue**
When you click an item in the dropdown list of "Recent documents" applet, nothing happens if it was deleted or moved.

**Steps to reproduce**
1. Create a new empty document in Home directory, opening and typing some text and saving it.
2. Open the Recent Documents applet and check if it is listed and does open when you click it in the Recent Documents list.
3. Go to Home folder and delete that file.
4. Open the Recent Documents applet, which should still list it, doing nothing when you click it.

**Expected behaviour**
Ideally, deleted items should be automatically removed from the list, and moved items should be re-linked. If this is too demanding, at least a message should be displayed that it must have been deleted or moved, preferably providing the user an option to remove it from the list.

Thanks to @icarter09 for the advice to move this old bug report to this repo.

**Comment by icarter09** [comment]
@Sadi58 I reopened the old issue since I gave you some bad advice. Sorry about that.

**Comment by Sadi58** [comment]
@icarter09 No problem. I was also tired; ;-)
