### ISSUE TITLE
Spices Update: frequency field ignores value if it is too high

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon-spices-applets#2679]
[Instruction unclear]

```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") 5.0.0
 * Cinnamon version (cinnamon --version) 4.2.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.2
 * Graphics hardware *and* driver used: N.A.
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@claudiux

**Issue**

Frequency field ignores value if it is too high.

**Steps to reproduce**

Enter, say, '72' in the 'frequency' field (the field determining how frequent checks are).

**Expected behaviour**

Programs should actively reject values they dislike and give an explanation of why they are doing it.

**Other information**

**Comment by claudiux** [comment]
Hi @LinuxOnTheDesktop,

Is your session open permanently? The "Frequency" tooltip shows: "Please note that the first check will take place one minute after this applet starts."

Thus, one minute after the opening of your session, a first check is made. Then, the next check will take place 72 hours after this one, unless you close your session.

**Comment by LinuxOnTheDesktop** [comment]
> Is your session open permanently?

I am afraid that I am unsure what you mean. Anyhow, so far as I can tell, you miss my points. My point were/are as follows.

(1) If one changes a setting in such a way as to alter what should be checked for, then, if that change will - once it is applied - affect the number shown on the panel icon, then that number should be updated immediately. For, telling the program not to e.g. check for new desklets, and then have the program continue to show new desklets - that combination makes little sense.

(2) Your applet crashes Cinnamon when Cinnamon is restarted. That crash should not occur.

I apologise if I make some mistake.

**Comment by claudiux** [comment]
It seems me that your last comment concerns #2680.

**Comment by LinuxOnTheDesktop** [comment]
Ah yes, my mistake. I have deleted the mistaken comment.

Let me clarify the problem. If I enter '72' into the field at issue, and then close the window and re-open it, then the value is not retained. However, if I enter '24' instead, then the value is retained.

**Comment by claudiux** [comment]
OK. I see where is the problem.

Please check the contents of your `/.cinnamon/configs/SpicesUpdate@claudiux/SpicesUpdate@claudiux.json` file.

From line 650 have you that?
```
    "general_frequency": {
        "type": "spinbutton",
        "default": 1,
        "min": 1,
        "max": 720,
        "step": 1,
        "units": "hours",
        "description": "Time interval between two checks",
        "tooltip": "Please note that the first check will take place one minute after starting this applet.",
        "value": 72
    },
```

If the "max" value is set to 24, Cinnamon did not apply the changes to the `settings-schema.json` file in #2616 and I'll go to open an issue.

Please try to completely remove and then reinstall Spices Update. After deletion, the `~/.cinnamon/configs/SpicesUpdate@claudiux` folder should no longer exist. This folder will be recreated after the reinstallation.

**Comment by claudiux** [comment]
@LinuxOnTheDesktop I had the same bug by directly typing the frequency value instead of using the `+` and `-` widgets.

**Comment by claudiux** [comment]
Replacing this `spinbutton` widget by a `scale` one, this issue is solved.
