### ISSUE TITLE
Spices Update: applet fails to update the displayed count 

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon-spices-applets#2680]
[Instruction unclear]

```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") 5.0.0
 * Cinnamon version (cinnamon --version) 4.2.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.2
 * Graphics hardware *and* driver used: N.A.
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@claudiux

**Issue**

Unticking 'Let regularly check if new desklets are available' does not affect the displayed updateable/new-items count.

**Steps to reproduce**

Have there be >= 1 new desklet(s).
Have  'Let regularly check if new desklets are available' ticked.
Observe the number shown on the applet's icon.
Untick the aforementioned item.

**Expected behaviour**

Telling the program to ignore something should make the program ignore that thing immediately. Thus, if the applet shows the number '2' - because two new desklets are available - then that count should become zero, if and when I tell the applet to ignore new desklets.

**Other information**

I imagine that the problem extends beyond the particular case - namely, new desklets - that I mention.

EDIT: I restarted Cinnamon - to try to get the applet to refresh its count - and Cinnamon reported an error. The log has this:

```
[SpicesUpdate@claudiux]: Applet SpicesUpdate@claudiux: Could not create applet object.
[SpicesUpdate@claudiux]: Error importing applet.js from SpicesUpdate@claudiux
```
 'Let regularly check if new desklets are available' is poor English. Better would be: Check regularly whether new desklets are available.

**Comment by claudiux** [comment]
@LinuxOnTheDesktop,

Thank you for reporting these issues.

Can you post here the contents of your `~/.xsession-errors` file, please?

**Comment by claudiux** [comment]
@LinuxOnTheDesktop 

I made a bash script to unlock the SpicesUpdate starting.

The version 5.1.0 of this applet is here.

Please take a look at https://cinnamon-spices.linuxmint.com/applets/view/309#count.

**Comment by LinuxOnTheDesktop** [comment]
Thanks: that script made the applet work again.
