### ISSUE TITLE
SpicesUpdate fails to open

### ISSUE THREAD

**Issue by fluntelion** [linuxmint/cinnamon-spices-applets#2681]
Good evening, claudiux,

Is the following the interesting part of the .xsession-errors file?
If not, please tell me what else you need: fluntelion@protonmail.com

Kind regards,
fluntelion

_____________________________________________________________

Cjs-Message: 18:19:07.740: JS LOG: [LookingGlass/trace] 
<----------------
_rewrite_metadataFile@/home/name/.local/share/cinnamon/applets/SpicesUpdate@claudiux/4.2/applet.js:1153:24
populateSettingsUnprotectedThemes@/home/name/.local/share/cinnamon/applets/SpicesUpdate@claudiux/4.2/applet.js:913:13
SpicesUpdate@/home/name/.local/share/cinnamon/applets/SpicesUpdate@claudiux/4.2/applet.js:437:5
main@/home/name/.local/share/cinnamon/applets/SpicesUpdate@claudiux/4.2/applet.js:1906:10
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:581:18
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:356:22
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:95:14
Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:277:17
---------------->
Cjs-Message: 18:19:07.741: JS LOG: [LookingGlass/error] 
[SpicesUpdate@claudiux]: Applet SpicesUpdate@claudiux: Could not create applet object.
[SpicesUpdate@claudiux]: Error importing applet.js from SpicesUpdate@claudiux
Cjs-Message: 18:19:07.741: JS LOG: [LookingGlass/trace] 
<----------------

**Comment by claudiux** [comment]
Good evening, @fluntelion,

A very old theme is certainly present in your `~/.themes` folder.

Can you, using 'insert code', give me bellow the result of the `tree -P metadata* ~/.themes/` command, please?

**Comment by fluntelion** [comment]
Good evening, claudiux,

Here's the answer to your question.

name@WorkStation:~$ tree -P metadata* ~/.themes/
/home/name/.themes/
├── Glaucous
│   ├── cinnamon
│   └── metadata.json
├── Numix-Curry
│   └── cinnamon
│       ├── background-assets
│       ├── buttons
│       ├── control-assets
│       ├── expo-scale-assets
│       ├── metadata.json
│       ├── misc-assets
│       ├── panel-assets
│       ├── third-party-APPLET-stylesheets
│       ├── third-party-DESKLET-stylesheets
│       └── third-party-EXTENSION-stylesheets
├── Numix-Green
│   └── cinnamon
│       ├── background-assets
│       ├── buttons
│       ├── control-assets
│       ├── expo-scale-assets
│       ├── metadata.json
│       ├── misc-assets
│       ├── panel-assets
│       ├── third-party-APPLET-stylesheets
│       ├── third-party-DESKLET-stylesheets
│       └── third-party-EXTENSION-stylesheets
└── Numix-Red
    └── cinnamon
        ├── background-assets
        ├── buttons
        ├── control-assets
        ├── expo-scale-assets
        ├── metadata.json
        ├── misc-assets
        ├── panel-assets
        ├── third-party-APPLET-stylesheets
        ├── third-party-DESKLET-stylesheets
        └── third-party-EXTENSION-stylesheets

35 directories, 4 files
name@WorkStation:~$

And here's a question. Which one would be the very old theme?

Thank you in advance for your answer

fluntelion

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by claudiux** [comment]
@fluntelion  These three themes no longer exist in the Cinnamon database.

**Comment by fluntelion** [comment]
Good morning, claudiux,

"These three themes no longer exist in the Cinnamon database."

You're right and you aren't, because they never did. :-) 'Numix' is in the database by the name of Numix Cinnamon Transparent. Numix Curry, Green & Red weren't and aren't, because they are my forks of the original. I removed transparency, some lines and shadows as well as some other fancy things, and gave them new highlight colours: Curry, Green, and Red. What I did not do is move any file from any folder to any other folder, so all three are still in the original state - except for the changes within the css files.

The puzzling thing is that the combination of a forked Numix theme and Spices Update worked perfectly well for nearly one year - until last week when there was an update of Spices Update itself. ;-) What's more: Changing the theme to different default themes did not make Spices Update work either.

Hence the question: Who loads an applet, desklet or extension? No matter which theme or the OS itself? I'm inclined to say that it's the OS itself, most of all because .xsession-errors said: Applet SpicesUpdate@claudiux: Could not create applet object. and: Error importing applet.js from SpicesUpdate@claudiux.

But howsoever, could I get a short message when the next version of Spices Update will be available? I cannot find the number of the current version at https://cinnamon-spices.linuxmint.com/applets/view/309.

Kind regards,
flunti

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by claudiux** [comment]
Good evening, @fluntelion,

I understand better, thank you. I've made a bash script to create the missing metadata.json file at the root of some themes. 

The version 5.1.0 of Spices Update is here, from now on.

Please take a look at https://cinnamon-spices.linuxmint.com/applets/view/309#count.

Kind regards.
Claudiux
