### ISSUE TITLE
Weather UUID: weather@mockturtl

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-applets#2698]
* Applet version/Build date Version 2.3.2 (2019-10-30 05:43:33)
 * Cinnamon version 4.4
 * Distribution - Arch
 * Graphics hardware AMD
error t=2019-11-25T15:06:41Z [weather@mockturtl]: Extension is not compatible with current Cinnamon version
Cjs-Message: 14:57:22.346: JS LOG: [LookingGlass/error] [weather@mockturtl]: Extension is not compatible with current Cinnamon version
logError@/usr/share/cinnamon/js/ui/extension.js:134:17
Extension.prototype.validateMetaData@/usr/share/cinnamon/js/ui/extension.js:322:19
Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:242:17

 ```

<!-- Author list: https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/CODEOWNERS -->

**Notify author of applet**
weather@mockturtl 

**Issue**



**Steps to reproduce**



**Expected behaviour**



**Other information**

**Comment by Padre2** [comment]
With 1 instance loaded and **+** still showing in white colour, clicking the **+** changes the applet into the loading icon and adds a 2nd loading icon and the computer freezes (see attached photo), requiring Ctrl+Alt+Esc/Del to reboot .
On rebooting, it has many multiple instances across the panel (see attachment).
I cannot understand why it is necessary to allow multiple instances for this applet. As far as I am aware, applets change the **+** and **-** from white to grey or vice versa after using and only permit loading 1 instance as, I believe was was the case before.
![Weather_2x_loading_freezing](https://user-images.githubusercontent.com/38849451/69794917-bfc55480-11fd-11ea-85d2-552d21e34a42.jpg)
![Multiple_weather_after_reboot_2019-11-28 15-59-53](https://user-images.githubusercontent.com/38849451/69794981-d8ce0580-11fd-11ea-986d-f78dbb1bac4e.png)

**Comment by Padre2** [comment]
*

**Comment by Padre2** [comment]
weather@mockturtl
Sorry, was closed. Must have clicked the wrong button

**Comment by Gr3q** [comment]
It was limited to 3 applets (for multiple places). I do not know why it is not enforced (anymore? I never really checked).

**Comment by Padre2** [comment]
@Gr3q  weather@mockturtl
The issue right now is that clicking **+** more than once on Cinnamon 4.4 will try to install a second instance and the computer will freeze.  Are you looking at this issue, or is anyone else taking care of this applet?

**Comment by Gr3q** [comment]
I'm working on the applet the most this year.

I looked into it, adding multiple instances in quick succession does not freeze Cinnamon for me, but both the ability freeze and able to click multiple times is still there.

The limit actually not working is not exclusive to this applet, the limit only works if its set to 1.

I think the problem is with the 'Applets' Cinnamon settings at this time, you should create an issue in the main cinnamon repo. (both on failing on limiting and allowing to spam the + button)

**Comment by Padre2** [comment]
@Gr3q  I changed the max-instance from 3 to 1 in the metadata.json file and it fixes the issue.
I tried to open a PR, but new to GitHub have never used before and apparently it failed.  Can you take a look?
I see no reason why more than one instance would ever be needed in the Cinnamon panel.

**Comment by Padre2** [comment]
@Gr3q
It appears that several posts were deleted, although not by me.  
>I think the problem is with the 'Applets' Cinnamon settings at this time, you should create an issue in the main cinnamon repo. (about failing on limiting and allowing to spam the + button).

My understanding was that you would do this, but I cannot find anything.  Please advise if you did.

**Comment by Gr3q** [comment]
I opened the issue here https://github.com/linuxmint/cinnamon/issues/9004

**Comment by Padre2** [comment]
@Gr3q   Köszönöm a segítséget.

**Comment by Gr3q** [comment]
@Padre2  I've got a reply:

> Hi @Gr3q , we've changed the way we use the max-instances field over time. Originally it was used as you're describing, but now we only use it to distinguish between single-instance and multi-instance. (I can't think of a use-case where you could allow more than one instance, but not more than x instances, so I don't really see the point in having a multi-instance applet that doesn't allow an infinite number of instances). Admittedly it would probably make more sense to rename it and make it a boolean setting so it's less confusing, but I believe we left it as-is for backwards compatibility reasons, and I'm not sure it's worth the effort to change it now. In any case, this is actually working as intended, so I'm going to close this. The crashing is a different issue entirely, so we probably want a separate issue for that
