### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: Settings are reset on every update

### ISSUE THREAD

**Issue by Fabian42** [linuxmint/cinnamon-spices-applets#2703]
```
 * Applet version/Build date: 1.8.9
 * Cinnamon version: 3.2.7
 * Distribution: Debian 9.11
 * Snippet of ~/.cinnamon/glass.log:
error t=2019-11-25T21:04:43.307Z Failed to load prefs.json: GLib.FileError: Failed to open file '/home/fabian/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.2/prefs.json': No such file or directory Attempting to create it.
 ```

**Notify author of applet**
@jaszhix 

**Issue**
Every time I update this applet, its settings get reset. The cause seems pretty apparent from the log and when looking at the folder: The settings are saved in sub-folder that is named after the version! So of course it doesn't find them again after an update!

**Comment by claudiux** [comment]
Now, the `prefs.js` file is stored in another folder.
