### ISSUE TITLE
 Weather by mockturtl - multiple instances

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-applets#2707]
UUID: weather@mockturtl

Applet version/Build date Version 2.3.3 (2019-11-27 03:57:15)
Cinnamon version 4.4
Distribution - Arch
Graphics hardware AMD

**Notify author of applet**
 weather@mockturtl

**Issue**
After downloading this new version it can be loaded and functions. However, after clicking **+** the symbol remains highlighted and can be clicked repeatedly, which installs multiple applets. When clicking **-** asks to remove all instances. Also had warning ! triangle after deleting.

**Steps to reproduce**
Repeats after downloading, loading, removing, loading and removing.

**Expected behaviour**
can only load one instance

**Other information**

**Comment by Gr3q** [comment]
I...I'm positive that is a feature what was in there even before I started working on the applet.

It supposed to allow maximum of 3 instances.

**Comment by Padre2** [comment]
To the best of my recollection, after selecting to load the applet by clicking the white **+** the colour changed to grey and the **-** changed from grey to to white. Now after clicking **+** both remain white colour and there seems to be no limit to the number of instances that can be loaded (see attachment).
![Multiple_instances_Weather _applet_2019-11-28 10-48-25](https://user-images.githubusercontent.com/38849451/69776195-d358c700-11cd-11ea-88a3-e378d123972c.png)

**Comment by Gr3q** [comment]
Do you still can add more than 3 instances? If yes please reopen the issue and I'll look into it.
