### ISSUE TITLE
 Radio++ by Driglu4it - Increase station list window size. 

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-applets#2714]
FEATURE REQUEST
![Radio_list_window](https://user-images.githubusercontent.com/38849451/69844057-0ae27480-129d-11ea-86c0-6c1d387ed427.png)

* Applet version/Build date - Updated on 2019-10-20 00:00:27
 * Cinnamon version 4.4
 * Distribution - Arch
 * Graphics hardware - AMD/ATI

**Notify author of applet**
radio@driglu4it

It would help to be able to see as many of the listed stations as possible.  Without changing the overall size, would it be possible to increase the text list window (white background area) size?

**Comment by claudiux** [comment]
@Padre2 That's done!

**Comment by Padre2** [comment]
@claudiux  Merci beaucoup! It's logical to make use of the space to reduce scrolling.

**Comment by Padre2** [comment]
Hello Caudiux,

Can I communicate directly with you via this e-mail address, or is it posted on github?

Regards,
Padre2
