### ISSUE TITLE
CinnVIIStarkMenu

### ISSUE THREAD

**Issue by majfv** [linuxmint/cinnamon-spices-applets#2717]
Hello
I do not have a favorites, just apps grouped by theme.
Is it possible to hide the "Favorites" column and the "Favorites" button found in the applications column.
Thank you for your reply
```
 * Applet version1.7
 * Cinnamon version 4.2.4
 * Distribution Mint 19.2
 * Graphics hardware NVIDIA


 ```

**Notify author of applet**
CinnVIIStarkMenu@NikoKrause@

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by claudiux** [comment]
Please mention the author: @NikoKrause
