### ISSUE TITLE
"redshift only gets darker"

### ISSUE THREAD

**Issue by Stoatwblr** [linuxmint/cinnamon-spices-applets#2747]
This is on Ubuntu 19.10 and seems to be common with the KDE applet bug report:

https://lists.debian.org/debian-release/2019/10/msg00011.html

This is due to a parameter change in redshift:

Description: Redshift version >= 1.12 requires the -P option to clear the existing gamma ramps for one-shot mode. Without it the screen gets darker and darker until it is impossible to see anything.

The fix is simple enough if you look at the kde entry above

**Comment by icarter09** [comment]
@Marvel4U

**Comment by Darkless012** [comment]
I've tried to debug and fix this applet, but without any luck.
Here is the one shot line (where I've tried to add `-P` flag): 
https://github.com/linuxmint/cinnamon-spices-applets/blob/b9b238ca63aaa86e284fd7df2e4a397ada802a71/redshift%40marvel4u/files/redshift%40marvel4u/applet.js#L327
This plugin also flickers on changing brightness by slider (flicker seems to be cause by brightness being switched between 100%  and set value)

**NOTE** (for other users encountered this issue)
I can only recommend trying QRedshift applet, which seems not to have those issues.
