### ISSUE TITLE
sysmonitor@orcus add text label/title to each graph

### ISSUE THREAD

**Issue by mlavi** [linuxmint/cinnamon-spices-applets#2748]
```
 * Applet version 1.6.4/2019-12-08
 * Cinnamon version 4.2.4
 * Distribution - Mint 19.2
 * Graphics hardware *and* driver used:
Advanced Micro Devices, Inc. [AMD/ATI] Curacao PRO [Radeon R7 370 / R9 270/370 OEM]
       configuration: driver=radeon latency=0
 * Snippet or attachment of ~/.cinnamon/glass.log
  Interesting, no mention of sysmonitor, closest I saw was loading: multicore-sys-monitor@ccadeptic23
 * Snippet or attachment of ~/.xsession-errors
Cjs-Message: 12:28:03.004: JS LOG: [LookingGlass/info] Loaded applet sysmonitor@orcus in 628 ms
(cinnamon:2461): Cjs-WARNING **: 12:28:03.005: JS ERROR: GLib.Error g-invoke-error-quark: Could not locate glibtop_init_s: 'glibtop_init_s': /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.11: undefined symbol: glibtop_init_s

 ```
**Notify author of applet**
@orcuscz

**Feature Request**

As a desktop users, I use the tooltip when mousing over the applet and it incredibly helpful to learn what is being displayed. But discerning and verifying which graph is which, especially when they are nearly empty (e.g.: swap barely in use, load is near zero) is hard at a glance or when you are new/learning the layout.

I would ask for a simple textual label in the corner of each graph, the same as you use for the tooltip.

Thank you so much, your applet is one of the first things I install!

**Comment by claudiux** [comment]
This is impossible, as the tooltip is already displayed when the applet is hovered over.
