### ISSUE TITLE
[show-hide-applets@mohammad-sn] Add option to not autohide on click

### ISSUE THREAD

**Issue by aerkiaga** [linuxmint/cinnamon-spices-applets#2756]
This is simply a feature request. The idea is that when "Activate on hover" and "Autohide" are both enabled, a further option was made available where hovering and then clicking on the activated icon disables autohide until the applet icons are manually hidden by clicking or hovering (if "Hide on hovering again" is enabled. There are other ways of specifying this configuration, like radiobuttons for the autohide option.

This can be really useful, since there are times when a user may occasionally desire to actually keep an applet or set of applets on display for some time, but don't usually need them otherwise. I can think of many examples.

**Comment by icarter09** [comment]
@mohammad-sn
