### ISSUE TITLE
web-developer-menu@infiniteshroom

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-applets#2760]
@infiniteshroom

 * Applet version/Build date:  ? not shown in metadata.js - latest download
 * Cinnamon version 4.4.4 & 4.4.5
 * Distribution - Arch 
 * Graphics hardware *and* driver used AMD/ATI Radeon
 * Snippet or attachment of ~/.cinnamon/glass.log
error t=2019-12-19T15:02:44Z 
[web-developer-menu@infiniteshroom]: assignment to undeclared variable s
[web-developer-menu@infiniteshroom]: Failed to evaluate 'main' function on applet: web-developer-menu@infiniteshroom/145
error t=2019-12-19T15:02:44Z 
[web-developer-menu@infiniteshroom]: Applet web-developer-menu@infiniteshroom: Could not create applet object.
[web-developer-menu@infiniteshroom]: Error importing applet.js from web-developer-menu@infiniteshroom

 * Snippet or attachment of ~/.xsession-errors
[web-developer-menu@infiniteshroom]: assignment to undeclared variable s
[web-developer-menu@infiniteshroom]: Failed to evaluate 'main' function on applet: web-developer-menu@infiniteshroom/145
[web-developer-menu@infiniteshroom]: Applet web-developer-menu@infiniteshroom: Could not create applet object.
[web-developer-menu@infiniteshroom]: Error importing applet.js from web-developer-menu@infiniteshroom
 ```
<!-- Author list: https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/CODEOWNERS -->

**Notify author of applet**
@infiniteshroom

**Issue**
Not loading, errors.

**Comment by Padre2** [comment]
Now on Cinnamon 4.4.8.
No response for more than a month.
@claudiux   Do you know the author?

**Comment by claudiux** [comment]
@Padre2 The author is @infiniteshroom, who has not had any public activity on Github since December 2018.
