### ISSUE TITLE
[brightness-and-gamma-applet@cardsurf] All values are reset to 100% on each update

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon-spices-applets#2790]
```
 * Applet version/Build date: Version 1.1.1 (2020-01-02 18:26:03)
 * Cinnamon version: 4.4.6
 * Distribution: Mint 19.3
 ```

**Author of applet**
@cardsurf

**Issue**
Whenever this applet is updated, all the values are reset to 100%.

**Steps to reproduce**
Wait for an update... or use settings of Spices Update to reload the latest version of brightness-and-gamma-applet@cardsurf.

**Expected behaviour**
Let these values be kept.

**Other information**
You can create in `~/.cinnamon/configs/brightness-and-gamma-applet@cardsurf/` a file containing these values and reload them at the start of this applet.

**Comment by cardsurf** [comment]
@claudiux
Hi,
Thanks for the detailed description.
I will fix the issue this week. In the next days I will test that the applet works correctly.

**Comment by claudiux** [comment]
@cardsurf Yesss! It works very well! Thank you very much!
