### ISSUE TITLE
hwmonitor@sylfurd: New applet - I/O Disk usage

### ISSUE THREAD

**Issue by ArnaudDovi** [linuxmint/cinnamon-spices-applets#2801]
Actually for me hwmonitor@sylfurd is the perfect replacement to the system tray icons of process explorer under Windows except it lacks the informations to monitor I/O disk usage.

I believe it helps to not charge the system queue too much when there is extreme disk works.

@claudiux @brownsr

**Comment by Hultan** [comment]
I have implemented two new graphs, showing disk read and write of the **root disk (/)**.

I hope you like it :-)

**Comment by ArnaudDovi** [comment]
Thanks you a lot @Hultan 

Definitely the best hardware applet outta there, I use it at home and work everyday ;)

Keep up the good work

**Comment by ArnaudDovi** [comment]
Hey @Hultan, is there any requirement to the disk usage to work ? because it does a few minutes I installed it and both graph are showing 0 usage

**Comment by Hultan** [comment]
I am using **fusage** in **libgtop** (https://developer.gnome.org/libgtop/stable/libgtop-fsusage.html) to measure how many blocks have been read and written. I might have misunderstood how it works though.

Try copying a large file and see if you see anything. I noticed on my machine too that the disk wasn't used very much, but whenever I copy a large file I see the graph move. Maybe this graph should have the lin/log option too, like net in/out have?

**Comment by Hultan** [comment]
And remember, that once the disk has reached its max performance once, that value will be used for the rest of the applets life time as a max value, so all percentages will be based on that max value. In the beginning it does not have that max value, so it will seem like it is being used more.

I implemented it like this, to avoid having to add a setting for disk speed, that I felt that most people don't know, or know how to find.

**Comment by ArnaudDovi** [comment]
Not better, yet I'm trying on work computer with normal disk but still nothing moves even with a large file transfer.
![Screenshot from 2020-02-28 16-10-06](https://user-images.githubusercontent.com/52439/75560244-17659d00-5a45-11ea-9703-69d0d27ef596.png)

**Comment by Hultan** [comment]
Are you sure you are copying that file from the root disk (/), to the root disk(/)?

I get the behavior that you describe if I copy a file from a secondary disk to a secondary disk. But every time I involve the root disk (/) in the process, I get reasonable graphs. If I copy from the root disk (/) to a secondary disk, I get some action in the DISK (read) graph, and vice versa.

After having copied the same file a couple of times, it looks like there might be some caching involved, and I get lower percentages. I do not know how that works in the hardware though, it might be different on SSDs and spinning drives...

Anyway, we'll have to monitor the behavior for a few days, and see if it works. I'll fix whatever I can, as soon as we understand what is wrong here.

**Comment by ArnaudDovi** [comment]
I would like to help you so I searched a bit the use of libgtop around, and it seems in your code, you miss the crawl of all the available mounts.

This is just assumption, but I think you are monitoring only my swap, my boot partition, something like that while another applet seems to parse all the available mounts

Found this [here](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/cd2704c219da5f36e4f93fc3a06260d9ae68bad3/system-monitor%40paradoxxx.zero.gmail.com/extension.js#L1364)

Hope it helps, I'm sure you will get it working

**Comment by Hultan** [comment]
I have added a new setting, you can no set which dir to monitor. This means that you can choose to monitor the root drive (/) (default), or you can choose to monitor another drive (for example /mnt/another_drive).

Let's see if that helps you. It is strange, because it does seem to work on my machine, and my main drive has two partitions. So I don't know what to do here.

Anyway, the link you sent, didn't use **libgtop**, instead it directly monitored the file **/proc/diskstat** file, if I read the code correctly. It was still helpful though, because now I have an alternative way to monitor the drives, if I need to change the code later.

Anyway, see if the new setting helps you to make some sense of the data you get on your machine, and then maybe later we can improve this applet.

**Comment by claudiux** [comment]
@Hultan Is it possible to monitor an entire disk or a partition, using /dev/sda or /dev/sda4?

**Comment by Hultan** [comment]
To be honest,@claudiux, I have no idea. The documentation is horrible, which is just slightly better than non-existing:

https://developer.gnome.org/libgtop/stable/libgtop-fsusage.html

**Comment by claudiux** [comment]
@Hultan Thank you for your reply.

**Comment by ArnaudDovi** [comment]
Thank you for clarification. I have seen the new options you added, yet nothing better. 

I have tried / , /dev/vg0/root and /dev/mapper/vg0-root nothing 

Maybe it has something to do with LVM, unfortunately I don’t have an unencrypted system yet to test with. Will let you know if I get anything better

**Comment by Hultan** [comment]
@ArnaudDovi I think it must have to do with LVM then, it seems to work perfectly on my machine. I have tested with a few different mounted drives in the mnt folder. I have for example /mnt/250 and /mnt/2000 which behaves just as expected, and so is the root drive /. 

Since the documentation is not very clear on how to use these functions, I think we'll have to wait a while to see if we get more information from other users. Maybe I'll have to develop a way to choose to skip **libgtop** and go directly against the /proc/diskstat file.

By the way, can you check if the file /proc/diskstat exists on your machine?

**Comment by ArnaudDovi** [comment]
Yes /proc/diskstats exists.
Also I have verified in /boot that is my only one partition unencrypted, seems to work, I got for first time the graph showing in here.

I think before finding an alternative, would be better to verify if we could get libgtop working with encrypted partition because LVM on LUKS is a common setup 

https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#LVM_on_LUKS

**Comment by ArnaudDovi** [comment]
I smell the libgtop bug

Relevant discussion : https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/97

Did not read all but seems people found workarounds, I will do few tests tonight when I go back home

**Comment by Hultan** [comment]
Sounds like you definetely found the explanation for why it is not working on your machine there...

Thanks for spending time investigating this...I am sitting here being very confused, since everything seems to be working correctly on my machine :-)

Let me know if you find a workaround that works on your machine. I'll update the readme.md eventually when we have some better understanding of this.

**Comment by ArnaudDovi** [comment]
So I did some investigation, and I get it working after applying a patch to libgtop

Below the official PKGBUILD of Arch Linux with the patch instruction
[libgtop-git_lvm_patched.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/4277498/libgtop-git_lvm_patched.zip)

https://bugzilla.gnome.org/show_bug.cgi?id=160441 - Historical BugZilla Issue now archived
https://gitlab.gnome.org/GNOME/libgtop/issues/3 - New issuesite but closed

I wonder why is it still a thing today and also wonder if the Arch Linux administrator could allow me to host it as AUR package, I already maintain one but as far I remember the AUR is supposed to contain only packages not in the core distribution, unfortunately libgtop in core distro doesnt not seem to support LVM, despite being the 2.40.0 version.

Do you have any idea ? Nobody developing libgtop want to patch it for lvm ?

**Comment by Hultan** [comment]
Great that you got it to work!

I will link to this thread in the readme.md if there are more LVM-users out there who uses this applet.

I have no idea about **libgtop**, I just began to improve this applet about a year ago, and it was already using **libgtop** at that time. Why this bug still exists, if there are a solution for it out there, I don't understand. I guess they have given up supporting that package?

**Comment by ArnaudDovi** [comment]
I think most look at /proc/diskstats and a fallback to libgtop as it doesn't seem to support a large range of systems, found interesting discussion about it here if you interested

https://github.com/mate-desktop/mate-applets/issues/290

**Comment by ArnaudDovi** [comment]
Bad news, the libgtop patch seem to work a moment and after some time nothing is showing again.

So the libgtop patch is not suitable

**Comment by Hultan** [comment]
@ArnaudDovi Ok, I guess I'll have to look into if its possible to go directly at the file /proc/diskstat, instead of going trough **libgtop**. I'll have to add a setting for that also I guess. I'll do that when I find some time...

**Comment by KickerTom** [comment]
What about using dbus udisks2? For inspiration, check out this applet/desklet:
https://github.com/mariusvam/Drives-Manager
