### ISSUE TITLE
CPU Temperature Indicator - picking displayed temp

### ISSUE THREAD

**Issue by kalee** [linuxmint/cinnamon-spices-applets#2806]
$ sensors
k10temp-pci-00db
Adapter: PCI adapter
Tdie:         +33.2°C  (high = +70.0°C)
Tctl:         +60.2°C  

k10temp-pci-00cb
Adapter: PCI adapter
Tdie:         +32.2°C  (high = +70.0°C)
Tctl:         +59.2°C  

amdgpu-pci-0900
Adapter: PCI adapter
vddgfx:       +0.90 V  
fan1:         787 RPM
temp1:        +46.0°C  (crit = +91.0°C, hyst = -273.1°C)
power1:       65.17 W  (cap = 185.00 W)

k10temp-pci-00d3
Adapter: PCI adapter
Tdie:         +32.2°C  (high = +70.0°C)
Tctl:         +59.2°C  

k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +34.0°C  (high = +70.0°C)
Tctl:         +61.0°C 

The temp the displays is the very last one.  How do I pick which one I want to display?  There was a previous post that asked a similar question, but no answer was in the post and it was closed.

For this cpu, one of the tdie temperatures is desired.

**Comment by claudiux** [comment]
Hi @kalee,

The next time, please mention me (@claudiux) for any issue about this applet.

I am working on an interface allowing the user to choose the sensors to take into account.

**Comment by kalee** [comment]
@claudiux 
>> I am working on an interface allowing the user to choose the sensors to take into account.
That is fantastic news and great too know.  
In the meantime, if I want to select a different temperature to be displayed, is that an option in the applet.js file?  
If not, do you have a a rough idea on when?  Weeks, or Months?  I plan to continue to use the applet, I just do the -25 degree math in my head.

Thank you for that great applet and support!

**Comment by claudiux** [comment]
@kalee Can you try this version, please? https://github.com/linuxmint/cinnamon-spices-applets/pull/2755
This is a "work in progress" version. The final version will come ... when it's done, as Debian says. ;)

**Comment by claudiux** [comment]
@kalee Post here that the command `sensors -u` returns, and the contents of your `/etc/modules` file, please.

**Comment by kalee** [comment]
@claudiux 

### output of sensors command
$ sensors -u
k10temp-pci-00db
Adapter: PCI adapter
Tdie:
  temp1_input: 31.250
  temp1_max: 70.000
Tctl:
  temp2_input: 58.250

k10temp-pci-00cb
Adapter: PCI adapter
Tdie:
  temp1_input: 30.750
  temp1_max: 70.000
Tctl:
  temp2_input: 57.750

amdgpu-pci-0900
Adapter: PCI adapter
vddgfx:
  in0_input: 1.106
fan1:
  fan1_input: 809.000
temp1:
  temp1_input: 43.000
  temp1_crit: 91.000
  temp1_crit_hyst: -273.150
power1:
  power1_average: 83.165
  power1_cap: 185.000

k10temp-pci-00d3
Adapter: PCI adapter
Tdie:
  temp1_input: 30.750
  temp1_max: 70.000
Tctl:
  temp2_input: 57.750

k10temp-pci-00c3
Adapter: PCI adapter
Tdie:
  temp1_input: 32.750
  temp1_max: 70.000
Tctl:
  temp2_input: 59.750


### /etc/modules does not have any entries
$ cat modules
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.

**Comment by kalee** [comment]
@claudiux 
Thank you for the info on #2755 
I needed to install git-extras, then run git pr 2755, after a git clone of the cinnamon-spices-applets repo.  I backed-up my files, and replaced with the WIP files.  I then ran alt-f2 with r to restart cinnamon without losing all of my open windows.

I now get four temps in the pop-up, all of them the higher temps, none of the tdie values.

The cpu is a threadripper 2970.

I appreciate your help!  Thank you again!

**Comment by claudiux** [comment]
@kalee Your `/etc/modules` file is empty. Did you try the command `sudo sensors-detect --auto`? On my computer, it returns:
```
[...]
To load everything that is needed, add this to /etc/modules:
#----cut here----
# Chip drivers
coretemp
nct6775
#----cut here----
[...]
```

To display Tdie values, try to modify the line 38 of applet.js.
From:
```
const cpuIdentifiers = ['CPU Temp', 'CPU0 Temp', 'CPU1 Temp', 'Tctl', 'CPU Temperature', 'Current CPU Temperature', 'PECI Agent 0'];
```
To:
```
const cpuIdentifiers = ['CPU Temp', 'CPU0 Temp', 'CPU1 Temp', 'Tctl', 'Tdie', 'CPU Temperature', 'Current CPU Temperature', 'PECI Agent 0'];
```

**Comment by kalee** [comment]
@claudiux 
The command  sudo sensors-detect --auto does not add anything to /etc/modules on my system.
I did add 'Tdie' and removed 'Tctl' form line 38 of applet.js.  The temp now displays the correct temperatures for me.

This will work great!  I look forward to the update that allows picking the temperature, then I can add the 'Tctl' values back in.

Thank you again for the quick response and very helpful answers!
