### ISSUE TITLE
0dyseus@PopupTranslator not working

### ISSUE THREAD

**Issue by Faust30000** [linuxmint/cinnamon-spices-applets#281]
Applet not working.
Linux Mint 18.1.
Message in applet:
**Unmet dependencies found!!!
A detailed error has been logged into ~/.cinnamon/glass.log file.**

**Comment by NikoKrause** [comment]
What does the ~/.cinnamon/glass.log file say?

**Comment by Faust30000** [comment]
```
error t=2017-04-07T21:20:22.479Z 
# [Popup Translator]
# Unmet dependencies found!!!
# xsel command not found!!!
# Check this applet help file for instructions.
# It can be accessed from this applet context menu.
```

**Comment by NikoKrause** [comment]
You habe to install xsel.
`sudo apt install xsel`

**Comment by Faust30000** [comment]
Thanks. Now everything works.
