### ISSUE TITLE
Web Developer Menu (web-developer-menu@infiniteshroom)

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-applets#2823]
@claudiux  Many thanks for looking at this.

 * Applet version/Build date:  Updated on 2020-01-23 03:22:21
 * Cinnamon version:  4.4.8
 * Distribution - Arch
 * Graphics hardware AMD/ATI Radeon
 * Snippet or attachment of ~/.cinnamon/glass.log
   fo t=2020-01-23T14:21:17Z Loaded applet web-developer-menu@infiniteshroom in 244 ms
 * Snippet or attachment of ~/.xsession-errors
   Cjs-Message: 14:21:17.559: JS LOG: [LookingGlass/info] Loaded applet web-developer-menu@infiniteshroom in 244 ms
 

**Issue**
Applet loads and displays icon in panel
None of the Applet menu items can be opened except Launch phpMyAdmin

Applet presumably not created for an Arch distribution, so made following changes:
Original code:
```//applet command constants
var CommandConstants = new function() {
  this.COMMAND_START_APACHE = "gksu service apache2 restart";
  this.COMMAND_STOP_APACHE = "gksu service apache2 stop";
  this.COMMAND_START_MYSQL = "gksu service mysql restart";
  this.COMMAND_STOP_MYSQL = "gksu service mysql stop";
  this.COMMAND_APACHE_CONFIG_EDIT = "gksu gedit /etc/apache2/sites-enabled/000-default";
  this.COMMAND_PHP_CONFIG_EDIT = "gksu gedit /etc/php5/apache2/php.ini";
  this.COMMAND_LAUNCH_PHPMYADMIN = "xdg-open http://localhost/phpmyadmin/";
  this.COMMAND_LAUNCH_WEBDIR = "xdg-open http://localhost/";
  this.COMMAND_OPEN_WEBDIR = "nemo /var/www/";
}
 ```
Changed to:
```//applet command constants
var CommandConstants = new function() {
  this.COMMAND_START_APACHE = "sudo systemctl restart httpd";
  this.COMMAND_STOP_APACHE = "sudo systemctl stop httpd";
  this.COMMAND_START_MYSQL = "sudo systemctl start mariadb";
  this.COMMAND_STOP_MYSQL = "sudo systemctl stop mariadb";
  this.COMMAND_APACHE_CONFIG_EDIT = "sudo nano /etc/httpd/conf/httpd.conf";
  this.COMMAND_PHP_CONFIG_EDIT = "sudo nano /etc/php/php.ini";
  this.COMMAND_LAUNCH_PHPMYADMIN = "xdg-open http://localhost/phpmyadmin/";
  this.COMMAND_LAUNCH_WEBDIR = "xdg-open http://localhost/";
  this.COMMAND_OPEN_WEBDIR = "nemo /srv/http/wordpress/";
} 
```
result 
  COMMAND_START_APACHE - not working
  COMMAND_STOP_APACHE - not working
  COMMAND_START_MYSQL - not working
  COMMAND_STOP_MYSQL - not working
  COMMAND_APACHE_CONFIG_EDIT - not working
  COMMAND_PHP_CONFIG_EDIT - not working
  COMMAND_LAUNCH_PHPMYADMIN - working
  COMMAND_LAUNCH_WEBDIR - working 
  COMMAND_OPEN_WEBDIR - working

**Other information**
`gksu` is deprecated in Debian and Ubuntu. Didn't look for it initially in Arch, but is available in AUR.
Changed code used above will open as expected in the terminal.
Replacing `sudo` with `pkexec`, or `gksu` works too in the terminal.

**Comment by Padre2** [comment]
The toggle button for mariadb will switch position, when command to start or stop mdb is run from the terminal or an alias. 
Have tried adding action  for nano and systemctl to polkit for pkexec, but no success.

**Comment by claudiux** [comment]
@Padre2 Forking it for Arch is useless. I will do a PR to automatically adapt these commands and services to the detected distro. Please wait a few days, I'm too busy now.

**Comment by Padre2** [comment]
@claudiux   @claudiux  Regarding forking, understood, it had been a long day and I was not thinking clearly. It would be great if you can adapt it to detect the distro. No rush!
Most of my web development is on the WordPress platform, so I included it for launching the web directory, but presumably you will want to remove `wordpress` from line 20, for generally use.
This applet is very useful with LAMP. If several PHP versions are installed, it makes it easier to switch versions and it is good to have a one-click restart Apache after changing PHP versions and to start the Maria DB.

**Comment by Padre2** [comment]
@claudius  My Manjaro OS installation crashed after an update and went into grub rescue with corrupted lib files. I gave up on the repair, since the Arch that I compiled is still running well with no issues for > 6 months.  I had feren OS installed on an old HDD, which just failed and the latest feren OS has replaced Cinnamon with Plasma, so I installed the new Ubuntu Cinnamon Remix on the good drive.  This gave me an opportunity to check the Web Developer Menu applet on Ubuntu.

As I mentioned above, `gksu` is deprecated in Ubuntu, but I found an old version for Debian together with the `libgksu-2.0` dependent package, then found that 6 more dependencies were required, which were not available in the repositories. I was able to satisfy 4 using -dev packages, but was not able to install the remaining 2 dependencies:  gnome-keyring-1.0` and `libgtop-2.0`, because newer versions are already installed. Perhaps there is a way around this, but I stopped at this point.

I then changed to use `sudo -H` and `pkexec` to replace `gksu` and updated the paths.  Although the code worked in the terminal, it did not work in the applet.js file and I have not yet found the cause. I recall that using sudo was also an issue with Arch. I would be interested to know whether you can get this applet to work in Ubuntu.

**Comment by Padre2** [comment]
@claudiux 
I had no problem to get the lines working to open and  launch the WEBDIR and launch phpMyAdmin:
`this.COMMAND_LAUNCH_PHPMYADMIN = "xdg-open http://localhost/phpmyadmin/";`
 ` this.COMMAND_LAUNCH_WEBDIR = "xdg-open http://localhost/";`
 ` this.COMMAND_OPEN_WEBDIR = "nemo /var/www/";`
I made progress with the CONFIG_EDIT for the apache2.conf and php.ini files:
`this.COMMAND_APACHE_CONFIG_EDIT = "gedit admin:///etc/apache2/apache2.conf";`
 `this.COMMAND_PHP_CONFIG_EDIT = "gedit admin:///etc/php/7.3/apache2/php.ini";`
However unlike with `gksu`, authentication is still needed.
I cannot get the toggles to work on restart/stop apache 2, or start/stop mysql.

**Comment by Padre2** [comment]
Using `systemctl` for the Apache and MySQL toggles:
```this.COMMAND_RESTART_APACHE = "systemctl restart apache2";
  this.COMMAND_STOP_APACHE = "systemctl stop apache2";
  this.COMMAND_START_MYSQL = "systemctl start mysql";
  this.COMMAND_STOP_MYSQL = "systemctl stop mysql";
```
Clicking the Apache toggle button causes the authentication window to display. After entering password Apache is stopped. However, after clicking again to open Apache, there is a message:
`expected type filename for Argument 'command line', but got type 'undefined'`
Clicking the MySQL toggle button causes the authentication window to display. After entering the password, there is no change and no message, and this will repeat after each click.

**Comment by claudiux** [comment]
@Padre2 I will verify all that.

**Comment by claudiux** [comment]
@Padre2 Please take a look at this PR of @Aminur670: #2854

**Comment by Padre2** [comment]
@claudiux 
I am running Ubuntu 19.10, Apache/2.4.41 (Ubuntu), MySQL Ver. 8.0.19-0ubuntu0.19.10.3, 
PHP Version 7.3.11-0ubuntu0.19.10.2 and phpMyAdmin ver. 5.0.1.

I am a novice with Ubuntu and struggling trying to find packages in the repositories, e.g, phpMyAdmin appears to be no longer in Debian and Ubuntu repositories and is a pain to install. PHP 7.4 is also not yet in the repositories so I installed PHP 7.3. Both are now working as expected.

The code in the PR uses `php5` and  `service` and I have the impression that the applet was originally written before systemd was adopted and I have no experience with these earlier Linux distributions. For that reason, I will comment on the Apache and MySQL lines with the toggle commands:
```
  this.COMMAND_START_APACHE = "sudo service apache2 restart";
  this.COMMAND_STOP_APACHE = "sudo service apache2 stop";
  this.COMMAND_START_MYSQL = "sudo service mysql restart";
  this.COMMAND_STOP_MYSQL = "sudo service mysql stop";
```
Using `sudo' was the first step that I tried with the applet in Arch and it produced no results.  I also tried it with the above LAMP setup in Ubuntu and it also produced no results. 
My solutions for Arch are working perfectly and without requests for authentication.
Coming back to PHP, I am puzzled that the php5 was retained, as even PHP 7.1 is no longer supported.

**Comment by Padre2** [comment]
@claudiux  
I have just installed the new version dated 2020-02-11 07:45 UTC, which appears to follow the PR.
The Apache Web Server and MySQL toggles, and the Edit default php.ini and Apache Conf are not working with my set-up. Other menu items are working as would be expected.

**Comment by Padre2** [comment]
@claudiux  After trying to do some updating of Ubuntu Cinnamon Remix I got int an endless loop with the updating of LAMP, so I decided to reinstall the OS.  I now have Maria DB instead of MySQL, but still same issues with the toggles: commands that work in the terminal do not work in the applet.

**Comment by Padre2** [comment]
@claudiux   I was able to get the applet to function. I opened a PR, but would appreciate your assistance, if I have not followed the procedures properly.

**Comment by claudiux** [comment]
@Padre2 https://github.com/claudiux/docs/blob/master/HOW_TO_MAKE_A_CLEAN_REFORK.md

**Comment by Padre2** [comment]
@claudiux  Sorry for the trouble and many thanks for the link.  I previously  installed GitHub on Arch system, but followed the procedures in the link on the Ubuntu system,  until the following:
```victor@phenom:~/git/csa/master$ git pull upstream master
From https://github.com/linuxmint/cinnamon-spices-applets
 * branch              master     -> FETCH_HEAD
Auto-merging web-developer-menu@infiniteshroom/files/web-developer-menu@infiniteshroom/applet.js
CONFLICT (content): Merge conflict in web-developer-menu@infiniteshroom/files/web-developer-menu@infiniteshroom/applet.js
Auto-merging weather@mockturtl/files/weather@mockturtl/metadata.json
CONFLICT (content): Merge conflict in weather@mockturtl/files/weather@mockturtl/metadata.json
Removing turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/enable_mouse.sh
Removing turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/disable_mouse.sh
Removing brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/filesCsv.js
Removing brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/files.js
Automatic merge failed; fix conflicts and then commit the result.
```
The conflict is shown with the previous Weather applet.  How do I fix this conflict?

**Comment by claudiux** [comment]
@Padre2 You must have a clean fork and **not work in the master branch**.

Save locally the code of your applet.

Go to https://github.com/Padre2/cinnamon-spices-applets/settings then, in the Danger Zone: Delete this repository (you will need to enter its name: cinnamon-spices-applets).

Go to https://github.com/linuxmint/cinnamon-spices-applets and click the Fork button. Now, a proper https://github.com/Padre2/cinnamon-spices-applets exists.

On your computer:
```
cd ~/git/
rm -rf csa
mkdir csa
cd csa
git clone -b master --single-branch https://github.com/Padre2/cinnamon-spices-applets cinnamon-spices-applets
cd cinnamon-spices-applets
git remote add upstream https://github.com/linuxmint/cinnamon-spices-applets.git
git remote -v
```
The latest command should return:
```
origin	https://github.com/Padre2/cinnamon-spices-applets.git (fetch)
origin	https://github.com/Padre2/cinnamon-spices-applets.git (push)
upstream	https://github.com/linuxmint/cinnamon-spices-applets.git (fetch)
upstream	https://github.com/linuxmint/cinnamon-spices-applets.git (push)
```

(I just rewrite https://github.com/claudiux/docs/blob/master/HOW_TO_MAKE_A_CLEAN_REFORK.md adding tips)

Now, go to https://github.com/Padre2/cinnamon-spices-applets. Under the number of commits, you see a button `Branch: master`. Click on it and create your own branch from master; for example: webmenu-arch. (Before that, your master branch must be even with the master branch of linuxmint; use the script `refork-csa` described in the Tips section to do that.)

Then, on your computer:
```
cd ~/git
git clone -b webmenu-arch --single-branch https://github.com/Padre2/cinnamon-spices-applets.git webmenu-arch
```
Wait for the end of the copy. Open with Nemo your `~/git/webmenu-arch/web-developer-menu@infiniteshroom/files/web-developer-menu@infiniteshroom` folder. Press the F3 key. In the second panel just opened, go into your applet folder and copy/paste the modified file from the second panel to the first panel. Use `git status` to know what to do.

**Comment by Padre2** [comment]
@claudiux  Thanks again for your help.
The `.profile` file now has
```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
```
and
```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
```
I am down to 
```
(Before that, your master branch must be even with the master branch of linuxmint; use the script `refork-csa` described in the Tips section to do that.)
...
To take these lines into account: source ~/.profile
I created the ~/bin/refork-csa script, containing:
```
and am unsure about `source` and where the script goes.
Getting late - bad day - heavy rains caused a roof leak onto ceiling above computer and another above TV and will be busy with urgent roof repairs, so may not be able to work on this until late tomorrow.

**Comment by claudiux** [comment]
@Padre2 Cheer up! I have experienced the same misadventures and I know how unpleasant and worrying it is.

If you have logged out / logged in since you changed your .profile file, don't worry about the source command, which allows you to immediately take into account (only in the terminal where the source command is executed) changes made to that file.

**Comment by Padre2** [comment]
@claudiux   As we say in English "it never rains but it pours" applies both literally and metaphorically. Apart from my roof leaks, the old HDD with the Ubuntu OS crashed with an i/o issue, which has occurred before.  but this time I was unable to revive the drive and it is dead. Un malheur n’arrive jamais seul!  I hope to have a new drive by Monday afternoon.

I have rerun the _clean refork_ on my Arch OS.  As for clearing the conflict, the Weather files are still there and I seem to be lost in the weeds - se perde dans les herbes.

**Comment by OdinVex** [comment]
This is a Linux Mint applet...and modern Mint uses Xed, not Gedit. Perhaps you could use 'xdg-open' instead so our own default editors are used instead.

**Comment by Aminur670** [comment]
Thanks Linuxmint/Cinnamon-Spices-Applets

**Comment by OdinVex** [comment]
I'd also suggest maybe using multiple paths for Apache and PHP. Apache's Documentation has a page dedicated to to determining the default locations of Apache per-distro. PHP seems to have changed v7 onward.

**Comment by Aminur670** [comment]
Thanks for your suggestion.
I Found more things need to changed.
Last night switches didn't worked correctly on Mint 19.
I will be looking for it.

**Comment by jerrywham** [comment]
While waiting for a proper pull request, here's a correction for LinuxMint 19.3.
FIle applet.js, line 9 to 22 :
```javascript
const AppletDir = imports.ui.appletManager.appletMeta[UUID].path;

//applet command constants
var CommandConstants = new function() {
  this.COMMAND_START_APACHE = AppletDir + "/scripts/script_apache_start.sh";
  this.COMMAND_STOP_APACHE = AppletDir + "/scripts/script_apache_stop.sh";
  this.COMMAND_START_MYSQL = AppletDir + "/scripts/script_mysql_start.sh";
  this.COMMAND_STOP_MYSQL = AppletDir + "/scripts/script_mysql_stop.sh";
  this.COMMAND_APACHE_CONFIG_EDIT = "xed admin:///etc/apache2/sites-enabled/000-default.conf";
  this.COMMAND_PHP_CONFIG_EDIT = "xed admin:///etc/php/7.2/apache2/php.ini";
  this.COMMAND_LAUNCH_PHPMYADMIN = "xdg-open http://localhost/phpmyadmin/";
  this.COMMAND_LAUNCH_WEBDIR = "xdg-open http://localhost/";
  this.COMMAND_OPEN_WEBDIR = "nemo /var/www/";
}
```
`xed admin://` is the new syntax to edit a file with sudoer privileges.
For services, you may use pkexec as below.

Create `scripts` a sub-directory in applet dir `web-developer-menu@infiniteshroom` and create 4 files `scripts/script_apache_start.sh`, `scripts/script_apache_stop.sh`, `scripts/script_mysql_start.sh` and `scripts/script_mysql_stop.sh`.

For Mysql scripts, enter this 2 lines : 
```bash
#!/bin/bash
pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY systemctl restart mysql
```
(change restart by stop in one of them).
Idem for apache :

```bash
#!/bin/bash
pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY service apache2 restart
``` 
For this four files, open a terminal and enter this cmd :
```bash
sudo chmod a+x .local/share/cinnamon/applets/web-developer-menu@infiniteshroom/script_apache_start.sh
sudo chmod a+x .local/share/cinnamon/applets/web-developer-menu@infiniteshroom/script_apache_stop.sh
sudo chmod a+x .local/share/cinnamon/applets/web-developer-menu@infiniteshroom/scripts/script_mysql_stop.sh
sudo chmod a+x .local/share/cinnamon/applets/web-developer-menu@infiniteshroom/scripts/script_mysql_start.sh
```

Restart cinnamon pressing buttons `alt+F2+r`

**Comment by Aminur670** [comment]
Thanks A lot for you useful contribution.

**Comment by Padre2** [comment]
@claudiux  In our last communications 21/22 February, I was suffering from roof and ceiling leaks and a failed HDD - much to relate, but not here.  I reinstalled Ubuntu Cinnamon Remix, but got Ubuntu ver. 20.10 by mistake and can only install PHP 7.4, because older versions not yet available, even on PPA repositories. I installed the Web Developer Menu again and have everything working.  However, the commands that require sudo require authentication rather defeats the purpose of the applet. These commands could easily be done by using alias. In case you are interested, the code I used is as follows:

`//applet` command constants
var CommandConstants = new function() {
  this.COMMAND_RESTART_APACHE = "systemctl restart apache2";
  this.COMMAND_STOP_APACHE = "systemctl stop apache2";
  this.COMMAND_START_MYSQL = "systemctl start mysql";
  this.COMMAND_STOP_MYSQL = "systemctl stop mysql";
  this.COMMAND_APACHE_CONFIG_EDIT = "gedit admin:///etc/apache2/sites-enabled/000-default.conf";
  this.COMMAND_PHP_CONFIG_EDIT = "gedit admin:///etc/php/7.4/apache2/php.ini";
  this.COMMAND_LAUNCH_PHPMYADMIN = "xdg-open http://localhost/phpmyadmin/";
  this.COMMAND_LAUNCH_WEBDIR = "xdg-open http://localhost/";
  this.COMMAND_OPEN_WEBDIR = "nemo /var/www/";
}`
To use in Mint the text editor may need to be changed.

 `onapacheSwitchPressed: function(item){
    this.menu.toggle(); 
    if(item.state){
      Util.spawnCommandLine(CommandConstants.COMMAND_RESTART_APACHE);
    }

    else {
      Util.spawnCommandLine(CommandConstants.COMMAND_STOP_APACHE);
    }
  },`
  
The code I wrote for use in Arch works flawlessly and is very useful, especially when switching PHP versions.
If there is no easy way to replace the gksu and avoid authentication, as in the original coding, the applet is not so useful. If this is the case, I propose to close this issue.

**Comment by claudiux** [comment]
Thanks for these contributions. I'll see what I can do.

**Comment by Aminur670** [comment]
Thanks a lot brother.
I will update asap

**Comment by Padre2** [comment]
@claudiux  After several recent Arch updates, the MySQL Server button did not change from off when toggled, although the server status changed from off to on and LAMP worked as usual after clicking.
I changed the line:
`this.mysqlEnabledSwitch.setToggleState(checkService("mysql"));   //reload state`
to
`this.mysqlEnabledSwitch.setToggleState(checkService("mariadb"));   //reload state`
and all is well.
I am not sure what changed because I have been using MariaDB all along.

**Comment by Padre2** [comment]
My version for Arch has worked without any need for using `sudo` or any issues for well over a year.  In addition to having PHP 7.2 , 7.3 and 7.4 in LAMP, I have recently added PHP 8.0. All run without any issues and switching the PHP version to be used in the server is made so much easier with this applet. 
I don't presently have  a drive to install Ubuntu so am unable to contribute further to the original version at this time, so will close this issue.
