### ISSUE TITLE
The vpnLookOut@claudiux applet uses only the tun0 interface.

### ISSUE THREAD

**Issue by Bundy01** [linuxmint/cinnamon-spices-applets#2824]
```
 * Applet version/Build date: 3.4.2
 * Cinnamon version: 4.4.8
 * Distribution: Arch
 * Graphics hardware *and* driver used: Intel
 

 ```

**Notify author of applet**
@claudiux

**Issue**
this applet is great but only handles the tun0 interface. My vpn creates a 'VPN_name-server' interface when I use a protocol other than Open-VPN. I noticed when manually removing the tun0 interface, it worked. But if I change server and want to redo the manipulation, the applet makes X crash.
Maybe the solution would be to automatically remove the interface at applet startup and to be able to refresh with the menu when the user changes server.

Regards.

**Steps to reproduce**
**For X crash:** Connect to a server whose interface is not 'tun0' and try to change the interface manually in the applet settings.

**Comment by claudiux** [comment]
@Bundy01 OK, I will try to make this applet use other interfaces than tun0. Thanks for reporting this issue.

**Comment by Bundy01** [comment]
The protocol used by the vpn is 'wireguard'.

**Comment by claudiux** [comment]
OK. I will test wireguard, using this doc (in French): https://www.tutos.snatch-crash.fr/wireguard-vpn-rapide-moderne-et-securise/

**Comment by claudiux** [comment]
@Bundy01 Please post here, using triple-backquotes, the return of the command `ls /sys/class/net/*`:

1. when all VPN are down.
2. when you are connected to a Wireguard VPN.

**Comment by Bundy01** [comment]
@claudiux 

no vpn:
```
/sys/class/net/enp3s0f1:
address
addr_assign_type
addr_len
broadcast
carrier
carrier_changes
carrier_down_count
carrier_up_count
device
dev_id
dev_port
dormant
duplex
flags
gro_flush_timeout
ifalias
ifindex
iflink
link_mode
mtu
name_assign_type
netdev_group
operstate
phydev
phys_port_id
phys_port_name
phys_switch_id
power
proto_down
queues
speed
statistics
subsystem
tx_queue_len
type
uevent

/sys/class/net/lo:
address
addr_assign_type
addr_len
broadcast
carrier
carrier_changes
carrier_down_count
carrier_up_count
dev_id
dev_port
dormant
duplex
flags
gro_flush_timeout
ifalias
ifindex
iflink
link_mode
mtu
name_assign_type
netdev_group
operstate
phys_port_id
phys_port_name
phys_switch_id
power
proto_down
queues
speed
statistics
subsystem
tx_queue_len
type
uevent

/sys/class/net/wlp2s0:
address
addr_assign_type
addr_len
broadcast
carrier
carrier_changes
carrier_down_count
carrier_up_count
device
dev_id
dev_port
dormant
duplex
flags
gro_flush_timeout
ifalias
ifindex
iflink
link_mode
mtu
name_assign_type
netdev_group
operstate
phy80211
phys_port_id
phys_port_name
phys_switch_id
power
proto_down
queues
speed
statistics
subsystem
tx_queue_len
type
uevent
wireless
```


with vpn:
```
/sys/class/net/enp3s0f1:
address
addr_assign_type
addr_len
broadcast
carrier
carrier_changes
carrier_down_count
carrier_up_count
device
dev_id
dev_port
dormant
duplex
flags
gro_flush_timeout
ifalias
ifindex
iflink
link_mode
mtu
name_assign_type
netdev_group
operstate
phydev
phys_port_id
phys_port_name
phys_switch_id
power
proto_down
queues
speed
statistics
subsystem
tx_queue_len
type
uevent

/sys/class/net/lo:
address
addr_assign_type
addr_len
broadcast
carrier
carrier_changes
carrier_down_count
carrier_up_count
dev_id
dev_port
dormant
duplex
flags
gro_flush_timeout
ifalias
ifindex
iflink
link_mode
mtu
name_assign_type
netdev_group
operstate
phys_port_id
phys_port_name
phys_switch_id
power
proto_down
queues
speed
statistics
subsystem
tx_queue_len
type
uevent

/sys/class/net/nordvpn-nl629:
address
addr_assign_type
addr_len
broadcast
carrier
carrier_changes
carrier_down_count
carrier_up_count
dev_id
dev_port
dormant
duplex
flags
group
gro_flush_timeout
ifalias
ifindex
iflink
link_mode
mtu
name_assign_type
netdev_group
operstate
owner
phys_port_id
phys_port_name
phys_switch_id
power
proto_down
queues
speed
statistics
subsystem
tun_flags
tx_queue_len
type
uevent

/sys/class/net/wlp2s0:
address
addr_assign_type
addr_len
broadcast
carrier
carrier_changes
carrier_down_count
carrier_up_count
device
dev_id
dev_port
dormant
duplex
flags
gro_flush_timeout
ifalias
ifindex
iflink
link_mode
mtu
name_assign_type
netdev_group
operstate
phy80211
phys_port_id
phys_port_name
phys_switch_id
power
proto_down
queues
speed
statistics
subsystem
tx_queue_len
type
uevent
wireless
```

Thanks.

**Comment by claudiux** [comment]
@Bundy01 Thank you. When you are connected to your wireguard VPN, is your `/tmp/.vpn_iface` file containing `nordvpn-nl629`?

**Comment by Bundy01** [comment]
I don't have a **.vpn_iface** file on /. I use the Linux application of my vpn, maybe that's why?

**Comment by claudiux** [comment]
Yes, but these values are used to automatically (re)connect to the latest VPN.

Please try to replace, in `4.2/applet.js` the lines 360-366

https://github.com/claudiux/cinnamon-spices-applets/blob/b25905dddff6f6747918f117af4121c431058560/vpnLookOut%40claudiux/files/vpnLookOut%40claudiux/4.2/applet.js#L363-L366

by these two lines:
```
            // Detect VPN interface:
            this.vpn_interface_detect();
```

Do the same near line 1326. Reload this applet and test it, please.

**Comment by Bundy01** [comment]
I applied the changes but the applet doesn't recognize the vpn connection (the icon remains grey). I post the changes in case I made a mistake:
```
            // Set initial value
            //this.set_applet_icon_path(this.vpnwait);

            // Make sure the temp files are created
            GLib.spawn_command_line_async('touch /tmp/.vpn_status /tmp/.vpn_name');

            // Detect VPN interface:
            this.vpn_interface_detect();


            this.applet_running = true; //** New to allow applet to be fully stopped when removed from panel
            this.is_deactivated = false;
            this.active_status_message = _("Deactivate vpnLookOut");
            this.active_status_icon = "media-playback-pause-symbolic";
            if (this.deactivateAtStartup && this.reactivationRequested === false) {
                this.switch_activation();
            }
            this.reactivationRequested = false;
```


```
            // Before to reload this applet, stop the loop, remove all bindings and disconnect all signals to avoid errors.
            this.on_applet_removed_from_panel();
            // Reload this applet with dependencies installed
            GLib.spawn_command_line_async('sh ' + this.appletPath + '/../scripts/reload_ext.sh')
        }

        // Inhibits also after the applet has been removed from the panel
        if (this.applet_running == true) {
            // Detect VPN interface:
            this.vpn_interface_detect();


            this.updateUI(); // update icon and tooltip

            // Force truncation of the log file, once a day:
            this.next_truncation -= this.refreshInterval;
            if (this.next_truncation < 0) {
                this.next_truncation = 86400; // 86400 seconds = 1 day
                this.activityLog.truncate_log_file();
            }

```

**Comment by claudiux** [comment]
@Bundy01 I am completely rewriting the code of this applet in order to take into account any type of VPN, including Wireguard.

**Comment by Bundy01** [comment]
Must have taken a big job for you.
Thanks for the effort.

**Comment by claudiux** [comment]
@Bundy01 Please try my new applet VPN-Sentinel: https://cinnamon-spices.linuxmint.com/applets/view/368

**Comment by Bundy01** [comment]
Hi,

the applet does not start, I copy the LookingGlass report:

```
error t=2023-05-04T16:03:00Z L’ouverture du fichier « ~/.configs/cinnamon/spices/VPN-Sentinel@claudiux/VPN-Sentinel@claudiux.json » a échoué : Aucun fichier ou dossier de ce type
trace t=2023-05-04T16:03:00Z
<----------------
VPNSentinel@~/.local/share/cinnamon/applets/VPN-Sentinel@claudiux/applet.js:196:50
main@~/.local/share/cinnamon/applets/VPN-Sentinel@claudiux/applet.js:1402:12
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:597:25
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:372:34
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:98:14
_init/<@/usr/share/cinnamon/js/ui/extension.js:276:32
---------------->
info t=2023-05-04T16:03:00Z Role locked: windowattentionhandler
info t=2023-05-04T16:03:00Z Loaded applet window-list@cinnamon.org in 59 ms
info t=2023-05-04T16:03:00Z Loaded applet sound@cinnamon.org in 25 ms
error t=2023-05-04T16:03:00Z
[VPN-Sentinel@claudiux]: Applet VPN-Sentinel@claudiux: Could not create applet object.
[VPN-Sentinel@claudiux]: Error importing applet.js from VPN-Sentinel@claudiux
trace t=2023-05-04T16:03:00Z
<----------------
_init/<@/usr/share/cinnamon/js/ui/extension.js:277:23
---------------->
```
I also have a question about dependencies. Why use `yad` and `sox` ? The system is more likely to have `zenity` and `ffmpeg` installed.
To play a system sound, the command is `ffplay`.

For the `networkmanager-openvpn` dependency, it would be nice if the user could install it as an option. If he uses Wireguard, the package is useless for him.

A small correction, on Archlinux, the `bind-tools` package does not exist. It is just `bind`.

Regards.

**Comment by claudiux** [comment]
@Bundy01 
Please try the latest version of VPN-Sentinel. I fixed the bug reported in LookingGlass.

About yad: Some options of yad don't exist in zenity.
About ffmpeg: No, it is not so frequently installed. But I will consider it.
About networkmanager-openvpn, you are right. But some friends IRL didn't understand why they can't install openvpn VPN with NetworkManager. I will try to find a solution... knowing that the user manuals are almost never read.

`bind` instead of `bind-tools` for Archlinux. I will correct that.

Many thanks to you!

**Comment by Bundy01** [comment]
@claudiux 
The applet is functional. If I see any errors, I'll let you know.
It didn't ask me to install `bind`.

For `ffmpeg` , I prefer it to `sox` , as the latter has some known security problems: https://security.archlinux.org/AVG-2100

For `openvpn`, why not include a description in the applet parameters?

Thank you.

**Comment by claudiux** [comment]
I'm thinking of an interface for installing dependencies that would allow you to choose between different proposals (`sox` or `ffmpeg` to produce sound?) with descriptions.
Access to this interface would be the only option in the applet menu until all dependencies are satisfied.
This interface could also be used to install certain non-mandatory packages, such as `networkmanager-openvpn`.

This will take time and complicate the applet code, but I think it's worth it.

**Comment by claudiux** [comment]
Little change for `bind` in Arch: #4877

**Comment by Bundy01** [comment]
@claudiux :
I just discovered a cinnamon dependency on Arch: `gsound`.
This package can play audio files with this command: `gsound-play -f YOUR_FILE.oga`

If this dependency is also on your distro, it would remove dependencies on sox or ffmpeg.

**Comment by claudiux** [comment]
In Linux Mint `gsound-play` is in the `gsound-tools` package which isn't a Cinnamon dependency.
