### ISSUE TITLE
bing-wallpaper@starcross.dev is loosing wp-name

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-spices-applets#2825]
@Starcross 
Hi, I noticed that the WP-Applet is loosing the mouse-over name of the current picture when rebooting, logging off and in again or just restarting Cinnamon. After loading a new picture its name is loaded normally.

As I did'nt know how to save the name I tried a different solution: get the name again (only the name, not the picture and only if it's different from the default). That happens after the next loop (5 min.).
Do you mind if I provide a pull request? Of course you could decline or change it as you like.

Greetings

**Comment by Starcross** [comment]
Yes pull requests welcome. I may rework this to save all the data pulled in the json locally, but your fix sounds like a good way around this for now.
