### ISSUE TITLE
weather@mockturtl applet is not unloading/reloading properly

### ISSUE THREAD

**Issue by Gr3q** [linuxmint/cinnamon-spices-applets#2831]
```
 * Applet version/Build date: Irrelevant, the bug persisted over multiple versions.
 * Cinnamon version: 4.4.8
 * Distribution - Arch
 * Graphics hardware *and* driver used
 ```
**Issue**
On Moving/Updating/Removing/Adding **any** applet on the Panel where the Weather applet is, there is a chance of the weather applet's main loop remain, this can cause the applet updating several times for van update interval, causing API call limits to saturate.

**Steps to reproduce**
1. Move/Update/Remove/Add any applet on the panel where the Weather applet is.
2. Wait and check the logs that the weather is updated multiple times over the set "update interval setting"
(I've added DEBUG more logs for my branch to observe my RefreshLoop function since then)

**Expected behaviour**
Only one of the applet's loop remain.

**Comment by Gr3q** [comment]
The problem is [here](https://github.com/linuxmint/cinnamon-spices-applets/blob/7d4f73ae3e55de257caa0c702c0d339993a9f089/weather%40mockturtl/src/applet.ts#L452). Multiple loops can remain and work in parallel. 

On my branch I switched to an async version of this function but it still relies on the same function so it behaves the same.

Any ideas what I can do do prevent this happening?

Some more info: applet ID is the same for all remaining loops.

What I came up with as a workaround:
So, multiple instances exist with the same instanceID and still work. I generate a uuid4 for the applet and save it to a global variable and in the applet class for each instanceID.

Every time the applet gets reloaded it saves that uuid4 to the global variable.
Then I check in the loop if the uuid4s match. If not, I stop the loop. I also have to use a global lock variable to prevent race conditions.

Log when 3 instances are running on top of each other:
```
info t=2020-01-25T19:22:56Z [weather@mockturtl#78]: Loop began 
 On Line: applet.js:334:17
info t=2020-01-25T19:22:56Z [weather@mockturtl#78]: 55ee3cab-07a0-4054-8f70-de90b6ec3281 
 On Line: applet.js:335:17
info t=2020-01-25T19:22:56Z [weather@mockturtl#78]: 8fd11675-f32d-42e8-a4c7-0e7d5d2192b6 
 On Line: applet.js:336:17
info t=2020-01-25T19:22:56Z [weather@mockturtl#78]: No need to update yet, skipping 
 On Line: applet.js:359:21
info t=2020-01-25T19:23:00Z [weather@mockturtl#78]: Loop began 
 On Line: applet.js:334:17
info t=2020-01-25T19:23:00Z [weather@mockturtl#78]: bf43c4d9-631c-4e3a-be53-0e31135b6114 
 On Line: applet.js:335:17
info t=2020-01-25T19:23:00Z [weather@mockturtl#78]: 8fd11675-f32d-42e8-a4c7-0e7d5d2192b6 
 On Line: applet.js:336:17
info t=2020-01-25T19:23:00Z [weather@mockturtl#78]: No need to update yet, skipping 
 On Line: applet.js:359:21
info t=2020-01-25T19:23:03Z [weather@mockturtl#78]: Loop began 
 On Line: applet.js:334:17
info t=2020-01-25T19:23:03Z [weather@mockturtl#78]: 8fd11675-f32d-42e8-a4c7-0e7d5d2192b6 
 On Line: applet.js:335:17
info t=2020-01-25T19:23:03Z [weather@mockturtl#78]: 8fd11675-f32d-42e8-a4c7-0e7d5d2192b6 
 On Line: applet.js:336:17
info t=2020-01-25T19:23:03Z [weather@mockturtl#78]: No need to update yet, skipping 
 On Line: applet.js:359:21

```

**Comment by Gr3q** [comment]
@Odyseus do you know that is there a way to know when the applet is unloaded? Would be much better than what I came up with for this issue.

**Comment by Odyseus** [comment]
Hello, @Gr3q.

There is a new function called [on_applet_reloaded](https://github.com/linuxmint/cinnamon/blob/master/js/ui/applet.js#L407) added around Cinnamon 4.0.x in [6a9eaa6](https://github.com/linuxmint/cinnamon/commit/6a9eaa61fd8162c7debe1fdda33f03dbfe238e83). But I don't know if it's triggered when *moving/updating/removing/adding any applet*.

To prevent unnecessary API quota consumption in my own fork of this applet, I simply store the data received and the time it was retrieved into a `generic` setting. The loop in my fork runs every 60 seconds, if the difference between the retrieved time of the stored data and the current time isn't greater than the update interval, there is no attempt to retrieve new data.

**Comment by Gr3q** [comment]
I see ```on_applet_removed_from_panel```, I checked its in at least from 3.0 and its called when the applet is moved or other applets moved next to it.

I think I will use that, and the uuid4 method as well for good measure. I don't want this bug to creep back in any form.
