### ISSUE TITLE
weather@mockturtl minor language things

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#2835]
```
 * Applet version/Build date 2.3.7 (2020-01-21 00:16:39)
 * Cinnamon version 4.4.8
 * Distribution - Mint 19.3
 * Graphics hardware Intel Corporation Haswell-ULT Integrated Graphics Controller i915
 ```
@Gr3q

**Issue**
The text "Feels Like" is not translated to your chosen language in other languages than English.
The Configuration page also need some work regarding localization?

**Steps to reproduce**
Click on applet logged in with a language not English with DarkSky as provider and see Feels Like.

**Expected behaviour**
The text should be translated to your chosen language.

**Other information**
The workaround seems to be adding a colon character in the po-file to:
```
#: 3.0/darkSky.js:135 3.8/darkSky.js:87
msgid "Feels Like:"
```
Have not looked any further about the configuration page.

**Comment by Gr3q** [comment]
Yes, it is my mistake changing the string a couple of times.

I moved the colon out from the string, it shouldn't really be there and I went through all the translation files this time to make sure all of them are correct.

It will be in the next update.
