### ISSUE TITLE
[CinnVIIStarkMenu@NikoKrause]: live search results

### ISSUE THREAD

**Issue by ak1dd** [linuxmint/cinnamon-spices-applets#2840]
Arc Menu has come a long way.  One of the very best features is the option to show "live search" results from the store and filesystem as you type.    Would really love this in StarkMenu

**Comment by icarter09** [comment]
@NikoKrause

**Comment by NikoKrause** [comment]
The search results feature is the same as in the original Cinnamon menu.
Today I pushed the upstream improvements for search results. The menu entries do get reordered now. It's pretty great in my opinion.

But it doesn't have live search results or system search results. Maybe the search providers are an alternative for you: https://github.com/linuxmint/cinnamon/issues/8453
