### ISSUE TITLE
Weather (weather@mockturtl): German translation got raped after trying to fix it

### ISSUE THREAD

**Issue by Kabuse** [linuxmint/cinnamon-spices-applets#2844]
Referring to my previous issue of German translation of "Cloudiness" and missing ":".

 "Cloudiness" still not translated and missing ":" is now "::"

Furthermore, most of the German translations are truncated, please see the  picture:

Heute ->  ute, "Hu" missing
Morgen -> rgen "Mo" missing
Sonnenaufgang -> nnenaufgang "So" missing
Sonnenuntergang -> nnenuntergang "So" missing
Regen (in the status bar) -> Gen "Re" missing, G should not be capital letter

I really don't want to complain, but this is much more worse than before my first issue report...

![Bildschirmfoto vom 2020-02-03 21-39-37](https://user-images.githubusercontent.com/13647006/73690107-f0c77700-46cf-11ea-9566-5c11b2fe7b56.png)

**Comment by Gr3q** [comment]
You are right, it is much worse.

The double ```::``` got fixed already (https://github.com/linuxmint/cinnamon-spices-applets/pull/2842), there should be a new update showing up.

About the other issue, I see even the km/h and the hPa is cut off, I don't know what causes it, but I'll look into it. I can't reproduce it at the moment.

In the meantime, update the applet and restart cinnamon and see if its any better.

**Comment by Gr3q** [comment]
@Kabuse is it still an issue?

**Comment by Kabuse** [comment]
I installed the following version today, and everything seems to be fine now:

Version 2.4.1 (2020-02-11 21:52:35)

Thank you very much!

![Bildschirmfoto vom 2020-02-13 19-35-30](https://user-images.githubusercontent.com/13647006/74466990-9204b900-4e98-11ea-8950-64748823a906.png)
