### ISSUE TITLE
weather@mockturtl, the config window is wider than desktop, can't read all

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#2853]
"name": "Weather", 
    "version": "2.4.1", 
    "last-edited": 1581269639, 
    "uuid": "weather@mockturtl"

Cinnamon 3.6.7

Linux Mint 18.3
Default video driver for Quad core Intel Core i7-8550U (-HT-MCP-) cache: 8192 KB
No errors, this is a visual bug

**Issue**
Right click -> config produces the config window that is wider than the screen.  It cannot be scaled down.   You have to slide the window left / right to read and make changes.

**Steps to reproduce**
See above.

![Weather1](https://user-images.githubusercontent.com/26556059/74194026-75f9e100-4c26-11ea-81bf-c59161010330.png)
![Weather2](https://user-images.githubusercontent.com/26556059/74194027-76927780-4c26-11ea-9e64-ced3c5b9136b.png)

**Comment by Gr3q** [comment]
I'll get it fixed as soon as possible

**Comment by ChooChooAl** [comment]
Thanks.  Works great.   I picked the two files from here.
