### ISSUE TITLE
weather@mockturtl

### ISSUE THREAD

**Issue by eduardoxfurtado** [linuxmint/cinnamon-spices-applets#2860]
```
 * Applet version 2.4.1 (2020-02-09 12:33:59)
 * Cinnamon version 4.4.8
 * Distribution - manjaro 18
 ```

**Notify author of applet**
@mockturtl 

**Issue**
"Display current temperature in panel" does not work when the panel is vertical.

**Steps to reproduce**
Move the panel do any vertical position.

**Expected behaviour**
Current temperature should be shown right below the icon.

**Other information**
If you move the panel to a horizontal position, it will show the temperature next to the icon.
If you move the panel back to a vertical position, it will briefly show the temperature below the icon, and then disappear.

**Comment by Gr3q** [comment]
You are right, it should show it.

Even when I explicitly set to show, it still isn't showing the applet label (it is the default, anyway)

I'll look into it a bit further, but at first glance I can't tell if its the applet's issue or something else's

**Comment by Odyseus** [comment]
Hello, everybody.

@Gr3q : The applets labels on vertical panels is automatically hidden. Plus, you are hiding them every time you call `this.update_label_visible()` [in your code](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/weather%40mockturtl/files/weather%40mockturtl/3.8/applet.js#L373). Use the `set_show_label_in_vertical_panels` method introduced around Cinnamon 3.4.x (https://github.com/linuxmint/cinnamon/commit/3870e42fe58533598ef8998ffb7d6bd3f213cbec) to allow for labels to always show if not empty.

**Comment by Gr3q** [comment]
@Odyseus thanks, I wondered that bit of legacy code did. Now I know. Time and time again I have to remind my self if somethings is not working and don't know why, its usually my code not someone else's.

@eduardoxfurtado I will able to show the temperature, but not the condition (too long) in vertical panels in the next update. Is that all right?
