### ISSUE TITLE
Weather applet 2.4.1 "Overcast" icon needs a night version

### ISSUE THREAD

**Issue by garuffalo** [linuxmint/cinnamon-spices-applets#2861]
The panel icon for the condition, "Overcast" always shows the sun and clouds icon, rather than the dark moon and clouds icon associated with other conditions, such as "Partly Cloudy". Other icons seem to have day and night versions.

![Screenshot from 2020-02-13 11-19-05](https://user-images.githubusercontent.com/28717740/74456683-31a05800-4e55-11ea-856b-180b05a9ba14.png)

```
 * Applet version/Build date - 2.4.1 (2020-02-11)
 * Cinnamon version 4.2.4
 * Distribution - Mint 19.2 Cinnamon
 * Graphics hardware - Intel Mobile GM965/GL960 Integrated Graphics (driver: i915)

**Comment by Gr3q** [comment]
Hello,

Which weather provider do you use?
Also, the Overcast icon should have only clouds showing (the main problem), that's why there is no day/night version of it.

**Comment by garuffalo** [comment]
I use Dark Sky.

I wouldn't mind if the "Overcast" icon was the same as the one for "Partly Cloudy", as long as there were day and night versions. It's the yellow sun in the night time hours that seems weird.

**Comment by Gr3q** [comment]
I will make that happen in the next update. 

Also, could you tell me which icon set are you using? just for later reference. It seems to show the partly cloudy icon because your icon set does not contain an overcast or a cloudy icon.

**Comment by garuffalo** [comment]
Thank you.

I use the Adwaita icon set.
