### ISSUE TITLE
Icing task manager: Title in app button doesn't update when set to focused

### ISSUE THREAD

**Issue by Ninjabdou** [linuxmint/cinnamon-spices-applets#2865]
```
 * Applet version/Build date 6.3.13 09/27/2018 18:07 UTC
 * Cinnamon version (cinnamon --3.6.7)
 * Distribution - (Mint 18.3)
 * Intel Corp Mobile 4 series chipset
 * [xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/4216578/xsession-errors.txt)

 ```

@jaszhix

**Issue**
Title in app button doesn't update when set to focused

**Steps to reproduce**
Open the Icing task manager configure window, go to the **_Panel_** tab, set the title display to **_Focused_**
Open some app which title can change, like a browser or a file manager with multiple tabs opened (if you open different web pages in each tab the title of the button app should change according to the selected tab's title)
The title of the app button wont change unless you reduce/restore said window
Let's take an example, I open nemo, it will open in **Home** folder by default and the title indicates **Home**, now I open a new tab and go to **Documents** but the title still displays **Home**, I reduce the window then retore it, now it dislays **Documents** as title, I swith to the **Home** tab but the title still displays **Documents**

**Expected behaviour**
The title of the app button should change automatically like when the _**'Title display'**_ option is set to _**'Title'**_.

**Other information**

**Comment by NikoKrause** [comment]
This applet has been deleted:

https://github.com/linuxmint/cinnamon-spices-applets/commit/0c7493a1a2ae8ccb66011aa3c801c5215d84927f
