### ISSUE TITLE
weather@mockturtl OpenWeatherMap condition not translated to used locale 

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#2872]
```
 * Applet version/Build date - 2.4.3 / 2020-02-20 22:56 UTC
 * Cinnamon version - 3.6.7 and  4.4.8
 * Distribution - Mint 18.3 and 19.3
 * Graphics hardware - Intel Corporation Haswell-ULT Integrated Graphics Controller - i915
 * Snippet or attachment of ~/.cinnamon/glass.log
![Screenshot weather Swedish 2020-02-21 16-30-17](https://user-images.githubusercontent.com/5297223/75051439-2f31a400-54ce-11ea-91e2-9e49e95d3641.png)
[weather_243_log20200221.log](https://github.com/linuxmint/cinnamon-spices-applets/files/4236972/weather_243_log20200221.log)

 ```
**Notify author of applet**
@Gr3q

**Issue**
When using Weather provider OpenWeatherMap and current weather is Light rain and locale language is other than English the condition in the applet is not translated. 

**Steps to reproduce**
Choose a location with current weather Light rain and a language not English and open the applet.

**Expected behaviour**
That the current weather condition should be translated. 

**Other information**
 The upcoming forecast bellow the top current one seems to work translating Light rain correct.

**Comment by Gr3q** [comment]
@jorgenqv  is the condition displayed "Light rain"? Exactly like this?

Is it possible if you could enable debugging and paste some of the logs here? (you can redact it if you want)

The translated text supposed to come from OpenWeatheMap, like so:
```json
{
    "coord": {
        "lon": -5.93,
        "lat": 54.58
    },
    "weather": [
        {
            "id": 500,
            "main": "Rain",
            "description": "lätt regn",
            "icon": "10d"
        }
    ],
    "base": "stations",
    "main": {
        "temp": 283.82,
        "feels_like": 276.04,
        "temp_min": 283.15,
        "temp_max": 284.26,
        "pressure": 1003,
        "humidity": 81
    },
    "visibility": 10000,
    "wind": {
        "speed": 10.3,
        "deg": 220
    },
    "rain": {
        "3h": 1.31
    },
    "clouds": {
        "all": 100
    },
    "dt": 1582306526,
    "sys": {
        "type": 1,
        "id": 1376,
        "country": "GB",
        "sunrise": 1582270407,
        "sunset": 1582306902
    },
    "timezone": 0,
    "id": 2655984,
    "name": "Belfast",
    "cod": 200
}
```

I want to confirm it is not the case.

**Comment by jorgenqv** [comment]
Hello, yes I tried to attach screenshot and debug logs, see url:s under Snippet. Yes it's right on the panel but not if you exapnd and look at the top current, see screenshot:
https://user-images.githubusercontent.com/5297223/75051439-2f31a400-54ce-11ea-91e2-9e49e95d3641.png

**Comment by Gr3q** [comment]
Apart from the fact that it should translate "Light Rain", it actually does not add the language parameter to the url.

After a bit digging, it is happening because the Swedish language code is "sv", and OpenWeatherMap uses "se" so it comes out as not supported.

I will fix that and not the translations this time.
