### ISSUE TITLE
[search-box@mtwebster] Custom provider provider can not utilized correctly.

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-applets#2901]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (4.4.8)
 * Distribution - (Fedora 30 X64 bit Cinnamon edition)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@mtwebster 

**Issue**
When I tried to use a custom search provider, like https://search.disroot.org, then applet can not utilize it.

**Steps to reproduce**
1) enter setting of this applet
2) activate custom search provider
3) enter the following URL: https://search.disroot.org
4) try to search about "Baghdad" [the capital city of Iraq]

**Actual behaviour**
The Internet browser (FF in my case) will open on following URL:
https://search.disroot.orgbaghdad
which is non-existing URL !
The error is that search item(s) added to end of URL of search engine to be part of it, & this will lead to non-existing web page !

**Expected behaviour**
Should utilize search engine & show results for "Baghdad"

**Other information**
You can use any search items other than "Baghdad" & you will get same error.

**Comment by Gr3q** [comment]
Use the actual search URL disroot uses.

https://search.disroot.org?q=

**Comment by Nokia808** [comment]
@Gr3q 
Thank you ! I was not know about this !
