### ISSUE TITLE
Weather in Portuguese.

### ISSUE THREAD

**Issue by nogueira13** [linuxmint/cinnamon-spices-applets#2924]
How should I do to show the Weather applet in Portuguese in the Panel of my Linux Mint 19.3
```
 * Applet Version 2.4.6 (2020-03-12 19:39:01)
 * Cinnamon version (cinnamon --version)
 * Distribution - Linux Mint 19.3
 * Nvidia Graphic Card
 

 ```

**Notify author of applet**
@

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by brownsr** [comment]
someone has to do the translations, if you look at the past commit history of that applet you will see numerous examples.
