### ISSUE TITLE
weather@mockturtl: Ambigous string for translation in source text

### ISSUE THREAD

**Issue by sveinki** [linuxmint/cinnamon-spices-applets#2929]
```
 * Version 2.4.6 (2020-03-12 22:39:01)
 ```
**Notify author of applet**
@mockturtl

**Issue**
The string number 221 (and 251) in the POT-file begins as follows:
"WeatherBit - Minimum of 10min refresh rate is recommended or you might exceed you daily quota."

I was wondering if this wasn't a bit confusing, at least I had to read it several times to grasp the (hopefully correct) meaning. Perhaps it could be rather like this:
"WeatherBit - At least 10 minutes as refresh rate is recommended, since otherwise you might exceed you daily quota."

I know it's a bit of nitpicking, but somehow the original phrase seems for me to be inviting to lower the refresh rate to something less than 10 minutes. Which is of course not the case.

**Comment by Gr3q** [comment]
If other people agree with you I'm happy to change it.

**Comment by sveinki** [comment]
NB: I'm not a native English-speaker, so best would be to have a native one to decide on this.

**Comment by fosterjoelr** [comment]
Sounds easy enough to understand to this English grammatically inclined, but, poor representation therefof. I'd vote aye.
