### ISSUE TITLE
temperature@fevimu: strange behaviour, applet increasing CPU temperature?

### ISSUE THREAD

**Issue by Kallys** [linuxmint/cinnamon-spices-applets#2940]
* Applet version/Build date: Updated on 2020-03-14 16:11:48
 * Cinnamon version: Cinnamon 4.4.8
 * Distribution: Linux Mint 19.3 Tricia
 * Graphics hardware *and* driver used:
 ```
VGA compatible controller: Intel Corporation Device 3e9b
	Subsystem: Micro-Star International Co., Ltd. [MSI] Device 1215
	Kernel driver in use: i915
	Kernel modules: i915
VGA compatible controller: NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev a1)
	Subsystem: Micro-Star International Co., Ltd. [MSI] GP106M [GeForce GTX 1060 Mobile]
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia
 ```
Actually using nvidia-driver-440 version 440.64-0ubuntu0~0.18.04.2.
 * Snippet or attachment of ~/.cinnamon/glass.log: empty file
 * Snippet or attachment of ~/.xsession-errors: Mainly an infinity of following lines
 ```
(caribou:4731): GLib-GObject-CRITICAL **: 10:27:15.551: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
 ```

**Notify author of applet**
@claudiux

**Issue**
Strange behaviour using applet temperature@fevimu.
When my laptop is idling, applet show an average CPU temperature of 70°C. When I disable the applet, and watch CPU temperature using command line or xsensors, average temperature is 50°C. When I'm on Windows, average CPU temperature is 50°C too.

Moreover, when applet is enabled, and I start watching sensors files, applet temperature decrease, but effectively starts at the previous value shown, as if the applet itself, when it watch for temperature by itself, increase temperature.

Following gif shows what I'm trying to explain:
![](https://i.imgur.com/m9TvJ8r.gif)

1. watching on "/sys/class/thermal/thermal_zone2/type" does nothing, which is normal since applet is using sensors which uses coretemp
2. watching on "sensors" package id line show first same temperature as applet, and then rapidly decrease
3. stop watching on "sensors", applet temperature increase
4. same as 2. when watching on "/sys/devices/platform/coretemp.0/hwmon/hwmon3/temp1_label"
5. same as 3.

Additional infos: 
```
$ cat /sys/class/thermal/thermal_zone2/type 
x86_pkg_temp
$ cat /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp1_label 
Package id 0
```
Applet refreshing time set to 2000ms.
lm-sensors version: 1:3.4.0-4

**Steps to reproduce**
See description above.

**Expected behaviour**
Enabling applet should not increase CPU temperature.

**Other information**
I can't understand what can cause this issue so I'm really not sure about this applet responsibility, maybe it's just something wrong in my laptop config, but I see 100% reproducibility when enabling and disabling this applet (and ear my laptop fans noisier when enabled).

Thanks!

**Comment by claudiux** [comment]
@Kallys Thank you for this info. I rewrite certain parts of this applet to take into account specific sensors that the user can choose from a list.

**Comment by claudiux** [comment]
@Kallys Maybe related with https://github.com/linuxmint/cinnamon/issues/9085 ?

**Comment by claudiux** [comment]
@Kallys I just created the [Sensors@claudiux](https://cinnamon-spices.linuxmint.com/applets/view/337) applet. It aims to replace temperature@fevimu.

Can you test it out and give me your feedback, please?

Regards.
Claudiux

**Comment by Kallys** [comment]
Hi! I can't reproduce this issue with Sensors@claudiux.
