### ISSUE TITLE
Weather (weather@mockturtl)

### ISSUE THREAD

**Issue by French77** [linuxmint/cinnamon-spices-applets#2941]
Weather (weather@mockturtl)
```
 * Version 2.4.7 (2020-04-03 09:34:25)
 * 4.4.8 
 * Mint 19.3 
 
 


 ```

**Notify author of applet**
@mockturtl 

**Issue**
Translation

**Other information**
These changes don't seem to have been implemented in the translation files (pot.po files)

![weather@mockturl pot](https://user-images.githubusercontent.com/3099270/78403256-5ebeea80-75fc-11ea-9504-dc453b1a8bf4.png)
The dutch translation change (po file),has no effect
![Vertaling Nederlands](https://user-images.githubusercontent.com/3099270/78403943-aa25c880-75fd-11ea-839d-dfedd6c4e139.png)

**Comment by Gr3q** [comment]
Yes, I changed that piece of text as requested, and I forgot to update the pot file, mainly because I'm an idiot.

I'll do that today.

**Comment by French77** [comment]
Oke no problem at all.Thank you for your answer.

**Comment by French77** [comment]
@Gr3q :up: thanks for updating the pot file,dutch translation has been completed. @French77
