### ISSUE TITLE
weather@mockturtl Displays temperature unit even when temperature on panel is disabled

### ISSUE THREAD

**Issue by prcr** [linuxmint/cinnamon-spices-applets#2970]
```
 * Applet version/Build date: Version 2.4.8 (2020-04-21 08:17:07)
 * Cinnamon version: Cinnamon 4.4.8
 * Distribution: Mint 19.3
 ```

**Notify author of applet**
@mockturtl

**Issue / Steps to reproduce**

Even if I disable the option **Display current temperature in panel**, the applet still shows the selected temperature unit (ºC or ºF), just without the actual temperature value.

![image](https://user-images.githubusercontent.com/436692/79995869-ab853b00-84af-11ea-8245-3731753a3ce8.png)

**Expected behaviour**

When the option **Display current temperature in panel** is disabled I expect both the temperature and its unit to disappear from the panel.

**Other information**

If I set a value for "Override label on panel", the temperature unit does get substituted by the string that I enter in the field.

**Comment by Gr3q** [comment]
Indeed, the logic dealing with that is in the wrong place.
