### ISSUE TITLE
weather@mockturtl: sunset/sunrise time is in GMT with Weatherbit.

### ISSUE THREAD

**Issue by Bundy01** [linuxmint/cinnamon-spices-applets#2977]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
2.4.9

 * Cinnamon version (cinnamon --version)
Cinnamon 4.4.8

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch

 * Graphics hardware *and* driver used
Intel

 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@mockturtl

**Issue**
Hi,
I noticed that the sunrise and sunset times with the Weatherbit provider were in GMT format.
This is the only provider that is in this case, is this issue due to the applet or is it a Weatherbit error?
Regards.

**Steps to reproduce**
Use the Weatherbit provider.

**Comment by Gr3q** [comment]
@Bundy01 Hi, do you mean the sunset/sunrise times does not match your timezone, they are in GMT timezone instead?

**Comment by Gr3q** [comment]
I can see that seems to bee the case.

I see why now that I looked into it a bit, Weatherbit only returns a string with "hh:mm" format - unlike the others what return unix dates - what I convert to dates to fit into the applet. This wouldn't be the problem in itself, but **Weatherbit does not return in DST, but GBP instead, not the correct time.**

I'll have to do some nasty hack for this to know when they return incorrect time.
