### ISSUE TITLE
weather@mockturtl: changes in openweathermap API

### ISSUE THREAD

**Issue by G4Zz0L1** [linuxmint/cinnamon-spices-applets#2980]
```
 * Applet version/Build date: 2.4.9 (2020-04-22 21:13:45)
 * Cinnamon version: Cinnamon 4.4.8
 * Distribution: Arch
 ```

**Notify author of applet**
@mockturtl 

**Issue**
With the latest versions, (the unified API of openweathermap), manual location has stopped working with some formats. That's because the new API doesn't work with the other methods like the old ones (as seen in the readme).

![image](https://user-images.githubusercontent.com/13220636/80278984-eb8c2e00-86fa-11ea-83e1-ef2dd149f31b.png)

The new unified API works only with lat and lon, as seen in their docs:

![image](https://user-images.githubusercontent.com/13220636/80279022-2aba7f00-86fb-11ea-8ed3-95e67e75402b.png)

Using lat and lon works, but users will lose the other methods for fetching datas (to me the most breaking change was to lose the name of the location in the applet)

I think that there's two solutions:
- revert to the old method (with the normal API)
- or change the readme only with the new format

**Comment by Gr3q** [comment]
Yes, that was an oversight on my part. Do you mean that the location got deleted from the settings?

I'm not gonna revert it, because it is part of the preparation for implementing Hourly forecasts. I'll change the readme. I know it is an inconvenience, but for now OpenWeatherMap's finder can be used to get the coordinates.

If there is a demand for it, I can create some utility what you guys can use to search for and save coordinates more easily. Please open an issue for it here if it's something you want to see.

**Comment by G4Zz0L1** [comment]
Location it's in the settings as usual, but it doesn't work with city or zipcode, only works with lat and lon.

The openwheatermap finder works fine for that, I don't think another tool to save lat and lon is needed.

It's there a chance to show the city name on the applet like before? I always used the manual location with my city, which worked fine. Now the applet only prints the coordinates I use in the settings. Maybe inserting a text input below the location input with a custom text?

**Comment by Gr3q** [comment]
In the Settings, Presentation section, there is a setting "Override location label". You can write whatever you want and it will be displayed as location.

Edit 1: I will see if it becomes a bigger issue, I suspect most people uses automatic location.
Edit 2: That would increase complexity greatly, both in logic and in settings (a lazy excuse to be honest), also it can lead unexpected behavior facing users (enabling hourly forecasts causes refresh error with WOEIDs and ZIP codes). 

I think OpenWeatherMap slowly moves to the onecall API so it is sensible to use that, hopefully they will expand the functionality to accept the same parameters as the old ones. I will write them an email noting my interest in id and zipcode support, and we will see what they say what their plans are.

**Comment by G4Zz0L1** [comment]
Perfect! I didn't remember that option, sorry. 
For the other things, we'll wait for OWM eventual changes then.
Thank you again!
