### ISSUE TITLE
sports-update@pavanred: has problem running and does not update the score at all

### ISSUE THREAD

**Issue by sammy1881** [linuxmint/cinnamon-spices-applets#299]
[Have you read the guidelines for contributing?]: <> (Before opening an issue, please read the guidelines for contributing linked above. Else the issue will be closed. Also don't forget to notify the author.)
@AppletAuthor

[Issue]: <> (Describe your issue below.)

The spice has problem running and does not update the score at all. I have installed it both by copying the files in githut in /applets folder and also gave it a shot by installing it from Applets menu in Settings.

The only error I could find was in ~/glass.log and it says **"sports-update@pavanred : Error parsing score updates URIError: malformed URI sequence"**

Hope this helps. I do not have much familiarity with JSON otherwise I would be happy to debug further.

**Comment by NikoKrause** [comment]
@sammy1881 
The author oft the applet is pavanred. So to notify him write @pavanred

**Comment by pavanred** [comment]
I do not actively maintain this applet anymore. I will try to find time to fix this issue. Meanwhile, if any one wants to take this up, I would be happy to help.

**Comment by icarter09** [comment]
@pavanred is this applet still available to be worked on? I'm not seeing the code for it in the applet repository.

**Comment by jaszhix** [comment]
This was removed because it had a number of issues needing to be fixed with no maintainer.

**Comment by brianfeaster** [comment]
I'm drinking beer with the original developer as we speak right now.
