### ISSUE TITLE
[betterlock] Notification remain sticky even after remove from panel or uninstall applet !!

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-applets#30]
Hi. I'm on Fedora 24 X64 bit Cinnamon edition (up to date OS + DE). I installed applet. I have strange bug !!

When I disable applet (remove it from panel) or even UN-INSTALL it , notifications will continue to appear each time I use click CapsLock or NumLock key !! I have to restart Fedora to remove this bug ! 

Please fix.

Thank you for your hard efforts.

**Comment by jaszhix** [comment]
Which applet? This is likely a problem with whatever applet you were using.

**Comment by Nokia808** [comment]
Applet name is:

Num Lock/Caps Lock indicator with MessageTray notifications by betterlock

UUID as shown in website is betterlock
