### ISSUE TITLE
Network Usage Applet doesn't read from vnstat-conf

### ISSUE THREAD

**Issue by thob** [linuxmint/cinnamon-spices-applets#3017]
Applet v1.02.2

so, I have my network set in vnstat.conf but the applet shows another. How can I tell the applet to read from the vnstat.conf? I'm on Ubuntu 18.04 with Cinnamon 4.2.4. Thanks

---

If I run vnstati in the cli it works though @pdcurtis

**Comment by pdcurtis** [comment]
@thob  When you install vnstat it should automatically be set up for all the network connections present on the machine at the time under Mint (or Ubuntu) and you should not need to do any further set up or change vnstat.conf. The only time you might want to change the vnstat set up is if you have to add an interface not controlled by the network manager such as a bluetooth modem or a USB Wifi stick. Modifying the vnstat configuration is fraught with difficulties.

The applet then displays the ACTIVE connection using vnstati and information _from the Network Manager_ at the time. There is little point in displaying interfaces not in use.

This is a basic applet originally written  by Clem as a simple demonstration which I have been keeping up to date for changes in the Network Manager and there are limited options available. I regret there are no plans to enhance it

The Network Data Usage Monitor I wrote is more flexible and can display data from ppp0 and Bluetooth PAN (bnep0) connections and has an option to display vnstat/vnstati information.

**Comment by thob** [comment]
Thanks, I see. Well, I had to change vnstat.conf in order to get any data at all in vnstat because it only had eth0 assigned. I'll the other one.

**Comment by thob** [comment]
I installed numo and it took some effort to change to the actual interface I want to monitor. It took initially the same one as the 1st applet
