### ISSUE TITLE
SpicesUpdate@claudiux not compatible

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-applets#3020]
```
 * Applet version/Build date permetadata.json:  5.3.0
 * Cinnamon version:  Cinnamon 4.6.0
 * Distribution:  Arch
 * Graphics hardware *and* driver used AMD/Radeon
 * Snippet or attachment of ~/.cinnamon/glass.log
error t=2020-05-16T11:36:36Z [SpicesUpdate@claudiux]: Extension is not compatible with current Cinnamon version
 * Snippet or attachment of ~/.xsession-errors
Cjs-Message: 11:36:36.519: JS LOG: [LookingGlass/error] [SpicesUpdate@claudiux]: Extension is not compatible with current Cinnamon version
 ```

**Notify author of applet**
@claudiux 

**Issue**
Not compatible with updated Cinnamon.

**Steps to reproduce**

**Expected behaviour**

**Other information**
Can be fixed by putting "4.6" in the metadata.json file

**Comment by Padre2** [comment]
Issue can be fixed by adding"4.6" to the metadata.json file.

**Comment by Padre2** [comment]
Today when trying to update an applet I get an error notification on the screen.
Error from LookingGlass:  
js-Message: 10:20:55.792: JS LOG: error: Execution of '/.local/share/cinnamon/applets/SpicesUpdate@claudiux/cs/4.6/cinnamon-settings.py desklets -t 1 -s update' failed:: Failed to execute child process “.local/share/cinnamon/applets/SpicesUpdate@claudiux/cs/4.6/cinnamon-settings.py” (No such file or directory).

**Comment by claudiux** [comment]
@Padre2 The next version of Spices Update is coming soon. (The past few months have been very hard for me.)

**Comment by Padre2** [comment]
@claudiux  Sorry to hear that, but good to hear from you. I hope not from Covid-19. Moi aussi - quelques mois difficiles.
