### ISSUE TITLE
Sticky-Notes-applet doesn't work on vertical panel

### ISSUE THREAD

**Issue by uocxp** [linuxmint/cinnamon-spices-applets#303]
It's not possible on a vertical panel to create a new Note. When clicking on _new note_ or _new check-list_ nothings happen.
I'm using Linux Mint 18.1 Serena.

**Comment by NikoKrause** [comment]
@collinss

**Comment by collinss** [comment]
I can't reproduce this on Cinnamon 3.4. New note worked fine for me (though it did overlap the panel). Could you please provide more detail such as anything in glass.log or .xsession-errors that might be related, your monitor/panel configuration, etc.

**Comment by uocxp** [comment]
**.xsession-errors:**
(cinnamon-settings-daemon:4441): color-plugin-WARNING **: failed to get edid: unable to get EDID for output

(cinnamon-settings-daemon:4441): color-plugin-WARNING **: unable to get EDID for xrandr-LVDS: unable to get EDID for output

(process:4527): indicator-sound-WARNING **: volume-control-pulse.vala:735: unable to get pulse unix socket: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.PulseAudio1 was not provided by any .service files

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:4514): libglade-WARNING **: unknown attribute `swapped' for <signal>.
INFO:guake.guake_app:Logging configuration complete
/usr/lib/python2.7/dist-packages/guake/guake_app.py:1785: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
  self.mainframe.pack_start(self.notebook, expand=True, fill=True, padding=0)
Cjs-Message: JS LOG: About to start Cinnamon
Could not set X locale modifiers
INFO:guake.notifier:Notification service is not running (yet). Guake can't display notifications!
  We'll retry a few times more a bit later, but you can use
  the following command to disable the startup notification:
$ gconftool-2 --type bool --set /apps/guake/general/use_popup false
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Tue May 09 2017 13:52:37 GMT+0200 (CEST)
Nemo-Share-Message: Called "net usershare info" but it failed: 'net usershare' returned error 255: mkdir failed on directory /var/run/samba/msg.lock: Permission denied
net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory
Please ask your system administrator to enable user sharing.

SendMessage (44040234, 0x112c, 0x4, 0x4)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
openGL version 3.3 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
failed to create drawable
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a0003f (Open Datab)
Cjs-Message: JS LOG: Invalid network device type, is 13
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: Invalid network device type, is 13
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active
Cjs-Message: JS LOG: network applet: Found connection for active
Cjs-Message: JS LOG: network applet: Found connection for active

(KeePass:4571): Gdk-CRITICAL **: IA__gdk_window_thaw_toplevel_updates_libgtk_only: assertion 'private->update_and_descendants_freeze_count > 0' failed

(indicator-stickynotes:4518): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(blueberry-tray.py:4521): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
/usr/lib/python2.7/dist-packages/guake/main.py:236: GtkWarning: IA__gdk_window_thaw_toplevel_updates_libgtk_only: assertion 'private->update_and_descendants_freeze_count > 0' failed
  gtk.main()

(cinnamon:4507): Clutter-CRITICAL **: clutter_actor_set_child_below_sibling: assertion 'child->priv->parent == self' failed
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x564f34bdafa0  Text: 0
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a00015 (KeePass)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a00015 (KeePass)
Cinnamon WARNING: Possible orphan label being accessed via st_label_set_text().  Check your timers and handlers!
Address: 0x564f33a67b60  Text: 0
/usr/lib/python2.7/dist-packages/guake/guake_app.py:825: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DOCK)
/usr/lib/python2.7/dist-packages/guake/guake_app.py:826: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_NORMAL)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x200004d (Guake!)

**Comment by uocxp** [comment]
**glass.log**:
info t=2017-03-30T13:49:01.511Z Cinnamon.AppSystem.get_default() started in 104 ms
info t=2017-03-30T13:49:01.515Z loading default theme
info t=2017-03-30T13:49:01.603Z PlacesManager: Updating devices
info t=2017-03-30T13:49:01.630Z loaded at Thu Mar 30 2017 15:49:01 GMT+0200 (CEST)
info t=2017-03-30T13:49:01.914Z Loaded applet menu@cinnamon.org in 281 ms
info t=2017-03-30T13:49:02.088Z Role locked: panellauncher
info t=2017-03-30T13:49:02.088Z Loaded applet IcingTaskManager@json in 174 ms
info t=2017-03-30T13:49:02.104Z Loaded applet panel-launchers@cinnamon.org in 15 ms
info t=2017-03-30T13:49:02.118Z Role locked: notifications
info t=2017-03-30T13:49:02.121Z Loaded applet notifications@cinnamon.org in 17 ms
info t=2017-03-30T13:49:02.148Z Loaded applet user@cinnamon.org in 26 ms
info t=2017-03-30T13:49:02.155Z Loaded applet removable-drives@cinnamon.org in 6 ms
info t=2017-03-30T13:49:02.172Z Loaded applet keyboard@cinnamon.org in 16 ms
info t=2017-03-30T13:49:02.225Z Loaded applet network@cinnamon.org in 52 ms
info t=2017-03-30T13:49:02.277Z Loaded applet sound@cinnamon.org in 51 ms
info t=2017-03-30T13:49:02.293Z Loaded applet power@cinnamon.org in 15 ms
info t=2017-03-30T13:49:02.304Z Loaded applet systray@cinnamon.org in 10 ms
info t=2017-03-30T13:49:02.322Z Loaded applet calendar@cinnamon.org in 17 ms
info t=2017-03-30T13:49:02.328Z Loaded applet windows-quick-list@cinnamon.org in 5 ms
info t=2017-03-30T13:49:02.338Z Loaded applet show-desktop@cinnamon.org in 9 ms
info t=2017-03-30T13:49:02.338Z AppletManager.init() started in 707 ms
info t=2017-03-30T13:49:02.341Z Cinnamon took 949 ms to start
info t=2017-03-30T13:49:02.803Z Hiding systray: network
info t=2017-03-30T13:49:02.804Z Adding systray: blueberry-tray.py (24x24px)
info t=2017-03-30T13:49:04.531Z Resized blueberry-tray.py with normalized size (22x22px)
info t=2017-03-30T13:49:06.542Z resolve!: "..."
info t=2017-03-30T13:49:22.202Z Adding systray: mintupdate.py (24x24px)
info t=2017-03-30T13:49:23.705Z Resized mintupdate.py with normalized size (22x22px)
info t=2017-03-30T13:49:48.769Z Adding systray: cli (24x24px)
info t=2017-03-30T13:49:50.272Z Resized cli with normalized size (22x22px)
info t=2017-03-30T13:52:02.859Z PlacesManager: Updating devices
info t=2017-03-30T13:54:16.257Z Adding systray: blueberry-tray.py (24x24px)
info t=2017-03-30T13:54:16.259Z Adding systray: cli (24x24px)
info t=2017-03-30T13:54:16.261Z Adding systray: mintupdate.py (24x24px)
info t=2017-03-30T13:54:16.261Z Hiding systray: network
info t=2017-03-30T13:54:17.761Z Resized blueberry-tray.py with normalized size (22x22px)
info t=2017-03-30T13:54:17.761Z Resized cli with normalized size (22x22px)
info t=2017-03-30T13:54:17.773Z Resized mintupdate.py with normalized size (22x22px)
info t=2017-03-30T13:54:31.310Z PlacesManager: Updating devices
info t=2017-03-30T13:54:36.549Z PlacesManager: Updating devices
info t=2017-03-30T13:56:35.102Z PlacesManager: Updating devices
info t=2017-03-30T13:59:32.310Z PlacesManager: Updating devices
info t=2017-03-30T14:50:27.567Z GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files
trace t=2017-03-30T14:50:27.567Z

**Comment by collinss** [comment]
Are you using the latest version of the sticky notes? There was an issue with the menu for a while, but it was fixed recently. Try updating it in applet settings and see if that fixes your issue.

**Comment by uocxp** [comment]
i am using v1.2. This is the version available in Cinnamon applet store. Is there any newer version ?

**Comment by NikoKrause** [comment]
What's the output of:
```
grep last-edited ~/.local/share/cinnamon/applets/sticky@scollins/metadata.json 
```

**Comment by uocxp** [comment]
"last-edited": 1491423606

**Comment by NikoKrause** [comment]
That's from April 5. There's a version from April 19, but that's only translation update.

**Comment by NikoKrause** [comment]
Not sure. It works for me on Cinnamon 3.2.7 on vertical panel. Maybe uninstall, restart and install again?

**Comment by uocxp** [comment]
i already tried :/

**Comment by NikoKrause** [comment]
Your glass log is weird. There's no mention of sticky notes at all.

**Comment by uocxp** [comment]
i updated the log. in ~/.cinnamon/glass.log is not mensioned only in the log in looking glass

**Comment by NikoKrause** [comment]
Okay. I just was about to write, that I can't reproduce it. But actually I can.

When I have a horizontal panel at the bottom and another vertical panel, it works. But when I have only 1 vertical panel only (and no horizontal panels), then I can reproduce it. That's weird.

@collinss 
I get the following error then:
```
(cinnamon:18093): Clutter-CRITICAL **: clutter_actor_set_child_below_sibling: assertion 'child->priv->parent == self' failed
```

Unrelated to this issue:
Another JS ERROR I noticed. Try to remove a checklist. You'll get a JS ERROR. Type error or something like that.

**Comment by NikoKrause** [comment]
Okay. I just was about to write, that I can't reproduce it. But actually I can.

When I have a horizontal panel at the bottom and another vertical panel, it works. But when I have only 1 vertical panel only (and no horizontal panels), then I can reproduce it. That's weird.

@collinss 
I get the following error then:
```
(cinnamon:18093): Clutter-CRITICAL **: clutter_actor_set_child_below_sibling: assertion 'child->priv->parent == self' failed
```

Unrelated to this issue:
Another JS ERROR I noticed. Try to remove a checklist. You'll get a JS ERROR. Type error or something like that.

**Comment by NikoKrause** [comment]
Also, when I have the first panel at left and then add the second one at the bottom,
I can create new notes, but they appear at the bottom left. See screenshot. When I try to grab them that's not possible, because they hide under the bottom panel:
![screenshot-screen-2017-05-09-150245](https://cloud.githubusercontent.com/assets/8415124/25852196/d8f0dc00-34c8-11e7-8112-f46474149120.png)

**Comment by uocxp** [comment]
I use only 1 panel on the right. The panel story took me btw away from ubuntu since in unity it's not possible to place the panel on the right side :p

**Comment by NikoKrause** [comment]
@uocxp I think we found the cause of the issue with vertical panels. Fix has been released
