### ISSUE TITLE
Cinnamenu@json Right arrow when no result or calculating does not work

### ISSUE THREAD

**Issue by mahajanudit** [linuxmint/cinnamon-spices-applets#3035]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") 4.1.5
 * Cinnamon version (cinnamon --version) Cinnamon 4.4.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 
 * Graphics hardware *and* driver used Intel
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
Ideally arrow keys are used to navigate around the search results when typing in something in the menu, but on occasion where I misspell something or using calculator I can use left key to go left where I am typing, but right key does not work. So let's say I entered 4_5, when I intended to write 4-5, now I press left arrow and correct it and I want to continue with my calculations so I press right arrow -> to come past 5, but that doesn't work.

**Steps to reproduce**
Right any math equation and press left arrow key, it will go left in the edit box, now press right arrow. That won't work.

**Expected behaviour**
Right should go to right character

**Other information**

**Comment by fredcw** [comment]
@mahajanudit Thanks for reporting. I'll fix as soon as a can.

**Comment by fredcw** [comment]
@mahajanudit I think it's a bug that you can move left in the search entry at all. Giving navigation to the search entry means that an extra keypress is required to give navigation back to the menu. I think this would be more inconvenient in most cases. Just using backspace is the better option for now I think.

**Comment by fredcw** [comment]
@mahajanudit @brownsr This issue can be closed. I don't know how to close it myself.

**Comment by fredcw** [comment]
I don't remember in which PR I fixed this issue but the arrow keys can now be used to navigate the text in the search entry.

**Comment by mahajanudit** [comment]
> I don't remember in which PR I fixed this issue but the arrow keys can now be used to navigate the text in the search entry.
> 
> I think it was PR #3097

Closing
