### ISSUE TITLE
[CinnVIIStarkMenu@NikoKrause] Dragging causes system freeze.

### ISSUE THREAD

**Issue by fredcw** [linuxmint/cinnamon-spices-applets#3037]
```
 * Version 1.19 (2020-04-23 21:11:23)
 * Cinnamon version: 4.4 & 4.6
 * Distribution - mint 19.3 
 ```

**Notify author of applet**
@NikoKrause 

**Issue**
Dragging an application in the application list immediately causes cinnamon to freeze.

**Comment by NikoKrause** [comment]
Thanks @fredcw for pointing this out.

It's fixed in the newest version (probably have to wait 1 or 2 days for the new version to update).
