### ISSUE TITLE
Weather (weather@mockturtl)

### ISSUE THREAD

**Issue by French77** [linuxmint/cinnamon-spices-applets#3059]
```
 * Applet version/Build date 2.6.0
 * Cinnamon version 4.4.8
 * Distribution - Mint 19.3
 


 ```

**Notify author of applet**
@mockturtl

**Issue**
Text under icoons weather forecast in hours are not translated see image

![Weather applet](https://user-images.githubusercontent.com/3099270/83965292-e94cf000-a8b2-11ea-8e88-4f0d10e763f9.png)
@French77

**Comment by Gr3q** [comment]
Yes, obvious mistake from my part, I will fix it later today.
