### ISSUE TITLE
vpnLookOut@claudiux: Support for Wireguard

### ISSUE THREAD

**Issue by casswarry0** [linuxmint/cinnamon-spices-applets#3070]
vpnLookOut@claudiux

 * Applet version/Build date: 3.5.0 (2020-06-07)
 * Cinnamon version: 4.6.2
 * Distribution: Arch

**Notify author of applet**
@claudiux

**Issue**
Support for Wireguard

**Steps to reproduce**

**Expected behaviour**

**Other information**
To support Wireguard the main Problem lies in the script vpn_iface_detect.sh where there is a check for the file /sys/class/net/$iface/tun_flags. The problem is:

a) Wireguard interfaces are no TUN interfaces therefore the file tun_flags does not exist
b) not all TUN interfaces are VPN interfaces (e.g. networks for QEMU virtual machines consists of 2 interfaces: virbr0 and virbr0-nic whereof virbr0-nic is a TUN interface)

I checked /sys/class/net/$iface/type where the interfaces eth0, usb0, virbr0, virbr2-nic, wlan0 have the content 1 (ARPHRD_ETHER); lo has the content 772 (ARPHRD_LOOPBACK); Wireguard interfaces have the content 65534 (ARPHRD_VOID). Since I don't use other VPN types I don't know what type they have. Maybe 768 (ARPHRD_TUNNEL)? Assuming it won't be 1 I added the Wireguard branch to the if and removed the unneccesary writes to /tmp/.vpn_iface in the file vpn_iface_detect.sh:
```
#!/bin/sh

ret=1
for iface in $(ls -1 /sys/class/net/); do
	# Check if interface is a VPN
	if [ -f "/sys/class/net/$iface/tun_flags" ] && grep -Fxqv "1" /sys/class/net/$iface/type ; then
		echo -n $iface
		ret=0
	elif grep -Fxq "65534" /sys/class/net/$iface/type ; then
		echo -n $iface
		ret=0
	fi
done

exit $ret
```

The second problem is that with Wireguard the interface name is always the name of the Wireguard connection. Therefore the interface name will always change when the connection is changed. Since in applet.js the VPN interface name is determined only once and then stored in the applet settings the shell script vpn_iface_detect.sh is executed only once. If the script is executed always in updateLoop() any change to the VPN will be properly detected.

**Comment by claudiux** [comment]
Hi @casswarry0,

I'm working on a new applet, which detects continuously the interfaces.

This project has been delayed because the past few months have been particularly difficult for me.

But... I'm back!

**Comment by casswarry0** [comment]
Hi @claudiux,

thanks for your update. I'm waiting for your new applet.

Best Regards

**Comment by claudiux** [comment]
Hi @casswarry0,

I'm working on this new applet. Now it correctly detects when Wireguard is up or down. Thanks for your help!

Now I must write the Wireguard management. Have you a method to use wg-quick without sudo? I could ask the user to modify `/etc/sudoers` but I would not prefer.

And NetworManager does not recognize wireguard connections before LM 20...

**Comment by casswarry0** [comment]
Hi @claudiux,
I'm sorry but I can't help you with that. I'm running Arch Linux and therefore I'm using NetworkManager to manage my Wireguard connections. I never used wg-quick.

P.S. I found a problem with my changes in updateLoop() ... it makes the applet a resource hog :-( I hope your new applet takes another approach.

**Comment by mockturtl** [comment]
> Have you a method to use wg-quick without sudo?

Seems **dangerous**, but possible:

https://unix.stackexchange.com/a/578487

https://github.com/atareao/wireguard-indicator/issues/15

**Comment by claudiux** [comment]
@casswarry0 @mockturtl Please try my new applet VPN-Sentinel: https://cinnamon-spices.linuxmint.com/applets/view/368
