### ISSUE TITLE
[SpicesUpdate@claudiux] Error when starting Cinnamon

### ISSUE THREAD

**Issue by JoeJoeTV** [linuxmint/cinnamon-spices-applets#3071]
* Applet version/Build date: 5.4.1
 * Cinnamon version: 4.4.8
 * Distribution: Mint 19.3 64bit
 * Graphics hardware *and* driver used: Nvidia GTX 1060 6G / Driver: nvidia-driver-440
 * Snippet or attachment of ~/.cinnamon/glass.log: 
```
error t=2020-06-14T23:13:45Z 
[SpicesUpdate@claudiux]: this.unprotectedDico[type][name] is undefined
[SpicesUpdate@claudiux]: Failed to evaluate 'main' function on applet: SpicesUpdate@claudiux/30
error t=2020-06-14T23:13:45Z 
[SpicesUpdate@claudiux]: Applet SpicesUpdate@claudiux: Could not create applet object.
[SpicesUpdate@claudiux]: Error importing applet.js from SpicesUpdate@claudiux
```
 * Snippet or attachment of ~/.xsession-errors:
```
[SpicesUpdate@claudiux]: this.unprotectedDico[type][name] is undefined
[SpicesUpdate@claudiux]: Failed to evaluate 'main' function on applet: SpicesUpdate@claudiux/30
Cjs-Message: 23:12:55.199: JS LOG: [LookingGlass/trace] 
<----------------
populateSettingsUnprotectedSpices@/home/joejoetv/.local/share/cinnamon/applets/SpicesUpdate@claudiux/4.2/applet.js:889:29
populateSettingsUnprotectedApplets@/home/joejoetv/.local/share/cinnamon/applets/SpicesUpdate@claudiux/4.2/applet.js:916:9
SpicesUpdate@/home/joejoetv/.local/share/cinnamon/applets/SpicesUpdate@claudiux/4.2/applet.js:473:9
main@/home/joejoetv/.local/share/cinnamon/applets/SpicesUpdate@claudiux/4.2/applet.js:1996:12
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:581:18
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:356:22
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:95:14
Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:277:17
---------------->
Cjs-Message: 23:12:55.199: JS LOG: [LookingGlass/error] 
[SpicesUpdate@claudiux]: Applet SpicesUpdate@claudiux: Could not create applet object.
[SpicesUpdate@claudiux]: Error importing applet.js from SpicesUpdate@claudiux
Cjs-Message: 23:12:55.199: JS LOG: [LookingGlass/trace] 
<----------------
Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:278:23
---------------->
```

**Notify author of applet**
@claudiux 

**Issue**
When (re)starting Cinnamon after updating to this version, everytime, it shows the "Problems with starting Cinnamon" message and in the log it shows me that the applet didn't load correctly.

**Steps to reproduce**
 * Update Applet to 5.4.1
 * Restart Cinnamon

**Expected behaviour**
 * No Errors during restart

**Other information**

**Comment by claudiux** [comment]
@JoeJoeTV Thank you for reporting this issue.

You can try that:
Edit your `/home/joejoetv/.local/share/cinnamon/applets/SpicesUpdate@claudiux/4.2/applet.js` file.
Before the line 889, insert this line:
```
                            this.unprotectedDico[type][name] = {};
```
Save the file and restart Cinnamon.

Please, tell me if that fixes this issue.

Regards.

**Comment by JoeJoeTV** [comment]
> @JoeJoeTV Thank you for reporting this issue.
> 
> You can try that:
> Edit your `/home/joejoetv/.local/share/cinnamon/applets/SpicesUpdate@claudiux/4.2/applet.js` file.
> Replace the line 888 by this one:
> 
> ```
>                             this.unprotectedDico[type][name] = {};
> ```
> 
> You should obtain these lines 886->892:
> 
> ```
>                         if (this.unprotectedDico[type][name] === undefined) {
>                             this.unprotectedList[type].push({"name": name, "isunprotected": true, "requestnewdownload": false});
>                             this.unprotectedDico[type][name] = {};
>                             this.unprotectedDico[type][name]["name"] = name;
>                             this.unprotectedDico[type][name]["isunprotected"] = true;
>                             this._get_last_edited_from_metadata(type, name);
>                         }
> ```
> 
> Save the file and restart Cinnamon.
> 
> Please, tell me if that fixes this issue.
> 
> Regards.

Yeah, that fixed it, thanks for responding so quickly.
