### ISSUE TITLE
Cinnamenu@json menu display is wrong

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon-spices-applets#3088]
```
 * Applet version/Build date: Version 4.2.2 (2020-06-21 10:08:28)
 * Cinnamon version: 4.4.8
 * Distribution: Mint 19.3
 ```

**Notify author of applet**
@fredcw 

**Issue**
Cinnamenu@json menu display became wrong since #3086. Categories do not appear.

**Steps to reproduce**
Start or restart Cinnamon.

**Expected behaviour**
Cinnamenu@json menu displaying as expected ; and as usual by default.

**Other information**

Error message in .xsession-errors:
```
(cinnamon:20825): Cjs-WARNING **: 20:37:41.786: JS ERROR: TypeError: this.powerGroupBox is undefined
destroyDisplayed@/home/claude/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:2003:9
refresh@/home/claude/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:609:9
onIconsChanged@/home/claude/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:416:9
anonymous/CinnamenuApplet/<@/home/claude/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:156:90
```

**Comment by fredcw** [comment]
@claudiux I can't reproduce this. Thanks for the error log but I think it shows a subsequent contingent error rather than the initial error. Does this only happen when the search box extends over the right side of the menu

**Comment by fredcw** [comment]
@claudiux That was the relevant error, my mistake.

**Comment by claudiux** [comment]
@fredcw Thank you for fixing this issue!
