### ISSUE TITLE
Cinnamenu@json show really weird

### ISSUE THREAD

**Issue by bomdia** [linuxmint/cinnamon-spices-applets#3089]
* Version 4.2.2 (2020-06-21 10:08:28)
 * Cinnamon 4.4.8
 * Mint 19.3
 * nvidia geforce 1050 ti mobile with nvidia 440.82

**Issue**
the applet show really weird (screenshoot attached)

**Author**
@fredcw

**Steps to reproduce**
install
add to a panel
open

**Expected behaviour**
show correctly

**Other information**
![cinnamenu_weird_layout](https://user-images.githubusercontent.com/1759618/85233639-22837500-b408-11ea-9993-1a630c1ff1fa.png)

**Comment by bomdia** [comment]
changing the session button location in the settings temporarily fix the problem

**Comment by claudiux** [comment]
Same as #3088.

**Comment by bomdia** [comment]
I wasn't sure as you don't have attached any screenshot

**Comment by claudiux** [comment]
This issue stems from #3086.

**Comment by bomdia** [comment]
i noticed that if you change the location to any other and return to bottom (that is the default) the applet return to work till next cinnamon restart, that is very strange behavior

**Comment by fredcw** [comment]
@claudiux @bomdia I can't reproduce this. Thanks for the error log but I think it shows a subsequent contingent error rather than the initial error. Doe's this only happen when the search box extends off the right side of the menu?

**Comment by bomdia** [comment]
@fredcw so for me this happen when cinnamon is started or restarted, i tested all 4 disposition and the right and left one is like this
![cinnamenu_weird_layout2](https://user-images.githubusercontent.com/1759618/85235769-e48e4d00-b417-11ea-89f3-be977cc0fc8d.png)
and the top and bottom one is like my previus screenshot
if i change the position the apple return to work correctly

**Comment by fredcw** [comment]
@bombia Any chance you can post your error log? restart cinnamon, open cinnamenu and close, paste here <home-dir>/.xsession-errors

**Comment by bomdia** [comment]
[xsession-errors.log](https://github.com/linuxmint/cinnamon-spices-applets/files/4810332/xsession-errors.log)

**Comment by bomdia** [comment]
@fredcw hope that can help

**Comment by fredcw** [comment]
@bomdia Yes, I think I found it, thanks. Will update asap.

**Comment by bomdia** [comment]
ahhh yes i found it too lol in the constructor there is no this.powerGroupBox creation ahaha, i've already fixed my version :) i've added 
        this.powerGroupBox = new PowerGroupBox(this.state); at line 140 before any signal connect and all work flawlessly

**Comment by bomdia** [comment]
@fredcw i've an ot question for cinnamenu can you add a size chose for the powerGroup icons i want them more wider but i'm pretty sure that any user want them in different size

**Comment by bomdia** [comment]
ok all work fine with your fix, i close the issue

**Comment by fredcw** [comment]
@bomdia Thanks for your help.
