### ISSUE TITLE
Cinnamenu@json don't show cinnamon-screensaver-lock-dialog anymore

### ISSUE THREAD

**Issue by ClovisGauzy** [linuxmint/cinnamon-spices-applets#3093]
```
 * Version 4.2.3 (2020-06-22 09:37:20)
 * Cinnamon 4.6.3
 * Manjaro 20.0.3
 ```

**Notify author of applet**
@fredcw 

**Issue**
`cinnamon-screensaver-lock-dialog` is not shown before locking screen via Cinnamenu

Capabilities have been removed at <https://github.com/linuxmint/cinnamon-spices-applets/commit/c55fe4ceb2d414880a09495c7f99859330413711#diff-4e2751f1f97747997e6de845446f3a0fL1942>. 

Please restore this function.

**Comment by fredcw** [comment]
@ClovisGauzy Will be back in next update. Thanks.

**Comment by ClovisGauzy** [comment]
It's back, thanks, ^^

**Comment by fredcw** [comment]
@ClovisGauzy np, could you close this issue now (button at the bottom), since I can't do it myself. Thanks.
