### ISSUE TITLE
timeshift-spy@nicog60 - Translation problem

### ISSUE THREAD

**Issue by alan7000** [linuxmint/cinnamon-spices-applets#3095]
```
 * Cinnamon version 4.4.8
 * Distribution - Mint 19.3
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors
 ```

**Notify author of applet**
@NicoG60 

**Issue**
I have a French Linux Mint 19.3. When I install your applet, all the other cinnamon applets are in English.

**Steps to reproduce**
Put the system in english and install the applet. Do a reboot so that all applets restart.

**Expected behaviour**
Normally the applet should not crash the translations of cinnamon applets.

**Comment by NicoG60** [comment]
Thanks for the ticket, I'll have a look when I got time.
