### ISSUE TITLE
betterlock: Applet need adding configurations setting like up to date GNOME corresponding extention !

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-applets#31]
Hi. This applet is drived from an extension for GNOME DE. It seem that it drived at a time when original GNOME extension have no configuration setting. 

Applet need to be updated to have configuration setting like that existing in original GNOME extension. For example it should have options for:

1) disable / enable notification
2) hide icon if inactive (if CapLock is inactive then it's icon in panel should disappear & if Numluck key is inactive then it's icon in panel should disappear)
3) option to select whether CapLuck + Numluck or only CapLuck or only Numluck state monitoring.

Please review configuration of GNOME extension.

This applet very important because Lenovo ThinkPad (& other laptops) have no LED for these 2 keys.

**Comment by collinss** [comment]
@Nokia808 Please specify which applet you are referring to. There are currently over 200 in this repository.

**Comment by Nokia808** [comment]
Applet name is:

Num Lock/Caps Lock indicator with MessageTray notifications by betterlock

**Comment by Nokia808** [comment]
Is there plane to address this issue in future ?

**Comment by NikoKrause** [comment]
The author of this applet is called @entelechy.
He doesn't seem to be active lately.

**Comment by NikoKrause** [comment]
Could you add some screenshots of the GNOME version? (Left-Click, Right-Click, Settings)

**Comment by Nokia808** [comment]
Hi. Thank you very very very much for covering my 1st suggestion (Show Notification). I test new feature & it work very well. Now applet is usable when user switch on "sound effect for Notification in Cinnamon DE".

But please do not forget point 2 that I suggest in this issue. Also, please do not forget to cover issue 32 about this applet.

Best.

**Comment by NikoKrause** [comment]
Plesse do not forget my previous comment.

**Comment by Nokia808** [comment]
Hi again.

@NikoKrause 

Dear Niko I have Fedora 24 Cinnamon version on my laptop & I did not use Fedora GNOME, so I can not give you screenshots. I googled about this but I did not found suitable image. Finally I got image at official site of GNOME extension (Key Lock extension). Please look on image in the bellow link:

https://github.com/kazysmaster/gnome-shell-extension-lockkeys

**Comment by Nokia808** [comment]
@NikoKrause 
Hi. 
![2](https://cloud.githubusercontent.com/assets/25375330/24837045/7d4678f8-1d1a-11e7-904f-f08b04b34395.png)
![1](https://cloud.githubusercontent.com/assets/25375330/24837044/7d457278-1d1a-11e7-8f54-9c0905de69bd.png)
I received last update for this applet. I noticed that there is "configure" added to this applet (look screenshot 1). But when I click on "configure" I got no real configuration !! (look screenshot 2). Only "betterlock setting" but no thing appear when I click over it !
Please your kind follow up.
Best.

**Comment by NikoKrause** [comment]
Should be fixed now by Odyseus

**Comment by NikoKrause** [comment]
Added option to select whether CapsLock + NumLpck or only CapsLock or only NumLock state should be shown.
