### ISSUE TITLE
weather@mockturtl Some Configuration Settings suggestions

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#3100]
UUID: weather@mockturtl
```
 * Applet version/Build date - 2.6.2
 * Cinnamon version - 4.4.8
 * Distribution - Mint 19.3
 * Graphics hardware Intel Corporation Haswell-ULT Integrated Graphics Controller - i915
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@Gr3q
First, thanks for a truly great release of the Weather applet :)

**Issue**
1) It looks like in 2.6.2 the provider info went away from the Config settings and moved to README and the Cinnamon-spices applet page. It would look nice and perhaps sometimes be useful in Configuration settings to have a short generic intro text in the "Weather provider information" box above the "Click here..." button that links to the Cinnamon-spices applet page? If the user have connection trouble not being able to reach the information or weather service, and have never used the applet, it can perhaps be confusing?
Anyway, here is a suggestion to a simple Weather Provider Information intro text for the info box in config:   

You can use several different weather forecast providers that you choose in the Options area bellow. Some require a API key to work and they all need a functional internet connection to the chosen service. 

2) The 3.8+ the Configuration settings window is much wider than other applets setting windows in Cinnamon. With this wide layout is a bit harder to see what's what, and seems to be caused by the long "powered by" text at the bottom of the Configuration settings (if I put a line brake in the powered by text and split it, the window shrinks, at least for me). The new Climacell service is also missing here.

**Steps to reproduce**
Right click on the weather applet and choose Configuration...

**Expected behaviour**
That there is a short generic intro about the applet and that the Configuration settings window is more close to the Cinnamon default width.

**Comment by Gr3q** [comment]
Thanks for the feedback

I removed the info because with Climacell there are too many providers now (and I'm implementing Met Office UK and US National Weather service) and it takes away too much space when you open the config the first time, but I agree what I have there now is lacking.

I probably rework the settings completely, maybe change it to tabbed layout, then we can have a tab just for the information. Alternatively, I can just make the current section more clear as you said.

I will also fix the credits text, I did not notice that it does not automatically line break (it does with normal labels).

**Comment by jorgenqv** [comment]
@Gr3q
Yes, all sounds good. As long as it's as simple and clear as possible?
I fully understand that all the alternatives was cluttering up the Config and the new UK/US implementing seems very interesting. Tabbed layout is good if you understand what what happens if you click to go further, perhaps start with a open tab with a intro there?
Nice that the auto line brake issue will be fixed, thanks.

Some README observations: The python3-requests-oauthlib Required Packages sholud be on Yahoo, under OpenWeatherMap perhaps replace "anymore!" with "and is the default provider"?

**Comment by Gr3q** [comment]
Maybe I'll name the tab with the Info "Help" so it's obvious to click there if someone is stuck. I'll try to get tooltips wherever I can.

I didn't notice the package requirement jumped line, thanks

**Comment by Gr3q** [comment]
Although some of the text will be changed, it will look like this:
![image](https://user-images.githubusercontent.com/22377521/87225852-d8970a80-c387-11ea-8dd0-8b30bb19c873.png)

**Comment by jorgenqv** [comment]
Looks good :)

**Comment by Gr3q** [comment]
@jorgenqv let me know if the new version is ok or it still has some issues (be picky, it's ok)

**Comment by jorgenqv** [comment]
@Gr3q The latest version 2.6.4 is very nice but a bit confusing and messy in my opinion! :-) The main problem is that the Help and Contact tabs purpose isn't very clear and I think is better to work further on the README / Spices Website. Is it possible you start a wiki documentation area for Weather here on Github linking from README?

Some ideas:

- At the top of the first Weather Tab, clarify that there is more settings by adding text: Click on the Tab buttons above for more settings and information.

- The length of the content on the Help Tab it too long, confusing and is better to have elsewhere. If you scroll down to the bottom on the Help tab and click on the Contact tab it appears blanc, if you dont' realise that you need to scroll up again. Move all this information under Help to the README/SpicesWeb and replace with:

Weather provider choices and location

You can use several different weather forecast providers that you choose under the first Weather Tab in this Configuration panel. Some providers require a API key to work, some have regional limits, differ in forecast length, and they all need a functional internet connection to the chosen service. 

Your location in most cases work automatic but you can also want to enter this manually by coordinates "Latitude,Lognitude" (e.g. 51.5085,-0.1257) or use "City,Country-code" (e.g. London,UK) or try to enter {House number} {Street} {City/Town} {Postcode} {Country}. You can use commas if you like. After 3 seconds without typing the address you enter will be replaced automatically for validating you choice. 

For more information go to the Spices Website by clicking the button bellow. You can also comment and ask a questions to the community at this page by logging in with your Github account.

Button >> [ Weather Applet at Cinnamon Spices Website ]

- Change the Tab label "Contact" to "Report Issue" and add text above the Submit an Issue button: If you find an issue with this applet please make a report by clicking on the button bellow and login in with your Github account. Don't forget to write weather@mockturtl in the top Title field to make it easier for everyone to know that the issue is about the weather applet (the form is for all Cinnamon applets).

**Comment by Gr3q** [comment]
@jorgenqv Thank you for the ideas, I'll do it like you described it. I didn't really had a clear vision with the content on the Help and Contact pages.

**Comment by jorgenqv** [comment]
@Gr3q Alright, thanks for liking my ideas. Your vision and great effort with putting Tabs in Configure works very well, my simple suggestion is just fine-tuning :-)

**Comment by jorgenqv** [comment]
@Gr3q  Another Conf thingie: The Tab Presentation can be a bit shorter and made more distinct by moving the top Keybindings to the bottom of the next one and rename that label to "Units, Icons and Key Shotcuts".

**Comment by jorgenqv** [comment]
@Gr3q Ahhh, and finally forgot (sorry): Missing the the long "powered by" text. Should perhaps go under the last Tab relabel to "Report issue and Creds"

**Comment by Gr3q** [comment]
@jorgenqv Yes, I didn't know where should I put the keybindigs, I agree that I can put it under the icons.

I removed the powered by text intentionally because credit is shown on the bottom bar as a button for the one being used, so that is not needed anymore

**Comment by jorgenqv** [comment]
Ah ok, thanks for pointing out the move of powered by. Looking forward for the new version :)

**Comment by jorgenqv** [comment]
@Gr3q Just found a minor typO in my suggested text for the Help Tab, last in the section about location, should be:
"...will be replaced automatically for validating **your** choice."

**Comment by Gr3q** [comment]
I was thinking if we use something like this is ok/better:

Only display the info on the selected provider
![image](https://user-images.githubusercontent.com/22377521/89014035-d849b980-d30c-11ea-80ed-2f63e104a08f.png)
![image](https://user-images.githubusercontent.com/22377521/89014093-ea2b5c80-d30c-11ea-97cb-3b918c9f7f25.png)

**Comment by jorgenqv** [comment]
@Gr3q Looks great, seems like a good idea and sure makes things better. But I think it's still good to keep the other suggested tabs regarding help and report.

**Comment by jorgenqv** [comment]
@Gr3q Just tried out the new 2.6.5 release and it's very good, congratulations for some really great well done work! Guessing that the Data service display info didn't work out as expected (but this is not crucial in my opinion) so I think we can safely close this issue.

**Comment by Gr3q** [comment]
Thanks, I didn't have time to add that part in the end, it will be in the next release
