### ISSUE TITLE
Pomodoro timer by pomodoro@gregfreeman.org unable to load in Cinnamon 4.6.6

### ISSUE THREAD

**Issue by ozcavic** [linuxmint/cinnamon-spices-applets#3105]
```
I very much like your Pomodoro applet and have used it for quite some time now. Yesterday I installed the new Linux Mint 20
(Ulyana) with Cinnamon 4.6.6. Of course, I installed your applet (Updated on 2019-10-25 16:22:15) too. My first clue that a
problem existed was that the usual icon and timer indication did not appear in the panel. Today when I booted up, in addition to
no icon/timer appearing in the panel, I received an error notification from the system saying that Cinnamon could not load the
applet and to contact the developer. Hence, this note. I hope you find this helpful as I may not be the only one who will experience
this problem.

I am also attaching the following file in the hope it is helpful in arriving at a solution...
[termbin.com-.pdf](https://github.com/linuxmint/cinnamon-spices-applets/files/4849261/termbin.com-.pdf)

**Comment by myh98** [comment]
Running "sudo apt install python-is-python3" fixes it. Apparently there's a call to "python" which doesn't point to any version of python. 
Found the solution under this.
https://cinnamon-spices.linuxmint.com/applets/view/131

**Comment by ozcavic** [comment]
Works like a charm.

Thank you
Dean Whitney

**Comment by Naushikha** [comment]
> Running "sudo apt install python-is-python3" fixes it. Apparently there's a call to "python" which doesn't point to any version of python.

This worked for me as well, much thanks! :smile:

**Comment by claudiux** [comment]
`sudo apt install python-is-python3` does uninstall virtualbox-6.1.

**Comment by arohde69** [comment]
> Running "sudo apt install python-is-python3" fixes it. Apparently there's a call to "python" which doesn't point to any version of python.
> Found the solution under this.
> https://cinnamon-spices.linuxmint.com/applets/view/131

thanks a lot. Works fine for me.

**Comment by NikoKrause** [comment]
The latest applet version shouldn't need python-is-python3 anymore.

**Comment by arohde69** [comment]
> The latest applet version shouldn't need python-is-python3 anymore.

ok. thanks for this information....i got the latest version of the applet and removed python-is-python3
now it works....
