### ISSUE TITLE
clipboard-qr@wrouesnel: LM 20 needs python3-zbar

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-spices-applets#3119]
@wrouesnel

Hi, this used to work with python-zbar, but that's no more available in the LM20/focal fossa repos.
It has to be changed to python3-zbar in code and in hints (readme/cinnamon-spices website).
May be with backwards compatibility for older versions of LM or LMDE.

**Comment by NikoKrause** [comment]
Fixed in https://github.com/linuxmint/cinnamon-spices-applets/pull/3429
