### ISSUE TITLE
Cinnamenu@json: an option to always open Favorite Apps?

### ISSUE THREAD

**Issue by AlexP11223** [linuxmint/cinnamon-spices-applets#3125]
```
 * Applet version/Build date: 4.2.8 (2020-07-16 14:42:30)
 * Distribution - Mint 20
 ```

Looks like currently it remembers the latest opened category, and after re-opening Cinamenu (pressing `Win` twice) still shows it.
Is there any way to always open e.g. Favorite Apps category?
If not, would be great to add such option :)

**Notify author of applet**
@fredcw

**Comment by fredcw** [comment]
@AlexP11223 It's hard to know how many people would find this option useful and every extra option has the disadvantage of possibly making the options too complicated. If more people request it, I will add it in the future.

**Comment by AlexP11223** [comment]
By "too complicated" you mean UI/UX?
Then maybe for now it can be added just to the config file without UI? :)

I think that's how most of the others Start Menus work (Windows, KDE, ...), resetting on re-opening. So people used to that may want this behavior.

**Comment by fredcw** [comment]
@AlexP11223 Yes, I mean in terms of the UI. Applets don't usually have config files but that is an idea I have thought about before. Also, I'm curious about the use-case for having the favorites category open each time when you already have your favorites app icons alongside the session buttons? Why might these icons be insufficient do you think?

**Comment by AlexP11223** [comment]
I disabled them in the session buttons to keep it cleaner. And it's easier to open via big icons anyway.

After opening something in a category usually I am more likely to not care about this category anymore and want the favorite apps back.

Also some users may get confused because they may not notice/remember that there is the "favorites" category with the apps they used most of the time.

**Comment by fredcw** [comment]
@AlexP11223 Thanks for the feedback. I think you're right, some people may prefer this option. I'll add it in the next update.

**Comment by fredcw** [comment]
@AlexP11223 If you wish, you can close this issue now. Thanks.
