### ISSUE TITLE
batterymonitor@pdcurtis - Error "Extension is not compatible with current Cinnamon version" - cinnamon 4.6.6+debbie

### ISSUE THREAD

**Issue by EmersonPrado** [linuxmint/cinnamon-spices-applets#3126]
* Applet version/Build date - 1.4.0.1
 * Cinnamon version 4.6.6+debbie
 * Linux Mint Debian Edition 4 (Debbie)
 * Intel i915 video chipset
* Error message from `~/.xsession-errors`:
    ```
    Cjs-Message: 16:18:39.670: JS LOG: [LookingGlass/error] [batterymonitor@pdcurtis]: Extension is not compatible with current Cinnamon version
    ```

@pdcurtis

After I log in, I get a notification about an applet error. Searching `~/.xsession-errors`, I found the error above.

`.metadata.json` lists 4.6 as a supported Cinnamon version, so I guess it's an issue with validating the version string. I don't know if this is done in the applet or Cinnamon itself.

**Comment by EmersonPrado** [comment]
My full `~/.xsession-errors`:
[xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/4942852/xsession-errors.txt)

**Comment by pdcurtis** [comment]
@EmersonPrado I only  check that any utilities it needs are are loaded. The  version verification is done in Cinnamon. If you choose to load anyway it should work if it is just the version check. It does on all my machines with C 4.6 under Mint and other users have used Debian in the past and the only recent change has been to include version 4.6!

**Comment by EmersonPrado** [comment]
@pdcurtis In fact, there's no option to load it. It just gives the warning message and aborts.
I downloaded again and reinstalled the applet. Now it works. I checked `metadata.json`, and the version is the same: 1.4.0.1.
I presume this recent change fixed the issue, and the version string didn't change.
Thanks!
