### ISSUE TITLE
Weather version 2.6.4 doesn't work

### ISSUE THREAD

**Issue by Pjotr123** [linuxmint/cinnamon-spices-applets#3147]
The latest Weather displays an error, whereas previous versions worked flawlessly.

Looking Glass says this:

error t=2020-07-27T16:36:33Z [weather@mockturtl#52]: Generic Error while refreshing Weather info: TypeError: loc is undefined
error t=2020-07-27T16:36:33Z [weather@mockturtl#52]: Retrying in the next 15 seconds...
error t=2020-07-27T16:36:48Z [weather@mockturtl#52]: Generic Error while refreshing Weather info: TypeError: loc is undefined
error t=2020-07-27T16:36:48Z [weather@mockturtl#52]: Retrying in the next 15 seconds...
etc., etc., etc.

Entering a location manually doesn't help.

OS: Linux Mint 19.3 Cinnamon.

**Comment by Gr3q** [comment]
Hi, first, can you enable Debug logs by placing a text file named "DEBUG" into ```~/.local/share/cinnamon/applets/weather@mockturtl``` so we can see what is the issue?

Second, can you tell me what provider do you use? maybe what locations did you use?

**Comment by Pjotr123** [comment]
After a reboot and after removing, re-downloading and re-adding Weather, the problem has disappeared. It works well now. Strange, but good = good. I'll close the bug report.
