### ISSUE TITLE
Weather 2.6.4: typo at line 978 in the .po file

### ISSUE THREAD

**Issue by Pjotr123** [linuxmint/cinnamon-spices-applets#3148]
At line 978 in the Dutch .po file (nl.po), the string to be translated says:
"Few clouds and windz"

That should probably be:
"Few clouds and windy"

#: 3.0/us_weather.js:454 3.8/us_weather.js:357

**Comment by Gr3q** [comment]
Hi, this is fixed in 2.6.4 in the pot file, please update the nl.po file with Poedit or manually.

I do not touch translation files myself with languages I don't speak because I can easily make a mistake and I'll never know.

**Comment by Pjotr123** [comment]
I've updated it.
