### ISSUE TITLE
Cinnamenu@json: "Always open menu on favorite apps" not translated

### ISSUE THREAD

**Issue by erwn16** [linuxmint/cinnamon-spices-applets#3164]
Cinnamenu@json: "Always open menu on favorite apps" not translated into German

```
 * Version 4.2.10
 * Cinnamon version of Linux Mint 20 
 ```

**Notify author of applet**
@ fredcw

**Issue**

"Always open menu on favorite apps" and tool tip not translated into German.
de.po compared with pot.file: correct
Cinnamenu reinstalled with actual version: no success
Cinnamenu refreshed: no success

**Steps to reproduce**
None.

**Expected behaviour**
German translation appears.

**Other information**
Thank you for correcting the bug. The context menu works fine now.

**Comment by claudiux** [comment]
@erwn16 It seems you can close this issue. The de.po file contains:
```
#. 4.0
msgid "Always open menu on favorite apps"
msgstr "Beim Öffnen des Menüs immer die Favoriten anzeigen"

#. 4.0
msgid "Always open the menu with favorite apps category selected"
msgstr "Beim Öffnen des Menüs immer die Kategorie »Favoriten« markieren"
```

If these messages don't appear translated, then renew the download of Cinnamenu@json using the Spices Update applet.

**Comment by fredcw** [comment]
@erwn16 Ah, yes, the context menu. I forgot to ask you about that. I know that if the menu height is more than that of the monitor then the context menu doesn't appear but there are other problems with the context menu as well. I really need to implement it in a different way but I haven't figured out how to do it yet. I didn't actually change anything so maybe it was the height issue? I couldn't reproduce the issue with category icon size.

There wasn't a translation for that string in version 4.2.10 but there is in version 4.2.11. I updated the .po file in version 4.2.10 without the translation in case someone wanted add it.

**Comment by erwn16** [comment]
@claudiux Thanks for the advice. Your applet solved the problem. I was surprised because I de-installed and re-installed Cinnamenu and refreshed it by the interface of Cinnamon several times - and no improvement. After the installation of the Spices Update applet it indicated that all of my six applets weren't up to date.

@fredcw Sorry for the "false alert", I really tried to avoid it. 
The context menu disappears when the size of the categories icons is so big that Cinnamenu extends the hight of my notebook screen - from 38 pixel onwards. So I think it is only a minor flaw.

To give something back:
Cinnamenu sets the focus on the last chosen category or on the favorites when it is opened. This is a core function of a menu. As one don't know exactly how users work it will be better for some users to set the places or the recently used files as settings instead of the favorites.
Unfortunately I can only write programs in R and SAS. If I was capable in developing programs with Java Script I would assist. In addition to this some weeks ago I tried to get first insights in the structures and modules of Linux Mint but the progress I made was really limited.

**Comment by claudiux** [comment]
@erwn16 Spices Update ensures that you are downloading the latest version of Spices, unlike Cinnamon's interface. Glad it was helpful to you.

**Comment by claudiux** [comment]
@erwn16 Maybe you can close this issue now?

**Comment by erwn16** [comment]
"Always open menu on favorite apps" is translated in German.
