### ISSUE TITLE
weather@mockturtl Report issue button not reachable under Help Tab in LM20

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#3169]
```
 * Applet version/Build date 2.6.5 Aug 6, 2020
 * Cinnamon version 4.6.6
 * Distribution - Linux Mint 20 Cinnamon
 * Graphics hardware *and* driver used - VirtualBox and two physical Intel laptops (i915)  
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@Gr3q

**Issue**
When you open Weather Configuration you cannot reach the The Report Issue button at the bottom off the Help Tab, 
there is no scroll bar at the right side of the window in LM20, seems to be there in LM19.3.
The workaround is to grab the corner/bottom of the window and drag down to see the content at the bottom of the Help Tab where the button is located. 

**Steps to reproduce**
Right click on the Weather Applet in panel and choose Configure, click on Help and try to click the bottom button for Reporting Issue. Tested on three installs of LM20, one VirtualBox and two Laptops.

**Expected behaviour**
Be able to click the button marked Submit an Issue at the bottom fo the Help Tab.

**Other information**
One way to go is to try to limit height of the content by trying to have the top three boxes in one like as suggested in the screenshot, perhaps better regarding layout collecting everything regarding help in one box? Another idea is to simply move the Report Issue to its own tab as before. 

![Screenshot_Weather-2 6 5_LM20-Cinnamon](https://user-images.githubusercontent.com/5297223/89628146-2d04ab80-d89c-11ea-97f3-99a04ee1848a.png)

![Screenshot_Weather-2 6 5_LM20-Cinnamon_compact](https://user-images.githubusercontent.com/5297223/89628177-3857d700-d89c-11ea-9643-8268ac53ab14.png)

**Comment by Gr3q** [comment]
The way I see it this is a regression in cinnamon 4.6, so I'm going to raise this in the main repo when I get to my computer.

I'd rather not work around bugs if I have to.

Of course there is always the possibility that I messed something up, hopefully they can point it out if that's the case.

**Comment by jorgenqv** [comment]
Ok I see and fully agree that this seems to be a main cinnamon scrolling issue in 4.6 / LM20. Otherwise this bug aside I think it's a good thing to avoid scrolling if possible when using tabs ux wise in config if possible, but is of course not a major problem.

**Comment by French77** [comment]
> When you open Weather Configuration you cannot reach the The Report Issue button at the bottom off the Help Tab,
there is no scroll bar at the right side of the window in LM20
Enlarge the Help Tab
![Naamloos](https://user-images.githubusercontent.com/3099270/89706414-b92ed580-d965-11ea-91a4-6ca2c56e231a.png)

**Comment by jorgenqv** [comment]
@French77 Thanks for pointing out the middle button, yes it solves the access problem but not the experience of easy usage in configuration or the fact that the right side scrolling bar is missing.

**Comment by jorgenqv** [comment]
@Gr3q  Looks like the scroll bar is back in later versions of Cinnamon, at least in 4.8.6 when using lower screen resolutions? Tested on Mint 20.1, 19.3 and Manjaro 20.2 with screen height of 768px.
![Screenshot from 2021-02-03 12-18-06](https://user-images.githubusercontent.com/5297223/106804008-22697a00-6665-11eb-875f-77d2316373b4.png)

**Comment by Gr3q** [comment]
I still haven't got one, I don't really know why tho

**Comment by jorgenqv** [comment]
Have not seen this for a long time on several cinnamon installs so I think we can safely close this.
