### ISSUE TITLE
weather@mockturtl 2.6.5 hourly forecast info still superimposed

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#3176]
"uuid": "weather@mockturtl"
 * Applet version/Build date  Version 2.6.5 (2020-08-08 13:30:28)
 * Cinnamon version Cinnamon 4.4.8
 * Distribution - Mint 19.3 

**Issue**
At least on my desktop with 1600x900 display and the font's set to my specs I still get the 12 hour temps and status overlaying each other.

![before](https://user-images.githubusercontent.com/26556059/89721048-bdc7ae00-d9a6-11ea-9943-8ac5b9df3874.png)

I've added one line to the styles.css file to fix it.  
.hourly-box {
	padding: 10px 10px 0px 10px;
	min-height: 150px; }
Now with that change the figures are proper.
![after](https://user-images.githubusercontent.com/26556059/89721072-1008cf00-d9a7-11ea-9890-e13a0a8ce4ad.png)

**Other information**
In System-Settings->font-selection the font sizes are 14,14,14,12,17 respectively down the page.
My desktop theme is CBlue tweaked for larger fonts at least if not other items like transparency etc.
My eyesight is not as good as it should be so I've made these adjustments.

**Comment by Gr3q** [comment]
Yeah, I couldn't reproduce it at all, so I couldn't fix it.

I will try one more time and if I still can't find the issue, I'll just put a workaround in
