### ISSUE TITLE
Update on CPU Temp Indicator Issue on Linux Kernel v5.3 - a fix MIGHT BE possible!

### ISSUE THREAD

**Issue by rdlf4** [linuxmint/cinnamon-spices-applets#3191]
I'm going to mention @claudiux mainly because this thread post is a message for him.
Linux Mint 19 now supports Linux Kernel v5.3 by default, which means users who have updated their kernel version now most likely have broken CPU Temperature Indicator applet, which now displays the temp @ 0 ºC or 32 ºF.

Initially, I thought this was an issue with sensors because I let the developer know about this and he told me to go through sensors-detect questions, but in the end it'd output:
"Sorry, no sensors were detected.
This is relatively common on laptops, where thermal management is
handled by ACPI rather than the OS."

But that might not be sensors' fault. I have proof sensors is working as it should, even on Linux Kernel v5.3. Here's how:
I've made a new Python Virtual Environment, used PIP3 to install PySensors on it, from https://pypi.org/project/PySensors/
Think of PySensors as a Python package (or applet) that prints out the temperature values provided by sensors.
After that, I created a new python file, which imports sensors and then prints the temps it detects out. And guess what, it works.
Please check attached picture.
![sensors_working](https://user-images.githubusercontent.com/17544190/90313633-1550a700-dedc-11ea-9d5a-3cd93c007003.png)

The next step would be to 'forward' those values, so that CPU Temp Indicator could show it.
I've attached the Python file I made, in case that helps. It's in txt file format, just download and change it to .py
[temp.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/5078730/temp.txt)

**Comment by claudiux** [comment]
@rdlf4 Thank you for your help! I will try your python script soon.

**Comment by claudiux** [comment]
@rdlf4 I modified your script to also obtain `temp_max` and `temp_crit`, and I included this `sensors` library in this applet (to avoid using pip3). I will try it on several machines. Many many thanks to you!

**Comment by claudiux** [comment]
@rdlf4 I just created the [Sensors@claudiux](https://cinnamon-spices.linuxmint.com/applets/view/337) applet. It does not use this `sensors` library (which freezes Cinnamon).

Can you test it out and give me your feedback, please?

Regards.
Claudiux

**Comment by rdlf4** [comment]
@claudiux Thanks for the tip. Unfortunately I've been unable to get a temp display.
Digging a bit further through Looking glass, it outputs that 
`Failed to evaluate 'main' function on applet `
Please download the file _sensorsmonitor.txt_ which is attached to this post.
Looking forward to making this work!

Regards.

**Comment by claudiux** [comment]
@rdlf4 
Thank you for your feedback.

I see where is the problem. The `Util.spawnCommandLineAsyncIO` function appears in Cinnamon 4.2 (Linux Mint 19.2) and you have Cinnamon 3.8 (Linux Mint 19). I will resolve this issue very soon.

**Comment by claudiux** [comment]
@rdlf4 Can you test out the [version 1.2.1 of Sensors@claudiux](https://cinnamon-spices.linuxmint.com/files/applets/Sensors@claudiux.zip?f31e6b59-33ff-4ee4-9f7b-2708fa86bc76) and give me your feedback, please?

Extract the downloaded zip file into `~/.local/share/cinnamon/applet`. Then delete this zip file and reload Cinnamon (<ctrl-alt-esc>, or <alt-F2> then <r> <enter>).

**Comment by rdlf4** [comment]
Yay! Progress!
![sensors_working](https://user-images.githubusercontent.com/17544190/94345940-4e118f00-fff7-11ea-8c33-7dc787f88efe.png)
Got a few questions about the new Sensors applet:
CPU Temp Indicator had this option that you could input any text and it'd print out <text_from_user> and then the temperature.
Sensors has a 'Shown Name' column but it doesn't output that to understand which device is at the displayed temp. What is the data in 'Shown Name' for?

I like the colored background and the fact it goes yellow when the cputemp enters the 70ºC or hotter.
However, yellow with white text is good.. but I guess orange would do a better job, as it does still have my attention and it's a bit darker than yellow. Any way I can change the text/background color?

Gnome DISKS reports both the temps of my SATA SSD's. For this to work in Sensors, I need to provide the Sensor Name.
Same goes for my laptop fan.
How can I get that info?

Overall, Sensors does a great job. Thank you for reaching me.
Keep up the great work!

**Comment by claudiux** [comment]
The data in 'Shown name' replaces the 'Sensor name' in the tooltip of this applet.

The colors are defined in your `~/.local/share/cinnamon/applets/Sensors@claudiux/stylesheet.css` file. But any update of Sensors@claudiux will replace this file; so, all changes will be lost.
Extract from this file:
```
.sensors-high {
    background: DarkOrange;
...
}

.sensors-critical {
    background: FireBrick;
...
}
```

Disk temperatures are not monitored by `sensors`. Try the command `sudo hddtemp /dev/sdX` where X is the letter of your drive (a or b or ...).
I'm searching for a way to obtain these temperatures without 'sudo'. Help needed!

Thank you for your support.
