### ISSUE TITLE
betterlock: Please add option to exclude from "sound effect for showing notification"

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-applets#32]
Hi. Can you add this option please ? I'm already activate sound effect for showing notification from system setting & like this feature. But it is annoying to hear such sound effect each time activating CapsLuck/NumLuck keys during writing ...... . 

It will be very helpful if  you add option (in applet configuration setting) to exclude applet notification (if activated by user) from sound effect for showing notification that already activated from system setting so that last one continue to working on notifications other than applet's notification.

Best.

**Comment by collinss** [comment]
Is this a request for a specific applet? If so, please specify which one.

**Comment by Nokia808** [comment]
Applet name is:

Num Lock/Caps Lock indicator with MessageTray notifications

**Comment by jaszhix** [comment]
Right click the applet, go to Preferences > About, what is the applet's UUID above the description?

**Comment by Nokia808** [comment]
UUID is betterlock

**Comment by Nokia808** [comment]
Is there plan to address this issue in future?

**Comment by collinss** [comment]
@icarter09 here: https://cinnamon-spices.linuxmint.com/applets/view/83

It's called "Num Lock/Caps Lock indicator with notifications"

**Comment by Centurix** [comment]
Addressed with this PR: https://github.com/linuxmint/cinnamon-spices-applets/pull/5942
