### ISSUE TITLE
[Sensors@claudiux] Merged applet does not appear on the website

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon-spices-applets#3226]
```
 * Applet version: 1.0.0 
 * Build date: 2020-09-16
 * Cinnamon version: 4.6.7
 * Distribution: Mint 20
 * Graphics hardware *and* driver used: does not matter.
 ```

@clefebvre @mtwebster @brownsr 

**Issue**
My new applet Sensors@claudiux was validated:
```
~/git/csa/cinnamon-spices-applets $ ./validate-spice Sensors@claudiux
✔ ✔ ✔ ✔ ✔ Sensors@claudiux is valid!
```

Its branch was merged with the cinnamon-spices-applets/master branch.

However, this applet does not appear on the website.

What happens?

Thank you for helping me!

Regards.
Claudiux

**Expected behaviour**

Let this applet appear on the website.

**Comment by claudiux** [comment]
You solved this issue! Thank you!

**Comment by NikoKrause** [comment]
For future reference:
Fixed by https://github.com/linuxmint/cinnamon-spices-applets/commit/cb9061c270852d7da47c05b872535da6cc3e38a5
