### ISSUE TITLE
[SpicesUpdate@claudiux]: Tray icon not hiding

### ISSUE THREAD

**Issue by abhidesh128** [linuxmint/cinnamon-spices-applets#3253]
```
 * Applet version/Build date : 6.1.0 (2020-10-11 03:26:00)
 * Cinnamon version : 4.6.7
 * Distribution - Arch
 * Graphics : 
     Device: Intel 2nd Generation Core Processor Family Integrated Graphics 
     driver: i915 v: kernel
     Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: vesa 
     resolution: 1366x768~60Hz 
     OpenGL: renderer: Mesa DRI Intel HD Graphics 3000 (SNB GT2) 
     v: 3.3 Mesa 20.2.0 
 ```

**Notify author of applet**
@claudiux 

**Issue**
Even the tray icon is hidden until nothing to report, it still shown on panel.

**Steps to reproduce**
1. Right click on the tray icon > configure > General > Display section - Check the box "Hide the icon as long as nothing to report"
2. Close the window. Tray icon still shown in tray.
3. Rebooting the system or restarting cinnamon doesn't solves the problem.

**Expected behaviour**
After checking the box, tray icon should be hidden.

**Comment by claudiux** [comment]
@abhidesh128 You're right. I'll fix this issue.
