### ISSUE TITLE
weather@mockturtl Missing localization on some headline titles in Config

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#3257]
```
 * Applet version/Build date 2.6.6 Oct 10, 2020
 * Cinnamon version 4.6.7
 * Distribution - Manjaro Cinnamon 20.1.1
 * Graphics hardware *and* driver used - Intel Haswell-ULT Integrated Graphics Controller (i915)  
 ```
**Notify author of applet**
@Gr3q

Thank you for making a very usable, stable, feature rich and well working applet! Here is a minor observation for future updates:

**Issue**
Some of the Weather Configuration headlines is not translated from English to your choosen language: "Weather conditions", "Panel (Taskbar)", "Popup menu" and "Keybindings".  

**Steps to reproduce**
Right click on the Weather Applet in panel and choose Configure, logged in using any language not English.

**Expected behaviour**
That all text in the Weather applet is translated to your choosen login language.

**Other information**
Edit and change:
#. settings-schema.json->conditionSettings->description
msgid "Weather Conditions"
To:
msgid "Weather conditions"
and Add:
#. settings-schema.json->presentationPanel->description
msgid "Panel (Taskbar)"
msgstr "...translation..."
#. settings-schema.json->presentationPopup->description
msgid "Popup menu"
msgstr "...translation..."
#. settings-schema.json->unitsIconsKeysKeybindings->description
msgid "Keybindings"
msgstr "...translation..."

**Comment by Gr3q** [comment]
You are absolutely right, they are not included in the .pot file.

It seems cinnamon-spices-makepot does not include section titles when it generates them
