### ISSUE TITLE
cheaty@centurix: Display issues

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#3279]
```
 * Applet version/Build date: Version 0.0.2 (2020-10-16 13:31:15)
 * Cinnamon version: Cinnamon 4.6.7
 * Distribution: Mint 20
 ```

**Notify author of applet**
@Centurix

**Issue**
Many cheats are not displayed correctly:
![Screenshot from 2020-10-22 18-17-30](https://user-images.githubusercontent.com/4856462/96901455-cfd3cb80-1482-11eb-8a0c-c230bf005ca6.png)

**Comment by Centurix** [comment]
I'm having difficulty trying to reproduce the issue, is there a particular theme being used on your installation? The applet uses courier bold for the code samples and it may be something to do with the theme or font configuration.

**Comment by sphh** [comment]
Nothing special…

Themes:
* Window border: Mint-X
* Icons: Mint-Y-Orange
* Controls: Mint-Y-Orange
* Mouse pointer: DMZ-White
* Desktop: Mint-Y-Dark-Orange

Font Selection:
* Default font: Ubuntu Regular 10
* Desktop font: Ubuntu Regular 10
* Document font: Sans Regular 10
* Monospace font: Hack Regular 10
* Window title font: Ubuntu Medium 10

Font Settings:
* Text scaling factor: 1.0
* Hinting: Slight
* Antialiasing: Rgba
* RGBA Order: RGB

And here I searched for `Courier` in `gnome-font-viewer`:
![Screenshot from 2020-10-27 10-38-04](https://user-images.githubusercontent.com/4856462/97283979-6401b200-1838-11eb-8b63-a514d0b952c7.png)

Is the Courier font hard coded? Why don't you use the System's Monospace font?

**Comment by Centurix** [comment]
Might be related to [this](https://forums.linuxmint.com/viewtopic.php?t=325523) issue. Looks like a possible MS dependency for the msscorefonts. I'll have to drop it back to the monospace. Thanks!
