### ISSUE TITLE
gpaste-reloaded@feuerfuchs.eu doesn't work with gpaste 3.38.2 because of API change

### ISSUE THREAD

**Issue by bazuchan** [linuxmint/cinnamon-spices-applets#3288]
I made quick patch, but it needs more work to support both APIs

```
diff -urN orig/gpaste-reloaded@feuerfuchs.eu/GPasteHistoryItem.js new/gpaste-reloaded@feuerfuchs.eu/GPasteHistoryItem.js
--- orig/gpaste-reloaded@feuerfuchs.eu/GPasteHistoryItem.js	2019-08-27 16:06:54.925613197 +0300
+++ new/gpaste-reloaded@feuerfuchs.eu/GPasteHistoryItem.js	2020-10-28 15:13:58.668412274 +0300
@@ -77,8 +77,10 @@
         this._index = index;
 
         if (index != -1) {
-            this._applet.client.get_element(index, Lang.bind(this, function(client, result) {
-                this.label.set_text(client.get_element_finish(result).replace(/[\t\n\r]/g, ''));
+            this._applet.client.get_element_at_index(index, Lang.bind(this, function(client, result) {
+                let item = client.get_element_at_index_finish(result);
+                this._uuid = item.get_uuid();
+                this.label.set_text(item.get_value().replace(/[\t\n\r]/g, ''));
             }));
 
             this.actor.show();
@@ -92,7 +94,7 @@
      * Remove history item
      */
     remove: function() {
-        this._applet.client.delete(this._index, null);
+        this._applet.client.delete(this._uuid, null);
     },
 
     //
@@ -114,7 +116,7 @@
      * Select history item
      */
     activate: function(event) {
-        this._applet.client.select(this._index, null);
+        this._applet.client.select(this._uuid, null);
         this._applet.menu.toggle();
     }
 };
```

**Comment by dima2306** [comment]
Is it related to Gpaste reloaded not "syncing" history with main Gpase program? I mean when I updated to Fedora 33 with Cinnamon DE Gpaste reloaded stopped working(( I do see history in main program, but applet stays empty. I've further researched this issue and noticed that when I search through the applet the specific item which is in history it does appear in the apple menu and stays there even when I clear search field, but as soon as I mistype for example, applet's history gets cleared.

**Comment by NikoKrause** [comment]
@Feuerfuchs

**Comment by bazuchan** [comment]
One more diff to fix syncing
```
--- GPasteHistoryItem.js.orig        2020-10-28 15:13:58.668412274 +0300
+++ GPasteHistoryItem.js  2021-02-08 17:33:25.203021525 +0300
@@ -91,6 +91,16 @@
     },
 
     /*
+     * Refresh history item's content
+     */
+    refresh: function() {
+        this._applet.client.get_element_at_index(this._index, Lang.bind(this, function(client, result) {
+            let item = client.get_element_at_index_finish(result);
+            this.label.set_text(item.get_value().replace(/[\t\n\r]/g, ''));
+        }));
+    },
+
+    /*
      * Remove history item
      */
     remove: function() {
```

**Comment by t3pfaffe** [comment]
This issue was resolved on my machine a month or two ago. Noticed there's still some activity on this issue. Maybe your pkgs are out of date or its something else?

```
 * Cinnamon version: 4.8.6
 * Distribution - Arch 5.10.12 (x64)
 * gaste-daemon version: 3.23.1-1 
 ```
![image](https://user-images.githubusercontent.com/16065962/107396831-08f97f80-6af6-11eb-83e4-16f71426efac.png)

**Comment by bitstrings** [comment]
Yeah, i have the same issue and this is from a fresh install. Works with the patches.

**Comment by bitstrings** [comment]
Will this be fixed or do we assume it's resolved?

* Cinnamon version: 4.8.6
* gpaste-daemon: 3.24.1

**Comment by NikoKrause** [comment]
@bazuchan Do you want to create a pull request with your fixes?

**Comment by klangman** [comment]
The patch worked for me.. GPaste 3.40.2, Cinnamon 5.03, Fedora 34

**Comment by C-O-D** [comment]
I can't see any items in the applet (the rows are there but no text) since the next-to-last version.
Cinnamon 5.0.4, Linux Mint 20.2

**Comment by klangman** [comment]
> I can't see any items in the applet (the rows are there but no text) since the next-to-last version.
> 
> Version 2.6 (2021-07-12 22:42:07)
> Cinnamon 5.0.4, Linux Mint 20.2

That's what the latest merge addresses. Just update your applets and it should work.

**Comment by C-O-D** [comment]
Well, with the latest update it doesn't workfor me.
That's why I wrote my comment and why I added the version number.

**Comment by t3pfaffe** [comment]
I am also getting a similar experience to what @C-O-D 's is reporting. 
However, I am running:
```
Cinnamon 5.0.4 on Arch 5.12.15
gpaste-client 3.24.1
gpaste-reloaded@feuerfuchs.eu 2.6
```
This may not be related, but the only error messages/problems I have been able to dig out of the logs relating to it is gpaste-ui core-dumping every time it tries to load. 

This is what I pulled from journalctl after running `$ /usr/lib/gpaste/gpaste-ui` and receiving a response of `Segmentation fault (core dumped)` 
[
gpaste-ui_3.24.1_core_dump.log](https://gist.github.com/t3pfaffe/29f8275b6f6ccb6a5322de31f32cddcf)

**Comment by klangman** [comment]
Based on the original post, I guess we have an API break starting with 3.38.2. If you upgrade GPaste I assume the issue will be resolved.

**Comment by C-O-D** [comment]
Can anyone provide a deb package from the latest version that I can use with Mint?

**Comment by Gr3q** [comment]
It seems the best course would be to support the versions before/after breaking change.

**Comment by klangman** [comment]
> Can anyone provide a deb package from the latest version that I can use with Mint?

Maybe you can try building from src? 

https://github.com/Keruspe/GPaste

Steps to install it after cloning (skip the ./autogen.sh part if you're building it from a tarball):

./autogen.sh
./configure --sysconfdir=/etc
make
sudo make install
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
