### ISSUE TITLE
multicore-sys-monitor@ccadeptic23 Separate CPU usage type?

### ISSUE THREAD

**Issue by pkoch** [linuxmint/cinnamon-spices-applets#3289]
Hi, @jaszhix! :wave: 

How hard would it be to split each CPU by usage type (IO, Nice, usr, sys, etc)? Would this be a welcome addition?

Thank you!

**Comment by claudiux** [comment]
@pkoch 
Hi, I am the new maintainer of this applet.
Where to find these informations? I do not think to integrate them in this applet. Maybe in a new applet? But I don't see much use for it.

**Comment by pkoch** [comment]
This was three years ago. I don't even remember the context anymore. 😅

Let's close this for now, and someone more motivated can re-opem if they want to.

Thank you for your contributions! 🫡
