### ISSUE TITLE
applet is not showing on Mint 20 Cinnamon x64

### ISSUE THREAD

**Issue by kleajmp** [linuxmint/cinnamon-spices-applets#3290]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
I installed the applet manually by extracting it to the correct folder, it shows up in the Applets system panel but it does not show in the "systray", I cannot click the settings button, it's greyed out ans shows an exclamation mark and this message:
"This applet contains function calls that could potentially cause Cinnamon to crash or freeze"

Is this a know issue? What can I do?

**Steps to reproduce**

**Expected behaviour**
Also not working on my other computer running Mint 19, same issue.

**Other information**
Freshly installed Mint 20 x64 on Intel i5 mbr

**Comment by claudiux** [comment]
Click on the "+" to add the applet on a panel.

**Comment by NikoKrause** [comment]
Which applet?
