### ISSUE TITLE
Cinnamenu@json: Arrow-keys trigger twice when IBus running, Regression of #3259

### ISSUE THREAD

**Issue by okaestne** [linuxmint/cinnamon-spices-applets#3294]
```
 * Cinnamenu@json 4.9.2 (2020-10-30 09:02:01)
 * Cinnamon 4.6.7
 * Mint 20 Cinnamon
 * NVIDIA GTX 970, NVIDIA 450.80.02
 * Snippet or attachment of ~/.cinnamon/glass.log (no useful information)
 * Snippet or attachment of ~/.xsession-errors (no useful information)

 ```

**Notify author of applet**
@fredcw 

**Issue**
When the IBus daemon is running, the `onMenuKeyPress` (applet.js:659) method is called twice, when using the right or left arrow keys, causing the selection in the grid view to skip one entry each time, which makes running programs by searching and selecting via keyboard annoying.
This has been introduced in #3259 (found out by `git bisect`).

Changing applet.js:973 (or 977) from `return Clutter.EVENT_PROPAGATE` to `return Clutter.EVENT_STOP` fixes the selection with arrow keys, but then the search entry field cursor can't be moved anymore.

**Steps to reproduce**
Activate IBus, restart Cinnamon, try to select an application with the left and right arrow keys -> selection skips an element

**Expected behaviour**
Obviously

**Comment by fredcw** [comment]
@okaestne Thanks for reporting. It's hard to know what to do here because I think some people may find it useful to navigate in the search entry for example when using the calculator. There might be another way to fix this problem, I'll have to think about it.

**Comment by okaestne** [comment]
If it were easy I would have created a pull request already ;) One option would be using the list layout for search results, so that the right and left arrow keys aren't required to select an entry, but I don't think that you want to give up the grid layout when searching.

**Comment by fredcw** [comment]
@okaestne I have a fix, will be included in next update. Thanks.

**Comment by fredcw** [comment]
@okaestne you can close this issue now if you wish as I neglected to do it previously. Thanks.
