### ISSUE TITLE
Search not working in CinnVIIStarkMenu@NikoKrause

### ISSUE THREAD

**Issue by gisn8** [linuxmint/cinnamon-spices-applets#3309]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@NikoKrause 

**Issue**
Search does not return results; program list remains unchanged when typing search term. 

**Steps to reproduce**

**Expected behaviour**
I begin to type the name of an installed gui program and the program list reduces to matching program names.

**Other information**
Running Linux Mint Cinnamon 19.2. Having issues searching in menu. It doesn't return results. I assume it's just me. The regular Linux Mint menu searches as expected, but I really prefer to use this. I've tried resetting to default settings, installing the latest version, and uninstalling/reinstalling with no improvement. Any ideas? Anything "under the hood" I could try?

**Comment by NikoKrause** [comment]
Thanks for bringing this issue to my attention. I fixed the bug. It takes a few days till it appears in Mints Applets Settings directly, though. You can download the latest version from the website though.

**Comment by NikoKrause** [comment]
Let me know, if it works for you.

**Comment by gisn8** [comment]
> Let me know, if it works for you.

Excellent! It works again! Thanks so much! 🙂
