### ISSUE TITLE
Timer with Notifications won't start

### ISSUE THREAD

**Issue by muzena** [linuxmint/cinnamon-spices-applets#332]
Timer with Notifications (notifications@markbokil.com) it can't be added to panel.
I get this error in .xsession-errors:

Cjs-Message: JS WARNING: [/home/goran/.local/share/cinnamon/applets/timer-notifications@markbokil.com/applet.js 387]: AppOptions is read-only
Cjs-Message: JS WARNING: [/home/goran/.local/share/cinnamon/applets/timer-notifications@markbokil.com/applet.js 388]: AppOptions is read-only
Cjs-Message: JS WARNING: [/home/goran/.local/share/cinnamon/applets/timer-notifications@markbokil.com/applet.js 388]: useless expression
Cjs-Message: JS WARNING: [/home/goran/.local/share/cinnamon/applets/timer-notifications@markbokil.com/applet.js 389]: AppOptions is read-only

**Comment by NikoKrause** [comment]
What does the glass-log say?

**Comment by muzena** [comment]
Glass-log:

@/home/goran/.local/share/cinnamon/applets/timer-notifications@markbokil.com/applet.js:16
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:155
Extension@/usr/share/cinnamon/js/ui/extension.js:116
loadExtension@/usr/share/cinnamon/js/ui/extension.js:449
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:236
---------------->
error t=2017-04-24T16:38:02.180Z [Applet "timer-notifications@markbokil.com"]: Error importing applet.js from timer-notifications@markbokil.com
error t=2017-04-24T16:38:02.180Z Could not load applet timer-notifications@markbokil.com

**Comment by Odyseus** [comment]
Hello, everybody.

@muzena: Just remove line 16 of applet.js file (`const PanelMenu = imports.ui.panelMenu;`). It seems that that file (panelMenu.js) was a remnant of Gnome Shell and it was removed from Cinnamon around version 3.2 (in Cinnamon 3.0.7 that file still exists and the applet loads and works fine). The applet doesn't make use of that constant, so it is safe to remove.

**Comment by NikoKrause** [comment]
@muzena
Are you using Cinnamon nightly?

Yeah it has been removed. Needs to be fixed.

**Comment by muzena** [comment]
@NikoKrause 
Yes Nightly.

**Comment by NikoKrause** [comment]
There are several more applets with the same issue. This will be fixed soon.
