### ISSUE TITLE
Cinnamenu@json: Spacer between session buttons and favourites looks like an icon

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#3320]
```
 * Applet version/Build date: 4.11.1 (2020-11-18 08:22:30)
 * Cinnamon version Cinnamon 4.6.7
 * Distribution: Linux Mint 20
 ```

**Notify author of applet**
@fredcw 

**Issue**
@fmeneuhe mentioned this already in the comment section of the applets page https://cinnamon-spices.linuxmint.com/applets/view/322 (and I cannot word it better). I just want to transfer it to the issue system …

* @fmeneuhe
  What is the big dot spot next to the session buttons? is possible to remove it?
  * @fredcw
    It's just a visual indicator to separate the session buttons from the fav app buttons. Unfortunately it's not possible to remove it atm. Do you think it would look better without it?
    * @fmeneuhe
      I think it is confusing, because looks like an icon app and it uses lot of room. I would replace it by a thin vertical bar and with the possibility to hide it from settings options. 

IMHO a thin vertical/horizontal bar or space would be less confusing and also use less space. Do you think that's possible?

**Other information**
Personally I would not need the option to hide the space …

**Comment by fredcw** [comment]
@sphh You're probably right. I think it looks ok with bigger icon sizes but a bit confusing with smaller icons. The dot was only meant to be a temporary measure until I figured out how to do a shaded line so I'll try to figure it out soon.

**Comment by sphh** [comment]
Thanks @fredcw for #3323. Looks good!!

BTW: Why do you import Cairo? https://github.com/linuxmint/cinnamon-spices-applets/blob/90863128c5a72212308f0d145bbe4be52fd77307/Cinnamenu%40json/files/Cinnamenu%40json/4.0/applet.js#L4
I just wonder, because it is not uses later …

**Comment by fredcw** [comment]
I forgot to take it out after I was trying to draw a color gradient line. I started by copying the code from menu separator item in popupMenu.js but it was getting a bit complicated so I went with a flat line instead.

**Comment by sphh** [comment]
Thanks for the spacer. It looks great!!

**Comment by fredcw** [comment]
I think it looks a lot better so thanks for the suggestion and feedback. I probably wouldn't have seen it as a priority otherwise.
