### ISSUE TITLE
hamster@projecthamster.wordpress.com: update for hamster v3.0.2

### ISSUE THREAD

**Issue by dr0bz** [linuxmint/cinnamon-spices-applets#3329]
hamster@projecthamster.wordpress.com

Is it possible to update the hamster@projecthamster.wordpress.com applet code to work with the current hamster application v3.0.2?

Best regards,
dr0bz

**Comment by Gr3q** [comment]
@dr0bz What exactly doesn't work for you? I tested it with that version and everything works fine for me

**Comment by dr0bz** [comment]
@Gr3q Sorry for not posting the details, i really thought the applet is just not compatible with the latest hamster version.

I open hamster-applet menu and click on _show overview_ (might differ, i have German language) -> nothing happens. The error i get is:

JS ERROR: Exception in callback for signal: activate: Gio.IOErrorEnum: GDBus.Error:org.freedesktop.DBus.Python.ImportError: Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 711, in _message_cb
retval = candidate_method(self, *args, **keywords
File "/usr/lib/hamster-applet/hamster-windows-service", line 38, in overview
File "/usr/lib/python2.7/dist-packages/hamster/configuration.py", line 106, in show
File "/usr/lib/python2.7/dist-packages/hamster/configuration.py", line 132, in get_overview_class
ImportError: No module named overview
_proxyInvoker@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:82:16
_makeProxyMethod/<@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:112:16
anonymous/HamsterApplet.prototype._onShowHamsterActivate@/home/dr0bz/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com/applet.js:552:9
_emit@resource:///org/cinnamon/cjs/modules/signals.js:142:27
activate@/usr/share/cinnamon/js/ui/popupMenu.js:179:9
_onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:152:9

It might happen due to broken python installation. The hamster application is residing in /usr/lib/python3/dist-packages/hamster.

Best regards,
Dr0bz

**Comment by sietse** [comment]
Hi @dr0bz, is this still broken for you?

If yes, could you try to install the Project Hamster backend under Python 3 instead of Python 2? The [README at Hamster v3.0.2](https://github.com/projecthamster/hamster/tree/v3.0.2#dependencies) states that Python 3.5 is the minimum supported version; the traceback you posted mentions Python 2.7.

Kind regards,
Sietse

**Comment by dr0bz** [comment]
Hi @sietse,

thank you for the reply. The issue is not relevant anymore i changed the distro. But i think you are right: very likely messed up the python installation. It's not occurring on new distro.

Best regards,
dr0bz
