### ISSUE TITLE
Cinnamenu@json: add option not to use a panel icon

### ISSUE THREAD

**Issue by gilbertohasnofb** [linuxmint/cinnamon-spices-applets#3333]
```
 * Applet version/Build date: Version 4.11.2 (2020-11-20 07:26:28)
 * Cinnamon version (cinnamon --version): Cinnamon 4.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Linux Mint 20
 ```

**Notify author of applet**
@fredcw I have just migrated from Linux Mint 18.3 to Mint 20, and I am happy to see that Cinnamenu works with the new version. 

**Issue**

I like my menu to simply show the word `Applications` without any icon. In the past, I could enable the `Use a custom icon` option but leave its path empty in `Panel icon`. This would result in no icon being shown. In the current version with Linux Mint 20, it's not possible to leave `Panel icon` empty as that field is no longer typable, but rather a search for an icon file.

**Other information**

Would it be possible for you to add an option to not show an icon in the panel at all?

**Comment by fredcw** [comment]
I don't think there's a simple way to change this because of the way settings work. However, there is still a way to do this. Make a copy of any .png file, set it as your icon then delete the copied file and restart cinnamon. When cinnamenu can longer find the file on disk, it shows no icon.

**Comment by gilbertohasnofb** [comment]
Thank you, I will give this a try. 

Would you still consider implementing this as a feature in the future, perhaps adding a toggle at the top of the Appearance tab named `Show panel icon`, which would be enabled by default. If disabled, then the toggle `Use custom icon` and fields `Panel icon` and `Panel text` could became greyed out.

**Comment by fredcw** [comment]
@gilbertohasnofb I just added an option to change the size of the panel icon. So now you can change the size of the icon to 0 and it will disappear. Thanks for the suggestion.

**Comment by gilbertohasnofb** [comment]
@fredcw Just updated to the latest version and tested it, it works really well. The only thing though is that it might be not too obvious to other users that they can select a custom icon and set the size to `0`. 

Also, about the new release, I noticed that when I click in the menu and it opens, it takes a couple of milliseconds for the icons to show up (I'm guessing something in the order of 200ms). It's short, but very noticeable, as if the shortcuts are being loaded. This wasn't the case before; is this an intended behaviour or a bug that needs reporting?

**Comment by fredcw** [comment]
Populating the apps list was originally quite slow so I think I changed it to populate the apps after the menu was opened in order to make the menu feel more responsive. I've made some speed improvements since then and neglected to test opening the menu with the apps already populated and it's actually pretty quick. I'll probably include this for the next update.

**Comment by gilbertohasnofb** [comment]
> I'll probably include this for the next update.

Great, thanks a lot. I'll report back once the new update is released.

**Comment by gilbertohasnofb** [comment]
I just updated the applet and the icons populate the menu instantaneously, thanks for getting this sorted!

**Comment by fredcw** [comment]
Cinnamenu still doesn't open as quickly as the default menu app so I think there's still room for more improvements.

**Comment by gilbertohasnofb** [comment]
For me it's now basically instantaneous, I can't see any delay whatsoever.

**Comment by fredcw** [comment]
@gilbertohasnofb Thanks for the feedback. You can close this issue now if you like as I forgot to do it myself.

**Comment by gilbertohasnofb** [comment]
@fredcw Thank you so much for all the work!
