### ISSUE TITLE
weather@mockturtl - German translation of "Mostly Sunny" is missing

### ISSUE THREAD

**Issue by Kabuse** [linuxmint/cinnamon-spices-applets#3334]
German translation of "Mostly Sunny" is missing. It should be "Meist Sonnig".

**Comment by Gr3q** [comment]
Hi, @Kabuse which weather provider are you using?

**Comment by Kabuse** [comment]
I am using Yahoo.

I have also seen some other translations missing during the last days, like "rain and snow".

Is there a complete list of the conditions, so I could help with translating the whole list?

**Comment by Gr3q** [comment]
Yahoo doesn't provide a list for the Condition texts, only for condition codes, so the only way is to collect them through using it.

Please collect any what you don't see translated and I'll include it in the translation file

**Comment by Kabuse** [comment]
I don't think so. This looks like a complete list of the Yahoo weather conditions:

https://developer.yahoo.com/weather/documentation.html

Code | Description
-- | --
0 | tornado
1 | tropical storm
2 | hurricane
3 | severe thunderstorms
4 | thunderstorms
5 | mixed rain and snow
6 | mixed rain and sleet
7 | mixed snow and sleet
8 | freezing drizzle
9 | drizzle
10 | freezing rain
11 | showers
12 | rain
13 | snow flurries
14 | light snow showers
15 | blowing snow
16 | snow
17 | hail
18 | sleet
19 | dust
20 | foggy
21 | haze
22 | smoky
23 | blustery
24 | windy
25 | cold
26 | cloudy
27 | mostly cloudy (night)
28 | mostly cloudy (day)
29 | partly cloudy (night)
30 | partly cloudy (day)
31 | clear (night)
32 | sunny
33 | fair (night)
34 | fair (day)
35 | mixed rain and hail
36 | hot
37 | isolated thunderstorms
38 | scattered thunderstorms
39 | scattered showers (day)
40 | heavy rain
41 | scattered snow showers (day)
42 | heavy snow
43 | blizzard
44 | not available
45 | scattered showers (night)
46 | scattered snow showers (night)
47 | scattered thundershowers

Should be easy to translate to every possible language.

**Comment by Gr3q** [comment]
They can be translated, but currently I'm using the text fields in the json response (see docs), and they can be different.

I don't want to switch to translating the weather codes because the text field is more descriptive (with a downside that it needs to be collected manually).

**Comment by Gr3q** [comment]
Sorry for putting this off for so long, the missing localisation string will be added in the next release.
