### ISSUE TITLE
Sensors@claudiux (Warning indication)

### ISSUE THREAD

**Issue by French77** [linuxmint/cinnamon-spices-applets#3336]
```
 * Applet Versie 1.4.0 (2020-11-08 09:03:54)
 * Cinnamon version 4.6.7 
 * Distribution - (Mint 20 Ulyana)
 
 
 

 ```

**Notify author of applet**
@claudiux 

**Issue**
**Gives a warning indication:** 
***This toolbar contains function calls that could cause cinnamon to crash,consider removing it***

**Other information**
![Schermafdruk van 2020-11-29 09-34-28](https://user-images.githubusercontent.com/3099270/100537320-c3802280-3227-11eb-907d-29514929bea1.png)

**Comment by claudiux** [comment]
Hi @French77,

It seems that this message comes from using the `sensors` program. To my knowledge, there is no javascript library to interface `sensors`. If anyone knows of one, well documented, I am interested!

@mtwebster ?

**Comment by claudiux** [comment]
@French77  This issue is now fixed. Thank you to close it.
