### ISSUE TITLE
Mailnag doesn't work in cinnamon 4.8

### ISSUE THREAD

**Issue by porcaror** [linuxmint/cinnamon-spices-applets#3339]
Mailnag applet doesn't work anymore in Cinnamon 4.8 (I have EndeavourOS)
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by NikoKrause** [comment]
Fixed by https://github.com/linuxmint/cinnamon-spices-applets/pull/3341

**Comment by porcaror** [comment]
Thank you very much.
Now it's possible to install the mailnag applet in Cinnamon.
But unfortunately when installing it on the panel bar I receive an error  "Something went wrong while loading" and then the icon applet appears in the panel bar but it doesn't work (no mail notification at all).

**Comment by NikoKrause** [comment]
Try to uninstall the applet and mailnag.
Reboot your computer and reinstall both.

There's also a ppa, which provides a more up to date version of mailnag. Maybe that does the trick? 

Which mail provider do you use? I tried gmx.de and web.de. The first worked fine, the last one didn't worked at all, but that's most likely an issue with mailnag not with the applet.

If you're using gmail: a user on the spices website mentioned, that you have to allow mailnag.

Have a look at the latest comments there. There's also described, how to add the ppa.

https://cinnamon-spices.linuxmint.com/applets/view/244
