### ISSUE TITLE
[mailnagapplet@ozderya.net]: Failed to start with cinnamon 4.8.0

### ISSUE THREAD

**Issue by Dany-Dan** [linuxmint/cinnamon-spices-applets#3340]
```
 * Applet version/Build date : 2020-08-03 23:22:01
 * Cinnamon version : 4.8.0
 * Distribution : Arch Linux
 ```

**Notify author of applet**
@hyOzd

**Issue**
Applet failed to start after updating to cinnamon 4.8.0

`
Cjs-Message: 12:14:40.481: JS LOG: [LookingGlass/error] 
[mailnagapplet@ozderya.net]: missing ( after for
[mailnagapplet@ozderya.net]: Error importing applet.js from mailnagapplet@ozderya.net
`

**Steps to reproduce**

- Update cinnamon to 4.8.0 version
- Restart desktop session

**Comment by NikoKrause** [comment]
Fixed by https://github.com/linuxmint/cinnamon-spices-applets/pull/3341
