### ISSUE TITLE
vpnLookOut@claudiux: not working with StrongSwan VPN

### ISSUE THREAD

**Issue by Kallys** [linuxmint/cinnamon-spices-applets#3343]
```
 * Applet version/Build date : Version 3.5.1 (2020-08-10 23:00:43)
 * Cinnamon version : 4.6.7
 * Distribution : Mint 20
 ```

**Notify author of applet**
@claudiux 

**Issue**
Applet tells me that I'm always connected to my VPN (green icon) which is wrong.
When I try to disconnect using applet, it changes nothing.
Applet auto-detect a virtual interface "vibr0".

I don't know how ipsec VPN works, but it seems this is not supported by applet, unless something went wrong in my configuration.

**Comment by claudiux** [comment]
Hi @Kallys,

This applet is not working with virtual interfaces like "vibr0", but only "tun0". 

I'm working on a new applet but I'm too busy now to continue this development for several weeks.

**Comment by claudiux** [comment]
@Kallys Please try my new applet VPN-Sentinel: https://cinnamon-spices.linuxmint.com/applets/view/368
