### ISSUE TITLE
"Num Lock/Caps Lock indicator with MessageTray notifications" Does not work on LMDE 4 Debbie

### ISSUE THREAD

**Issue by einaring** [linuxmint/cinnamon-spices-applets#3344]
Im recently download it from the Applets Manager (Fresh LMDE Debbie), but once i installed, cant enable it

```
 * Applet version/Build date (Updated on 2020-10-13 02:05:45)
 * Cinnamon version (LMDE 4 Debbie)
 * Distribution - (LMDE 4 Debbie)
[xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/5632347/xsession-errors.txt)

 ```

**Notify author of applet**
@

**Issue**
When i try to setup or eneable the Applet the buttons dont even work
![screenshot](https://user-images.githubusercontent.com/62968484/100937491-10caf100-34c1-11eb-82ac-cc9aa402e036.png)

**Comment by NikoKrause** [comment]
Any mention of the applet in the logs?
