### ISSUE TITLE
multicore-sys-monitor@ccadeptic23 Feature: Alternative overall width setting

### ISSUE THREAD

**Issue by jondo** [linuxmint/cinnamon-spices-applets#3345]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json"): 1.8.91
 * Cinnamon version (cinnamon --version): 4.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 20
 ```

**Notify author of applet**
@jaszhix

**Issue**
I want to make the overall widget smaller. For this I currently have to go through all the separate width settings. My suggestion: In the General tab, provide an overall width setting, and a switch to turn it on.
This should compute an corresponding field width, equal for all different fields.

**Comment by claudiux** [comment]
On computers with a large number of CPUs, this may make this applet too large.

**Comment by jondo** [comment]
@claudiux  I think you misunderstood my suggestion. It would be just a way to set all the separate width settings at once, instead of needing to set each of them separately. This cannot make the applet larger than now.

**Comment by claudiux** [comment]
My 'CPU' width is set to150. My 'NET' width is set to 75. I can't set both to the same value.

**Comment by jondo** [comment]
I see – it's just my special case that all my widths are set as equal.
