### ISSUE TITLE
Cinnamenu@json: Request to change the panel icon size independently

### ISSUE THREAD

**Issue by Oober** [linuxmint/cinnamon-spices-applets#3346]
It would be REALLY nice if the panel icon size could be different (larger) than the other icons in the appropriate panel zone. Default Cinnamon Menu makes this possible, could you implement this feature also into Cinnamenu?

**Comment by NikoKrause** [comment]
?

**Comment by Oober** [comment]
Actually found the solution. I changed the menu icon file to icon-symbolic.png and that superior applet enables me to change that icon size independently.

Thank you for a great applet! This is rock solid, even stabler that the default menu.
