### ISSUE TITLE
weather@mockturtl - Feature request

### ISSUE THREAD

**Issue by GHNewbiee** [linuxmint/cinnamon-spices-applets#3364]
Optionally, date to be added next to the forecast days e.g. <today is Wed Dec 16>
```bash
Today,16th     Tomorrow,17th     Friday,18th     Saturday,19th    Sunday,20th   ...
```

By that, if we are interested in seeing the forecast on 25th, we **avoid** counting 16, 17, 18, ..., oh 25th.

*Tia*

**Comment by Gr3q** [comment]
Thank you, I'm working on it, although I still need to decide on a display format what looks good in most situations

**Comment by GHNewbiee** [comment]
Format would also be. by choice,:
```bash
Today,16th     T'row,17th     Fri,18th     Sat,19th     Sun,20th ...   (3 letters)  or
Today,16th     T'row,17th     F,18th       S,19th        S,20th ...    (1 letter)
```
if space troubles you.

You would also omit "st", "nd", and "th".

**Comment by Gr3q** [comment]
I meant more like languages and localisations

**Comment by Gr3q** [comment]
Added it, It will be the next release, I went with the JS default format (for each locale)
