### ISSUE TITLE
Question Development: Bind Spinbutton max value to value of other Spinnbutton in settings

### ISSUE THREAD

**Issue by jonath92** [linuxmint/cinnamon-spices-applets#3402]
I am currently working on the radio applet. I want to add two Spinbuttons in the settings which shall allow the user to set the maximum and the initial volume of the radio: 
![image](https://user-images.githubusercontent.com/49979415/103454797-b43d3a80-4ce7-11eb-97ae-78c24302f175.png)

As you can see in the above screenshot, it is currently possible to set the initial volume above the maximum volume which is not very logical. In order to prevent this, I want to bind the max value of the initial volume to the value of the maximum volume. So that when a user  increase the initial volume above the maximum volume or decrease the maximum volume below the initial volume, the initial volume is automatically updated. Optimally the settings-schema.json file should look something like this (which is not working):

```
 "max-volume": {
    "type": "spinbutton",
    "default": 130,
    "min": 100,
    "max": 200,
    "step": 5,
    "description": "Maximum Volume"
  },
  "initial-volume": {
    "type": "spinbutton",
    "default": 50,
    "min": 5,
    "max": "max-volume", // this is not working
    "step": 5,
    "description": "Initial Volume",
  },
```

As a workaround I thought I could ensure that the initial-volume is always <= the max-volume programmatically by changing the initial volume in the both callback functions for the inital-volume and the max-volume, e.g for the initial-volume in that way: 
```
_init: function (orientation, panel_height, instance_id) {
   ...
   this.settings.bind("initial-volume", "initial_volume", this.on_initial_volume_changed);
   ...
},

on_initial_volume_changed: function () {
    if (this.initial_volume > this.max_volume) {
       this.initial_volume = this.max_volume
    }
},   
```
However in that case I always get the following error in the `~/.xsession-errors` file when increasing the initial volume above the maximum volume: 
```
(cinnamon:20527): Cjs-CRITICAL **: 10:57:57.513: Object Cinnamon.GenericContainer (0x561c579103f0), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
```

The initial volume is in that case not directly updated but only after closing and reopening the settings. 

So my question is how can I achieve that that the max value of the initial value is binded to the value of the maximum volume? I had a look at the [settings example applet](https://github.com/linuxmint/cinnamon/tree/master/files/usr/share/cinnamon/applets/settings-example@cinnamon.org)  and many other applets but couldn't find a way to achieve this. In case this is not possible, can this issue be handled as feature request? 

Any hints are much appreciated.

**Comment by NikoKrause** [comment]
Why do you need an initial volume in the first place. Can't you just store the last used value?

**Comment by jonath92** [comment]
Thanks for your fast apply. I have thought about that but this has the following disadvantages:  
- The problem is that the actual sound also depends on the global volume (I think the correct technical term is actually master volume). Imagine a user has a low master volume and a high radio volume and the next time he starts the radio he has a large master volume. This would lead to excessively loud sound when he starts the radio next time (which potentially even could be harmful to the users ears). We could circumvent this problem by also saving and applying the master volume however this doesn't solve the next following problem. 
- Imagine a user listen to the radio on one day with high radio and high master volume with his loudspeakers and the next time he listens with his headsets. Even if we save the master volume, the user probably would be pissed by the high volume anyway

Obviously the approach of defining an initial volume has also some disadvantages (especially that the user might need to adjust the volume again each time) but as each method has disadvantages I thought allowing the user to set an initial volume is a good start and we can add more options later.

**Comment by fredcw** [comment]
@jonath92 Why not set the max volume on both the maximum volume and the initial volume to the same value in the settings-schema, i.e. 200. And then if the user increases the initial volume above the maximum volume, then programmatically increase the maximum volume to reflect this.

so instead of:
```
on_initial_volume_changed: function () {
    if (this.initial_volume > this.max_volume) {
       this.initial_volume = this.max_volume
    }
}
```

use:

```
on_initial_volume_changed: function () {
    if (this.initial_volume > this.max_volume) {
       this.max_volume = this.initial_volume
    }
},   
```

**Comment by jonath92** [comment]
that sound as a good idea @fredcw but unfortunately the problem persists. First of all I need to correct myself. The error mentioned in previous post was not to related to the volume settings - so this can be ignored. But the problem is still that the  settings are not immediately updated but only after closing and reopening the settings. This does not happen when I change the value from the popup menu, e.g. when I change the `on_inital_volume_changed` function to: 

```
on_initial_volume_changed: function () {
    this.max_volume = 50;
}
```

It happens the following: 

![Peek 2021-01-04 12-04](https://user-images.githubusercontent.com/49979415/103529024-3b73e500-4e85-11eb-93f2-b24725b2ee8c.gif)

However  if I change the function, executed when pressing on "stop" inside the popup menu to exactly the same, the settings are immediately updated - without the need of reopening the settings: 

```
on_stop_item_clicked: function () {
   this.max_volume = 50
}
```


![stop](https://user-images.githubusercontent.com/49979415/103529699-67dc3100-4e86-11eb-86de-0a336668de51.gif)


So I think I need to call somehow a refresh function after updating the settings. But I couldn't find anything in `/usr/share/cinnamon/js/ui/settings.js` for that.

**Comment by fredcw** [comment]
Not quite sure what you're getting at but if you're talking about the cinnamon settings not updating the value in the applet then have you set up a callback to update the value when it's changed in settings?

`this.settings.bind("some-max-volume-setting", "maxVolume", () => this.updateVolumeSetting);`

**Comment by jonath92** [comment]
Yes I have defined a callback function. This function is also indeed executed. I am sure about this because otherwise the value wouldn't change at all. However the value shown in the settings dialogue is not updated immediately but only after opening and closing the dialogue. I think it is not possible at the moment to immediately update the value of a widget in the setting inside a settings callback function ...

**Comment by fredcw** [comment]
@jonath92 This is strange. Whenever I've done this, the value in the settings dialog updates straight away even when the dialog is open.

```
this.settings = {};
this.settingsObj = new AppletSettings(this.settings, __meta.uuid, this.instance_id);
...
this.settingsObj.bind('custom-menu-height', 'customMenuHeight', () => callback());
...
this.settings.customMenuHeight = 123; //this should update the value in the settings immediately even when the settings dialog is open
```

I would need to look at your code to see what the problem is.

**Comment by jonath92** [comment]
> Edit: Ah, I just reread your comment. I haven't tried updating a setting from inside a setting callback function. I see the problem now...

Yes exactly.

> I would need to look at your code to see what the problem is.

Feel free to have a look at my pull request for the radio applet. 
Current Behavior:
- Open Settings of radio applet. Go to "Audio Player" tab and set the initial volume above the maximum volume
- Close Settings
- Open Settings and see that the initial volume is now equal to the maximum volume

Expected Behavior: 
-  Open Settings of radio applet. Go to "Audio Player" tab and set the initial volume above the maximum volume. Maximum volume is immediately updated

**Comment by fredcw** [comment]
@JonasJF360 Yes you're right, there seems to be no way to update a setting while responding to a setting change. It's strange but I can't find a way to do this.

I tried your applet and tbh, it's a bit confusing. I can't figure out what the max volume is supposed to do and neither the max volume nor the initial volume seem to make any difference to the volume of the music. Initial volume only seems to make a difference after restarting cinnamon.

Also, although I'm not sure what the max volume setting is supposed to do, the initial volume setting could be specified as a percentage of the max volume (0 - 100%) instead of a specific value maybe?

**Comment by jonath92** [comment]
Thanks for your feedback @fredcw .

I think you have overseen the fact that you can change the volume (which indeed is not that obvious). You can change the volume by moving the cursor above the applet icon and scrolling the mouse wheel (the same as with the sound applet).  But you cannot increase the volume with the mouse wheel above the maximum volume. However I think it also should be added a slider for changing the volume to make it more obvious.  The initial volume is applied when clicking on a radio channel and no other channel is already running. This is the case when you start cinnamon and when you start a channel after clicking "stop".  NikoKrause has suggested to just store the volume and use it again when clicking on a channel and no other channel is running. I want to implement this as another option but this also has some disadvantages (see my comment above). IMO there definitely should be therefore also an option to set the initial volume individually. 

There also should be somehow a maximum volume because otherwise you can increase the volume without limit (this is possible with the used package for this).  This was the case before and due to this it easily happened to set a low master volume and very high radio volume which lead to a very bad sound quality.  Because of this I had to decide whether to set a hard coded maximum volume or a user-defined volume. The problem with a hard-coded value is that it is not that obvious which value to take. The sound is getting amplified as soon as the value is above 100. I don't fully understand what that means technically but in general the higher the volume is above 100 the worse the sound quality. But I guess this also depends on the output device. In KDEConnect and in the sound applet the volume for applications can only be set to 100. However in mpv you can set the volume by default to 130. So basically I think this setting won't be much used by users but it somehow also doesn't feel right to make the decision in behalf of the user. 

>Also, although I'm not sure what the max volume setting is supposed to do, the initial volume setting could be specified as a percentage of the max volume (0 - 100%) instead of a specific value maybe?

No I don't think so, tbh. Because this would be inconsistent to other applications, e.g. in this case a maximum volume of 200 % and an initial volume of 50 %, would be shown as 100 % in kdeconnect. And this would also mean that, the sound get immediately amplified as soon as the volume is increased which you wouldn't expect at 50 %. But I think I can make the fact, that the volume is amplified above 100 % more obvious by using a slider with an indicator for 100 % and a label for Amplified and Reduced as in the sound settings. This would make the applet also more consistent with Cinnamon. 

![image](https://user-images.githubusercontent.com/49979415/103931515-b147ad00-5120-11eb-9d68-aa81ff4237d7.png)

**Comment by fredcw** [comment]
>The problem with a hard-coded value is that it is not that obvious which value to take

The 100 refers to 100%, i.e. the waveform as it's received from the stream. less than this is a reduced waveform within the allowable range and greater than 100% is increasing the size of the waveform with the obvious risk of it going outside the allowed range of the signal, which is called clipping https://en.wikipedia.org/wiki/Clipping_(audio). This is the distortion you spoke of. Broadcast tv&radio and professionally recorded sound should always utilise the full dynamic range of the signal and thus any amplification should normally always cause clipping. Over amplification is only really useful on a bad (very quiet) recording where there is room for amplification without clipping. mpv and vlc (and cinnamon) allow overamplification but really I think this unnecessary, especially on the signal from a radio stream. Also, you'll notice that for instance, video controls on the internet only go to 100%, e.g. youtube. I would hard code the max volume to 100% and if people want a greater volume they can turn it up in cinnamon or over amplify it (up to 150%) in cinnamon. When an app supplies a sound to cinnamon (eg. chrome, vlc, mpv etc.) it only sends a waveform, not a volume. that's why if you over amplify the signal in the app (and introduce clipping) the clipping will still be there even if you turn the volume down in cinnamon.

**Comment by jonath92** [comment]
thanks @fredcw  that's a good explanation. I removed the max volume now from the settings and hard coded it to 100. Therefore the problem of this issue is basically solved (although it would still be great if it were possible to immediately change a settings parameter inside a callback function of a settings parameter)
