### ISSUE TITLE
ShutdownApplet@DeadMD : appears twice in Applets list

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3412]
```
 * Applet version 2020-05-01 21:29:41
 * Cinnamon 4.8.5
 * Mint 20.1
 ```

@icarter09

**Issue**
This applet appears twice in the list of applets :

![Capture d’écran du 2021-01-07 11-45-26](https://user-images.githubusercontent.com/3955499/103920504-ad605e80-5111-11eb-8c97-cdc113f54478.png)

**Comment by NikoKrause** [comment]
Those are 2 different applets:

https://cinnamon-spices.linuxmint.com/applets/view/159

https://cinnamon-spices.linuxmint.com/applets/view/49

**Comment by InfoLibre** [comment]
Are you sure ? I don't see the difference on LM 20.1 Cinnamon, excepted that one is in English and the other is using the locale (French).

![Capture d’écran du 2021-01-07 22-26-51](https://user-images.githubusercontent.com/3955499/103946967-aa786480-5137-11eb-8f51-47cda5a2605e.png)

![Capture d’écran du 2021-01-07 22-26-32](https://user-images.githubusercontent.com/3955499/103946976-acdabe80-5137-11eb-8361-50bf33ce2690.png)

**Comment by NikoKrause** [comment]
Sorry for my wording.
Those are two separate applets. But they are indeed not different.
One applet is just a fork of the other one with translations added.
The two separate ones are just ancient residues.
Before the spices were ported to GitHub, there was no chance for other people to translate or fix applets, if the author abandoned the applet. So people were forced to fork applets for simple fixes or translations. I guess nobody noticed in all those years, that we have still two versions of this applet. We get rid of one. 
Thanks for finding and reporting :-)
