### ISSUE TITLE
calendar@ccprog: Alignment of world clocks [cosmetic]

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#3420]
```
 * Applet version/Build date: Version 1.1.4 (2021-01-05 09:58:10)
 * Cinnamon version: Cinnamon 4.8.5
 * Distribution: Mint 20.1
 ```

**Notify author of applet**
@ccprog 

**Issue**
As can be seen in the two pictures below, the time of the world clocks are not aligned:

_Calendar with public Holidays (calendar@ccprog) [left] & [World Clock Calendar (calendar@simonwiles.net)](https://cinnamon-spices.linuxmint.com/applets/view/108) [right]_
![caldendar_holidays](https://user-images.githubusercontent.com/4856462/104121804-10800a00-5339-11eb-8a78-cbbd4914bd56.png) ![worldclock](https://user-images.githubusercontent.com/4856462/104121806-137afa80-5339-11eb-8e80-912c046fd948.png)

Is it possible to align these times? BTW I like the smaller padding between those two lines!

**Other information**
Maybe the same alignment could also be implemented in #3315? Here the World Clock Calendar also has problems …

**Comment by ccprog** [comment]
Thank you for the report.

As for alignment in tooltips, as far as I am aware of that is impossible.

**Comment by sphh** [comment]
Thanks for the PR!! Looking forward to see it as update.

Re the alignment in tooltips: That's exactly what I suspected …

**Comment by sphh** [comment]
@ccprog: Great, thanks!

Is there a reason, why there is a rather big padding between the times and the right border?
![Untitled](https://user-images.githubusercontent.com/4856462/104217927-ecedba00-5433-11eb-88e2-5e904c16be59.png)
(Just wondering …)

**Comment by ccprog** [comment]
It's either that, or the right alignment overshooting the right side by 1em. (Just like the simonwiles version does.) So I made a design decision.

**Comment by sphh** [comment]
Thanks for the explanation. (But doesn't the left alignment also overshoot?)
