### ISSUE TITLE
sysmonitor@orcus empty/collapsed after reboot

### ISSUE THREAD

**Issue by dajusc** [linuxmint/cinnamon-spices-applets#3432]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
    - Version 1.6.4 (2020-10-03 13:52:17)
 * Cinnamon version (cinnamon --version)
    - Cinnamon 4.8.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
    - Linux Mint 20.1
 * Graphics hardware *and* driver used
    - AMD Ryzen 7 PRO 4750G with Radeon Graphics, driver=amdgpu
 * Snippet or attachment of ~/.cinnamon/glass.log
    ---
 * Snippet or attachment of ~/.xsession-errors
    ---

 ```

**Notify author of applet**
@OrcusCZ 

**Issue**
If within the applet the network monitor is enabled, the applet collapses into a small empty rectangle after next reboot.

**Steps to reproduce**
1. Add applet to bar
2. Enable network monitor
3. Reboot system or sign off+on user from cinnamon session
4. Applet is collapsed

**Expected behaviour**
Visual appearance of applet should survive a reboot

**Other information**
Possibly related to #3350 and #3416 (cinnamon cjs-4.8.2)

**Comment by ehtron** [comment]
also on cinnamon restart  (strg-alt-esc)

**Comment by dajusc** [comment]
Thx, that's probably the easiest/fastest way to reproduce the problem

**Comment by OrcusCZ** [comment]
Hi, I have tried Mint 20.1 in a VM and reproduced the issue.

The fix suggested in #3350 helped for me. @dajusc could you insert line with code `let info;` right before this line https://github.com/linuxmint/cinnamon-spices-applets/blob/9eb793cae979bc8c00f33721f9df497f136bdb9c/sysmonitor%40orcus/files/sysmonitor%40orcus/3.2/providers.js#L132 and verify that it fixes the issue for you as well? The file should be at `~/.local/share/cinnamon/applets/sysmonitor@orcus/3.2/providers.js`.
Note: you should be using cjs version 4.8.2, but I think you already do as said in the other issue.
If it works for you, I will create a PR with fix in the morning.

I wrote the catch branch as a fallback for one system where `GTop.glibtop.get_netlist` would fail to return anything and most likely committed the wrong code without a declared variable.

**Comment by dajusc** [comment]
Hi, thank you for the quick response!
Yes, my CJS is currently version 4.8.2.
I added the one line of code as you described and **it indeed solved the issue** for me! :)

**Comment by OrcusCZ** [comment]
Hi, thank you for verifying. I have created a PR with a fix so it should be fixed in master soon :)

**Comment by dajusc** [comment]
Great! Thx for the fix and PR. :)

**Comment by dajusc** [comment]
Should have not closed this manually, because it will be closed automatically on merge of PR. --> reopening
