### ISSUE TITLE
cryptocoin@guantanamoe : doesn't work anymore, "Error loadingprices" message

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3453]
```
 * Applet version 1.7
 * Cinnamon version 4.8.6
 * Mint 20.1

 ```

**Notify author of applet**
@ImDeprecated

**Issue**

Only show the message "Error loading prices..."

![Capture d’écran du 2021-01-17 20-30-37](https://user-images.githubusercontent.com/3955499/104853711-e3b48f80-5902-11eb-959b-7e6a7ff34c6b.png)

**Steps to reproduce**

Configure like this :

![Capture d’écran du 2021-01-17 20-32-48](https://user-images.githubusercontent.com/3955499/104853778-59b8f680-5903-11eb-91ef-de56f8cf1d29.png)

**Comment by NikoKrause** [comment]
@imDeprecated

**Comment by icarter09** [comment]
@InfoLibre I use this applet quite a bit. I notice the error message as well when I change the ticker value, but after about 10 seconds, it goes away and the value appears for the given cryptocurrency. I just updated the applet to the latest version and it still works.

**Comment by InfoLibre** [comment]
I updated it but still the same error message.

**Comment by icarter09** [comment]
Are you able to view this URL? https://min-api.cryptocompare.com/

That's what the applet is using to retrieve the data.

**Comment by InfoLibre** [comment]
I see an error message :


  |  
-- | --
**Response | "Error"
Message | "You are over your rate limit please upgrade your account!"**
HasWarning | false
Type | 99
RateLimit |  
calls_made |  
second | 1
minute | 1
hour | 346
day | 3681
month | 80780
total_calls | 80780
max_calls |  
second | 20
minute | 300
hour | 3000
day | 7500
month | 50000
Data | {}

**Comment by icarter09** [comment]
Odd. I'm not sure why it's asking you to upgrade your account since the applet does not require you to login to use it. 
@InfoLibre have you tried removing/uninstalling the applet then adding it back? Maybe that will reset the rate limit.

**Comment by InfoLibre** [comment]
Yes, I removed the applet and installed it again. I changed the crypto (BTC, ETH...). Is there a log error file I could send to you ?

**Comment by icarter09** [comment]
The error log would be `~/.xsession-errors`. But the main issue is that the site the app uses is saying that you are over the limit for the free account. You aren't logged into that site (figured not but wanted to make sure). Another thing would be to remove the applet from `~/.local/share/cinnamon` instead of from the Applet download/manage UI.

**Comment by icarter09** [comment]
@InfoLibre this also might just be an issue of the site is now locking down free accounts when previously it was not. You might just be the first person to notice this and have submitted a ticket on the issue. I also have the `Rates update interval` turned down to only update every 10 mins instead of every 5 seconds.

**Comment by InfoLibre** [comment]
I removed it again :

![Capture d’écran du 2021-01-19 17-07-34](https://user-images.githubusercontent.com/3955499/105061257-9c044400-5a79-11eb-9fc9-e515af16709f.png)

When I install it, there's an error message ("error during the loading") :

![Capture d’écran du 2021-01-19 17-08-51](https://user-images.githubusercontent.com/3955499/105061309-aa526000-5a79-11eb-8339-ccc28a364751.png)

In .xsession-errors :

```
(pix:32488): GLib-GObject-WARNING **: 17:13:40.336: g_type_class_add_private() called multiple times for the same type
Cjs-Message: 17:14:42.781: JS LOG: [LookingGlass/info] Reloading applet: systray@cinnamon.org/3
Cjs-Message: 17:14:42.782: JS LOG: [LookingGlass/info] Reloading applet: xapp-status@cinnamon.org/4
Cjs-Message: 17:14:42.783: JS LOG: [LookingGlass/info] Reloading applet: notifications@cinnamon.org/5
Cjs-Message: 17:14:42.784: JS LOG: [LookingGlass/info] Reloading applet: printers@cinnamon.org/6
Cjs-Message: 17:14:42.785: JS LOG: [LookingGlass/info] Reloading applet: network@cinnamon.org/9
Cjs-Message: 17:14:42.785: JS LOG: [LookingGlass/info] Reloading applet: sound@cinnamon.org/10
Cjs-Message: 17:14:42.786: JS LOG: [LookingGlass/info] Reloading applet: calendar@cinnamon.org/12
Cjs-Message: 17:14:42.787: JS LOG: [LookingGlass/info] Reloading applet: weather@mockturtl/29
Cjs-Message: 17:14:42.787: JS LOG: [LookingGlass/info] [weather@mockturtl#29]: Removing applet instance...
Cjs-Message: 17:14:42.788: JS LOG: [LookingGlass/info] Reloading applet: download-and-upload-speed@cardsurf/38
Cjs-Message: 17:14:42.789: JS LOG: [LookingGlass/info] Reloading applet: ShutdownApplet@DeathMD/50
Cjs-Message: 17:14:43.060: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function 49]: Too many arguments to function GLib.file_set_contents: expected 2, got 4
Cjs-Message: 17:14:43.128: JS LOG: [LookingGlass/info] Installing settings for cryptocoin@guantanamoe
Cjs-Message: 17:14:43.128: JS LOG: [LookingGlass/info] Settings successfully installed for cryptocoin@guantanamoe
Cjs-Message: 17:14:43.248: JS LOG: [LookingGlass/info] Hiding XAppStatusIcon (we have an applet): nm-applet
Cjs-Message: 17:14:43.248: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintreport (:1.80/org/x/StatusIcon/Icon)
Cjs-Message: 17:14:43.250: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: oscar-unknown (:1.48/org/x/StatusIcon/Icon)
Cjs-Message: 17:14:43.251: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintUpdate.py (:1.74/org/x/StatusIcon/Icon)
Cjs-Message: 17:14:43.278: JS LOG: Unknown network device type, is 14
Cjs-Message: 17:14:43.323: JS LOG: [LookingGlass/info] [weather@mockturtl#29]: Saved locations are loaded in from location store at: '/home/david/.config/weather-mockturtl/locations.json'
Cjs-Message: 17:14:43.411: JS LOG: [LookingGlass/error] You are over your rate limit please upgrade your account!
Cjs-Message: 17:14:43.411: JS LOG: [LookingGlass/error] You are over your rate limit please upgrade your account!
Cjs-Message: 17:14:43.713: JS LOG: [LookingGlass/info] [weather@mockturtl#29]: Weather Information refreshed
Cjs-Message: 17:14:48.157: JS LOG: [LookingGlass/error] You are over your rate limit please upgrade your account!

```

**Comment by icarter09** [comment]
@InfoLibre not for sure what else to suggest. Looking like you have gone over the allotment for the free account.

**Comment by InfoLibre** [comment]
Feature request : adding the possibility to use other API, like https://www.kraken.com/fr-fr/features/api ?

**Comment by undersound** [comment]
Same problem here. Is the workaround to update the **Rates update interval**? Just set it on 10 minutes as suggested in https://github.com/linuxmint/cinnamon-spices-applets/issues/3453#issuecomment-762931767

**Comment by InfoLibre** [comment]
Tryed with 10 minutes (600 sec.), same bug.

**Comment by icarter09** [comment]
The only fix is going to be adding alternate APIs or using another API completely.

**Comment by undersound** [comment]
Yeah I am having no luck with the 10 minutes setting as well. I am curious though. Is this because rate limiting of the free account or? 

Can we use the free setting and allow a user to set this up with his own personal key? 
https://min-api.cryptocompare.com/pricing

**Comment by InfoLibre** [comment]
It works again, I don't know why, I just started my computer this morning !!!???

**Comment by InfoLibre** [comment]
It works again, I don't know why, I just started my computer this morning.

**Comment by NikoKrause** [comment]
I guess the website allows a certain calls per month, as the message says:

"You are over your rate limit please upgrade your account!"**

Since today is February 1st, your counter has reset. If you don't want it to see the "Error loadingprices" in the middle of the month again, I suggest you change the "Rate update intervall" to 5 or 10 minutes instead of 5 seconds.

**Comment by InfoLibre** [comment]
Aaahh, OK. I will try with 300 s this month.

**Comment by icarter09** [comment]
@InfoLibre can this ticket be closed?

**Comment by icarter09** [comment]
@InfoLibre feel free to make some feature request tickets for this applet such as using other APIs and possibly setting the default `Rate update interval` to a value that does not ping the server as much. Thanks.

**Comment by InfoLibre** [comment]
Yes, you can close it if you want.

**Comment by icarter09** [comment]
@InfoLibre you authored the ticket so you are able close it. Thanks.

**Comment by InfoLibre** [comment]
Done.

**Comment by NikoKrause** [comment]
We shouldn't allow update intervall rates as 5 seconds. Gonna change that.

**Comment by NikoKrause** [comment]
@InfoLibre Was 300 s enough for this month? I've changed the default setting to this value.

**Comment by InfoLibre** [comment]
It seems to work with 300.
