### ISSUE TITLE
Website: https://cinnamon-spices.linuxmint.com/ - The server is down too often

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon-spices-applets#3462]
**Issue**
Website: https://cinnamon-spices.linuxmint.com/ - The server is down too often.

**Steps to reproduce**
Try to access to https://cinnamon-spices.linuxmint.com/ or to https://cinnamon-spices.linuxmint.com/json/applets.json

**Expected behaviour**
Ensure access to this website.

**Other information**
Applets SpicesUpdate and Spices Notifier are disturbed.

**Comment by claudiux** [comment]
Unable to update applets!
![image](https://user-images.githubusercontent.com/33965039/106369334-dd85d080-6350-11eb-8c51-16083118708c.png)

**Comment by 392781** [comment]
Down again...
