### ISSUE TITLE
Cinnamenu@json: issues in 20.1

### ISSUE THREAD

**Issue by 4turtlez** [linuxmint/cinnamon-spices-applets#3463]
Some issues have cropped up in newest version:

Always open menu on favorite apps option no longer works

Missing the menu options to change the height of the menu (its way to big by default, loved 400 or less)

Missing option to change how many icons go across the menu (I always choose only having 3)

Really like the options this menu has to make it how each person likes!!

**Comment by fredcw** [comment]
@4turtlez Sorry I didn't reply sooner, I didn't see your post.

>Always open menu on favorite apps option no longer works

Do you have "Show favorite apps category" option enabled as well as "Always open menu on favorite apps"?

The size of the menu can now be changed by dragging on the edges. Sorry, I should indicate this in some way because it isn't obvious.

**Comment by 4turtlez** [comment]
That is awesome actually that now can adjust size of menu by dragging the
edges of it!! More menus need this feature!  But yeah might need a mention
of that in appearance section possibly.

And I have tried both ways with the favorites....and doesn't do the always
open to favorites currently.

Do love that the menu reopens to last used category as well though
otherwise . The customizability of this menu is fantastic!

Big Thanks!

**Comment by 4turtlez** [comment]
Sorry I was mistaken with the favorites. I had tried it with add favorites
session buttons turned on and off...totally didn't have show favorite app
category content turned on....Ha....My bad!
