### ISSUE TITLE
sticky@scollins Title height does not adjust when font changed is adjusted larger

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#3474]
Version 1.2 (2020-10-13 03:05:45)
Cinnamon 4.8.6
Mint 20.1 Cinnamon 64bit.
Intel built in video.
No error messages, just visual issue.
@collinss 

**Issue**
I changed the font size in config to 24pt.  I like big letters, on 1920x1080 monitor.
The lines of text in the notes look fine but the title line height does not enlarge enough for the new font change.  Bottoms of the letters are cut off.

![Screenshot from 2021-01-25 15-22-18](https://user-images.githubusercontent.com/26556059/105762160-060d6500-5f22-11eb-98c2-8d89853ee877.png)

**Comment by ChooChooAl** [comment]
New  Version 1.2 (2021-02-24 16:37:53) Still has this same bug.
@scollins

**Comment by collinss** [comment]
Hi @ChooChooAl I'm not really maintaining this applet any more. Instead, I've been working on a sticky notes stand-alone app in gtk. It works sort of similar to this one, but it's more flexible (it can be installed and used in any desktop environment), and can do a lot more (undo/redo, text formatting, and organizing notes into groups are just a few examples). It's actually included in Mint 20.2 (the beta released yesterday). You can check out the repository if you want as well: https://github.com/linuxmint/sticky (and even build it yourself if you don't want to try the beta or wait for release).

**Comment by ChooChooAl** [comment]
Thanks, I saw the info on 20.2 this AM and that's why I tested to see if this applet had been fixed.   
I'll hold out for the 20.2 release and upgrade.   Thanks.   I'm closing this for me.
