### ISSUE TITLE
weather@mockturtl V3.0.0

### ISSUE THREAD

**Issue by French77** [linuxmint/cinnamon-spices-applets#3486]
```
 * Versie 3.0.0 (2021-01-30 09:52:53)
 * Cinnamon version (4.8.6)
 * Distribution - (Mint 20.1)
 
 
 

 ```

**Notify author of applet**
@Gr3q

**Issue**
Wind direction icon does not show the correct current direction

**Screenshots**
#### Direction icon applet
![icon wind direction](https://user-images.githubusercontent.com/3099270/106361042-15265580-631c-11eb-992d-2082efabb80c.png)
#### Wind direction today
![wind richting](https://user-images.githubusercontent.com/3099270/106360740-88c76300-631a-11eb-96e9-3cb618730310.png)
#### Wind direction icon wttr.in
![wttr in](https://user-images.githubusercontent.com/3099270/106361062-2ff8ca00-631c-11eb-8626-722dcf643d94.png)

**Comment by Gr3q** [comment]
I'll have a look, maybe I switched up the icons.

 Also, what theme are you using? The icon really shouldn't be black, I'll have to sort that out as well

**Comment by French77** [comment]
> Also, what theme are you using? The icon really shouldn't be black, I'll have to sort that out as well

Cinnamox-Kashmir-Blue

**Comment by Gr3q** [comment]
Oh yeah, obviously east wind is coming from the east, not going to east...

**Comment by Gr3q** [comment]
@French77 If you switch to symbolic icons are they also black? (icons are not black for me btw)

**Comment by French77** [comment]
@Gr3q When I switch to symbolic icons,direction icon is white after refreshment,but don't really like the symbolic icons.

**Comment by Gr3q** [comment]
yeah sure, I just wanted to see if there is a problem with the logic

**Comment by jorgenqv** [comment]
@Gr3q 
I think it's a good idea to keep the Wind direction arrow and the letters at the end to minimize confusion :-)
Like: ← 5.6 m/s E
