### ISSUE TITLE
weather@mockturtl 2.7.0 not acknowledging Climacell API key

### ISSUE THREAD

**Issue by garuffalo** [linuxmint/cinnamon-spices-applets#3488]
weather@mockturtl 2.7.0 shows "incorrect API key" when switching to Climacell

```
 * Version 2.7.0 (2021-01-30 03:52:53)
 * Cinnamon Version 4.4.8
 * Distribution - Linux Mint 19.3 Cinnamon (Tricia)
 * Graphics hardware - Intel Mobile GM965/GL960 Integrated Graphics (driver: i915)
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@mockturtl 

**Issue**
I signed up for a developer account at your link, https://developer.climacell.co/sign-up to obtain an API key. Sign-up appeared to go OK and took me to an account page with the "Secret Key". I have previously been using Dark Sky with no issues, but wanted to try another API as Dark Sky will cease to work at the end of this year. When selecting Climacell in the configure window and providing the API key I was given, the applet declared "incorrect API key".

**Steps to reproduce**
Switched back and forth between Dark Sky and Climacell several times with same failed result with Climacell every time. Restarting Cinnamon or rebooting the computer did nothing.

**Expected behaviour**
With correct API keys, one should be able to switch between different data providers.

**Other information**
I received a welcome email from Climacell and was able to log in to my account through a link in the email. However, when I attempt to log in at https://developer.climacell.co/sign-in, login fails. Even the "forgot password" link doesn't work.

If I go to to the homepage at https://www.climacell.co/ I can log in to Weather API v4 at https://app.climacell.co/signin - but not Weather API v3. API v3 has a white themed interface, and appears to be the one used at https://developer.climacell.co/sign-in, whereas API v4, at https://app.climacell.co/signin uses a dark theme.

Is it possible that the Weather applet is set to use API v3, but new signups are for API v4?

**Comment by Gr3q** [comment]
You are right, they block registrations for v3 and redirect to v4. The applet uses v3, so i have to specify that, and create a new provider for v4 to make transition smooth, the remove v3 later this year, as do they

**Comment by Gr3q** [comment]
I added the v4 version of Climacell so when 3.0.1 becomes available you can try it out
