### ISSUE TITLE
Development Question: Is there a simple way to ensure that only unique values are used in list column?

### ISSUE THREAD

**Issue by jonath92** [linuxmint/cinnamon-spices-applets#3491]
For the radio applet I would like to ensure that the users can only add radio channels with a URL not used before and a title not used before. Optionally it should be shown an error message when users try to add a channel with an already existing name/url 

![image](https://user-images.githubusercontent.com/49979415/106393030-e3cd8880-63f4-11eb-868a-78f8a7ab83d2.png)

I don't see any method to do this except writing my own widget for that.  This would me okay for me but as this is not that easy and I haven't done this before I wanted to ask if anybody knows an easier option for that.  

Any help is much appreciated

**Comment by Gr3q** [comment]
as far as I know there is no unique constraint option what you could use.

If I had to do it, I'd make the binding BIDIRECTIONAL then set the list from the callback without the added entry, then send a notification. definitely not perfect nor nice, but easy.

Alternatively if you have lots of time you will have to roll your own custom setting. See the Settings API demo code in `/usr/share/cinnamon/applets/settings-example@cinnamon.org`. See how it defines a custom widget in `CustomWidget.py` and how it's used. Then you could use that as a base and dig through the [GTK docs](https://gjs-docs.gnome.org/gtk40~4.0_api/) how to recreate the listview exactly how you want it.

**Comment by jonath92** [comment]
> Edit: /usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py has the implementation of the List widget in the settings, you could copy it, modify it and use it as a custom widget as seen in Settings API.

I will use that as a starting point. Thank you :-).
