### ISSUE TITLE
tracker@glebihan: Feature request: Add an option to define the result window size and naming pattern

### ISSUE THREAD

**Issue by Piiit** [linuxmint/cinnamon-spices-applets#35]
It would be nice to set the text entry width to half resolution of the screen (or to something linke 3/4 of the monitor). Results are truncated most of the time.

![arbeitsflache 1_049](https://cloud.githubusercontent.com/assets/6096063/22372354/7d252588-e49c-11e6-8359-21d34c5298fc.jpg)

Other Files should maybe show filenames only (with paths in paranthesis afterwards). Also shortening the paths would be nice, like /home/xyz/.../topic/ch1.pdf for instance.

**Comment by Piiit** [comment]
@glebihan, if you have any questions, please let me know.

**Comment by icarter09** [comment]
@brownsr this ticket can be closed. Applet has been removed.
