### ISSUE TITLE
hamster@projecthamster.wordpress.com: missing ( after for

### ISSUE THREAD

**Issue by dr0bz** [linuxmint/cinnamon-spices-applets#3501]
hamster@projecthamster.wordpress.com

```
 * Applet version/Build date -  "version": 0.2 (it's from current master)
 * Cinnamon 4.8.5
 * Distribution - Arch
 * cjs - 4.8.2-1
 ```

**Issue**
If i try to add the applet, then the applet does not appear on the panel

**Steps to reproduce**

- right click on panel
- applets
- find hamster applet
- click on plus

**Expected behaviour**
The applet should appear on the panel

**Other information**
This is the error at looking glas:

```
[hamster@projecthamster.wordpress.com]: missing ( after for
[hamster@projecthamster.wordpress.com]: Error importing applet.js from hamster@projecthamster.wordpress.com
```

**Comment by NikoKrause** [comment]
Fixed
