### ISSUE TITLE
weather@mockturtl New 3.0 release - Configure improvments thoughts

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#3507]
```
 * Applet version/Build date 3.0.1 Feb 1, 2021
 * Cinnamon version 4.8.6
 * Distribution - Manjaro Cinnamon 20.2.1 Nibia
 * Graphics hardware *and* driver used - Intel Haswell-ULT Integrated Graphics Controller (i915)  

```

**Notify author of applet**
@Gr3q

Thank you and congrats to an excellent 3.0 release of the Weather applet! I really like it :) Here are some minor suggestions below to make it even better.

**Issue**

The Help tab in Configure contains lots of text and can be a bit hard to read and understand.
So here are some ideas for a better placed and clearer help texts by spreading it out.

1. Move text section 'How to choose a weather provider' from the Help tab to the bottom of the first Weather tab and change it to:
```
About Weather Providers:
You can use several different weather forecast providers by choosing from 
the dropdown menu Data service. Some providers require a API key to work, 
some have regional limits, differ in forecast length, and they all need a 
functional internet connection to work. Usually it takes a wile after 
registering before the API key works. Options are described in detail on 
the Cinnamon Spices Website, click the link button under the Help tab.
```

2. Move text section 'Allowed location formats' from the Help tab to the bottom of the second Location tab and change it to:
```
About Location formats:
Your location in most cases work automatically but you can enter it manually 
by activating Manual location and filling out the Location field. 
Use coordinates 'Latitude,Longitude' (e.g. 51.5085,-0.1257) or use 'City,
Country-code' (e.g. London,UK) or try to enter {House number} {Street} {City/
Town} {Postcode} {Country}. The search algorithm is very flexible with the 
format. After 3 seconds without typing, the address you entered is replaced 
automatically for validating your choice.
```

3. Change text sections 'View additional information' and 'Report an issue' under the Help tab to:
```
More about the Weather applet:
For more detailed information about the applet please go to the Spices Website 
by clicking the button below. You can also comment and ask a questions to the 
community at this page by logging in with your Github account. You can also find
information about known issues, troubleshooting, changelog etc. 

Report an issue:
If you find an issue with this applet please make a report by clicking on 
the button below. Please make sure that the issue is not already submitted.
Login in with your Github account. Don't forget to write weather@mockturtl 
in the top Title field to make it easier for everyone to know that the issue 
is about the weather applet (the form is for all Cinnamon applets).

```

**Steps to reproduce**
Right click on the applet in the panel and choose Configure.

**Expected behaviour**
Easier understanding of how the Weather applet works for new beginners. 

**Other information**
- submitIssue->tooltip does not show tooltip for me when hoovering the button, therefor adding this info in Report issue help text.
- Typo found in pot template, remove "is" in weatherbit.js:230 "API key is doesn't provide access to Hourly Weather, skipping"

**Comment by jorgenqv** [comment]
Another idea for Configuration: Why not add a symbol as a hint on things that have a tool-tip text? Here is a example where I use the [unicode circle i](https://www.unicodepedia.com/unicode/enclosed-alphanumerics/24d8/circled-latin-small-letter-i/) added in the settings-schema file (probably wrong place)...

![Screenshot from 2021-02-04 15-46-59](https://user-images.githubusercontent.com/5297223/106910823-e6382700-6701-11eb-9404-0ae790c3e627.png)

**Comment by Gr3q** [comment]
I can do most of the things here although around 80% of the settings have tooltips, I think it would look weird with all the Icons

**Comment by jorgenqv** [comment]
Ok thanks, great. And sure, agree about the icons now when I looked on the other tabs.

**Comment by Gr3q** [comment]
I've changed most, but instead of putting them into the provider and location page I've put them in as tooltips, so it's more obvious which control they belong to

**Comment by jorgenqv** [comment]
@Gr3q 
Looks very good och feels much more clean and easy to understand, tooltips works great.
One minor thing is the first Help info could be slightly shortened and better (now same start of the last two sentences, sorry)
like:
```
More about the Weather applet:
For detailed information about the applet please go to the Spices Website to find info about
known issues, troubleshooting, changelog and more by clicking the button below. 
Here you can ask questions etc in the comment section by logging in with your Github account.
```

**Comment by Gr3q** [comment]
Ah, yeah it's quite obvious, I'll change it

**Comment by jorgenqv** [comment]
There is also a small change in the "Report an issue" text about checking for issue is not already submitted, that didn't make the 3.0.2 release.

**Comment by Gr3q** [comment]
also added
