### ISSUE TITLE
weather@mockturtl Add Weather Forecast Provider DMI possible?

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#3508]
@Gr3q

I have been using the Danish Weather Provider DMI on the web for many years and feel they often are very accurate where I live. They do not have a official API yet but plan for providing this for free next year.

But then I found this unofficial workaround, so I wonder if it's possible at all to add DMI in the Weather Applet as a provider now or is it not possible?

https://github.com/rugaard/dmi

Thanks!

**Comment by Gr3q** [comment]
After having a look, i think I might be able to do this.

Their internal API url is this atm: `https://www.dmi.dk/NinJo2DmiDk/ninjo2dmidk?cmd=llj&lon=0.1084&lat=52.2231` with my full query.

**Comment by Gr3q** [comment]
I'll integrate it if you define the payload for me (like each field's unit).

I'm most interested in `windDir` and `precipType` because they are not in English and their possible options, and the `symbol` property, all the possible options for it and what they mean (icons represent the symbol on the website).

You can cross-reference the symbol's in the API and the icons(conditions on the website).

If you provide all of this I'm more than happy to integrate it

**Comment by Gr3q** [comment]
Here https://www.dmi.dk/lokation/show/US/4959902/Cambridge/#vejrgrafer I think the icons' filename in the website's html matches the symbol name (at least for hourly weather), so it makes life easier

**Comment by jorgenqv** [comment]
Very cool that there is a chance that this could work :)  I will be happy to try to define the icons definition to English but I am unsure how to do it and to cross reference and match? If i look at the API feed `time "20210206220000"` compared to the website it looks like `precipType 'regn'` have an icon that looks like cloudy? https://www.dmi.dk/assets/img/3.svg
Also this looks strange at this time:  `windDir "Ã\u0098NÃ\u0098"`

**Comment by Gr3q** [comment]
precipType is irrelevant (I know, it's weird) for the symbol, maybe the precip chance is under a certain % so it's not worth displaying. 

Focus on the symbols for hourly weather (`timeserie`) array and check if they match with the iconNames on the website. If they do, you just have to come up with an english title (or just give me the icons, whichever easier) for each code.

For windDir I guess is the browser can't decode the char `~` after every `Ã` char properly, you decide if the `~` char is important in your language

**Comment by jorgenqv** [comment]
Ok, here we go, hope I got it right... there might be some symbols missing. I also found something about codes at  DMI Open Data web site https://confluence.govcloud.dk/pages/viewpage.action?pageId=26476621
No idea if it is relevant here?

## List weather condtion symbol icons DMI
[dmi_dk_img.tar.gz](https://github.com/linuxmint/cinnamon-spices-applets/files/5937601/dmi_dk_img.tar.gz)

| Code / Img URL (symbol) | Condition Description | Comment |
| :--- | :--- | :---: |
| 1 / https://www.dmi.dk/fileadmin/assets/img/1.svg | Clear | Day time |
| 2 / https://www.dmi.dk/fileadmin/assets/img/2.svg | Partly cloudy | Day time |
| 3 / https://www.dmi.dk/fileadmin/assets/img/3.svg | Cloudy | Any time |
| 60 / https://www.dmi.dk/fileadmin/assets/img/60.svg | Slight rain | Any time |
| 63 / https://www.dmi.dk/fileadmin/assets/img/63.svg | Moderate rain | Any time |
| 70 / https://www.dmi.dk/fileadmin/assets/img/70.svg | Slight snow | Any time |
| 80 / https://www.dmi.dk/fileadmin/assets/img/80.svg | Rain showers | Day time |
| 101 / https://www.dmi.dk/fileadmin/assets/img/101.svg | Clear | Night time |
| 102 / https://www.dmi.dk/fileadmin/assets/img/102.svg | Partly cloundy | Night time |
| 103 / https://www.dmi.dk/fileadmin/assets/img/103.svg | Cloudy | Any time |
| 138 / https://www.dmi.dk/fileadmin/assets/img/138.svg | Blowing snow | Any time |
| 145 / https://www.dmi.dk/fileadmin/assets/img/145.svg | Foggy | Any time |
| 160 / https://www.dmi.dk/fileadmin/assets/img/160.svg | Rain | Any time |
| 163 / https://www.dmi.dk/fileadmin/assets/img/163.svg | Continuous rain | Any time |
| 168 / https://www.dmi.dk/fileadmin/assets/img/168.svg | Rain and snow | Any time |
| 169 / https://www.dmi.dk/fileadmin/assets/img/169.svg | Heavy rain and snow | Any time |
| 170 / https://www.dmi.dk/fileadmin/assets/img/170.svg | Slight snow | Any time |
| 173 / https://www.dmi.dk/fileadmin/assets/img/173.svg | Moderate snow | Any time |
| 180 / https://www.dmi.dk/fileadmin/assets/img/180.svg | Slight rain showers | Night time |
| 181 / https://www.dmi.dk/fileadmin/assets/img/181.svg | Moderate rain showers | Night time |
| 183 / https://www.dmi.dk/fileadmin/assets/img/183.svg | Slight mixed rain and snow | Night time |
| 184 / https://www.dmi.dk/fileadmin/assets/img/184.svg | Heavy mixed rain and snow | Night time |
| 185 / https://www.dmi.dk/fileadmin/assets/img/185.svg | Snow showers | Night time |
| 186 / https://www.dmi.dk/fileadmin/assets/img/186.svg | Heavy snow showers | Night time |
| 195 / https://www.dmi.dk/fileadmin/assets/img/195.svg | Thunderstorm with precipitation | Any time |


## Wind direction

| windDir (char-decode) | English (windDegree) |
| :--- | :---: |
| N    | North - N (350,360,010) |
| NNØ (NNÃ\u0098) | North North East - NNE (20,30) |
| NØ (NÃ\u0098)  | NorthEast - NE (40,50) |
| ØNØ (Ã\u0098NÃ\u0098)  | East North East - ENE (60,70) |
| Ø (Ã\u0098) | East - E (80,90,100) |
| ØSØ (Ã\u0098SÃ\u0098) | East South East - ESE (110,120) |
| SØ (SÃ\u0098) | South East - SE (130,140) |
| SSØ (SSÃ\u0098) | South South East - SSE (150,160) |
| S | South - S (170,180,190) |
| SSV | South South West - SSW (200,210) |
| SV | South West - SW (220,230) |
| VSV | West South West - WSW (240,250) |
| V | West W (260,270,280) |
| VNV | West North West - WNW (290,300) |
| NV | North West - NW (310,320) |
| NNV | North North West - NNW (330,340) |

**Comment by Gr3q** [comment]
Thanks, it's very useful, I'll start integrating it

**Comment by jorgenqv** [comment]
@Gr3q  Brilliant work integrating and fast too! :1st_place_medal: 
However, a bit inconsistent and somewhat confusing name with "Danish MI" and "Danish Meteorologist Institute"... 
Why not simply "DMI Denmark" like "MET Norway" is _not_ called "Norwegian Meteorological Institute" or "Norwegian MI"?
DMI is the more commonly used name https://translate.google.com/translate?sl=da&tl=en&u=https://www.dmi.dk/om-dmi/ 
Thank you! :)

**Comment by Gr3q** [comment]
Thanks, I wasn't sure what is the bast way to call it, I'll change it to DMI Denmark

**Comment by jorgenqv** [comment]
Missing the weather conditions "Slight snow" and "Moderate snow" found in danishMI.js used in the 3.0.2 pot file from 2021-02-06 19:08.

**Comment by Gr3q** [comment]
I generated one for he changes for the next release an that has it

**Comment by jorgenqv** [comment]
One not that important thing, but would be nice to have for DMI: When clicking on your current location in the top expanded applet, your web browser now redirects to https://www.dmi.dk. I think you can get data from the feed so you instead come directly to the location url, like from feed https://www.dmi.dk/NinJo2DmiDk/ninjo2dmidk?cmd=llj&lon=0.1084&lat=52.2231 you can get https://www.dmi.dk/lokation/show/GB/2653941/ that seems to work ( url / country / id ).

**Comment by Gr3q** [comment]
Yes, I can do that (and will)

**Comment by jorgenqv** [comment]
Just a big thanks for a very well done implementation of DMI for the Weather applet! I have been running it for more than a week now without any problems this far.
