### ISSUE TITLE
CustomApplicationsMenu@LLOBERA warning that it might cause cinnamon to crash

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#3529]
"version": "2.1",
    "author": "Nicolas01",
Cinnamon version Cinnamon 4.8.6
Linux mint 20.1 cinnamon 64bit
GPU: Intel UHD Graphics 620
Looking glass:
error t=2021-02-08T15:08:00Z 
[CustomApplicationsMenu@LLOBERA]: redeclaration of const _
[CustomApplicationsMenu@LLOBERA]: Error importing applet.js from CustomApplicationsMenu@LLOBERA

@Nicolas01 

Applet does no load.  No icon in panel.

**Comment by Nicolas01** [comment]
#3532

**Comment by ChooChooAl** [comment]
As long as you know.
Thanks.
