### ISSUE TITLE
cryptocoin@guantanamoe : applet is downloaded but doesn't appear in the installable applets

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3533]
```
 * Applet version 1.7
 * Cinnamon version 4.8.6
 * Mint 20.1
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
No file.
 * Snippet or attachment of ~/.xsession-errors

 ```
[.xsession-errors.tar.gz](https://github.com/linuxmint/cinnamon-spices-applets/files/5950123/default.xsession-errors.tar.gz)

**Notify author of applet**
@imDeprecated

**Issue**

I can download Crypto applet :

![Capture d’écran du 2021-02-09 09-58-50](https://user-images.githubusercontent.com/3955499/107341044-ce282500-6abe-11eb-88cb-d468fc420f40.png)

But after, when I want to add it on my desktop bar, I can't because it doesn't appear in the list :

![Capture d’écran du 2021-02-09 09-59-17](https://user-images.githubusercontent.com/3955499/107341170-ee57e400-6abe-11eb-9228-8f14637e0dbb.png)

**Comment by InfoLibre** [comment]
Is it since I updated the translation fr.po file ?

**Comment by NikoKrause** [comment]
I can't reproduce it. Have you tried deleting and reinstalling the applet?

**Comment by InfoLibre** [comment]
Yes, throught applets list and after, with Linux command. Same result.

**Comment by InfoLibre** [comment]
How could I help ? By typing a command or sending you a file ?

**Comment by NikoKrause** [comment]
Hey,

you were right. It is indeed a problem with the French translation.
Are you using `poedit` for translation or are you just using a normal text editor?

To create proper translation files you should get used to use poedit. Here are some instructions on how to get started with poedit: https://github.com/NikoKrause/CinnVIIStarkMenu/issues/19
You can ignore the first two sections and start with section "Create a translation for the first time with the application Poedit".

**Comment by InfoLibre** [comment]
I used this Gitlab editor. I will try with poedit.

**Comment by InfoLibre** [comment]
A new version or fr.po, edited with poedit. Sorry for the problem.

[fr.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/5957448/fr.po.zip)

**Comment by NikoKrause** [comment]
Looks good.
Can you create a pull request?

**Comment by InfoLibre** [comment]
I tried to delete and send a new file with a merge request. But I not sure what I did was OK.

**Comment by InfoLibre** [comment]
I made a new merge request.

**Comment by NikoKrause** [comment]
Merged. Update the applet in 5 minutes and it should appear again.

**Comment by InfoLibre** [comment]
It works, thank you very much.
