### ISSUE TITLE
weather@mockturtl : No space before % and no uppercase at the beginning of days

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3538]
```
 * Applet version 3.0.1
 * Cinnamon version 4.8.6
 * Mint 20.1
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@mockturtl

**Issue**

1) In the French version, the days don't have a uppercase letter at the beginning (there are any in the .po file but not on the screen)

2) A space is missing between the value and %

![Capture d’écran du 2021-02-10 09-05-21](https://user-images.githubusercontent.com/3955499/107482445-fd529b00-6b7f-11eb-9a7f-9e387ff6f9c7.png)

**Comment by Gr3q** [comment]
Hi, the humidity, I think it was always like this, but I can change it.

The days are coming from straight to Javascript that's why translations are not used. I'll add an extra check to capitalize them when french locale is used

**Comment by InfoLibre** [comment]
I don't know the exact rule but I think that there's always a space between a value and a unit. Perhaps it's different with humidity ?

**Comment by Gr3q** [comment]
No idea looking at weather websites (at least English ones) there is no space, but it looks ok, so I can add that as well

**Comment by InfoLibre** [comment]
I found this :
http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=4870

**Comment by Gr3q** [comment]
Javascript has a formatter based on language for percent, so I'll start using that. (UK is 5%, FR is 5 % for example)
