### ISSUE TITLE
cryptocoin@guantanamoe : the Symbol translation doesn't appear on the screen

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3544]
```
 * Applet version 1.7 (2021-02-10)
 * Cinnamon version 4.8.6
 * Mint 20.1
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
No file.
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@imDeprecated

**Issue**

Show currency - Option - Symbol : the translation that is in the french.po file doesn't appear on screen.

![Capture d’écran du 2021-02-10 14-13-32](https://user-images.githubusercontent.com/3955499/107514979-a9a97700-6baa-11eb-9707-5e2f22f02cda.png)

![Capture d’écran du 2021-02-10 14-13-45](https://user-images.githubusercontent.com/3955499/107514992-ae6e2b00-6baa-11eb-9a5b-5dd5338f2b9a.png)

**Comment by InfoLibre** [comment]
And if I choose **Nom (Name)** in the list, the name doesn't appear, it's the same result than with **Aucun (None)** :

![Capture d’écran du 2021-02-10 14-46-00](https://user-images.githubusercontent.com/3955499/107518079-e24b4f80-6bae-11eb-9446-fc6899be3994.png)

![Capture d’écran du 2021-02-10 14-47-16](https://user-images.githubusercontent.com/3955499/107518091-e5ded680-6bae-11eb-8a33-8430d2dca81c.png)

**Comment by NikoKrause** [comment]
Has this issue been solved?

**Comment by InfoLibre** [comment]
Yes, it's OK now.
