### ISSUE TITLE
cryptocoin@guantanamoe : some variables are missing in the .pot and .po files

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3545]
```
 * Applet version 1.7 (2021-02-10)
 * Cinnamon version 4.8.6
 * Mint 20.1

 ```

**Notify author of applet**
@imDeprecated

**Issue**

![Capture d’écran du 2021-02-10 14-19-14](https://user-images.githubusercontent.com/3955499/107516970-6f8da480-6bad-11eb-88ab-69ce39ca3ba9.png)

![Capture d’écran du 2021-02-10 14-20-42](https://user-images.githubusercontent.com/3955499/107516988-761c1c00-6bad-11eb-83ee-a648f942a48f.png)

![Capture d’écran du 2021-02-10 14-23-11](https://user-images.githubusercontent.com/3955499/107517010-7caa9380-6bad-11eb-977a-b97a31ebdc3b.png)

For **Graph Foregroung Color**, there's something similar in .pot file :

```
#. cryptocoin@guantanamoe->settings-schema.json->graph-color->description
msgid "The Graph Foreground Color"
msgstr ""
```

**Comment by NikoKrause** [comment]
I've updated the translation template.
For your info:
We do have a script `./cinnamon-spices-makepot` in this repository, which allows you to create and update the translation template. 
For example if you want to update the translation template for this cryptocoin applet, you use the following command in the root directory of this repository:
```
./cinnamon-spices-makepot cryptocoin@guantanamoe
```

This is also mentioned in the README of this repo, so you don't have to remember this command.

**Comment by InfoLibre** [comment]
```
david@ordinateur:~$ ~/Bureau/cinnamon-spices-makepot download-and-upload-speed@cardsurf
Spice with UUID »download-and-upload-speed@cardsurf« does not exist!
```

I will not waste more time with that. If the author want help with translation, the minimum is to provide updated .pot file.
