### ISSUE TITLE
weather@mockturtl : can't find some translations in the po files

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3548]
```
 * Applet version 3.0.1
 * Cinnamon version 4.8.6
 * Mint 20.1

 ```

**Notify author of applet**
@mockturtl

**Issue**

These texts are translated in French but I can't find them in the .po files. There are some translation mistakes in these texts :

![Capture d’écran du 2021-02-10 19-50-25](https://user-images.githubusercontent.com/3955499/107567988-b0ee7600-6be6-11eb-9d5f-b6eab3e0a9d4.png)

![Capture d’écran du 2021-02-10 19-50-59](https://user-images.githubusercontent.com/3955499/107568014-b77ced80-6be6-11eb-9749-be2db5ca2d7e.png)

**Comment by Gr3q** [comment]
These does not belong to the applet, these come with Cinnamon, and can be edited there

**Comment by InfoLibre** [comment]
Thank you, I will try to find where.

**Comment by InfoLibre** [comment]
I found where it is and prosed a new translation :

https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon/fr/503/+translate

https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon/fr/501/+translate
