### ISSUE TITLE
weather@mockturtl (cinnamon-weather)

### ISSUE THREAD

**Issue by Pjotr123** [linuxmint/cinnamon-spices-applets#3554]
* Applet version/Build date: Version 3.0.2 (2021-02-13 08:53:57)
 * Cinnamon version: 4.8.6
 * Distribution - Linux Mint 20.1 Ulyssa

**Notify author of applet**
@Gr3q 
@French77 

**Issue**
In a Dutch localized Weather, the tab buttons are invisible on a smallish laptop display. Possibly because of the length of one tab button name: "Eenheden, pictogrammen en toetsen". I need to enlarge the application window a bit, in order to make them visible after all.

**Steps to reproduce**
Right-click on the Weather icon on the panel - Instellen... (Dutch for: Configure...)

**Expected behaviour**
I expect to see the tab buttons straightaway, without having to enlarge the application window first.

**Other information**
See the attached screenshots: Screenshot-issue.png (with the issue, before enlarging the window) and Screenshot-normal.png (normal view, after enlarging the window).
![Screenshot-issue](https://user-images.githubusercontent.com/5963756/107846811-042f1700-6de7-11eb-9dd1-9e4eba64949e.png)
![Screenshot-normal](https://user-images.githubusercontent.com/5963756/107846836-3ccef080-6de7-11eb-8c9f-97c6ba282b0c.png)

**Comment by Gr3q** [comment]
Another problem with the settings window.

As a workaround I take suggestions for a shorter title for that tab because I couldn't come up with a better one

**Comment by Pjotr123** [comment]
No problem.... As workaround I've abbreviated the Dutch translation in the tab name. See my latest pull request.

**Comment by jorgenqv** [comment]
How about the 7 chars shorter "Other options" as an alternative to "Units, Icons and Keys"?

**Comment by French77** [comment]
>@Pjotr123 No problem.... As workaround I've abbreviated the Dutch translation in the tab name. See my latest pull request.
#### Sorry but this workaround (know you're doing your best to make it workable) does not look very neat,see screenshot below
![tab button](https://user-images.githubusercontent.com/3099270/107872536-43bf3700-6eab-11eb-8f08-3639fffc1f01.png)


#### This description as 23 characters,maybe just enough to make it fits better.
`Eenheden,tekens&toetsen`



>@jorgenqv How about the 7 chars shorter "Other options" as an alternative to "Units, Icons and Keys"?

#### Dutch translation might be `Andere keuze´s`
Well thought,description is less detailed 😉

**Comment by Pjotr123** [comment]
@French77 : You have a point there.... I'll change it to "Overige keuzes".

**Comment by French77** [comment]
@Pjotr123 : Even better 👍🏼

**Comment by Gr3q** [comment]
> How about the 7 chars shorter "Other options" as an alternative to "Units, Icons and Keys"?

I like that, I'll change it to Other options
