### ISSUE TITLE
weather@mockturtl : some french translations are now in english

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3555]
```
 * Applet version 3.0.2
 * Cinnamon version 4.8.6
 * Mint 20.1

 ```

**Notify author of applet**
@mockturtl

**Issue**

In the French version, these comments are in English (it was in French in the previous version :

![a](https://user-images.githubusercontent.com/3955499/107849001-7a884500-6df8-11eb-91c1-16c8e0523a56.png)

![Capture d’écran du 2021-02-14 10-55-16](https://user-images.githubusercontent.com/3955499/107873496-52115100-6eb3-11eb-9e82-fb794af81c05.png)

In the french version, a title and a part of the help is in English (it was in French in the previous version) and there was more comments in the previous version (they disappeared) :

![Capture d’écran du 2021-02-13 12-34-38](https://user-images.githubusercontent.com/3955499/107849057-dfdc3600-6df8-11eb-9eb4-94b9f8333c6b.png)

This comment appears twice :

![Capture d’écran du 2021-02-14 10-38-51](https://user-images.githubusercontent.com/3955499/107873517-72d9a680-6eb3-11eb-9c15-de90368fa724.png)

**Comment by jorgenqv** [comment]
There have been some changes in the original English texts (and more is coming), so the French translation needs to be updated.

**Comment by InfoLibre** [comment]
That's the problem with the .po files. The key for each entry is the English text and each time you modify it, all the other translations don't appear any more. Isn't it possible to use .po files with a number as key or something like that ?

**Comment by Gr3q** [comment]
What would happen if the original text is changed for a translation key? Still show the outdated translation? I don't see that as a better option

**Comment by InfoLibre** [comment]
It's better to show the outdated translation than nothing. But indeed, we will not know when the translation must be updated. Another alert mechanism is necessary in this case, doesn't it exist ?

**Comment by jorgenqv** [comment]
I am now aware of any alerts but there is almost always something changed in new versions? To check When donw I usually test my translation locally before committing it (see about .MO file below) if you mean when working with it? Here is how I do a translation most of the time (there is sure better ways of doing this?) posted in the Spices comment section five moths ago:

### Localization and Translation Guide
* Install package Poedit and choose a text editor that can compare files. 
  One good alternative is jEdit with the visual diff and merge plugin jDiffPlugin installed. 
* Go to the Github website and browse to: 
  cinnamon-spices-applets/weather@mockturtl/files/weather@mockturtl/po/
* Download your language .PO file and the latest .POT template file.
* Open the files side by side and compare, start working on your translation. Reuse previously contributed translations as much as possible and get familiar with the correct technical terms for things in your language.
* When done open your .PO file in Poedit and go over all your translations again checking things look correct, there is usually always typos and other mistakes.
* In Poedit click Verify and when everything is ok click on Save. This will generate a .MO file.
* Now it’s time to test you translation in action. Copy the generated .MO file to  ~/.local/share/locale/xx/LC_MESSAGES with the right file name and don’t forget to do a backup of the old weather@mockturtl.mo file.
* Restart your computer and check that everything is working and looks like you want.
* Finally edit the first rows of the .PO file, add the version number last on the row Project-Id-Version, add your name and email on the Last-Translator row, also creds and other useful information on the first hashtag marked rows is nice to have.

Please correct me if something can be done better :)

**Comment by Gr3q** [comment]
I just use [Poedit](https://poedit.net/) to edit translations, it can update a .po file from a .pot file, look it up in your package manager.

To test it, you can clone this repo, edit the .po files there then run `./cinnamon-spices-makepot weather@mockturtl --install` to install the edited translations for you. I always restart cinnamon after, I don't know if it's necessary.

There is no notification system as far as I know, but I'm more than happy to tag anyone who working on the my release PRs where I changed translations if they ask me. I'm happy to even hold off a release if they feel it's important to release the new translations at the same time.

**Comment by InfoLibre** [comment]
I tried to update the English texts in the French .po file, with the English text that is in the .pot file but I don't succeed and I'm afraid to make a mistake. Could you please update the fr.po file with the same English text than il the .pot file ? After, I could make the last French translations.

**Comment by Gr3q** [comment]
Yeah you can, but it's easier if you use a tool like poedit to do that

**Comment by InfoLibre** [comment]
Yes, I'm using poedit to update the french .po file but this file is buggy because it is not synchronized with the .pot file. Could you update the French .po file with the updated English text ?

**Comment by Gr3q** [comment]
Yes, I don't know off the top of my head but there is an option in one of the submenus called 'Update from .pot file'. Your can do it with that

**Comment by InfoLibre** [comment]
I did and nothing happens.

**Comment by Gr3q** [comment]
Assuming you updated your branch with the latest upstream master, it updated it. The changes should be highlighted.

**Comment by French77** [comment]
> Yes, I'm using poedit to update the french .po file but this file is buggy because the English text is not synchronized with the .pot file. Could you update the French .po file with the updated English text that is in the .pot file ?

#### Update from POT file syncronized <->fr.po
![Pot po bestanden](https://user-images.githubusercontent.com/3099270/107870498-16698d80-6e99-11eb-8ad9-b659f45f53e2.png)

**Comment by InfoLibre** [comment]
I did it ! Thank you for your help, I will propose a new translation .po file.

**Comment by jorgenqv** [comment]
Thank you for the hints on how to use poedit, will check it out :)

**Comment by NikoKrause** [comment]
This might help keeping track of new translatable strings:
https://github.com/linuxmint/cinnamon-spices-applets/issues/3588
