### ISSUE TITLE
weather@mockturtl : in French, a space must be put before ":"

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3556]
```
 * Applet version 3.0.2
 * Cinnamon version 4.8.6
 * Mint 20.1

 ```

**Notify author of applet**
@mockturtl

**Issue**

In French, a space must be put before each ":"

![Capture d’écran du 2021-02-13 12-15-54](https://user-images.githubusercontent.com/3955499/107849114-51b47f80-6df9-11eb-8fc9-0ca473734bd5.png)

**Comment by Gr3q** [comment]
I will put in an extra check

**Comment by InfoLibre** [comment]
Or ":" could be in .po file.

**Comment by Gr3q** [comment]
Its too generic on its own. It used to be included in the text, but that's not good practice either. 

I'll just make a function to localize it for now, because most places doesn't need the space and don't want to put it back to the translations.
