### ISSUE TITLE
weather@mockturtl : Only works with auto location

### ISSUE THREAD

**Issue by ByteEnable** [linuxmint/cinnamon-spices-applets#3560]
```
 * Version 3.0.1 (2021-02-03 00:01:21)
 * 4.8.6-1.fc33
 * Fedora 33
 * NVidia GTX1060 - 460.39
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
Applet bombs when switching between multiple cities as specified in saved locations.

**Steps to reproduce**
Enter location data for two cities.
Switch to manual location
Attempt to switch between the cities in the applet.

**Expected behaviour**
Ability to  switch between cities as specified in location.

**Other information**

**Comment by Gr3q** [comment]
Hi, can you tell me how you use that feature?

Are you using the arrow buttons to switch between locations?
Have you entered the locations completely manually or have you used the save location button?

I have to admit I neither validate what is entered in the locations section neither explain it how it works, so I'll add a tooltip or something how it works, also explain it here.

Every column for a location is  only used for displaying information about your location except the search entry field. The search entry field is the one to be placed into the location setting for validation, so you have to make sure it conforms what that field expects written in it's tooltip (for example you can just set it to {lat},{long})

This is for ensuring compatibility between saved locations via automatic location lookup and manual search entries (not the best way I admit, but I wanted to make sure when those are saved users know how they can find it again). This also make it counter-intuitive when adding a location completely manually (via the '+' button), what I might disable in the future.

**Comment by ByteEnable** [comment]
If you have two cities that are in location and then use the arrows from the popup to move to the next city it fails.

**Comment by Gr3q** [comment]
Ok,

What is the error message?

Also, if you are ok with it, could you share the locations with me via email or here? (for trying to reproduce the issue)

**Comment by ByteEnable** [comment]
I attached a pic of the dialog box.
![Screenshot from 2021-02-14 10-05-26](https://user-images.githubusercontent.com/5896865/107881965-b4cc1200-6ede-11eb-8125-6aa122b23b6b.png)

**Comment by Gr3q** [comment]
Yeah, ok I see what the problem is.

So I'm looking up location by the search entry to switch between. In short, they can be anything, but the have to be **unique**. If they are not unique, it will always switch to the first one with the same search entry.

To fix your problem, write something in for each of the search entries.

For the future, if I find an entry search entry when a location is added I will backfill it with lat,long
