### ISSUE TITLE
Feature request : Cinnamon applets automatic update

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3562]
**Issue**

Like in Linux Mint, could you add these options in the Cinnamon Applets parameters :
- manual or automatic update of installed applets
- in manual mode, showing or not an alert when an update is available for installed applets. In this case, it could be included in Mintreport : https://github.com/linuxmint/mintreport

**Comment by French77** [comment]
>   @InfoLibre   * in manual mode, showing or not an alert when an update is available for installed applets. 
####  Applet Spices Update warns you when installed Spices (applets, desklets, extensions, themes) require an update or new Spices are available. 
[https://cinnamon-spices.linuxmint.com/applets/view/309](url)

**Comment by InfoLibre** [comment]
I never had an alert ? Your link is dead, could you modify it ?

**Comment by French77** [comment]
> I never had an alert ?! Your link is dead, could you modify it ?

#### That´s weird the url is correct
Otherwise try to copy and paste the link into the url bar of your web browser

**Comment by InfoLibre** [comment]
I understand now, I must install this applet to have an alert, thank you.
