### ISSUE TITLE
"About" button doesn't work

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3563]
* Cinnamon version 4.8.6
 * Mint 20.1

**Issue**

Impossible to click on the About Button, it's grey :

![Capture d’écran du 2021-02-14 09-53-31](https://user-images.githubusercontent.com/3955499/107872446-c5629500-6eaa-11eb-8032-64d0a81a50a3.png)

**Comment by NikoKrause** [comment]
Select an applet first, which you want to know more "About".

**Comment by InfoLibre** [comment]
Aahhh, than you. I thought it was about the software that show the list of applets.
