### ISSUE TITLE
weather@mockturtl : a translation line is twice

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3567]
```
 * Applet version 3.0.2
 * Cinnamon version 4.8.6
 * Mint 20.1

 ```

**Notify author of applet**
@mockturtl

**Issue**

This translation line is twice :

![Capture d’écran du 2021-02-14 10-38-51](https://user-images.githubusercontent.com/3955499/107874414-e8e10c00-6eb9-11eb-845a-59f9169a3f42.png)

**Comment by Gr3q** [comment]
One of them is for the 3.0 version and the other one is for 3.8, I'll adjust one of them
