### ISSUE TITLE
cinnamon-spices-makepot can silently fail if any of the element name equals any of the special keys

### ISSUE THREAD

**Issue by Gr3q** [linuxmint/cinnamon-spices-applets#3592]
@NikoKrause 

**Steps:**
* Take a settings schema, name one of the elements (I only came across this issue with a `page` type element tbh, never tested it on anything else) `units` like this:
  ```
  "units":{
     "type":"page",
     "title":"Other options",
     "sections":[
         "units-section",
         "icons",
         "keybindings"
      ]
  },
  ```
* Run `cinnamon-spices-makepot`

**Expected behaviour**
All strings from the settings-schema should show up in the generated .pot file or script should crash/error out

**Actual behaviour**
Not all string are present (seemingly random, I guess in which order it was processed by the script)

**Comment by NikoKrause** [comment]
Do you got any errors?

I came across a similar issue a few minutes ago with this applet here: https://github.com/linuxmint/cinnamon-spices-applets/pull/3591/files#diff-f25090c79738e5e26de2386bc29e4a539629c0d03d59e7a2efbd6efe84df16d3L6 

I got the following error:
```
Scanning JavaScript files...
found 1 file(s)
Scanning for python files...
none found
Scanning metadata.json and settings-schema.json...
Traceback (most recent call last):
  File "/usr/bin/cinnamon-xlet-makepot", line 292, in <module>
    scan_xlet()
  File "/usr/bin/cinnamon-xlet-makepot", line 283, in scan_xlet
    scan_json(dir, pot_path)
  File "/usr/bin/cinnamon-xlet-makepot", line 57, in scan_json
    extract_settings_strings(data, rel_path.replace('/', '->'), pot_file)
  File "/usr/bin/cinnamon-xlet-makepot", line 74, in extract_settings_strings
    save_entry(data[key], comment, pot_file)
  File "/usr/bin/cinnamon-xlet-makepot", line 112, in save_entry
    if not msgid.strip():
AttributeError: 'collections.OrderedDict' object has no attribute 'strip'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_cinnamon-xlet-makepot.1000.crash'
Original exception was:
Traceback (most recent call last):
  File "/usr/bin/cinnamon-xlet-makepot", line 292, in <module>
    scan_xlet()
  File "/usr/bin/cinnamon-xlet-makepot", line 283, in scan_xlet
    scan_json(dir, pot_path)
  File "/usr/bin/cinnamon-xlet-makepot", line 57, in scan_json
    extract_settings_strings(data, rel_path.replace('/', '->'), pot_file)
  File "/usr/bin/cinnamon-xlet-makepot", line 74, in extract_settings_strings
    save_entry(data[key], comment, pot_file)
  File "/usr/bin/cinnamon-xlet-makepot", line 112, in save_entry
    if not msgid.strip():
AttributeError: 'collections.OrderedDict' object has no attribute 'strip'
```

Is it the same for you?

**Comment by Gr3q** [comment]
Nope, it won't crash, it will succeed as usual, but I can see some string were not included

**Comment by Gr3q** [comment]
Here is the relevant part of the diff what it generated:
```diff
-#. 3.8->settings-schema.json->units-page->title
-msgid "Other options"
-msgstr ""
-
-#. 3.8->settings-schema.json->info-section->title
-msgid "Help"
-msgstr ""
-
-#. 3.8->settings-schema.json->location-section->title
-msgid "Location settings"
-msgstr ""
-
-#. 3.8->settings-schema.json->location-store->title
-msgid "Saved Locations"
-msgstr ""
-
-#. 3.8->settings-schema.json->panel-options->title
-msgid "Panel (Taskbar)"
-msgstr ""
-
-#. 3.8->settings-schema.json->presentation->title
-msgid "Popup menu"
-msgstr ""
-
-#. 3.8->settings-schema.json->keybindings->title
-msgid "Keybindings"
-msgstr ""
-
-#. 3.8->settings-schema.json->more-info->title
-msgid "More about the Weather applet"
-msgstr ""
-
-#. 3.8->settings-schema.json->submit-issue->title
-msgid "Report an issue"
-msgstr ""
-
```

**Comment by NikoKrause** [comment]
Do you have an example to test with?

**Comment by Gr3q** [comment]
Change this line from `units-page` to `units`:
https://github.com/linuxmint/cinnamon-spices-applets/blob/34207a59b7aa0e336a09f7a36d5130331d34778c/weather%40mockturtl/files/weather%40mockturtl/3.8/settings-schema.json#L35

And generate the .pot

**Comment by NikoKrause** [comment]
Indeed. I can reproduce. The script completes without any error messages.

@collinss You might have a look?

**Comment by collinss** [comment]
It looks like the issues are due to "title" and "units" both being fields we translate, so it assumes that the values associated with those keys are strings that need to be translated.

As for a solution, I suppose it would be possible to modify the script to handle these edge cases, but doing so would require some non-trivial reworking, and would significantly increase the complexity of the relevant code (which would in turn make it more difficult to maintain, while simultaneously making it more likely to need maintenance). I would instead prefer to document those as reserved words that cannot be used for settings keys (along with "description" and "tooltip", which are also key words we scan for).

**Comment by Gr3q** [comment]
Is it the same if you'd make the script exit with an error message when it comes across this edge case?

I would be happy with that as well, anything but the current situation because it's incredibly easy not to notice this issue.

**Comment by collinss** [comment]
@Gr3q, @NikoKrause and I found a solution that works quite simply https://github.com/linuxmint/cinnamon/pull/9939. That fixes the script so it ignores those keywords if they aren't strings. It's not the most elegant solution, but it's probably the most reasonable, and it's certainly the simplest fix (just a 1-liner).

**Comment by Gr3q** [comment]
I'm good with that
