### ISSUE TITLE
weather@mockturtl Toggle Hourly Forecasts over days

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#3603]
@Gr3q

Here is an idea and feature request to make the expanded weather applet's access to hourly forecasts hopefully a little bit more intuitive and easier to use?

If there is a Hourly Forecast make the "Today" text a clickable button (that works exactly like the bottom arrow up), and could look like this:

![weather-exp-today](https://user-images.githubusercontent.com/5297223/108409767-e9193880-7226-11eb-83b3-99b124916b8e.png)

If the Hourly Forecast goes over to the next day in time, make "Tomorrow" text a button, and when clicked expands and shows the tomorrow hours something like this (maybe from 01 hrs and like anchor links on web pages?):

![weather-exp-tomorrow](https://user-images.githubusercontent.com/5297223/108409843-f8988180-7226-11eb-82fa-a96a856bdb11.png)

If the Hourly Forecast goes beyond tomorrow the next weekday gets a button and so on.

Is this interesting to have, and doable in a good way or at all?

**Comment by Gr3q** [comment]
In theory I can do this, but I would add the functionality if hourly weather is already expanded the buttons could react on hover

**Comment by jorgenqv** [comment]
Ah, great and sounds reasonable to add if expanded. Will rename this issues title to better reflect what it's about.

**Comment by jorgenqv** [comment]
Another idea related to hourly toggling: You could use the graphics file `time-3-symbolic.svg` in the icons directory next to the toggling button on the bottom bar, something like this?
![weather-exp-hourly-time-icon](https://user-images.githubusercontent.com/5297223/108481291-51543280-7298-11eb-8a1a-3fd5f356deee.png)

**Comment by Gr3q** [comment]
Here is how it looks:
https://user-images.githubusercontent.com/22377521/108593353-0525f280-736b-11eb-8655-8f1b3ab0d46d.mp4

Also, what is the reasoning to display 2 icons instead of one on the bar for toggling hourly weather?

**Comment by jorgenqv** [comment]
Looks excellent, thanks for the nice video! :)

My reasoning was that the toggle hourly button needs a indicator of some kind as a hint to what it does. When you introduced this feature the first time it took me a while to realize that you could toggle and open up the extra hourly part. The button is kind of small too. There is probably better ways than my 2 icon idea - it can be confusing and look strange and maybe even ugly to some... ;-)

**Comment by jorgenqv** [comment]
After some reflection scrap the two icon idea... Another thing you could do is to add some "padding" to the liked objects for all interactive stuff in the panel if possible? Just a few pixels. The reasoning for this is that I think they will appear more clear. Like if you add a little space around the toggle button when hoovering the contrast background color will be more noticeable perhaps?

**Comment by Gr3q** [comment]
I already did add some horizontal padding to make the toggle button and the location selectors bigger, does it need some more? It currently looks like this for me:

![image](https://user-images.githubusercontent.com/22377521/108607638-72607480-73b9-11eb-8c51-4debc2680abb.png)

Also I might remove the on-hover change, it's possible that it will be quite annoying for some people (it's noticeable even for me, it changes positions when I want to go for the scrollbar). I have to use it some more to come up with a solution what's not annoying

**Comment by jorgenqv** [comment]
Good! I think you can go for even more width and some height too? I believe that you could go for almost the panel height below? 

I would guess that the on-hover it's probably not important or useful to most people.

**Comment by jorgenqv** [comment]
After looking at the toggle button again, I think it's not better by adding height, width as shown in your latest screenshot looks good enough to me. One other thing that might be useful here is to expand what is clickable around the buttons, like you can click just beside a button and it works. Is this something that can be done? Goes for all clickable things in the applet. 
Amazing work this far!

**Comment by Gr3q** [comment]
Maybe the buttons are different for you. Which theme are you using?

Unfortunately I think if we want a bigger clickable area the highlighted are will grow as well, there is no ways around it

**Comment by jorgenqv** [comment]
Not really, only use the included standard mint-x and y themes. Will checkout theme possibilities, thank you!
