### ISSUE TITLE
download-and-upload-speed@cardsurf : texts missing in .pot file

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3610]
```
 * Applet version 1.6.5
 * Cinnamon version 4.8.6
 * Mint Cinnamon 20.1

 ```

**Notify author of applet**
@cardsurf

**Issue**

Some text is missing in .pot file, impossible to translate it :

![Capture d’écran du 2021-02-20 22-49-13](https://user-images.githubusercontent.com/3955499/108609554-e6f1de00-73ce-11eb-8e42-846bb97f83e3.png)

![Capture d’écran du 2021-02-20 22-49-27](https://user-images.githubusercontent.com/3955499/108609562-ed805580-73ce-11eb-99c5-72e2ed949134.png)

**Comment by NikoKrause** [comment]
You can update the translation template on your own, see https://github.com/linuxmint/cinnamon-spices-applets/issues/3545#issuecomment-784547994

**Comment by InfoLibre** [comment]
I know, I updated the .po with the .pot file. But I can't find the text in it, only the first line of the text :

![Capture d’écran du 2021-02-25 07-43-39](https://user-images.githubusercontent.com/3955499/109113972-518f7a80-773d-11eb-9ad0-f5007a8c184c.png)

**Comment by NikoKrause** [comment]
Did you update the pot file first?

**Comment by InfoLibre** [comment]
I downloaded the last version of the .pot file. But I don't modify the .pot file, only the developer can modify it, isn't it ?

**Comment by NikoKrause** [comment]
No, you can also update the pot file.
Not every developer makes aure that the pot file is up to date, so sometimes it's up to translators to update that as well. 

I've described how to update the pot file properly here:
https://github.com/linuxmint/cinnamon-spices-applets/issues/3545#issuecomment-784547994

It's pretty easy. Just running one command.

**Comment by InfoLibre** [comment]
```
david@ordinateur:~$ ~/Bureau/cinnamon-spices-makepot download-and-upload-speed@cardsurf
Spice with UUID »download-and-upload-speed@cardsurf« does not exist!
```

I will not waste more time with that. If the author want help with translation, the minimum is to provide updated .pot file.

**Comment by NikoKrause** [comment]
Ah, you've only downloaded the script? It only work, if you download the whole repository.
It's ok. I'll update it. If you see other pot files, which are not up to date, let me know.

**Comment by NikoKrause** [comment]
Ok, I've updated the pot file in https://github.com/linuxmint/cinnamon-spices-applets/pull/3640
