### ISSUE TITLE
[Cinnamenu@json] Unexpected search results

### ISSUE THREAD

**Issue by yrtimiD** [linuxmint/cinnamon-spices-applets#3643]
* Applet version: 4.12.7
 * Cinnamon 3.8.8
 * Distribution - Debian 10
 * ~/.cinnamon/glass.log - nothing useful
 * ~/.xsession-errors - empty

@fredcw, search behaviour feels weird

While searching "teams" highlights: 
<ins>Te</ins>legr<ins>am</ins>
<ins>Te</ins>rmin<ins>a</ins>l
...many other irrelevant results...
Microsoft T<ins>ea</ins>ms (this expected exact match is far-far after inexact splitted matches not even in the name but in description only.)

Typing "Microsoft" does brings Microsoft Teams to first result. (which is good)

Also, when Search Providers are enabled (with enabled Tracker provider) search stops after first 2 chars.

**Comment by fredcw** [comment]
@yrtimiD I can fix the "search stops after first 2 chars" bug but I can't improve the search algorithm because that would take a lot of effort and rewrite of the code in the 3.2 branch which is no longer being actively developed.

**Comment by yrtimiD** [comment]
thanks, works better!
