### ISSUE TITLE
weather@mockturtl Service Error

### ISSUE THREAD

**Issue by allanmcpherson** [linuxmint/cinnamon-spices-applets#3659]
Version 3.0.4 (2021-03-01 11:33:18)
Cinnamon 4.4.8
Linux Mint 19.3 Cinnamon
Intel Corporation HD Graphics 5500
[xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/6069836/xsession-errors.txt)

**Notify author of applet**
@mockturtl 

**Issue**
Beginning a few updates ago, the applet starting showing a Service Error message and will not load the weather. I'm using the WeatherBit API.

**Comment by Gr3q** [comment]
There is an error in my code (missing null check) what slowly exhausts your daily usage limit, I suggest use a different API until the next version.
