### ISSUE TITLE
no refreshment after moving manually a few times cursors bright or temp with Qredshift 1.5.4 (2021-02-24 22:37:53)

### ISSUE THREAD

**Issue by didier-linux** [linuxmint/cinnamon-spices-applets#3660]
* Applet version/Build date : 1.5.4 (2021-02-24 22:37:53)
 * Cinnamon version (cinnamon --version) : 4.8.6
 * Distribution  : LMDE 4 Debbie
 * Graphics hardware *and* driver used : Intel Corporation UHD Graphics 620
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

Dear Raphael Quintao
Thanks a lot for this great application, since I use it, I can't do without. I did an update of the latest version yesterday and observed a bug :
first method: changing manually "temp" or "bright" cursors with lclick on mouse, slip and release mouse does not change temp nor bright. After moving the cursor this way, temp or bright are change only after performing a "reload applet"

second method : but,  changing manually "temp" or "bright" cursors by left clicking directly on the cursor bar works to the condition the first method as not been tried before 

This bug occurs only since the version 1.5.4, and occurs either with day or night cursors. I did not change any options before and after the update. Thanks a lot to fix this error, I really need Qredshift for my eyes
best regards,
      Didier

**Comment by raphaelquintao** [comment]
Working on that as seen in: https://github.com/raphaelquintao/QRedshift/issues/31
Can close here.

**Comment by raphaelquintao** [comment]
@NikoKrause @brownsr
