### ISSUE TITLE
CinnVIIStarkMenu@NikoKrause: search function bug when write <

### ISSUE THREAD

**Issue by germe-fur** [linuxmint/cinnamon-spices-applets#3666]
CinnVIIStarkMenu@NikoKrause

```
 * Applet version/Build date Versión 1.31 (2021-02-17 14:40:30)
 * Cinnamon version Cinnamon 4.8.6
 * Distribution - Mint 20.1
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
when I write a < in the search bar of the applet, it starts to say "Search for results on the web" many, many times
(the same times you write "<")

**Steps to reproduce**
turn on any browser on the web search section, then touch the applet and write "<"

a "graphic" description:

```
        > - DuckDuckGo
        Search for results on the web
 logo   Search for results on the web
        Search for results on the web
        Search for results on the web
    Search for results on the web

2 results
<<<<
```

**Comment by NikoKrause** [comment]
Thanks for reporting. It should be fixed now.
