### ISSUE TITLE
[Lazy Contribution] French.pot

### ISSUE THREAD

**Issue by uapv1702675** [linuxmint/cinnamon-spices-applets#3670]
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-02-16 20:27+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

**# HERE I BEGIN TO TRANSLATE ~ INTO BAGUETLANG  ( A.K.A FRENCH )**
**# NO RIDICULOUS ACCENTS BUT QUIET CORRECT**

#: applet.js:79
msgid "Erreur : En attente, commande en cours d'execution !"
msgstr ""

#. metadata.json->name
msgid "Bash Sensors"
msgstr ""

#. metadata.json->description
msgid ""
"Ecrivez les commandes Bash dont les sorties doivent etre affichees par l'applet "
"not only!)"
msgstr ""

#. settings-schema.json->head->description
msgid "Parametres - Bash Sensors ( Ecrivez des commandes en Bash ! )"
msgstr ""

#. settings-schema.json->title1->description
msgid "Titre"
msgstr ""

#. settings-schema.json->title1->tooltip
msgid "Titre utilisé lors de l'affichage des notifications"
msgstr ""

#. settings-schema.json->refreshInterval->units
msgid "secondes"
msgstr ""

#. settings-schema.json->refreshInterval->description
msgid "Frequence de rafraichissement [ 0 pour ne pas rafraichir ]"
msgstr ""

#. settings-schema.json->shell->description
msgid "Shell"
msgstr ""

#. settings-schema.json->shell->tooltip
msgid "Shell a utiliser ('-c' va etre utilise pour appeller les commandes)"
msgstr ""

#. settings-schema.json->head1->description
msgid "Commandes"
msgstr ""

#. settings-schema.json->script1->description
msgid "Commande 1"
msgstr ""

#. settings-schema.json->script1->tooltip
msgid " Premiere sortie de commande  (utilisez \\f pour plus de lignes)"
msgstr ""

#. settings-schema.json->enableScript2->description
msgid "Mode Double-Commandes ( commande 2 active )"
msgstr ""

#. settings-schema.json->script2->description
msgid "Commande 2"
msgstr ""

#. settings-schema.json->script2->tooltip
msgid " Deuxieme sortie de commande (optional)"
msgstr ""

#. settings-schema.json->head2->description
msgid "Icone"
msgstr ""

#. settings-schema.json->dynamicIcon->description
msgid "Utilisation Dynamique de l'icone ( utilisez la sortie de la commande icon comme icone)"
msgstr ""

#. settings-schema.json->iconScript->description
msgid "Icone statique ou commande qui retourne le chemin complet d'une icone"
msgstr ""

#. settings-schema.json->iconScript->tooltip
msgid "La commande doit retourner une icone ( Vide  pas d'icone )"
msgstr ""

#. settings-schema.json->head3->description
msgid "Tooltip"
msgstr ""

#. settings-schema.json->dynamicTooltip->description
msgid "Info-bulle dynamique (utilisez la sortie de la commande tooltip comme info-bulle)"
msgstr ""

#. settings-schema.json->tooltipScript->description
msgid "Commande tooltip ou texte statique comme info-bulle"
msgstr ""

#. settings-schema.json->tooltipScript->tooltip
msgid "Info-bulle ( statique ou dynamique )"
msgstr ""

#. settings-schema.json->head4->description
msgid "Commande lors d'un clique droit"
msgstr ""

#. settings-schema.json->menuScript->description
msgid "Menu commande ( lors d'un clique droit )"
msgstr ""

#. settings-schema.json->menuScript->tooltip
msgid "Permet d'afficher beaucoup d'information dans le menu popup"
msgstr ""

#. settings-schema.json->menuScriptDisplay->description
msgid "Affichage de sortie du menu commande"
msgstr ""

#. settings-schema.json->head5->description
msgid "Commande au demarrage"
msgstr ""

#. settings-schema.json->startupScript->description
msgid "Commande lancee au demarrage"
msgstr ""

**Comment by uapv1702675** [comment]
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-02-16 20:27+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME EMAIL@ADDRESS\n"
"Language-Team: LANGUAGE LL@li.org\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

**# HERE I BEGIN TO TRANSLATE ~ INTO BAGUETLANG ( A.K.A FRENCH )
# NO RIDICULOUS ACCENTS BUT QUIET CORRECT
# SOME OUPSIES SO I COMMENT AGAIN**

#: applet.js:79
msgid "Erreur : En attente, commande en cours d'execution !"
msgstr ""

#. metadata.json->name
msgid "Bash Sensors"
msgstr ""

#. metadata.json->description
msgid ""
"Ecrivez les commandes Bash dont les sorties doivent etre affichees par l'applet "
"not only!)"
msgstr ""

#. settings-schema.json->head->description
msgid "Parametres - Bash Sensors ( Ecrivez des commandes en Bash ! )"
msgstr ""

#. settings-schema.json->title1->description
msgid "Titre"
msgstr ""

#. settings-schema.json->title1->tooltip
msgid "Titre utilisé lors de l'affichage des notifications"
msgstr ""

#. settings-schema.json->refreshInterval->units
msgid "secondes"
msgstr ""

#. settings-schema.json->refreshInterval->description
msgid "Frequence de rafraichissement [ 0 pour ne pas rafraichir ]"
msgstr ""

#. settings-schema.json->shell->description
msgid "Shell"
msgstr ""

#. settings-schema.json->shell->tooltip
msgid "Shell a utiliser ('-c' va etre utilise pour appeller les commandes)"
msgstr ""

#. settings-schema.json->head1->description
msgid "Commandes"
msgstr ""

#. settings-schema.json->script1->description
msgid "Commande 1"
msgstr ""

#. settings-schema.json->script1->tooltip
msgid " Premiere sortie de commande (utilisez \f pour plus de lignes)"
msgstr ""

#. settings-schema.json->enableScript2->description
msgid "Mode Double-Commandes ( commande 2 active )"
msgstr ""

#. settings-schema.json->script2->description
msgid "Commande 2"
msgstr ""

#. settings-schema.json->script2->tooltip
msgid " Deuxieme sortie de commande (optional)"
msgstr ""

#. settings-schema.json->head2->description
msgid "Icone"
msgstr ""

#. settings-schema.json->dynamicIcon->description
msgid "Utilisation Dynamique de l'icone ( utilisez la sortie de la commande icon comme icone)"
msgstr ""

#. settings-schema.json->iconScript->description
msgid "Icone statique ou commande qui retourne le chemin complet d'une icone"
msgstr ""

#. settings-schema.json->iconScript->tooltip
msgid "La commande doit retourner une icone ( Vide pas d'icone )"
msgstr ""

#. settings-schema.json->head3->description
msgid "Tooltip"
msgstr ""

#. settings-schema.json->dynamicTooltip->description
msgid "Info-bulle dynamique ( Utilisez la sortie de la commande en guise d'info-bulle )"
msgstr ""

#. settings-schema.json->tooltipScript->description
msgid "Commande ou texte statique en guise d'info-bulle"
msgstr ""

#. settings-schema.json->tooltipScript->tooltip
msgid "Info-bulle ( statique ou dynamique )"
msgstr ""

#. settings-schema.json->head4->description
msgid "Commande lors d'un clique droit"
msgstr ""

#. settings-schema.json->menuScript->description
msgid "Menu commande ( lors d'un clique droit )"
msgstr ""

#. settings-schema.json->menuScript->tooltip
msgid "Permet d'afficher beaucoup d'information dans le menu popup"
msgstr ""

#. settings-schema.json->menuScriptDisplay->description
msgid "Affichage de sortie de la commande de menu " #NOT SURE I OF MY UNDERSTANDING 
msgstr ""

#. settings-schema.json->head5->description
msgid "Commande au demarrage"
msgstr ""

#. settings-schema.json->startupScript->description
msgid "Commande lancee au demarrage"
msgstr ""

**Comment by NikoKrause** [comment]
Lazy review

**Comment by uapv1702675** [comment]
I didn't expect you to stop to laze bro, I made this translation bc I like this applet but has 0 time to do it properly. It's up to you to judge what you are ready to do to improve this magnificent applet, like I did ;) 

with love, I wish you a good day :*

**Comment by NikoKrause** [comment]
If you want to help to improve this applet, install `poedit` and do the translation with this application by opening the `.pot` with poedit. You can then zip the `fr.po` and upload it here. 

Right now the translation file you posted above has so many errors that it is unusable.

**Comment by Gr3q** [comment]
@uapv1702675  I'll give you some explanation what is wrong with this:

First, the formalities:
* didn't specify which applet you did translations for
* code is better suited to be put in code blocks ```like this```
* Making translations is not an issue, a PR is better suited for it

Now, the show-stoppers:
* you edited the .pot file directly instead of updating the fr.po file with it (manually or with Poedit), which makes these translations unusable
* you overwritten the msgids with the french translations, which makes your translations completely unusable `msgid` field is for the original text, `msgstr` field is for the translations

What you should've done:
* Ask how to contribute to translations

What you should've done exactly:
* Obtain the .pot file and the fr.po file for the applet you want to translate (either by fork this repository and clone your fork or download this repository)
* (If you are using your own fork now is the time to create a separate branch)
* Update the fr.po from the .pot file (Poedit could make this a 1-second-job)
* If Create a Pull Request or upload the changed fr.po here

**Comment by uapv1702675** [comment]
> If you want to help to improve this applet, install `poedit` and do the translation with this application by opening the `.pot` with poedit. You can then zip the `fr.po` and upload it here.
> 
> Right now the translation file you posted above has so many errors that it is unusable.

Ok, thx, i'll try do to that properly once I'm less late on my stuff. I was quiet aware about that contribution has "some many" errors but unusable ? http://image.noelshack.com/fichiers/2017/45/1/1509995704-risitas-gratte-tete.png

**Comment by NikoKrause** [comment]
Yes it's unusable, because the translation belongs into `msgstr`. You have just overwritten the original texts, i.e. the `msgid`. Using poedit is the easiest way to do translations properly.

**Comment by uapv1702675** [comment]
You know exactly what's the prob is, but it's unusable. http://image.noelshack.com/fichiers/2020/43/5/1603447274-jesus-fondu-altieri.png

**Comment by uapv1702675** [comment]
Ok so guys, i tryed to do it properly, here is the result ( the .pot used, the .mo and the .po) ! Thanks for explanations about how to contribute. I was less painful than expected.

Kiss, have a nice day 

[BASH_SENSORS_FRENCH.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/6095451/BASH_SENSORS_FRENCH.zip)

**Comment by NikoKrause** [comment]
Thanks for the translation, I've uploaded your `fr.po` file.
If you update the applet, the applet should be translated now.
