### ISSUE TITLE
Does not open Version 3.0.5 (2021-03-03 00:29:25)

### ISSUE THREAD

**Issue by dismasop32** [linuxmint/cinnamon-spices-applets#3682]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**

Does not open.  Tried uninstalling and reinstalling.  Stuck on loading icon.

**Steps to reproduce**

**Expected behaviour**

**Other information**

Version 3.0.5 (2021-03-03 00:29:25)

**Comment by NikoKrause** [comment]
Can you tell us, which applet?

**Comment by dismasop32** [comment]
Sorry, it was Weather.

I tried using Yahoo for source, it told me to install a python3 package,
and then it worked.

**Comment by Gr3q** [comment]
Can I assume that this issue is resolved?

**Comment by dismasop32** [comment]
Close, please
