### ISSUE TITLE
weather@mockturtl Temperature unit features

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#3694]
**Notify author and original request submitter**
@Gr3q
@spsf64
Summary and some more ideas for Temperature unit feature idea from the comment section on the Spices website.

**Feature request**
Add the option to display both temperature units (Fahrenheit and Celsius) at the same time in the weather applet.
Reason for the request is that it can to be useful for people moving between places that use different temperature units
with the purpose of learning and understanding temperature unit differences.

**List of ideas and requirement thoughts**
- The option could be placed in Configure under Other options / Units / Temperature unit.
- The name of the option could be "Show Fahrenheit and Celsius at the same time" and the default setting is false.
- If enabled both temperatures are shown like 25°C (77°F) in applet Panel and Popup current temperature on the top right. 
- If the option is enabled to true and Temperature unit is Fahrenheit the shown order should be 77°F (25°C).
- Another way to go is to use linked toggling as used in popup on Hourly, i.e. when clicking on any F och C unit marks in the applet the value to the left of the mark changes between Fahrenheit and Celsius on every click.

**Expected behavior**
When enabled you get the possibility to see Fahrenheit Celsius units more directly. 

**Other information**
- Unit change shortcut idea: Once upon a time many years ago the applet had a little Gear icon top right in the popup to access Configure (see screenshot on the Spices website). One idea is to reintroduce this icon again but this time make it a direct shortcut to the Configure "Other options" Tab (if possible?), this way you save 2 clicks and can be seen as a little bit more intuitive.
- Another minor thing related to temperature: Move "Show temperature Russian style" to Unit section under "Temperature unit", and add to description or tool-tip: (i.e. −2…+3 °C). The reason for this is that it's shown in both popup and panel, the parenthesis text explains what it does, and it's about temperature and therefor perhaps better placed under Units/Temperature).

**Comment by Gr3q** [comment]
I have to choose a format, options:
Only display alternative unit's temperature
* 0 (32) °C 
* 32 (0) °F
* 0 (32) /  0 (32) °C 
* 32 (0) °F / 32 (0) °F

Show everything one after the other
* 0 °C (32 °F) 
* 32 °F (0 °C)
* 0 °C (32 °F) / 0 °C (32 °F)
* 32 °F (0 °C) / 32 °F (0 °C)

Show temperatures and units grouped
* 0 (32) °C (°F)
* 32 (0) °F (°C)
* 0 (32) / 0 (32) °C (°F)
* 32 (0) / 32 (0) °F (°C)

I prefer the first one, because it is an opt-in feature, alternatively the last one.
@spsf64 what's your opinion on the format because primarily you will be using this feature

**Comment by spsf64** [comment]
@Gr3q sorry for the late reply, and thanks for the feedback!
I think the best layout would be the second you listed, like:
0 °C (32 °F) when primary is °C
32 °F (0 °C) when primary is °F


@jorgenqv thanks for bringing this issue here from the comments!

**Comment by Gr3q** [comment]
@spsf64 Do you prefer the same format (0 °C (32 °F) / 0 °C (32 °F)) for the forecast temperature range in the daily forecasts?

**Comment by spsf64** [comment]
> @spsf64 Do you prefer the same format (0 °C (32 °F) / 0 °C (32 °F)) for the forecast temperature range in the daily forecasts?

Well, never thought about the forecast; Yeah, maybe the same format...
Wouldn't it become too cluttered? If so, just keep it with the primary unit.
Thanks!
