### ISSUE TITLE
scripts@paucapo.com

### ISSUE THREAD

**Issue by muzena** [linuxmint/cinnamon-spices-applets#37]
@Odyseus  @NikoKrause 
Can some fix problem with this applet.
It won't show script list, It only works when I manually replace in applet.js file, in line 32
"/.scripts-applet" with "/.local/share/nemo/scripts/"
Then I try to change in settings Scripts directory, some other directory and back to  "/.local/share/nemo/scripts/" directory and then don't work again.

**Comment by NikoKrause** [comment]
@paucapo

**Comment by Odyseus** [comment]
Hello, everybody.

@NikoKrause & anyone that is willing to fix this applet.

The problem resides in the **filechooser** setting. In Cinnamon 3.2.x this setting type returns a file URI, not a path like it used to. The applet's code always expects a path.

I use a simple fix like the following:
```javascript
if (/^file:\/\//.test(path))
    path = path.substr(7);
```

**Comment by muzena** [comment]
@NikoKrause 
I try to generate scripts@paucapo.com.pot file and I get this error:

$ cinnamon-json-makepot --js scripts@paucapo.com.pot

msgid = msgid.encode("ascii")
AttributeError: 'dict' object has no attribute 'encode'

**Comment by Odyseus** [comment]
Hello, @muzena.

You are not executing that command from inside the applet folder. And you don't need to specify the .pot extension (not an error, just not needed).

**Comment by muzena** [comment]
@Odyseus 
mint@mint-asus ~/.local/share/cinnamon/applets/scripts@paucapo.com $ cinnamon-json-makepot --js scripts@paucapo.com
xgettext (GNU gettext-tools) 0.19.7
Copyright (C) 1995-1998, 2000-2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.
 
Running xgettext on JavaScript files...
Scanning metadata.json and settings-schema.json...
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-json-makepot/cinnamon-json-makepot.py", line 270, in <module>
    Main()
  File "/usr/share/cinnamon/cinnamon-json-makepot/cinnamon-json-makepot.py", line 143, in __init__
    self.scan_dirs()
  File "/usr/share/cinnamon/cinnamon-json-makepot/cinnamon-json-makepot.py", line 208, in scan_dirs
    self.extract_strings(data)
  File "/usr/share/cinnamon/cinnamon-json-makepot/cinnamon-json-makepot.py", line 222, in extract_strings
    self.save_entry(data[key], comment)
  File "/usr/share/cinnamon/cinnamon-json-makepot/cinnamon-json-makepot.py", line 252, in save_entry
    msgid = msgid.encode("ascii")
AttributeError: 'dict' object has no attribute 'encode'

**Comment by Odyseus** [comment]
@muzena.

Mmmm. I don't know what to tell you then. I have only seen that error when I accidentally run that command outside an applet's directory.

I can generate the .pot file for this applet without any problems.

Try without using the **--js** argument. The applet.js file doesn't have any string to extract anyway.

[scripts@paucapo.com.pot.tar.gz](https://github.com/linuxmint/cinnamon-spices-applets/files/743467/scripts.paucapo.com.pot.tar.gz)

**Comment by muzena** [comment]
@Odyseus

Same error.

applet.js have 3 strings only missing brackets
Line 115 and 120:
      let open = new PopupMenu.PopupMenuItem("_(Open scripts folder"));
      let update = new PopupMenu.PopupMenuItem(_("Update menu"));

**Comment by Odyseus** [comment]
@muzena.

I recommend you to create a repository on your GitHub account so you can work more freely.

I missed the **_("Scripts")** line on the applet.js file.

Lines 115 and 120 should be as follow:
```javascript
let open = new PopupMenu.PopupMenuItem(_("Open scripts folder"));
```
```javascript
let update = new PopupMenu.PopupMenuItem(_("Update menu"));
```

And since you are adding a custom translation, you should also add the following constant and function:

```javascript
const Gettext = imports.gettext;

function _(aStr) {
    let customTrans = Gettext.dgettext(UUDI, aStr);

    if (customTrans !== aStr)
        return customTrans;

    return Gettext.gettext(aStr);
}

```

**Comment by muzena** [comment]
@Odyseus 
Same error again, but i forget mention that pot file was created with only these 3 strings from applet.js file.

**Comment by Odyseus** [comment]
@muzena.

I don't know why are you having that error. I tried it in 3 of my Cinnamon systems (2.8.8, 3.0.7 and 3.2.x) and the **cinnamon-json-makepot** command works on this and any other applet.

You can use this file in the meantime. [scripts@paucapo.com.pot.tar.gz](https://github.com/linuxmint/cinnamon-spices-applets/files/743631/scripts.paucapo.com.pot.tar.gz)

**Comment by NikoKrause** [comment]
Have you tried with other applets?

**Comment by muzena** [comment]
@NikoKrause 
Only on this applet, I try a few @Odyseus applet, on them work.
And I try on clean Install of Mint 18 in Virtualbox, same error.

**Comment by NikoKrause** [comment]
I have to try it later.

Is his a clean version or have you modified the applet?
Try downloading the ZIP file on Cinnamon Spices Website (clicking the Download button),
unzip it and try in the unziped folder.
`cinnamon-json-makepot --js test`
This should create a test.pot file.

**Comment by muzena** [comment]
No I haven't modify anything.
Same thing from  ZIP file on Cinnamon Spices Website.
Maybe is missing some package dependencies on my system?

**Comment by NikoKrause** [comment]
I can reproduce the error with makepot.

**Comment by NikoKrause** [comment]
@muzena 
I found the reason, why this error happened.
This PR https://github.com/linuxmint/cinnamon-spices-applets/pull/62 fixes it.
Can you try and confirm?

**Comment by muzena** [comment]
@NikoKrause 
Thanks, now it works!

**Comment by muzena** [comment]
@NikoKrause 
Can you tell me why these 3 strings are not translated from applet.js only from settings-schema.json are  translated?
I test it on this way #https://github.com/NikoKrause/CinnVIIStarkMenu/issues/19

**Comment by NikoKrause** [comment]
Which 3 strings are not translated?

**Comment by muzena** [comment]
@NikoKrause 
         this.set_applet_tooltip(_("Scripts"));
         let open = new PopupMenu.PopupMenuItem(_("Open scripts folder"));
         let update = new PopupMenu.PopupMenuItem(_("Update menu"));

**Comment by NikoKrause** [comment]
I forgot to mention that you have to restart Cinnamon after `cinnamon-json-makepot -i`

If it doesn't work, can you upload your files. Just zip them and then drag&drop the zip here.

**Comment by muzena** [comment]
Thanks!
After restarting Cinnamon works!
