### ISSUE TITLE
gpaste-reloaded@feuerfuchs.eu: Applet can't be loaded

### ISSUE THREAD

**Issue by Ilis** [linuxmint/cinnamon-spices-applets#370]
@feuerfuchs.eu

Error adding applet to panel

Error message:
Applet load problem, it will be removed (or something like that)

glass.log
==8<====
error t=2017-04-20T17:09:17.433Z Requiring GPaste, version none: Typelib file for namespace 'GPaste' (any version) not found
trace t=2017-04-20T17:09:17.433Z 
<----------------
@/home/ilis/.local/share/cinnamon/applets/gpaste-reloaded@feuerfuchs.eu/applet.js:13
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:155
Extension@/usr/share/cinnamon/js/ui/extension.js:116
loadExtension@/usr/share/cinnamon/js/ui/extension.js:449
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:235
---------------->
error t=2017-04-20T17:09:17.434Z [Applet "gpaste-reloaded@feuerfuchs.eu"]: Error importing applet.js from gpaste-reloaded@feuerfuchs.eu
error t=2017-04-20T17:09:17.434Z Could not load applet gpaste-reloaded@feuerfuchs.eu
==8<====

**Comment by Ilis** [comment]
After installing
--
gpaste
libgpaste4
gir1.2-gpaste-4.0
--
I tried add applet again, then Cinnamon crashed.
After restarting Cinnamon, applet was added :)

**Comment by NikoKrause** [comment]
So when you problem is solved now, please close the issue.

**Comment by Ilis** [comment]
@NikoKrause 

Sorry, the problem is: user don't get instruction what to do when he get error.

Installing some packages allow user to add applet onto panel, but don't solve problem user has no idea why applet won't be added.

**Comment by NikoKrause** [comment]
Yeah. You are right. The applet should be prevented from crashing and instead give some Information what needs to be installed.

**Comment by NikoKrause** [comment]
@feuerfuchs

**Comment by Feuerfuchs** [comment]
I agree, crashing is not a good way to signalize somethings wrong. I'll implement a more robust solution.
