### ISSUE TITLE
mylauncher@markbokil.com, updates overwrite settings.

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#3702]
```
 * Applet version/Build date Updated on 2021-02-16 13:45:08
 * Cinnamon version Cinnamon 4.8.6
 * Distribution - Mint20 Kernel: 5.4.0-67-generic x86_64 bits: 64
 * Graphics hardware Intel UHD Graphics 620 driver: i915 v: kernel
  ```
@markbokil

**Issue**
Update to the applet overwrites 'mylauncher.properties' file and you lose all your custom menu settings.
**Steps to reproduce**
Just wait for an update
**Expected behaviour**
Hopefully there should be some way to prevent the overwriting if this one file exists.
**Other information**
Luckily I have a backup.

**Comment by psyray** [comment]
Yes stop overwrite this file, or if you could not, backup the replaced file

**Comment by psyray** [comment]
Same problem again.
@markbokil
Could you fix this ?
Thanks

**Comment by Centurix** [comment]
Issue resolved with: https://github.com/linuxmint/cinnamon-spices-applets/pull/5932
