### ISSUE TITLE
How do I submit/propose a change to someone's applet (MessagingMenuV3@blub)?

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/cinnamon-spices-applets#3720]
**Notify author of applet**
@blub

**Issue**
I've fixed some of the issues with Messaging Menu V3 not recognizing certain messaging applications (such as Geary, Evolution, Discord, Zoom, Caprine, etc.). However, I'm not sure how to submit the change for approval. If someone could help me out with that, I'd appreciate it! Thank you!

**Comment by icarter09** [comment]
@mfreeman72 create a PR and tag the author of the applet is all.

**Comment by mfreeman72** [comment]
So, basically what I just did? :)

**Comment by icarter09** [comment]
Yes but as a PR with your changes.

**Comment by mfreeman72** [comment]
Ok. Got it. I'll close this, and restart as a proper PR (at least I hope I do it right!). Thank you!
