### ISSUE TITLE
MessagingMenuV3@blub: Update Application Support, added support for unsupported and updated applications

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/cinnamon-spices-applets#3721]
```
 * Applet version/Build date: 2021-04-04 11:07:04
 * Cinnamon version: 4.8.6
 * Distribution: Linux Mint 20.1

 ```

**Notify author of applet**
@blub

**Issue**
Current version of Messaging Menu V3 is missing support for newer messaging applications, and older applications that used to be supported no longer show up in the menu (specifically Geary and Evolution).

I am submitting this PR as an update to the applet.js file so that the applet recognizes these applications. In the "/*global values*/" section of the file, the compatible_Apps, compatible_Emails, compose_Commands, and contact_Commands variable lines should be changed to the following:

`let compatible_Apps = ["caprine", "discord", "skype", "skypeforlinux", "teams", "pidgin", "empathy", "xchat", "kmess", "gajim", "emesene", "qutim", "amsn", "openfetion", "gwibber", "qwit", "turpial", "birdie", "pino", "slack", "fbmessenger", "fbmessengerdesktop", "telegramdesktop", "whatsdesk", "whatsie", "Zoom", "org.gnome.Contacts"];`
`let compatible_Emails = ["evolution", "org.gnome.Evolution", "postler", "geary", "org.gnome.Geary", "thunderbird", "KMail2", "claws-mail"];`
`let compose_Commands = ["evolution mailto:", "evolution mailto:", "postler mailto:", "geary mailto:", "geary mailto:", "thunderbird -compose", "kmail -compose", "claws-mail --compose"];`
`let contact_Commands = ["evolution -c contacts", "evolution -c contacts", null, null, null, "thunderbird -addressbook", null, null];`

I've kept in the older geary and evolution ID's as well as the newer org.gnome.* versions in case this is used on older systems that might still support the older applications.

This is my first PR. Hopefully I did this correctly. If anything needs to change, let me know, and I will change it.

**Comment by icarter09** [comment]
@mfreeman72 you created an "Issue". You need to select "Pull requests" , then create a new pull request. The file you changed needs to be included in that pull request.

**Comment by mfreeman72** [comment]
I had a feeling I did something wrong. Ok. I'll try again. Sorry.

**Comment by NikoKrause** [comment]
If you're not familiar with git and you don't want to struggle to learn it right now, there's an easy solution. Since your change seems to involve only one file, your easiest solution would be to edit the file in your browser.

https://github.com/linuxmint/cinnamon-spices-applets/blob/master/MessagingMenuV3%40blub/files/MessagingMenuV3%40blub/applet.js

I think it's this file. There's a pencil icon, which let's you edit the file in the browser and also should show you a button create a pullrequest afterwards.

**Comment by mfreeman72** [comment]
@NikoKrause Thank you! That's better than taking a github crash course. :) I think (hope) I submitted the PR properly this time.

**Comment by NikoKrause** [comment]
You did the changes to the applet.js file in your branch mfreeman72-patch-1 now you need to create a PR.

Go to your branch here:
https://github.com/mfreeman72/cinnamon-spices-applets/commits/mfreeman72-patch-1

Then there should be a button "Pull request" as described here https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request#creating-the-pull-request. 

You need to choose linuxmint/master as "base" and "mfreeman72-patch-1" as compare. 

If you've done that, the pull request should appear in this list here:  https://github.com/linuxmint/cinnamon-spices-applets/pulls

Then we are able to merge it.

**Comment by mfreeman72** [comment]
I did that. Did it not go through?

**Comment by NikoKrause** [comment]
No

**Comment by mfreeman72** [comment]
Ok. I just tried again.

**Comment by NikoKrause** [comment]
Merged

**Comment by mfreeman72** [comment]
Awesome. Thank you for your help! This was a bit more of a learning curve that I expected, I guess. I apologize for taking so much of your time.

**Comment by NikoKrause** [comment]
You're welcome. I'm happy to help people, who want to contribute and are willing to learn as you are. It's not all about the end result, but also about how you get there. I've got help when I started with my first contribution and now I'm glad I was able to help others. :)
