### ISSUE TITLE
weather@mockturtl : Bad translation ?

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#3733]
```
 * weather@mockturtl
 * Cinnamon 4.8.6
 * Mint 20.1

 ```

**Notify author of applet**
@Gr3q

**Issue**

In the .pot file, are there errors with the use of "what" word instead of "that" ?

Exemples :

```
Please Make sure you
entered the API key what you have from Climacell
```
->
```
Please Make sure you
entered the API key what you have from Climacell
```

```
Saves location information to file, so you can switch between them with buttons in the applet (what will appear if you have more than one).
```
->
```
Saves location information to file, so you can switch between them with buttons in the applet (that will appear if you have more than one).
```

```
Maximum number of days what can be displayed, maximum rows and columns setting in the Presentation tab will affect the final number.
```
->

```
Maximum number of days that can be displayed, maximum rows and columns setting in the Presentation tab will affect the final number.
```

**Comment by Gr3q** [comment]
Hi I'm Attila and I have a grammar problem. I use `what` excessively and inappropriately in writing.

It's funny because its true, I'll fix it in the next update

Thanks

**Comment by jorgenqv** [comment]
Found one tiny w to change to t in: 3.0/darkSky.js:238 and 3.8/providers/darkSky.js:166 in the Gr3q:weather-dev branch.

And it's interesting that I or any of the other translators looking at the pot-template so many times didn't see this at all for such many releases... Well, I still am the king of random typos :-)
