### ISSUE TITLE
weather@mockturtl not displaying Met Office UK data

### ISSUE THREAD

**Issue by julesbl** [linuxmint/cinnamon-spices-applets#3738]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
Applet just displays error. If I change to OpenWeatherMap starts working again.
Was working until recently so presumably it is something changed with the Met Office api.

**Steps to reproduce**
Set the data service to Met Office UK (UK only)
My Location 50.837829469127726, -0.1414968489898248

**Expected behaviour**
Should display weather for the UK, in this case Brighton

**Other information**

**Comment by Gr3q** [comment]
Your nearest observation site completely stopped reporting information, seems to be a rare issue.

Will be fixed in the next release
