### ISSUE TITLE
multicore-sys-monitor@ccadeptic23 Preferences does not open

### ISSUE THREAD

**Issue by buster666** [linuxmint/cinnamon-spices-applets#3765]
* Applet version/Build date  1.8.91 (2021-04-04 20:07:04)
 * Cinnamon version 4.8.6
 * Distribution - EndeavourOS base: Arch Linux 
 * Graphics hardware *and* driver used - AMD Navi 10 [Radeon RX 5700] driver: loaded: amdgpu,ati
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@ccadeptic23
@jaszhix
@brownsr

**Issue**
The preferences window does not open at all


**Steps to reproduce**
Rightclick on the applet and click on Preferences

**Expected behaviour**
Show the preferences window

**Other information**
In ~/.xsession-errors I can see multiple times the following entry:
`(cinnamon:8072): Cjs-CRITICAL **: 12:34:45.550: JS ERROR: TypeError: colorsList[datapointnum] is undefined
paint@/home/skl/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/4.0/Graphs.js:297:15
onGraphRepaint@/home/skl/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/4.0/applet.js:372:35
__init/<@/home/skl/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/4.0/applet.js:208:54`

**Comment by fredcw** [comment]
I'm on manjaro but I can't reproduce this bug. Have you tried removing the applet and reinstalling? Also, just to make sure that the prefs file isn't corrupted and causing the problem, try deleting the file `~/.cinnamon/configs/multicore-sys-monitor@ccadeptic23/prefs.json` before you reinstall.
