### ISSUE TITLE
weather@mockturtl - Hourly Forecast toggle view has different height each time, increasing to eventually go off top of screen.

### ISSUE THREAD

**Issue by GalacticSun** [linuxmint/cinnamon-spices-applets#3787]
**Applet version/Build date (to be found in "About.." or in "metadata.json")**
Version 3.0.7 (2021-05-13 05:58:18)
 
**Cinnamon version (cinnamon --version)**
Cinnamon 4.8.6

**Distribution - (Mint 17.2, Arch, Fedora 25, etc...)**
Mint 20.1

 **Graphics hardware *and* driver used**
2015 Apple Macbook Pro
Device-1: Intel Crystal Well Integrated Graphics vendor: Apple driver: i915 v: kernel
Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa resolution: 2880x1800~60Hz 
OpenGL: renderer: Mesa DRI Intel Iris Pro Graphics P5200 (HSW GT3) v: 4.5 Mesa 20.2.6 compat-v: 3.0 direct render: Yes 

**Snippet or attachment of ~/.cinnamon/glass.log**
info t=2021-05-17T12:22:33Z [weather@mockturtl#29]: Weather Information refreshed
info t=2021-05-17T12:22:42Z [weather@mockturtl#29]: hourlyScrollView requested height and is set to: 236
info t=2021-05-17T12:22:42Z [weather@mockturtl#29]: hourlyScrollView requested height and is set to: 472
info t=2021-05-17T12:22:43Z [weather@mockturtl#29]: hourlyScrollView requested height and is set to: 944
info t=2021-05-17T12:22:48Z [weather@mockturtl#29]: No need to update yet, skipping
info t=2021-05-17T12:23:03Z [weather@mockturtl#29]: No need to update yet, skipping
info t=2021-05-17T12:23:08Z [weather@mockturtl#29]: hourlyScrollView requested height and is set to: 1888
info t=2021-05-17T12:23:18Z [weather@mockturtl#29]: No need to update yet, skipping
info t=2021-05-17T12:23:22Z [weather@mockturtl#29]: hourlyScrollView requested height and is set to: 3776
info t=2021-05-17T12:23:33Z [weather@mockturtl#29]: No need to update yet, skipping
info t=2021-05-17T12:23:48Z [weather@mockturtl#29]: No need to update yet, skipping
info t=2021-05-17T12:24:03Z [weather@mockturtl#29]: No need to update yet, skipping
info t=2021-05-17T12:24:18Z [weather@mockturtl#29]: No need to update yet, skipping
info t=2021-05-17T12:24:24Z [weather@mockturtl#29]: hourlyScrollView requested height and is set to: 7552

**Notify author of applet**
@mockturtl

**Issue**
When I click the toggle button to view the hourly forecast, the first time works correctly.  The next time I try it, the hourly forecast appears higher (twice as high) as last time.  Each subsequent toggle to view the hourly forecast pushes it higher up and higher up until it is off the top of the screen.
Notice in the logs above that "hourlyScrollView" height appears to double upon each click on the hourly forecast button.

**Steps to reproduce**
Click Weather applet button in the panel.  Click the hourly toggle button in the Weather panel.  Hourly forecast is displayed.  It is pushed too far up.

**Expected behaviour**
Not to be pushed up at all.

**Other information**
This has been a probem since I started using the applet about 5 months ago.

**Comment by Gr3q** [comment]
Hi, I'll try to debug this, but I have no idea how to reproduce this problem, but I'll try a few things anyway.

A bit more in-depth explanation:
- I set the height exactly to the requested size because of previous issues with low resolution displays when animations are off.
- The size request comes straight from GTK, I do not calculate it manually or anything like that.

**Comment by GalacticSun** [comment]
By the way, I thought I'd mention that I have a Hi-DPI display (2880x1800).  I noticed that doubles the resolution.  Under Prefs->Display->Layout tab I have User Interface Scale set to "Double (Hi-DPI)", so maybe that is having an affect in some way?  Not sure, but I thought I'd let you know in case this might be part of the cause.

**Comment by GalacticSun** [comment]
In fact, I just tried turning off Hi-DPI (set it to "Normal") and then tested the Weather applet by toggling the hourly view, and it does work as expected - so this problem does appear to have something to do with Hi-DPI.  Hopefully this info can help you fix it.

**Comment by Gr3q** [comment]
Thanks, that's very useful, I will (probably) fix it easily

**Comment by Gr3q** [comment]
Wow, it was annoying to fix, only because I had to use 2x scaling on my 15" laptop display.

Basically I was setting the min-height as styling to workaround some issues with low resolution displays (set it the exact height needed), but I never removed them when that section got collapsed. 

So basically because of that styling the box it started to increase it's preferred size every time it was shown again.

I'm waiting for another of my PR, I'll remove the draft tag of the fix after.

**Comment by GalacticSun** [comment]
Thanks, Gr3q.  Glad that info heped and you were able to fix it.
