### ISSUE TITLE
toggle the visibility of unvisible apps

### ISSUE THREAD

**Issue by Pferdinant243** [linuxmint/cinnamon-spices-applets#3797]
```
 * Version 1.1.0 (2021-02-06 02:47:05)
 * Cinnamon version 4.8.6
 * Distribution - LMDE 4 Debbie
 * Intel Corporation HD Graphics 520

 ```

**Notify author of applet**
@cardsurf
@feuerfuch 

**Issue**
Applet is not extracting or toggling the visibility as expected.

**Steps to reproduce**
right click
Einrichten... (Settings...)
under configuration:
Change Action to 'toggle visibility applets'
and Trigger : Mouse hover

**Expected behavior**
That it works like, @Feuerfuchs collapsible tray. Or the applets will appear in the pop up and then usable in there (like in the KDE Systray).

**Other information**
I think it's a nice idea, with a lot of potential. Maybe you and Feuerfuchs could work together and and greate synergies for a great useful tool!

Thank you, for your hard work, guys!

**Comment by NikoKrause** [comment]
Please add the name of the applet in the title. Not sure, which applet you're talking about.
