### ISSUE TITLE
ipindicator@matus.benko@gmail.com : Home icon not displayed

### ISSUE THREAD

**Issue by PRSoftware** [linuxmint/cinnamon-spices-applets#3800]
* Applet version/Build date : 2021-05-07 09:04:17
 * Cinnamon version : Cinnamon 4.8.6
 * Distribution : Mint 20.1

Hello,

Since the last update, the custom icon configured for home ISP is not shown and a message "trying to fetch IP information" is displayed when the mouse is over the applet.

It was ok with the previous version.

Here is the lookingglass.log (I have masked my IP address): the ISP is well recognized and the associated icon is found but it is not displayed ...

info t=2022-06-04T18:10:12Z Setting debugger log level: 2
info t=2021-06-04T18:10:12Z Updating with no info
info t=2021-06-04T18:10:12Z Checking if network interfaces have changed
info t=2021-06-04T18:10:12Z Executing /home/patrick/.local/share/cinnamon/applets/ipindicator@matus.benko@gmail.com/getNetworkInterfaces.sh
info t=2021-06-04T18:10:12Z Old interfaces: 
info t=2021-06-04T18:10:12Z Current interfaces: enp5s0,lo
info t=2021-06-04T18:10:12Z CHANGED!!!
info t=2021-06-04T18:10:12Z Fetching full info
info t=2021-06-04T18:10:12Z http://ip-api.com/json?fields=country,countryCode,isp,query
info t=2021-06-04T18:10:12Z Update interval ifconfig = 5 seconds
info t=2021-06-04T18:10:12Z Checking if public IP has changed
info t=2021-06-04T18:10:12Z Fetching only IP
info t=2021-06-04T18:10:12Z https://bot.whatismyipaddress.com/
info t=2021-06-04T18:10:12Z Update interval service = 5 minutes
info t=2021-06-04T18:10:12Z Status code: 200
info t=2021-06-04T18:10:12Z Response = {"country":"France","countryCode":"FR","isp":"ProXad network / Free","query":"__.__.__.__"}
info t=2021-06-04T18:10:12Z Updating info
info t=2021-06-04T18:10:12Z ip = __.__.__.__
info t=2021-06-04T18:10:12Z isp = ProXad network / Free
info t=2021-06-04T18:10:12Z country = France
info t=2021-06-04T18:10:12Z countryCode = fr
info t=2021-06-04T18:10:12Z Searching for ISP settings
info t=2021-06-04T18:10:12Z ISP setting found: ProXad network / Free
info t=2021-06-04T18:10:12Z iconName: /home/patrick/Images/Icones/Perso/maison.ico
info t=2021-06-04T18:10:13Z Status code: 200
info t=2021-06-04T18:10:13Z Response = ____:___:____:____:____:____:____:____
info t=2021-06-04T18:10:13Z Old public IP: undefined
info t=2021-06-04T18:10:13Z Current public IP: ____:___:____:____:____:____:____:____
info t=2021-06-04T18:10:13Z CHANGED!!!
info t=2021-06-04T18:10:13Z Fetching full info
info t=2021-06-04T18:10:13Z http://ip-api.com/json?fields=country,countryCode,isp,query
info t=2021-06-04T18:10:13Z Status code: 200
info t=2021-06-04T18:10:13Z Response = {"country":"France","countryCode":"FR","isp":"ProXad network / Free","query":"__.__.__.__"}
info t=2021-06-04T18:10:13Z Updating info
info t=2021-06-04T18:10:13Z ip = __.__.__.__
info t=2021-06-04T18:10:13Z isp = ProXad network / Free
info t=2021-06-04T18:10:13Z country = France
info t=2021-06-04T18:10:13Z countryCode = fr
info t=2021-06-04T18:10:13Z Searching for ISP settings
info t=2021-06-04T18:10:13Z ISP setting found: ProXad network / Free
info t=2021-06-04T18:10:13Z iconName: /home/patrick/Images/Icones/Perso/maison.ico
info t=2021-06-04T18:10:18Z Checking if network interfaces have changed
info t=2021-06-04T18:10:18Z Executing /home/patrick/.local/share/cinnamon/applets/ipindicator@matus.benko@gmail.com/getNetworkInterfaces.sh
info t=2021-06-04T18:10:18Z Old interfaces: enp5s0,lo
info t=2021-06-04T18:10:18Z Current interfaces: enp5s0,lo
info t=2021-06-04T18:10:18Z ARE NOT CHANGED

**Comment by PrimaMateria** [comment]
Hi @PRSoftware 

Sorry for the late answer. Next time, please mention my nickname, otherwise I won't be notified.

In the logs, I would expect one more line saying "Appearance is ....". After this log command, if the appearance includes icon, the `_showIcon` is called, which should set the custom ISP icon. I don't really get it why it's missing.

Can you maybe try to go to config and change values in the appearance select item? Or open Looking Glass and reload the applet code.
