### ISSUE TITLE
US Weather Service forecast wrong days, wrong forecast

### ISSUE THREAD

**Issue by holmesrichards** [linuxmint/cinnamon-spices-applets#3806]
```
 * 2.6.9
 * 4.8.6
 * Mint 20.1

 ```

**Notify author of applet**
@

It is Monday morning. With US National Weather Service selected, applet is showing forecast for Wednesday, Thursday, Friday.

![Screenshot from 2021-06-14 08-44-11](https://user-images.githubusercontent.com/56895621/121895666-7c9ed980-ccee-11eb-935d-d5c5ece5c38b.png)

I would expect today, tomorrow, Wednesday.

The forecast does not match the one on the NWS website for the same location for the upcoming Wednesday, Thursday, Friday but it does approximately match the actual weather for Wednesday, Thursday, Friday of last week, so I suspect the applet is serving an old out of date forecast. (Current conditions are correct, however.)

**Comment by Gr3q** [comment]
Hi, is this still an issue?

if yes, could you share your location you are using (over email or somewhere else) so I can see the NWS payload?

Without that I will have a harder time fixing this, but I can always add extra checks to make sure I don't use days in the past.

**Comment by holmesrichards** [comment]
Now it's showing "Sunday, today, tomorrow".

![Screenshot from 2021-06-14 18-37-43](https://user-images.githubusercontent.com/56895621/121968147-c06dff00-cd3f-11eb-8065-52cf65c66d2d.png)

I am in Syracuse, New York, USA. More specifically in the vicinity of 43.05°N 76.25°W.

**Comment by Gr3q** [comment]
Thanks, I'll have a look. Currently US weather API seems to be down

**Comment by Gr3q** [comment]
let me know if the fix is working

**Comment by holmesrichards** [comment]
I still have 2.6.9 and Applets says no update is available.

**Comment by Gr3q** [comment]
That's problematic because the current version is 3.0.9, 2.6.9 is pretty old

**Comment by holmesrichards** [comment]
Cinnamon version is 4.8.6.

I tried uninstalling and reinstalling (using Applets), and now I get an error.

![Screenshot from 2021-06-20 13-19-45](https://user-images.githubusercontent.com/56895621/122683035-d873d180-d1ca-11eb-863b-3ffb9a88353f.png)
![Screenshot from 2021-06-20 13-19-09](https://user-images.githubusercontent.com/56895621/122683039-dc075880-d1ca-11eb-8c4f-84d2b49e5566.png)

I don't know what Spices updater is.

**Comment by Gr3q** [comment]
Have you tried restarting cinnamon? What does the Looking Glass app say?
