### ISSUE TITLE
weather@mockturtl - Met Office UK provider not working

### ISSUE THREAD

**Issue by WhosyVox** [linuxmint/cinnamon-spices-applets#3815]
@mockturtl 

As of around 11pm UK time (as first observed), the Met Office provider for the weather applet has stopped working.

I'm not sure if this is due to a change in the API or an edge case not yet handled by this applet, but the issue can be tracked at least on my side, to line 441 of `met_uk.ts`. Where the code currently expects `element.Rep` to be`ObservationPayload[]`, instead the json returned seems to have been only a single instance of `ObservationPayload`. This resulted in the method always returning null. Having changed the line to simply `return element.Rep`, the applet began to work as expected and appears to be outputting the correct weather data.

**Comment by Gr3q** [comment]
It is a edge case, it seems a few observation sites return data in a different format
