### ISSUE TITLE
weather@mockturtl - daylight savings bug in Met Office provider

### ISSUE THREAD

**Issue by WhosyVox** [linuxmint/cinnamon-spices-applets#3817]
@mockturtl 

Between 00:00 to 01:00 the applet cannot load any weather data through Met Office. I believe this is because of the discrepancy between the date in UTC vs BST.

As of 01:01, predictably, the issue resolved itself once more.

**Comment by Gr3q** [comment]
I'll look into it, thanks

**Comment by Gr3q** [comment]
@WhosyVox I think the issue might be fixed, but reopen this issue if it's still not resolved
