### ISSUE TITLE
[hwmonitor@sylfurd]: Settings window too small

### ISSUE THREAD

**Issue by jkirk** [linuxmint/cinnamon-spices-applets#3818]
**Facts**

 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 1.3.1 -> https://github.com/linuxmint/cinnamon-spices-applets/tree/009831231f8bd0a04e7f8c45f8b1ad2931e24a1c
 (**please update the version string.**)
 * Cinnamon version (cinnamon --version)
 Cinnamon 4.8.6
 (**please add support for Cinnamon 4.8.**)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 Debian GNU/Linux 11 (bullseye)

**Notify author of applet**
@hultan

**Issue**
The settings window is too small. The settings pages are not visible at first:

![Screenshot from 2021-06-22 11-07-27](https://user-images.githubusercontent.com/288637/122897178-0c293580-d34a-11eb-8202-13e81b4a9ad6.png)

Only after expanding the width, the settings pages get visible:

![Screenshot from 2021-06-22 11-14-11](https://user-images.githubusercontent.com/288637/122898201-fb2cf400-d34a-11eb-84c6-d54e3d90e7d9.png)

**Steps to reproduce**

Right click hwmonitor-applet -> click configure

**Expected behaviour**

The settings window should be large enough to make all settings pages visible by default.

Thanks for maintaining the applet and looking into this. 🤗

**Comment by Hultan** [comment]
To my knowledge, hwmonitor has no control over the settings window size. I believe this is handled by Cinnamon. Is it still a problem for you? I guess that, since it had been a month, you have rebooted your machine, otherwise try that.
