### ISSUE TITLE
Rules violations for a lot of applets.

### ISSUE THREAD

**Issue by lestcape** [linuxmint/cinnamon-spices-applets#385]
Yours reviewer are adding a translations to all extensions in cinnamon against yours owns rules.

"Pull requests from other people

In addition to the checks specified above, if the pull requests comes from **somebody else than the author**, the reviewer will need to check the nature of the changes.

If the changes represent a bug fix, the PR can be merged.

If the **changes** represent a change in **functionality**, or in look and **feel**, or if their implementation could be questioned and/or discussed, **the reviewer should leave the PR open** and **ask the author** to review it.

**If the author is happy with the PR, it can then be merged**. If he's not, it can be closed instead."

**Comment by JosephMcc** [comment]
From my understanding of discussions I've seen, translations are treated as a bit of a special case. They provide a benefit to all spices users. They are being treated more as a bugfix than a feature.

Outside of that, up until now you've been quite clear about the fact that you want nothing to do with this new system. That's fine and it's your choice to make. I don't understand why then you feel the need to pop in here just to open an issue like this.

**Comment by lestcape** [comment]
Because this is exactly the reason of why i don't want...

**Comment by lestcape** [comment]
Make what you want of course, it's yours repository, you are not doing anything wrong then, but don't say this is a repository of third-party then, is not in that way is yours repository and of course yours can do what you want here.

**Comment by lestcape** [comment]
That is not nice, i lost 5 years as a Cinnamon thrid-party dev, and all for what? @clefebvre decide fork all thrid-party extension and change it like he want. I will not stop this here, this is not right. This will go from the network.

**Comment by jaszhix** [comment]
> Reviewvers, yours are adding a translations to all extensions in cinnamon against yours owns rules.

"Pull requests from other people

In addition to the checks specified above, if the pull requests comes from somebody else than the author, the reviewer will need to check the nature of the changes.

If the changes represent a bug fix, the PR can be merged.

If the changes represent a change in functionality, or in look and feel, or if their implementation could be questioned and/or discussed, the reviewer should leave the PR open and ask the author to review it.

If the author is happy with the PR, it can then be merged. If he's not, it can be closed instead."

> That is not nice, i lost 5 years as a Cinnamon thrid-party dev, and all for what? @clefebvre decide fork all thrid-party extension and change it like he want. I will not stop this here, this is not right. This will go from the network.

I think the full discussion happened, and people decided whether to keep their applets here or not. Since everybody who wanted them removed had the chance by now, I don't think this disservices anybody by having people translate their applets for them. It brings more attention to a lot of applets that otherwise would be lost in obscurity.

I had my doubts at first, but I have come around to the idea of it after seeing how much better the quality is. Its allowed me to fix a bug in the weather applet that's annoyed me. I've seen more help with translations on my own applets. I think the whole point of writing these extensions is to improve Cinnamon. At the end of the day your applet is going to be on Github, whether its here, or on your account I think is a minor difference. You in particular GPL licensed your work, that is free software. Nobody has to get your blessing to fork it any way, it is just good conduct to ask - LM respected this by removing your applets.

Did you waste 5 years? It seems like any experience I get writing code, I grow as a developer. It seems a little bitter.

**Comment by lestcape** [comment]
@jaszhix wander-full if it's your decision.

I commented here because this is just the proved from where this come, before I had not prove and it was just my fear. **This is then only the broken promise of respect the author decisions about not modify the code without his authorization** So, this is the end of the chance to wait for a different implementation. This is then the death of all code that i make to work inside cinnamon only.

And finally this is the death of all the hopes I could have, that things were not where they certainly go. I can speak with base on facts now and not ex-peculations for an unclear things...

So, this is just only that i feel bad about who the things are now and i express my nonconformity with this.

Won't worried, the thing can not go more wrong for me here, as actually i removed all things, that also included the hope.

**Comment by jaszhix** [comment]
> This is then only the broken promise of respect the author decisions about not modify the code without his authorization

How are PO files code? Honestly as an English only speaker this translation help is nice. Before I spent hours copying (probably) mediocre translations from Google Translate. Now more native speakers are doing it.

I could have removed my applets, maybe even build a mirror of Spices, and maybe continue work on your port of Cinnamon's JS. I'm not though because the Linux userland has way too much fragmentation as it is. It is my decision.

**Comment by JosephMcc** [comment]
So, you posted the issue, I responded, you deleted all your comments, and now some of them at least are back. This isn't going much further or it will be locked.

The spices site is run by Linux Mint and Linux Mint sets the rules for it. That means they can be changed by Linux Mint when it is felt necessary. You made it clear from the beginning you didn't like the idea. We respected your wishes and removed all of your stuff when you asked. You've chosen not to be a part of this or a contributor to it. Fine, that's your choice. Ranting and threatening things like "I will not stop this here, this is not right. This will go from the network" is going to get you nowhere. It will simply result in the issues being closed, locked, and/or deleted.

**Comment by collinss** [comment]
https://github.com/linuxmint/cinnamon-spices-applets/commit/48a642fdc2100256d8c6dc83acfb3c970d06b302

**Comment by brownsr** [comment]
@lestcape I wish you well in whatever you move onto next.  I enjoyed working with you on Mint code, you were knowledgeable and inventive, and you helped me solve some problems.  We are all part of a small community trying to move things forward and to do the right thing for those who use our open source software.  Adding translations would seem to be one of those things that is so obviously going to be of benefit to our users.  It's something that is fundamentally aligned to the open source ethos, with people from different countries contributing their language skills, so more people can use our code.  And with gettext tools it is largely independent of writing the application code. So although I can see you appear to be upset and angry, I don't really understand why. I am glad that @collinss has clarified how translations are handled, above. But anyway ... best wishes for your future work. Simon.

**Comment by lestcape** [comment]
@brownsr I know i'm difficult to understand the English is not my language. All my projects have translations, i was the first who ask to a way to do that. The translation are not the problem.

My problem is work with the rules of others in my projects. I want to be the manager, the author, and the developer of my projects, if is not in that way i don't want to do it.

In the new model, I'm not the manager of my own code, it's @clefebvre, as it's the leader of the Mint team. In my head, I have never developed a software for Mint. I create free software, as cinnamon it's a cross desktop that can be installed in different distros. I add cross code to cinnamon only because of it.

If i was wrong and always was Mint software only, sorry, i was who is wrong. Also in my own code that i develop outside here.

If it's free software, why my code is lead by other person and why this other person can decide or change something for little that it was without ask to the author or the manager?

I don't agree with anything of it and more than that i think this not good for cinnamon at all, as rules are impositions that limited the freedom for create software. 

All this have a different perception of course. Freedom and security are two words where in software like in life, they go always in opposite directions.

In that point we are in opposite directions then, as by concept, as by law, the free software it's without any warranty. So, i don't understand what is this, but it's not what the licence of the code say. What i do say clear in the license is: without any warranty. The mint warranty don't say me anything, just it changed  what i say.

Sorry, if this could create problems to you or anyone, this create problems to me. Most of you only do what the lead say, and how this was his idea, need to be also only his matter, and not anything else. I know is not in this way.

**Comment by lestcape** [comment]
If any-want want to change somethings in my project they can fork it and change it, but not in my project, in his copy all can. so, copy it and not do it in my name.

**Comment by JosephMcc** [comment]
@lestcape nothing is being done here in your name. YOU asked for your projects to be removed when this first started a couple of months ago. YOUR wishes were respected. Why you've suddenly come back after all this time looking to cause trouble I really don't get. You didn't want to be a part of it. You moved on. The project moved on.

Many of the Mint/Cinnamon devs, myself included, have worked/communicated with you on projects in the past. Never do I remember you being treated disrespectfully. You want to run around places like g+ posting about ethics, changing your github bio, and generally bad mouthing the Mint projects. Yet then I see you are essentially porting huge amounts of cinnamon code to create your new gnome extensions. That's fine, this is open source after all. But while you use it your going to bad mouth the people who wrote much of it? A multitude of devs contributed to writing that code of the years and it seems you are going to refuse to give them any credit for their hard work. Not sure you have any room to talk about ethics.

**Comment by lestcape** [comment]
@JosephMcc the extension that you mention won't work and say **"it's an intention to port cinnamon desktop"**. Of course you and all involved have all credits then it will work some day, i don't make cinnamon. I just i try that it will run inside other platforms and not success.

The last comment explain to @brownsr why i don't agree to continues working and why i considered the new model is not ethics and not more than that. I don't think i'm the most ethics or something, similar and my problem it's not with you.

**Comment by lestcape** [comment]
@JosephMcc I think was enough, i reported what i considered a problem and you all heard them. I remove the g+ publications. If you want remove this also. If you can not remove my comments i will do for you if you are ok with it.

**Comment by JosephMcc** [comment]
Ok, I'll just lock it. No reason to delete anything in case someone does end up here.
