### ISSUE TITLE
Website: cinnamon-spices.linuxmint.com  unable to "un-like" an applet.  

### ISSUE THREAD

**Issue by SZemanek** [linuxmint/cinnamon-spices-applets#3872]
I accidentally clicked "like it" on the wrong applet on the cinnamon-spices website.   There is seems to be no way to "unlike" an applet, theme, extension, or desklet.  

Considering this is how "popularity" is determined on the applets configuration panel within Cinnamon, this should probably be fixed.  

Also, consider counting the number of downloads instead of number of likes to determine "popularity", or allow users to "like" a plugin from within the Cinnamon GUI.  Not everyone has a github account.

**Comment by NikoKrause** [comment]
You're right. It's not possible to unlike an applet. The like will disappear after a year.
For more details see: https://github.com/linuxmint/cinnamon-spices-applets/issues/2542

Furthermore Linux Mint does not count any downloads. As mentioned by @clefebvre in this ![blog post](https://blog.linuxmint.com/?p=4030):
> We can’t measure anything with precision because there’s nothing in your computer which sends data to us and we don’t configure Linux Mint in a way that even allows us to count how many users we have. In other words, there is nothing in Linux Mint that is common to all users and that we could rely on to establish statistics.
