### ISSUE TITLE
weather@mockturtl: - feature request - custom temperature scales

### ISSUE THREAD

**Issue by Elle1108** [linuxmint/cinnamon-spices-applets#3882]
UUID: weather@mockturtl
Last edited: 1 day ago 2021-08-09, 01:53
Last commit: [003ed882] [weather@mockturtl] Update He.po (#3879) 
@Gr3q 
It'd be nice to have the ability to add our own temperature scales to the applet.

To implement it you could have a text box to ask for the symbol for it (like we have °F and °C) and then two more boxes to ask for the freezing point and boiling point of water. The app could take care of the math to convert to the user's custom temperature scale to then display on the applet

**Comment by Elle1108** [comment]
@mockturtl too just in case

**Comment by Gr3q** [comment]
Hi, sorry for the late reply.

To be honest, I don't see the use case of supporting custom temperature scales.

I can add the rest of the existing temperature scales (Kelvin and Rankine) next to Celsius and Fahrenheit if that helps, but adding custom scales is not worth the complexity.

**Comment by Elle1108** [comment]
> Hi, sorry for the late reply.
> 
> To be honest, I don't see the use case of supporting custom temperature scales.
> 
> I can add the rest of the existing temperature scales (Kelvin and Rankine) next to Celsius and Fahrenheit if that helps, but adding custom scales is not worth the complexity.

I think that's a good idea, I have no idea if you did it yet or not I've been using gnome for a while now. Delisle is a nice one that's included in the gnome weather extention, I had no idea it existed before
