### ISSUE TITLE
Move typescipt declaration to node module

### ISSUE THREAD

**Issue by jonath92** [linuxmint/cinnamon-spices-applets#3886]
@Gr3q What do you think about moving the typescript declarations to a node package? Currently it is not very comfortable to use the declarations outside of this repo (e.g.  for cinnamon desklet/extension,  unpublished applets, custom libraries, ...).  I would for example like to use them for [this](https://www.npmjs.com/package/cinnamonpopup) node package. Also the types might even be useful for gnome users.

**Comment by Gr3q** [comment]
It definitely can be, I'll see what can I do tomorrow. 

I think we can do both for a while.

**Comment by Gr3q** [comment]
It's accessible here: 

https://www.npmjs.com/package/@ci-types/cjs

For now, you have to make a declaration file with the contents
```ts
import "@ci-types/cjs";
```

I don't know how can I make it imported by default atm, let me know if you know.

**Comment by jonath92** [comment]
Many thanks that's really great. 

> I don't know how can I make it imported by default atm, let me know if you know.

I also don't know atm. It would be of course nice if the declaration file wouldn't be needed but it is not a big issue for me. 

IMO there is no reason to keep the types twice - inside this repo and as node module as this can easily lead to inconsistencies. I also think it is a better workflow to just use the node package as in that way it is more clearly differentiate between applet code and typescript code - so when I want to commit some type changes I can do so in your repo and simon doesn't need to accept the Pr. That's why I have now started using the node module types in the radio applet. 

For some reason I had to include `"moduleResolution": "Node"` in my tsconfig.json as without typescript didn't find the types. Fun fact: without the types I received 172 errors which shows how useful the types are.

**Comment by Gr3q** [comment]
Without `"moduleResolution": "Node"` Typescript won't look for imports in the `node_modules` folder.

The main reason I want to keep the declarations here too because I don't want to force people to use webpack if they want to use typescript, but ofc I don't want duplicate code

**Comment by brownsr** [comment]
You are very much doing your own thing between yourselves here.  Which is fine.  But if you are moving things externally, please be aware of why we have the spices in a repo, which is so we can review and inspect the code to ensure it is not carrying malware of any sort.  Essentially we want our userbase to be secure from this sort of thing, as best we can.  So if you are moving things externally, to something I won't review, my colleagues won't review, and isn't general purpose packaged libraries that have lots of eyes on them, then I am going to get nervous about the way things are going.  I don't have a background in node etc, don't know the pros and cons of what you are suggesting, but I will need to be able to review and inspect your merge requests within this repository without having to hop elsewhere.   No need to respond, and actually please don't, as I don't often read my email !

Regards

Simon
