### ISSUE TITLE
Cinnamenu@json Feature request to add remove app option like default menu does on LM

### ISSUE THREAD

**Issue by LambLeeg** [linuxmint/cinnamon-spices-applets#3898]
So, when you use default Cinnamon's menu spice, then you can right-click and remove a software on Linux Mint. Is there a way to add it to this awesome alternative spice?

**Comment by fredcw** [comment]
@LambLeeg Do you mean an option to uninstall the software packages? Cinnamenu used to have this but I removed it because of the risk of inexperienced users uninstalling vital system packages by mistake and I couldn't think of an easy way to prevent this. It's much safer to use the software manager. Also, the default menu doesn't have this option.

**Comment by LambLeeg** [comment]
> @LambLeeg Do you mean an option to uninstall the software packages? Cinnamenu used to have this but I removed it because of the risk of inexperienced users uninstalling vital system packages by mistake and I couldn't think of an easy way to prevent this. It's much safer to use the software manager. Also, the default menu doesn't have this option.

Yes, I talk about that. I think, it can be disabled by default but be available in settings. Default menu in Linux Mint has it, tho, I have not seen it on Fedora or Manjaro etc. I can attach screenshot with this option

**Comment by fredcw** [comment]
You're right, the default menu has this option in linux mint, I forgot about this. I'll have a look to see if there's a better way to implement this.

**Comment by LambLeeg** [comment]
> You're right, the default menu has this option in linux mint, I forgot about this. I'll have a look to see if there's a better way to implement this.

Thank you! I suppose, I can close now the branch?
