### ISSUE TITLE
weather@mockturtl : Add Yandex.Weather to the applet as a weather provider too.

### ISSUE THREAD

**Issue by IT-Tool** [linuxmint/cinnamon-spices-applets#3915]
@mockturtl

**﻿Feature request:**

Please add Yandex.Weather to the weather applet.
There is a free plan. Details can be found here - https://yandex.com/dev/weather/
It can be very useful and here's why - https://yandex.com/pogoda/meteum

**Thank you for the best weather applet**

**Comment by Gr3q** [comment]
Hi I will implement it when I find some time.

Note from what I can see Yandex does not provide Hourly forecast.

**Comment by Gr3q** [comment]
Are you using the paid subscription for yourself? the free one has like 2-2.5 days of forecasts and no hourly weather, which is not much

**Comment by IT-Tool** [comment]
I thought it would be easier, but writing to tech support received an answer:

"Unfortunately, we can not help you. Currently, API data is provided selectively, mainly for resources that conduct media activities, or for large meteo-dependent market players.

It is possible that in the future the situation will change. In this case, information will appear on the pages of the service.

If you have any new questions about Yandex services, please contact us."

I think I can close this task for now.

By the way, I will periodically scan this page for changes.
https://yandex.com/dev/weather/doc/dg/concepts/pricing.html
