### ISSUE TITLE
[Feature] Cinnamenu@json Option to adjust the space between icons

### ISSUE THREAD

**Issue by slgobinath** [linuxmint/cinnamon-spices-applets#3933]
```
 * Applet version/Build date: 4.14.15 (2021-09-15 03:51:59)
 * Cinnamon version: 5.0.5
 * Distribution - Mint 20.2
 ```

**Notify author of applet**
@fredcw 

**Feature**
First of all thank so much for this awesome applet. I'm able to get a unity like dashboard using your applet. However the default icon distribution in grid view seems little crowded. I understand it is totally a personal preference but I would appreciate it if there is a way to configure the number of columns and/or margins for icons.

Right now, I have hard coded the column count and the top and bottom padding to get my desired output https://github.com/slgobinath/cinnamon-spices-applets/commit/0f0429be9646ebd809c5d0202c5e8548a37b916b

![Screenshot from 2021-09-21 08-09-08](https://user-images.githubusercontent.com/4003168/134167859-f2b40ad4-1e0b-46a0-a48b-4cc9dfd75e0e.png)

Without above hack, the icons look too crowded to my eyes. Once again it's my personal taste but I hope it will be a nice addition to the applet. @fredcw WDYT?

**Comment by fredcw** [comment]
@slgobinath It looks good. Someone else suggested this as well. I'll think about it but really I want to avoid making the user options too complicated. It may even be a better idea to make a separate full screen menu applet similar to gnome.

**Comment by slgobinath** [comment]
Instead of separate applet, what do you think about a drop down list providing different styles? Currently there are list and grid views.
I also noticed win 10 tile style configuration on your GitHub repo. So what i we have a drop down with the following styles or something similar:

- Cinnamon
- Win 10
- Gnome

and change the settings internally?

IMHO forking this applet will cause a lot of duplicate maintenance and only two lines have to be changed other than the UI related stuff. I think such a style selection can hide the complexity. WDYT?

Thanks

**Comment by fredcw** [comment]
Tbh, I haven't really been feeling that motivated to do much programming lately and there's a few other things I've been thinking about. Should cinnamon applets transition to using gtk rather than the st library for better features in the future and how does wayland fit into that picture, I have no idea. Also, xfce, mate, cinnamon and gnome applets are all incompatible, maybe there should be a more desktop agnostic way of writing applets to avoid duplication of effort in general?

**Comment by slgobinath** [comment]
Makes sense. I'm closing this issue since I can live with the current hack.
