### ISSUE TITLE
[MuteToggler@jebeaudet.com] Not working on every installation

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#3979]
```
 * Applet version/Build date: 2021-07-16 09:28:06
 * Cinnamon version: 5.0.5
 * Distribution: Mint 20.2
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log: N/A
 * Snippet or attachment of ~/.xsession-errors: No entries

 ```

**Notify author of applet**
@jebeaudet 

**Issue**
I have `MuteToggler` installed on two computers, both with Mint 20.2. It works on one, but not on the other. I could track it down to the problem, that `Capture` does not exist on one computer:

1st computer:
```sh
$ amixer scontrols
Simple mixer control 'Master',0
Simple mixer control 'Headphone',0
Simple mixer control 'Speaker',0
Simple mixer control 'PCM',0
Simple mixer control 'Mic',0
Simple mixer control 'Mic Boost',0
Simple mixer control 'IEC958',0
Simple mixer control 'IEC958',1
Simple mixer control 'IEC958',2
Simple mixer control 'IEC958',3
Simple mixer control 'IEC958',4
Simple mixer control 'Capture',0
Simple mixer control 'Auto-Mute Mode',0
Simple mixer control 'Digital',0
Simple mixer control 'Internal Mic Boost',0
Simple mixer control 'Loopback Mixing',0
```

2nd computer
```sh
$ amixer scontrols
Simple mixer control 'IEC958',0
Simple mixer control 'IEC958',1
Simple mixer control 'IEC958',2
Simple mixer control 'IEC958',3
Simple mixer control 'IEC958',4
```

Toggling the microphone with the help of the `Sound applet` works on both computers.

**Expected behaviour**

Show at least an error message, if toggling does not work.

**Other information**

Because toggling the mic with the `Sound applet` works, that left me wondering, if it is not easier (for the user) to implement the feature of `MuteToggler` into the `Sound applet`. Most of the features are already there: In the preferences dialog, it is possible to set the action of a middle click to `Toggle Mute input`. The only feature missing is to show it on the icon, e.g. by an emblem/badge with a green or a red, crossed out mic. (This would also save some space!)

What do you think?

**Comment by sphh** [comment]
Maybe you can use the same (or similar) code as the `SoundApplet` to toggle the microphone.

I did a bit of digging and found, that `GroupedWindowList` uses badges to show the number of windows in a group: https://github.com/linuxmint/cinnamon/blob/749a4952b7d5ad6dd258017a3d13b47351148953/files/usr/share/cinnamon/applets/grouped-window-list%40cinnamon.org/appGroup.js#L117

Unfortunately my knowledge of JavaScript does not reach that far to make such changes …

**Comment by sphh** [comment]
I finally found a way around the problem, that the microphone is not toggled: In these cases the following command line parameters have to be added: `-D pulse`, e.g. `amixer -D pulse sget Capture`. Perhaps the applet can check for this control to exist with `amixer scontrols` and if no `Capture` device exists it checks with `amixer -D pulse scontrols` and adapts the command line accordingly?

BTW why do you use the `bash` shell and not the (simpler) `sh` shell?

**Comment by jebeaudet** [comment]
Hi @sphh 

Unfortunately I'm not using linux mint anymore, if you propose a PR or a ownership takeover I would be open to review it and merge it here, let me know.

**Comment by sphh** [comment]
@jebeaudet: #5090 is a quick fix. Maybe the user expects an error message, if `amixer` cannot detect the proper channel, but this way above my JavaScript skills!

**Comment by Radius17** [comment]
Last update brokes MuteToggler on Linux Mint 20.3 with error "TextDecoder is not defined"
