### ISSUE TITLE
app-launcher@mchilli : Feature requests - menu separators, browse command, desktop files.

### ISSUE THREAD

**Issue by Hultan** [linuxmint/cinnamon-spices-applets#3984]
Here are few feature requests:

* I would like to be able to add separators in the menu. (See CustomApplicationsMenu@LLOBERA that supports this)
* I would like to browse to the executable (in the command field), instead of manually enter the path.
* I would like to be able to point directly to a desktop file (in the command field), and then preferably icon and name should be filled in from the desktop file. (See CustomApplicationsMenu@LLOBERA that supports this)

Just found this applet, and other than the minor things mentioned above, I love it.

Ps. I just read about the drag'n'drop feature before hitting the submit button, maybe the last two of my suggestions are not that important then...I still definitely want the separators though.

**Comment by mchilli** [comment]
Hey, nice to hear that you like it.
That are interesting ideas, but there are some questions about it:

- should be possible! But i have to figure out a nice way to add the seperators to list view (I don't like the idea to put a special character in the app name, or something like this. Maybe an extra button or so....)
- you mean to open a file browser to choose an executable from there, like when you create a starter from the normal panel launcher?
- did you mean that you want to choose the *.desktop file directly from a path? And when you choose a file and get the icon and name from it, should it be overwritten directly or you have to confirm it first? (Maybe the drag'n'drop feature has more the behaviour you want)

**Comment by Hultan** [comment]
* Yes, it might be difficult to make the config GUI look nice and also work well, but it would really nice to have separators in the menu to group items. Maybe you could add a checkbox field to each menu item (in the "App Launcher" dialog), "add separator before menu item". If you check that checkbox, a separator would be added before the menu item. This might require an extra yes/no column in the list, to show where the separators will be added. That way you don't have to add the separators items to the list.
* Yes, a browse button to the right of the Command field would work. This is not super important, most people are probably better at typing than I am, so they are most likely ok with typing in the path. I am a mouse-point-and-click person :-)
* It might be hard to make it work in the GUI, but my point with this would be that everything you need is in the desktop file (Name, executable path, icon path) with the exception of group (which might be a problem, how would you add a group to a "desktop item"?). So maybe if you could somehow select two options (radiobuttons), either browse to the desktop file, or create the menu item manually as you have to do today. But I feel that this one is not THAT important, when I learned that drag and drop works.
