### ISSUE TITLE
weather@mockturtl current weather column is misaligned

### ISSUE THREAD

**Issue by Gr3q** [linuxmint/cinnamon-spices-applets#3985]
```
 * Applet version/Build date: 3.1.5
 * Cinnamon version: 5.0.6
 * Distribution - Arch
 * Graphics hardware *and* driver used: AMD, amdgpu
 ```

**Issue**
Right column in current weather is misaligned:
<img src="https://user-images.githubusercontent.com/22377521/137987866-8f9bc68a-ab1b-4ef9-af19-5ec11298e013.png" width="400" />

Direct cause is the Celsius (or Fahrenheit) characters make the labels bigger on the right side than on the left side. Other laptop with the same versions does not produce this issue.

I still have to check if it's an updated package or not.

Possible workarounds:
1. Use `Grid` instead of 2 separate vertical BoxLayouts

**Comment by lunalucadou** [comment]
Can confirm this occurs on my machine as well, though it's not as bad as your screenshot.

![image](https://user-images.githubusercontent.com/22415965/146482973-1096e991-8225-4928-b03f-4200dc064447.png)

**Comment by lunalucadou** [comment]
With #4197, this issue has been resolved for me.

![image](https://user-images.githubusercontent.com/22415965/148798862-7352839e-c4fd-4505-a3d7-ecdc1b31e5a1.png)
