### ISSUE TITLE
weather@mockturtl - Location name doesn't change when cycling through multiple locations

### ISSUE THREAD

**Issue by Beckfield** [linuxmint/cinnamon-spices-applets#3993]
weather@mockturtl
```
 * Applet version/Build date (3.1.5 (2021-10-23 01:21:22)
 * Cinnamon version: 5.0.6
 * Distribution - Mint 20.2

 ```

**Notify author of applet**
@mockturtl

**Issue**
I've saved several locations.  When I cycle through them using the left or right arrows in the applet, the weather info changes, but the title does not.

**Steps to reproduce**
Save several locations with unique Search names
Open applet and click left/right arrows

**Expected behaviour**
Title changes to match weather info

**Other information**

**Comment by Gr3q** [comment]
@Beckfield can you close this issue as it was resolved?
