### ISSUE TITLE
Some node packages not working with minimize = false

### ISSUE THREAD

**Issue by jonath92** [linuxmint/cinnamon-spices-applets#3994]
@Gr3q I am currently working on a new applet for which I want to use the node package `query-string` but it doesn't work with the webpack option `optimization: { minimize: false }` (it is working without this option) . I also hat the problem with `chardet` which I might use for the radio applet in future. I googled this option but couldn't find any solution for this (I guess most people don't really care about this option). I opened this ticket to both inform you and to ask if you have any ideas on how to fix this.

**Comment by fredcw** [comment]
@jonath92 What applet are you working on? I'm nosey. xd

**Comment by jonath92** [comment]
I am working on an online calendar applet: 
![image](https://user-images.githubusercontent.com/49979415/139798892-f7de0b37-73ee-4622-a5f6-d486d6cd8d38.png)
I am using it already for some time and I find it pretty useful. Currently it only syncs with Office365. It has a settings dialogue which allows to login: 
![image](https://user-images.githubusercontent.com/49979415/139799242-cf4a20e7-6ffb-4bdb-8820-692bb09c9b57.png)
(On the image it is shown wrongly Google at the moment, it should be office365). The dialogue is highly influenced by the Online Account but it syns with Office365 directly (which makes it less dependent of other packages). When clicking on an account, it is opening the login dialogue for office365 in the browser. The biggest issue I am currently facing is, that for Business accounts you get a warning that it needs admin approval: 
![image](https://user-images.githubusercontent.com/49979415/139799504-52750c62-e888-45fc-894b-e1dc83eba8b9.png)
I think this can be fixed by getting verified in the Azure Portal but Microsoft doesn't make that process very comfortable (or logical).
