### ISSUE TITLE
invalid language tag: "c"

### ISSUE THREAD

**Issue by SL-Pirate** [linuxmint/cinnamon-spices-applets#4010]
```
 * Applet version 3.15
 * Cinnamon version 5.0.6
 * Distribution - Arch linux
 ```

**Notify author of applet**
@

**Issue**

forecast parsing failed: RangeError: invalid language tag: "c"

**Steps to reproduce**

It's the same error ever since it was installed. So sry if I was doing it wrong.

**Comment by Gr3q** [comment]
Hi, I thought I already check for this, so I'm going to double check this.

Anyway, probably you missed this step during system install: https://wiki.archlinux.org/title/Installation_guide#Localization

**Comment by SL-Pirate** [comment]
> Anyway, probably you missed this step during system install: https://wiki.archlinux.org/title/Installation_guide#Localization

I'm pretty sure I set the localization. I was following a youtube guide by DistroTube

**Comment by SL-Pirate** [comment]
Thank you so much. I was first confused cuz I did the loacalization setting. But I later realized that I was missing 

`Create the locale.conf(5) file, and set the LANG variable accordingly:

/etc/locale.conf
LANG=en_US.UTF-8`

part. Now the applet is working fine.
