### ISSUE TITLE
CinnVIIStarkMenu@NikoKrause: Spanish translation

### ISSUE THREAD

**Issue by haggen88** [linuxmint/cinnamon-spices-applets#4037]
Hi @NikoKrause 
I do not know how to generate a PR so I send it this way: 
[CinnVIIStarkMenu@NikoKrause.es.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/7696046/CinnVIIStarkMenu%40NikoKrause.es.po.zip)

Regards

**Comment by fredcw** [comment]
Maybe this will help.

https://github.com/linuxmint/doc-translation-guide/pull/4#issuecomment-897021550
