### ISSUE TITLE
app-launcher@mchilli: Spanish translation

### ISSUE THREAD

**Issue by haggen88** [linuxmint/cinnamon-spices-applets#4046]
Hi @mchilli  
I attach the translation into Spanish in this way:   [app-launcher@mchilli    es.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/7550812/app-launcher%40mchilli.es.po.zip)

Regards

**Comment by mchilli** [comment]
Hi and thanks for the translation, i will commit it with the next update.
There are two new lines in the settings, can you translate it for me, so i can put this in the update too?

1. "Show menu"
2. "Set keybinding(s) to show the menu"

Thanks

**Comment by haggen88** [comment]
@mchilli 

1. "Mostrar menú"  
2. "Establecer combinación de teclas para mostrar el menú" >
