### ISSUE TITLE
weather@mockturtl no update 

### ISSUE THREAD

**Issue by French77** [linuxmint/cinnamon-spices-applets#4053]
```
 * Version 3.1.5 (2021-11-03 08:24:48)
 * Cinnamon version (5.0.7)
 * Distribution - (Mint uma 2.02)


 ```

**Notify author of applet**
@Gr3q 

**Issue**
No Version update to 3.1.6 available still on Version 3.1.5 (2021-11-03 08:24:48)

**Steps to reproduce**
Restart and refresh update manager no updates applets available.
Applets are and always have been perfectly auto-updated,so what is going wrong here ???

**Expected behaviour**

**Other information**

**Comment by mchilli** [comment]
I think its not only the weather applet. There are no applet updates available since the last two weeks, even on the cinnamon-spices website. Maybe this is a larger problem!?

**Comment by haggen88** [comment]
I recently had problems with the Cinnamon-spices website, the blog and the Mint website. In the same blog Clem commented on a problem with Spam ... perhaps that could be related.

**Comment by French77** [comment]
Reported issue at:
[https://github.com/linuxmint/mintupdate/issues/710](url)

**Comment by French77** [comment]
5 days after reporting this problem,(incidentally without any response on how or why this problem has occurred) the update of this applet has been processed
