### ISSUE TITLE
app-launcher@mchilli: Hotkey request

### ISSUE THREAD

**Issue by Hultan** [linuxmint/cinnamon-spices-applets#4055]
@mchilli 

Is it possible to add a HotKey to open the menu and set focus to it, so that you can use it without using the mouse?

**Comment by mchilli** [comment]
Hi, sure it's possible. I will add this with the next update. But i think applets doesn't get updates at the moment, not on the cinnamon spice website nor in linux mint itself!? Hopefully this will be fixed soon.
