### ISSUE TITLE
Cinnamenu@json Flickering of search highlight

### ISSUE THREAD

**Issue by joka42** [linuxmint/cinnamon-spices-applets#4056]
```
 * Applet version/Build date: Current Master 2021-11-21
 * Cinnamon version: 5.0.7
 * Distribution: Mint 20.2
 * Graphics hardware: Intel 630

 ```

**Notify author of applet**
@fredcw 

**Issue**
When searching, the search results are updated and the highlighted entry including the "hover-text" flickers. 

**Steps to reproduce**
Search in cinnamenu and the first entry does not change during text entry.

**Expected behaviour**
* The first item is highlighted and the highlight and "hover-text" do not flicker. 
* Hover text might be disabled completely 

**Other information**

https://user-images.githubusercontent.com/68659955/142775138-23387d8b-3605-4715-8265-578e62f9b74f.mp4

**Comment by fredcw** [comment]
@joka42 Thanks, bug fix on the way.

**Comment by fredcw** [comment]
@joka42 If you're happy with the fix, can you close this issue, thanks.

**Comment by joka42** [comment]
@fredcw the highlight does not flicker anymore, as far as I can see, but the hover text still does. Would it be possible to just not show it at all? I thing that would look nicer anyway.

**Comment by fredcw** [comment]
@joka42 You mean the tooltips? I would have to make an exception to not show tooltips when searching but I'm not sure that's the right thing to do as some people may still find them useful. You can of course turn of tooltips in the options but that might not be ideal.

**Comment by joka42** [comment]
Alright, I disabled it. I don't think it is really necessary to show it, especially during search. I'd argue that when you search an application, you probably know, what it does.
Maybe a little delay during search would be sufficient?

But for me it is fine now, thanks! I will close the issue, have a nice week and Christmas time ;-)
