### ISSUE TITLE
weather@mockturtl: unuseful line in .po and .pot files

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#4096]
**Notify author of applet**
@mockturtl

**Issue**

In .pot an .po files, this line is used:

![Capture d’écran du 2021-12-11 12-28-44](https://user-images.githubusercontent.com/3955499/145675009-f276f734-08dd-4a7a-9990-6d5d50f9d302.png)

But this line isn't used anymore and should be removed:

![Capture d’écran du 2021-12-11 12-28-31](https://user-images.githubusercontent.com/3955499/145674995-1290419d-52ab-475f-acf5-c8c86497219b.png)

**Comment by Gr3q** [comment]
It's used in the old 3.0 version, that's why they are there.

I'm a bit wary removing that version altogether, but I can update the unused strings, like this one so it doesn't differ from the current one.

If you find any more, let me know.
