### ISSUE TITLE
weather@mockturl - Text is at an abnormal height

### ISSUE THREAD

**Issue by lunalucadou** [linuxmint/cinnamon-spices-applets#4127]
```
 * Applet version - 3.1.6
 * Cinnamon version - 5.0.7
 * Distribution - Linux 5.4.0-882110311031-generic 0 mediatree hauppauge-Ubuntu SMP Sat Nov 6 00:51:47 UTC 2021 x86_64 x86_64 GNU/Linux
 * Graphics hardware - 07:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070 Ti] rev a1
```

**Notify author of applet**
@Gr3q

**Issue**

The temperature in the taskbar starts slightly above the date/time and it's annoying.

**Steps to reproduce**

1. Put applet on taskbar
2. Drag it to be next to the time
3. Become unable to unsee this

**Expected behaviour**

The text should be on the same level as the date/time. At first I wondered if there was an "official" height for text on the taskbar, except QRedshift is at the same height as date/time, so I'm inclined to believe there is a regular height to put text at.

**Other information**

Screenshot:

![image](https://user-images.githubusercontent.com/22415965/146290162-99c93999-2a25-48cd-a335-03a50542326c.png)

**Comment by lunalucadou** [comment]
![image](https://user-images.githubusercontent.com/22415965/146290681-6197b478-70db-4e0a-8539-8dea8109d9a4.png)

The image from the [Spice page](https://cinnamon-spices.linuxmint.com/applets/view/17) has the opposite problem - the text is too low.

Interesitng.

**Comment by Gr3q** [comment]
I do have an idea why it could be happening, I think the temperature unit characters cause problems. Look at my Desktop's issue: https://github.com/linuxmint/cinnamon-spices-applets/issues/3985

Just to make sure, can you do a few tests for me?
* Go into Font Selection->Set "Hinting" to None to see if Hinting is the problem or not
* In the Applet settings, edit to Presentation->Override label on panel. The rules for it are in the tooltip. Can you just enter normal text and every the combination of the available values? To see if only one of them is the culprit, or it doesn't make a difference.

Either way, this is most likely not a problem with the Applet itself but something with Cinnamon and text rendering, but I would have to investigate it further what the underlying issue is.

**Comment by Gr3q** [comment]
Also double check the font you are using, maybe it's missing the temperature unit characters and rendering silently falls back to a different font.

**Comment by lunalucadou** [comment]
Disabling font hinting did not change anything.

However, I found some interesting things when messing around with the presentation settings, hinting still set to none (however, it behaves the same regardless of the hinting setting).

Just weather conditions (aligned):

![image](https://user-images.githubusercontent.com/22415965/146405108-777b59af-c742-45c5-bcba-e449b7ff9712.png)

Weather conditions and temperature (misaligned like temperature-only):

![image](https://user-images.githubusercontent.com/22415965/146405403-83dc93d6-da7e-4056-87ff-2310f4608d4d.png)

Override label (aligned):

![image](https://user-images.githubusercontent.com/22415965/146405611-69fdbf46-8061-4bfb-9210-4cd0449a36c5.png)

My fonts (haven't changed them from their defaults):

![image](https://user-images.githubusercontent.com/22415965/146406108-c9014670-3be3-4c17-94ef-86bdf71812a4.png)

**Comment by lunalucadou** [comment]
![image](https://user-images.githubusercontent.com/22415965/146406924-d5aeb8d9-599d-41ed-988b-c5bc668a5f3d.png)

Interestingly, if I put the degree symbol (° U+00B0) in the label override, it's aligned.

**Comment by Gr3q** [comment]
https://www.compart.com/en/unicode/U+00B0 is not the same as https://www.compart.com/en/unicode/U+2109, which the applet is using.

that character is not in your font, so it is falling back to some other font, which has that character (and a different height)

**Comment by lunalucadou** [comment]
![image](https://user-images.githubusercontent.com/22415965/146561157-c7f91884-e15e-4bc0-a35b-bceac30f453e.png)

Sure enough, when I put U+2109 into it, it renders differently. I think it's falling back to DejaVu Sans:

![image](https://user-images.githubusercontent.com/22415965/146564296-febefa1d-71c4-454f-a84f-febf98c17f86.png)

U+00B0 is present in many more fonts than U+2109 and U+2103 (that said, U+2103 is present in more fonts than U+2109 for some reason), so the simplest fix might be to use U+00B0 and U+0046/U+0043.
