### ISSUE TITLE
weather@mockturl - A translated text appears in english inste

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#4135]
```
 * Applet version - 3.1.7
 * Cinnamon version - 5.0.7
 * Distribution - Linux Mint Cinnamon 20.2
```

**Notify author of applet**
@Gr3q

**Issue**

**Save to File** is translated in fr.po file but it still appers in english:

![Capture d’écran du 2021-12-18 00-25-17](https://user-images.githubusercontent.com/3955499/146619024-bc39eb48-3ade-4e73-a084-feefcdc33218.png)

![Capture d’écran du 2021-12-18 00-25-42](https://user-images.githubusercontent.com/3955499/146619039-485cb016-a4cb-4047-89d6-5022cfcd7fcb.png)

Or I missed something...

**Comment by haggen88** [comment]
@InfoLibre   -  #4136 duplicate

**Comment by Gr3q** [comment]
@brownsr this can be closed, it is a duplicate

**Comment by InfoLibre** [comment]
It appears translated now.
