### ISSUE TITLE
weather@mockturl - A translated text is displayed in english instead of french

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#4136]
```
 * Applet version - 3.1.7
 * Cinnamon version - 5.0.7
 * Distribution - Linux Mint Cinnamon 20.2
```

**Notify author of applet**
@Gr3q

**Issue**

**Save to File** is translated in fr.po file but it still appears in english:

![Capture d’écran du 2021-12-18 00-25-17](https://user-images.githubusercontent.com/3955499/146619024-bc39eb48-3ade-4e73-a084-feefcdc33218.png)

![Capture d’écran du 2021-12-18 00-25-42](https://user-images.githubusercontent.com/3955499/146619039-485cb016-a4cb-4047-89d6-5022cfcd7fcb.png)

Or I missed something...

**Comment by jorgenqv** [comment]
Confirming that the same goes using Swedish, also checked some other languages.

**Comment by haggen88** [comment]
The same is true for the Spanish translation
![Captura de pantalla de 2021-12-19 12-12-40](https://user-images.githubusercontent.com/68134588/146680205-e13c1e20-e14b-4825-aecf-b0d9afc39585.png)

**Comment by Gr3q** [comment]
Yes, I will fix that shortly.

**Comment by InfoLibre** [comment]
:+1: :1st_place_medal: :dancers: :tada: :v: :zany_face: :partying_face: :sun_with_face: :smiling_face_with_three_hearts: :smile: :smiley: :grinning: :laughing:
