### ISSUE TITLE
weather@mockturl - First letter of the name of the weekday is shown in lower case.

### ISSUE THREAD

**Issue by haggen88** [linuxmint/cinnamon-spices-applets#4147]
```
 * Applet version: 3.1.7
 * Cinnamon version: 5.0.7
 * Distribution: Mint 20.2
 ```
@Gr3q

**Issue**
As the title indicates the first letter of the name of the weekdays is shown in lower case. I checked the translation file [in this case Spanish], and the lines appear correctly translated.

>#: 3.0/utils.js:204
msgid "Monday"
msgstr "Lunes"

>#: 3.0/utils.js:204
msgid "Tuesday"
msgstr "Martes"

>#: 3.0/utils.js:204
msgid "Wednesday"
msgstr "Miércoles"

>#: 3.0/utils.js:204
msgid "Thursday"
msgstr "Jueves"

>#: 3.0/utils.js:204
msgid "Friday"
msgstr "Viernes"

>#: 3.0/utils.js:204
msgid "Saturday"
msgstr "Sábado"

![weather@mockturtl](https://user-images.githubusercontent.com/68134588/146683879-62d56509-6475-4df9-a9a4-29f3b9e8ff6b.png)

**Comment by Gr3q** [comment]
I get those straight from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString.

It seems that is the official representation of days (according to MDN, anyway).

I'll add some code to always try to capitalize them, int his case it will work.
