### ISSUE TITLE
batterypower@joka42 no such device

### ISSUE THREAD

**Issue by wennaspeedy** [linuxmint/cinnamon-spices-applets#4195]
```
error t=2021-12-31T15:23:01Z Failed to read from file “/sys/class/power_supply/BAT0/current_now”: No such device
error t=2021-12-31T15:23:01Z 
[batterypower@joka42]: Applet batterypower@joka42: Could not create applet object.
[batterypower@joka42]: Error importing applet.js from batterypower@joka42
```

After reboot.

**Comment by fredcw** [comment]
Ping @joka42

**Comment by joka42** [comment]
@wennaspeedy thanks for reporting the issue!

Has it worked after installing the applet? Does the error also occur when you restart cinnamon when the system is already up and running (`Alt+F2` then `r` and enter)?

**Comment by wennaspeedy** [comment]
> 

Yes, it worked after installing and works after restart cinnamon.

**Comment by joka42** [comment]
@wennaspeedy the merge request should fix it, can you confirm?

**Comment by wennaspeedy** [comment]
> @wennaspeedy the merge request should fix it, can you confirm?

It seems ok. Thanks.
