### ISSUE TITLE
weather@mockturl - X server is crashing when updating+restarting Cinnamon

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#4200]
```
 * Applet version - Version 3.1.8 (2022-01-03 09:10:11)
 * Cinnamon version - 5.0.7
 * Distribution - Linux 5.4.0-91-generic 102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 GNU/Linux
 * Graphics hardware - 05:00.0 VGA compatible controller: NVIDIA Corporation GK107GL [Quadro K2000] rev a1
```

**Notify author of applet**
@Gr3q

**Issue**

Sometimes, my X server freezes. Mouse cursor doesn't move and no more keys work on my keyboard, excepted magic keys.

I'm not sure, but it seems to be when Weather applet is updated and Cinnamon restarted at the end of the update.

How could I debut this? I find nothing in /var/log files.

**Comment by Gr3q** [comment]
Enable Debug logs in the applet, and the logs should be in `~/.cinnamon/glass.log` to see when it's going wrong

**Comment by InfoLibre** [comment]
Thank you for your help.
