### ISSUE TITLE
MPV opens

### ISSUE THREAD

**Issue by bamper45** [linuxmint/cinnamon-spices-applets#4201]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
When you click on the play, the MPV player opens and plays on it.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by jonath92** [comment]
@bamper45 I guess you are referring to the radio-applet? In that case you should notify me with `@jonath92` as otherwise I don't get informed automatically. 

Apart form this I don't  understand what you mean. Can you please provide the steps (as exact as possible) necessary to reproduce the issues? Thanks

**Comment by bamper45** [comment]
@jonath92
Ok, I didn't know.
  Yes, the mpv player literally opens and playback is in progress. I don’t know how to send a report in detail if you don’t send a screen recording

**Comment by jonath92** [comment]
@bamper45 sorry but I still don't understand what you mean. Yes you can also send a screen recording. I need to know which steps you executed, what actually happens and what result you expected. If you have language problems,  just use deepl.com (awesome tool).

**Comment by bamper45** [comment]
@jonath92
I just press play, mpv opens and playback is in progress.
  In my system, mpv is used by default for video, m3u, m3u8 like. But this shouldn't lead to this
  
Screen recording:  https://streamable.com/koiarm@jonath92

**Comment by jonath92** [comment]
ok that's interesting. You are right that shouldn't happen. Thanks for reporting. I have some ideas how to fix it but unfortunately I can't test as haven' (yet) found a way to reproduce it. @bamper45 can you please try the following: 

1. Stop mpv (e.g by running  `pkill mpv`in the terminal)
2. Run `mpv http://live.antenne.at/arr --config=no` in the terminal. 

Please let me know if this starts mpv without user interface?

**Comment by bamper45** [comment]
Yes, it started
![2022-01-03_23-36](https://user-images.githubusercontent.com/77186394/147967025-f0e41209-20af-4341-9057-adab6523cd60.png)

**Comment by jonath92** [comment]
ok perfect. I opened now a PR which will fix that.
