### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: memory pie chart also includes swap use

### ISSUE THREAD

**Issue by MauroFoti** [linuxmint/cinnamon-spices-applets#4227]
```
 * Applet version/Build date: 1.8.91 (2021-12-26 16:22:03)
 * Cinnamon version: 4.8.6 and 5.0.7
 * Distribution: Mint 20.1 and Mint 20.2
 ```

**Notify author of applet**
@jaszhix 

**Issue**
The pie chart, that measures memory usage, also includes swap in the total memory, even though swap is supposed to be measured by a vertical bar in the background. As a result, it is quite difficult to estimate how much physical memory is actually free.

For example, in a system with 4GiB of physical memory and 4GiB of swap, assuming a ram consumption of 2GiB, 1/4 of the pie chart will be red, instead of the supposed 1/2. If in this system, 5GiB of ram were occupied (4GiB physical + 1GiB swap), the pie char would be red for only 5/4, while there would be a 1/4 full vertical bar in the background. This would misrepresent the actual memory situation in the system.

**Steps to reproduce**
Just measure the proportions of occupied ram in system monitor compared to the portion of the pie char in red

**Expected behaviour**
The pie chart should only display the amount of physical memory. With the same system as above, 2GiB of occupied memory would mean a 1/2 red pie chart and no vertical background, while 5GiB of occupied memory would mean a full red pie chart and 1/4 vertical bar in the background

**Other information**

**Comment by fredcw** [comment]
I can't reproduce this. I have 8GiB of mem and 4GiB of swap file and it seems to be reporting the percentages accurately based on 8GiB of memory only. I had a look at the code and it doesn't appear to be adding the mem and swap together in the applet. I could be something to do with libgtop library that the applet uses though.
Does the pie chart match the figures (percentages) in the tooltip?

**Comment by MauroFoti** [comment]
![](https://user-images.githubusercontent.com/42967448/153309615-fcf63bdc-b509-449c-8ea6-8f151da2ef08.png)
![](https://user-images.githubusercontent.com/42967448/153309635-824248b1-c81e-4538-a40f-f8edfdbf7dd5.png)

As you can see, occupied memory is 28.9%, but on the chart it shows as a lower percentage (~25%).
Why it does not add up the total and swap memory is weird, it also seems to not replicate well

**Comment by fredcw** [comment]
It seems that this applet matches the values given by System Monitor applet (sysmonitor@orrus) and the commands `free` & `top`. So I guess it's just gnome system monitor that has the wrong values.
