### ISSUE TITLE
[radio@driglu4it] - Popup Menu not opening

### ISSUE THREAD

**Issue by jonath92** [linuxmint/cinnamon-spices-applets#4243]
Hi @pomponfrais, 

I am answering here because here code blocks are getting formatted. Sorry for the delay but I didn't have much time this week. First of all there is a serious bug in the current version which might be the reason for the popup menu not opening. I have provided a fix for that but unfortunately it hasn't get merged yet. You can install it manually with the following: 

```
git clone git@github.com:linuxmint/cinnamon-spices-applets.git
cd cinnamon-spices-applets
git fetch origin pull/4238/head:pr4238
git checkout pr4238
rm -rf ~/.local/share/cinnamon/applets/radio@driglu4it
cp -r ./radio@driglu4it/files/radio@driglu4it/ ~/.local/share/cinnamon/applets
```
Afterwards you need to restart cinnamon. If the radio still doesn't work it might be a Manjaro specific problem. Some Manjaro users have reported some problems with the applet a couple of months ago but the root of the problem hasn't yet been figured out unfortunately (I was not able to reproduce this on a clean Manjaro install). In that case you should be able to start the applet by commenting out the line `5477` of this file: `~/.local/share/cinnamon/applets/radio@driglu4it/4.6/radio-applet.js`, i.e. the line should afterwards look  the following: 

``` 
            //await installMpvWithMpris();
```

I am really sorry for the Bug and things like that obviously shouldn't happen but a lot of things in cinnamon are much more complex as you expect (and as they should). I am trying my best to prevent such bugs but unfortunately that still can happen from time to time. 

Please let me know how it went at if you had to comment out line 5477 because in that case we need to further communicate to find a more persistent solution (the changed file will be replaced at the next update again).

**Comment by 2play** [comment]
HI @jonath92 
I dont see the stop pause etc
MPV keeps opening sessions/streams on top of last one
I have:
Applet v2.0.4 (14.03.2022)
Ubuntu 20.04.4 LTS

mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.4-1ubuntu0.1

mpv-mpris_0.6-2_arm64.deb

![image](https://user-images.githubusercontent.com/30235736/163693875-c2a58f22-ee9d-4352-97d0-2861da613298.png)

**Comment by jonath92** [comment]
@2play This looks for me like an issue with the mpris plugin. What are the first couple of lines when you run this command: ` mpv --config=no --no-video --script=~/.cinnamon/configs/radio@driglu4it/.mpris.so http://62.210.105.16:7000/stream`?

**Comment by 2play** [comment]
> @2play This looks for me like an issue with the mpris plugin. What are the first couple of lines when you run this command: ` mpv --config=no --no-video --script=~/.cinnamon/configs/radio@driglu4it/.mpris.so http://62.210.105.16:7000/stream`?

hi @jonath92 
Thank you for your reply!
I was reading your git readme and in the known issues i read that default mpris plug in is for x86 atchitecture so I compiled th plug in on my linux arm board and your applet is working great as it should!
thank you again for your reply!
