### ISSUE TITLE
weather@mockturl - 

### ISSUE THREAD

**Issue by quamok** [linuxmint/cinnamon-spices-applets#4255]
```
 * Applet version - 3.2.0
 * Cinnamon version - 5.2.7
 * Distribution - Linux 5.4.0-97-generic 110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 GNU/Linux
 * Graphics hardware - 01:00.0 VGA compatible controller: NVIDIA Corporation TU104 [GeForce RTX 2060] rev a1
```

**Notify author of applet**
@Gr3q

**Issue**

Weather is not updating automatically. Updating manually works fine.

**Steps to reproduce**

run applet. let it run for an hour, then check the time "as of hh:mm" on the bottom left, and the time and weather hasn't updated.

**Expected behaviour**
weather refreshes automatically.

**Other information**

log file
[weather.log](https://github.com/linuxmint/cinnamon-spices-applets/files/8028752/weather.log)

**Comment by Gr3q** [comment]
It seems the library that detects your internet connectivity does not detect you have full internet access.

```javascript
* The host's network connectivity state, as reported by #GNetworkMonitor.
*/
enum NetworkConnectivity {
/**
* The host is not configured with a
*   route to the Internet; it may or may not be connected to a local
*   network.
*/
LOCAL = 1,
/**
* The host is connected to a network, but
*   does not appear to be able to reach the full Internet, perhaps
*   due to upstream network problems.
*/
LIMITED = 2,
/**
* The host is behind a captive portal and
*   cannot reach the full Internet.
*/
PORTAL = 3,
/**
* The host is connected to a network, and
*   appears to be able to reach the full Internet.
*/
FULL = 4
}
```

It detects it as one of these except full (I did not setup logging for your value), do you have some special network configuration what would map to one of those?

Nevertheless I plan to change detection to be more permissive.

Also, good decision to redact more stuff in the config section of the log, I should have done that for location as well not just for API keys.

**Comment by Gr3q** [comment]
The workaround until an update is push would be 
1. you opening the file `~/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js`
2. looking for the line `this.loop.Pause();` around this code:
   ```javascript
   case NetworkConnectivity.PORTAL:
      if (this.online === false)
          break;
      logger_Logger.Info("Internet access now down, pausing refresh.");
      this.loop.Pause();
      this.online = false;
      break;
   ```
3. Comment out mentioned line by prepending it with `//`
4. Restart Cinnamon

This would stop the applet pausing refresh.

If you feel adventurous, you can also add an extra line logging your connectivity state right below your edited line to see witch one you get:
`global.log(NetworkMonitor.get_default().connectivity)`

**Comment by quamok** [comment]
thank you, after I've made the modifications you've suggested, it's now updating again:)
