### ISSUE TITLE
Feature Request: Center screen position

### ISSUE THREAD

**Issue by henriquebach** [linuxmint/cinnamon-spices-applets#4256]
Hello, I would like to ask a feauture to set the position of the menu to be horizontally centered, just like the Windows 11 menu.
The current behavior is the menu is centered from the menu icon, as shown in the images bellow:
![CurrentBehavior](https://user-images.githubusercontent.com/77576600/153319950-723fb494-7fe5-4fe7-a9a5-cb2b8531bc94.png)
![DesiredBehavior](https://user-images.githubusercontent.com/77576600/153319958-9eee97d2-6dc1-499e-8145-a5885ae22421.png)

**Comment by jonath92** [comment]
@fredcw

**Comment by fredcw** [comment]
Hi, the position is calculated automatically by cinnamon. I think there's a way to override this but it may take me a while to figure out how to do it.

**Comment by henriquebach** [comment]
> Hi, the position is calculated automatically by cinnamon. I think there's a way to override this but it may take me a while to figure out how to do it.

Thank you for consider this feature.
