### ISSUE TITLE
Cinnamenu@json - using search sometimes leads to X11 crash

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon-spices-applets#4278]
```
 * Applet version/Build date: Version 4.15.3 (2022-02-28 07:43:41)
 * Cinnamon version: 5.2.7
 * Distribution - Mint 20.3
 * Graphics:  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
           Device-2: Realtek Integrated_Webcam_HD type: USB driver: uvcvideo
           Display: x11 server: X.Org 1.20.13 driver: loaded: modesetting unloaded: fbdev,vesa
           resolution: 1920x1080~60Hz
           OpenGL: renderer: Mesa Intel UHD Graphics 620 (WHL GT2) v: 4.6 Mesa 21.2.6
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@fredcw 

**Issue**
Hi,

Been having this issue for a little while - intermittent, but fairly frequent (i.e most days) locking up of the display server triggered by using the search function in Cinnamenu - the display is frozen with the search results partially populated. Recovery is via Ctrl-Alt-Backspace to kill the session. No particular search string implicated, although I get it most often with searches for 'synaptic' or it's partial string, but I think that's just coincidence as I search for synaptic frequently.

xsession-errors.old is huge on checking after recovery - over 3 million lines.

This section corresponds with the initial crash

https://pastebin.com/4RrQs8Gu

The last two entries then repeat add-infinitum every millisecond or so until I kill the xserver

https://pastebin.com/Bj2uEsbW

Nothing relevant in syslog other than entries related to me killing X11.

Cinnamenu config.

https://pastebin.com/PjVLnfmv

As I've got browser history and bookmarks search enabled - browsers installed are Chrome and Firefox. 

**Steps to reproduce**
 Use the search function

**Expected behaviour**
No lock up.

**Other information**

I'm going to test for a few days with the browser search functions disabled - just a hunch that that might be related.

**Comment by fredcw** [comment]
Hi, I can't reproduce this bug, bookmarks search seems to working ok for me. You say you have browser history search enabled, is this a customised version of the search provider located at github cinnamon/docs/search-providers-examples/chromium-history@cinnamon.org/ ? I can't seem to get this to work.

**Comment by smurphos** [comment]
Hi fredcw - sorry I haven't got browser history search enabled (or any other search-provider) - just double checked. To be sure I've removed all the old search provider definitions I've collected over the years from ~/.local/share/cinnamon/search_providers

**Comment by fredcw** [comment]
hmm, still an odd bug though. I've installed some search providers with them not enabled and I'll see if I can reproduce it.

**Comment by smurphos** [comment]
I'm still getting this problem - albeit more rarely - a couple of times in the last week...

Snip from .xsession-errors.old - the last two lines then repeat at sub millisecond intervals until I kill the X-server.
...
(cinnamon:1651): St-CRITICAL **: 07:04:55.786: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed

(cinnamon:1651): St-CRITICAL **: 07:04:55.786: cr_declaration_parse_list_from_buf: assertion 'parser' failed

(cinnamon:1651): St-CRITICAL **: 07:04:55.787: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed

(cinnamon:1651): St-CRITICAL **: 07:04:55.787: cr_declaration_parse_list_from_buf: assertion 'parser' failed

(cinnamon:1651): St-CRITICAL **: 07:04:55.828: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed

(cinnamon:1651): St-CRITICAL **: 07:04:55.828: cr_declaration_parse_list_from_buf: assertion 'parser' failed

(cinnamon:1651): St-CRITICAL **: 07:04:59.327: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed

(cinnamon:1651): St-CRITICAL **: 07:04:59.327: cr_declaration_parse_list_from_buf: assertion 'parser' failed

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: The offending callback was AsyncReadyCallback().
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: The offending callback was AsyncReadyCallback().
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: The offending callback was AsyncReadyCallback().
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: The offending callback was AsyncReadyCallback().
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: The offending signal was captured-event on ClutterStage 0x5565602bddd0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: The offending signal was captured-event on ClutterStage 0x5565602bddd0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: The offending signal was get-preferred-width on CinnamonGenericContainer 0x556560b323d0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: The offending signal was get-preferred-height on CinnamonGenericContainer 0x556560b323d0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.721: The offending signal was allocate on CinnamonGenericContainer 0x556560b323d0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.722: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.722: The offending signal was captured-event on ClutterStage 0x5565602bddd0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.722: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.722: The offending signal was captured-event on ClutterStage 0x5565602bddd0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: The offending signal was leave-event on StBin 0x5565631ddf60.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: The offending signal was leave-event on ClutterStage 0x5565602bddd0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: The offending signal was captured-event on ClutterStage 0x5565602bddd0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: The offending signal was captured-event on ClutterStage 0x5565602bddd0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: The offending signal was enter-event on ClutterStage 0x5565602bddd0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: The offending signal was captured-event on ClutterStage 0x5565602bddd0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: The offending signal was captured-event on ClutterStage 0x5565602bddd0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.723: The offending signal was motion-event on StBin 0x5565631ddf60.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.731: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.731: The offending signal was captured-event on ClutterStage 0x5565602bddd0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.731: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.731: The offending signal was captured-event on ClutterStage 0x5565602bddd0.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.731: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.731: The offending signal was motion-event on StBin 0x5565631ddf60.
== Stack trace for context 0x55655ffbe130 ==

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.731: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.

(cinnamon:1651): Cjs-CRITICAL **: 07:05:00.731: The offending callback was SourceFunc().
== Stack trace for context 0x55655ffbe130 ==
...

**Comment by fredcw** [comment]
@smurphos This looks like the same bug was causing cinnamon to crash when I first made the menu resizable. https://github.com/linuxmint/cinnamon/issues/9920 I fixed it by using a custom version (without the settings file monitor) of usr/share/cinnamon/js/ui/settings with cinnamenu. It was also mitigated with https://github.com/linuxmint/cjs/pull/97 However, AFAIK no applet settings are changed during a search, not that that should make a difference anyway. I'm at a bit of a loss to know what this could be. I'll have another look later.

**Comment by fredcw** [comment]
@smurphos Could you try turning off the "Search home folder" option on the search tab for a while to see if that fixes it. I don't know what else it might be.

**Comment by smurphos** [comment]
So no instances of this since disabling home search a couple of weeks ago. I've turned it back on today will report back if/when I get a freeze.

**Comment by smurphos** [comment]
OK, no freezes since I turned home search back on. Issue closed again, hopefully for good...

**Comment by fredcw** [comment]
You were right, searching still led to occasional system freezes. Pretty sure I've fixed it this time. PR submitted.
