### ISSUE TITLE
SpicesUpdate@claudiux Docker Compose makes Spices Update Applet run and break Cinnamon

### ISSUE THREAD

**Issue by indicozy** [linuxmint/cinnamon-spices-applets#4283]
```
 * Applet version/Build date - Version 6.3.1
 * Cinnamon version Cinnamon 4.8.6
 * Distribution - Debian 11
 * Graphics hardware *and* driver used - AMD 3 5500U, amdgpu
 * Snippet or attachment of ~/.cinnamon/glass.log - No such file
 * Snippet or attachment of ~/.xsession-errors - https://gist.github.com/indicozy/06fcd33f9b52c66a056810076328fc83

 ```

**Notify author of applet**
@claudiux 

**Issue**
When I run docker-compose with building dockerfile, Spices update applets shows that it's updating or so and in about every 4-5 docker-compose runs it breaks cinnamon

**Steps to reproduce**
1. Install docker and docker-compose via official documentation
2. run docker-compose (with dockerfile build in my instance) several times with `docker compose up -d --no-deps --build compiler`
3. watch applet to turn on "updating, loading" swirling icon every time I build docker-compose
4. watch Cinnamon to crash

**Expected behaviour**
Applet not breaking Cinnamon

**Other information**
I use latest linux via debian packports - `5.16.0-0.bpo.4-amd64`

**Comment by claudiux** [comment]
@indicozy 
Can you retry with SpicesUpdate v6.4.0, please?
