### ISSUE TITLE
weather@mockturl - status shows unexpected distance when manual location is set

### ISSUE THREAD

**Issue by grauerfuchs** [linuxmint/cinnamon-spices-applets#4285]
```
 * Applet version - 3.2.1
 * Cinnamon version - 5.2.7
 * Distribution - Linux 5.13.0-37-generic 42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 GNU/Linux

```

**Notify author of applet**
@Gr3q

**Issue**
On the version of the weather applet listed above, the pop-up window's status bar will show improper and confusing distance "from you" values when a manual location is set.

**Steps to reproduce**
Load the applet. Specify a manual location. Open the pop-up and look at the distance "from you" listed on the status bar.
The status bar appears to show the difference between the automatically calculated location vs. the manually specified location. However, at least where I am, the automatically calculated location is very much incorrect.

**Expected behaviour**
If a manual location is specified, I expect the "%.1f %s from you" text to read 0.0 or to not appear.  If this is not the intended appearance, maybe provide an option to disable the display text?

**Comment by Gr3q** [comment]
Hi, 

That text refers to the weather data, not your provided location.

Meaning the data shown is coming from an observation station "%.1f %s from you"

**Comment by grauerfuchs** [comment]
Ahh, understood. Is there a concise way to make it more obvious that this is the intent of showing the distance? At least in the English version, it makes it a bit confusing. For instance, maybe something along the lines of "As of %s, conditions recorded %.1f %s from you"?

**Comment by Gr3q** [comment]
If you come up with something relatively short and better then the current one, I'm happy to change it.

Alternatively I can add a tooltip shown on hover with some additional information

**Comment by grauerfuchs** [comment]
A hover tooltip might be more valuable, especially if the conditions report includes the name and location of the reporting station. With such a detail, you could shorten the text even further to show only the reporting time and a symbol indicating there is a tooltip available. The tooltip could then show reporting station details and distance from the selected location.

**Comment by Gr3q** [comment]
I'll start working on it when I've got some time

**Comment by grauerfuchs** [comment]
Thank you very much.

Would you prefer this issue remain open, or would you prefer it closed?

**Comment by Gr3q** [comment]
Leave it open, I'll reference it when I've fixed it
