### ISSUE TITLE
weather@mockturl - Add ability to scroll left and right via the scroll wheel when viewing the hourly weather view for a current day.

### ISSUE THREAD

**Issue by linusrg1** [linuxmint/cinnamon-spices-applets#4292]
```
 * Applet version - 3.2.1
 * Cinnamon version - 5.2.7
 * Distribution - Linux 5.13.0-37-generic 42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 GNU/Linux
 * Graphics hardware - 06:00.0 VGA compatible controller: NVIDIA Corporation TU116 [GeForce GTX 1660 SUPER] rev a1
```

**Notify author of applet**
@Gr3q

**Issue**
Right now I cannot seem to scroll up and down on the scrollwhell to scroll left and right on the hourly weather view. It would be cool if this could be done. 

**Steps to reproduce**
Click on the today/day of the week you would like to view the hourly weather for
Try scrolling through the hourly weather with scroll wheel 
It doent function

**Expected behaviour**
To be able to scroll through the hourly weather view via the scrollwheel

**Comment by Gr3q** [comment]
Hi, I'll add it in the next update

**Comment by linusrg1** [comment]
> Hi, I'll add it in the next update

It works great. Thanks!
