### ISSUE TITLE
Cinnamenu@json Unable to drag and drop items to taskbar in Cinnamenu

### ISSUE THREAD

**Issue by linusrg1** [linuxmint/cinnamon-spices-applets#4300]
```
 Applet Version 4.15.5
 Cinnamon 5.2.7
 Linux Mint 20.3
 Nvidia driver version 470.103.01
 * Snippet or attachment of ~/.cinnamon/glass.log (Not found)
 * Snippet or attachment of ~/.xsession-errors (too long)

 ```

**Notify author of applet**
@fredcw 

**Issue**
I cannot drag items from the menu to the panel when I try to is simply does not get pinned.

**Steps to reproduce**
Drag item from menu to panel to pin it 
Item does not get pinned 

**Expected behaviour**
Drag item to panel 
Item gets pinned

**Comment by fredcw** [comment]
@linusrg1 Thanks for reporting. I'll have a fix ASAP.

**Comment by linusrg1** [comment]
> @linusrg1 Thanks for reporting. I'll have a fix ASAP.

thx! Sorry for reporting so much on this applet. Its my favourite cinnamon menu, so I just feel like I should report on potential improvments.

**Comment by fredcw** [comment]
No, not at all. I really appreciate it. I obviously want people to like the applet and find it useful so it's very helpful when people report bugs. Cinnamenu is what it is because of the feedback and suggestions I get.

**Comment by linusrg1** [comment]
> No, not at all. I really appreciate it. I obviously want people to like the applet and find it useful so it's very helpful when people report bugs. Cinnamenu is what it is because of the feedback and suggestions I get.

Alright!
