### ISSUE TITLE
weather@mockturl: wrong use of JS function

### ISSUE THREAD

**Issue by Drugwash2** [linuxmint/cinnamon-spices-applets#4306]
weather@mockturl

```
 * Applet version/Build date 3.2.2
 * Cinnamon version 4.2.4
 * Distribution Mint 19.2
 * Graphics hardware *and* driver used NVIDIA GT218M [GeForce 310M] / nvidia v340.108
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@Gr3q

**Issue**
Applet errors out continuously due to incorrect usage of a JS function: set_markup().
```
Cjs-Message: 21:05:01.402: JS LOG: [LookingGlass/error] [weather@mockturtl#115]: Generic Error while refreshing Weather info: TypeError: _d.set_markup is not a function, 
Cjs-Message: 21:05:01.403: JS LOG: [LookingGlass/error] Display@/home/dragos/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:15262:75
Display@/home/dragos/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:15425:9
RefreshWeather@/home/dragos/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:15833:18
Cjs-Message: 21:05:01.576: JS LOG: [LookingGlass/error] [weather@mockturtl#115]: Retrying in the next 285 seconds...
```

**Steps to reproduce**
Enable applet, set everything properly, watch panel showing 'Error'.

**Expected behaviour**
Display conditions and all configured info in tooltip.

**Other information**
Fix for the issue:
in weather-applet.js, line 15262
```
-        (_d = this.timestampTooltip) === null || _d === void 0 ? void 0 : _d.set_markup(tooltipText);
+       (_d = this.timestampTooltip) === null || _d === void 0 ? void 0 : _d._tooltip.get_clutter_text().set_markup(tooltipText);
```

**Comment by Gr3q** [comment]
It seems that function is particularly new in `...cinnamon/js/ui/tooltips.js`. I don't need markup so I can use `set_text` instead (I'm not even using markup...)

I'll fix it very soon

**Comment by Drugwash2** [comment]
It probably is kind of a shortcut to previous version, most likely due to the announced? retirement of the Clutter library.
Markup may be used at some point so it shouldn't be discarded on a whim; rather use a try/catch for the two versions of that particular line, so that users of both old and new JS libraries could benefit.
Or, more elegantly, define a local function based on such try/catch and use that in any and all other places that may at some point benefit from markup text.

**Comment by Gr3q** [comment]
Clutter is retiring, but in Gnome/GTK4. Cinnamon uses early version of there libraries and probably keep using them for a while. In this case the library in question is Cinnamon's (Tooltips implemented in JS).

For now I'm going to just use `set_text`, because the moment I want to use markup I probably need to re-implement Cinnamons tooltip because it lacks certain features (like better positioning) that currently prevents me to use multiline tooltips without risking text cutoff on y axis

**Comment by Drugwash2** [comment]
To me it looks like Cinnamon is already preparing for the upcoming Clutter retirement since they modified their tooltip library.
Anyhow, there are two options for the future:
**1.** build separate scripts for different Cinnamon versions
**2.** Use a single script with local functions

I just cooked such local function and it seems to work fine here:
```
function setTTMarkup(obj, txt) {
	try { obj.set_markup(txt); global.log("Used new version of 'set_markup()'"); }
	catch(e) { obj._tooltip.get_clutter_text().set_markup(txt); global.logWarning("Used old Clutter-based version of set_markup()"); }

 (_d = this.timestampTooltip) === null || _d === void 0 ? void 0 : setTTMarkup(_d, tooltipText);
```
If/when time comes to reimplement the entire tooltips library you'd already have a helper function. At least that's my point of view.

**Comment by bananawana** [comment]
Now you made people on Mint 19 have to go outside to check the weather. :clap:

**Comment by C3x64** [comment]
> Now you made people on Mint 19 have to go outside to check the weather. clap

LOOOOOL

**Comment by Gr3q** [comment]
Please see #4306

**Comment by Drugwash2** [comment]
> Please see #4306

You probably meant to post this in #4312 :-)

**Comment by Gr3q** [comment]
Indeed
