### ISSUE TITLE
radio@driglu4it - YouTube should have also a capitalized T

### ISSUE THREAD

**Issue by sveinki** [linuxmint/cinnamon-spices-applets#4323]
radio@driglu4it: As the title says, YouTube should be written with a capitalized T - not Youtube - since this is a brand name.
I totally get it if this is not a priority, and it would be unhelpful if this correction would fuzzy 4 strings in all of the PO-files. But if you manage to change this without extra work for the translators, IMHO it should be done.

**Comment by fredcw** [comment]
Ping @jonath92

**Comment by jonath92** [comment]
I will include it in the next update.

**Comment by fredcw** [comment]
@jonath92 You could use the linux command line to replace all occurrences of "Youtube" in the po directory and update them all at once. `sed -i 's/Youtube/YouTube/g' *`
