### ISSUE TITLE
ScreenLocker@tuuxx applet icon resizes itself when cinnamon restarts or system restarts cinnamon 

### ISSUE THREAD

**Issue by adrummer354** [linuxmint/cinnamon-spices-applets#4339]
ScreenLocker@tuuxx applet icon resizes itself when cinnamon restarts or system restarts

```
 * [fe05d809](https://github.com/linuxmint/cinnamon-spices-applets/commits/master/ScreenLocker@tuuxx)
Cinnamon 5.2.7
Linux Mint 20.3 Una
 
PC Name:
description: Desktop Computer
product: Z390 AORUS PRO WIFI (Default string)
vendor: Gigabyte Technology Co., Ltd.
version: Default string
serial: Default string
width: 64 bits
capabilities: smbios-3.1.1 dmi-3.1.1 smp vsyscall32
configuration: boot=normal chassis=desktop family=Default string sku=Default string uuid=1802C003-4D04-3B05-9806-B80700080009
*-core
description: Motherboard
product: Z390 AORUS PRO WIFI-CF
vendor: Gigabyte Technology Co., Ltd.
physical id: 0
version: x.x
serial: Default string
slot: Default string
*-firmware
description: BIOS
vendor: American Megatrends Inc.
physical id: 0
version: F11
date: 10/15/2019
size: 64KiB
capacity: 16MiB
capabilities: pci upgrade shadowing cdboot bootselect socketedrom edd int13floppy1200 int13floppy720 int13floppy2880 int5printscreen int14serial int17printer acpi usb biosbootspecification uefi
*-memory
description: System Memory
physical id: 3a
slot: System board or motherboard
size: 16GiB
*-bank:0
description: [empty]
physical id: 0
slot: ChannelA-DIMM0
*-bank:1
description: DIMM DDR4 Synchronous 2133 MHz (0.5 ns)
product: F4-3200C16-8GVKB
vendor: Fujitsu
physical id: 1
serial: 00000000
slot: ChannelA-DIMM1
size: 8GiB
width: 64 bits
clock: 2133MHz (0.5ns)
*-bank:2
description: [empty]
physical id: 2
slot: ChannelB-DIMM0
*-bank:3
description: DIMM DDR4 Synchronous 2133 MHz (0.5 ns)
product: F4-3200C16-8GVKB
vendor: Fujitsu
physical id: 3
serial: 00000000
slot: ChannelB-DIMM1
size: 8GiB
width: 64 bits
clock: 2133MHz (0.5ns)
*-cache:0
description: L1 cache
physical id: 44
slot: L1 Cache
size: 512KiB
capacity: 512KiB
capabilities: synchronous internal write-back unified
configuration: level=1
*-cache:1
description: L2 cache
physical id: 45
slot: L2 Cache
size: 2MiB
capacity: 2MiB
capabilities: synchronous internal write-back unified
configuration: level=2
*-cache:2
description: L3 cache
physical id: 46
slot: L3 Cache
size: 12MiB
capacity: 12MiB
capabilities: synchronous internal write-back unified
configuration: level=3
*-cpu
description: CPU
product: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
vendor: Intel Corp.
physical id: 47
bus info: cpu@0
version: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
serial: To Be Filled By O.E.M.
slot: U3E1
size: 800MHz
capacity: 4900MHz
width: 64 bits
clock: 100MHz
*-pci
description: Host bridge
product: 8th/9th Gen Core 8-core Desktop Processor Host Bridge/DRAM Registers [Coffee Lake S]
vendor: Intel Corporation
physical id: 100
bus info: pci@0000:00:00.0
version: 0d
width: 32 bits
clock: 33MHz
configuration: driver=skl_uncore
resources: irq:0
*-pci:0
description: PCI bridge
product: 6th-10th Gen Core Processor PCIe Controller (x16)
vendor: Intel Corporation
physical id: 1
bus info: pci@0000:00:01.0
version: 0d
width: 32 bits
clock: 33MHz
capabilities: pci pm msi pciexpress normal_decode bus_master cap_list
configuration: driver=pcieport
resources: irq:121 ioport:3000(size=4096) memory:39000000-392fffff ioport:40000000(size=268435456)
*-display
description: VGA compatible controller
product: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
vendor: Advanced Micro Devices, Inc. [AMD/ATI]
physical id: 0
bus info: pci@0000:01:00.0
version: e7
width: 64 bits
clock: 33MHz
capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
configuration: driver=amdgpu latency=0
resources: irq:129 memory:40000000-4fffffff memory:39000000-391fffff ioport:3000(size=256) memory:39200000-3923ffff memory:c0000-dffff
*-multimedia

 ```

**Notify author of applet**
@tuuxx 

Issue

Restart Cinnamon by itself and/or restart PC to restart Cinnamon

I put the "screen locker" applet on my size 44 bottom panel and with this setting the screen locker applet matches the icon size of the others in that left zone which is set to 32 pixel icon size. When I restart cinnamon or restart the machine, that screen locker applet icon resizes itself automatically to a small about 16 pixel. I can get the screen locker icon back to it matching the size of rest by resizing the symbolic icon on the left from 32 to 34. I am not sure why it resizes itself but would like to avoid having to resize the symbolic icons there to get it to match the rest of those icons again.

https://imgur.com/a/Auk42wG

https://github.com/linuxmint/cinnamon-spices-applets/tree/master/ScreenLocker@tuuxx

**Comment by tuuxx** [comment]
#4354 Should fix this issue.

**Comment by adrummer354** [comment]
I can see this change but I am not sure what file on my system to make this change in your fix shows or how to apply it. I am fairly new to this.

**Comment by Drugwash2** [comment]
User-installed x-lets are found in `/home` under a hidden folder, so you may have to enable showing hidden files in Nemo first:
**Nemo menu > View > Show Hidden Files** or alternatively use the hotkey **Ctrl + H**.
 Then navigate to **~/.local/share/cinnamon/applets/ScreenLocker@tuuxx**, make a backup copy of **applet.js** (drag it a few pixels while keeping Ctrl pressed until the +/plus sign appears then release mouse button), then open **applet.js** in your favorite text editor.

You can then modify the required lines according to the pull request. Basically it's the same chunk of text to be pasted in six different places; you can see it marked with a darker green color (**, panelHeight, instance_id**) on the pull request page.

Save the file overwriting the existant one, then restart Cinnamon through **Ctrl +Alt + Esc** (easy way) or open Looking Glass, go to **Extensions** tab, find Screen Locker, right-click it and choose **Reload code** (hard way but avoids whole desktop restart).

Alternatively just wait until the pull request is being accepted and merged, then you'll be notified of the new applet version and go to update it the usual way.

**Comment by adrummer354** [comment]
I was able to apply this change and it is working now. Thank you.
