### ISSUE TITLE
[bluetooth-battery@zamszowy] Wishlist: Add notification warning about low battery

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#4345]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json"): Updated on 2022-05-17 21:16:22
 * Cinnamon version (cinnamon --version): Cinnamon 5.2.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Linux Mint 20.3 Cinnamon
 ```

**Notify author of applet**
@zamszowy 

This is not a bug report, but an item for the wishlist.

**Issue**

I really like this applet (and it makes one of my scripts obsolete) …

I would love to have a non-intrusive applet which nevertheless warns me, if the battery level of any device becomes (too) low. This it is how I imagine it:
- As soon as the battery level of any device falls below a (configurable) warning level, a notification message pops up.
- As soon as the battery level of any device falls below a (configurable) critical level, a notification message with the urgency `critical` pops up.
- It can be configured, if the icon shows, if the batteries of all devices are above the warning level.
- The notification messages only pop up once in one session.

Why would I want such a feature? At the moment I would need to monitor the battery level continuously, which distracts me. With such a warning feature, I could hide the icon to get a distraction free working environment, but still get a warning message to change/charge the battery. I admit that the icons were designed to help here, but I would very much prefer an active notification!

Do you think, that would be possible?

Best would be to have different notification/warning levels for different devices (You might want to charge the headphones earlier than changing the batteries on your mouse …), but that's already asking for too much!

**Comment by zamszowy** [comment]
@sphh sure, I will add such feature.

**Comment by sphh** [comment]
Oh, thanks!

**Comment by zamszowy** [comment]
@sphh I've added notifications in #4341 
I've considered implementing different notification levels for different devices, but in the end I've dropped the idea (sorry :-(), as this would require adding some local database functionality (to remember device and notification levels mapping across sessions) which would introduce whole lot of issues to deal with, and I don't want to overcomplicate this applet that much.

**Comment by sphh** [comment]
@zamszowy: Brilliant! Thanks. (Now I can finally retire that script of mine.)

I do understand, that adding a new database functionality is certainly an overkill. I only had this idea of configurable levels, because I saw this blacklist list and thought, that adding the two numbers would be easy:
```
Mouse 20 10
Headphone 35 20
```
but I just noticed, that this would disable monitoring those two devices, so that would not work.

**Comment by sphh** [comment]
@zamszowy: I should explain the reason behind the ‘warning only once’ feature: I noticed that the battery level sometimes oscillates around the warning value. Without the ‘warning only once’ feature, this would notify everytime, when the level falls after it has recovered. I obviously missed, that you could recharge or exchange the batteries (where I obviously want a new notification)!

Hence the idea is to have a sort of filter, filtering out the small changes around a warning level (warning only once), but keep the large changes after recharging …

**Comment by zamszowy** [comment]
@sphh okay, that makes sense. I'll see what I can do. :slightly_smiling_face:

**Comment by zamszowy** [comment]
@sphh I've finally added a change which adds option to filter small changes of battery level (#4373).
