### ISSUE TITLE
QRedshift qredshift@quintao applet does not run

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-applets#4347]
```
 * Applet version:  1.7.1
 * Cinnamon version:  5.2.7
 * Distribution -  Arch  5.17.9
 * Graphics hardware:  ATI Radeon
 * Snippet or attachment of ~/.cinnamon/glass.log  - Nothing relevant found.
 * Snippet or attachment of ~/.xsession-errors - Nothing relevant found.

 ```

**Notify author of applet**
qredshift@quintao .

**Issue**
Redshift installed. No redshift-gtk present.
Installed QRedshift  in Applets panel.
QRedshift listed in Manage has yellow ! warning. Configure button greyed out.
Checked metadata.json, versions listed up to 4.8.  Added 5.2. Restarted but no change.

**Steps to reproduce**
As above repeated several times.

**Expected behaviour**
Applet starts and can be configured.

**Other information**

**Comment by Padre2** [comment]
For reasons I have not determined, the applet now loads, can be configured and appears to be working properly, although the yellow ! warning still appears.

**Comment by Drugwash2** [comment]
Advice: make sure you have no other applets installed **and** enabled that have similar features, or there may appear inconsistencies. Known such applets are **Redshift** (in Spices repository) and **Applet PYE** (in the Mint forums).

The warning icon appears for any x-lets that use certain system APIs which can **potentially** cause problems. You shouldn't worry about these unless you do experience serious issues with the desktop, in which case disabling all such x-lets, then enabling them one by one and observing the behavior could help in pinpointing the culprit.

**Comment by Padre2** [comment]
@Drugwash2  Thank for the advice. I think the issues may have been caused when setting up and using Redshift before I installed the QRedshift applet. I don't seem to be having any issues with the applet now.
