### ISSUE TITLE
weather@mockturtl WeatherKit

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#4369]
Read on the DarkSky blog that they now is a part of Apple’s new WeatherKit API.
https://blog.darksky.net/
Is it interesting, or possible at all to use WeatherKit, or is it only for Apple thingies?
Saw something about any platform and REST API or am I lost here? :)
https://developer.apple.com/weatherkit/

Thanks!

@Gr3q

**Comment by Gr3q** [comment]
I doubt it will be usable by us, Apple has a tendency to lock in services to iOS

**Comment by jorgenqv** [comment]
Ah ok, agree it's probably so.
