### ISSUE TITLE
Integrate the data from DWD

### ISSUE THREAD

**Issue by wolfgang-58** [linuxmint/cinnamon-spices-applets#4378]
Good morning,
First of all, thank you for the great applet. I think you also have a lot of friends in Germany and it would be great if you could integrate the data from the DWD (German Weather Service). There's a really good API there: https://brightsky.dev/
I would be happy if you could consider that soon.
Many greetings
THANKS!
wolfgang

**Comment by fredcw** [comment]
Ping @Gr3q

**Comment by wolfgang-58** [comment]
Thanks, I didn't realize I was at the wrong address.
greeting
wolfgang

**Comment by Gr3q** [comment]
@wolfgang-58 this was the right place to request this.

**Comment by Gr3q** [comment]
I completed the integration, although I have not tested it with rural locations

**Comment by wolfgang-58** [comment]
Hi,
thank you very much for the new version. Will this soon be integrated into Mint as an applet update?
Have a nice day
wolfgang
greetings
