### ISSUE TITLE
Can't configure the applet

### ISSUE THREAD

**Issue by razi006** [linuxmint/cinnamon-spices-applets#4382]
```
 * Applet version/Build date Updated on 2022-06-07 17:26:49
 * Cinnamon version 5.2.7
 * Distribution - Linux Mint 20.3 Cinnamon
 * Graphics hardware *and* driver used

 ```

**Notify author of applet**
@slgobinath 
**Issue**
Dark mode applet is not letting me configure it. Whenever I'm clicking the configure option, it's not showing the usual window. 

**Steps to reproduce**
Right click the applet, click configure.

**Expected behaviour**

**Other information**

**Comment by fredcw** [comment]
@razi006 PR submitted.

**Comment by razi006** [comment]
The problem had been solved. But, after the update this morning, I am unable to configure the applet again.
