### ISSUE TITLE
Weather 3.25 does not work with LM 19.3

### ISSUE THREAD

**Issue by wolfgang-58** [linuxmint/cinnamon-spices-applets#4386]
Good morning,
Thank you for the update (3.25).
Unfortunately it doesn't work under LM19.3 Cinnamon under 20.3 everything is fine. The picture shows the correct update date but the wrong version.
Greetings Wolfgang
![Mo 4  Jul 05:09:20 CEST 2022-Bildschirmfoto](https://user-images.githubusercontent.com/77605776/177075782-b1738b82-d9a7-4b1a-9417-bf1107841fb3.png)

**Comment by fredcw** [comment]
Ping @Gr3q

**Comment by Gr3q** [comment]
I don't know how long it takes for the updater to refresh it's cache to show the l last version, it should appear after some time

**Comment by wolfgang-58** [comment]
Good morning,
sorry for asking again. I don't understand that, under LM19.3 an update was also carried out and the date is 2022-07-03 19:47:49, this corresponds to the date of version 3.25, which also works under LM20.3. But with LM19.3 the 3.24 is still displayed.
Have a nice day
greeting
wolfgang

**Comment by wolfgang-58** [comment]
@Gr3q 
Good morning,
the great applet now also works on LM19.3.
Thanks
greeting wolfgang
