### ISSUE TITLE
Weather applet 3.25 Wrong location at DWD

### ISSUE THREAD

**Issue by wolfgang-58** [linuxmint/cinnamon-spices-applets#4387]
Hi,
Unfortunately, I've noticed a small inconvenience. If you select the DWD, the manual location is not accepted, instead a random place name comes. One question, is the automatic localization implemented via >geoclue<?
Thank you for the great applet.
greeting
wolfgang

**Comment by fredcw** [comment]
It's best to mention the author so that they get a notification @Gr3q

**Comment by Gr3q** [comment]
Manual location only accepts lat,long it search for places in https://nominatim.openstreetmap.org/ui/search.html then uses the lat,long form there

**Comment by wolfgang-58** [comment]
Hi,
i think you didn't understand me
I would like to see the location I enter when manually creating a location. This is not so, the name displayed is that of the station, not the location. Or with the API of "nominatim", but in reverse mode, that means I enter lat and lon and get the location, like this:
https://nominatim.openstreetmap.org/reverse?lat=50.0&lon=10.0&format=geojson
Why all this, if you have several locations, you want to be able to change them in the view and a clear name of the location should be displayed, with the locations of the stations found, the assignment is difficult.
I hope you have understood my request now.
have beautiful  Day
greeting
wolfgang

**Comment by Gr3q** [comment]
I would probably understand it better with some screenshots, but I think I get it now.

I guess you enter your location in "lat,lon" format, right? I'm that case I do not use any reverse geocoding, and the API does not provide enough info.

What you can do is in the settings you can use the "Save manual location" button, then it adds it to the list. In there you can edit the city, country, timezone etc. The ones the applet uses for displaying the location is "city, country" in this format.

If those fields are not available I've written the DWD provider that it will use the station name in that case, which was probably a bad choice in retrospect

**Comment by Gr3q** [comment]
I'm near a computer again, I checked the code, yeah the code is reversed, it prioritizes the station name incorrectly
