### ISSUE TITLE
weather@mockturl - Mint 21 Data Parse Issues

### ISSUE THREAD

**Issue by arehtykitna** [linuxmint/cinnamon-spices-applets#4409]
[debug log weather app.log](https://github.com/linuxmint/cinnamon-spices-applets/files/9241735/debug.log.weather.app.log)
```
 * Applet version - 3.2.6
 * Cinnamon version - 5.4.8
 * Distribution - Linux 5.15.0-41-generic 44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 GNU/Linux
 * Graphics hardware - 29:00.0 VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 960] rev a1
```

**Notify author of applet**
@Gr3q

**Issue**
Data Parsing error for all weather service providers

**Steps to reproduce**
Install on Mint 21

**Expected behaviour**
Normal data parsing

**Other information**

log attached, too long for here

</details>

**Comment by Gr3q** [comment]
You environment is not set up correctly, you haven't configured your locale, it's still `c`

**Comment by arehtykitna** [comment]
Ah okay, I was trying it from Live media to see if UI tweaks I did to LMDE5 will carry on working after Cinnamon 5.4 is ported. Many thanks for the clarification, very much appreciated.
