### ISSUE TITLE
radio@driglu4it Volume adjusting not working

### ISSUE THREAD

**Issue by Axel-Erfurt** [linuxmint/cinnamon-spices-applets#4419]
* Applet version/Build date: Version 2.1.4 2022-06-07 13:26:49
 * Cinnamon version 5.4.9
 * Distribution - LMDE5
 * Graphics:  Intel 2nd Generation Core Processor Family Integrated Graphics driver: i915

 
Snippet of ~/.xsession-errors
```
(cinnamon:1647): Gjs-CRITICAL **: 17:06:09.735: JS ERROR: TypeError: grab_pointer is not a function
createSlider/<@/home/brian/.local/share/cinnamon/applets/radio@driglu4it/4.6/radio-applet.js:4858:21
```

**Issue**
After today's Cinnammon update, the volume can no longer be adjusted.
With the mouse wheel it only goes up to 5%, with the mouse button nothing works anymore.

**Expected behaviour**
Volume adjusting

**Comment by fredcw** [comment]
@jonath92 

```
(cinnamon:831): Gjs-CRITICAL **: 22:32:24.573: JS ERROR: TypeError: grab_pointer is not a function
createSlider/<@/home/fred/.local/share/cinnamon/applets/radio@driglu4it/4.6/radio-applet.js:4858:21
```

I had the same problem in Cinnamenu. Instead of:
```
Clutter.grab_pointer(this.actor);
```
I used:
```
this.drag_device = event.get_device();
this.drag_device.grab(this.actor);
```
with `event` being any mouse event. And to ungrab:
```
this.drag_device.ungrab();
```
It seems to work with older version of Clutter as well

**Comment by jonath92** [comment]
Yes that was one problem. Another problem was that there are now more Clutter.ScrollDirection Event types which were not always handled correct. So I guess the PR should fix it.
