### ISSUE TITLE
[sticky@scollins] Resizing notes no longer works requiring cinnamon restart.

### ISSUE THREAD

**Issue by fredcw** [linuxmint/cinnamon-spices-applets#4421]
@collinss 

In cinnamon 5.4.x `Clutter.grab_pointer()` and `Clutter.ungrab_pointer()` no longer work

An alternative method that also seems to work with earlier cinnamon versions (I've only tested on Mint 20.x) is:

```
this.drag_device = event.get_device();
this.drag_device.grab(this.actor);

⋮

this.drag_device.ungrab();
```

where `event` is any mouse event.

**Comment by collinss** [comment]
I don't support this applet now that mint has a built in sticky note app (which is much better than this applet). The only reason I've kept it around is for backwards compatibility with older systems that don't support new enough dependencies for the sticky app to work. That being said, you're welcome to make whatever changes you'd like to this applet.
