### ISSUE TITLE
where is slideshow@cinnamon.org?

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#4427]
Mint Cinnamon up to V21 has always had slideshow@cinnamon.org, a simple slideshow controls applet.   I can't find it now in V21 and it's not even in this list any more, yet 20.3 on and update does not want to remove it.

Is it history?
![slideshow](https://user-images.githubusercontent.com/26556059/184501091-b0134158-a2c1-4687-bb9b-c1599430c534.png)

**Comment by mtwebster** [comment]
It's a built-in applet (comes with Cinnamon), and is still there:

![image](https://user-images.githubusercontent.com/262776/184501442-c2588a21-dd9a-40ca-8768-b8d28ba331d6.png)

**Comment by ChooChooAl** [comment]
Thanks.  I double check.
