### ISSUE TITLE
Cinnamenu@json no longer accepts numpad enter as enter after updating to mint 21

### ISSUE THREAD

**Issue by Ember-Ember** [linuxmint/cinnamon-spices-applets#4437]
```
 * Version 5.0.1 (2022-08-20 07:14:57)
 * Cinnamon 5.4.10
 * Mint 21
 * rx580, mesa 22
 * file doesn't exist
* Snippet or attachment of https://github.com/linuxmint/cinnamon-spices-applets/files/9394058/xsession-errors.txt

 ```

**Notify author of applet**
@fredcw

**Issue**
Cinnamenu should accept both numpad enter and normal enter to open an application

**Steps to reproduce**
search for something then use numpad enter, it will do nothing

**Expected behaviour**
it should open the searched-for app

**Other information**
issue appeared after upgrading to mint 21

**Comment by fredcw** [comment]
@Ember-Ember Thanks, I'll have a fix for this in the next update.
