### ISSUE TITLE
Removal of redshift-gtk qredshift@quintao

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-applets#4473]
```
 * Version 1.7.3 (2022-09-14 02:47:25)
 * Cinnamon 5.4.12
 * Distribution:  Arch 5.19.8
 * Graphics hardware:  Radeon

 * Snippet or attachment of ~/.cinnamon/glass.log
 =warning t=2022-09-16T09:45:32Z 
QRedshift: Created
warning t=2022-09-16T09:45:32Z 
QRedshift: redshift-gtk should be removed
warning t=2022-09-16T09:45:32Z 
QRedshift: ADDED TO PANEL

 * Snippet or attachment of ~/.xsession-errors
QRedshift: Created
Gjs-Message: 09:45:32.853: JS LOG: [LookingGlass/warning] 
QRedshift: redshift-gtk should be removed
Gjs-Message: 09:45:32.946: JS LOG: [LookingGlass/warning] 
QRedshift: ADDED TO PANEL
Gjs-Message: 09:45:32.946: JS LOG: [LookingGlass/info] Loaded applet qredshift@quintao in 443 ms
 ```

**Notify author of applet**
@quintao

**Issue**
Installed QRedshift and it appears to be functioning as expected.
The notification ! _redshift-gtk_ should be removed appears, but was ignored for a long time, because the applet seems to be functioning ok.
Decided to remove redshift-gtk (sudo pacman -R redshift-gtk) and, on restart, the applet does not run with the message _requires redshift._

**Steps to reproduce**
Reinstalling redshift (sudo pacman -S redshift) causes the remove redshift-gtk to reappear.

**Expected behaviour**
Per instructions to remove redshift-gtk, the applet should continue to function.

**Other information**

**Comment by Padre2** [comment]
@quintao

**Comment by JulianGro** [comment]
Looking at the code, the warning is just triggered, without actually checking. https://github.com/linuxmint/cinnamon-spices-applets/blob/ea6ad32983763ef24a7645cfed856667fd95b2cf/qredshift%40quintao/files/qredshift%40quintao/applet.js#L621

**Comment by Padre2** [comment]
@quintao
In the code, I see:
`check_redshift_gtk() {
        let cmd = "which redshift-gtk";
        Util.spawnCommandLineAsync(cmd, (out) => {
            if (this.redshift_info_menu_item == null) {
                this.redshift_info_menu_item = new QPopupHeader({
                    label: "redshift-gtk",
                    sub_label: _("should be removed."),
                    iconName: "dialog-warning", //dialog-warning-symbolic
                    iconSize: 16
                });
                this.menu.addMenuItem(this.redshift_info_menu_item, 2);
            }
        }, (out) => {
            if (this.redshift_info_menu_item !== null) {
                this.redshift_info_menu_item.destroy();
                this.redshift_info_menu_item = null;
            }
        });
    }`
I do not have `redshift-gtk installed, but also see in Looking glass :
`warning t=2023-05-22T13:03:06Z 
QRedshift: Created
warning t=2023-05-22T13:03:06Z 
QRedshift: redshift-gtk should be removed
warning t=2023-05-22T13:03:06Z 
QRedshift: ADDED TO PANEL`
Please explain why this is happening
