### ISSUE TITLE
[radio@driglu4it] Version : inconsistent popup menu place & crash

### ISSUE THREAD

**Issue by nicolasmol** [linuxmint/cinnamon-spices-applets#4479]
Mint 20.3. Cinnamon 5.2.7. Since last Radio applet update to version 2.2.0  sometime the popup menu appears on the mid-top left of the screen far from the bottom bar then cinnamon will crash if I don't prevent it by restarting this applet just in time. Note it's not very often (occurred 3 times since update to 2.2.0), but never before

**Comment by fredcw** [comment]
Ping @jonath92
