### ISSUE TITLE
Cinnamenu@json : Cannot change the menu size by draging the menu edge

### ISSUE THREAD

**Issue by sangorys** [linuxmint/cinnamon-spices-applets#4485]
```
 * Applet version/Build date : 4.14.21 (2021-12-26 16:20:30)
 * Cinnamon version (cinnamon --version) : innamon 5.4.12
 * Distribution : Manjaro 22.0.0 Sikaris
 * Graphics hardware *and* driver used : Mesa Intel(R) Iris(R) Pro Graphics P5200 (HSW GT3). Driver i915
 * Snippet or attachment of ~/.cinnamon/glass.log : file does not exist
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@Jason Hicks @json (sorry : I don't know who is the author !!! Nuby here...)

**Issue**
[xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/9733946/xsession-errors.txt)
When draging, the mouse icon becomes normal and the menu size is still the same

**Steps to reproduce**
I use the mouse to change the menu size by draging the menu edge.
The mouse icon changes to display the "change size" icon

**Expected behaviour**
The menu size changes

**Other information**
Strange, no ???

**Comment by fredcw** [comment]
@sangorys The version of the applet you're using is quite old and is no longer compatible with Cinnamon 5.4.x. Updating to the latest version of the applet (5.0.2) should fix this problem. Thanks.

**Comment by sangorys** [comment]
I had no idea I had to update the applet manually.

It is done

Problem solved !

Sorry for any inconvenience

Thanks

**Comment by fredcw** [comment]
Actually, since LM 20.2, the update manager should also list applets that need updating in addition to updatable packages. Not sure why that didn't happen.
