### ISSUE TITLE
[Feature Request] Search box on the bottom panel

### ISSUE THREAD

**Issue by jcperil** [linuxmint/cinnamon-spices-applets#4495]
There is a search box when you click on the menu launcher.
#### Feature Request:

An option to place the search box on the bottom panel. Requesting only for placement without interfering with any functionality.

Attachment:
![before anyone gets triggered, requesting for an option only](https://user-images.githubusercontent.com/89805719/193395286-7a5df109-ecd1-47df-800f-b7221e62daa8.png)

**Comment by fredcw** [comment]
Do you mean the default cinnamon menu? If so, then the place to put this request is in https://github.com/linuxmint/cinnamon as the default applets are there.
