### ISSUE TITLE
weather@mockturl - 

### ISSUE THREAD

**Issue by danielhoechstetter** [linuxmint/cinnamon-spices-applets#4503]
```
 * Applet version - 3.2.9
 * Cinnamon version - 5.2.7
 * Distribution - Linux 5.15.0-52-generic 58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 GNU/Linux
 * Graphics hardware - 04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 164c rev c2
```

**Notify author of applet**
@Gr3q

**Issue**
automatic detection of location doesnt work anymore; only since last update (3 days ago); entering location manually does work

**Steps to reproduce**

**Expected behaviour**

**Other information**

<details>
<summary>Relevant Logs</summary>

```
The contents of the file saved from the applet help page goes here
```

</details>

**Comment by Gr3q** [comment]
Hello,

Does search work for you here? https://nominatim.openstreetmap.org/ui/search.html

logs (Debug enabled) would also help

**Comment by danielhoechstetter** [comment]
ok, i dont know what changed since the issue occured, but atm automatic location detection works again. probably some issue with my setup
