### ISSUE TITLE
weather@mockturl - Refresh when changing saved locations

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#4505]
```
 * Applet version - 3.2.9 (actually 3.2.10 from Oct 10th)
 * Cinnamon version - 5.4.12
 * Distribution - Linux 5.15.74-3-MANJARO 1 SMP PREEMPT Sat Oct 15 13:39:11 UTC 2022 x86_64 unknown GNU/Linux
 * Graphics hardware - 00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller rev 09
```

**Notify author of applet**
@Gr3q

**Issue**
When I change between my saved locations the top right side weather data for the new current location does not refresh when browsing with the arrow buttons.

**Steps to reproduce**
Add several locations and open the applet and click the right ans left arrow buttons.

**Expected behaviour**
That the weather information for the new location is shown, or that a refresh button is shown is one idea.

**Other information**
To right click and choose Refresh on the applet is perhaps not obvious for everybody and would be nice to be more easy to access and handle.

**Comment by jorgenqv** [comment]
Update: I think this might relate to the number of locations you have. When I use 3 I get a few characters but if i use 7 locations I only get dots in current locations data. Maybe a layout/size problem?
![Sreenshot 2022-10-23 12-24-41](https://user-images.githubusercontent.com/5297223/197386996-96d36e5d-76f9-48b0-9c45-b892c77fd12b.png)

**Comment by Gr3q** [comment]
Unfortunately I'm aware of the problem, it has nothing to do with the number of locations. I think it caused by rebuilding the ui on that change (even tho its supposed to prevent this).

I'll have a fix at some point next week, I'll include improvements on config change handling.

**Comment by jorgenqv** [comment]
Works good, thanks!
