### ISSUE TITLE
[Feature Request] - Add audio out selection

### ISSUE THREAD

**Issue by TomDC777** [linuxmint/cinnamon-spices-applets#4531]
**Feature Request**

I'm always switching between my headphones and sound bar for my audio output. 

Instead of clicking "Sound Settings" and then selecting my hardware device, it would be nice to select it just how Radio++ lets you quickly select a station in the popup menu.

![example_radio](https://user-images.githubusercontent.com/84793268/198901786-f5838fe7-79a6-4eba-b140-ba574e153ffd.png)
![example_soundsetting](https://user-images.githubusercontent.com/84793268/198901791-82f6e886-9185-4dae-9231-53b3d48dc3d5.png)
![example_soundsetting2](https://user-images.githubusercontent.com/84793268/198901790-fe4092bf-1e12-461f-b38b-85c4eb37bc1c.png)

**Comment by Drugwash2** [comment]
Have you tried right-clicking the sound icon...?

**Comment by TomDC777** [comment]
Thank you!
------- Original Message -------

**Comment by claudiux** [comment]
@TomDC777 Can you close this issue, please?
