### ISSUE TITLE
Typo in MuteToggler applet

### ISSUE THREAD

**Issue by williamdes** [linuxmint/cinnamon-spices-applets#4536]
https://github.com/linuxmint/cinnamon-spices-applets/blob/66be69e4a795763bbbfd6103ea0b6fa61363c698/MuteToggler%40jebeaudet.com/files/MuteToggler%40jebeaudet.com/settings-schema.json#L4

microphoone -> microphone

**Comment by fredcw** [comment]
Ping @jebeaudet

**Comment by jebeaudet** [comment]
@williamdes Next time don't hesitate to open PRs, if I'm not mistaken linuxmint maintainers can merge those trivial changes themselves.

**Comment by williamdes** [comment]
Sure, I will maybe improve the applet then :)
