### ISSUE TITLE
Unnecessary message "redshift-gtk should be removed" on Arch Linux

### ISSUE THREAD

**Issue by lukaszpolowczyk** [linuxmint/cinnamon-spices-applets#4559]
The latest Arch Linux
This redshift package - https://archlinux.org/packages/community/x86_64/redshift/

In QRedShift the message: "redshift-gtk should be removed."

I don't have the "redshift-gtk" package on my system, I only have the redshift package.
But the redshift package has its own GUI.

When I remove redshift, a message about no redshift appears in QRedShift and QRedShift does not work at all.

**This message is unnecessary, please remove it.**

**Comment by claudiux** [comment]
Also on Linux Mint.

**Comment by fredcw** [comment]
Ping @raphaelquintao

**Comment by raphaelquintao** [comment]
Very strange. 
Can you please show-me the output of the command `which redshift-gtk` ?

**Comment by lukaszpolowczyk** [comment]
@raphaelquintao 
```
$ which redshift-gtk
/usr/bin/redshift-gtk
```

**Comment by raphaelquintao** [comment]
So you have `redshift-gtk` installed.
I guess the `redshift-gtk` gui comes with `redshift` package in arch and maybe in the newer versions of Mint too, you cann try to remove it and install `redshift-minimal`. 
Let me know it solves you problem.

**Comment by lukaszpolowczyk** [comment]
>  you can try to remove it and install redshift-minimal

@raphaelquintao It helped. Thanks.

But you need to give a different message in applelet in that case, because this one is confusing on Arch.

**Comment by raphaelquintao** [comment]
Its a problem because i use Debian, so its hard to test on other distros like Arch and Fedora.
Even on Mint i cant be 100% sure it will work.

**Comment by ucimo** [comment]
Got the same message on a freshly installed Mint
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/38113520/0e1a4979-0f3a-4d11-95fa-73f4d22ea2ff)
