### ISSUE TITLE
Sensors@Claudiux use in Manjaro-Cinnamon

### ISSUE THREAD

**Issue by yaxunil2** [linuxmint/cinnamon-spices-applets#4575]
```
 * Applet version 1.5.0
 * Cinnamon version 5.4.12
 * Distribution - Manjaro-Cinnamon 21
 * Sensors version 3.6.0-git + Libsensors 3.6.0-git 
 * Graphics hardware NVIDIA Geforce GTX 550 Ti
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors
\\\{
   "coretemp-isa-0000":{
      "Adapter": "ISA adapter",
      "Package id 0":{
         "temp1_input": 34.000,
         "temp1_max": 85.000,
         "temp1_crit": 105.000,
         "temp1_crit_alarm": 0.000
      },
      "Core 0":{
         "temp2_input": 27.000,
         "temp2_max": 85.000,
         "temp2_crit": 105.000,
         "temp2_crit_alarm": 0.000
      },
      "Core 1":{
         "temp3_input": 34.000,
         "temp3_max": 85.000,
         "temp3_crit": 105.000,
         "temp3_crit_alarm": 0.000
      },
      "Core 2":{
         "temp4_input": 31.000,
         "temp4_max": 85.000,
         "temp4_crit": 105.000,
         "temp4_crit_alarm": 0.000
      },
      "Core 3":{
         "temp5_input": 31.000,
         "temp5_max": 85.000,
         "temp5_crit": 105.000,
         "temp5_crit_alarm": 0.000
      }
   }
}
\\\
 ```

**Notify author of applet**
@claudiux 

**Unable to get to work 
The desktop/interface in Manjaro-Cinnamon is almost identical to Mint-Cinnamon. I downloaded and installed the applet 'Sensors@Claudiux' in the applet app, but I can not open the settings button (the cog icon) of your app. 
lm-sensors and xsensors are installed and I can get some values when I open xsensors, but to get them to show in the panel, I need your app to work. I also tried 'Psensors' that I think is better than xsensors. Do have any suggestion on how to get your app to work in my system so that I can have the temps displayed in the panel. Thanks **

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by claudiux** [comment]
Hi @yaxunil2,

Please copy here the part of your ''~/.xsession-errors'' file concerning this applet.

**Comment by yaxunil2** [comment]
Hi, 
Thanks for the reply, but I since fixed it - it was missing a dependency
