### ISSUE TITLE
better-backgrounds@simonmicro: SUDDENLY STOPPED WORKING , wont show on panel either

### ISSUE THREAD

**Issue by Free-Radical** [linuxmint/cinnamon-spices-applets#4584]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * ---Updated on 2022-09-13 14:47:56
 * Cinnamon version (cinnamon --version)
 * ---Cinnamon 5.4.12
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * ---Linux Mint 21 5.17.0-1020-oem
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@simonmicro

**Issue**
not showing in panel or changing backgrounds

**Steps to reproduce**
see if the applet is on the panel , if yes then change back ground should change background

**Expected behaviour**
should show up in panel and change backgrounds

**Other information**

**Comment by simonmicro** [comment]
Heyho, do you have any logs for me to investigate? Because I still use it on a daily basis (four devices, all Linux Mint 21) and no other users pinged me over on https://github.com/simonmicro/better-backgrounds ...

**Comment by simonmicro** [comment]
Try to open "Looking Glass"  and take a look into the "Log" tab. There should be printed something whenever you add/remove the applet and something goes haywire... Your attached logfiles do not seem to contain anything. Sad thing is that I can't reproduce that error nor do I get any useful logs from you guys :cry: , without that I can't fix anything...

**Comment by Free-Radical** [comment]
I'm new at this and trying my best. 
Strangely,  ~/.xsession-errors did not exist 1st time, when i tried to send the file the first time.

**Comment by Free-Radical** [comment]
there is no "looking glass" app on my linux Mint 21, neither does anything show up on "software manager" , pls tell me where to get this app. 
Thanks.

**Comment by simonmicro** [comment]
Right-Click on your panel -> Troubleshoot -> Looking Glass

**Comment by simonmicro** [comment]
ping @Free-Radical

**Comment by Free-Radical** [comment]
No mention of "better backgrounds" startup output from looking glass log.  also missing from "Extensions" tab.

Full copy of log below
---
info t=2022-12-07T17:28:48Z Cinnamon.AppSystem.get_default() started in 116 ms
info t=2022-12-07T17:28:48Z loading user theme: /usr/share/themes/Silk/cinnamon/cinnamon.css
info t=2022-12-07T17:28:48Z added icon directory: /usr/share/themes/Silk/cinnamon
info t=2022-12-07T17:28:48Z Monitor 1 not found. Not creating panel
info t=2022-12-07T17:28:49Z loaded at Wed Dec 07 2022 17:28:49 GMT-0500 (Eastern Standard Time)
info t=2022-12-07T17:28:49Z ExtensionSystem started in 3 ms
info t=2022-12-07T17:28:49Z SearchProviderManager started in 1 ms
info t=2022-12-07T17:28:49Z Loaded applet separator@cinnamon.org in 24 ms
info t=2022-12-07T17:28:49Z Loaded applet scale@cinnamon.org in 22 ms
info t=2022-12-07T17:28:49Z Role locked: tray
info t=2022-12-07T17:28:49Z Loaded applet systray@cinnamon.org in 10 ms
info t=2022-12-07T17:28:49Z Loaded applet xrandr@cinnamon.org in 0 ms
info t=2022-12-07T17:28:49Z Role locked: notifications
info t=2022-12-07T17:28:49Z Loaded applet notifications@cinnamon.org in 54 ms
info t=2022-12-07T17:28:49Z Loaded applet settings@cinnamon.org in 16 ms
info t=2022-12-07T17:28:49Z Loaded applet calendar@cinnamon.org in 78 ms
info t=2022-12-07T17:28:49Z Loaded applet calendar@simonwiles.net in 1 ms
info t=2022-12-07T17:28:49Z Loaded desklet diskspace@schorschii in 103 ms
info t=2022-12-07T17:28:49Z Loaded applet workspace-switcher@cinnamon.org in 19 ms
info t=2022-12-07T17:28:49Z Loaded applet workspace-switcher@cinnamon.org in 1 ms
info t=2022-12-07T17:28:49Z 28 desklet already loaded
info t=2022-12-07T17:28:49Z 29 desklet already loaded
info t=2022-12-07T17:28:49Z 30 desklet already loaded
info t=2022-12-07T17:28:49Z Loaded desklet diskspace@schorschii in 1 ms
info t=2022-12-07T17:28:49Z 28 desklet already loaded
info t=2022-12-07T17:28:49Z 29 desklet already loaded
info t=2022-12-07T17:28:49Z 30 desklet already loaded
info t=2022-12-07T17:28:49Z Loaded desklet diskspace@schorschii in 0 ms
info t=2022-12-07T17:28:49Z DeskletManager started in 384 ms
info t=2022-12-07T17:28:49Z Loaded applet xapp-status@cinnamon.org in 37 ms
info t=2022-12-07T17:28:49Z Loaded applet hwmonitor@sylfurd in 1 ms
info t=2022-12-07T17:28:49Z Loaded applet power@cinnamon.org in 30 ms
info t=2022-12-07T17:28:49Z Loaded applet sound@cinnamon.org in 67 ms
info t=2022-12-07T17:28:49Z Adding XAppStatusIcon: nm-applet (:1.56/org/x/StatusIcon/Icon)
info t=2022-12-07T17:28:49Z Hiding XAppStatusIcon (we have an applet): nm-applet (:1.56/org/x/StatusIcon/Icon)
info t=2022-12-07T17:28:49Z Loaded applet network@cinnamon.org in 44 ms
info t=2022-12-07T17:28:49Z Loaded applet SpicesUpdate@claudiux in 146 ms
info t=2022-12-07T17:28:50Z Loaded applet menu@cinnamon.org in 398 ms
info t=2022-12-07T17:28:50Z Loaded applet menu@cinnamon.org in 0 ms
info t=2022-12-07T17:28:50Z AppletManager started in 1122 ms
info t=2022-12-07T17:28:50Z Cinnamon took 1421 ms to start
info t=2022-12-07T17:28:50Z Adding XAppStatusIcon: ulauncher (:1.51/org/x/StatusIcon/Icon)
info t=2022-12-07T17:28:50Z Adding XAppStatusIcon: blueman (:1.51/org/x/StatusIcon/Icon_1)
info t=2022-12-07T17:28:50Z Adding XAppStatusIcon:  (:1.51/org/x/StatusIcon/Icon_2)
info t=2022-12-07T17:28:55Z Adding XAppStatusIcon:  (:1.51/org/x/StatusIcon/Icon_3)
info t=2022-12-07T17:29:11Z Adding XAppStatusIcon: mintUpdate.py (:1.90/org/x/StatusIcon/Icon)
info t=2022-12-07T17:29:34Z Adding XAppStatusIcon: mintreport (:1.92/org/x/StatusIcon/Icon)
info t=2022-12-07T17:29:34Z Adding XAppStatusIcon: process-monitor (:1.92/org/x/StatusIcon/Icon_1)
----

Futrther actions performed-
1) removing/pressing minus sign under applets for "better backgrounds" applet warns "multiple instances enabled, remove all?" --> Yes

2) clicked Plus sign on "Better BAckgrounds" but applet did not start and  not visible on Applet panel. Even though check mark (running ) in Applet panel.

NO NEW NOTIFICATIONS IN LOG! 

Im happy to share my desktop with you to do better debugging.

**Comment by simonmicro** [comment]
Okay. That's  _very_ strange! Would it be possible that you contact me by email? We could then proceed from there to figure out what is going on. I'll make sure to keep this issue up-to-date while we debug :)

**Comment by Free-Radical** [comment]
yes. of course, your email?

**Comment by simonmicro** [comment]
See my commits - or my website. I prefer to not just type them here :)

**Comment by Free-Radical** [comment]
Waiting on you Bro, sent email days ago.

**Comment by simonmicro** [comment]
Users system was the problem. This issue can be closed. I think.

**Comment by Free-Radical** [comment]
yes probably, could you recommend how to reinstall a vanilla settings cinnamon desktop?
