### ISSUE TITLE
[Sensors@claudiux] Allow duplicate entries

### ISSUE THREAD

**Issue by EmergReanimator** [linuxmint/cinnamon-spices-applets#4590]
```
 * Applet version 1.5.0
 * Cinnamon version: 5.2.7
 * Distribution: Fedora 36
 * Graphics hardware *and* driver used: See attachments
 * [attachments.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/10202488/attachments.zip)
 * sensors.json - _sensors -j_ output
 * example.json - example file generated by applet.


 ```

**Notify author of applet**
@claudiux

**Issue**
Duplicated entries issues by _sensors_ utility are filtered out by JSON library. Only last entry kept.

**Steps to reproduce**
Use attached sensors.json file generated by _sensors_.

**Expected behaviour**
Multiple "Processor Fan" keys should available.

**Other information**

**Comment by claudiux** [comment]
@EmergReanimator 

Thank you. I'll try to solve this issue.

**Comment by claudiux** [comment]
Hi @EmergReanimator 

Please try this: https://www.cyberciti.biz/faq/controlling-dell-fan-speeds-temperature-on-ubuntu-debian-linux/

It looks like your 2 fans should be named: Left Fan and Right Fan (not the two Processor Fans).

**Comment by EmergReanimator** [comment]
> Hi @EmergReanimator
> 
> Please try this: https://www.cyberciti.biz/faq/controlling-dell-fan-speeds-temperature-on-ubuntu-debian-linux/
> 
> It looks like your 2 fans should be named: Left Fan and Right Fan (not the two Processor Fans).

Actually there are two dedicated CPUs fans for two independent CPUs in Dell Precision T7610.
The `i8kctl` is not applicable in this case.

I am using sensors version 3.6.0 with libsensors version 3.6.0;

```
>> lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  32
  On-line CPU(s) list:   0-31
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) CPU E5-2687W v2 @ 3.40GHz
    CPU family:          6
    Model:               62
    Thread(s) per core:  2
    Core(s) per socket:  8
    Socket(s):           2
    Stepping:            4
    CPU(s) scaling MHz:  71%
    CPU max MHz:         4000.0000
    CPU min MHz:         1200.0000
    BogoMIPS:            6784.18
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pd
                         pe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor 
                         ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm
                          cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts m
                         d_clear flush_l1d
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   512 KiB (16 instances)
  L1i:                   512 KiB (16 instances)
  L2:                    4 MiB (16 instances)
  L3:                    50 MiB (2 instances)
NUMA:                    
  NUMA node(s):          2
  NUMA node0 CPU(s):     0-7,16-23
  NUMA node1 CPU(s):     8-15,24-31
Vulnerabilities:         
  Itlb multihit:         KVM: Mitigation: VMX disabled
  L1tf:                  Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
  Mds:                   Mitigation; Clear CPU buffers; SMT vulnerable
  Meltdown:              Mitigation; PTI
  Mmio stale data:       Unknown: No mitigations
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected```

**Comment by claudiux** [comment]
@EmergReanimator 
Hi, 
I plan to allow advanced users to monitor files under `/sys/class/`. Are there two different files in this directory that indicate the values you'd like to display?

**Comment by EmergReanimator** [comment]
> @EmergReanimator Hi, I plan to allow advanced users to monitor files under `/sys/class/`. Are there two different files in this directory that indicate the values you'd like to display?

Yes, there are dedicated entries found for each sensor label:

```
cat /sys/class/hwmon/hwmon1/fan?_label

Processor Fan
Processor Fan
Other Fan
```

**Comment by claudiux** [comment]
This issue is due to an incorrect configuration of the sensors program.

I'm closing it.

**Comment by EmergReanimator** [comment]
> @EmergReanimator Try to create the `/etc/sensors.d/custom.conf` containing:
> 
> ```
> chip "dell_smm-isa-*"
> 
>   label fan1 "Processor Fan 1"
>   label fan2 "Processor Fan 2"
> ```
> 
> Then reboot your computer.

Just want to confirm, that this is really the solution of this issue.
Thank you for the hint!
