### ISSUE TITLE
Feature Request - Customizable Graph Line Thickness

### ISSUE THREAD

**Issue by dmelorj** [linuxmint/cinnamon-spices-applets#4622]
I would like to suggest the possibility of configuring the line thickness of the graphics, to facilitate their visualization.

![image](https://user-images.githubusercontent.com/30875225/209801167-fa57e686-38f1-40e8-b64f-e398d0312605.png)

Edit: Applet Multi-Core System Monitor (multicore-sys-monitor@ccadeptic23)

**Comment by rcalixte** [comment]
@dmelorj Can you edit to include the name of the applet you're referring to here?

**Comment by claudiux** [comment]
Applet: multicore-sys-monitor@ccadeptic23

**Comment by claudiux** [comment]
@dmelorj 
Try to edit the `~/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/4.0/applet.js` file and replace the line 386:
`xOffset += width + 1;`
by:
`xOffset += width + 3;` (or whatever integer value you want, from 1 to 5).

Then restart Cinnamon.

**Comment by dmelorj** [comment]
@claudiux  sorry for the delay. I've tried this, but it looks like that instead of graph line thickness, it increased the distance between each monitor

![image](https://user-images.githubusercontent.com/30875225/211341626-30ba8446-7d61-4e06-aa6c-962c6b11783d.png)

![image](https://user-images.githubusercontent.com/30875225/211341855-361c06b0-77ef-4c1e-8a2b-b79ece1c7670.png)

**Comment by claudiux** [comment]
@dmelorj 
Sorry, I misunderstood your request.

To increase the graph line thickness, edit the `~/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/4.0/Graphs.js` file and change line 300:
`areaContext.setLineWidth(1);`
by:
`areaContext.setLineWidth(3);`

If this meets your expectation, then I will try to modify the configuration window.

**Comment by dmelorj** [comment]
@claudiux  it worked like a charm. Thanks a lot.

![image](https://user-images.githubusercontent.com/30875225/211390408-78a75a8f-8594-45bd-a53b-70612a7cdd61.png)

It would be very nice having the option to tunning this using the GUI of the applet.

**Comment by claudiux** [comment]
@dmelorj 

> It would be very nice having the option to tuning this using the GUI of the applet.

Yep: #4767.
