### ISSUE TITLE
[NEED HELP] popupMenu.js: insert a submenu into a submenu (Radio3.0@claudiux)

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon-spices-applets#4626]
```
 * Applet version: Radio3.0 (next version)
 * Cinnamon version: 5.6.5
 * Distribution: Mint 21.1

 ```

**Issue**
I'm trying to make a menu with the list of Categories of radio stations.

![Radio30_menu_with_categories](https://user-images.githubusercontent.com/33965039/210092715-cdfa8030-b629-4952-a439-33d36ca0c39b.png)

I would like that by clicking on a Category, the list of its radio stations is displayed.

But when I click on a category, only the triangle rotates and the list does not appear.

Is there a solution to this problem?

**Comment by mchilli** [comment]
Hi,
for me it works like this:
```
let subsubMenu1 = new PopupMenu.PopupSubMenuMenuItem('subsubmenu1');
let subsubMenu2 = new PopupMenu.PopupSubMenuMenuItem('subsubmenu2');
let subMenu = new PopupMenu.PopupSubMenuMenuItem('submenu');

subsubMenu1.menu.addMenuItem(new PopupMenu.PopupMenuItem('item1'));
subsubMenu1.menu.addMenuItem(new PopupMenu.PopupMenuItem('item2'));
subsubMenu1.menu.addMenuItem(new PopupMenu.PopupMenuItem('item3'));

subMenu.menu.addMenuItem(subsubMenu1);
subMenu.menu.addMenuItem(subsubMenu2);

this.menu.addMenuItem(subMenu);
```
as seen here:

![ksnip_20230102-173807](https://user-images.githubusercontent.com/13848421/210258601-9b613d4a-adf9-416e-839b-2cafe8e5db69.png)


Hope this helps?!
Greetings

**Comment by claudiux** [comment]
Thank you @mchilli. I'll try that.

**Comment by claudiux** [comment]
@mchilli 

Unfortunately, when the top submenu contains many submenus, these submenus no longer open.

**Comment by claudiux** [comment]
Thank you for testing. I'll try to calculate the menu dimensions.

**Comment by claudiux** [comment]
I'm closing this issue because I'm going to try another solution, as in `menu@cinnamon.org`.
