### ISSUE TITLE
weather@mockturtl Conditions not matching Weather Underground website (plus "!" on icon)

### ISSUE THREAD

**Issue by garuffalo** [linuxmint/cinnamon-spices-applets#4628]
```
 * Version 3.2.11 (2023-01-01 15:22:22)
 * Cinnamon Version 4.4.8
 * Linux Mint 19.3
 * Intel Mobile GM965/GL960 Integrated Graphics *and* i915 driver

 ```

**Notify author of applet**
@

**Issue**
Applet was reporting "Scattered Showers" with "cloud" icon and exclamation point. Observed that applets current conditions were not what the Weather Underground website was producing (it was actually "Clear" at my location). Same exact lat/long coordinates as website station are used for weather applet. When conditions changed from "Scattered Showers" to something else, the exclamation point icon went away.

Other weather data, such as temperature, were matched to the WU website info, but conditions continue to be a mismatch, although not as radical as the mismatch observed with the exclamation point icon, i.e., "Scattered Showers" vs. "Clear".

So there are actually two issues here: The icon with the exclamation point. -- And, the mismatch of current conditions to the WU weather station displayed on the WU website.

**Steps to reproduce**
Unable to reproduce, as it was observed as a one time occurrence. I am aware of the issue of certain conditions not having a related icon, so perhaps the next time "Scattered Showers" appears, the exclamation point will reappear. Won't know until that happens.

**Expected behaviour**
Would expect the weather applets current conditions to match those of Weather Underground. Also would be good if exclamation point did not appear on icon.

**Other information**
![Screenshot_applet+website](https://user-images.githubusercontent.com/28717740/210401238-d775ba78-352f-4f1c-a54f-98aa624808db.png)

**Comment by Gr3q** [comment]
Unfortunately the data access through the API is very limited, If you registered a weather station you can only query other Personal weather stations and on 5 days of forecast, so sometimes it doesn't have enough data even if it tries to merge observations from multiple stations around your area

**Comment by Gr3q** [comment]
Actually, conditions are only available in forecast, I pull them from there because the applet doesn't support not having them. Even then sometimes they are missing.

**Comment by garuffalo** [comment]
Thanks for the explanation. Too bad the API for Weather Underground is so limited. They have a high rating for accuracy, and I like the phone app and website. I've used Dark Sky since I started using the applet, and that worked really well. But that API is going dark in March, so I am looking for a good replacement.

**Comment by garuffalo** [comment]
Well, just like that, the Weather Underground API started working for me again! My "device" still says "offline" in my account settings, so apparently that has no effect on the applet.

Do you know if there are a limited number of calls per day for Weather Underground? I had the update interval set to every 5 minutes. Maybe I used up all my allotted calls, and now it is reset for another 24 hours? I am on the East Coast (USA), if time zone is of any concern. I changed the update interval to 10 minutes as an experiment.

**Comment by garuffalo** [comment]
Regarding pulling conditions from the forecast, I assume this is only an issue with Weather Underground, as their API doesn't provide any descriptive wording for current conditions. In comparison, Dark Sky, for example, seems to provide current conditions wording that more or less matches what is actually happening outside.

As I write this, Dark Sky (via applet) says "Overcast", which is correct; whereas Weather Underground says "Rain" (for current conditions, incorrect). If Weather Underground is to be continued as an API source, perhaps there should be a disclaimer in your documentation stating that the conditions are actually derived from the forecast. Ideally, behavior of the applet should be consistent, regardless of which API is used. My opinion.

There are many things I really like about Weather Underground. Too bad their API is not more comprehensive.

**Comment by Gr3q** [comment]
I will update the README with the information, it got left out. for example MET Norway and the others contain these kind information.

**Comment by garuffalo** [comment]
![scattered_showers_error](https://user-images.githubusercontent.com/28717740/212789146-d53633d6-3a59-4cdb-b325-658ece5279de.png)

The only condition icon I continue to have issues with (so far) is the "scattered showers" icon. I checked in the Mint-Y icons and there appears to be a symbolic icon there called "weather-showers-scattered", in "panel" folder, which is a cloud with a couple of droplets. Is there no way to point the applet to this icon when the conditions are "scattered showers"?

![symbolic_scattered_showers](https://user-images.githubusercontent.com/28717740/212789096-30d5a208-ce8b-4812-8ac6-fa946e3ef94b.png)

**Comment by garuffalo** [comment]
Yes, I believe it was in the evening, based on the time stamps for when I made a screenshot and when I logged in to GitHub to report the issue.

**Comment by Gr3q** [comment]
Then this should go away after the next update is merged

**Comment by garuffalo** [comment]
I hate to be a pain, but WU doesn't seem to have a "Heavy Rain" icon either. Is that something that can be fixed, as with "Scattered Showers"? We have a lot of different types of weather at my location!
It is just a couple of minutes past sunset. I was away from my computer pre-sunset, so I don't know what was showing then.

![heavy_rain_exlam](https://user-images.githubusercontent.com/28717740/214701510-0b77a868-7bec-4ee5-9837-5abae82614b3.png)

**Comment by Gr3q** [comment]
Done
