### ISSUE TITLE
grouped-window-list@cinnamon.org: Not respecting 'super-num-hotkeys' false setting until re-toggled

### ISSUE THREAD

**Issue by t3pfaffe** [linuxmint/cinnamon-spices-applets#4634]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon 5.6.3
 * Arch Linux 6.0.10-arch2-1

 ```

**Notify author of applet**
<not applicable>

**Issue**
The grouped window list applet still occasionally decides to use the 'Super+<number>' hotkeys even though it is disabled in the config. Going into the preferences and enabling/disabling it again will fix this issue. 

**Steps to reproduce**
Seemingly randomly after restarts or updates, using the 'super+<number>' hotkeys which are bound elsewhere in my Cinnamon shortcuts config no longer works as it opens the numbered shortcut in the grouped-window-list instead despite it being disabled.

**Expected behavior**
The 'super+<number>' hotkeys do not open pinned programs on the grouped-window-list when the 'super-num-hotkeys' is disabled

**Other information**
I have encountered this issue on multiple machines, so it does not appear to be device configuration specific. I checked the config to make sure it isnt being unset but the config file being used clearly has the value of the key 'super-num-hotkeys' as false.

**Comment by fredcw** [comment]
@t3pfaffe You can close this issue here if you like.
