### ISSUE TITLE
CinnVIIStarkMenu@NikoKrause Visual artifact on (All Programs) panel

### ISSUE THREAD

**Issue by scoson** [linuxmint/cinnamon-spices-applets#4641]
```
 * CinnVIIStarkMenu version 1.31
 * Cinnamon 5.6.5 
 * Linux Mint 21.1 Vera
 * Graphics:
  Device-1: Intel GeminiLake [UHD Graphics 600] vendor: Hewlett-Packard
    driver: i915 v: kernel bus-ID: 00:02.0
  Device-2: Luxvisions Innotech HP TrueVision HD Camera type: USB
    driver: uvcvideo bus-ID: 1-6:4
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: i915 resolution: 1366x768~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics 600 (GLK 2) v: 4.6 Mesa 22.0.5
    direct render: Yes


 ```

**Notify author of applet**
@NikoKrause

**Issue**
I've noticed the issue shown below since Mint Cinnamon 21 Vanessa release. It seems 2 others report the same on the Spices Applet page. I just did a clean install of Vera and am using Mint-y-blue theme and icons. I had to actually take a pic of this as it disappears with screenshot.

![IMG_20230110_141346_NR resized](https://user-images.githubusercontent.com/46092441/211661201-c04102ac-b1c4-4af1-969c-f0954c37def4.jpg)

**Comment by fedaykin451** [comment]
I have noticed the exact same issue since upgrading to Mint Cinnamon 21, as well.  I notice it most often while scrolling or moving the cursor from right to left in the menu.

**Comment by scoson** [comment]
Wondering if an update somehow fixed this issue within the last week? It seems to have resolved. I haven't seen this issue occur in several days. Just sayin..

**Comment by fedaykin451** [comment]
> Wondering if an update somehow fixed this issue within the last week? It seems to have resolved. I haven't seen this issue occur in several days. Just sayin..

Still an issue for me.  I have noticed it doesn't reproduce every time.  Some days I don't see it at all.

**Comment by scoson** [comment]
@fedaykin451 Yeah, I was mistaken, still a problem here to.

**Comment by fedaykin451** [comment]
I installed today's update (2/7/2023), problem still occurs.

**Comment by fedaykin451** [comment]
Problem still occurring after most recent update.

**Comment by anaximeno** [comment]
I also had the same problem in my computer.

Here's a video exemplifying the behavior of the menu when reproducing this bug:

https://user-images.githubusercontent.com/63073056/235327713-00a0a8b5-9d02-456d-bf71-cad1dabae3c7.mp4

**Comment by fedaykin451** [comment]
> One thing I'll point out in case anyone isn't aware, is that @NikoKrause hasn't been active on github for over a year. Even though there have been some unrelated updates to CinnVIIStarkMenu recently, I imagine it's possible that this issue might not ever be addressed.

Is @NikoKrause active on some other platform where issues can be reported?  It would seem odd for them to abandon github entirely if they are still maintaining the applet.  This is by far the best menu for Cinnamon and while it's still usable for the moment, it would be a shame for this never to get fixed.

**Comment by scoson** [comment]
What a nice surprise, thank you!
