### ISSUE TITLE
weather@mockturtle: Standard temperature unit is set based on language instead of region setting

### ISSUE THREAD

**Issue by UristMcEngineer** [linuxmint/cinnamon-spices-applets#4644]
```
* Applet version/Build date: Version 3.2.11 (2023-01-01 21:22:22)
* Cinnamon version: 5.6.6
* Distribution: Linux Mint 21.1
```

**Notify author of applet**
@Gr3q

**Issue**
The standard units for temperature are set based on the systems language settings instead of its region setting.

**Steps to reproduce**
Changing the systems language between "German, Germany" and "English, United States" changes the used temperature unit between Celsius and Fahrenheit.

**Expected behaviour**
Standard temperature unit should be set based on the systems region setting.

**Comment by Gr3q** [comment]
The only thing I can use that is set on almost all systems is the timezone instead. I will probably do that for wind, distance and temperature units as well

**Comment by Drugwash2** [comment]
Personally I think this and others similar should have manual overrides. It is the user as a person who prefers a certain type of display, and while system settings, language and timezones can change at any time for whatever reason the user may still be the same and would usually have the very same preferences regardless of those changes.

And to cover any corner cases I believe establishing some (editable) profiles for such settings could help, so in case there are multiple individuals working with the same machine and same username, or the unique user requires different settings in different situations, simply switching display unit profiles through a discrete button would quickly solve any related issue.

**Comment by Gr3q** [comment]
> Personally I think this and others similar should have manual overrides.

There are, this is for "Automatic" settings.

> It is the user as a person who prefers a certain type of display, and while system settings, language and timezones can change at any time for whatever reason the user may still be the same and would usually have the very same preferences regardless of those changes.

I try to infer the sane defaults based on either the user's locale (language) or now the user's location (timezone) - **this is what this discussion should really be about** -  I haven't decided which one is better, it's usually done via locale. Anyone who changes languages (or maybe from now on timezones) frequently should just set their preference manually, that's why it's exposed.

> And to cover any corner cases I believe establishing some (editable) profiles for such settings could help, so in case there are multiple individuals working with the same machine and same username, or the unique user requires different settings in different situations, simply switching display unit profiles through a discrete button (which displays a menu) would quickly solve any related issue.

This argument falls apart way before we would even reach discussing this in the scope of the weather applet. This exact use case is what linux user management was intended for.

**Comment by Drugwash2** [comment]
Ah, sorry for barging in without thoroughly checking the conjecture. Please disregard my comment.
