### ISSUE TITLE
Sensors@claudix Question: How to get sensors to display in the temperatures list?

### ISSUE THREAD

**Issue by alexspurling** [linuxmint/cinnamon-spices-applets#4658]
```
 * Sensors v2.0.2
 * Cinnamon 5.6.7
 * Mint 21.1
 ```

I am wondering what are the steps required to get temperature sensors to display in the "Temperature sensors" list shown in the "Temperature" tab of the Sensors Monitor applet settings? I have just installed the most recent version of the applet on a clean install of Mint 21.2 and done nothing else. Here is what my "Temperature" tab looks like:

![image](https://user-images.githubusercontent.com/137831/215345331-4d35b6c5-2f18-47d1-97e6-0e2419e01b3b.png)

**Comment by claudiux** [comment]
Hi @alexspurling 

Did you try the `sudo sensors-detect` command?

**Comment by claudiux** [comment]
Please check the 'Display the values of these selected sensors' box.

**Comment by alexspurling** [comment]
Thanks, that worked although I had to click the "Renew the list of sensors" button twice for anything to happen.

**Comment by claudiux** [comment]
Great!
Just the time for the 'sensors' program to return the first data...
Can you close this issue, please?
Regards.
