### ISSUE TITLE
pam_unix(sudo:auth): auth could not identify password for [<user>]

### ISSUE THREAD

**Issue by HanM23** [linuxmint/cinnamon-spices-applets#4672]
```
Version 2.0.2 (2023-01-24 16:52:05)
Cinnamon 5.6.5
Fedora 37
NVIDIA Driver (proprietary) 525.85.05
 ```

.xsession-errors
```
(cinnamon:2003):` Gjs-CRITICAL **: 16:30:59.912: JS ERROR: TypeError: can't convert undefined to object
unref/<@/home/<user>/.local/share/cinnamon/applets/Sensors@claudiux/lib/util.js:683:27
setTimeout/id<@/home/<user>/.local/share/cinnamon/applets/Sensors@claudiux/lib/util.js:584:18
```

**Notify author of applet**
@claudiux

**Issue**

I get the folliowing error message in journalctl every '_refresh interval_' once in check any checkbox in the '_Temperature scripts_' zone inside the '_Temperature_' tab:

```
Feb 05 16:47:58 sudo[13086]: pam_unix(sudo:auth): auth could not identify password for [<user>]
Feb 05 16:47:58 sudo[13086]: pam_unix(sudo:auth): conversation failed
```

**Steps to reproduce**

Install the applet, click any checkbox inside the '_Temperature scripts_' zone inside '_Temperature_' tab

**Expected behaviour**

I should not have those error message in my logs. My refresh interval is 2 seconds and i get them every 2 seconds.

**Other information**

I suspect this is due to the scripts located in `/home/<user>/.local/share/cinnamon/applets/Sensors@claudiux/scripts`.
Some of them (get_disk_temp.sh for instance) use `sudo smartctl`, but this is just a thought.

Thank you for your help

**Comment by claudiux** [comment]
Hi @HanM23,

Please try this command:

`~/.local/share/cinnamon/applets/Sensors@claudiux/scripts/pkexec_make_smartctl_usable_by_sudoers.sh`

**Comment by HanM23** [comment]
Hi @claudiux 

I ran this command in a terminal,log out & log in but it does not change anything. 
I also removed the applet, then added it to see if there is any difference, but i still have those error messages in my logs every 'refresh interval'

**Comment by claudiux** [comment]
The command:
`sudo cat /etc/sudoers.d/smartctl`
must return:
`%sudo ALL = NOPASSWD: /usr/sbin/smartctl`

The command:
`which smartctl`
must return:
`/usr/sbin/smartctl`

The answer to the command:
`groups`
must contain 'sudo'

Can you verify all that, please?

**Comment by HanM23** [comment]
I got it, I do not have any `sudo` group in my distro.
I replaced `sudo` by `wheel` in the script `make_smartctl_usable_by_sudoers.sh`

I think this is fine now, i do not have any error messages in my logs anymore :)
I guess i am not alone in this case...

**Comment by claudiux** [comment]
Thank you for reporting that! I'll adapt this script to the user's distro.
