### ISSUE TITLE
Feed is broken

### ISSUE THREAD

**Issue by misterhsp** [linuxmint/cinnamon-spices-applets#4677]
Hi
The feed is no longer working

https://github.com/linuxmint/cinnamon-spices-applets/commits/master.atom

Thanks...

```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by fredcw** [comment]
Which applet?

**Comment by misterhsp** [comment]
Open the URL in the browser, the applet will be named there.



Am 08.02.23 um 23:30 schrieb fredcw:

**Comment by misterhsp** [comment]
```
XML Parsing Error: not well-formed
Location: https://github.com/linuxmint/cinnamon-spices-applets/commits/master.atom
Line Number 591, Column 9:
        [200~Radio3.0@claudiux:Update_Croatian_translation
--------^
```

**Comment by NeatNit** [comment]
Yup, there is a malformed character in the commit message of #4643 and it was preserved in the merge commit cd091881e3666162a5a600a23e922fded0f5d6d2.

I'm no git expert but I think it's not possible to retroactively change a commit message without messing up the git history (i.e. force push). So it's not easy to fix.

This sounds to me more like a GitHub issue than anything else - GitHub is the one generating the atom feed, and it's supposed to guarantee a valid atom feed. It also raises the question of how the control character got into the commit message in the first place, and why git and/or GitHub allowed it.

**Comment by misterhsp** [comment]
Is it not enough that the commit is corrected and uploaded again?

**Comment by NeatNit** [comment]
> Is it not enough that the commit is corrected and uploaded again?

Yes, it can be done, but this is "rewriting history" which is generally not advised in Git. It causes everyone working on the repository to "de-sync". It's not disastrous by any means, but it's just not "natural" for git.

Either way, though - as I said, the next time anyone makes any change in the master branch, it will fix your issue. The bad commit is the 20th most recent commit in the master branch. Only the last 20 commits are in the feed. So next time anyone pushes anything, the bad commit will become 21st most recent and won't be included in the atom feed anymore. Problem solved!

**Comment by claudiux** [comment]
Ping @muzena @mtwebster
