### ISSUE TITLE
Multi-Core System Monitor (multicore-sys-monitor@ccadeptic23) applet won't open, no preferences accessible

### ISSUE THREAD

**Issue by MintCinnamon5-6-5** [linuxmint/cinnamon-spices-applets#4693]
To: multicore-sys-monitor@ccadeptic23
I am running Linux Mint 21.1 Cinnamon Desktop 5.4.5
Fresh install
The applet won't open
Preferences aren't accessible
There is a minimal spacer in the desktop panel, which when clicked on, gives the system stats, l guess that is all l can get from the applet at present.

I have had this applet in previous installs, and it displays graphical data quite nicely, including bars for each CPU core.

Graphics hardware: NVIDIA Corporation GM206 [GeForce GTX 950]

**Comment by claudiux** [comment]
@MintCinnamon5-6-5 

Are there any messages in `~/.xsession-errors` regarding this applet?

**Comment by MintCinnamon5-6-5** [comment]
Sorry l don't know how to do that.

**Comment by MintCinnamon5-6-5** [comment]
I have not observed any graphical notification of error. Just an apparently successful invisible install.

**Comment by claudiux** [comment]
> Sorry l don't know how to do that.

You can use the xsession applet: https://cinnamon-spices.linuxmint.com/applets/view/362

**Comment by claudiux** [comment]
Is it installed on a real or a virtual machine?

**Comment by seliver** [comment]
This is due to the newer version of cinnamon in the mint 21.1. Check the workaround in https://github.com/linuxmint/cinnamon-spices-applets/pull/4665

**Comment by MintCinnamon5-6-5** [comment]
> Is it installed on a real or a virtual machine?
> 
> It works well on my real machine, but it doesn't work on my virtual machines.

It's a real machine and it tastes of heavy metals
@seliver  thank you for the proposed solution. I have downgraded to Mint 20.3 due to this issue and another one with the bundled LibreOffice Writer (imported image gets an unchangeable margin on the Writer page, cannot be moved past this arbitrary margin). Sadly the LibreOffice Writer bug is still there, so l may need to upgrade to Mint 21.1 again. At least in Mint 20.3 the present issue with the Multi-Core System Monitor no longer exists. I guess l'll have to move back up to Mint 21.1 for about the 2nd or 3rd time.

I do wonder how small the volunteer testing base for this distro is. Bye for now @claudiux and @seliver - I will return if the proposed fix doesn't work.

**Comment by MintCinnamon5-6-5** [comment]
> This is due to the newer version of cinnamon in the mint 21.1. Check the workaround in #4665

@seliver I'm very sorry but I still cannot make this work.
I am currently in Linux Mint 21.1
I opened terminal, and entered:

mkdir -p ~/.config/cinnamon/spices

I then rebooted.
Nothing changed.

**Comment by seliver** [comment]
You ran the wrong command. Check the link again.

**Comment by git-minix** [comment]
I just installed Linux Mint 21 and tried to activate the Multi-Core System Monitor in cinnamon. Same symptoms.  

- Fresh install
- The applet won't open
- Preferences aren't accessible

~/.xsession-errors

`** (csd-power:1725): CRITICAL **: 03:27:29.477: abs_to_percentage: assertion 'max > min' failed
`

see also 
https://github.com/linuxmint/cinnamon/issues/9671

> It seems to be caused by certain applet, possibly the hardware monitor. As a workaround one can use different applet or completely disable it.

**Comment by git-minix** [comment]
** (csd-power:1725): CRITICAL **: 03:27:29.477: abs_to_percentage: assertion 'max > min' failed 

points to an issue with an other applet.

The Multi-Core System Monitor issue described here is solved with 

`#mkdir -p ~/.cinnamon/configs
`

The applet could not store the config file.

**Comment by claudiux** [comment]
@MintCinnamon5-6-5 @seliver @git-minix 
I just made a PR that will close this issue: #4756
