### ISSUE TITLE
StarkMenu: broken after update

### ISSUE THREAD

**Issue by deekej** [linuxmint/cinnamon-spices-applets#47]
Today, I have updated the StarkMenu@mintystark, and here's the result:
![bad](https://cloud.githubusercontent.com/assets/6081285/22462780/ff813296-e7ae-11e6-9a20-aaf786ab5081.png)

As you can see, the menu items text is gone, and the icons are moved to the edge.

So, after doing downgrade (I have backup of all applets), I get back to menu properly displaying:
![good](https://cloud.githubusercontent.com/assets/6081285/22462786/06e3c6b6-e7af-11e6-89f6-4009f03c30bf.png)

I'm using Fedora 25, with LightDM and Cinnamon 3.2.8. The theme I'm using is Arc-Darker theme (the fork of it is used in Linux Mint).

**Comment by NikoKrause** [comment]
Which Cinnamon Version have you used to create the bottom screenshot?

Die I understand it right, that you upgraded and downgraded the StarkMenu applet and not Cinnamon?

**Comment by NikoKrause** [comment]
Either way, the StarkMenu is not maintained anymore. As far as I know it's broken since Cinnamon 2.6. 

I forked it, but have not uploaded it on spices yet.
You can install it manually in the meantime, if you want to:
https://github.com/NikoKrause/CinnVIIStarkMenu

**Comment by deekej** [comment]
Well, the StarkMenu was working for me for some time. I don't know which version of Cinnamon I was using when I installed it first. (I was moving my /home folder with me since then, and I was occasionally doing updates of the applets).

So, what happened here:
0) I've read about how Cinnamon is stepping in, to do an intermediary between applet developers and users, to protect to users etc.
1) I decided to update my applets. I have downloaded all the updates (they were automatically installed).
2) I restarted the cinnamon after that (ALT+F2, write 'r' and hit Enter)
3) StarkMenu started to be distorted (see 1st screenshot)
4) I downgraded the StarkMenu via my local backup & restarted cinnamon. It was again working now (see 2nd screenshot).

Here's the diff of the `old`(working) and `latest`(distorted) version (ignore the dates, please):
```diff
--- old/applet.js	2016-03-19 19:13:16.000000000 +0100
+++ new/applet.js	2017-02-01 17:43:32.478946555 +0100
@@ -247,7 +247,7 @@ function TransientButton(appsMenuButton,
 }
 
 TransientButton.prototype = {
-    __proto__: AppPopupSubMenuMenuItem.prototype,
+    __proto__: PopupMenu.PopupSubMenuMenuItem.prototype,
 
     _init: function(appsMenuButton, pathOrCommand) {
         let displayPath = pathOrCommand;
@@ -590,83 +590,8 @@ function TextBoxItem(label, icon, func,
     this._init(label, icon, func, parent, hoverIcon);
 }
 
-function AppPopupSubMenuMenuItem() {
-    this._init.apply(this, arguments);
-}
-
-
-
-AppPopupSubMenuMenuItem.prototype = {
-    __proto__: PopupMenu.PopupBaseMenuItem.prototype,
-
-    _init: function(text, hide_expander) {
-        PopupMenu.PopupBaseMenuItem.prototype._init.call(this);
-
-        this.actor.add_style_class_name('popup-submenu-menu-item');
-
-        let table = new St.Table({ homogeneous: false,
-                                      reactive: true });
-
-        if (!hide_expander) {
-            this._triangle = new St.Icon({ icon_name: "media-playback-start",
-                                icon_type: St.IconType.SYMBOLIC,
-                                style_class: 'popup-menu-icon' });
-
-            table.add(this._triangle,
-                    {row: 0, col: 0, col_span: 1, x_expand: false, x_align: St.Align.START});
-
-            this.label = new St.Label({ text: text });
-            this.label.set_margin_left(6.0);
-            table.add(this.label,
-                    {row: 0, col: 1, col_span: 1, x_align: St.Align.START});
-        }
-        else {
-            this.label = new St.Label({ text: text });
-            table.add(this.label,
-                    {row: 0, col: 0, col_span: 1, x_align: St.Align.START});
-        }
-        this.actor.label_actor = this.label;
-        this.addActor(table, { expand: true, span: 1, align: St.Align.START });
-
-        this.menu = new PopupMenu.PopupSubMenu(this.actor, this._triangle);
-        this.menu.connect('open-state-changed', Lang.bind(this, this._subMenuOpenStateChanged));
-    },
-
-    _subMenuOpenStateChanged: function(menu, open) {
-        this.actor.change_style_pseudo_class('open', open);
-    },
-
-    destroy: function() {
-        this.menu.destroy();
-        PopupBaseMenuItem.prototype.destroy.call(this);
-    },
-
-    _onKeyPressEvent: function(actor, event) {
-        let symbol = event.get_key_symbol();
-
-        if (symbol == Clutter.KEY_Right) {
-            this.menu.open(true);
-            this.menu.actor.navigate_focus(null, Gtk.DirectionType.DOWN, false);
-            return true;
-        } else if (symbol == Clutter.KEY_Left && this.menu.isOpen) {
-            this.menu.close();
-            return true;
-        }
-
-        return PopupMenu.PopupBaseMenuItem.prototype._onKeyPressEvent.call(this, actor, event);
-    },
-
-    activate: function(event) {
-        this.menu.open(true);
-    },
-
-    _onButtonReleaseEvent: function(actor) {
-        this.menu.toggle();
-    }
-};
-
 TextBoxItem.prototype = {
-    __proto__: AppPopupSubMenuMenuItem.prototype,
+    __proto__: PopupMenu.PopupSubMenuMenuItem.prototype,
 
     _init: function (label, icon, func, parent, hoverIcon) {
         this.parent = parent;
@@ -674,7 +599,7 @@ TextBoxItem.prototype = {
         this.icon = icon;
         this.func = func;
         this.active = false;
-        AppPopupSubMenuMenuItem.prototype._init.call(this, label);
+        PopupMenu.PopupSubMenuMenuItem.prototype._init.call(this, label);
 
         this.actor.set_style_class_name('menu-category-button');
         this.actor.add_style_class_name('menu-text-item-button');
@@ -682,7 +607,6 @@ TextBoxItem.prototype = {
         //this.removeActor(this.label);
         this.label.destroy();
         //this.removeActor(this._triangle);
-       
         this._triangle.destroy();
         this._triangle = new St.Label();
         this.label_text = label;
@@ -776,10 +700,10 @@ function AllProgramsItem(label, icon, pa
 }
 
 AllProgramsItem.prototype = {
-    __proto__: AppPopupSubMenuMenuItem.prototype,
+    __proto__: PopupMenu.PopupSubMenuMenuItem.prototype,
 
     _init: function (label, icon, parent) {
-        AppPopupSubMenuMenuItem.prototype._init.call(this, label);
+        PopupMenu.PopupSubMenuMenuItem.prototype._init.call(this, label);
 
         this.actor.set_style_class_name('');
         this.box = new St.BoxLayout({ style_class: 'menu-category-button' });
@@ -966,13 +890,13 @@ function ShutdownMenu(parent, hoverIcon)
 }
 
 ShutdownMenu.prototype = {
-    __proto__: AppPopupSubMenuMenuItem.prototype,
+    __proto__: PopupMenu.PopupSubMenuMenuItem.prototype,
 
     _init: function (parent, hoverIcon) {
         let label = '';
         this.hoverIcon = hoverIcon;
         this.parent = parent;
-        AppPopupSubMenuMenuItem.prototype._init.call(this, label);
+        PopupMenu.PopupSubMenuMenuItem.prototype._init.call(this, label);
         this.actor.set_style_class_name('menu-category-button');
         //this.removeActor(this.label);
         this.label.destroy();
```

**Comment by NikoKrause** [comment]
@deekej 
You must have "fixed" StarkMenu by yourself some months ago.
This looks exactly like this Pull Request https://github.com/mintystark/starkmenu/pull/11, which has never been merged into StarkMenu.

> I've read about how Cinnamon is stepping in, to do an intermediary between applet developers and users, to protect the users, etc.

The change to the spices is pretty new. It will need some time, to get rid of most of the bugs. So far we haven't been able to test and fix all applets. There are over 200 applets.
A lot of the applets are abandoned or doubled and some need to be fixed or removed.
There's still some work to do.
We still have to see, which applets are still in development by their authors. Which authors are still active or willing to jump on the bandwagon. E.g. Odyseus, jaszhix are very active. Others as mintystark are gone a long time ago.

As for StarkMenu it is abandoned quite some time. As I mentioned above, I suspect that you have fixed it on your own, by adding the pull request manually. It was never updated on spices though.

For example: The checkboxes "Show bookmarks and places" and "Show recent files" in the menusettings of your fixed/working StarkMenu are broken, right?

I would recommend CinnVIIStarkMenu. It will be available here very soon. Or you can test it manually, if you can't wait. I don't think StarkMenu will be fixed, if we have a working fork of it. Unless mintystark happens to reappear and fixes it (I doubt it).

So a lot of work is still to do. Help is always appreciated.

And thanks for the feedback. It helps to know, which applets are actually used and need to be fixed in priority :)

**Comment by NikoKrause** [comment]
I recommend to use CinnVIIStarkMenu. It's a fork of the StarkMenu with many bug fixes and new features. It's now available on Cinnamon Spices Website, which means that it can be installed through System Settings > Applets > Available Applets (online)

**Comment by deekej** [comment]
> For example: The checkboxes "Show bookmarks and places" and "Show recent files" in the menusettings of your fixed/working StarkMenu are broken, right?

Yes, you're right. I just checked it, and I'm unable to disable those.

> I recommend to use CinnVIIStarkMenu. It's a fork of the StarkMenu with many bug fixes and new features. 

Actually, I didn't know about the fork. Thanks for the info. I will try it whenever I have time. :)

Anyway, seems like the number of applets will be growing really fast soon (if it isn't already), because of all the abandoned applets and new forka appearing. Here I would suggest, sooner the better you should come up with some policy on how to deal with applets where developer is inactive and updated/active fork of it exits.

My suggestions would be to implement a way the old/inactive applets would be deprecated/obsoleted, and at some point removed from your "applets repository".
