### ISSUE TITLE
vboxlauncher - show machine status [feature]

### ISSUE THREAD

**Issue by tgaertner** [linuxmint/cinnamon-spices-applets#471]
For me the applet makes only sense if it would show the status of the virtual machine e.g. "running" 
Could be an icon or even just a color.

**Comment by NikoKrause** [comment]
Notifying author @mockturtl

**Comment by mockturtl** [comment]
I like the idea of the feature, but the applet essentially just [runs a shell command](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/vboxlauncher%40mockturtl/files/vboxlauncher%40mockturtl/applet.js#L213).

- Do you have design and/or implementation ideas?
- Can you give a more specific description of your use case, or the problem it solves? (Personally, I rarely use  a VM -- I would never forget one is running)

**Comment by tgaertner** [comment]
Hi,
My use case is this: I use Vagrant with VirtualBox for developing web-projects. I configured the virtual machines with the same IP-Adress for automation-reasons. I often have to switch between Projects, so I have to stop the running machine and start another one (because running two machines with the same IP results in conflicts and unexpected behaviour). I mean I have to start/stop the machines with the vagrant-commands anyway but it would help a lot if I had an indicator what machine is running. I have now the VirtualBox Manager open all the time.

Maybe my use case is too special, but I think having little indicators for each machine and maybe also the possibility to start, stop, suspend, resume the machines directly from the tray would be very nice - for everybody using VirtualBox.

Using the status icons from VirtualBox would make sense for me.
Looking at the tray from the external drives ... something like this. Status icon in front of each line and on the right like the "unmount-icon" some action icons like start, stop (and may some more)

Should be possible if I look e.g. at the tray from the sound-applet...

I never did something like this and and have sadly no time to dive into it, so I can give no help for implementing, but I could do a little design-shot if this helps.

Greetings from Germany

**Comment by mockturtl** [comment]
@NikoKrause maybe tag this with FEATURE-REQUEST?

**Comment by xearonet** [comment]
@mockturtl 
Hi. i use this applet too and I've some ideas.
IMHO start/stop vm feature should be option controlled. I want to use this and 'll be nice to turn off this.
However, different color to running vm would be very nice and useful.

**Comment by Centurix** [comment]
There's similar functionality in my Homestead/Vagrant controller which uses the switch menu item to control the VM status: [Rancher](https://github.com/linuxmint/cinnamon-spices-applets/tree/master/rancher%40centurix)

**Comment by tgaertner** [comment]
Nice - but does only work with Homestead... a general solution for vagrant would be very nice!!

**Comment by xearonet** [comment]
Hi. I wrote some code that add running indicator to list. In couple days I commit it. Bye

**Comment by tgaertner** [comment]
Thx, 'll check it out!

**Comment by xearonet** [comment]
Hi. It should be working now. Please give some feedback.

@tgaertner

**Comment by tgaertner** [comment]
Yes THANKS this is working and VERY helpful!! For me it would be perfect to be able to start my vagrant machines from it. But they has to be started via vagrant command. But this is not the approach of THIS applet I think. There need to be a "vagrantLauncher" Applet for this, maybe I'll do it someday for it seems not to exist jet.
Thanks anyway for your work - your applet is now in use :-) and this ticket can be closed!

**Comment by xearonet** [comment]
maybe this be good enough:
https://github.com/linuxmint/cinnamon-spices-applets/blob/master/rancher%40centurix/README.md

**Comment by tgaertner** [comment]
thnx but it seams not to work without Homestead
