### ISSUE TITLE
color-picker@fmete breaks when using display scaling. Almost always picks color #000000

### ISSUE THREAD

**Issue by mrmatteastwood** [linuxmint/cinnamon-spices-applets#4711]
I don't know how to find out the applet's UUID, unfortunately.

```
 * Applet version/Build date: "About" screen says "Updated on 2023-02-14 09:54:44"
 * Cinnamon version (cinnamon --version): 5.6.7
 * Distribution - Linux Mint 21.1 Vera (base: Ubuntu 22.04 jammy)
 * Graphics hardware *and* driver used: NVIDIA GeForce RTX 3080 Ti Laptop GPU/PCIe/SSE2 v: 4.6.0 NVIDIA 525.85.05
 * Snippet or attachment of ~/.cinnamon/glass.log: can't find that file on my system
 * Snippet or attachment of ~/.xsession-errors: attached

[xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/10910819/xsession-errors.txt)

 ```

**Notify author of applet**
@icarter09

**Issue**
Color picker doesn't pick the correct colors. It mostly picks color #000000, regardless of where the user clicks. Video: https://youtu.be/24Eutz8kiDo. Issue only occurs when display scaling is set to a value other than 100%.

**Steps to reproduce**
1. Install color picker and required packages, xclip and python3-xlib
2. Set display scaling to 125%
3. Try to pick colors

**Expected behaviour**
Color picker should pick the correct colors.

**Other information**
Full PC specs: https://termbin.com/jmf4i

**Comment by BlessedDisco** [comment]
Created a pull request to fix this issue. Hopefully it can be merged soon
