### ISSUE TITLE
weather@mockturtl need alittle change for german translation

### ISSUE THREAD

**Issue by bignexus** [linuxmint/cinnamon-spices-applets#4719]
Hello, first i want say ty for the great applet. But i hope you can change a little bit in the German translation.. The applet shows > Dev Point < - for German is not translate...  but the german word is > Taupunkt < hope you can change it in near future ..

**Comment by Gr3q** [comment]
I meant to do this earlier.

It's a bit more complicated than you think, the translation file needs to be updated with the latest changes from the template, and that messes up other translations. And I don't speak German so I can't really do it myself.

So if you could edit the attached file with [Poedit](https://poedit.net/download/), fix the translations marked with yellow, translate whatever you feel you want to, then attach it to a comment here, and I will include it in the next version.

File: [de.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/10999544/de.po.zip)

**Comment by bignexus** [comment]
Hello,
i have change in the de.po file for english word > Dev Point < to the german word > Taupunkt < 
the translation is new, its not from the marked with yellow 
[de.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/11002339/de.po.zip)

**Comment by Gr3q** [comment]
The yellow ones are incorrect due to the fact that I had to update the file - via Poedit - with the latest additions. Poedit marks them as yellow after it's done merging the 2 files, they need to be fixed before I can use the file again.

**Comment by bignexus** [comment]
I've edited and translated all of them... Hope it fits now.
[de.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/11009565/de.po.zip)

**Comment by Gr3q** [comment]
Thanks, I will include this in the next release
