### ISSUE TITLE
[NEED HELP] Applet stops loading after changing system language

### ISSUE THREAD

**Issue by Severga** [linuxmint/cinnamon-spices-applets#4751]
My applet kdeccc@Severga now stopped loading if to change sys language to Russian. It gives an error. It cannot find ")". But I have checked the code, and it's ok. Moreover, it loads normally in English UI. There are no any brackets in the Russian translation.
Please, help me find the problem. May be, some symbols which can't be used in translation files?..

**Comment by claudiux** [comment]
@Severga 

  * Set sys language to English.
  * $ `cd ~/.local/share/cinnamon/applets/kdeccc@Severga`
  * $ `cjs applet.js`

This error message appears:
```
(cjs:79636): Gjs-CRITICAL **: 15:03:24.060: JS ERROR: SyntaxError: missing ) after argument list @ applet.js:114

(cjs:79636): Gjs-CRITICAL **: 15:03:24.060: Script applet.js threw an exception
```

The error is present in line 144 of applet.js. Change it from:
`this.set_applet_tooltip(_"No reachable paired devices"));`
to:
`this.set_applet_tooltip(_("No reachable paired devices"));`

**Comment by Severga** [comment]
Thank you very much!
