### ISSUE TITLE
calendar@cinnamon.org: Bing back world clock :)

### ISSUE THREAD

**Issue by igorsantos07** [linuxmint/cinnamon-spices-applets#4761]
```
 * Applet version/Build date 1.2.2 (2023-01-26 04:52:12)
 * Cinnamon version 5.6.5
 * Distribution Mint 21.1
 ```

**Notify author of applet**
The calendar official applet does not show up in `CODEOWNERS`

**Issue**
Not sure if "bring back" makes sense at all, but it was a feature present in Mate and, IIRC, Gnome 2. This is _so_ missing that someone made a clone calendar _just_ to add it (ccprog's version). Please, incorporate those features and reduce the duplicate code :)

**Comment by fredcw** [comment]
The default applets (@cinnamon.org) are in the https://github.com/linuxmint/cinnamon repository.

**Comment by igorsantos07** [comment]
Moved to https://github.com/linuxmint/cinnamon/issues/11579
Sorry, @fredcw!
