### ISSUE TITLE
weather@mockturl - the applet can't get data

### ISSUE THREAD

**Issue by ihola777** [linuxmint/cinnamon-spices-applets#4762]
```
 * Applet version - 3.2.12
 * Cinnamon version - 5.6.8
 * Distribution - Linux 5.15.0-67-generic 74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 GNU/Linux
 * Graphics hardware - 00:02.0 VGA compatible controller: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620] rev 02
```

**Notify author of applet**
@Gr3q

**Issue**
Error calling URL: Could not connect: Socket I/O timed out, null

**Steps to reproduce**

**Expected behaviour**

**Other information**

ip-api.com refused to connect
seems like the route lost
traceroute ip-api.com
![image](https://user-images.githubusercontent.com/38958623/226205473-0b9b85a9-d612-40d1-934f-8d41994640d4.png)

<details>
<summary>Relevant Logs</summary>

```
The contents of the file saved from the applet help page goes here
```

</details>

**Comment by Gr3q** [comment]
It seems not Hungary is the only place they more or less block now.

Please use manual location for now, I'll look for a different location provider.
