### ISSUE TITLE
[kdecapplet@joejoetv] Configuration Dialog Not Launching With KDE Connect 22.12.3

### ISSUE THREAD

**Issue by rcalixte** [linuxmint/cinnamon-spices-applets#4772]
**Notify author of applet**
@JoeJoeTV (thank you again for this applet!)

**Issue**
The package kdeconnect 22.12.3, available in the repositories for Debian 12 and Ubuntu 23.04, leads to the applet being unable to load the configuration options from either the "Configure KDE Connect" applet menu option or from the "Open KDE Connect Configuration" button in the applet options.

**Steps to reproduce**
Install kdeconnect 22.12.3 and attempt to launch the configuration options through the applet. No error messages appear in the Cinnamon or system logs.

**Expected behaviour**
Selecting either option launches the configuration dialog.

**Other information**
I took a look through the code for the kdeconnect application to see what changed. I'm not sure if this will help. I also wasn't able to find where or what to patch in the applet right away when I looked. Another complication is that this isn't bound by the version of Cinnamon or version of the underlying operating system, strictly the version of the kdeconnect application/daemon that is installed.
```bash
--- main.qml	21.12.3
+++ main.qml	22.12.3
@@ -40,7 +40,7 @@
     Plasmoid.preferredRepresentation: isConstrained ? Plasmoid.compactRepresentation : Plasmoid.fullRepresentation
 
     function action_launchkcm() {
-        DaemonDbusInterface.openConfiguration()
+        OpenConfig.openConfiguration()
     }
 
     Component.onCompleted: {

```

**Comment by JoeJoeTV** [comment]
Hi,

Most problems with the applet will probably only stem from KDE Connect, as the DBus interface I use in the Applet for communicating with KDE Connect often changes between versions. That is also the reason, why my applet has a compatability level for  specific versions(mostly the ones included in the Linux Mint releases, as I'm using Linux Mint and can test those)
Either check the Cinnamon "Looking Glass" (Right click on Panel -> sub menu with "Find Errors" or similar -> Looking Glass) for the message "Compatability Level: ..."or check directly in `~/.xsession-errors` for the line and please tell me what it says.
The Applet normally logs all errors to the same places, but I have added another error message, which you can try, by grabbing the "applet.js" file from [here](https://github.com/JoeJoeTV/cinnamon-spices-applets/tree/kdecapplet-kdeconnect-22.12.3/kdecapplet%40joejoetv/files/kdecapplet%40joejoetv), replacing the one you currently have (should be here: `~/.local/share/cinnamon/applets/kdecapplet@joejoetv/`) and reloading the applet using the context menu.
Then look in the Looking Glass or `~/.xsession-errors` for an error message after trying to open the configuration.

**Comment by rcalixte** [comment]
I saw the code for the compatibility check and after a cursory look, I still wasn't able to decipher that conditional to support the newer version.

With the changes to logging that you linked, it does now generate the desired error in the logs (pretty much confirming DBus changes as the root cause):
```
JS LOG: [LookingGlass/error] [kdecapplet@joejoetv/MINIMAL] Error while calling 'openConfiguration' DBus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method 'openConfiguration' in interface 'org.kde.kdeconnect.daemon' at object path '/modules/kdeconnect' (signature '')
```

A quick fix would be to place the `kcmshell5` command in the `else` block but I'm not sure how clean that would be long-term. (I've installed `kde-cli-tools` and modified it locally for now.)

I quickly tried to experiment with the DBus definitions locally but that didn't yield anything functional. I can at least PR the short-term fix while something longer-term can be put together.

With regards to the update to the README, I'm not sure how you want to proceed there. This workaround only works if users have and/or are aware to install `kde-cli-tools` on their systems or the DBus code changes get fixed by then.

Thanks again!

**Comment by JoeJoeTV** [comment]
@rcalixte Since you run the affected version, can you send me the output of the following command:
```sh
dbus-send --dest=org.kde.kdeconnect --print-reply --session --type=method_call /modules/kdeconnect org.freedesktop.DBus.Introspectable.Introspect
```
It calls the DBus method of the KDE Connect daemon that gives you the info about the existing methods on `/modules/kdeconnect`.
Maybe they just renamed the method and I have to change a small thing.

Also thanks for trying to fix this, but I want to first have a look at the output from the DBus method, since the DBus method call can return different errors than just the method not existing and one would want to see the error passed to the callback in `errorObj`.
The call to `kcmshell5 kcm_kdeconnect` was originally meant for older KDE Connect versions (e.g. 1.3) as the functionality to open the configuration using DBus wasn't present there AFAIK, but I want to do everything possible through DBus, so I don't have to use other tools kide `kcmshell5`

**Comment by rcalixte** [comment]
```bash
$ dbus-send --dest=org.kde.kdeconnect --print-reply --session --type=method_call /modules/kdeconnect org.freedesktop.DBus.Introspectable.Introspect
method return time=1679788408.753129 sender=:1.2895 -> destination=:1.6139 serial=142301 reply_serial=2
   string "<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
  <interface name="org.kde.kdeconnect.daemon">
    <method name="sendSimpleNotification">
      <arg name="eventId" type="s" direction="in"/>
      <arg name="title" type="s" direction="in"/>
      <arg name="text" type="s" direction="in"/>
      <arg name="iconName" type="s" direction="in"/>
    </method>
  </interface>
  <interface name="org.kde.kdeconnect.daemon">
    <property name="isDiscoveringDevices" type="b" access="read"/>
    <property name="pairingRequests" type="as" access="read"/>
    <property name="customDevices" type="as" access="readwrite"/>
    <signal name="deviceAdded">
      <arg name="id" type="s" direction="out"/>
    </signal>
    <signal name="deviceRemoved">
      <arg name="id" type="s" direction="out"/>
    </signal>
    <signal name="deviceVisibilityChanged">
      <arg name="id" type="s" direction="out"/>
      <arg name="isVisible" type="b" direction="out"/>
    </signal>
    <signal name="deviceListChanged">
    </signal>
    <signal name="announcedNameChanged">
      <arg name="announcedName" type="s" direction="out"/>
    </signal>
    <signal name="pairingRequestsChanged">
    </signal>
    <signal name="customDevicesChanged">
      <arg name="customDevices" type="as" direction="out"/>
    </signal>
    <method name="acquireDiscoveryMode">
      <arg name="id" type="s" direction="in"/>
    </method>
    <method name="releaseDiscoveryMode">
      <arg name="id" type="s" direction="in"/>
    </method>
    <method name="forceOnNetworkChange">
    </method>
    <method name="announcedName">
      <arg type="s" direction="out"/>
    </method>
    <method name="setAnnouncedName">
      <arg name="name" type="s" direction="in"/>
    </method>
    <method name="devices">
      <arg type="as" direction="out"/>
      <arg name="onlyReachable" type="b" direction="in"/>
      <arg name="onlyPaired" type="b" direction="in"/>
    </method>
    <method name="devices">
      <arg type="as" direction="out"/>
      <arg name="onlyReachable" type="b" direction="in"/>
    </method>
    <method name="devices">
      <arg type="as" direction="out"/>
    </method>
    <method name="deviceNames">
      <arg type="a{ss}" direction="out"/>
      <annotation name="org.qtproject.QtDBus.QtTypeName.Out0" value="QMap&lt;QString,QString&gt;"/>
      <arg name="onlyReachable" type="b" direction="in"/>
      <arg name="onlyPaired" type="b" direction="in"/>
    </method>
    <method name="deviceNames">
      <arg type="a{ss}" direction="out"/>
      <annotation name="org.qtproject.QtDBus.QtTypeName.Out0" value="QMap&lt;QString,QString&gt;"/>
      <arg name="onlyReachable" type="b" direction="in"/>
    </method>
    <method name="deviceNames">
      <arg type="a{ss}" direction="out"/>
      <annotation name="org.qtproject.QtDBus.QtTypeName.Out0" value="QMap&lt;QString,QString&gt;"/>
    </method>
    <method name="deviceIdByName">
      <arg type="s" direction="out"/>
      <arg name="name" type="s" direction="in"/>
    </method>
    <method name="sendSimpleNotification">
      <arg name="eventId" type="s" direction="in"/>
      <arg name="title" type="s" direction="in"/>
      <arg name="text" type="s" direction="in"/>
      <arg name="iconName" type="s" direction="in"/>
    </method>
    <method name="selfId">
      <arg type="s" direction="out"/>
    </method>
  </interface>
  <interface name="org.freedesktop.DBus.Properties">
    <method name="Get">
      <arg name="interface_name" type="s" direction="in"/>
      <arg name="property_name" type="s" direction="in"/>
      <arg name="value" type="v" direction="out"/>
    </method>
    <method name="Set">
      <arg name="interface_name" type="s" direction="in"/>
      <arg name="property_name" type="s" direction="in"/>
      <arg name="value" type="v" direction="in"/>
    </method>
    <method name="GetAll">
      <arg name="interface_name" type="s" direction="in"/>
      <arg name="values" type="a{sv}" direction="out"/>
      <annotation name="org.qtproject.QtDBus.QtTypeName.Out0" value="QVariantMap"/>
    </method>
    <signal name="PropertiesChanged">
      <arg name="interface_name" type="s" direction="out"/>
      <arg name="changed_properties" type="a{sv}" direction="out"/>
      <annotation name="org.qtproject.QtDBus.QtTypeName.Out1" value="QVariantMap"/>
      <arg name="invalidated_properties" type="as" direction="out"/>
    </signal>
  </interface>
  <interface name="org.freedesktop.DBus.Introspectable">
    <method name="Introspect">
      <arg name="xml_data" type="s" direction="out"/>
    </method>
  </interface>
  <interface name="org.freedesktop.DBus.Peer">
    <method name="Ping"/>
    <method name="GetMachineId">
      <arg name="machine_uuid" type="s" direction="out"/>
    </method>
  </interface>
  <node name="devices"/>
</node>
"
```

It looks like it was either moved or removed from its previous location.

**Comment by JoeJoeTV** [comment]
@rcalixte Hmm, strange, they probably moved it or something, since the change you mentioned seems to have moved the functionality inside the KDE Connect codebase. Maybe they moved it to another object path?
I don't really know how you can get the entire tree of available object paths for a dbus service in terminal, so maybe you can check the `org.kde.kdeconnect` service on the `Session Bus` using a tool like D-Feet or qdbus-viewer for anything that looks like it could help here.

**Comment by rcalixte** [comment]
This is what I meant when I said I looked around earlier. I looked through the source code as well and a cursory look suggests the configuration options dialog might now be a private class. I've yet to see any documentation or release notes to this effect though. If I have time, I can take a look through the commits to see if I can find something helpful.
