### ISSUE TITLE
sound@cinnamon.org - Applet does not scale icons or text with Text scaling factor adjustments

### ISSUE THREAD

**Issue by mknepper** [linuxmint/cinnamon-spices-applets#4781]
```
 * Version shipped with Linux Mint 21.1 'Vera' Cinnamon Edition 
 * Cinnamon 5.6.8
 * Mint 21.1, Sapphire PULSE Radeon RX 580 8GB,  * Graphics hardware *and* driver used
 * (cinnamon:1941): mutter-WARNING **: 16:23:51.951: Failed to store clipboard: Format image/png not supported
Gjs-Message: 16:24:54.376: JS LOG: [LookingGlass/info] [weather@mockturtl#19]: Weather Information refreshed
Gjs-Message: 16:39:54.869: JS LOG: [LookingGlass/info] [weather@mockturtl#19]: Weather Information refreshed
Gjs-Message: 16:54:55.323: JS LOG: [LookingGlass/info] [weather@mockturtl#19]: Weather Information refreshed
Gjs-Message: 17:09:55.817: JS LOG: [LookingGlass/info] [weather@mockturtl#19]: Weather Information refreshed
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x5e00325

 ```

**Notify author of applet**
sound@cinnamon.org

**Issue**

When text is scaled beyond 1.0, the sound applet does not render or display text correctly. Some of it is cut off or not aligned correctly. Note in the example below, the player icons are cut off and misaligned. The higher the font is scaled, the worse this becomes.

Image:
![image](https://user-images.githubusercontent.com/12740958/229242668-a193c380-c312-41a4-8de8-380fb0e35e39.png)

**Steps to reproduce**

Go to System Settings > Font Selection > Text scaling factor. Adjust to anything above 1.0 (mine was set to 1.4).

**Expected behaviour**

Sound applet, when clicked, will retain proper alignment and not cut off text.

**Other information**

I was unable to locate a version number after checking "About" or from reading the metadata.json and applet.js files. It is whatever ships with Linux Mint 'Vera' 21.1 Cinnamon Edition. 

The effect and misalignment/cutoff icons and text gets worse with higher scaling values and even has some artifacting. For example, this is set to 2.0 (you can see it's worse and has a artifact of a black line):

![image](https://user-images.githubusercontent.com/12740958/229243792-134f846e-aadb-41cb-a54d-019b22b57532.png)

This is reproduceable on these apps: Audacious (both the Mint repo and Flathub version), Microsoft Edge, Librewolf, VLC, Rhythmbox, Chromium, Firefox, etc... anything with media player capabilities.

**Comment by fredcw** [comment]
This is a problem with Mint-Y and Mint-X themes and probably mint-y legacy but I haven't checked.
