### ISSUE TITLE
weather@mockturtl wrong name of the german translation in the last update 

### ISSUE THREAD

**Issue by bignexus** [linuxmint/cinnamon-spices-applets#4783]
weather@mockturtl update 3.2.13 (https://github.com/linuxmint/cinnamon-spices-applets/pull/4755)

* Update da.po by @bignexus and increment version  <<<< thats wrong the german translation file have name de.po

**Comment by Gr3q** [comment]
Always this typo, sorry about the commit message. The file that I updated was actually `de.po` here https://github.com/Gr3q/cinnamon-spices-applets/blob/39446430095efad71ba173a19ba127af98b1893f/weather%40mockturtl/files/weather%40mockturtl/po/de.po
