### ISSUE TITLE
batterymonitor@pdcurtis: battery is charged notification - feature request

### ISSUE THREAD

**Issue by szabopeter** [linuxmint/cinnamon-spices-applets#4793]
In order to improve battery lifetime on all kinds of devices, it would be beneficial to have a notification for when the battery has reached an optimal level during charging, e.g. 80%, so that the user can disconnect the charger.
A separate battery applet just for this function does not seem feasible from a UX perspective.
Charge level could be configurable or fixed.
Turning this function off should be configurable.

**Comment by fredcw** [comment]
Ping @pdcurtis

**Comment by karolskolasinski** [comment]
please add this feature

**Comment by rcalixte** [comment]
@szabopeter I have this option available in the BIOS of a few machines so I'm a little unclear on the ask here. (I've unofficially taken up some of the maintenance of this applet which is why I ask.)

Is the goal just to have an optional notification displayed at a pre-configured charging threshold once it's reached? If so, I think this feature could be rolled out in the next few weeks (along with some other improvements I have in mind). Please shout if I have the wrong idea.

**Comment by karolskolasinski** [comment]
The goal is displaying notification when the battery reach charging threshold (configurable, for example 80%), just like alert "Rercentage Battery Charge at which Alert Displayed)

**Comment by szabopeter** [comment]
@rcalixte Yes, you got that right, the idea is just that, a notification once the level is reached. You're right that this is available on some machines, but there are two minor problems with that: 1. not all machines have this feature or it's limited (for example, you can only turn it on or off without specifying the charge level) 2. reconfiguration requires a reboot.

**Comment by rcalixte** [comment]
Agreed. I like the idea. I'll try to roll it out with the other changes I have in mind, hopefully within the next few weeks.

**Comment by rcalixte** [comment]
@szabopeter @karolskolasinski The code for version 2.0 includes this requested feature. If you have a chance to test before it is reviewed and released, please do. One caveat is that I was not able to implement a solution regarding hibernation.

In the hibernation example scenario, if you have the alert set to show at 80% but hibernated your machine while it was below 80% and then charged it above 80% before powering back on, the alert will still show. The best that I could think of for now was to have the alert show with accurate details. In the event of a lock screen, it might not even be an issue that gets noticed. Other than this, it should work as expected/requested. Shout if that's not the case!

**Comment by szabopeter** [comment]
Thank you!

I've tried to test it but I failed.
What I did:
- cloned the repo, checked out the bams_2 branch
- copied `batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/` to my `~/.local/share/cinnamon/applets/`
- restart (I've tried logout+login first but also a complete reboot the next time)

The applet works and shows the new version number, but the configuration screen did not have the new content.
It's definitely me doing something wrong but if you have a hint or a link on how to test properly, I'd give it another go.

**Comment by rcalixte** [comment]
Hmm, you should be able to copy from the cloned repo with something like `cp -pr batterymonitor@pdcurtis/files/batterymonitor@pdcurtis ~/.local/share/cinnamon/applets/` and then reloading the applet or restarting Cinnamon should load the applet. (Mind the trailing slashes.)

If that doesn't work, you can remove the 5.4 directory entirely from `~/.local/share/cinnamon/applets/batterymonitor@pdcurtis` and re-running the copy command above.

**Comment by rcalixte** [comment]
@szabopeter I'm going to go ahead and merge the pull request. If you had modified it locally, you will just need to edit the `metadata.json` file to append:
`'last-edited: 0'`
in order to receive updates.

Otherwise, no further changes will be required.
