### ISSUE TITLE
Is there any way to keep updates from wiping my CSS settings each time? 

### ISSUE THREAD

**Issue by dkop11** [linuxmint/cinnamon-spices-applets#4809]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by claudiux** [comment]
@dkop11 
You can use the SpicesUpdate applet. In its settings, go to the 'Applets' tab and uncheck the applets you don't want to update.

**Comment by fredcw** [comment]
I don't understand this question. What css settings do you mean?

**Comment by dkop11** [comment]
> I don't understand this question. What css settings do you mean?

BAMS > Housekeeping and System Submenu > Open stylesheet.css (Advanced Function) 
To alter the colors.

**Comment by fredcw** [comment]
The applet is batterymonitor@pdcurtis

There's a comment in the stylesheet that says:

>The applet checks for a file called stylesheet.css in folder batterymonitor@pdcurtis in your Home Folder.
if this is present then the default stylesheet is overwritten the next time the applet is started.
A further restart of the applet is then required before the applet uses the new stylesheet.

Have you tried this?

**Comment by dkop11** [comment]
Ok, just copied it from /home/me/.local/share/cinnamon/applets/batterymonitor@pdcurtis/5.4 to /home/me/.config/cinnamon/spices/batterymonitor@pdcurtis. The one in the .local folder is the one that keeps getting over-written.

**Comment by fredcw** [comment]
No, that's the wrong location. You need to create a new folder called: `/home/me/batterymonitor@pdcurtis/` and put your stylesheet.css in there. When the applet starts up it looks for `/home/me/batterymonitor@pdcurtis/stylesheet.css`  and if it finds it, it copies it to `/home/me/.local/share/cinnamon/applets/batterymonitor@pdcurtis/5.4` to replace the default one. Then you have to restart the applet so that cinnamon reads the new stylesheet for the applet.

**Comment by dkop11** [comment]
Thanks, will try that!

**Comment by rcalixte** [comment]
@dkop11 The latest version for this applet will deprecate the stylesheet.css functionality, removing the manual management required for it and replacing it with native configuration options. The native options will be much more resilient in the event of future upgrades and should only require configuration once.

The built-in color chooser supports all colors and transparency options. If you're not familiar with the color chooser, you can simply paste in the hex or RGB values from your local stylesheet while also tuning the transparency with the bar below (right-click opens the numerical option for tuning transparency values).
![Screenshot from 2023-07-09 17-46-32](https://github.com/linuxmint/cinnamon-spices-applets/assets/10281587/c2e27750-b929-452f-9004-6440673b1dab)


I've included a screenshot of what the new options will look like:
![Screenshot from 2023-07-09 17-42-48](https://github.com/linuxmint/cinnamon-spices-applets/assets/10281587/df8424bb-5510-44de-b237-5754721c6261)

If you have a chance to test before it's reviewed and released or if you have any thoughts, please feel free to let me know!

**Comment by dkop11** [comment]
Perfect!
