### ISSUE TITLE
Sensors@claudiux: Applet started to complain about missing package gdouros-symbola-fonts

### ISSUE THREAD

**Issue by MatthiasMann** [linuxmint/cinnamon-spices-applets#4828]
I was not able to locate a UUID for this applet

```
Sensors Monitor (Sensors@claudiux) Version 2.0.3 (2023-04-01 21:40:50)
Cinnamon 5.6.8
Linux Mint 21.1 Cinnamon
AMD RX7900XTX with Mesa 23.1.0-rc3

 ```

**Issue**
Starting today the applet complains about a missing package "gdouros-symbola-fonts" in a popup dialog and a desktop notification "You appear to be missing some of the programs required for this applet to have all its features."
This package doesn't seem to exists for Ubuntu derived distributions - and I have installed a symbola font which is used to display the Fan icon.

**Steps to reproduce**
Reload the applet

**Expected behaviour**
No such popup / message

**Other information**

**Comment by fredcw** [comment]
Ping @claudiux

**Comment by claudiux** [comment]
@MatthiasMann 

Please execute this command:
`apt install fonts-symbola apturl`

**Comment by MatthiasMann** [comment]
apturl is already the newest version (0.5.2+linuxmint13).
fonts-symbola is already the newest version (2.60-1.1).

**Comment by claudiux** [comment]
Your distro is detected as fedora or openSUSE. Can you copy here the return of the command:

`cat /etc/os-release | grep "ID="`

please?

**Comment by MatthiasMann** [comment]
$ cat /etc/os-release | grep "ID="
ID=linuxmint
VERSION_ID="21.1"

**Comment by claudiux** [comment]
Edit `/.local/share/cinnamon/applets/Sensors@claudiux/lib/checkDependencies.js` and replace the get_distro function (beginning line 213) by this one:

```
function get_distro() {
  let distro = DISTRO();
  switch (distro) {
    case "debian":
    case "arch":
    case "fedora":
      return distro;
    case "linuxmint":
    case "ubuntu":
      return "default";
    default:
      if (isArchLinux()) {
        return "arch";
      } else if (isFedora()) {
        return "fedora";
      } else if (isOpenSUSE()) {
        return "openSUSE"
      }
      return "default"; // linuxmint or ubuntu
  }
} // End of get_distro
``` 

Then restart this applet or restart Cinnamon.

**Comment by MatthiasMann** [comment]
That worked - thanks!
