### ISSUE TITLE
applets not work >> placesCenter@scollins - places-with-terminal@mtwebster - places-bookmarks@dmo60.de

### ISSUE THREAD

**Issue by bignexus** [linuxmint/cinnamon-spices-applets#4839]
placesCenter@scollins
places-with-terminal@mtwebster
places-bookmarks@dmo60.de

```
 
 * Cinnamon 5.6.8
 * Distribution - Mint 21.1 
 * GTK 3.24.33
 ```

**Issue**
At April 28, 2023 I  found that nothing will launch from the placesCenter@scollins applet. It doesn't appear to attempt to do anything. It the terminal icon is visible, those work. But it won't launch Nemo when I click on any item on the menu.

Ihave the same isusses with places-with-terminal@mtwebster and places-bookmarks@dmo60.de

Steps to reproduce
Click on any item on the Places  Launcher menu.

Expected behaviour
Clicked folder is launched in Nemo.

Other information
I have removed/re-added the applet several times. I have added places-with-terminal@mtwebster and places-bookmarks@dmo60.de applet, no one work

ihave capture the isusses as video.. you can see here >> https://drive.google.com/file/d/1qhdOdTzImOBzTrtEC4D2OU8lyH1T2YsJ/view?usp=sharing

**Comment by claudiux** [comment]
Are there any messages about this in your ~/.xsession-errors file? ( You can use the Xsession applet to monitor its content: https://cinnamon-spices.linuxmint.com/applets/view/362 )

**Comment by bignexus** [comment]
Gjs-Message: 20:46:53.973: JS LOG: [LookingGlass/info] Reloading applet: placesCenter@scollins/38
Gjs-Message: 20:46:54.107: JS LOG: [LookingGlass/info] Loaded applet placesCenter@scollins in 113 ms
Window manager warning: placesCenter-open - Overwriting existing binding of keysym 70 with keysym 70 (keycode 21).
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
/usr/bin/wslview: line 216: /mnt/c/Windows/System32/reg.exe: No such file or directory
/usr/bin/wslview: line 308: [: -ge: unary operator expected
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
/usr/bin/wslview: line 216: /mnt/c/Windows/System32/reg.exe: No such file or directory
/usr/bin/wslview: line 308: [: -ge: unary operator expected

**Comment by claudiux** [comment]
Are you using wslu on your system ? Is your partition usually mounted on /mnt well mounted?

**Comment by bignexus** [comment]
bigjr@gartenzwerg:~$ mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=16281956k,nr_inodes=4070489,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=3279384k,mode=755,inode64)
/dev/nvme0n1p3 on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=33870)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
none on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
tmpfs on /run/qemu type tmpfs (rw,nosuid,nodev,relatime,mode=755,inode64)
/dev/nvme0n1p2 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3279380k,nr_inodes=819845,mode=700,uid=1000,gid=1000,inode64)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
portal on /run/user/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000

Sy.. have no real idea why  its say /mnt ... icant remember im mount anything to /mnt

**Comment by claudiux** [comment]
I suggest you:

  - Right-click on the placesCenter icon and select Configure...
  - Click on the 'More options...' button at the top-right of the just opened Settings window.
  - Select 'Export to...' and save your configuration into the `~/Desktop/placesCenter@scollins.json` file. Close the Settings window.
  - Open, if it exists, the '~/.cinnamon/configs' directory: `xdg-open ~/.cinnamon/configs` then remove the 'placesCenter@scollins' folder.
  - If you have installed the Xsession applet, use it to restart the  'placesCenter@scollins'  applet. If not, re-open the previous Settings window and use the same menu to reload its code. Now 'placesCenter@scollins' must be functional. You can import its previous configuration. Test if all is OK.

**Comment by bignexus** [comment]
i have use both way.. test is failed...  here the log after reload cinnamon.
Gjs-Message: 22:21:47.183: JS LOG: About to start Cinnamon
Gjs-Message: 22:21:47.207: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 22 ms
Gjs-Message: 22:21:47.209: JS LOG: [LookingGlass/info] loading user theme: /usr/share/themes/Linux Mint/cinnamon/cinnamon.css
Gjs-Message: 22:21:47.220: JS LOG: [LookingGlass/info] added icon directory: /usr/share/themes/Linux Mint/cinnamon
Gjs-Message: 22:21:47.297: JS LOG: [LookingGlass/info] loaded at Wed May 03 2023 22:21:47 GMT+0200 (Mitteleuropäische Sommerzeit)
Gjs-Message: 22:21:47.297: JS LOG: Cinnamon started at Wed May 03 2023 22:21:47 GMT+0200 (Mitteleuropäische Sommerzeit)
Gjs-Message: 22:21:47.297: JS LOG: GPU offload supported: false
Gjs-Message: 22:21:47.303: JS LOG: [LookingGlass/info] ExtensionSystem started in 1 ms
Gjs-Message: 22:21:47.303: JS LOG: [LookingGlass/info] SearchProviderManager started in 0 ms
Gjs-Message: 22:21:47.388: JS LOG: [LookingGlass/info] Role locked: tray
Gjs-Message: 22:21:47.390: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 51 ms
Gjs-Message: 22:21:47.394: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 4 ms
Gjs-Message: 22:21:47.436: JS LOG: [LookingGlass/info] [weather@mockturtl#33]: Internet access now available, resuming operations.
Gjs-Message: 22:21:47.444: JS LOG: [LookingGlass/info] Loaded applet weather@mockturtl in 50 ms

(cinnamon:2011): Clutter-CRITICAL **: 22:21:47.478: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Gjs-Message: 22:21:47.487: JS LOG: [LookingGlass/info] Loaded applet radio@driglu4it in 43 ms
Gjs-Message: 22:21:47.494: JS LOG: [LookingGlass/info] Loaded applet cornerbar@cinnamon.org in 7 ms
Gjs-Message: 22:21:47.498: JS LOG: [LookingGlass/info] Loaded applet favorites@cinnamon.org in 4 ms
Gjs-Message: 22:21:47.499: JS LOG: [LookingGlass/info] Config file /home/bigjr/.local/share/cinnamon/desklets/TimeAndDate@nightflame/metadata.json
Gjs-Message: 22:21:47.501: JS LOG: [LookingGlass/info] Loaded desklet TimeAndDate@nightflame in 3 ms
Gjs-Message: 22:21:47.512: JS LOG: [LookingGlass/info] Loaded desklet quoteOfTheDay@tinnu in 11 ms
Gjs-Message: 22:21:47.539: JS LOG: [LookingGlass/info] Loaded applet printers@cinnamon.org in 27 ms
Gjs-Message: 22:21:47.542: JS LOG: [LookingGlass/info] Role locked: notifications
Gjs-Message: 22:21:47.546: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 7 ms
Gjs-Message: 22:21:47.563: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 17 ms
Gjs-Message: 22:21:47.573: JS LOG: [LookingGlass/info] Loaded applet xsession@claudiux in 10 ms
Gjs-Message: 22:21:47.582: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 9 ms
Gjs-Message: 22:21:47.585: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 2 ms
Gjs-Message: 22:21:47.605: JS LOG: [LookingGlass/info] Loaded desklet googleCalendar@javahelps.com in 20 ms
Gjs-Message: 22:21:47.612: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 7 ms
Gjs-Message: 22:21:47.650: JS LOG: [LookingGlass/info] Loaded applet placesCenter@scollins in 38 ms
Gjs-Message: 22:21:47.650: JS LOG: [LookingGlass/info] DeskletManager started in 348 ms
Gjs-Message: 22:21:47.655: JS LOG: calendar@cinnamon.org: Calendar events supported.
Gjs-Message: 22:21:47.667: JS LOG: [LookingGlass/info] Role locked: panellauncher
Gjs-Message: 22:21:47.667: JS LOG: [LookingGlass/info] Role locked: windowattentionhandler
Gjs-Message: 22:21:47.669: JS LOG: [LookingGlass/info] Loaded applet grouped-window-list@cinnamon.org in 19 ms

** (csd-power:1905): CRITICAL **: 22:21:47.674: abs_to_percentage: assertion 'max > min' failed
Gjs-Message: 22:21:47.675: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: nm-applet (:1.46/org/x/StatusIcon/Icon)
Gjs-Message: 22:21:47.678: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: blueman (:1.42/org/x/StatusIcon/Icon)
Gjs-Message: 22:21:47.688: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintreport (:1.108/org/x/StatusIcon/Icon)
Gjs-Message: 22:21:47.690: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: process-monitor (:1.108/org/x/StatusIcon/Icon_1)
Gjs-Message: 22:21:47.691: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintUpdate.py (:1.88/org/x/StatusIcon/Icon)
Gjs-Message: 22:21:47.709: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 40 ms
Gjs-Message: 22:21:47.749: JS LOG: [LookingGlass/info] Hiding XAppStatusIcon (we have an applet): nm-applet (:1.46/org/x/StatusIcon/Icon)
Gjs-Message: 22:21:47.753: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 44 ms
Gjs-Message: 22:21:47.836: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 83 ms
Gjs-Message: 22:21:47.837: JS LOG: [LookingGlass/info] AppletManager started in 538 ms
Gjs-Message: 22:21:47.838: JS LOG: [LookingGlass/info] Cinnamon took 655 ms to start
Gjs-Message: 22:21:47.845: JS LOG: Unknown network device type, is 14
Gjs-Message: 22:21:47.853: JS LOG: Unknown network device type, is 13
Gjs-Message: 22:21:47.853: JS LOG: Unknown network device type, is 30
Window manager warning: switch-monitor - Overwriting existing binding of keysym 70 with keysym 70 (keycode 21).
Gjs-Message: 22:21:48.427: JS LOG: [LookingGlass/info] [weather@mockturtl#33]: Weather Information refreshed
Gjs-Message: 22:21:51.482: JS LOG: Enabling WindowAttentionHandler
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
/usr/bin/wslview: line 216: /mnt/c/Windows/System32/reg.exe: No such file or directory
/usr/bin/wslview: line 308: [: -ge: unary operator expected

**Comment by bignexus** [comment]
ok ithink we stop here.. im looking if i find a way with another theme... and report next days.. so for moment ty
