### ISSUE TITLE
[Sensors@claudiux] pam_unix floods the log

### ISSUE THREAD

**Issue by git70** [linuxmint/cinnamon-spices-applets#4846]
```
Applet version: 3.0.1
Cinnamon version: 5.6.8
Distribution: LMDE5 + LM19.3
 ```

**Notify author of applet**
@claudiux

**Issue**
The auth.log is flooded (according to the set refresh interval, 1s for me) with the following entry:
```
user@host:~$ tail -f /var/log/auth.log
Apr 24 18:45:02 host sudo: pam_unix(sudo:auth): conversation failed
Apr 24 18:45:02 host sudo: pam_unix(sudo:auth): auth could not identify password for [user]
```

**Steps to reproduce**
Temperature tab -> Disk Temperature Sensors section -> selecting Show In Panel triggers the flood (***instead of showing the disk temperature*** on the panel)
![flood](https://github.com/linuxmint/cinnamon-spices-applets/assets/49098178/0eea8655-dc0d-4d90-9d03-174e2714bfb4)

**Other information**
https://github.com/linuxmint/linuxmint/issues/576

**Comment by claudiux** [comment]
@git70 Please execute the script:

`~/.local/share/cinnamon/applets/Sensors@claudiux/scripts/pkexec_make_smartctl_usable_by_sudoers.sh`

Then, to be sure, restart your computer.

**Comment by claudiux** [comment]
I tried first this: https://unix.stackexchange.com/questions/327301/how-to-stop-sudo-pam-messages-in-auth-log-for-a-specific-user-on-ubuntu-16-04 but it doesn't work.

The other way I plan is not to use sudo but to run smartctl as root for all users with the command:
`sudo chmod u+s /usr/sbin/smartctl`
but that seems more risky.

**Comment by claudiux** [comment]
I've found the solution!
Edit the `~/.local/share/cinnamon/applets/Sensors@claudiux/scripts/make_smartctl_usable_by_sudoers.sh` script. Replace its contents with :
```
#!/bin/bash
[[ $UID -eq 0 ]] || exit 1

echo "%sudo ALL = NOPASSWD:NOLOG_INPUT:NOLOG_OUTPUT: /usr/sbin/smartctl" | sudo tee "/etc/sudoers.d/smartctl"
echo "%wheel ALL = NOPASSWD:NOLOG_INPUT:NOLOG_OUTPUT: /usr/sbin/smartctl" | sudo tee -a "/etc/sudoers.d/smartctl"

exit 0
```

Then execute in a terminal:
`sudo ~/.local/share/cinnamon/applets/Sensors@claudiux/scripts/pkexec_make_smartctl_usable_by_sudoers.sh`

No more floods in auth.log!

**Comment by claudiux** [comment]
@git70 Did you try that?

**Comment by claudiux** [comment]
@git70 
I hope your computer will be fixed soon.
The use of `smartctl` is reserved for sudoers. This means that the rights required to use `smartctl` are not lowered (no `chmod` on smartctl).
