### ISSUE TITLE
[SpicesUpdate@claudiux] Does not show updated or new spices

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#4850]
```
 * Applet version/Build date: 6.4.2 (2023-04-14 19:29:13)
 * Cinnamon version: 5.6.8
 * Distribution: Mint 21.1
 * Snippet or attachment of ~/.xsession-errors (see below)
 ```

**Notify author of applet**
@claudiux 

**Issue**
`SpicesUpdate` stopped to work some time ago. It neither shows updated or new spices when checking automatically or manually.

**Steps to reproduce**
- Start a manual check from the spice's menu.
- The icon starts to spin and then stops after some time, but neither a notification is displayed nor the icon colour changes.

**Expected behaviour**
- There should be notifications and the colour of the icon should change.

**Other information**
Everything worked previously and then I noticed, that I do not get notifications anymore. It is hard (or virtually impossible) to pinpoint when that happened.

I checked the notification and the test notification is displayed.

The update manager and the applets system setting both show the updated spices.

Parts of the `.xsession-errors` files I think are relevant to `SpicesUpdates`:

System startup:
```
js-Message: 07:59:02.811: JS LOG: [LookingGlass/info] 
[SpicesUpdate@claudiux] 07:59:02: now=1683784743 ; this.general_next_check_date=1683784803

Gjs-Message: 07:59:02.856: JS LOG: [LookingGlass/info] Loaded applet SpicesUpdate@claudiux in 151 ms
```

Manual check (the update manager shows new versions for some spices):
```
js-Message: 21:21:04.663: JS LOG: [LookingGlass/info] 
[SpicesUpdate@claudiux] 21:21:04: Checking for applets

Gjs-Message: 21:21:04.676: JS LOG: [LookingGlass/info] 
[SpicesUpdate@claudiux] 21:21:04: Is it time to check? true. Now: 1683832865. Ne
xt: 1683833165. Interval: 7200

Gjs-Message: 21:21:04.844: JS LOG: [LookingGlass/info] 
[SpicesUpdate@claudiux] 21:21:04: Checking for desklets

Gjs-Message: 21:21:04.851: JS LOG: [LookingGlass/info] 
[SpicesUpdate@claudiux] 21:21:04: Is it time to check? true. Now: 1683832865. Next: 1683833165. Interval: 7200

Gjs-Message: 21:21:04.855: JS LOG: [LookingGlass/info] 
[SpicesUpdate@claudiux] 21:21:04: Checking for extensions

Gjs-Message: 21:21:04.860: JS LOG: [LookingGlass/info] 
SpicesUpdate@claudiux] 21:21:04: Is it time to check? true. Now: 1683832865. Next: 1683833165. Interval: 7200

Gjs-Message: 21:21:04.869: JS LOG: [LookingGlass/info] 
[SpicesUpdate@claudiux] 21:21:04: Checking for themes

Gjs-Message: 21:21:04.880: JS LOG: [LookingGlass/info] 
[SpicesUpdate@claudiux] 21:21:04: Is it time to check? true. Now: 1683832865. Next: 1683833165. Interval: 7200
```

I know, this is not much to work on, so feel free, if you need any debugging or some tests.

**Comment by claudiux** [comment]
I just updated 17 applets with SpicesUpdate... but I need to rewrite this applet to better take into account the Cinnamon system for updating spices. Please be patient, I'm working on it.

**Comment by sphh** [comment]
So this is a known problem with the spices website access limits?

Maybe a simple notification to tell the user this when it occurs for the first time in a session, might be helpful (and probably quick to implement).

Thanks for looking into this!

**Comment by claudiux** [comment]
If you make multiple successive requests to the website, it temporarily blocks your IP; the server becomes unreachable.

**Comment by sphh** [comment]
I see. But both the `Update Manager` and the manual update from `System Settings > Applets` do show the updated applets. Do they use a different mechanism than `SpicesUpdate`?

**Comment by sphh** [comment]
Today was the first time for some months, that `SpicesUpdate` showed me a notification (it was telling me that a new applet [`Power Profiles`](https://cinnamon-spices.linuxmint.com/applets/view/369) is available) … I have not changed any of my settings!

**Comment by claudiux** [comment]
I will rewrite some parts of this applet's code that are not compatible with Cinnamon 5.8.

**Comment by sphh** [comment]
Good to hear. But I am on cinnamon version 5.6.8. Are these changes affecting this version as well?

**Comment by claudiux** [comment]
Yes, I will fix some bugs, too.
