### ISSUE TITLE
Radio++ controls not working on LMDE 2

### ISSUE THREAD

**Issue by jonath92** [linuxmint/cinnamon-spices-applets#4863]
This is a response on the conversion on: https://cinnamon-spices.linuxmint.com/applets/view/297. Unfortunately I can't answer there directly anymore because I always get an error when clicking on "Submit". 

> wgetting it to .cinammon/configs and running the mpv command works fine, it also correctly reacts to playerctl

Can you also control mpv with playerctl (or the sound applet) when you start the radio applet? This should be possible. Also can you confirm that you see the pause/donwload/copy/stop button after clicking on a channel? When this is the case we definitely know that the root of the problem is not the plugin. 

In that case I only could imagine that the onClick action is for some reason not triggered when you click on a toolbar button. And for that I could image two reasons: Some weird stuff in the theme (so maybe trying with another theme) or some breaking change in gjs. So maybe you can try to replace the lines 4743-4745 of ~/.local/share/cinnamon/applets/radio@driglu4it/4.6/radio-applet.js: 
        if (button !== 3) {
            onActivated === null || onActivated === void 0 ? void 0 : onActivated();
        }

 with just `onActivated()`. This might also be a good starting point for debugging (e.g. adding a global.log here to see if this line is executed when clicking on a toolbar button). Although I would recommend to use the typescript files directly for a more in depth-analyisis.

**Comment by SebiTimeWaster** [comment]
i would click a station name and it would start playing (also it would react correctly to playerctl), but it would still look like this (so not show any controls):
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/3726309/1e08c568-446f-4573-85b4-fa9d6329b78a)

i reinstalled the applet multiple times, even remove every file/directory i could find with "driglu4it" in it, and it would not work. then when i started debugging i restarted cinammon (ctrl + alt + esc) and it suddenly worked.

no clue what was the problem in the forst place. on first install i clicked to not install mpris in the first place (wanted to find out what that is first), maybe that broke it somehow...

ill try to reproduce that. give me minute.

**Comment by SebiTimeWaster** [comment]
no, not reproducible.

thanks for your help.

Ich wünsche dir noch einen schönen Tag :)

**Comment by SebiTimeWaster** [comment]
@jonath92 it happened again, the radio was playing but it showed no controls in the popup or radio station name in the task bar.

reloading Cinnamon fixed it (Ctrl + Alt+ Esc).

**Comment by Aggtaa** [comment]
Same here. Installed it, added to a panel once - was working flawlessly.
After a reboot shows no controls, only station list.

Also clicking on a new station in the list starts it without stopping the previous ones in a new player. Clicking stop button in Sound applet menu stops all players one by one.

Reloading with Ctrl+Alt+Esc does not help. Reinstalling the applet does not help either.

Linux Mint 21.2 Cinnamon
Cinnamon 5.8.4
Radio++ Version 2.2.3 (2023-08-23 11:20:42)

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/2315863/2b606035-ad3e-4479-aa60-69ca26a9a0cd)

**Comment by blausand** [comment]
**Confirm**, still the case. Mint 21.3 here.
I dance the whole "_stop several concurrent radio-streams sequentially via sound-applet_" shenanigans on a daily base.
Also, radio++ captures the focus so hard that even the hardware power button does nothing unless I leave the menu, which consumes one click that is hence not bubbled to it's destination.

_Essential applet, no bad vibes here, but would really appreciate these being fixed._
