### ISSUE TITLE
[Sensors@claudiux] Double separator error

### ISSUE THREAD

**Issue by git70** [linuxmint/cinnamon-spices-applets#4886]
```
Applet version: 3.0.1
Cinnamon version: 5.6.8
Distribution: LMDE5
```
**Notify author of applet**
@claudiux

**Issue**
After last commit [8171665f] Sensors@claudiux: added functionality to user define a separator string (#4868)
all entered separators are displayed double `||` instead of `|`, `//` instead of `/` and so on

**Comment by claudiux** [comment]
I can't reproduce that.

**Comment by claudiux** [comment]
Ok, I see where the problem is.

**Comment by claudiux** [comment]
Fixed:  #4887

**Comment by claudiux** [comment]
No, none of my applets update themselves.

**Comment by claudiux** [comment]
Please take a look to your mintupdate settings. Perhaps you've checked the automatic spice update option?
