### ISSUE TITLE
show-hide-applets@mohammad-sn not working on LM 21.1 Cinnamon 5.6.8

### ISSUE THREAD

**Issue by JoseOlin** [linuxmint/cinnamon-spices-applets#4908]
Drawer (show/hide applets) it's not working.

It used to work great in older versions and did the job very well.

 * Applet version/Build date: "last-edited": 1683827772
 * Cinnamon version: 5.6.8
 * Distribution: Linux Mint 21.1
 * Graphics hardware: GeForce MX130.  Driver used: xserver-xorg-video-noveau v 1.0.17-2build1
 * Snippet or attachment of ~/.cinnamon/glass.log **Couldn't find this one**
 

<details><summary>~/.xsession-errors</summary>
<p>

(cinnamon:1769): Gtk-WARNING **: 09:52:45.598: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Gjs-Message: 09:52:45.639: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 136 ms
Gjs-Message: 09:52:45.786: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 147 ms
Gjs-Message: 09:52:45.786: JS LOG: [LookingGlass/info] AppletManager started in 878 ms
Gjs-Message: 09:52:45.789: JS LOG: [LookingGlass/info] Cinnamon took 1024 ms to start
Gjs-Message: 09:52:45.796: JS LOG: Unknown network device type, is 14
Gjs-Message: 09:52:45.801: JS LOG: Unknown network device type, is 30
Gjs-Message: 09:52:45.806: JS LOG: [LookingGlass/info] Adding systray: ksnip (22x22px)
Gjs-Message: 09:52:45.808: JS LOG: [LookingGlass/info] Adding systray: megasync (22x22px)
Gjs-Message: 09:52:45.814: JS LOG: [LookingGlass/info] Adding systray: bitwarden1 (16x16px)
Gjs-Message: 09:52:45.815: JS LOG: [LookingGlass/info] Adding systray: superproductivity (16x16px)
Gjs-Message: 09:52:45.816: JS LOG: [LookingGlass/info] Hiding systray: network
Window manager warning: switch-monitor - Overwriting existing binding of keysym 70 with keysym 70 (keycode 21).
Gjs-Message: 09:52:49.305: JS LOG: Enabling WindowAttentionHandler
sys:1: Warning: g_hash_table_foreach: assertion 'version == hash_table->version' failed
Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
Gjs-Message: 10:09:48.812: Profiler is disabled. Not setting up signals.
Gjs-Message: 10:09:48.970: JS LOG: About to start Cinnamon
Gjs-Message: 10:09:49.006: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 33 ms
Gjs-Message: 10:09:49.008: JS LOG: [LookingGlass/info] loading user theme: /usr/share/themes/Mint-Y-Dark-Aqua/cinnamon/cinnamon.css
Gjs-Message: 10:09:49.020: JS LOG: [LookingGlass/info] added icon directory: /usr/share/themes/Mint-Y-Dark-Aqua/cinnamon
Gjs-Message: 10:09:49.132: JS LOG: [LookingGlass/info] loaded at Wed Jun 21 2023 11:09:49 GMT-0600 
Gjs-Message: 10:09:49.132: JS LOG: Cinnamon started at Wed Jun 21 2023 11:09:49 GMT-0600 
Gjs-Message: 10:09:49.132: JS LOG: GPU offload supported: false
Gjs-Message: 10:09:49.142: JS LOG: [LookingGlass/info] ExtensionSystem started in 1 ms
Gjs-Message: 10:09:49.142: JS LOG: [LookingGlass/info] SearchProviderManager started in 1 ms
Gjs-Message: 10:09:49.265: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 33 ms
Gjs-Message: 10:09:49.273: JS LOG: [LookingGlass/info] Loaded applet separator@cinnamon.org in 8 ms
Gjs-Message: 10:09:49.289: JS LOG: [LookingGlass/info] Loaded applet user@cinnamon.org in 16 ms
Gjs-Message: 10:09:49.296: JS LOG: [LookingGlass/info] Loaded applet xrandr@cinnamon.org in 7 ms
Gjs-Message: 10:09:49.301: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 5 ms
Gjs-Message: 10:09:49.301: JS LOG: [LookingGlass/info] Loaded applet separator@cinnamon.org in 0 ms
Gjs-Message: 10:09:49.303: JS LOG: [LookingGlass/info] Role locked: tray
Gjs-Message: 10:09:49.305: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 4 ms
Gjs-Message: 10:09:49.305: JS LOG: [LookingGlass/info] Loaded applet separator@cinnamon.org in 0 ms
Gjs-Message: 10:09:49.309: JS LOG: [LookingGlass/info] Loaded applet settings@cinnamon.org in 4 ms
Gjs-Message: 10:09:49.322: JS LOG: [LookingGlass/info] Loaded desklet hostcheck@schorschii in 13 ms
Gjs-Message: 10:09:49.334: JS LOG: [LookingGlass/info] Loaded applet printers@cinnamon.org in 12 ms
Gjs-Message: 10:09:49.350: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 16 ms
Gjs-Message: 10:09:49.355: JS LOG: [LookingGlass/info] Role locked: notifications
Gjs-Message: 10:09:49.367: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 17 ms
Gjs-Message: 10:09:49.368: JS LOG: [LookingGlass/info] DeskletManager started in 226 ms
Gjs-Message: 10:09:49.404: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 37 ms
Gjs-Message: 10:09:49.449: JS LOG: [LookingGlass/info] Loaded applet multicore-sys-monitor@ccadeptic23 in 45 ms
Gjs-Message: 10:09:49.463: JS LOG: [LookingGlass/info] Loaded applet temperature@fevimu in 14 ms
Gjs-Message: 10:09:49.469: JS LOG: [LookingGlass/info] Loaded applet workspace-switcher@cinnamon.org in 6 ms
Gjs-Message: 10:09:49.481: JS LOG: [LookingGlass/info] Loaded applet show-hide-applets@mohammad-sn in 12 ms
Gjs-Message: 10:09:49.496: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 14 ms
Gjs-Message: 10:09:49.595: JS LOG: [LookingGlass/info] Loaded applet placesCenter@scollins in 99 ms
Gjs-Message: 10:09:49.620: JS LOG: [LookingGlass/info] Role locked: panellauncher
Gjs-Message: 10:09:49.622: JS LOG: [LookingGlass/info] Loaded applet panel-launchers@cinnamon.org in 27 ms
Gjs-Message: 10:09:49.627: JS LOG: calendar@cinnamon.org: Calendar events supported.
Gjs-Message: 10:09:49.648: JS LOG: [LookingGlass/info] Role locked: windowattentionhandler
Gjs-Message: 10:09:49.652: JS LOG: [LookingGlass/info] Loaded applet grouped-window-list@cinnamon.org in 29 ms
Gjs-Message: 10:09:49.655: JS LOG: [LookingGlass/warning] 
QRedshift: Created
Gjs-Message: 10:09:49.657: JS LOG: [LookingGlass/warning] 
QRedshift: redshift-gtk should be removed
Gjs-Message: 10:09:49.673: JS LOG: [LookingGlass/warning] 
QRedshift: ADDED TO PANEL
Gjs-Message: 10:09:49.673: JS LOG: [LookingGlass/info] Loaded applet qredshift@quintao in 21 ms

** (csd-power:1631): CRITICAL **: 10:09:49.685: abs_to_percentage: assertion 'max > min' failed
Gjs-Message: 10:09:49.705: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 32 ms

(cinnamon:1769): Gtk-WARNING **: 10:09:49.850: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Gjs-Message: 10:09:49.920: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 215 ms
Gjs-Message: 10:09:50.073: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 153 ms
Gjs-Message: 10:09:50.073: JS LOG: [LookingGlass/info] AppletManager started in 941 ms
Gjs-Message: 10:09:50.076: JS LOG: [LookingGlass/info] Cinnamon took 1106 ms to start
Gjs-Message: 10:09:50.083: JS LOG: Unknown network device type, is 14
Gjs-Message: 10:09:50.088: JS LOG: Unknown network device type, is 30
Gjs-Message: 10:09:50.112: JS LOG: [LookingGlass/info] Adding systray: megasync (22x22px)
Gjs-Message: 10:09:50.114: JS LOG: [LookingGlass/info] Adding systray: ksnip (22x22px)
Gjs-Message: 10:09:50.121: JS LOG: [LookingGlass/info] Adding systray: superproductivity (16x16px)
Gjs-Message: 10:09:50.122: JS LOG: [LookingGlass/info] Adding systray: bitwarden1 (16x16px)
Gjs-Message: 10:09:50.124: JS LOG: [LookingGlass/info] Hiding systray: network
Window manager warning: switch-monitor - Overwriting existing binding of keysym 70 with keysym 70 (keycode 21).
Gjs-Message: 10:09:53.297: JS LOG: Enabling WindowAttentionHandler

</p>
</details>

**Comment by claudiux** [comment]
Ping @mohammad-sn

**Comment by fredcw** [comment]
@JoseOlin Could you be more specific, it seems to be working ok for me.

**Comment by JoseOlin** [comment]
> @JoseOlin Could you be more specific, it seems to be working ok for me.

Sure, I add a gif to show te behavior
![Drawer](https://github.com/linuxmint/cinnamon-spices-applets/assets/6277774/7ab56ee5-aa7f-45cd-8edd-f5d783f47d88)

It doesn't matter where I put the icon, it doesn't hide any other icons

I've tried dragging and dropping the other icons but to no avail, although I remember that it used to work to hide all the icons to their left.

**Comment by claudiux** [comment]
Mmmh, this applet should be rewritten. Using it, many error messages appear in `~/.xsession-errors`:

```Gjs-Message: 22:35:46.304: JS LOG: [LookingGlass/warning] Invalid or null source id used when attempting to run Mainloop.source_remove()
overrideDumpStack/global.dump_gjs_stack@/usr/share/cinnamon/js/ui/overrides.js:24:42
overrideMainloop/Mainloop.source_remove@/usr/share/cinnamon/js/ui/overrides.js:163:20
doAction@/home/claude/.local/share/cinnamon/applets/show-hide-applets@mohammad-sn/applet.js:146:22
on_panel_edit_mode_changed@/home/claude/.local/share/cinnamon/applets/show-hide-applets@mohammad-sn/applet.js:215:18
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
_init/<@/home/claude/.local/share/cinnamon/applets/show-hide-applets@mohammad-sn/applet.js:64:33
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
toggle@/usr/share/cinnamon/js/ui/popupMenu.js:941:14
activate@/usr/share/cinnamon/js/ui/popupMenu.js:933:18
_onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:153:14

Gjs-Message: 22:35:46.334: JS LOG: [LookingGlass/warning] Invalid or null source id used when attempting to run Mainloop.source_remove()
overrideDumpStack/global.dump_gjs_stack@/usr/share/cinnamon/js/ui/overrides.js:24:42
overrideMainloop/Mainloop.source_remove@/usr/share/cinnamon/js/ui/overrides.js:163:20
doAction@/home/claude/.local/share/cinnamon/applets/show-hide-applets@mohammad-sn/applet.js:146:22
on_panel_edit_mode_changed@/home/claude/.local/share/cinnamon/applets/show-hide-applets@mohammad-sn/applet.js:215:18
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
_init/<@/home/claude/.local/share/cinnamon/applets/show-hide-applets@mohammad-sn/applet.js:64:33
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
toggle@/usr/share/cinnamon/js/ui/popupMenu.js:941:14
activate@/usr/share/cinnamon/js/ui/popupMenu.js:933:18
_onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:153:14

Gjs-Message: 22:41:17.602: JS LOG: [LookingGlass/info] Reloading applet: c-eyes@anaximeno/121
Gjs-Message: 22:41:17.603: JS LOG: [LookingGlass/info] Reloading applet: text-to-speech-applet@cardsurf/141
Gjs-Message: 22:41:17.604: JS LOG: [LookingGlass/info] Reloading applet: rwall@typicalfoobar/157
Gjs-Message: 22:41:17.605: JS LOG: [LookingGlass/info] Reloading applet: show-hide-applets@mohammad-sn/166
Gjs-Message: 22:41:19.869: JS LOG: [LookingGlass/warning] Invalid or null source id used when attempting to run Mainloop.source_remove()
overrideDumpStack/global.dump_gjs_stack@/usr/share/cinnamon/js/ui/overrides.js:24:42
overrideMainloop/Mainloop.source_remove@/usr/share/cinnamon/js/ui/overrides.js:163:20
doAction@/home/claude/.local/share/cinnamon/applets/show-hide-applets@mohammad-sn/applet.js:146:22
on_panel_edit_mode_changed@/home/claude/.local/share/cinnamon/applets/show-hide-applets@mohammad-sn/applet.js:215:18
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
_init/<@/home/claude/.local/share/cinnamon/applets/show-hide-applets@mohammad-sn/applet.js:64:33
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
toggle@/usr/share/cinnamon/js/ui/popupMenu.js:941:14
activate@/usr/share/cinnamon/js/ui/popupMenu.js:933:18
_onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:153:14


(cinnamon:2328): St-CRITICAL **: 22:41:26.079: st_widget_get_theme_node called on the widget [0x56506619ed30 StBoxLayout.applet-box show-hide-applets-mohammad-sn-applet:checked] which is not in the stage.

(cinnamon:2328): St-CRITICAL **: 22:41:26.079: st_widget_get_theme_node called on the widget [0x5650638a0c60 StIcon.system-status-icon:last-child first-child] which is not in the stage.

(cinnamon:2328): St-CRITICAL **: 22:41:26.079: st_widget_get_theme_node called on the widget [0x56506619ed30 StBoxLayout.applet-box show-hide-applets-mohammad-sn-applet:checked] which is not in the stage.

(cinnamon:2328): St-CRITICAL **: 22:41:26.079: st_widget_get_theme_node called on the widget [0x5650638a0c60 StIcon.system-status-icon:last-child first-child] which is not in the stage.

(xapp-sn-watcher:2695): Gtk-CRITICAL **: 22:42:24.442: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(xapp-sn-watcher:2695): Gtk-CRITICAL **: 22:42:24.442: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
```

**Comment by claudiux** [comment]
However, this applet does the job (LM21.2 Cinnamon 5.8.4)

**Comment by JoseOlin** [comment]
> @JoseOlin I think it stopped working at one point but I can't reproduce it again. Does restarting cinnamon not make any difference? Have you tried removing and deleting the applet and then downloading it again? What are your settings for the applet? ( you can click on the gear icon on the config page and "export to file")

Interesting... on the bottom panel it works correctly. 
![DrawerBottomPanel](https://github.com/linuxmint/cinnamon-spices-applets/assets/6277774/a8cd4dd6-4ebe-4c4b-9815-fc0fc8f84e3b)


The problem is only when I place it on the top panel (which is where I have almost all my icons)

I add the config JSON
<details><summary>Details</summary>
<p>

    "head": {
        "type": "header",
        "description": "Settings for show-hide-applets@mohammad-sn"
    },
    "autohide": {
        "type": "checkbox",
        "default": true,
        "description": "Autohide",
        "tooltip": "check if you want to hide applets automatically, unless you should click on applet to do so",
        "value": true
    },
    "disablestarttimeautohide": {
        "type": "checkbox",
        "default": false,
        "description": "Disable start time autohide",
        "tooltip": "if not in autohide mode",
        "value": false
    },
    "hidetime": {
        "type": "spinbutton",
        "default": 2,
        "min": 0.25,
        "max": 10,
        "step": 0.25,
        "units": "seconds",
        "dependency": "autohide",
        "description": "Autohide after ",
        "tooltip": "",
        "value": 2
    },
    "hoveractivates": {
        "type": "checkbox",
        "default": true,
        "description": "Activate on hover",
        "tooltip": "show applets on mouse hover",
        "value": true
    },
    "hoveractivateshide": {
        "type": "checkbox",
        "default": false,
        "dependency": "hoveractivates",
        "description": "Hide on hovering again",
        "tooltip": "toggle visibility of applets on mouse hover",
        "value": false
    },
    "hovertime": {
        "type": "spinbutton",
        "default": 75,
        "min": 10,
        "max": 500,
        "step": 5,
        "units": "miliseconds",
        "dependency": "hoveractivates",
        "description": "Hover activates/hides after ",
        "tooltip": "",
        "value": 75
    },
    "autohiders": {
        "type": "checkbox",
        "default": true,
        "description": "Autohide reshowing applets",
        "tooltip": "",
        "value": true
    },
    "autohiderstime": {
        "type": "spinbutton",
        "default": 1.25,
        "min": 0,
        "max": 5,
        "step": 0.25,
        "units": "seconds",
        "dependency": "autohiders",
        "description": "Reshowers' autohide delay: ",
        "tooltip": "",
        "value": 1.25
    },
</p>
</details>

**Comment by JoseOlin** [comment]
Hi @edofe99 In my case it works normally if I place it on the default Cinnamon bar, but if I add a second bar on that one it doesn't work, even if I restart Cinnamon. 

So I decided to put the icons that I don't use often in the bottom panel and then Drawer applets hides them correctly.

**Comment by claudiux** [comment]
Solved!
