### ISSUE TITLE
Sensors@claudiux disk temperature reading issue!

### ISSUE THREAD

**Issue by nikto1** [linuxmint/cinnamon-spices-applets#4929]
Took me a while to find it out but indirectly your applet filled up my whole partition (150GB!!) with security email alerts because the "feature" (lol) didn't have root access to read the disk temperatures:

Received: (nullmailer pid 160323 invoked by uid 1000);
	Sat, 08 Jul 2023 01:44:02 -0000
To: root@username
From: username@username
Auto-Submitted: auto-generated
Subject: *** SECURITY information for username ***
Date: Sat, 08 Jul 2023 03:44:02 +0200
Message-Id: <1688780642.908062.160322.nullmailer@username>

username : Jul  8 03:44:02 : username : a password is required ; PWD=/home/username ; USER=root ; COMMAND=/usr/sbin/smartctl -A /dev/sdb

Authentication log was also HUGE with/ without root access because each second the applet logs in/ out to read disk temperatures; if there's no root access system writes following authentication error each second anyway:

sudo: pam_unix(sudo:auth): conversation failed
pam_unix(sudo:auth): auth could not identify password for username

**Comment by claudiux** [comment]
@nikto1 

Please use the latest version (3.1.0) and run the command: 

```
~/.local/share/cinnamon/applets/Sensors@claudiux/scripts/pkexec_make_smartctl_usable_by_sudoers.sh
```

Tell me if that solves this issue.

**Comment by claudiux** [comment]
Fixed by #4916

**Comment by claudiux** [comment]
Please give me the contents of your `/etc/sudoers.d/smartctl` file, and the return of the command: `groups`.

**Comment by claudiux** [comment]
Please try v3.1.1.

**Comment by claudiux** [comment]
If you really have v3.1.1, then no disk temperature should appear in panel or tooltip... yet.

Select the Temperature tab in the settings of this applet. Nearly the bottom of this page, you should see the button: [Make disk temperature user-readable]. Click on. Enter your password. 

This button just execute the script: `~/.local/share/cinnamon/applets/Sensors@claudiux/scripts/pkexec_make_smartctl_usable_by_sudoers.sh`

The contents of `/etc/sudoers.d/smartctl` should become:

```
%sudo ALL = NOPASSWD:NOLOG_INPUT:NOLOG_OUTPUT:NOMAIL: /usr/sbin/smartctl
%wheel ALL = NOPASSWD:NOLOG_INPUT:NOLOG_OUTPUT:NOMAIL: /usr/sbin/smartctl
```

Please note the **NOMAIL:**

**Comment by claudiux** [comment]
**NOLOG_INPUT:NOLOG_OUTPUT:** fixes #4846. **NOMAIL:** fixes this one.

**Comment by claudiux** [comment]
LM, no. But this applet, yes.

**Comment by claudiux** [comment]
Please remove entirely this applet. Also remove `/etc/sudoers.d/smartctl` (with root rights).

Then download and reinstall it.

**Comment by claudiux** [comment]
I would have liked to know the return of the command: `cat /var/log/auth.log | grep smartctl`.

**Comment by claudiux** [comment]
Thank you. No new message for 3 hours?
