### ISSUE TITLE
Cinnamenu@json - add an option to choose a category by default when menu is open. [feature request]

### ISSUE THREAD

**Issue by Hilyxx** [linuxmint/cinnamon-spices-applets#4935]
**Notify author of applet**
@fredcw 

Please add an option to choose a category when menu is opening as accessories, music... 
There is "last category opened" option but when new session start, "all apps" view option is displayed by default.

**Comment by fredcw** [comment]
@Hilyxx Thanks for the suggestion and it's noted. But usually, unless a few people ask for the same feature, I don't like to add it because it makes the config UI and the applet code more complicated which I try to avoid as much as possible.

**Comment by Hilyxx** [comment]
@fredcw  Yes, of course . I understand and cinnamenu is great. This was a (very) personnal request and i don't want to add additional work for that.
