### ISSUE TITLE
Impossible to add a place into Météo (weather@mockturtl) applet

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/cinnamon-spices-applets#4980]
```
 * Applet version 3.3.0
 * Cinnamon version 5.8.4
 * Mint 21.2

 ```

**Notify author of applet**
@mockturtl

**Issue**

**Steps to reproduce**

Install Linux Mint Cinnamon 21.2 on a computer or a VM.
In Météo applet, choose DMI Denmark or OpenWeatherMap
Add a new place in Météo applet, with writing a Town
Wait
The place isn't recognized

**Expected behaviour**

The place should be recognized

**Other information**

On another computer, where Météo applet were already installed and parametrized, it still works, even after upgrading LM from 21.1 to 21.2 version.
I'm located in France.

**Comment by fredcw** [comment]
Ping @Gr3q

**Comment by InfoLibre** [comment]
:+1:
