### ISSUE TITLE
Manual location gives service error message weather@mockturtl applet

### ISSUE THREAD

**Issue by Zerophase** [linuxmint/cinnamon-spices-applets#4983]
```
 * version 3.3.0
 * Cinnamon version 5.8.4
 * Distribution - Arch

 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@Gr3q

**Issue**
manual locations do not seem to work anymore. Tried just putting the zipcode in, and I still receive the error message.

**Steps to reproduce**
1. Use VPN to change your location to another country
2. Enable manual location
3. add an address to manual location

**Expected behaviour**
Manual location should register

**Other information**
Trying to save the zip code  to my saved locations gives 'cannot save an incorrect location'

[glass.log](http
[xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/12255804/xsession-errors.txt)
s://github.com/linuxmint/cinnamon-spices-applets/files/12255788/glass.log)

**Comment by zecavalo** [comment]
Also have the same issue, manual location is not working.

**Comment by Frodoking21** [comment]
Same Issue

**Comment by Gr3q** [comment]
I will try to look at it this weekend, for now use raw coordinates in the entry.

I see they changed their API so it should be an easy fix
