### ISSUE TITLE
Sensors@claudiux — Make panel font follow theme font

### ISSUE THREAD

**Issue by Charlie-Harper** [linuxmint/cinnamon-spices-applets#4986]
**Notify author of applet**
@claudiux

**Issue**
Please, for better aesthetic integration, make the applet font displayed in the panel follow theme font. A monospaced font on the panel is out of harmony with the other fonts.

**Comment by claudiux** [comment]
Please try yourself:
Make a backup of `~/.local/share/cinnamon/applets/Sensors@claudiux/stylesheet.css`.

Edit `~/.local/share/cinnamon/applets/Sensors@claudiux/stylesheet.css` and remove each line containing `font-family: monospace;`

Restart Cinnamon. Tell me if the result suits you.

**Comment by claudiux** [comment]
Please note that I had set the font-family type to monospace because some users complained that the width of the applet varied according to the values displayed.

**Comment by claudiux** [comment]
From now on, the monospace font style is only used when size must be preserved.
