### ISSUE TITLE
[Sensors@claudiux] Another Double Separators Issue

### ISSUE THREAD

**Issue by My-Random-Thoughts** [linuxmint/cinnamon-spices-applets#5000]
```
 * v3.1.1 (2023-07-16)
 * Cinnamon 5.8.4
 * Mint 21.2 Cinnamon
 ```

**Notify author of applet**
@claudiux

**Issue**
When using a single `|` symbol for the separator, everything looks great.
If I then put a space either side to add some padding, extra symbols appear.

Just pipe symbol:
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/21334396/7f0aff0f-480a-44c3-8a3d-03a29734312e)

With spaces either side:
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/21334396/14b9040b-bcee-48c4-88b6-45da9646e612)

Thanks

**Comment by French77** [comment]
Try this start with a space then | followed by another space.

![Screenshot](https://i.imgur.com/0eACW8d.png"Screenshot")

**Comment by My-Random-Thoughts** [comment]
Nope, still the same issue no matter the order I try.
Note, not all my values are temperature values.  I think the issue is between the different types.

**Comment by claudiux** [comment]
Thank you for reporting this issue. I didn't think of the case where the separator contains more than a single character. I'll try to correct that soon.

**Comment by claudiux** [comment]
This problem now seems to be solved.
