### ISSUE TITLE
[sound150@claudiux] Sound icon doesn't switch to white or black 

### ISSUE THREAD

**Issue by Kile89** [linuxmint/cinnamon-spices-applets#5005]
@claudiux 

**Issue**

In the applet settings, there is a toggle option to change sound color icon if cinnamon theme is dark or light. 
But when cinnamon theme has a black panel, sound icon stays black instead of switching to white automatically.

![1](https://github.com/linuxmint/cinnamon-spices-applets/assets/142444870/45f516e5-1309-41d9-99da-3188e3966bdc)

![2](https://github.com/linuxmint/cinnamon-spices-applets/assets/142444870/81b393c5-4f53-4a34-b852-8be602820712)

**Steps to reproduce**
change your theme with white menu and black panel

**Other information**

If i remove:   **line 1025** "this.defaultColor = null; " in the code , sound icons automatically switch to white or black in the panel and menu with good color. 
This fix works with custom theme or mint official themes without using toggle color option.

![3](https://github.com/linuxmint/cinnamon-spices-applets/assets/142444870/f4b9a7e3-e4de-4178-b001-95740940dc0e)

LMDE 5 "elsie"
Cinnamon 5.6.8

**Comment by claudiux** [comment]
@Kile89 Issue fixed! Sorry for the delay.
