### ISSUE TITLE
QRedshift is not working after install

### ISSUE THREAD

**Issue by sf6gas** [linuxmint/cinnamon-spices-applets#5013]
```
 * Applet version/Build date 1.7.5
 * Cinnamon version - 5.84
 * Distribution - Mint 21.2
 * Graphics hardware *and* driver used - Intel Corporation Device a7a1 and rtw89-dkms version 1.0+klbkjammy16
 * Snippet or attachment of ~/.cinnamon/glass.log  (Tried running and got the error  ../.cinnamon/glass.log: No such file or directory)
 * Snippet or attachment of ~/.xsession-errors  (Tried running and got the error  ..xsession-errors: command not found)

 ```

**Notify author of applet**
qredshift@quintao

**Issue**
I installed Qredshift exactly how the instructions indicated and it does not work on my laptop.  Turning it on or off makes no change to my screen.

**Steps to reproduce**

**Expected behaviour**

**Other information**
I'm new to Linux but on my other conputer Qredshift works, I cannot figure out why it isn't working on this computer

**Comment by BDelacour** [comment]
+1

Uninstalled `redshift-gtk`, rebooted, but nothing happens

**Comment by claudiux** [comment]
Please post the contents of your `~/.xsession-errors` file.

**Comment by BDelacour** [comment]
Here it is : [xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/14887275/xsession-errors.txt)

**Comment by claudiux** [comment]
> cinnamon-session[1347]: WARNING: t+0.02210s: Could not read /home/bdelacour/.config/autostart/redshift-gtk.desktop: Could not parse desktop file redshift-gtk.desktop or it references a not found TryExec binary

In System settings -> Startup applications: Remove all reference to redshift-gtk.

**Comment by claudiux** [comment]
Use v1.7.6 and check the `Enable at startup` option.

**Comment by BDelacour** [comment]
I only found an occurrence to `redshift` that I removed. I also removed the `SpicesUpdate@claudiux` applet.

I selected `Enable at startup` in QRedshift but no improvement :cry: 
Here is my updated log file if you need : [xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/14893029/xsession-errors.txt)

**Comment by BDelacour** [comment]
Just tried a live boot from USB key. I installed QRedshift applet, uninstalled redshift-gtk sofware, activated QRedshift but same issue unfortunately.

**Comment by claudiux** [comment]
Please try these command lines:
`redshift -O 5741`
`redshift -O 3282`

See you any change on your screen after each of them?

**Comment by claudiux** [comment]
The problem seems to stem from these errors:

```
** (csd-color:1346): WARNING **: 11:02:41.327: failed to get edid: unable to get EDID for output

** (csd-color:1346): WARNING **: 11:02:41.331: unable to get EDID for xrandr-default: unable to get EDID for output

** (csd-color:1346): WARNING **: 11:02:41.331: failed to reset xrandr-default gamma tables: gamma size is zero
```

**Comment by claudiux** [comment]
Did you run the Driver Manager?

**Comment by BDelacour** [comment]
> Please try these command lines: `redshift -O 5741` `redshift -O 3282`
> 
> See you any change on your screen after each of them?

No change at all
```
bdelacour@bdelacour:~$ redshift -O 5741
Could not connect to wayland display, exiting.
Failed to start adjustment method wayland.
Trying next method...
Gamma ramp size too small: 0
Failed to start adjustment method randr.
Trying next method...
Using method `vidmode'.
bdelacour@bdelacour:~$ redshift -O 3282
Could not connect to wayland display, exiting.
Failed to start adjustment method wayland.
Trying next method...
Gamma ramp size too small: 0
Failed to start adjustment method randr.
Trying next method...
Using method `vidmode'.
```



> Did you run the Driver Manager?

And yes I did, but nothing to propose : 
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/18123038/ba8b78b1-19cb-485e-88db-ecb1267f9ccb)

FYI, I'm using the Edge ISO Edition of Linux Mint on a Lenovo X1 Carbon that I just bought

**Comment by BDelacour** [comment]
After investigating more in this direction, it looks like you're right : I'm missing a graphic driver...

```
bdelacour@bdelacour:~$ sudo lshw -c video
  *-display UNCLAIMED       
       description: VGA compatible controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 08
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list
       configuration: latency=0
       resources: iomemory:400-3ff iomemory:400-3ff memory:4058000000-4058ffffff memory:4000000000-400fffffff memory:c0000-dffff memory:405b000000-4061ffffff
  *-graphics
       product: EFI VGA
       physical id: 2
       logical name: /dev/fb0
       capabilities: fb
       configuration: depth=32 resolution=1920,1200
bdelacour@bdelacour:~$ lspci -k | grep -A2 VGA
00:02.0 VGA compatible controller: Intel Corporation Device 7d45 (rev 08)
	Subsystem: Lenovo Device 231e
	Kernel modules: i915
```

And my CPU is an Intel Core Ultra 7 155U

But my kernel is up-to-date 
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/18123038/3af15c3a-bbea-48a6-b2ad-011bcdccd10a)

I'm digging more but, from what I found until there, it should be included in the kernel

**Comment by BDelacour** [comment]
Well... Edge ISO was not enough for my hardware. Experimentally, I installed the mainline 6.7 Linux kernel and redshift now works like a charm !
But... I'm not so confident because I wasn't able to install linux-headers for 6.7 : 
```
linux-headers-6.7.3-060703-generic is already the newest version (6.7.3-060703.202401311935).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 linux-headers-6.7.3-060703-generic : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.6 is to be installed
```
And it doesn't seem to be a good solution to upgrade libc6

I'm not yet working with this laptop, it will give me some time to check if I have issues

**Comment by claudiux** [comment]
Mainline is not supported. v6.8 will be available soon (one month?) in Linux Mint.
