### ISSUE TITLE
Cinnamenu@json: Starpage searches direct to a Not Found page.

### ISSUE THREAD

**Issue by Draconicrose** [linuxmint/cinnamon-spices-applets#5018]
```
 * Version 5.4.6 (2023-08-11 19:49:41)
 * Cinnamon 5.8.4
 * Mint 21.2
 ```

**Notify author of applet**
@fredcw 

**Issue**
Startpage searches direct to https://www.startpage.com/notfound/

**Steps to reproduce**
Configure -> Search -> Web Search -> Startpage
Make any search.

**Expected behaviour**
That a search would open to the search results on Startpage.

**Other information**
https://support.startpage.com/hc/en-us/articles/4520913488148-Search-strings-adding-Startpage-to-unsupported-web-browsers

**Comment by fredcw** [comment]
Thanks, I'll fix this in the next update.
