### ISSUE TITLE
Message "impossible to find paquet mpv-mpris" at startup , Radio3.0@claudiux

### ISSUE THREAD

**Issue by enigma131** [linuxmint/cinnamon-spices-applets#5020]
Problem with radio3.0 @claudiux
Linux Mint 20.3 , cinnamon 5.2.7 , up to date.
inxi -G
Graphics:  Device-1: Intel Haswell-ULT Integrated Graphics driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4400 (HSW GT2) v: 4.5 Mesa 21.2.6 

Since a recent update, I get the error message + notification at startup.
The applet seems to work at all, i write "seems" ..
How to solve this ?

**Comment by claudiux** [comment]
@enigma131 
That worked for me on Mint 20.3,  cinnamon 5.2.7:

```
sudo add-apt-repository ppa:savoury1/mpv
apt update
apt install mpv-mpris
```

But the best way is to upgrade to upper version of Linux Mint.

**Comment by enigma131** [comment]
Thanks, that helped.
I don't want to upgrade my 20.3 now, it is under support until 2025, I have too may specifics on it. (I  dist-upgrade every 4 years)
