### ISSUE TITLE
ScreenShot+RecordDesktop - "selected area" component of app needs clicking twice

### ISSUE THREAD

**Issue by AtomicRobotMan0101** [linuxmint/cinnamon-spices-applets#5027]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```
-- Linux Mint Cinnamon 21.2 fully updated as of 6 Sept 2023 .... My `ixni -Fzxxx` --> https://termbin.com/39swe

-- Here is a dump of the .xsession-errors into pastebin --> https://termbin.com/lhqn

There is a lot of cruft in there and I'm unsure what NOT to include :)  There is no ~/cinnamon/glass.log

Metadata.json
```
`{
    "max-instances": -1,
    "uuid": "ScreenShot+RecordDesktop@tech71",
    "description": "Take A Snapshot Or Record Your Desktop (recording requires the packages ffmpeg, xdotool & x11-utils to be installed)",
    "name": "ScreenShot+Record Desktop",
    "author": "icarter09",
    "last-edited": 1692873474
}`
```

**Notify author of applet**
@icarter09

**Issue**
In order to "Selected Area" the applet needs to be activated a second time.

First click does not activate the selection area (where it turns the screen blue-ish), but second does.

**Steps to reproduce**
as above.

**Expected behaviour**

Active blue selection overlay on first activation :)

**Comment by new-on-github** [comment]
Same problem here on Linux Mint 21.2 Cinnamon.

Btw: Thanks for this amazing applet.

**Comment by junglized** [comment]
Same here in Linux 21.3 Cinnamon. First click does nothing. Only second click activates screenshot.

**Comment by AtomicRobotMan0101** [comment]
**Devs**, ~/.xsession-errors is producing this interesting error upon the first click attempt to use....

```
(cinnamon:2388): Gjs-WARNING **: 11:48:26.376: JS ERROR: Exception in callback for signal: activate: TypeError: Main.Util is undefined
defineScreenShotDefault/<@/home/msi/.local/share/cinnamon/applets/ScreenShot+RecordDesktop@tech71/applet.js:41:13
addAction/<@/usr/share/cinnamon/js/ui/popupMenu.js:1766:21
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
activate@/usr/share/cinnamon/js/ui/popupMenu.js:182:14
_onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:153:14
```

**Comment by junglized** [comment]
> **Devs**, ~/.xsession-errors is producing this interesting error upon the first click attempt to use....
> 
> ```
> (cinnamon:2388): Gjs-WARNING **: 11:48:26.376: JS ERROR: Exception in callback for signal: activate: TypeError: Main.Util is undefined
> defineScreenShotDefault/<@/home/msi/.local/share/cinnamon/applets/ScreenShot+RecordDesktop@tech71/applet.js:41:13
> addAction/<@/usr/share/cinnamon/js/ui/popupMenu.js:1766:21
> _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
> _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
> activate@/usr/share/cinnamon/js/ui/popupMenu.js:182:14
> _onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:153:14
> ```

exact same error here:
```
(cinnamon:2087): Gjs-WARNING **: 08:15:54.998: JS ERROR: Exception in callback for signal: activate: TypeError: Main.Util is undefined
defineScreenShotDefault/<@/home/user/.local/share/cinnamon/applets/ScreenShot+RecordDesktop@tech71/applet.js:31:13
addAction/<@/usr/share/cinnamon/js/ui/popupMenu.js:1766:21
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
activate@/usr/share/cinnamon/js/ui/popupMenu.js:182:14
_onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:153:14
```
