### ISSUE TITLE
hwmonitor@sylfurd: monitor additional drives

### ISSUE THREAD

**Issue by beelze** [linuxmint/cinnamon-spices-applets#5028]
Is there any way to add read/write widgets for additional drives? It would be nice, for instance, to monitor both NVME and HDD drives together. If not, this is a FR.

**Comment by fredcw** [comment]
Ping @Hultan

**Comment by Hultan** [comment]
It is not possible in the code I wrote, a few years ago, to add multiple drives. Someone might have added something later that I don't know about, but I doubt it.

I have not looked at the code for years, and probably will not do any improvements in the future either. Sorry, I just lost interest in developing in JavaScript. If someone wants to take over this project, feel free.

**Comment by fredcw** [comment]
@beelze You should be able to do this by using multiple instances of the applet and setting a different drive for each one. Btw, just in case you didn't realise, there's a cinnamon bug that prevents the config tabs showing unless you widen the config dialog first.

**Comment by beelze** [comment]
Thanks guys. I believe the issue is solved by using multiply instances.
