### ISSUE TITLE
Lightdm cannot access the Bing images folder

### ISSUE THREAD

**Issue by wintstar** [linuxmint/cinnamon-spices-applets#5042]
### Applet version/Build date

last Update from 7 Months

### Cinnamon version

5.8.4

### Distribution

LMDE 6

### Graphics hardware *and* driver used

Intel HD 3000 Grafik

### Applet name and maintainer

bing-wallpaper@starcross.dev @Starcross

### What happened?

@Starcross

Bing image folder is a hidden directory .config and does not show the image in the login window of Lightdm. When I select the directory of the Bing image .config/bingwallpaper in the settings of the login window, only a black background appears in the login window, but not the Bing daily image. Other images are displayed. I had already asked this in my last issue under point 2 pointed out https://github.com/linuxmint/cinnamon-spices-applets/issues/4651#issue-1551744302.

### Other information

OS: LMDE 6
Lenovo ThinkPad T420
Intel Core i5-2520M (2.50GHz, 3MB L3, 1333MHz FSB)
Intel HD 3000 Grafik
RAM 8GB

**Comment by mtwebster** [comment]
Is your home folder encrypted? If that's the case the images need to be in a system folder.

**Comment by wintstar** [comment]
@mtwebster No.

**Comment by wintstar** [comment]
Would like to add:
In LMDE 5 it still works. In Linux Mint 21 it never worked either. Since the update to LMDE 6 it doesn't work anymore either.

**Comment by Gr3q** [comment]
If your lighdm is run by `lightdm` user, it does not have permission to read anything in your home folder.

**Comment by wintstar** [comment]
That's why I mean that bing images should not be stored in a hidden folder /home/*user/.config//bingwallpaper.

**Comment by Gr3q** [comment]
Hidden means nothing when it's accessed directly, permissions are

**Comment by wintstar** [comment]
Why is the image not saved in /usr/share/wallpapers?

When setting the login window, it is pointed out that images from encrypted or restricted directories cannot be used.

**Comment by Gr3q** [comment]
Root access is needed to modify anything in /usr/, something the applet doesn't have.

**Comment by Starcross** [comment]
> 
> I don't understand why the Bing images are stored in the user directory in the hidden directory _.config_ /home/stephan/.config/bingwallpaper
> 

As Gr3q observed, `usr/*` is not writable except by root

I think it makes sense to save data for spices in the user directory as spices are user and not system level. 

Perhaps `~/.cache`  would have been more appropriate than `~/.config`, but not sure if this is writable in LightDM either? I guess I'm asking - What's the correct place to store user level data in LightDM, and can we determine which environment is running - I would have hoped an appropriate place would have been returned `by GLib.get_user_config_dir()` regardless

**Comment by claudiux** [comment]
`ls -l .config/bingwallpaper/` on  LM21.2:
```
total 3856
-rw-rw-r-- 1 claudiux claudiux 3940407 déc.   8 18:40 BingWallpaper.jpg
-rw-rw-r-- 1 claudiux claudiux    1144 déc.   8 18:40 meta.json
```

On LMDE6:
```
total 3856
-rw-r--r-- 1 claudiux claudiux 3940407  8 déc.  19:52 BingWallpaper.jpg
-rw-r--r-- 1 claudiux claudiux    1144  8 déc.  19:52 meta.json
```

**Comment by claudiux** [comment]
Changing rights doesn't solve the problem.
FYI this applet has the toString() bug:
```
(cinnamon:2803): Gjs-WARNING **: 20:12:36.485: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to use TextDecoder.
(Note that array.toString() may have been called implicitly.)
0 _getMetaData() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":86:30]
1 _refresh() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":56:13]
2 _init() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":51:13]
3 BingWallpaperApplet() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":29:9]
4 main() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":257:21]
5 createApplet() ["/usr/share/cinnamon/js/ui/appletManager.js":597:24]
6 addAppletToPanels() ["/usr/share/cinnamon/js/ui/appletManager.js":372:33]
7 finishExtensionLoad() ["/usr/share/cinnamon/js/ui/appletManager.js":98:13]
8 _init/<() ["/usr/share/cinnamon/js/ui/extension.js":275:31]

Gjs-Message: 20:12:36.512: JS LOG: [LookingGlass/info] Loaded applet bing-wallpaper@starcross.dev in 178 ms
```

**Comment by Starcross** [comment]
Since the image file has permissions to be read by all users, is this not a LightDM (lightdm-gtk-greeter) issue anyway?

**Comment by claudiux** [comment]
`ls -l /home` on LM21.2:
```
drwxr-xr-x 20 claudiux claudiux  4096 mai   22  2023 claudiux
```

On LMDE6:
```
drwx------ 15 claudiux claudiux  4096  9 déc.  10:36 claudiux
```

On LMDE6 `chmod +rx /home/claudiux` solved this issue. It's a choice of security and confidentiality for the user.

**Comment by wintstar** [comment]
@claudiux  Many Thanks for solution :+1:

**Comment by SeanyMCP** [comment]
> `ls -l /home` on LM21.2:
> 
> ```
> drwxr-xr-x 20 claudiux claudiux  4096 mai   22  2023 claudiux
> ```
> 
> On LMDE6:
> 
> ```
> drwx------ 15 claudiux claudiux  4096  9 déc.  10:36 claudiux
> ```
> 
> On LMDE6 `chmod +rx /home/claudiux` solved this issue. It's a choice of security and confidentiality for the user.

I'm on Linux Mint 21.2 and tried `chmod +rx /home/sean` and  `chmod 777 /home/sean/.config/bingwallpaper `

They failed to work for me

**Comment by claudiux** [comment]
@SeanyMCP 
In System settings -> Login window, did you check the "Draw user backgrounds" option?

**Comment by SeanyMCP** [comment]
> @SeanyMCP In System settings -> Login window, did you check the "Draw user backgrounds" option?

Yes I did, I also unchecked it and checked it again in case.

`ls -l /home` outputs this :
`drwxrwxrwx. 34 sean sean 4096 déc.  10 13:21 sean`

**Comment by claudiux** [comment]
> `ls -l /home` outputs this : `drwxrwxrwx. 34 sean sean 4096 déc. 10 13:21 sean`

These rights are too permissive.
```
chmod 755 /home/sean
```

**Comment by SeanyMCP** [comment]
I fixed the rights as you said, but still no bing image in lightdm.

`drwxr-xr-x. 34 sean sean 4096 déc.  11 10:37 sean`

I'm not sure what I'm missing

**Comment by wintstar** [comment]
### Info

drwxr-xr-x 17 stephan stephan 4096 Dez 11 18:49 stephan


This works on LM 21.**3 Beta**:
> On LMDE6 chmod +rx /home/claudiux solved this issue. It's a choice of security and confidentiality for the user.

drwxr-xr-x 17 stephan stephan 4096 Dez 11 18:52 stephan

**Comment by Gr3q** [comment]
You need to make sure that every parent folder have r+x rights until your reach the wallpaper itself.
