### ISSUE TITLE
smallcalc_applet giving decimal places when it shouldn't and also too many

### ISSUE THREAD

**Issue by Kellsen** [linuxmint/cinnamon-spices-applets#5045]
### Applet version/Build date

1683827772

### Cinnamon version

5.8.4

### Distribution

LMDE 6

### Applet name and maintainer

smallcalc_applet@lerc.sds @lerc

### What happened?

- Entryfield fills up with decimal places so sometimes you can't see the first digit

![1-2](https://github.com/linuxmint/cinnamon-spices-applets/assets/93977235/d5d1d7a7-26ad-48eb-9db7-0cf5f82d7d59)
![22](https://github.com/linuxmint/cinnamon-spices-applets/assets/93977235/cc025e45-bac2-4230-9bdc-9912b3c06485)

- Multiplications / divisions have decimal paces even when result is integer

![3-2](https://github.com/linuxmint/cinnamon-spices-applets/assets/93977235/5c42a287-0533-4f43-b980-dc2b50532087)
![4-2](https://github.com/linuxmint/cinnamon-spices-applets/assets/93977235/a8a88a92-8e23-45d5-b038-af998c4ddead)

### Other information

Buld #, Distro or Cinnamon version make no difference

**Comment by claudiux** [comment]
It's not a bug in this applet, but the way a floating-point number is represented in a computer.

```
$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a=1.3*3
>>> a
3.9000000000000004
>>> b=1.25*4
>>> b
5.0
>>> c=0.1+0.2
>>> c
0.30000000000000004
>>> 
```

**Comment by Kellsen** [comment]
Awesome update! Perfect now! Thanks!! 👍 😃
