### ISSUE TITLE
moonphase@techi-freki - black icons on dark panel

### ISSUE THREAD

**Issue by Severga** [linuxmint/cinnamon-spices-applets#5072]
### Applet version/Build date

0.0.2 (2023-10-29 07:14:43)

### Cinnamon version

5.2.7

### Distribution

Mint 20.3 Cinnamon

### Graphics hardware *and* driver used

NVIDIA GeForce GTX 760

### Applet name and maintainer

moonphase@techi-freki @Techi-Freki

### What happened?

The icons of the applet are almost not visible on my dark panel, because they are black instead of being the same color with the other elements.
![Untitled1](https://github.com/linuxmint/cinnamon-spices-applets/assets/66136019/82d67132-b177-4b89-bef8-4ef1eb876953)
![Untitled2](https://github.com/linuxmint/cinnamon-spices-applets/assets/66136019/cc0d4f53-f3c0-4bb8-9925-2e3cffeeeb35)

**Comment by Severga** [comment]
Yes, it doesn't depend. Black and transparent exchange but nothing changes. Black doesn't change to my interface light color.

**Comment by Severga** [comment]
It seems the SVGs' main color is black but not the default system color. Or I can't guess what it may be.

**Comment by claudiux** [comment]
Maybe try with #e4e4e4 instead of white and transparent instead of black. (Too busy to try myself now.)

**Comment by Gr3q** [comment]
https://github.com/linuxmint/cinnamon-spices-applets/blob/f4047e2e45af60cd63f6e4becdd10a0e167934de/moonphase%40techi-freki/files/moonphase%40techi-freki/js/moonPhase.js#L55

`set_applet_icon_symbolic_name(moon.currentPhaseIcon)` should be used with symbolic icons.

Although it works on my system even without that.

**Comment by Severga** [comment]
@Gr3q, the advice worked! Thanks!

@Techi-Freki, please, add the Russian translation to the applet (attachment), when updating the applet. I've no time at the moment to make commits.
[ru.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/13208817/ru.po.zip)
