### ISSUE TITLE
batterymonitor@pdcurtis - request: ability to set battery alert level > 40%

### ISSUE THREAD

**Issue by MatzFan** [linuxmint/cinnamon-spices-applets#5093]
### Applet name and maintainer

batterymonitor@pdcurtis @pdcurtis

### What would you like to see?

I am using your fine applet on an old MacBook with a shot battery and despite trying to calibrate the battery my machine still hibernates without warning at what it thinks is 60% capacity. I'd love to be able to set an audible alarm at, say 70%. Any chance you'd expand the alert ranges to cater for such a use-case? TIA

**Comment by claudiux** [comment]
@MatzFan You can edit this applet's `settings-schema.json` file and, on line 137, replace 40 with 70 or 80. Save this file and restart this applet or Cinnamon.

**Comment by MatzFan** [comment]
I'll do that thanks, can't imagine this would be useful to many other people!
