### ISSUE TITLE
Radio3.0 ignores "Do not check about dependencies" setting

### ISSUE THREAD

**Issue by CodehunterWorks** [linuxmint/cinnamon-spices-applets#5097]
### Applet version/Build date

1.9.0

### Cinnamon version

5.0.7

### Distribution

Mint 20.2 Cinnamon

### Graphics hardware *and* driver used

Advanced Micro Devices, Inc. [AMD/ATI] Renoir

### Applet name and maintainer

Radio3.0@claudiux @claudiux

### What happened?

Radio3.0 is starting each time when logging in to Cinnamon. Then it shows TWO messages about mpv-mpris is not found. mpv-mpris is not available for LM 20.2. Its okay because i do not need it and i do not want to manual compile and install it. Radio3.0 is working fine without mpv-mpris for my purpose. Therefore i have enabled the "Behavior" -> "Start-up" -> "Do not check about dependencies" but this messages are shown again each time Radio3.0 starts.

**Comment by claudiux** [comment]
@CodehunterWorks 
After installing LM 20.2 in a VM, I see the problem. I try to fix this issue soon.

**Comment by CodehunterWorks** [comment]
> @CodehunterWorks After installing LM 20.2 in a VM, I see the problem. I'll try to solve it soon.

Many thanks for your quick response and support for these older Mint versions!

**Comment by claudiux** [comment]
v1.9.1 is here. You can now uncheck the "Do not check about dependencies" setting.

**Comment by CodehunterWorks** [comment]
@claudiux 
Confirmed: Both messages about missing mpv-mpris disappeared with 1.9.1, even "Do not check about dependencies" is checked or not. Great job! This is why i love open source: Bug reports are taken seriously and some times like this fixed in hours. I really enjoyed upvoting this spice.
