### ISSUE TITLE
weather@mockturtl  - cannot save log file + panel temperature returns null on tomorrow.io

### ISSUE THREAD

**Issue by nikto1** [linuxmint/cinnamon-spices-applets#5107]
### Applet version/Build date

3.3.1

### Cinnamon version

5.8.4

### Distribution

mint 21.2

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

1) As per title, when selecting tomorrow.io the temperature returns/ shows null on the panel since today.
![screen](https://github.com/linuxmint/cinnamon-spices-applets/assets/9814101/75fc23a5-3eb0-4eb1-afc2-4c51bfe2b9c1)
2) then i tried to save a logfile but it returns the wrong path.
it says file not found  in **/home/user/.cinnamon/configs/weather@mockurtl/53.json**
3) would be good to have an option to export the configuration settings so i don't have to reconfigure the applet manually each time i reinstall it.

Thanks for help

**Comment by Gr3q** [comment]
Hi, I'll fix the save log issue.

Also every applet config has a hamburger menu where you can export/import settings.

I'll have a look at the tommorow.io issue.

**Comment by Gr3q** [comment]
It seems the best I can do for you is to not show `null` when tomorrow.io doesn't provide data
