### ISSUE TITLE
Power Consumption Display not working on Framework AMD Laptop

### ISSUE THREAD

**Issue by Zynth-dev** [linuxmint/cinnamon-spices-applets#5117]
### Applet version/Build date

2022-06-11

### Cinnamon version

5.8.4

### Distribution

Mint 21.2 Edge

### Applet name and maintainer

batterypower@joka42 @joka42

### What happened?

Applet shows no text; it is there but it is empty
I have looked at the code in github, and understand why maybe it does not work.
However, I can't solve it.

Some hints:
- BAT0 does not exist on this laptop, only BAT1.
- file /sys/class/power_supply/BAT1/status exists
- file /sys/class/power_supply/BAT1/power_now does not exist
- The command used in the .py should work: upower -i $(upower -e | grep BAT) | grep energy-rate | grep -Eo '[0-9]+([,|.][0-9]+)?' | sed 's/,/./' > .energyrate
- The other command for batterystate as well. Executing them manually creates the files with the correct content

**Comment by Zynth-dev** [comment]
Update:
After switching the "show unit" switch in the configuration window, it showed up.
And it stayed.
But after a reboot, it is empty again, and switching that "show unit" does not help anymore.

**Comment by joka42** [comment]
@Zynth-dev "file /sys/class/power_supply/BAT1/power_now does not exist" - do these files exist: voltage_now and current_now in the .../BAT1/ directory?

If so, do you know how to edit the applet in your files? Then I'd fix the issue and you could test it.

**Comment by Zynth-dev** [comment]
> @Zynth-dev "file /sys/class/power_supply/BAT1/power_now does not exist" - do these files exist: voltage_now and current_now in the .../BAT1/ directory?
> 
> If so, do you know how to edit the applet in your files? Then I'd fix the issue and you could test it.

Thanks for your reply!
Both files exist.
- voltage_now is about 16858000 when connected to a charger, and for example 16715000 when on battery.
- current_now is 0 when connected to a charger, and for example 212000 when on battery.

I know how to edit the files so I can test!

**Comment by joka42** [comment]
Ok great! Then you can just replace BAT0 with BAT1 in the js file where it reads these files, restart cinnamon and report back, then I can implement a solution that works for both.

**Comment by Zynth-dev** [comment]
> @Zynth-dev can you test the files in this Merge Request #5179 if everything works as expected?

All seems to be working fine! 
Thanks!
