### ISSUE TITLE
(Cinnamenu@json) Applet Bug - Logout button no longer does anything. 

### ISSUE THREAD

**Issue by scottyphillips** [linuxmint/cinnamon-spices-applets#5134]
### Applet version/Build date

Version 5.4.8 (2023-11-21 07:19:14)

### Cinnamon version

5.8.4

### Distribution

EndeavourOS

### Graphics hardware *and* driver used

Nvidia GTX 780M Mac Edition 470.223.02

### Applet name and maintainer

Cinnamenu@json @fredcw

### What happened?

The 'logout' button appears to have stopped working. Clicking on the button does not bring up the expected logout dialog.  The 'lock' and 'quit' buttons are working fine.  

In contrast with the User applet - log out function works fine.

**Comment by scottyphillips** [comment]
My educated guess is that 'cinnamon-session-quit' was modified recently upstream. 

I fixed it myself (yay!) by changing line 263 of sidebar.js to this

`                        Util.spawnCommandLine('cinnamon-session-quit --logout');`

**Comment by fredcw** [comment]
Thanks. Will fix shortly.
