### ISSUE TITLE
Radio 3.0 - Audio Recording .flac does not work

### ISSUE THREAD

**Issue by cubetti2004** [linuxmint/cinnamon-spices-applets#5149]
### Applet version/Build date

Radio 3.0 v1.10.1

### Cinnamon version

5.8.4

### Distribution

lmd6

### Graphics hardware *and* driver used

AMD

### Applet name and maintainer

Radio3.0@claudiux @claudiux

### What happened?

Hi, yes please remove libmpv1 or libmpv2. It does not work on Linux MInt 21.2 and LMDE6. Further I tried to record the radio to .flac, but this does not work too. If I try to play with vlc or Audicisous, I got the error message "Error playing file:///home/user1/Music/Radio3.0/O%20Come%2C%20O%20Come%2C%20Emanuel%20%20By%3A%20Eugene%20Ormandy%3A%20Philadelphia%20Orchestra%20-%20WALMRadio.com_2023-11-26_05-14-08%20PM_2023-11-26_05-14-08%20PM.flac: The file could not be decoded. It may be invalid, corrupt, or in an unsupported format." If I change the file type from .flac to .mp3 it works. Can you please change the recording or converting to real .flac files please.

**Comment by claudiux** [comment]
Sorry but this is a bug in mpv version 0.34.1, which seems to be fixed in mpv version 0.37.0. Waiting for this version in the repos.

**Comment by cubetti2004** [comment]
thank you very much. Very good job. Any possibility to donate?

**Comment by cubetti2004** [comment]
do you need any help for german translation? I am working hard and will try to find time to translate.

**Comment by claudiux** [comment]
> thank you very much. Very good job. Any possibility to donate?


Thank you very much, but I'm not asking for a donation. Just like this applet on its page (right-clic on applet to obtain the link) please.

**Comment by claudiux** [comment]
> do you need any help for german translation? I am working hard and will try to find time to translate.

Yes, many users need german translation. The status of translations is here: https://github.com/linuxmint/cinnamon-spices-applets/blob/translation-status-tables/.translation-tables/tables/Radio3.0%40claudiux.md# 
Please use the .pot file with PoEdit (or any other translation software) to create the de.po file containing german translation of all messages. Take your time. Thank you.

**Comment by cubetti2004** [comment]
> > thank you very much. Very good job. Any possibility to donate?
> 
> Thank you very much, but I'm not asking for a donation. Just like this applet on its page (right-clic on applet to obtain the link) please.

I cannot find the link, either not on the webpage.

**Comment by claudiux** [comment]
Go to https://cinnamon-spices.linuxmint.com/applets/view/360 then log in (button at top right of the page).
Return to https://cinnamon-spices.linuxmint.com/applets/view/360 and click on "Like it".
Thank you for all that!
