### ISSUE TITLE
[weather@mockturtl] Applet Bug

### ISSUE THREAD

**Issue by gervafernandez** [linuxmint/cinnamon-spices-applets#5152]
### Applet version/Build date

Versión 3.3.1 (2023-11-20 21:55:48)

### Cinnamon version

Cinnamon 5.8.4

### Distribution

Linux Mint 21.2 Cinnamon

### Graphics hardware *and* driver used

NVIDIA Corporation GP106BM [GeForce GTX 1060 Mobile 6GB]

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

Service error in the last 3 days (since nov. 25th)

**Comment by Gr3q** [comment]
Hi, which provider do you use? also, are you using manual or automatic location?

**Comment by fredcw** [comment]
OpenWeatherMap (manual location) stopped working for me the other day but it seems back to normal now.

**Comment by mithereal** [comment]
same error i get "Generic Error while refreshing Weather info: TypeError: SessionAsync is not a constructor" in the debugger regardless of which weather provider  i use, location doesnt matter.

**Comment by Gr3q** [comment]
@fredcw next time check the logs if it's just not a generic error (like the api is down or sth)

@mithereal what kind of distro are you using?
`SessionAsync` is in version 2 of the Soup library, this is how I decide which version to import it:
`export const soupLib: SoupLib = imports.gi.Soup.MAJOR_VERSION == 3 ? new Soup3() : new Soup2();`

this line is not working in your case.

**Comment by mithereal** [comment]
i am running arch with libsoup-2.74.3-1 and cinnamon 6.0.0

**Comment by Gr3q** [comment]
Sorry, I forgot to reply @mithereal. You should have `libsoup3` installed too. Cinnamon imports soup3. So I'm at a loss to be honest
