### ISSUE TITLE
SpicesUpdate@claudiux stopped working

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-applets#5167]
### Applet version/Build date

 v6.4.2 

### Cinnamon version

6.0.0

### Distribution

Arch Linux 6.6.3

### Graphics hardware *and* driver used

Radeon HD5450

### Applet name and maintainer

SpicesUpdate@claudiux @claudiux

### What happened?

Icon disappeared today. Error message from Cinnamon that an applet ... failed to load.
Deleted and reinstalled.
Still no icon. cannot access in settings.
Looking Glass:
error t=2023-12-03T10:13:24Z 
[SpicesUpdate@claudiux]: Soup.ProxyResolverDefault is not a constructor
[SpicesUpdate@claudiux]: Failed to evaluate 'main' function on applet: SpicesUpdate@claudiux/216
error t=2023-12-03T10:13:24Z 
[SpicesUpdate@claudiux]: Applet SpicesUpdate@claudiux: Could not create applet object.
[SpicesUpdate@claudiux]: Error importing applet.js from SpicesUpdate@claudiux

### Other information

.x-session-errors:
js-Message: 08:52:51.051: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 602 ms
Gjs-Message: 08:52:51.171: JS LOG: [LookingGlass/error] 
[SpicesUpdate@claudiux]: Soup.ProxyResolverDefault is not a constructor
[SpicesUpdate@claudiux]: Failed to evaluate 'main' function on applet: SpicesUpdate@claudiux/199
Gjs-Message: 08:52:51.171: JS LOG: [LookingGlass/trace] 
<----------------
define_http_session@/home/victor/.local/share/cinnamon/applets/SpicesUpdate@claudiux/5.6/applet.js:567:68
SpicesUpdate@/home/victor/.local/share/cinnamon/applets/SpicesUpdate@claudiux/5.6/applet.js:232:14
main@/home/victor/.local/share/cinnamon/applets/SpicesUpdate@claudiux/5.6/applet.js:2531:12
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:597:25
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:372:34
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:98:14
_init/<@/usr/share/cinnamon/js/ui/extension.js:286:32
---------------->
Gjs-Message: 08:52:51.172: JS LOG: [LookingGlass/error] 
[SpicesUpdate@claudiux]: Applet SpicesUpdate@claudiux: Could not create applet object.
[SpicesUpdate@claudiux]: Error importing applet.js from SpicesUpdate@claudiux
Gjs-Message: 08:52:51.172: JS LOG: [LookingGlass/trace]

**Comment by Padre2** [comment]
@claudiux
Installed Version 6.4.3 (2023-12-09 21:58:28)
After installation there is no icon and cannot open Spicesupdate _Configure_ in the list of applets.
Arch now at version 6.6.5,

**Comment by claudiux** [comment]
I'm working on this issue. Thanks for reporting.

**Comment by Padre2** [comment]
@claudiux 
Can I be of any help?

**Comment by claudiux** [comment]
@Padre2 You need to install Soup3 and use the latest version (7.1.1) of this applet.

**Comment by claudiux** [comment]
v7.2.0 of SpicesUpdate works well for me with Cinnamon 6.0.4 on Arch.
