### ISSUE TITLE
radio@driglu4it - applet fails to start after upgrade to Cinnamon 6.0

### ISSUE THREAD

**Issue by archiebug** [linuxmint/cinnamon-spices-applets#5168]
### Applet version/Build date

2.2.3

### Cinnamon version

6.0

### Distribution

Arch

### Applet name and maintainer

radio@driglu4it @jonath92

### What happened?

Applet does not start after upgrading to Cinnamon 6.0.  Below is the error log:

[radio@driglu4it]: SessionAsync is not a constructor
[radio@driglu4it]: Error importing applet.js from radio@driglu4it
Gjs-Message: 08:42:59.917: JS LOG: [LookingGlass/trace] 
<----------------
anonymous/<@/home/<user>/.local/share/cinnamon/applets/radio@driglu4it/4.6/radio-applet.js:5575:21
anonymous@/home/<user>/.local/share/cinnamon/applets/radio@driglu4it/4.6/radio-applet.js:5837:12
createExports@/usr/share/cinnamon/js/misc/fileUtils.js:219:11
requireModule@/usr/share/cinnamon/js/misc/fileUtils.js:281:16
require@/usr/share/cinnamon/js/misc/fileUtils.js:222:24
anonymous@/home/<user>/.local/share/cinnamon/applets/radio@driglu4it/4.6/applet.js:6:30
createExports@/usr/share/cinnamon/js/misc/fileUtils.js:219:11
requireModule/</<@/usr/share/cinnamon/js/misc/fileUtils.js:291:25
---------------->

**Comment by fredcw** [comment]
Applet needs updating to Soup 3.0
