### ISSUE TITLE
bluetooth-battery@zamszowy: Feature Request

### ISSUE THREAD

**Issue by rcalixte** [linuxmint/cinnamon-spices-applets#5171]
### Applet name and maintainer

bluetooth-battery@zamszowy @zamszowy

### What would you like to see?

Similar to #5145, would it be possible to make changes to allow support for multiple instances of this great applet? On multi-display setups, having a maximum of just one instance is restrictive. If you want, I can take a shot at it or leave it up to you but want to make sure you were okay with the potential change first.

**Comment by zamszowy** [comment]
> ### Applet name and maintainer
> bluetooth-battery@zamszowy @zamszowy
> 
> ### What would you like to see?
> Similar to #5145, would it be possible to make changes to allow support for multiple instances of this great applet? On multi-display setups, having a maximum of just one instance is restrictive. If you want, I can take a shot at it or leave it up to you but want to make sure you were okay with the potential change first.

Sure thing, I've opened pull request.
