### ISSUE TITLE
Radio 3.0 - No radio stations or audio

### ISSUE THREAD

**Issue by portanav** [linuxmint/cinnamon-spices-applets#5201]
### Applet version/Build date

1.11.2

### Cinnamon version

5.8.4

### Distribution

Mint 21.2

### Graphics hardware *and* driver used

Nvidia GeForce 680 / Nvidia Driver 470

### Applet name and maintainer

Radio3.0@claudiux @claudiux

### What happened?

I see no radio stations displayed, nor hear any music. Searching for radio stations does not work. Selecting the Applet brings up the menu, but selecting "Configure..." or "Search for new stations..." on the menu does nothing. All I get from the Applet is the menu displayed. Right clicking on the Applet does bring up a more elaborate menu and I can select the 3 switches on the menu ON/OFF, but I cannot configure or get search radio stations to work  or hear any audio.
Thanks.

### Other information

These are the two menus displayed from left/right clicks that I get from the Applet; as you can see in the extensive right click menu I am able to switch ON the "Display Station Logo", as I can also do with the other two switches.

Right Click Menu:
![Screenshot from 2023-12-08 05-54-30](https://github.com/linuxmint/cinnamon-spices-applets/assets/53981413/af135a8f-f434-416e-a640-0e7b624a59e7)

Left Click Menu:
![Screenshot from 2023-12-08 05-56-38](https://github.com/linuxmint/cinnamon-spices-applets/assets/53981413/64396fcb-71c7-4626-bd29-6b59860bc32e)

**Comment by claudiux** [comment]
Hi @portanav 

1. In the Network tab of this applet settings, what is the url of the database (at bottom of this tab)? If it's 'undefined' then try restarting this applet (or Cinnamon).

2. In the Search tab, click the 'Reset' button, set the Tag field to `rock` then click the 'Search...' button. What happens?

3. In the Radio tab use buttons to Save your radio list (if it isn't empty) then Restore the 'Radio3.0_EXAMPLES.json' file.

**Comment by claudiux** [comment]
@portanav Any news on that?

**Comment by portanav** [comment]
> @portanav Any news on that?

I did get it to work using your suggestions, but it continually froze up on my system when the music was playing, and I could not stop the music. So I decided to uninstall it and gave up on the idea of using the Applet.
Thanks,.

**Comment by claudiux** [comment]
You have 2 ways to stop the radio:

- middle-clicking on the applet icon,
- selecting Stop in this applet menu.

**Comment by portanav** [comment]
> You have 2 ways to stop the radio:
> 
> * middle-clicking on the applet icon,
> * selecting Stop in this applet menu.

None of those work, in fact I can't even get the menu's to display after the radio begins playing music from a station.

**Comment by claudiux** [comment]
Did you installed all the dependencies?

**Comment by portanav** [comment]
> Did you installed all the dependencies?

Yes I did.
