### ISSUE TITLE
[weather@mockturtl] Applet Bug

### ISSUE THREAD

**Issue by mckuup** [linuxmint/cinnamon-spices-applets#5212]
### Applet version/Build date

3.3.1

### Cinnamon version

6.0.0

### Distribution

Mint 21.3 beta

### Graphics hardware *and* driver used

Intel

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

After computer restart applet does not working. Only show refresh circle.

**Comment by davidbepo** [comment]
happens here too, it seems to be random, alt+f2 r makes it show tho

**Comment by fredcw** [comment]
Seems to happen only after reboot and restarting cinnamon fixes it.
```

(cinnamon:866): Gjs-CRITICAL **: 23:55:32.610: JS ERROR: Gio.ResolverError: Error resolving “api.openweathermap.org”: Temporary failure in name resolution
Send/data</<@/home/fred/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:17166:51
```

Curiously, same thing happens with spices-notifier@germanfr applet.
```

(cinnamon:866): Gjs-CRITICAL **: 23:55:33.492: JS ERROR: Gio.ResolverError: Error resolving “cinnamon-spices.linuxmint.com”: Temporary failure in name resolution
Send/data</<@/home/fred/.local/share/cinnamon/applets/spices-notifier@germanfr/lib/httpLib.js:61:51

```

I'm using manjaro.

**Comment by vajdao** [comment]
``Same here: Cinnamon 6.0.4, Linux Mint 21.3, Nvidia 535
@Gr3q it seems it's a returning error, it seems the applet tries to fetch data before the network connection is established.

Got this log in my `.xsession-errors` file
```
Gjs-Message: 12:09:51.591: JS LOG: [LookingGlass/info] [weather@mockturtl#29]: Internet access now down with "1", pausing refresh.
Gjs-Message: 12:09:51.606: JS LOG: [LookingGlass/info] Loaded applet weather@mockturtl in 97 ms
```

My machine is hungarian, but it a nutshell its a Resolve error:

```
(cinnamon:1692): Gjs-CRITICAL **: 12:09:51.893: JS ERROR: Gio.ResolverError: Hiba a(z) „get.geojs.io” feloldásakor: A név vagy a szolgáltatás nem ismert
Send/data</<@/home/vajdao/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:16234:51
```
Here my pc established network connection
```
Here the network was established:
Gjs-Message: 12:09:52.957: JS LOG: [LookingGlass/info] [weather@mockturtl#29]: Internet access now available, resuming operations.
```
But still there was only a refresh circle, so I reloaded the applet itself and finally managed to work:
```
Gjs-Message: 12:37:20.524: JS LOG: [LookingGlass/info] [weather@mockturtl#29]: Refreshing in progress, refresh skipped.
Gjs-Message: 12:37:25.287: JS LOG: [LookingGlass/info] Reloading applet: weather@mockturtl/29
Gjs-Message: 12:37:25.287: JS LOG: [LookingGlass/info] [weather@mockturtl#29]: Removing applet instance...
Gjs-Message: 12:37:25.377: JS LOG: [LookingGlass/info] [weather@mockturtl#29]: Internet access now available, resuming operations.
Gjs-Message: 12:37:25.391: JS LOG: [LookingGlass/info] Loaded applet weather@mockturtl in 88 ms
```

**Comment by Gr3q** [comment]
I see so it's a race condition, on start. Also I don't invalidate errors on network state changes.

**Comment by vajdao** [comment]
> I see so it's a race condition on start (I don't cancel ongoing refreshes). Also I don't invalidate errors on network state changes.

So what do you mean? No solution? More and more people struggling with the same problem.

[https://blog.linuxmint.com/?p=4624#comment-389026](https://blog.linuxmint.com/?p=4624#comment-389026)
[https://blog.linuxmint.com/?p=4629#comment-389055](https://blog.linuxmint.com/?p=4629#comment-389055)

Comment section
[https://cinnamon-spices.linuxmint.com/applets/view/17](https://cinnamon-spices.linuxmint.com/applets/view/17)

Forums, basically everywhere

**Comment by Gr3q** [comment]
Yeah my comment didn't really include I'm working on it and preparing a new release.

I'm working on it with the limited free time I have (along with fixing other issues with the applet)
