### ISSUE TITLE
SpicesUpdate@claudiux - Applet does not start

### ISSUE THREAD

**Issue by archiebug** [linuxmint/cinnamon-spices-applets#5216]
### Applet version/Build date

6.4.3

### Cinnamon version

6.0

### Distribution

Arch

### Applet name and maintainer

SpicesUpdate@claudiux @claudiux

### What happened?

After the latest update, the applet does not seem to start.  Also, it seems that monitored applets do not get populated in the settings menus.

Thank you for you work!

### Other information

xsession-errors log:

[SpicesUpdate@claudiux]: this._httpSession.queue_message is not a function
[SpicesUpdate@claudiux]: Failed to evaluate 'main' function on applet: SpicesUpdate@claudiux/78
Gjs-Message: 10:07:38.804: JS LOG: [LookingGlass/trace] 
<----------------
download_cache@/home/<user>/.local/share/cinnamon/applets/SpicesUpdate@claudiux/5.6/applet.js:1339:31
get_SU_settings@/home/<user>/.local/share/cinnamon/applets/SpicesUpdate@claudiux/5.6/applet.js:350:22
SpicesUpdate@/home/<user>/.local/share/cinnamon/applets/SpicesUpdate@claudiux/5.6/applet.js:303:14
main@/home/<user>/.local/share/cinnamon/applets/SpicesUpdate@claudiux/5.6/applet.js:2537:12
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:597:25
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:372:34
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:309:26
---------------->

**Comment by claudiux** [comment]
@archiebug Thank you for reporting this issue. I'll try to solve it as soon as possible.

**Comment by G4Zz0L1** [comment]
News on this?
Thanks in advance!

**Comment by gbit00** [comment]
Same problem here
error t=2024-03-26T13:27:45Z 
[SpicesUpdate@claudiux]: this._httpSession.queue_message is not a function
[SpicesUpdate@claudiux]: Failed to evaluate 'main' function on applet: SpicesUpdate@claudiux/74
error t=2024-03-26T13:27:45Z 
[SpicesUpdate@claudiux]: Applet SpicesUpdate@claudiux: Could not create applet object.
[SpicesUpdate@claudiux]: Error importing applet.js from SpicesUpdate@claudiux

**Comment by Padre2** [comment]
Heureux de voir la nouvelle version. Merci pour votre dur travail.
