### ISSUE TITLE
Applet Feature Request:  Report AQI

### ISSUE THREAD

**Issue by droj73** [linuxmint/cinnamon-spices-applets#5234]
### Applet name and maintainer

anime-wallpaper@flyflyan @flyflyan

### What would you like to see?

Air Quality Index (AQI) would be nice!

**Comment by rcalixte** [comment]
cc @fly206

**Comment by fly206** [comment]
Thanks for your suggestion! But I don't know how to obtain AQI and display it. Could you provide some examples as a reference, thanks

**Comment by droj73** [comment]
Hi Rick,
The following is a site that might provide more information on this subject.This is about the extent of my knowledge about AQI monitoring.

https://www2.purpleair.com/blogs/blog-home/why-air-quality-maps-have-different-data
Thank you for your response,Don Olson


    On Friday, December 15, 2023 at 07:35:01 PM PST, flyflyan ***@***.***> wrote:  
 
 


Thanks for your suggestion! But I don't know how to obtain AQI and display it. Could you provide some examples as a reference, thanks

**Comment by rcalixte** [comment]
> The following is a site that might provide more information on this subject.This is about the extent of my knowledge about AQI monitoring.

What does this have to do with an applet for a wallpaper? Did you mean to request a new applet? If so, that request should be made at [linuxmint/discussions](https://github.com/orgs/linuxmint/discussions), this should be closed, and then you should provide all the details you have there. Maybe someone has time and interest to pick it up.

**Comment by claudiux** [comment]
@rcalixte I agree and close this FR.
