### ISSUE TITLE
Radio3.0 shows always volume percentage in Taskbar and no scroll change

### ISSUE THREAD

**Issue by CodehunterWorks** [linuxmint/cinnamon-spices-applets#5246]
### Applet version/Build date

1.12.0

### Cinnamon version

5.0.7

### Distribution

Mint 20.2

### Graphics hardware *and* driver used

Advanced Micro Devices, Inc. [AMD/ATI] Renoir

### Applet name and maintainer

Radio3.0@claudiux @claudiux

### What happened?

Since version 1.12.0 is installed, it shows always the volume percentage right aside its taskbar icon. I cant find any configuration option to disable this. I have the same percentage on the speaker icon in the taskbar. So I need no second percentage on Radio3.0 icon. As a secondary issue it seems that the volume change when scrolling on the icon does not work anymore.

**Comment by claudiux** [comment]
@CodehunterWorks I see. You're right about Cinnamon 5.0. I'm looking for the bug. You can make the volume display disappear by unchecking the "Display volume level near icon" option in this applet's context menu (right-click).

**Comment by claudiux** [comment]
Error found! In`~/.xsession-errors`:
```
(cinnamon:1490): Cjs-CRITICAL **: 00:22:58.842: JS ERROR: Error: GSettings schema org.cinnamon.desktop.peripherals.mouse not found
_init@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:556:23
check_schema_and_init@/usr/share/cinnamon/js/ui/overrides.js:19:16
overrideGio/Gio.Settings.prototype._init@/usr/share/cinnamon/js/ui/overrides.js:75:85
_get_system_natural_scroll@/home/claudiux/.local/share/cinnamon/applets/Radio3.0@claudiux/applet.js:233:29
_onScrollEvent@/home/claudiux/.local/share/cinnamon/applets/Radio3.0@claudiux/applet.js:3425:18
_connect_signals/this.connectIdScroll<@/home/claudiux/.local/share/cinnamon/applets/Radio3.0@claudiux/applet.js:3382:85
```
The `org.cinnamon.desktop.peripherals.mouse` schema does not exist in Cinnamon 5.0, but `org.cinnamon.settings-daemon.peripherals.mouse`. I'll try to fix this issue as soon as possible, but it is not a bug from this applet.

**Comment by CodehunterWorks** [comment]
@claudiux You are right. In the past the context menu was not really useful to me. Therefore I had not tried right mouse button :-) I think it would be more intuitive when a config option in the Behavior tab is available.

BTW since I looked in the context menu after a long time ^^ I see three volume sliders. All of these are for mpv Media Player. But `ps -e |grep mpv` shows no running mpv process. Why?

As a feature request: If Radio3.0 could be configured to change the system master volume when scrolling over its icon, it would be a full replacement for the speaker icon. Then I could remove the speaker icon from the taskbar (because I have a lot of icons there and would happy to remove one ^^).

**Comment by claudiux** [comment]
@CodehunterWorks Thank you for this detailed report. This will allow me to improve this applet.

However, its purpose is not to replace the "sound" applet. I suggest you to try: https://cinnamon-spices.linuxmint.com/applets/view/265 (or create another panel?) if you use too many applets. I have 3 panels: bottom, top and right.

To make system changes easier, my /home folder is mounted on a separate partition. So no more worries in the event of an upgrade. I wrote this doc (in French): https://linux.claudeclerc.fr/linuxaddict:installer:preparer_le_disque_dur

**Comment by claudiux** [comment]
I reopen this issue because I'll make a PR that fixes it entirely.

**Comment by claudiux** [comment]
Et voilà !

**Comment by CodehunterWorks** [comment]
Confirmed: Volume change by scrolling icon works with Cinnamon 5.0.7

Joyeux Noël!
