### ISSUE TITLE
weather@mockturtl: Problem loading - check looking glass

### ISSUE THREAD

**Issue by skullscream** [linuxmint/cinnamon-spices-applets#53]
I get this issue when I try installing this applet via "applets" menu in system settings. This is the looking glass log:

```
info t=2017-02-01T10:36:32.678Z Cinnamon.AppSystem.get_default() started in 80 ms
info t=2017-02-01T10:36:32.685Z loading default theme
info t=2017-02-01T10:36:32.832Z PlacesManager: Updating devices
info t=2017-02-01T10:36:32.919Z loaded at Wed Feb 01 2017 11:36:32 GMT+0100 (CET)
info t=2017-02-01T10:36:33.548Z Loaded applet menu@cinnamon.org in 622 ms
info t=2017-02-01T10:36:33.831Z Role locked: panellauncher
info t=2017-02-01T10:36:33.832Z Loaded applet panel-launchers@cinnamon.org in 283 ms
info t=2017-02-01T10:36:33.900Z Loaded applet window-list@cinnamon.org in 66 ms
info t=2017-02-01T10:36:33.932Z Loaded applet removable-drives@cinnamon.org in 29 ms
info t=2017-02-01T10:36:33.985Z Loaded applet keyboard@cinnamon.org in 49 ms
info t=2017-02-01T10:36:33.995Z Loaded applet systray@cinnamon.org in 9 ms
info t=2017-02-01T10:36:34.110Z Loaded applet power@cinnamon.org in 112 ms
info t=2017-02-01T10:36:34.297Z Loaded applet network@cinnamon.org in 184 ms
info t=2017-02-01T10:36:34.470Z Loaded applet sound@cinnamon.org in 169 ms
info t=2017-02-01T10:36:34.549Z Loaded applet calendar@cinnamon.org in 78 ms
info t=2017-02-01T10:36:34.580Z Loaded applet settings@cinnamon.org in 29 ms
info t=2017-02-01T10:36:34.594Z 2 applet already loaded
info t=2017-02-01T10:36:34.595Z Loaded applet weather@mockturtl in 14 ms
info t=2017-02-01T10:36:34.596Z AppletManager.init() started in 1676 ms
info t=2017-02-01T10:36:34.601Z Cinnamon took 2054 ms to start
info t=2017-02-01T10:36:35.916Z Adding systray: parcellite (24x24px)
info t=2017-02-01T10:36:35.921Z Adding systray: pamac-tray (24x24px)
info t=2017-02-01T10:36:35.925Z Hiding systray: network
```

I tried changing from original version in metadata.json to my cinnamon version (3.2.8) and restart cinnamon but nothing happens. Using archlinux 4.9.6.1 64bit here.

**Comment by JosephMcc** [comment]
Please read the section on reporting issues at the end of the README https://github.com/linuxmint/cinnamon-spices-applets/blob/master/README.md

**Comment by skullscream** [comment]
Good now? I  don't really know what spices are so I assume they are applets?

**Comment by JosephMcc** [comment]
Ok, I fixed this one. Just using the applet name is the best bet.

I added that generic bit to the README for all the spices. There are 4 different types: applets, desklets, extensions, and themes.

**Comment by NikoKrause** [comment]
There seems to be no problem looking at your looking glass.
Try to uninstall the applet. Then "Refresh list" in "Available applets (online)" and install it again.

**Comment by NikoKrause** [comment]
> I tried changing from original version in metadata.json to my cinnamon version (3.2.8) 

The version in metadata.json doesn't mean the Cinnamon version. It's the applet version.

**Comment by skullscream** [comment]
`Try to uninstall the applet. Then "Refresh list" in "Available applets (online)" and install it again.`

Tried it, it's the same still. I'd include system error logs but I don't know which ones. There's so many of them :D

**Comment by Odyseus** [comment]
Hello, everybody.

@skullscream: I just installed weather@mockturtl applet on my Archlinux system fully updated. It installed without any error and I placed in the panel also without any errors.

Since the Spices website redesign, all applet's URLs changed. You should click the **Refresh list** button to update the applets cache and try to install your applet/s again.

**Comment by skullscream** [comment]
I already tried doing this. By the way this isn't a clean fresh installation of arch it's antergos which is just an install client for arch. I re-installed some packages yesterday so I will see if getting them back makes any difference.

**Comment by NikoKrause** [comment]
Have you tried manual installation?

**Comment by deekej** [comment]
Same for me after update. I had to downgrade to restore functionality.

**Comment by skullscream** [comment]
Downloaded from here https://cinnamon-spices.linuxmint.com/applets/view/17 put it into `~/.local/share/cinnamon/applets` (extracted the zip and pasted the folder not the zip file) and the weather applet was showing it was installed but when I clicked add to panel it got messed up. It put my menu button at far right, nothing else happened. [Here's a screenshot.](http://i.imgur.com/sIkiqwV.png)

**Comment by MuhmdRaouf** [comment]
@skullscream First of all i'd like to apologize for all the community as this is not the right place to ask for something like that, but i have seen the screen u provide  [Here's the screenshot](http://i.imgur.com/sIkiqwV.png) and i would like to ask u abut the theme u use the only thing i know is the numix theme icon but what about the winnow border and the control too, they look nice and i could it find'em any where else, thanks in advance mate.

**Comment by JosephMcc** [comment]
The controls and Cinnamon themes look like the Arc dark version. Not sure about the window borders.

**Comment by NikoKrause** [comment]
@skullscream 
Check if in the directory `~/.cinnamon/configs/` is a folder called `weather@mockturtl`.
If yes delete the folder and restart Cinnamon. Then try to add the weather applet again.

**Comment by NikoKrause** [comment]
Ah sorry. There's a pull request waiting to be merged, which seems to fix this problem.

**Comment by skullscream** [comment]
So after the pull is approved I should get this via normal system update? I tried doing your folder deleting and adding method. Still the same.

@MuhmdRaouf the theme is [arc flatabulous dark](https://github.com/andreisergiu98/arc-flatabulous-theme) which I think is made for gnome but seems to work in cinnamon too. 
The bottom bar is also arc-flatabulous-dark but now I changed it to cinnamon. Here's [another screenshot](http://i.imgur.com/a1p6VJ5.png) of my themes setup

**Comment by MuhmdRaouf** [comment]
@skullscream first Thanks a lot for ur answer, the theme looks awesome i love it, and about the control look at the 3rd row in ur image and u will know what i meant by controls, thanks mate ^_^

**Comment by skullscream** [comment]
Ah yes. That. :D No problem.

**Comment by NikoKrause** [comment]
As soon as the pull request is merged it should be available through System Settings > Applets > Available applets (online)
And hopefully it solves your problem.

**Comment by skullscream** [comment]
Cool. Thanks.
