### ISSUE TITLE
Sensors@Claudiux causes stutter

### ISSUE THREAD

**Issue by H34dl3ss** [linuxmint/cinnamon-spices-applets#5346]
### Applet version/Build date

Version 3.1.3 (2023-12-31 19:29:30)

### Cinnamon version

Cinnamon 5.8.4

### Distribution

Linux Mint 21.2 Victoria

### Graphics hardware *and* driver used

NVIDIA GA104 [GeForce RTX 3070] driver: nvidia v: 535.129.03

### Applet name and maintainer

Sensors@claudiux @claudiux

### What happened?

As discovered in bug reports for desklets [https://github.com/linuxmint/cinnamon-spices-desklets/issues/1025](url), and [https://github.com/linuxmint/cinnamon-spices-desklets/issues/932#issuecomment-1783798588](url) spawning subprocesses via `Gio.Subprocess()` is causing stutter in Cinnamon.

I tracked down this applet being also a source of stutter.
It can be observed in a graphical appliance (video, gaming).
I'm using glxgears to check for a smooth motion.
Setting the sensor polling interval to lowest will cause reproducible, serious stutter/chopping.

**Comment by claudiux** [comment]
@H34dl3ss Same response as here: https://github.com/linuxmint/cinnamon-spices-desklets/issues/1025#issuecomment-1872941233
"It's not possible to avoid subprocesses everywhere."
If you have a solution, I'll take it.

**Comment by claudiux** [comment]
I added an option in this applet menu to suspend it, when you want. #5347

**Comment by H34dl3ss** [comment]
Thank you, I just wanted to draw attention on this issue.
In case of the desklets, alternative approaches were possible.
If there are no alternatives, we'll have to live with it.
Maybe it makes sense to raise this issue upstream at the Gio devs?

The "suspend" option is a smart addition.

**Comment by claudiux** [comment]
Maybe a solution: #5395
