### ISSUE TITLE
Sensors@claudiux microfreeze

### ISSUE THREAD

**Issue by freewee** [linuxmint/cinnamon-spices-applets#5352]
### Applet version/Build date

last

### Cinnamon version

5.8.4

### Distribution

Mint 21.2

### Graphics hardware *and* driver used

Nvidia geForce GT555m NVidia driver 390.157 kernel 5.15.0-91

### Applet name and maintainer

Sensors@claudiux @claudiux

### What happened?

Hi
Since months, years, I'm not able to activate "sensors" on my laptop Dell XPS 17 L702X. When activated, there are micro-freezes of the PC in fraction of seconds  that prevent me to do anything, and it's very difficult to type commands in terminal, and click on icons!!
Cinnamon 5.8.4 Mint  21.2
sensors version 3.6.0 with libsensors version 3.6.0
'''
{
	"temps": {
		"ISA adapter dell_smm-isa-0000: CPU": {
			"input": 66
		},
		"ISA adapter dell_smm-isa-0000: Ambient": {
			"input": 36
		},
		"ISA adapter dell_smm-isa-0000: GPU": {
			"input": 56
		},
		"ISA adapter dell_smm-isa-0000: Other": {
			"input": 47
		},
		"ISA adapter dell_smm-isa-0000: SODIMM": {
			"input": 41
		},
		"ISA adapter coretemp-isa-0000: Package id 0": {
			"input": 77,
			"max": 86,
			"crit": 100,
			"crit_alarm": 0
		},
		"ISA adapter coretemp-isa-0000: Core 0": {
			"input": 77,
			"max": 86,
			"crit": 100,
			"crit_alarm": 0
		},
		"ISA adapter coretemp-isa-0000: Core 1": {
			"input": 73,
			"max": 86,
			"crit": 100,
			"crit_alarm": 0
		},
		"ISA adapter coretemp-isa-0000: Core 2": {
			"input": 67,
			"max": 86,
			"crit": 100,
			"crit_alarm": 0
		},
		"ISA adapter coretemp-isa-0000: Core 3": {
			"input": 68,
			"max": 86,
			"crit": 100,
			"crit_alarm": 0
		},
		"ACPI interface acpitz-acpi-0: temp1": {
			"input": 79,
			"crit": 100
		},
		"ACPI interface acpitz-acpi-0: temp2": {
			"input": 79,
			"crit": 100
		}
	},
	"fans": {
		"ISA adapter dell_smm-isa-0000: Processor Fan": {
			"input": 3455
		}
	},
	"voltages": {
		"ACPI interface BAT0-acpi-0: in0": {
			"input": 12.418
		}
	},
	"intrusions": {}
}
'''

'''
{
   "dell_smm-isa-0000":{
      "Adapter": "ISA adapter",
      "Processor Fan":{
         "fan1_input": 2450.000
      },
      "CPU":{
         "temp1_input": 60.000
      },
      "Ambient":{
         "temp2_input": 53.000

      },
      "GPU":{
         "temp3_input": 50.000
      },
      "Other":{
         "temp4_input": 45.000
      },
      "Other":{
         "temp5_input": 45.000
      },
      "SODIMM":{
         "temp6_input": 41.000
      },
      "Ambient":{
         "temp7_input": 38.000
      }
   },
   "BAT0-acpi-0":{
      "Adapter": "ACPI interface",
      "in0":{
         "in0_input": 12.418
      },
      "curr1":{
         "curr1_input": 0.001
      }
   },
   "coretemp-isa-0000":{
      "Adapter": "ISA adapter",
      "Package id 0":{
         "temp1_input": 63.000,
         "temp1_max": 86.000,
         "temp1_crit": 100.000,
         "temp1_crit_alarm": 0.000
      },
      "Core 0":{
         "temp2_input": 51.000,
         "temp2_max": 86.000,
         "temp2_crit": 100.000,
         "temp2_crit_alarm": 0.000
      },
      "Core 1":{
         "temp3_input": 58.000,
         "temp3_max": 86.000,
         "temp3_crit": 100.000,
         "temp3_crit_alarm": 0.000
      },
      "Core 2":{
         "temp4_input": 59.000,
         "temp4_max": 86.000,
         "temp4_crit": 100.000,
         "temp4_crit_alarm": 0.000
      },
      "Core 3":{
         "temp5_input": 57.000,
         "temp5_max": 86.000,
         "temp5_crit": 100.000,
         "temp5_crit_alarm": 0.000
      }
   },
   "acpitz-acpi-0":{
      "Adapter": "ACPI interface",
      "temp1":{
         "temp1_input": 64.000,
         "temp1_crit": 100.000
      },
      "temp2":{
         "temp2_input": 64.000,
         "temp2_crit": 100.000
      }
   }
}
'''
I have also micro-freezes with temperature@fevimu , but much less common,about every 3 seconds.

Thank you for your work, I have no problem on my desktop!
Happy new year!

**Comment by claudiux** [comment]
Please try setting the Refresh interval to 5 seconds.

**Comment by freewee** [comment]
It's a little easier to click a menu, but still freezes which prevent you from listening to music for example!

**Comment by claudiux** [comment]
How many sensors are displayed in panel, in tooltip?
Some sensors may be faulty; try removing them all and then adding them one by one.

**Comment by freewee** [comment]
Even when I choose not to display any temperature, I have the problem! My normal choice was to display only one temperature. I have 2 Dell XPS 17 L702X, and they have the same problem...

**Comment by claudiux** [comment]
Please display here the result of: `cat /etc/modules`

**Comment by freewee** [comment]
dominique@FREEWEE-PC:~$ cat /etc/modules
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.
Nothing else!

**Comment by claudiux** [comment]
Maybe the cause of your problem. Please run `sudo sensors-detect`.

**Comment by freewee** [comment]
# sensors-detect version 3.6.0
# System: Dell Inc. Dell System XPS L702X (laptop)
# Board: Dell Inc. 03RG89
# Kernel: 5.15.0-91-generic x86_64
# Processor: Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz (6/42/7)

This program will help you determine which kernel modules you need
to load to use lm_sensors most effectively. It is generally safe
and recommended to accept the default answers to all questions,
unless you know what you're doing.

Some south bridges, CPUs or memory controllers contain embedded sensors.
Do you want to scan for them? This is totally safe. (YES/no): y
Module cpuid loaded successfully.
Silicon Integrated Systems SIS5595...                       No
VIA VT82C686 Integrated Sensors...                          No
VIA VT8231 Integrated Sensors...                            No
AMD K8 thermal sensors...                                   No
AMD Family 10h thermal sensors...                           No
AMD Family 11h thermal sensors...                           No
AMD Family 12h and 14h thermal sensors...                   No
AMD Family 15h thermal sensors...                           No
AMD Family 16h thermal sensors...                           No
AMD Family 17h thermal sensors...                           No
AMD Family 15h power sensors...                             No
AMD Family 16h power sensors...                             No
Hygon Family 18h thermal sensors...                         No
Intel digital thermal sensor...                             Success!
    (driver `coretemp')
Intel AMB FB-DIMM thermal sensor...                         No
Intel 5500/5520/X58 thermal sensor...                       No
VIA C7 thermal sensor...                                    No
VIA Nano thermal sensor...                                  No

Some Super I/O chips contain embedded sensors. We have to write to
standard I/O ports to probe them. This is usually safe.
Do you want to scan for Super I/O sensors? (YES/no): y
Probing for Super-I/O at 0x2e/0x2f
Trying family `National Semiconductor/ITE'...               No
Trying family `SMSC'...                                     No
Trying family `VIA/Winbond/Nuvoton/Fintek'...               No
Trying family `ITE'...                                      No
Probing for Super-I/O at 0x4e/0x4f
Trying family `National Semiconductor/ITE'...               Yes
Found `ITE IT8518E Super IO'                                
    (no support yet)

Some hardware monitoring chips are accessible through the ISA I/O ports.
We have to write to arbitrary I/O ports to probe them. This is usually
safe though. Yes, you do have ISA I/O ports even if you do not have any
ISA slots! Do you want to scan the ISA I/O ports? (YES/no): y
Probing for `National Semiconductor LM78' at 0x290...       No
Probing for `National Semiconductor LM79' at 0x290...       No
Probing for `Winbond W83781D' at 0x290...                   No
Probing for `Winbond W83782D' at 0x290...                   No

Lastly, we can probe the I2C/SMBus adapters for connected hardware
monitoring devices. This is the most risky part, and while it works
reasonably well on most systems, it has been reported to cause trouble
on some systems.
Do you want to probe the I2C/SMBus adapters now? (YES/no): y
Using driver `i2c-i801' for device 0000:00:1f.3: Intel Cougar Point (PCH)

Next adapter: SMBus I801 adapter at efa0 (i2c-0)
Do you want to scan it? (YES/no/selectively): y


Next adapter: NVIDIA i2c adapter 0 at 1:00.0 (i2c-1)
Do you want to scan it? (yes/NO/selectively): 
Next adapter: NVIDIA i2c adapter 1 at 1:00.0 (i2c-2)
Do you want more?

**Comment by claudiux** [comment]
`echo "coretemp" | sudo tee -a /etc/modules`

`sudo modprobe coretemp`

Please tell me if that solves your problem.

**Comment by claudiux** [comment]
Also try:
`sudo modprobe drivetemp`

If no error message appears, then:
`echo "drivetemp" | sudo tee -a /etc/modules`

**Comment by claudiux** [comment]
In the temperature tab of this applet settings, on my computer:
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/33965039/cce10685-6901-4c54-9d2e-af622660333a)

**Comment by freewee** [comment]
No change with both... I have the temperatures for each core, but even when the temperatures are unchecked, I have micro freezes. 
I test "hardware sensors indicator" that uses coretemp-isa-0000, without freezes, but doesn't show the temperature on the board...

**Comment by claudiux** [comment]
Please try #5358 and uncheck "Display a tooltip on mouseover" in the General tab.

**Comment by freewee** [comment]
I'm still perplexed by the github site, because I don't speak English!!! Thank you but what should I do with what you show me?? probably replace a file somewhere but which one and where?

**Comment by claudiux** [comment]
Open a terminal and type:
`xed ~/.local/share/cinnamon/applets/Sensors@claudiux/applet.js`
In your browser, visit: https://raw.githubusercontent.com/linuxmint/cinnamon-spices-applets/153d3ec657342e726ccbd99d081bed7ae0f33f64/Sensors%40claudiux/files/Sensors%40claudiux/applet.js
Ctrl+A to select all. Ctrl+C to copy.
In xed: Ctrl+A to select all. Ctrl+V to replace by the new version. Ctrl+S to save applet.js. Close xed.

Then, in the terminal:
`xed ~/.local/share/cinnamon/applets/Sensors@claudiux/settings-schema.json`
In your browser, visit: https://raw.githubusercontent.com/linuxmint/cinnamon-spices-applets/153d3ec657342e726ccbd99d081bed7ae0f33f64/Sensors%40claudiux/files/Sensors%40claudiux/settings-schema.json
Ctrl+A to select all. Ctrl+C to copy.
In xed: Ctrl+A to select all. Ctrl+V to replace by the new version. Ctrl+S to save settings-schema.json. Close xed.

Restart Cinnamon only when both files are saved.

**Comment by freewee** [comment]
OK thank you I will try it as soon as possible, this evening, because i' m a little busy now! Thanks a lot!

**Comment by freewee** [comment]
"Display a tooltip on mouseover" unchecked, but always the problem...

**Comment by claudiux** [comment]
The problem seems to come from Gio.subProcess. Solving it is beyond my capabilities.

**Comment by freewee** [comment]
Thank you for the job!

**Comment by claudiux** [comment]
Maybe a solution: #5395
