### ISSUE TITLE
[directory-menu@torchipeppo] Does not open any menu on Cinnamon 5.4+

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon-spices-applets#5387]
### Applet version/Build date

Version 0.1 (2024-01-13 19:12:39)

### Cinnamon version

5.4+

### Distribution

Mint 21+

### Graphics hardware *and* driver used

No matters

### Applet name and maintainer

directory-menu@torchipeppo @torchipeppo 

### What happened?

Successfully tested on Cinnamon 5.0 and 5.2, this applet does not work on Cinnamon from 5.4 to 6.0.

No message in `~/.xsession-errors`, but the menu does not appear when clicking on the applet icon.

**Comment by torchipeppo** [comment]
This issues should be solved by these PRs now:
- https://github.com/linuxmint/cinnamon-spices-applets/pull/5451
- https://github.com/linuxmint/cinnamon-spices-applets/pull/5453
