### ISSUE TITLE
 weather@mockturl - OpenWeatherMap not updating.

### ISSUE THREAD

**Issue by MedjoPangit** [linuxmint/cinnamon-spices-applets#5392]
### Applet version/Build date

3.3.1

### Cinnamon version

6.0.4

### Distribution

21.3 Cinnamon

### Graphics hardware *and* driver used

N/A

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

I use OpenWeatherMap in this taskbar applet.  Lately, I've noticed, within the past few weeks, that the value it displays in the taskbar does not update.  If I click on the applet, it will show everything correct, but the main value displayed in the taskbar is stuck on what it was when I last rebooted, it seems.

**Comment by tcurry250** [comment]
Same here.  Upgraded from 21.2 to 21.3 then noticed weather applet would not refresh on startup.  Taskbar just shows a circular arrow as if waiting for a refresh.  Refreshing does nothing.   I have to remove the applet then re-add every time.  Only then it works,   This just started after the upgrade to 21.3.  After a reboot I have to go through the same process again and again.

**Comment by dunkfan** [comment]
Configure -> "Reload weather" can be used as a workaround

**Comment by UltiWebAlt** [comment]
Reload isn't reloading. I'm on Mint 21.3/Cinnamon 6.x. Mine says 1:25 PM. No idea what day that is. It is 9:30 AM.

**Comment by UltiWebAlt** [comment]
I removed it and added it back in Applets settings and it's working again.

**Comment by tcarver01** [comment]
I tried removing and adding back, no good. As soon as my computer goes to sleep or I reboot/shutdown Weather will not update and I must reload Cinnamon or the applet. It will be fixed eventually.

**Comment by Gr3q** [comment]
@tcarver01 Is your network disconnects when you go to sleep (wifi)?

**Comment by sagon53** [comment]
Das kann aber nicht die Lösung sein, traurig das der Bug nicht vom Programmierer behoben wird.
