### ISSUE TITLE
Set label to fixed width to stop it affecting adjacent applets

### ISSUE THREAD

**Issue by Praful** [linuxmint/cinnamon-spices-applets#5405]
### Applet name and maintainer

temperature@fevimu @claudiux

### What would you like to see?

The width used by the applet changes as the temperature changes if a variable font is used for the panel. This results in adjacent applets moving around slightly if the temperature applet is in the middle of a panel. 

To workaround this I put the applet at the end (left end of right section). Is there a way to fix the temperature applet's size so that it doesn't keep changing size when updated?

**Comment by claudiux** [comment]
Please update this applet and try the option "Avoid size changes" in settings.

**Comment by Praful** [comment]
Thank you for the quick response. This now works with a few fonts I've tried except for one: [Inter font](https://fonts.google.com/specimen/Inter), eg, _Inter Medium_ or _Inter Regular_. I've gone back to using _DejaVu Sans Book_ so it doesn't affect me but you may way to see if you get the same.
