### ISSUE TITLE
CPU Temperature Indicator: text colour changed from white to black

### ISSUE THREAD

**Issue by csimonosian** [linuxmint/cinnamon-spices-applets#5410]
### Applet version/Build date

2024.01.24

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

NVIDIA GeForce GTX 1060 6GB and nvidia-driver-535

### Applet name and maintainer

temperature@fevimu @claudiux

### What happened?

It seems that with this release, the text colour has changed from white to black and it's now invisible on my background. It's happened on three different PCs, all today, same Cinnamon & Mint but different GPUs. I've attached the screen shots, before, after and with a coloured background. It does appear to vary according to the theme, however it didn't before this update.
![before](h
![after](https://github.com/linuxmint/cinnamon-spices-applets/assets/72629997/52be041e-2491-4a72-b55d-2329ba54723c)
ttps://github.com/linuxmint/cinnamon-spices-applets/assets/72629997/09c49512-c942-4a81-be7a-e6cc1268adfa)
![with coloured bg](https://github.com/linuxmint/cinnamon-spices-applets/assets/72629997/6a8402d2-ab91-4319-89e7-9322b41f3c92)

**Comment by csimonosian** [comment]
![after](https://github.com/linuxmint/cinnamon-spices-applets/assets/72629997/89baa7f5-65ff-4ec2-b85a-b8c8109dd1a1)

**Comment by claudiux** [comment]
@csimonosian 
Please try to change in the line 183 of `~/.local/share/cinnamon/applets/temperature@fevimu/applet.js`:
`"applet-label"` by `"applet-box"`, save the file, restart this applet (or Cinnamon) and tell me if that solves this issue.

**Comment by csimonosian** [comment]
@claudiux 
Yes, this has indeed fixed the issue, the text is back to white. Thank you.
