### ISSUE TITLE
Weather applet shows wrong current time

### ISSUE THREAD

**Issue by altaloma** [linuxmint/cinnamon-spices-applets#5419]
### Applet version/Build date

3.8

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

The 'As of time' appears to be Australian east coast time instead of Perth west coast time. I have the location set manually to Bullsbrook, Australia which is in Western Australia.

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/66456780/adb1277b-5469-4393-a0e3-fd101c1863db)

**Comment by Gr3q** [comment]
The "as of" time shows when the applet last updated (in your local time), not the timestamp the forecast is for.

If you get east coast time and your system is not set to that, than it is indeed a bug. Otherwise it is expected.

Maybe a case can be made that both should be shown, but I have a hard time fitting all of the into the bar

**Comment by Gr3q** [comment]
Also I'm sad that the bug where you end up with no padding still happens

**Comment by altaloma** [comment]
Yeah, I did have second thoughts after I'd submitted the bug but seeing 2.54pm when it is 11 in the morning is a bit confusing.

This is what the apps says now, but it's 35 degrees outside. My Android phone says 35 degrees now with a top of 38 degrees which is correct.

I know you can't control the forecast but it almost looks like it's a day out of sync, yesterday was about 28 degrees.

***@***.***




On Tue, 2024-01-30 at 01:18 -0800, Attila Greguss wrote:
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

The "as of" time shows when the applet last updated (in your local time), not the timestamp the forecast is for.

If you get east coast time and your system is not set to that, than it is indeed a bug. Otherwise it is expected.

Maybe a case can be made that both should be shown, but I have a hard time fitting all of the into the bar

**Comment by altaloma** [comment]
Just realised that the first day shown as Today is Sunday, today is Tuesday.


On Tue, 2024-01-30 at 17:42 +0800, Franco Broi wrote:

Yeah, I did have second thoughts after I'd submitted the bug but seeing 2.54pm when it is 11 in the morning is a bit confusing.

This is what the apps says now, but it's 35 degrees outside. My Android phone says 35 degrees now with a top of 38 degrees which is correct.

I know you can't control the forecast but it almost looks like it's a day out of sync, yesterday was about 28 degrees.

***@***.***




On Tue, 2024-01-30 at 01:18 -0800, Attila Greguss wrote:
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

The "as of" time shows when the applet last updated (in your local time), not the timestamp the forecast is for.

If you get east coast time and your system is not set to that, than it is indeed a bug. Otherwise it is expected.

Maybe a case can be made that both should be shown, but I have a hard time fitting all of the into the bar

**Comment by Gr3q** [comment]
That is concerning. is the "as of" time updating at all? If you are looking at the (Looking Glass) logs what do you see?

OpenWeatherMap never provides past info, so I think your app stopped updating.

I really should add a some kind of warning somewhere if you are rally out of date, I just don't know how.

**Comment by altaloma** [comment]
info t=2024-01-29T07:34:03Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-29T10:44:55Z ***@***.******@***.***>#16]: Refreshing in progress, refresh skipped.
info t=2024-01-29T10:45:12Z ***@***.******@***.***>#16]: Refreshing in progress, refresh skipped.
info t=2024-01-29T10:46:05Z ***@***.******@***.***>#16]: Refreshing in progress, refresh skipped.
info t=2024-01-29T10:46:21Z ***@***.******@***.***>#16]: Refreshing in progress, refresh skipped.
info t=2024-01-29T10:46:27Z ***@***.******@***.***>#16]: Refreshing in progress, refresh skipped.
info t=2024-01-29T11:20:15Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-29T12:37:31Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-29T12:37:31Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-29T12:37:36Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-29T12:42:50Z Adding systray: pidgin (1x1px)
info t=2024-01-29T13:51:01Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-29T15:55:02Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-29T15:55:02Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-29T15:55:07Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-29T17:31:01Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-30T07:17:39Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-30T07:17:39Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-30T07:17:44Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-30T08:50:45Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-30T13:17:24Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-30T13:17:24Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-30T13:17:29Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-30T13:21:25Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-30T15:12:00Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-30T15:12:00Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-30T15:12:05Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-30T15:17:47Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-30T16:31:45Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-30T16:31:45Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-30T16:31:51Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-31T07:41:40Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-31T07:41:42Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-31T07:41:43Z ***@***.******@***.***>#16]: Internet access now down with "1", pausing refresh.
info t=2024-01-31T07:41:48Z ***@***.******@***.***>#16]: Internet access now available, resuming operations.
info t=2024-01-31T07:50:11Z ***@***.******@***.***>#16]: Refreshing in progress, refresh skipped.
info t=2024-01-31T07:50:58Z ***@***.******@***.***>#16]: Refreshing in progress, refresh skipped.
info t=2024-01-31T07:52:12Z ***@***.******@***.***>#16]: Refreshing in progress, refresh skipped.


On Tue, 2024-01-30 at 12:58 -0800, Attila Greguss wrote:
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

That is concerning. is the "as of" time updating at all? If you are looking at the (Looking Glass) logs what do you see?

OpenWeatherMap never provides past info, so I think your app stopped updating.

I really should add a some kind of warning somewhere if you are rally out of date, I just don't know how.
