### ISSUE TITLE
[weather@mockturtl] Feature Request: Save Weather Service JSON

### ISSUE THREAD

**Issue by BillyCroan** [linuxmint/cinnamon-spices-applets#5420]
### Applet name and maintainer

weather@mockturtl @Gr3q

### What would you like to see?

I use my API key to retrieve forecast data.  Each fetch consumes resources from OWM, and attributes usage to my key.

I would like to keep the data that the weather applet retrieves, in a log file or in a directory somewhere ( $HOME/logs/WeatherAppletFetches/$YYYYMMDD/$HHMMSS.json )

I'd like to use this data with other scripts that currently fetch their own data completely separately, to produce weather info visible on my screensaver.   And today that doubles the hits I make against the OWM api.

And I need to be able to look back at it over time to check forecast accuracy or remember things like "when was the _last time_ it was freezing here?"  or "When did the forecast _first show_ there would be rain this week?"  

I know it will pile up over time.  But I will take responsibility of cleaning it up.

I tried to add this myself but I can't seem to import the "fs module" needed to make a dir or write to a file:
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/37587/d232f224-36f2-4a2f-823f-b6218e354d17)

I thought about increasing log verbosity because that does cause JSON to appear in syslog, but it looks like its truncated to a couple thousand char there, probably for good cause in a syslog file.

My goal is reducing my footprint on the OWM servers, as well as creating an almanac so to speak, of the weather I have seen in the past.

**Comment by Gr3q** [comment]
Node libraries are not available in gjs, this is why it's not working. You can see the utility functions I'm using here https://github.com/linuxmint/cinnamon-spices-applets/blob/master/weather%40mockturtl/src/3_8/lib/io_lib.ts, although I did not implement an append function, just an overwrite one. Also I would do this in the `RefreshWeather` function.

I could do this in the next release, but that won't be now.

**Comment by BillyCroan** [comment]
Thanks for the tips and again for an awesome plugin.  I'll hack on my system some more.  The Json we get back is so small and drives so large these days it's a shame not to keep it.

**Comment by Gr3q** [comment]
I thought about this. Saving a history is probably an overkill for the applet, but what if I add a field in settings where you can enter a command/script that I will call every time the weather data refreshes.

I don't know how I would expose the data to it just yet, but it would probably be with 1 or more env variables, so it's easy to use any language to process them.

**Comment by BillyCroan** [comment]
That sounds workable.  And it would enable not just me but others too, to extend their use of the applet and weather data.  My city has severe wind storms and tornado season every year.  (exciting!)  And I'm going to set something up to pop up the radar gif for my area when we're under tornado watch and an adjacent county has had actual tornados on ground.

**Comment by BillyCroan** [comment]
Funny bug to report on this feature.

I errantly set the run command:
echo {{full_data} >> $HOME/logs/WeatherApplet/$( date +%Y%m%d_%H%M%S).log

(My error was one missing right curly brace)

Instead of no execution or an error, I was getting "partial" saves.  the jq parser was telling me the output was incomplete, and it looks like it is getting cut off.  Obviously an easy fix for me, but I thought I'd mention it because I didn't expect an error on the command spec to result in the output being cut off.

Thanks again for this feature and I hope you're having a great summer!

**Comment by Gr3q** [comment]
It was outputting { and the full data unescaped because of single braces.

I guess I could throw an error on mismatching curly braces.

**Comment by BillyCroan** [comment]
Perhaps I should also put the {{full_data}} in double-quotes to be safer in the chance that the .json file included a \nrm -rf / or some such??..... actually that doesn't run properly.  I changed it to

$HOME/logs/WeatherApplet/ingest <<< {{full_data}} so I could act on the json data more directly and that seems good.

**Comment by Gr3q** [comment]
{{}} will wrap the value in ' (which prevents evaluation) as a literal and all ' will be escaped inside.

So there is no need to wrap it in double quotes.

With {} you would need to do, but you wouldn't be able to escape " or ' inside the value
