### ISSUE TITLE
[screen-inhibit@mtwebster] Please add option to inhibit screensaver at startup

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon-spices-applets#5421]
### Applet name and maintainer

screen-inhibit@mtwebster

### What would you like to see?

@mtwebster 
Please add an option in settings to inhibit screensaver at startup.

**Comment by rcalixte** [comment]
This looks like it's been retired and moved to [Cinnamon](https://github.com/linuxmint/cinnamon/commits/master/files/usr/share/cinnamon/applets/inhibit%40cinnamon.org). For what it's worth, with something like `xdotool` and the latest version of the applet, you could just set a startup script to accomplish this.
