### ISSUE TITLE
weather@mockturtl Refresh icon still persists after 3.4.0 update

### ISSUE THREAD

**Issue by st4r-w4rs** [linuxmint/cinnamon-spices-applets#5425]
### Applet version/Build date

3.4.0

### Cinnamon version

6.0.4

### Distribution

Linux Mint 21.3 Virginia

### Kernel

5.15.0-92-generic

### Graphics hardware *and* driver used

NVIDIA GeForce GTX 1050 Ti, Nvidia driver 535.154.05

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

#5212 This issue still persist after today's pull request (#5396), only refresh icon after computer starts up :(

@Gr3q

**Comment by Gr3q** [comment]
Ok, can you provide full Debug level logs for the applet?

So I can know where it goes wrong exactly, because I still can't reproduce this.

**Comment by st4r-w4rs** [comment]
Sure I hope this is what you're asking for, uploaded it to my gists: 
https://gist.github.com/st4r-w4rs/addc1aa10815dfbeee80d2792636a0f5

**Comment by st4r-w4rs** [comment]
@Gr3q 

adding one additional log, from LookingGlass / Melange:
https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab

**Comment by st4r-w4rs** [comment]
@Gr3q 

adding one additional log, from LookingGlass / Melange:
https://gist.github.com/st4r-w4rs/bf59e6668911b63d70ea59132f53b4a7

**Comment by st4r-w4rs** [comment]
@Gr3q 
Many people reporting the same issue on the cinnamon spices website.
However I have some new info, maybe that can help or to be forwarded towards mint's dev team for further investigation (quoted my post from cinnamon spices website):

> Things start to be very odd on my end. I also upgraded my Mint from 21.2 to 21.3 and this circling icon still appears, however I also upgraded three of my laptops to Mint 21.3, and this arrow thing doesn't even show up, it works as intended but only on laptops o.O
> And its not even with the wifi or plugged in network, I tried them both, both seems to work on laptops, but not on desk pc.
> It's something that happened with cinnamon or mint's network manager
^The above last sentence is a wild guess tho!

**Comment by st4r-w4rs** [comment]
![Képernyőkép – 2024-02-07 10-58-31](https://github.com/linuxmint/cinnamon-spices-applets/assets/123484746/6a0f3252-454b-4607-82a0-223c8584446f)
