### ISSUE TITLE
VPN-Sentinel: Hide the flag place setting is ignored on startup

### ISSUE THREAD

**Issue by McConsington** [linuxmint/cinnamon-spices-applets#5449]
### Applet version/Build date

2.2.1

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Applet name and maintainer

VPN-Sentinel@claudiux @claudiux

### What happened?

The "hide the flag place" option is ignored on applet startup. The setting only works correctly when changing it around in the config menu while the applet is running.
To reproduce, simply set the "While VPN is off" flag setting to "Hide the flag place" and then reload the applet or restart Cinnamon.

**Comment by claudiux** [comment]
@McConsington I see. Thanks to reporting this issue.

**Comment by McConsington** [comment]
Thank you! Works perfectly in 2.2.2 now :)

**Comment by claudiux** [comment]
I'm glad you're satisfied. Please consider increasing the score of this applet on https://cinnamon-spices.linuxmint.com/applets/view/368

**Comment by McConsington** [comment]
Done! :+1:

**Comment by claudiux** [comment]
Thank you!
