### ISSUE TITLE
weather@mockturtl: Reboot Bug

### ISSUE THREAD

**Issue by Rambo-Junior** [linuxmint/cinnamon-spices-applets#5457]
### Applet version/Build date

3.4.0

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

GPU: Intel HD Graphics 530

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

Only works after reinstall, if system is rebooted not show/refresh weather at all

### Other information

[02042024.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/14158684/02042024.txt)
verbose log attached

**Comment by anaximeno** [comment]
Reloading the applet (in the configuration, not the refresh on the menu) also works instead of having to reinstall the applet. This might be a temporary solution while the bug isn't fixed.

**Comment by Rambo-Junior** [comment]
> Reloading the applet (in the configuration, not the refresh on the menu) also works instead of having to reinstall the applet. This might be a temporary solution while the bug isn't fixed.

Thanks for the reply, on which tab I can do that?

**Comment by anaximeno** [comment]
There:
![Captura de ecrã de 2024-02-05 17-24-50](https://github.com/linuxmint/cinnamon-spices-applets/assets/63073056/53682b89-566f-46ab-b836-88f1d542964e)

**Comment by mattmilano** [comment]
Restarting Cinnamon also forces the weather applet to refresh. I've added the Restart Cinnamon applet for speed.
