### ISSUE TITLE
[anime-wallpaper@flyflyan] Applet Bug 

### ISSUE THREAD

**Issue by Do-fomin** [linuxmint/cinnamon-spices-applets#5470]
### Applet version/Build date

3.4.0 (2024-02-04 21:33:18)

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt Radeon Graphics × 8

### Applet name and maintainer

anime-wallpaper@flyflyan @fly206

### What happened?

Not loaded after starting the system. It is required to restart the applet manually

**Comment by fredcw** [comment]
Which applet?
