### ISSUE TITLE
sct@skulptist.de: Theming Feature Request

### ISSUE THREAD

**Issue by Matthias-Hermsdorf** [linuxmint/cinnamon-spices-applets#5484]
### Applet name and maintainer

sct@skulptist.de @Matthias-Hermsdorf

### What would you like to see?

Hey me, 
please make the color of the default icon of my applet corresponding to the gtk icons around.

The Icon in the Panel uses this.set_applet_icon_symbolic_path(iconPath) by default. The icon has a fill: #fff which works fine on a dark background, but works not at all at a light background. Changing the fill color wouldn't be a problem. Or adding a second color variant. But I would prefer to use a css variable for the color in the svg. Or to have an api to get to know if the theme is light or dark or mixed.

https://blog.linuxmint.com/?p=4486 mentions symbolic gtk icons, which change color depending of the content.

Is there any documentation about how this dynamic coloring works, an if or when it gets shipped to the spiceland?

@rcalixte Do you know something?

**Comment by rcalixte** [comment]
Symbolic icons are svg files that are monochrome by default. If you are on a Linux system, run something like:
```bash
$ locate -r "symbolic.*svg" | wc -l
8887
```
This should help you get an idea of what your resulting file would look like.

The beauty of them is that as long as you specific in your code that the icon is symbolic, it will automatically be handled for you.

There are also gsettings you can read from as well using the Settings import, here as a command from my machine:
```bash
$ gsettings get org.gnome.desktop.interface color-scheme
'prefer-dark'
```
There are other Spices that have done something like this too.

Some Spices also do custom implementations for styling. I'm currently working on [this desklet](https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/bbcwx%40oak-wood.co.uk/files/bbcwx%40oak-wood.co.uk/5.4/desklet.js#L4332-L4354) and you can see how that solution is implemented for styling objects when it's called [here](https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/bbcwx%40oak-wood.co.uk/files/bbcwx%40oak-wood.co.uk/5.4/desklet.js#L616).

If all else fails, you can have the user customize it on their end via some sort of selection.


> Is there any documentation about how this dynamic coloring works, an if or when it gets shipped to the spiceland?

Sparse documentation exists, but [this](https://wiki.gnome.org/HowDoI/CreateSymbolicIconsThatChangeColorAccordingToTheme) serves as the most reliable example that I can find. It's already supported for all Spice types though.

**Comment by Matthias-Hermsdorf** [comment]
Thanks for your reply. The solution was easier than expected.

Add -symbolic to the filename

Applet.IconApplet has 4 icon functions. 2 for icons by name. And these two

.set_applet_icon_symbolic_path ()  
.set_applet_icon_path ()

Found [in Grenoble](http://transit.iut2.upmf-grenoble.fr/cgi-bin/dwww/usr/share/doc/cinnamon/cinnamon-js/cinnamon-js-ui-applet-IconApplet.html)

Using my icon with the .set_applet_icon_path results in an icon in the size of the colored App Icons. Using .set_applet_icon_symbolic_path renders icons in the size of the other monochrome status icons. 

With a filename like "icon.svg" I can set the fill and stroke colors for the svg elements and it gets rendered colorful. If I use "icon-symbolic.svg" the fill and stroke style attributes get ignored and get set by the theme.

How could I add that to the documentation? Why is the devHelp in another version than the websites online?

My problem is solved. The next version is on the way.

The code in bbcwx@oak-wood.co.uk is very long. 4,5k lines in one file. That is pretty long. Is that a compilation of different files? If not I would recommend to split it into modules, each less than 400 lines.
Thanks for your help.

**Comment by Matthias-Hermsdorf** [comment]
in the next update 1.2.2 the icon is theme colored
