### ISSUE TITLE
vboxlauncher@mockturtl - VMware VMs unable to start

### ISSUE THREAD

**Issue by MuhmdRaouf** [linuxmint/cinnamon-spices-applets#55]
every time i try to open my VMware VMs using this applet nothing happen, virtual box and its related virtual works good, vmplayer works good, my problem in loading vmplayer VMs, i tried to find the problem and solved my and post it but unfortunately i cant write java script, but i am summing the problem with the VMs path,

i am not that good with linux so if u need any log just tell me how to do it and i'll provide u with anything u want in order to fix that bug

**Comment by MuhmdRaouf** [comment]
i have found the error it's located at the line 218 :
Util.spawnCommandLine(CMD_VMPLAYER + " " + path)
if the VM name has spaces it wont work as the command wont run due the termenal does not accept spaces in name, so i had added single quote before and after the path to be :
Util.spawnCommandLine(CMD_VMPLAYER + " ' " + path + " ' ")
now every thing runs smoothly :100:

**Comment by NikoKrause** [comment]
@mockturtl
Maybe this should be fixed in the applet?

**Comment by mockturtl** [comment]
@MuhmdRaouf Good catch.  Spaces in filenames are the devil's work. :stuck_out_tongue: 

Could you submit a PR?

**Comment by mockturtl** [comment]
My mistake, it's here: #64
