### ISSUE TITLE
BAMS: ambiguous slider; no option within main menu for suspend threshold

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon-spices-applets#5500]
### Applet version/Build date

2.1.0

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Intel; Mesa

### Applet name and maintainer

batterymonitor@pdcurtis @pdcurtis

### What happened?

1) I left clicked on the applet, saw a slider, and wondered just what the slider controlled. So I opened the main BAMS menu, adjusted the aforementioned slider, and looked for changes in values within the main window. Seemingly the _alert_ setting changed, whereas so far as the slider gives one a steer one thinks that the slider changes the _alert_ threshold.

2) Seemingly there is no way within the main menu to change the alert threshold (!).

### Other information

I changed my 'desktop' theme - from Mint-L Dark Teal - to a light theme. So doing make no substantial change to the slider sub-menu.

Here is a screenshot of what I see.

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/47056543/61df60bc-8427-4385-afe1-c1e6ee120517)

**Comment by rcalixte** [comment]
This has been the core functionality of the applet for some time now. Adding a synced slider to the settings dialog hopefully shouldn't take too long though. What would you suggest for the title on the slider in the settings since it technically controls two options? It alters both the alerting and suspension thresholds.

**Comment by LinuxOnTheDesktop** [comment]
I am afraid that I have trouble understanding your first two sentences.

The slider 'controls two options'? How can a single slider control two thresholds?

**Comment by LinuxOnTheDesktop** [comment]
_Ah_: now that I have lowered the value of the option 'Refresh Interval for Display', I discover that adjusting the slider that appears within the dialogue window does adjust both the 'alert' value and the 'suspend' value (such that, while the two values are never identical, they do vary one with the other).

It seems to me that it would be better to split those two options. If the two options are to remain conjoined then thinking of a label for the slider is indeed hard. One could try this label: 'alert-and-suspend'.

**Comment by rcalixte** [comment]
That first issue sounds like a bug. The values should update when the slider is adjusted. For the display in the configuration options, I have some ideas I need to test but separating them out is unlikely given how tricky that would be to implement. (Think about a value like 20. It can be both a min and a max. Changing one value would mean having to redraw the slider for the other.) The core functionality for the applet is to alert before triggering any other action so I want to make sure both actions stay coupled to reduce bugs that impact that core functionality.

Two action items for me:
* Adjusting the slider in the menu should update with the new values right away.
* Adding the slider from the menu into the configuration options and making sure they are synced.
