### ISSUE TITLE
Applet Bug app-launcher@mchilli

### ISSUE THREAD

**Issue by vilqvilq** [linuxmint/cinnamon-spices-applets#5519]
### Applet version/Build date

 "last-edited": 1707164733

### Cinnamon version

5.2.7

### Distribution

Mint 20.3

### Graphics hardware *and* driver used

intel HD Graphics P530 // i915

### Applet name and maintainer

app-launcher@mchilli @mchilli

### What happened?

More operations makes applet slower and slower in time... [even 5min]

1. from CinnVIIStarkMenu

a] Moving apps and dropping to applet

2. in Applet Editor

a] Moving apps/groups
b] Editing apps/group

after 10-15 operations cinnamon needs restart and cycle repeats...

### Other information

Looking Glass shows no info

**Comment by mchilli** [comment]
Hey and I'm sorry you're having trouble with my applet. Maybe it's because the applet is always updated when you change the order or edit an entry. Unfortunately I don't have the time at the moment, so it may take some time to find a solution.
I hope you can use it anyway.
