### ISSUE TITLE
GPaste package can't be installed on latest Ubuntu

### ISSUE THREAD

**Issue by K0-RR** [linuxmint/cinnamon-spices-applets#5539]
### Applet version/Build date

2.6

### Cinnamon version

5.8.4

### Distribution

Rhino Linux (Ubuntu Noble)

### Applet name and maintainer

gpaste-reloaded@feuerfuchs.eu @feuerfuchs

### What happened?

The applet requires me to install gpaste, it is however no more available - replaced by gpaste-2.

### Other information

```
sudo apt install gpaste
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package gpaste is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gpaste-2

E: Package 'gpaste' has no installation candidate
```

**Comment by Zalk0** [comment]
Same for Mint 22 because I believe the change of the gpaste package comes from Ubuntu

**Comment by fredcw** [comment]
Install gpaste-2 and gir1.2-gpaste-2 instead. It seems to work just the same.

**Comment by aventura-ms** [comment]
> Install gpaste-2 and gir1.2-gpaste-2 instead. It seems to work just the same.

It helped but when shortcuts keyboard still doesnt work
