### ISSUE TITLE
Cinnamenu tooltip outside screen

### ISSUE THREAD

**Issue by AndreiMiculita** [linuxmint/cinnamon-spices-applets#5543]
### Applet version/Build date

5.4.13

### Cinnamon version

5.8.4

### Distribution

21.2

### Applet name and maintainer

Cinnamenu@json @fredcw

### What happened?

When the sidebar location is set to bottom, the tooltip shows partially outside the screen.

Might be a more general cinnamon issue, in which case it should be added to the cinnamon repo too. But I can't tell where the source is.

### Other information

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/6352172/97f4d2d5-661d-408a-854d-f9debbc91a01)

**Comment by rcalixte** [comment]
This is a Cinnamon issue that is resolved in Cinnamon 6.0+.

The PRs with the fixes are linuxmint/cinnamon#11980 and linuxmint/cinnamon#11991.

**Comment by fredcw** [comment]
Actually, this is a bug in Cinnamenu because Cinnamenu implements it's own tooltips.

Thanks for reporting, I'll have a fix ASAP.
