### ISSUE TITLE
Feature Request: Weather applet should show weather alerts/warnings

### ISSUE THREAD

**Issue by joeskeen** [linuxmint/cinnamon-spices-applets#5546]
### Applet name and maintainer

weather@mockturtl @Gr3q

### What would you like to see?

We are currently experiencing a High Wind warning in my area. But the weather applet doesn't seem to think there's any reason to display this alert to the user. I can't find any settings on how to make it appear. I did turn on verbose logging and found that the data retrieved did indeed include this alert:

```json
Gjs-Message: 09:04:25.116: JS LOG: [LookingGlass/info] [weather@mockturtl#29:Verbose]: API full response: {
  // other data removed for brevity
  "alerts": [
    {
      "sender_name": "NWS Grand Junction CO",
      "event": "High Wind Warning",
      "start": 1709391600,
      "end": 1709424000,
      "description": "
        * WHAT...Southwest winds 30 to 40 mph with gusts up to 65 mph
        expected.

        * WHERE...Eastern Uinta Basin.
        * WHEN...From 8 AM this morning to 11 PM MST this evening.
        
        * IMPACTS...Damaging winds may blow down trees and power lines.
        Power outages are possible. Travel will be difficult,
        especially for high profile vehicles.",
      "tags": ["Wind"]
    }
  ]
}
```

Having an option to display this data would be really helpful, perhaps indicating an alert using a symbol in the panel like ⚠️ with full details in the popup.

**Comment by Gr3q** [comment]
I wanted to integrate warnings for a while now. When I will have time, I don't know. I will write down the design for it.

## Design

### Indicator

* Warning indicator should appear left of "As of HH:MM" text if there are any warnings. It should use the icon equivalent of most severe warning out of the list.

### Content
#### Version 1

Indicator show a tooltip on hover with all the warnings as an itemised list ordered by severity

##### Advantages
* Popup menu will not close on interaction
##### Disadvantages
* Too long text might cause problems

#### Version 2

Indicator is a button and opens a window on clicking. The window contains all the warnings as an itemised list ordered by severity

##### Advantages
* Content can easily fit
##### Disadvantages
* Will close the popup menu (I think)
