### ISSUE TITLE
Applet Bug: Radio3.0@claudiux

### ISSUE THREAD

**Issue by etuh** [linuxmint/cinnamon-spices-applets#5571]
### Applet version/Build date

Version 1.17.5 (2024-03-06 20:46:45)

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Intel Corporation Iris Plus Graphics G1

### Applet name and maintainer

Radio3.0@claudiux @claudiux

### What happened?

Displays xml code instead of song name for some stations as follows : 

`<?xml version="1.0" encoding="utf-8"?> <ZettaLite Version="0.0.0"> <LogEventCollection><LogEvent Type="SONG" ScheduledTime="2024-03-08T08:44:51Z" StartTime="2024-03-08T08:44:51Z" StartTimeLocal="2024 & 03 & 08 11:44:51" Chain="SEGUE" Status="CURRENT" Duration="00:00" LastStarted="true" ZettaId="5175599"><Asset Type="SONG" AssetTypeName="Song" Title="CARNIVAL" ZettaId="75710" File="\\HOMEOA\RCSZetta\HOMEOAMEDIASTORE\88\88971~CARNIVALClean.mp3" TotalLength="265.6664" Artist1="KANYE WEST &amp; TY DOLLA SIGN FT. RICH THE KID AND PLAYBOI CARTI" Category="ROW" Intro1="38.0595" TrimIn="12.9502" Segue="259.3345" TrimOut="259.4972" & >< & LogEvent><LogEvent Type="LINK" ScheduledTime="2024-03-08T08:48:57Z" StartTime="2024-03-08T08:48:57Z" StartTimeLocal="2024 & 03 & 08 11:48:57" Chain="SEGUE" Status="READY" Duration="00:00" ZettaId="5175600"><Asset Type="LINK" AssetTypeName="Link" Title="Record Of The Week (OUTRO)_HBR" ZettaId="57464" File="\\HOMEOA\RCSZetta\HOMEOAMEDIASTORE\63\63494~Record Of The Week (OUTRO)_HBR.mp3" TotalLength="5.8656" Category="ZL" TrimIn="0.0599" Segue="5.337" TrimOut="5.5474" & >< & LogEvent><LogEvent Type="LINK" ScheduledTime="2024-03-08T08:49:02Z" StartTime="2024-03-08T08:49:02Z" StartTimeLocal="2024 & 03 & 08 11:49:02" Chain="SEGUE" Status="READY" Duration="00:00" EditCode="USER_MOVE" ZettaId="5175593"><Asset Type="LINK" AssetTypeName="Link" Title="1035 Homeboyzradio Long Sweeper (The Best Ever)" ZettaId="18670" File="\\HOMEOA\RCSZetta\HOMEOAMEDIASTORE\19\19569~1035 Homeboyzradio Long Sweeper (The Best Ever).mp3" TotalLength="11.3774" Category="SLS" Segue="11.2589" & >< & LogEvent>< & LogEventCollection> < & ZettaLite>`

**Comment by etuh** [comment]
![screenshot crop](https://github.com/linuxmint/cinnamon-spices-applets/assets/58567262/9d479f00-9914-481e-8ec7-7eeb48ecb1fc)

**Comment by claudiux** [comment]
@etuh 
This is the first time I've seen this kind of message. Thank you for reporting this problem.

Which stations, please? (Which streaming URLs?)

**Comment by claudiux** [comment]
@etuh 
Found homeboyz radio! Effectively it send unusual xml messages. I will study the problem.
