### ISSUE TITLE
[sound150@claudiux] Icon near the volume slider does not show

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#5576]
### Applet version/Build date

Version 6.3.0 (2024-03-08 20:25:01)

### Cinnamon version

Cinnamon 6.0.4

### Distribution

Linux Mint 21.3 Cinnamon

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

The icon beside the volume slider does not show the loudspeaker (or has the loudspeaker in the same colour as the background):
![Screenshot from 2024-03-08](https://github.com/linuxmint/cinnamon-spices-applets/assets/4856462/6865028b-2eb5-4999-8531-28195337525b)

The standard sound applet shows the icon.

BTW the icon beside the volume slider also shows the microphone off badge, even if the microphone is not muted. This badge is not necessary here at all, because the microphone volume slider is just below …

**Comment by claudiux** [comment]
This is normal. The microphone (crossed-out) only appears as a badge on the output volume icon when the microphone is muted, which is not the case here.

**Comment by sphh** [comment]
Sorry, I do not understand you: It is normal, that the loudspeaker symbol cannot be seen near the volume slider?

**Comment by sphh** [comment]
> If you want to always see the microphone status, I must create new icons. Then, this is not an issue, but a feature request.

No, I do think, that the icon beside the volume slider should not show any microphone status at all.

**Comment by claudiux** [comment]
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/33965039/06dc4815-a2ad-4949-9669-e5b9834444e0)
This is normal with mic not muted.

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/33965039/b3934949-4b85-47ac-98ef-9b09917ffef5)
With mic and output volume muted.

**Comment by claudiux** [comment]
> 
> No, I do think, that the icon beside the volume slider should not show any microphone status at all.

Ok. This is much easier to do.

**Comment by claudiux** [comment]
Solved. I'll make a PR soon.

**Comment by sphh** [comment]
> This is normal with mic not muted.
> 
> With mic and output volume muted.

This is what I expect. But if you had a look at my screenshot, there is only the microphone status badge but no loudspeaker symbol!

**Comment by sphh** [comment]
> Solved. I'll make a PR soon.

Thanks for removing the microphone status badge!

**Comment by claudiux** [comment]
Done. Please wait for the update.

**Comment by sphh** [comment]
Updated to Version 6.3.0 (2024-03-08 22:36:01), still the icon with the loudspeaker does not show:
![Screenshot from 2024-03-08 22-54-29](https://github.com/linuxmint/cinnamon-spices-applets/assets/4856462/e68f955e-21d6-4915-8805-104c0ca7d78c)

**Comment by claudiux** [comment]
What theme are you using?

**Comment by sphh** [comment]
Application: Mint-Y-Orange
Icons: Mint-Y-Sand
Desktop: Mint-L-Orange

The default sound applet shows that icon correctly, if that is any help.

**Comment by claudiux** [comment]
Yes, I can see that. These icons are not well suited to the Mint-L themes.
The icon is here, but is only displayed by hovering over it with the mouse.

**Comment by claudiux** [comment]
In short, I still have a lot of work to do on this.

**Comment by claudiux** [comment]
Solved! Now the icon still appears. I'm making a new PR. But I'll rework my icons... later.

**Comment by claudiux** [comment]
@sphh 
Done. Can you please try the version 6.3.1 of this applet?

**Comment by sphh** [comment]
I just updated the applet to Version 6.3.1 (2024-03-09 00:41:48). I can confirm that the icon is visible now. Thanks.
