### ISSUE TITLE
[sound150@claudiux] Unmute does not work from main menu's loudspeaker/microphone icon

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#5579]
### Applet version/Build date

Version 6.3.1 (2024-03-09 00:41:48)

### Cinnamon version

6.0.4

### Distribution

Linux Mint 21.3 Cinnamon

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Please see https://github.com/linuxmint/cinnamon/issues/12114. The same behaviour can be observed in the sound150@claudiux applet.

In addition also the microphone icon shows the very same behaviour: It is not possible to unmute the microphone from the icon displayed left of the mic's volume slider.

**Comment by claudiux** [comment]
@sphh Effectively. I'll see what I can do about that.

**Comment by claudiux** [comment]
I've solved this problem. I'm doing some tests before making a PR.

**Comment by claudiux** [comment]
PR made. That works as you want.

Just another bug to solve: changing the volume with the slider causes the microphone badge on the applet icon to be lost.

**Comment by claudiux** [comment]
@sphh Done!

**Comment by sphh** [comment]
> I got it. It's not the icon that allows you to mute, but the fact that you click to the left of the slider, which sets its value to zero (thus muting it).

Wow, good detective work!

> Just another bug to solve before merging: changing the volume with the slider causes the microphone badge on the applet icon to be lost.

I thought, I saw that also before the update, but was not sure …

Thanks for all your work. :bow:

Strangely after updating the applet to the latest version, the icon stopped showing as described in #5576.

**Comment by claudiux** [comment]
@sphh 
Thank you for helping me to improve the sound150 applet!

>
> Strangely after updating the applet to the latest version, the icon stopped showing as described in https://github.com/linuxmint/cinnamon-spices-applets/issues/5576.

Definitely solved in v6.3.3. Sorry for the inconvenience.

**Comment by sphh** [comment]
> @sphh Thank you for helping me to improve the sound150 applet!

No problem. It is also in my interest. :wink:

> Definitely solved in v6.3.3. Sorry for the inconvenience.

I can confirm, that the icons show again. Thanks.

Just out of interest: I am only wondering, why you have replaced the default icons with your own version. Has this become necessary for all those changes to work?

**Comment by claudiux** [comment]
>  Has this become necessary for all those changes to work?

For the time being, yes.
