### ISSUE TITLE
Feature Request: Sensors@claudiux

### ISSUE THREAD

**Issue by dhdurgee** [linuxmint/cinnamon-spices-applets#5606]
### Applet name and maintainer

Sensors@claudiux @claudiux

### What would you like to see?

I would like to have an option for critical high temperature events to be written to the systemd journal log.

My laptop occasionally hits critical high temperatures for short periods.  I also have unexplained shutdowns of this laptop, so I am wondering if it is thermal protection kicking in.  Logging critical high temperatures would assist in debugging this.

I have had to replace the CPU fan in this laptop twice, so it might be going again.

**Comment by claudiux** [comment]
Write into the systemd journal log needs root rights.

But I can record these critical high temperature events in another file, if you like.

**Comment by dhdurgee** [comment]
I just tested this and you can write to the systemd journal log as follows:

cat testing | systemd-cat

This does work and the entry appeared as:

Apr 19 17:20:48 z560 cat[47130]: testing

There are additional options I didn't try to figure out, but this worked for me.

**Comment by claudiux** [comment]
Ok. I've RTFM. I plan to add options to log High and Critical values from each type of sensor.
Examples:

`systemd-cat -t sensors -p warning echo "Temperature: ISA adapter coretemp-isa-0000: Package id 0 reached 73°C"`

`systemd-cat -t sensors -p crit echo "Temperature: ISA adapter coretemp-isa-0000: Package id 0 reached 85°C"`

**Comment by claudiux** [comment]
To avoid flooding the journal, I plan not to send the same message several times.

**Comment by dhdurgee** [comment]
Agreed, you don't want to flood it.  Would it make sense to have one message upon entering the critical or warning range and then one when it drops below that range?  That would define the duration of the event, but if there is rapid fluctuation might also generate too many messages.

**Comment by claudiux** [comment]
@dhdurgee 
When the temperature exceeds or equals the High limit, a warning message is sent with the value.
If the value remains unchanged, no message is sent.
When the value changes but remains greater than or equal to the High limit, a new warning message is sent with the new value.

Same as for the Critical limit, but with critical messages.

When the value falls below one of the limits, a message is sent to indicate this.

What do you think about it?

**Comment by dhdurgee** [comment]
Sounds good to me.  That should even allow charting the values over time for the event if desired.

**Comment by claudiux** [comment]
I've started writing the code; it doesn't seem to work too badly. I still have a few adjustments to make before publishing it.

**Comment by claudiux** [comment]
@dhdurgee Done. I hope you'll find it to your liking.
