### ISSUE TITLE
sound150@claudiux icon stays a musical note even after music & app are closed.

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#5622]
### Applet version/Build date

Version 6.5.4 (2024-03-21 19:23:57)

### Cinnamon version

Cinnamon 6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Intel UHD Graphics 620 

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Played music from youtube video in Firefox.    Icon changed to musical note during play.
Closed firefox.   The sound icon in panel will not change back to speaker.
At least I think it should.

**Comment by ChooChooAl** [comment]
**killall playerctld**  does resets the icon.

**Comment by claudiux** [comment]
Solved!

**Comment by ChooChooAl** [comment]
Yes it does.  Thanks.

**Comment by claudiux** [comment]
@ChooChooAl Thanks for using this applet and reporting any problems you encounter!
