### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: eth0 errors when USB-C hub is attached

### ISSUE THREAD

**Issue by timur-g** [linuxmint/cinnamon-spices-applets#5630]
### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

AMD integrated

### Applet name and maintainer

multicore-sys-monitor@ccadeptic23 @claudiux

### What happened?

When this applet is loaded on startup and I attach USB-C hub with address enY, I get a permanent flood in .xsession-errors :
[WARNING] Failed to open "/sys/class/net/eth0/statistics/tx_bytes": No such file or directory
In applet, I monitor only other built-in Ethernet port enX. 

Seems not when I first attach hub and then start applet. Then it shows enY in Devices, which I did not notice before.

**Comment by claudiux** [comment]
@timur-g 
What happens when you right-click on this applet and select “Refresh graphics”?

**Comment by claudiux** [comment]
Thank you. I'm in the process of finding a solution to this bug.

**Comment by claudiux** [comment]
@timur-g 
Please try #6563.

**Comment by timur-g** [comment]
Thanks, Seems OK, it was reloaded on USB-C plug in and out.

**Comment by claudiux** [comment]
Fine! The new version is here now.
