### ISSUE TITLE
[search-box@mtwebster] Feature Request: Shortcuts & Multiple Search Providers

### ISSUE THREAD

**Issue by trymeouteh** [linuxmint/cinnamon-spices-applets#5666]
### Applet name and maintainer

search-box@mtwebster

### What would you like to see?

In modern browsers such as Chrome and Firefox, you can set a shortcut in the browser address bar to use a certain search engine. For example you can use "ddg linux mint iso" to search for "linux mint iso" on DuckDuckGo.

Consider having a search provider that will be named "Browser Address Bar" or something like it which will instead copy the prompt into the default browser search bar.

**Comment by claudiux** [comment]
Ping @mtwebster

**Comment by rcalixte** [comment]
Just a note that this applet is currently unmaintained. If anyone wants to try to complete this feature request or even take over as maintainer, feel free to open a pull request for either.

**Comment by claudiux** [comment]
@trymeouteh I've just completed the modifications you requested. I'll do a PR soon.

**Comment by claudiux** [comment]
Done. I advise you to wait a dozen hours before updating.

**Comment by claudiux** [comment]
Right-click on this applet to select your provider, as shown in the tooltip.
