### ISSUE TITLE
[directory-menu@torchipeppo] Feature Request

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon-spices-applets#5672]
### Applet name and maintainer

directory-menu@torchipeppo @torchipeppo

### What would you like to see?

Please add options:

1. to display favorite folders and files first.
2. to display pinned folders and files first.

Great applet! Thank you.

**Comment by torchipeppo** [comment]
Very reasonable request, though I don't think I'll be able to get it done in the near future.

I'll also have to check whether there is some sort of API to retrieve favorite/pinned items.

Thank you for the input!

**Comment by claudiux** [comment]
```
const XApp = imports.gi.XApp;
...
this.favorites = XApp.Favorites.get_default();

```
etc
Search about `XAppFavorites` in devhelp.

**Comment by claudiux** [comment]
To know pinned folders/files:
`gio info /path/to/file_or_folder -a metadata::pinned-to-top`

**Comment by claudiux** [comment]
To know pinned folders/files in javascript:

```
const Gio = imports.gi.Gio;
...
let file = Gio.file_new_for_path(here_the_path_to_file_or_folder);
if (file.query_exists(null)) {
    let fileIsPinned = jsonFile.query_info("metadata::pinned-to-top", 
                                           Gio.FileQueryInfoFlags.NONE, 
                                           null).get_attribute_as_string("metadata::pinned-to-top") == "true";
   global.log("fileIsPinned: "+fileIsPinned);
}

```

**Comment by igorsantos07** [comment]
Any chance we could also change the default sorting to be last changed instead of alpha?

**Comment by torchipeppo** [comment]
The request is noted. Adding an option in the configuration menu to switch between lexicographic order and last-changed should be feasible, though I'd probably keep lexicographic as the default setting and add last-changed as optional.

Note that I still don't know when I'll be able to get back to this myself.

Thanks for the suggestion! :)
