### ISSUE TITLE
Media player list should be expanded as standard

### ISSUE THREAD

**Issue by Dan-cer** [linuxmint/cinnamon-spices-applets#5678]
### Applet name and maintainer

sound150@claudiux @claudiux

### What would you like to see?

I just installed your applet and it is working much better than the inbuilt sound applet. Thank you very much!
In both applets the list of active media players (forground or background sources) is kollapsed in main view.
So each time I want to change the source I first have to expand it to find the desired player.
I added 2 screenshots combined in 1 image:
![sound150](https://github.com/linuxmint/cinnamon-spices-applets/assets/800638/2bed7e97-15de-4613-b4d8-c01c55701d6e)
It would be great to have the list expanded ALWAYS!
Thank you for your work, your answer and any improvement!

**Comment by claudiux** [comment]
@Dan-cer Thank you for this feature request. It could be an option. I will implement it.

**Comment by Dan-cer** [comment]
Great! I love it! Will the applet updated automatically by system?
