### ISSUE TITLE
weather@mockturtl: Unable to refresh correctly

### ISSUE THREAD

**Issue by autumnlansing** [linuxmint/cinnamon-spices-applets#5680]
### Applet version/Build date

3.4.1

### Cinnamon version

5.8.4

### Distribution

Fedora 38

### Graphics hardware *and* driver used

NVIDIA GeForce GTX 660

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

The weather applet stopped updating yesterday. I checked for a new version and installed it today. The app now seems to be stuck refreshing. The log shows the message: "Refreshing in progress, refresh skipped." When I try to save a manual location, it tells me it can't while the app is refreshing.

I've restarted Cinnamon, deleted the app and reinstalled it, and the issue still happens. 

### Other information

Gjs-Message: 10:01:04.518: JS LOG: [LookingGlass/info] [weather@mockturtl#26:Info]: Internet access "FULL (4)" now available, resuming operations.
Gjs-Message: 10:01:21.659: JS LOG: [LookingGlass/info] [weather@mockturtl#26:Info]: Refreshing in progress, refresh skipped.
Gjs-Message: 10:30:08.140: JS LOG: [LookingGlass/info] [weather@mockturtl#26:Info]: Refreshing in progress, refresh skipped.
Gjs-Message: 11:27:05.801: JS LOG: [LookingGlass/info] [weather@mockturtl#26:Info]: Refreshing in progress, refresh skipped.

**Comment by Gr3q** [comment]
Can you reproduce when you manually disconnect/reconnect from the internet this happens? Switch to 5min refresh cycle to test this.

I'm afraid the answer is going to be yes, but please check to be sure
