### ISSUE TITLE
[SpicesUpdate@claudiux] Include `Actions`

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#5683]
### Applet name and maintainer

SpicesUpdate@claudiux @claudiux

### What would you like to see?

Thanks for updating the spice!

Do you think, you could also include the new `Actions` spices category?

**Comment by claudiux** [comment]
I'm working on that.

**Comment by claudiux** [comment]
Done!

**Comment by sphh** [comment]
Thanks!
