### ISSUE TITLE
Add "next track" and "previous track" to Shortcuts settings tab

### ISSUE THREAD

**Issue by Dan-cer** [linuxmint/cinnamon-spices-applets#5721]
### Applet name and maintainer

sound150@claudiux @claudiux

### What would you like to see?

Hi claudiux, I think it's great that the button assignment setting within the applet settings ensures that they ALWAYS work. That's why it would be an advantage to also include the key assignment for "next track" and "previous track" in the applet settings.

Because in Linux Mint these keys often don't work for me, even though I have defined them in the Mint settings. The Mint settings were and are very often gotten inactive as soon as more than one media source is in play. I have known this for years.
As I learned that the applet shortcut settings give stability. I like to have this stability for the next and previous shortcuts too.
Thank you!

**Comment by claudiux** [comment]
Done! I'll make a PR soon.

**Comment by Dan-cer** [comment]
Great! I appreciate it very much!
