### ISSUE TITLE
 Keep open Select playback control

### ISSUE THREAD

**Issue by Dan-cer** [linuxmint/cinnamon-spices-applets#5767]
### Applet name and maintainer

sound150@claudiux @claudiux

### What would you like to see?

At the moment we have in Menu settings "Keep the player list open". I seems that it is meant for both sections, also for "Select playback control".
I prefer to have 2 options: 
1 for the upper section (player list with icons), and 1 for the second: "Select playback control" to keep open.
As I only use one player together with the applet I don't need the player list really, at least not open. But the section for selecting playback control always has to be open for me (to minimize clicks to change source).
Could you enlarge the settings menu for a second option? I would appreciate it very much!
Thank you for your work!

![applet](https://github.com/linuxmint/cinnamon-spices-applets/assets/800638/e2cd6e25-6053-4ca7-bc7a-e70d1f784523)

**Comment by claudiux** [comment]
Done in version 6.9.1.

**Comment by Dan-cer** [comment]
Great! Fine job!
