### ISSUE TITLE
Order scripts in Script Menu Applet

### ISSUE THREAD

**Issue by acsdev** [linuxmint/cinnamon-spices-applets#589]
First I would like to say that I use with applets all the time. for me it is a wonderfull idea.

I would like to know if is possible to configure how de script applet can order the scripts? I think the order always changes in random way. If is not possible right now, could you add this feature?

**Comment by NikoKrause** [comment]
This applet has currently no author. Maybe another dev will come along and reads this.

**Comment by acsdev** [comment]
I have edit the script on github to user order by I do not knowledge about make applets on mint. Do you know how release a version?

**Comment by NikoKrause** [comment]
This commit https://github.com/linuxmint/cinnamon-spices-applets/pull/600 fixes your feature request, right?

**Comment by acsdev** [comment]
Perfectly,
Thanks.
