### ISSUE TITLE
multicore-sys-monitor@ccadeptic23 : An option to only display tooltips without the graphs? 

### ISSUE THREAD

**Issue by heavenlyhexidecimal** [linuxmint/cinnamon-spices-applets#5931]
### Applet name and maintainer

multicore-sys-monitor@ccadeptic23 @claudiux 

### What would you like to see?

First of all thank you for developing this app. Its simple without being overly complicated like some others. This is my first time registering on github so that I can make this request.
Is it possible to have an option in the app to disable the displaying of graphs and only display a tooltip when hovering over the app icon?

**Comment by claudiux** [comment]
I'll see what I can do about that.

**Comment by claudiux** [comment]
Solved! Install the version 1.9.5, then right-click on this applet to choose 'Without any graphics'.

**Comment by heavenlyhexidecimal** [comment]
Just like the "sensor monitor" app, it can display only the tooltip with only a hover over the icon app on the panel.  If its not too much trouble and only if you have the time.  For now I reduced the width and color of the graphs so its not distracting for me.  I also use spices app which is such a useful app to keep everything updated. Thank you!

**Comment by heavenlyhexidecimal** [comment]
> Solved! Install the version 1.9.5, then right-click on this applet to choose 'Without any graphics'.

Wow, I was just replying back to you.  Thank you again!
