### ISSUE TITLE
After updating applets CPU usage rises and laggy/stuttering graphic

### ISSUE THREAD

**Issue by Machion** [linuxmint/cinnamon-spices-applets#5941]
### Cinnamon version

6.0.4

### Distribution

Arch/Manjaro

### Applet name and maintainer

SpicesUpdate@claudiux @claudiux

### What happened?

I have 4 applets installed: Temperature, darkMode, QRedshift and SpicesUpdate. 

In the last days there where many updates for SpicesUpdate and minor updates for the others. 

Since some days every time I updated SpicesUpdate (and I think Temperature), I noticed laggy/stuttering behaviour for example scrolling in windows (Firefox) or moving windows around on the desktop. SystemMonitor showed me a 30% CPU usage, but no real culprit process. Logging out/in again or restarting the PC solved this strange behaviour. 
I don't know, if it has something to do with the applet(s) itself or the update process/Cinnamon.

**Comment by claudiux** [comment]
I'm working on SpicesUpdate to make it more smoothly.
I recommend replacing Temperature with Sensors@claudiux: https://cinnamon-spices.linuxmint.com/applets/view/337
