### ISSUE TITLE
sound150@claudiux: OSD is lagging behind if changing the sound volume sound is enabled

### ISSUE THREAD

**Issue by mehdi-abdelkhalek** [linuxmint/cinnamon-spices-applets#5967]
### Applet version/Build date

6.10.0

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

AMD ATI with open source drivers

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

When "Changing the sound volume" is enabled in sound settings (the sound you hear while changing volume) the OSD doesn't update properly (only update after the sound finishes playing maybe?)

**Comment by claudiux** [comment]
@mehdi-abdelkhalek Thank you for reporting this issue (I've disabled the “sound that changes the volume of the sound” which is very unpleasant). I'll see what I can do about it.

**Comment by claudiux** [comment]
@mehdi-abdelkhalek 
This issue doesn't depend on the sound150@claudiux applet, but seems to depend on the Cinnamon's osdWindowManager.

**Comment by mehdi-abdelkhalek** [comment]
That's strange, it doesn't happen with the default sound applet.

**Comment by claudiux** [comment]
Ok, I'll try to do some more research.

**Comment by mehdi-abdelkhalek** [comment]
Hi,

after today's update the issue still persists (tried enabling the sound from both Cinnamon's settings and the applets configuration)

I have disabled the sound on my end (I don't really need it but thought it may be confusing and repel new users)

**Comment by claudiux** [comment]
@mehdi-abdelkhalek 
The lag has become less noticeable, although still not perfect.
The sound@cinnamon.org applet does not itself manage the OSD, unlike sound150@claudiux. But to be able to offer users a step different from 5%, I had to redefine quite a few initial behaviors; keyboard shortcuts and the OSD are among them.

When I'm listening to music or a program, or watching a video, I want to be able to change the sound volume without it being polluted by system sounds. I therefore systematically deactivate the sound associated with volume modification.

**Comment by mehdi-abdelkhalek** [comment]
Upon further inspection, this issue isn't related to the OSD.

Any enabled sound will cause the desktop to lag. This especially noticeable when switching workspace or changing volume (when their respective sound effect is enabled) but also happens with any of the other sounds (a slight delay for the notification to appear for example).

Removing the applet from panel makes the lag disappear, so I'm pretty sure it's caused by Sound 150% applet.

For now, I have disabled all cinnamon's sounds (except logout).

If you can reproduce this issue, please reopen and maybe mention it in README.md so it doesn't confuse users.

**Comment by claudiux** [comment]
I can't reproduce this problem, but I've made a change:

Edit script `~/.local/share/cinnamon/applets/sound150@claudiux/5.4/applet.js`; search for and replace "Cinnamon Volume Control" with "Sound150 Volume Control". Save it, then reboot your computer (to make sure it forgets the old configuration).

**Comment by claudiux** [comment]
After that, you should get:
```
$ pactl list clients | grep "application.name"
		application.name = "WirePlumber"
		application.name = "WirePlumber [export]"
		application.name = "pipewire"
		application.name = "Cinnamon Volume Control Media Keys"
		application.name = "Sound150 Volume Control"
		application.name = "Muffin"
		application.name = "Radio Volume Control"
		application.name = "mpv"
		application.name = "xdg-desktop-portal"
		application.name = "speech-dispatcher-dummy"
		application.name = "pactl"
```

**Comment by claudiux** [comment]
Oh, I'm using Pipewire instead of Pulseaudio. PipeWire handles the mixing of different sources and their distribution to various outputs. PipeWire also seems to produce better sound quality (IMHO).
