### ISSUE TITLE
SpicesUpdate@claudiux: Applet Bug

### ISSUE THREAD

**Issue by kyphi** [linuxmint/cinnamon-spices-applets#5969]
### Applet version/Build date

7.4.0

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

NVIDIA Corporation GF106 [GeForce GTS 450] - 390.157

### Applet name and maintainer

SpicesUpdate@claudiux @claudiux

### What happened?

When resuming from system suspend, desktop appears briefly then goes black and then returns to display desktop.  Mousing over icons in the panel makes them disappear.
The "Alt+F2 - r" sequence restarts Cinnamon and full functions.
I suspect that the Spices Updater comes into operation at the same time as the Cinnamon Updater and creates a conflict.  Perhaps a 10 - 20 seconds starting delay incorporated into the Spices Updater would fix this.

**Comment by claudiux** [comment]
@kyphi Thanks for reporting this issue. I'm going to run some tests.

**Comment by claudiux** [comment]
Done. Now waits 20 seconds before executing the cache update loop, so that mintupdate runs correctly.

**Comment by kyphi** [comment]
Thank you Claudiux.
Regards,
Kyphi

**Comment by claudiux** [comment]
Definitely fixed with v7.4.4.
