### ISSUE TITLE
Radio3.0 No sound

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-applets#5987]
### Applet version/Build date

2.0.2

### Cinnamon version

6.0.4

### Distribution

Arch 6.6.9

### Graphics hardware *and* driver used

AMD Radeon HD 5430

### Applet name and maintainer

Radio3.0@claudiux @claudiux

### What happened?

After Radio3.0 working properly using _pulseaudio,_ had some issues with the system and, after fixing, lost the sound in the Radio3.0 applet. Media players have sound and no other apparent sound issues.
Reinstalled _pulseaudio_ and Radio3.0, no change except that the sound volume % next to the panel icon remains at 100% and does not respond to volume changes,
Installed Sound 150% applet and the selected radio station showed in the tool tip, but still no sound. Uninstalled Sound 150% applet.

### Other information
Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Cedar HDMI Audio [Radeon HD 5400]

**Comment by claudiux** [comment]
@Padre2 
What returns the command `pactl info`?

**Comment by Padre2** [comment]
@claudiux 
zsh 1031 % pactl info
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 31
Tile Size: 65472
User Name: victor
Host Name: phenom
Server Name: pulseaudio
Server Version: 17.0
Default Sample Specification: s16le 2ch 44100Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_14.2.analog-stereo
Default Source: alsa_output.pci-0000_00_14.2.analog-stereo.monitor
Cookie: 4392:7013

**Comment by Padre2** [comment]
@claudiux 
My sort-time memory is getting bad. I just reread the Manual and noted the dependencies needed for Radio3.0:
    mpv
    sox
    pacmd
    libnotify-bin
    yt-dlp
    ffmpeg
    ffmpegthumbnailer
    python3-polib
    python3-brotli
I then remembered the pop-up with the download information. This pop-up did not appear when I reinstalled the applet.
Checking the above it seems that libnotify-bin python3-polib and python3-brotli are missing.
Could you please post the download instructions for all of them here so I can reinstall them.

**Comment by claudiux** [comment]
For Arch:

`sudo pacman -Syu mpv sox at libnotify youtube-dl ffmpeg ffmpegthumbnailer python-brotli`

`yay -S python-polib`

To install Yay on in Arch Linux and other Arch-based systems, run the following commands one by one:

`sudo pacman -S --needed git base-devel`

`git clone https://aur.archlinux.org/yay.git`

`cd yay`

`makepkg -si`

**Comment by claudiux** [comment]
Just tested on Arch Linux rolling. This applet works very well.

**Comment by Padre2** [comment]
Thanks for the above and _yay_ - have always used _yay_ on Arch.  I think _yt-dl_ should be _yt-dlp_.
Ran and installed everything, but no change after rebooting and reinstalling the applet, also sound still at 100%. 
I'm sure the problem is not in the applet. Mystery!

**Comment by claudiux** [comment]
Yesss! So, I close this issue. I'll update the help file. Thanks to you.

**Comment by claudiux** [comment]
Please check your output in Cinnamon sound settings.

**Comment by claudiux** [comment]
I will recreate my VM with Arch Linux to try the installation of this applet.

**Comment by claudiux** [comment]
Installing Arch Linux once is a great way to learn a lot.
Installing Arch Linux twice drives you crazy.

**Comment by claudiux** [comment]
@Padre2 You don't need to install `pulseaudio`, but `pipewire-pulse`.

**Comment by claudiux** [comment]
When pipewire-pulse is installed, right-click on this applet and select "Do not check dependencies". Reboot Cinnamon.

**Comment by Padre2** [comment]
Thanks for the above and _yay_ - have always used _yay_ on Arch.  I think _yt-dl_ should be _yt-dlp_.
Ran and installed everything, but no change after rebooting and reinstalling the applet, also sound still at 100%. 
I'm sure the problem is not in the applet. Mystery!

**Comment by Padre2** [comment]
@claudiux
Many thanks for your continued support with the issue.
Since we are sometimes digressing from the issue, is there any way I can reach you by email to discuss Arch issues?
Regarding the use of pipewire, I had previously considered this, but since I had no problems with pulseaudio, I did not try it and had read that there were conflicts between them, with people losing their sound altogether.
I installed pipewire and was asked to remove pulseaudio.  After that I rebooted and received a message from the applet: 
“Spices Update message: Some packages needed!
To complete the installation, please enter and execute the command:
sudo pacman -Syu && sudo pacman -S pulseaudio".
Although I checked before doing this, there was still no sound in the applet. So I am now back to square 1.
I have done a lot of searching, but found nothing that has fixed the issue.
I do have a question regarding the settings in the Pulse Audio Volume Control.  In the Configuration tab (see image), The Cedar HDMI Audio shows Profile:  Off.  Shouldn’t this be On?  N.B.  My sound is working normally in media players and notification sounds.,
I have searched many postings about this but haven’t yet found an answer.
![Screenshot from 2024-05-08 15-30-12](https://github.com/linuxmint/cinnamon-spices-applets/assets/38849451/bd29653e-404a-4df3-8b4e-5a755a33ea23)

**Comment by claudiux** [comment]
https://bbs.archlinux.org/viewtopic.php?id=282261

**Comment by Padre2** [comment]
@claudiux 
Thank you for the link. Yes I had read that one and it is possible that it is a kernel issue. I have never downgraded the kernel and would try it as a last resort. Perhaps I will try a new Arch installation on another drive and see if I can reproduce the problem.

**Comment by Padre2** [comment]
I made an Arch installation (same kernel) on another drive including the Cinnamon DE, pulseaudio and pavucontrol. I noted that the Volume Control displayed identically with the HDMI Audio showing Profile: Off, so I think that this is not the problem. I installed Radio3.0 and had the same no-sound issue. I then installed Radio++ and to my surprise it had sound. Returning to my old installation, I reinstalled Radio++ and it worked there too. This may give you some insight into why Radio3.0 does not have sound. Perhaps if time tomorrow I can try downgrading the kernel in the new installation to see if this solves the issue.

**Comment by Padre2** [comment]
It's late here, but I checked and _mpv-mpris_ is installed. I uninstalled and reinstalled Radio3.0, but still no sound. I will check more tomorrow.

**Comment by Padre2** [comment]
Have been checking packages that have a sound connection and found that clicking it in the menu opens it. I use _vlc_ so am not familiar with _mpv_. I see to use it you just drop a music or video file. If i do this it just closes _mpv._ 
I ran:
`zsh 1005 % mpv -v --audio-device=help                            
[cplayer] Command line options: '-v' '--audio-device=help'
[cplayer] mpv v0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Apr 18 2024 06:31:17
[cplayer] libplacebo version: v6.338.2
[cplayer] FFmpeg version: n6.1.1
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       58.29.100
[cplayer]    libavcodec      60.31.102
[cplayer]    libavformat     60.16.100
[cplayer]    libswscale      7.5.100
[cplayer]    libavfilter     9.12.100
[cplayer]    libswresample   4.12.100
[cplayer] Configuration: -Db_pie=true -Dpython.bytecompile=1 -Dlibmpv=true -Dgl-x11=enabled -Dcaca=disabled -Dcdda=enabled -Ddvbin=enabled -Ddvdnav=enabled -Dlibarchive=enabled -Dopenal=enabled -Dprefix=/usr -Dlibexecdir=lib -Dsbindir=bin -Dauto_features=auto -Dbuildtype=plain -Dwrap_mode=nodownload
[cplayer] List of enabled features: alsa av-channel-layout avif-muxer build-date cdda cplugins cuda-hwaccel cuda-interop dmabuf-interop-gl dmabuf-wayland drm dvbin dvdnav egl egl-drm egl-wayland egl-x11 ffmpeg ffnvcodec gbm gl gl-x11 glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg jpegxl lavu-uuid lcms2 libarchive libass libavdevice libbluray libdl libplacebo linux-fstatfs luajit memfd-create openal pipewire posix posix-shm ppoll pthread-condattr-setclock pulse rubberband rubberband-3 sixel uchardet vaapi vaapi-drm vaapi-wayland vaapi-x11 vapoursynth vdpau vdpau-gl-x11 vector vk-khr-display vt.h vulkan vulkan-interop wayland wayland-protocols-1-27 wayland-protocols-1-31 wayland-protocols-1-32 x11 xv zimg zimg-st428 zlib
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[ifo_dvdnav] Opening /etc/mpv/encoding-profiles.conf
[bdmv/bluray] Opening /etc/mpv/encoding-profiles.conf
[file] Opening /etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Setting option 'audio-device' = 'help' (flags = 8)
[ao/pipewire] Headers version: 1.0.5
[ao/pipewire] Library version: 1.0.5
[1]    23930 segmentation fault (core dumped)  mpv -v --audio-device=help`
Searching _segmentation fault (core dumped)_ found one caused by _mesa_ that was fixed by downgrade, but my attempt to try this was stopped by dependency conflict(s). Any suggestions?

**Comment by claudiux** [comment]
Also on my system both pulseaudio and pipewire are installed, but pulseaudio is provided by pipewire-pulse.
The command `pactl info` returns:
```
...
Server Name: PulseAudio (on PipeWire 0.3.48)
...
```

Please try this command:
```
/usr/bin/mpv --no-resume-playback --no-stop-screensaver --script=/home/$USER/.local/share/cinnamon/applets/Radio3.0@claudiux/scripts/mpvWatchTitle.lua --no-video --metadata-codepage=auto --input-ipc-server=/run/user/1000/mpvradiosocket --cache=yes --stream-buffer-size=1MiB --cache-on-disk=no https://i4.streams.ovh:8352/stream
```
On my computer, I hear this radio station and the output is like:
```
 (+) Audio --aid=1 (mp3 2ch 44100Hz)
File tags:
 icy-title: Matt Thorpe - New Blues
AO: [pulse] 44100Hz stereo 2ch float
A: 00:00:46 / 00:00:57 (82%) Cache: 10s/443KB
```
Stop with Ctrl+C. Don't care about error messages after Ctrl+C.

**Comment by Padre2** [comment]
pactl info
[/home/victor/.config/pulse/client.conf:1] Unknown lvalue 'ao' in section 'n/a'.
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 8
Tile Size: 65472
User Name: victor
Host Name: phenom
Server Name: pulseaudio
Server Version: 17.0
Default Sample Specification: s16le 2ch 44100Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_14.2.analog-stereo
Default Source: alsa_output.pci-0000_00_14.2.analog-stereo.monitor
Cookie: c573:3a3f

**Comment by Padre2** [comment]
/usr/bin/mpv --no-resume-playback --no-stop-screensaver --script=/home/$USER/.local/share/cinnamon/applets/Radio3.0@claudiux/scripts/mpvWatchTitle.lua --no-video --metadata-codepage=auto --input-ipc-server=/run/user/1000/mpvradiosocket --cache=yes --stream-buffer-size=1MiB --cache-on-disk=no https://i4.streams.ovh:8352/stream

 (+) Audio --aid=1 (mp3 2ch 44100Hz)
File tags:
 icy-title: BluesRadio - BluesRadio,Play Blues24-7
[1]    3758 segmentation fault (core dumped)  /usr/bin/mpv --no-resume-playback --no-stop-screensaver  --no-video

I not the segmentation fault..
Also on my new separate fresh install the applet plays well, except is has the same frozen 100% volume next to the icon.

**Comment by Padre2** [comment]
Eureka, I fixed it. I downgraded _mesa_ from version 24 to 23 by deleting a conflicting file.  On rebooting my DE had no bottom panel, or menu. I immediately ran _pacman -Syu_ and was amazed at the files that were to be installed:

Packages (14) alsa-card-profiles-1:1.0.6-1  chromium-124.0.6367.201-1
              freetds-1.4.13-1  fzf-0.52.0-1  gedit-plugins-47.1-1
              geoclue-2.7.1-3  libngtcp2-1.5.0-1  libpipewire-1:1.0.6-1
              mesa-1:24.0.6-2  nss-3.100-1  pipewire-1:1.0.6-1
              pipewire-audio-1:1.0.6-1  pipewire-session-manager-1:1.0.6-1
              python-cryptography-42.0.6-1

Total Download Size:   106.62 MiB
Total Installed Size:  453.11 MiB
Net Upgrade Size:        0.95 MiB

Seeing all the related audio files looked promising. So much happens behind the scenes in Linux.
I installed with only one issue:
 8/11) Compiling GSettings XML schema files...
/usr/share/glib-2.0/schemas/org.gnome.system.wsdd.gschema.xml:4:1  Error on line 4 char 1: <enum id='org.gnome.system.gvfs.GVfsBackendNetworkDisplayMode'> not (yet) defined..  This entire file has been ignored.

All completed without any problem and I rebooted to find my desktop back to normal and the applet sound now working.
The volume by the icon is still 100% but I can turn it off.
Can I communicate with you directly via the GitHub email?

**Comment by claudiux** [comment]
We're on the move! I always keep all my packages up to date; it's much safer.

> The volume by the icon is still 100%

I don't understand why. Do you use the middle button by rolling over the icon of this applet to change the volume of the radio sound?

**Comment by Padre2** [comment]
I always run _pacman -Syu_ and _yay -Syu_  using aliases, when I first start Arch every morning. As you discerned earlier, some issues were probably caused by HDD errors. I had a major problem last week and had to reinstall several packages. Probably some of the issues were hidden in dependencies that may have been affected. I presume in such cases the package must be removed, which forces removal of dependencies, before reinstalling. I am hoping to clone the system to a new HDD soon - Clonezilla?
Regarding the 100% volume next to the icon and the middle buttonl, I never use it. Checking now, the button does change the value, but does not change the actual sound level.

**Comment by claudiux** [comment]
To clone a hard disk, I boot my computer onto the Linux Mint live-DVD and use GParted. If you have hard disk errors, change that hard disk quickly!

**Comment by Padre2** [comment]
I just ran _pacman -Syu_ and _yay -Syu_ on the new installation and go almost the same package updates.
I just updated Radio3.0 but using the middle button changes the % displayed, but not the actual volume.

**Comment by claudiux** [comment]
Start a radio with this applet, then right-click on the sound applet (not this applet) and open the Applications submenu. You should see a line with a cursor for Mpv. Move this slider. The volume indicated on this slider should be the same as that indicated for Radio3.0.

**Comment by claudiux** [comment]
Start a radio with this applet, then right-click on the sound applet (not this applet) and open the Applications submenu. You should see a line with a cursor for Mpv. Move this slider. The volume indicated on this slider should be the same as that indicated for Radio3.0.
![Mpv_slider](https://github.com/linuxmint/cinnamon-spices-applets/assets/33965039/3eb02a0f-ff35-4490-9e02-fe1abbf9a4c0)

**Comment by Padre2** [comment]
Yes, now the volune % is working, even after closing the sound applet.

**Comment by Padre2** [comment]
Unaware that the sound applet, which I normally don't use, can control various applications, I had a problem with the browser, which would not play any YouTubes. This could be fixed by installing pipewire-media-sessions,  which then would require the removal of pulseaudio and other packages. If implemented YouTube could be run, but no radio sound. Now I understand what was happening.

**Comment by claudiux** [comment]
Did you try my applet `sound150@claudiux`? https://cinnamon-spices.linuxmint.com/applets/view/306

**Comment by Padre2** [comment]
Yes, I have tried isound150 and it works well. I am on a desktop with amplified external speakers so non really need it, but assume it would be great for a laptop.
I seem to have got all the sound issues sorted. The  replacement of _pulseaudio_ by _pipewire-pulse_ solved the browser issue and the volume %  is working.

To clone a hard disk, I boot my computer onto the Linux Mint live-DVD and use GParted.
I do have Live Linux Mint on a USB with _gparted_, which allows me to work on the old and new drives ( using MBR). I tried to  using CloneZilla, but it stopped after finding disk errors. I ran _e2ssck -cv /dev/sda1_ and it found 6 errors with two files.  This didn't fix the errors as Clonezilla stopped again.
Should I be using _dd_ per following:
`dd if=/dev/sda1 of=/dev/sdb1 bs=64K conv=noerror,sync status=progress`
I will give it a try.

**Comment by claudiux** [comment]
Using GParted, you can try copying the partitions (one by one) from the old disk to the new one. After copying a partition, you can resize it before copying the next one.

**Comment by Padre2** [comment]
Regarding the cloning of Arch from the old drive to a new one, I created a partition of the same size on the new larger HDD and ran:
`dd if=/dev/sda1 of=/dev/sdb1 bs=64K conv=noerror,sync status=progress`
On booting, it opened with _boot rescue_. Booting again with the live Mint USB, I was able to _chroot_ into the Arch and run:
`grub-mkconfig -o /boot/grub/grub.cfg`
The new installation booted and appeared to run well, with all the applets running and even my LAMP server with PHP 7.4 - 8.3 ran my test sites without apparent issues. 
Unfortunately one issue on the old drive that I hadn't corrected was still there. My internal SSD, HDD and removable drives do not show up in Nemo, although I can see the in _GParted_. I have spent considerable time trying to fix this looking at _fstab_, _udisks2_ and many other packages and settings without success. Any ideas?

**Comment by claudiux** [comment]
Try with `gio mount ...`. See `man gio`.

**Comment by Padre2** [comment]
I took a look at _gio_, but had no success.
I am looking for what happened to stop the internal and external drives from mounting.
I ran: `mkinitcpio -p linux`
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
==> Using configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img
==> ERROR: Invalid option -g -- '/boot/initramfs-linux.img' must be writable
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'fallback'
==> Using configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-fallback.img -S autodetect
==> ERROR: Invalid option -g -- '/boot/initramfs-linux-fallback.img' must be writable`
Confused by the  _ERROR: Invalid option -g_  - where is that used?
How do I fix this error?

**Comment by claudiux** [comment]
And using sudo ?

**Comment by Padre2** [comment]
Oh dear! It was 32 C in the room (air conditioner not working) where I was and I just didn't notice I was missing _sudo_.
Sorry, good that I gave up at that point. 
Using sudo, it ran normally. Nothing else changed and still not seeing the other drives in Nemo or any drive in Gnome Disks.

**Comment by claudiux** [comment]
What does the `mount` command tell you?

**Comment by Padre2** [comment]
Ran `sudo dmesg` and got the following errors:
`systemd-fstab-generator[252]: Failed to create unit file '/run/systemd/generator/-.mount', as it already exists. Duplicate entry in '/etc/fstab'?`
`[   14.824574] systemd-fstab-generator[252]: Failed to create unit file '/run/systemd/generator/-.mount', as it already exists. Duplicate entry in '/etc/fstab' `
`[   14.825366] (sd-exec-[248]: /usr/lib/systemd/system-generators/systemd-fstab-generator failed with exit status 1.`
Did not see duplicate fstab file and commented out fstab in the etc directory restarted and ran sudo dmedg again - no errors. checking /etc/fstab, a new file, but no drives listed.`

Ran`sudo blkid`
`[sudo] password for victor: 
/dev/sdb2: LABEL="480 GB Windows 7" BLOCK_SIZE="512" UUID="168678DD8678BEB5" TYPE="ntfs" PARTUUID="61184e8a-02"`
`/dev/sdb1: LABEL="System Reserved" BLOCK_SIZE="512" UUID="346A4AFA6A4AB7FE" TYPE="ntfs" PARTUUID="61184e8a-01"`
`/dev/sda1: UUID="17336e10-7adb-4750-afed-b14596146545" BLOCK_SIZE="4096" TYPE="ext4" PTTYPE="dos" PARTUUID="3083bb4a-01"`

This is my present fstab file:
# <file system> <mount point> <type> <options> <dump> <pass>
UUID=17336e10-7adb-4750-afed-b14596146545	/	ext4    defaults,noatime	0	1
UUID=168678DD8678BEB5   /   ntfs    defaults    0   0
PARTUUID=61184e8a-02    /   ntfs    defaults    0   0

Using mount - not sure what you wanted. Ran `sudo mount /dev/sdb2 /mnt` - runs with no output in terminal no other drives in Nemo or Disks.
 Why doesn't Gnome Disks show any disks?
![Screenshot from 2024-05-20 10-07-00](https://github.com/linuxmint/cinnamon-spices-applets/assets/38849451/ce0db0c2-e70d-4a41-9183-9986a5e1710f)

**Comment by claudiux** [comment]
This is wrong!
You can't have 3 different entries for the same mount point `/`. That causes the error message "Duplicate entry in '/etc/fstab'"

```
UUID=17336e10-7adb-4750-afed-b14596146545	/	ext4    defaults,noatime	0	1
UUID=168678DD8678BEB5   /   ntfs    defaults    0   0
PARTUUID=61184e8a-02    /   ntfs    defaults    0   0
```

Change these 3 lines for:
```
UUID=17336e10-7adb-4750-afed-b14596146545	/	ext4    defaults,noatime	0	1
# UUID=168678DD8678BEB5   /   ntfs    defaults    0   0
# PARTUUID=61184e8a-02    /   ntfs    defaults    0   0
```
then reboot your computer.

**Comment by Padre2** [comment]
I had added the 2nd and 3rd UUIDs, now removed - no change.
Ran `sudo pacman -Rns gnome-disk-utilities` and then reinstalled - still not showing any drives.
