### ISSUE TITLE
[sound150@claudiux] Feature Request: Please add another hotkey for switching sources

### ISSUE THREAD

**Issue by Dan-cer** [linuxmint/cinnamon-spices-applets#5989]
### Applet name and maintainer

sound150@claudiux @claudiux

### What would you like to see?

I love your applet more from day to day! As I said before, its media hotkey settings are more stable than mint keyboard settings.
However, I realized that i.e. Youtube gets focus of media keys very quickly, without starting any video yet. Turning on music from player fails. I have to switch source.
I only have 2 media sources - browser (Vivaldi) and player (Lollypop) - and would like to be able to toggle between them via hotkey, too.
At the moment it is already easy via mouse because source list is always open. But as I'm using hotkeys for pause/play anyway, it would be great to get toggling with keys too.
Is that easy to implement?
Thank you for your answer!

**Comment by claudiux** [comment]
@Dan-cer Perhaps a shortcut for swapping players?

**Comment by Dan-cer** [comment]
Yes exactly. While one player is youtube in browser, displayed with browser name here. 
Thank you for accepting the endeavor.

**Comment by claudiux** [comment]
To be sure of what exactly you want: to be able to swap between the players in the "Launch player" section, or between those in the "Choose player controls" section?
![Sound150MenuPart](https://github.com/linuxmint/cinnamon-spices-applets/assets/33965039/a3079be3-1d71-4d53-a3d9-580fdbcdc107)

**Comment by Dan-cer** [comment]
The latter: "Choose player controls" section

**Comment by claudiux** [comment]
Done! I hope you'll like it.

**Comment by Dan-cer** [comment]
YES! I LIKE IT VERY MUCH! It is exactly how I need it and it works perfectly.
Your applet is getting more and more beautiful!

**Comment by claudiux** [comment]
@Dan-cer Glad you like this applet so much. If you haven't already done so, please consider increasing its score.

**Comment by Dan-cer** [comment]
Yes, I did so now. Clicked on "like" and left a comment.

**Comment by claudiux** [comment]
Many thanks to you! I've left a reply to your excellent message.

**Comment by Dan-cer** [comment]
And I also wrote a thread on the [Linux Mint forum](https://forums.linuxmint.com/viewtopic.php?p=2466728#p2466728) about it.

**Comment by claudiux** [comment]
Wow, that's really cool! Thanks for everything you've written.

**Comment by Dan-cer** [comment]
Basically, a lot of developers like you deserve our thanks. You make the Linux experience a satisfying one!
