### ISSUE TITLE
[weather@mockturtl] Bug: MET Norway service randomly gives "Error"

### ISSUE THREAD

**Issue by momonix** [linuxmint/cinnamon-spices-applets#5990]
### Applet version/Build date

3.4.2

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Nvidia GeForce GTX 960, driver NVIDIA 545.29.06

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

For a few days now, the MET Norway service has been giving "Error", whereas until then it was working normally.

**Comment by Gr3q** [comment]
Apologies, I pulled the fix out of the other version so it's merged faster.

**Comment by momonix** [comment]
Great! Now it works. Thanks.
