### ISSUE TITLE
[Sensors@claudiux:] Feature Request: Please add "Watt usage" to Monitor

### ISSUE THREAD

**Issue by fl0kiiiii** [linuxmint/cinnamon-spices-applets#5994]
### Applet name and maintainer

Sensors@claudiux @claudiux

### What would you like to see?

I would love to see a Watt usage Monitor to be added as it would complete the overall experience. If it is not possible for any reasons I would highly appreciate if someone can hint me to an applet for Cinnamon Spices in case it already exists.

**Comment by claudiux** [comment]
You can try to use `powertop`, which needs root privileges.
`apt install powertop`
`sudo powertop`
