### ISSUE TITLE
[Sensors@claudiux] Feature Request: No Outlines of Monitor in System Tray

### ISSUE THREAD

**Issue by fl0kiiiii** [linuxmint/cinnamon-spices-applets#5995]
### Applet name and maintainer

Sensors@claudiux @claudiux

### What would you like to see?

I would like to request a feature as part of cosmetic enhancement to remove the outlines of the Monitor in the System Tray if possible. I have attached two screenshots to get a sense of what i mean.

![Bildschirmfoto vom 2024-05-08 17-57-29](https://github.com/linuxmint/cinnamon-spices-applets/assets/169278504/43b6cfd4-bd2d-473e-9d1e-e0052a0e7a19)
![Bildschirmfoto vom 2024-05-08 17-57-49](https://github.com/linuxmint/cinnamon-spices-applets/assets/169278504/ef28431b-a7a5-4ea8-a41b-6e9db8dd73e8)

**Comment by claudiux** [comment]
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/33965039/2bd4bbd0-8128-4232-8bc3-cb280e2ac2d9)
