### ISSUE TITLE
[weather@mockturtl] Feature Request: Configurable UserAgent String

### ISSUE THREAD

**Issue by jcbodnar** [linuxmint/cinnamon-spices-applets#5999]
### Applet name and maintainer

weather@mockturtl @Gr3q

### What would you like to see?

My employer uses a proxy that is now blocking certain browsers (assuming old ones that may have security issues). The weather applet uses a hard-coded UserAgent of Firefox 37 which is getting blocked. The UserAgent string needs to be optionally configurable to avoid issues like this.

**Comment by Gr3q** [comment]
I will add an override and update the user-agent string.

For now you can do a search and replace for `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0` in every `weather-applet.js` inside `~/.local/share/cinnamon/applets/weather@mockturtl/` folder.

**Comment by jcbodnar** [comment]
Thanks! Updating the user agent string and reloading the applet through Looking Glass allows me to get my weather again! Thanks so much! (I hate our stupid security policies.)
