### ISSUE TITLE
Icing Task Manager: indicate active application

### ISSUE THREAD

**Issue by rik-shaw** [linuxmint/cinnamon-spices-applets#6]
Currently the "active application" is not apparent from the Icing Task Manager applet.  Rather *all* running apps have the "underlining" on them (green underline using Mint-Y, or blue underline using Arc).  It seems the underline should only be on the "active application"?  But in that case another way would need to be used to show a "non-active running app" vs a "non-running pinned app".  I think others would have a "darker" color to non-running apps?  Not sure what is best here, but in summary there are 3 (or maybe 4?) different states of applications that need to be uniquely shown:

1.  Active application
2.  Running (non-active) application
3.  Non-running pinned application
4.  Running application (minimized)

Great work, BTW!

**Comment by clefebvre** [comment]
@jaszhix ^^

@rik-shaw you should mention the author like I did above, so he can be notified.

**Comment by jaszhix** [comment]
Hi, this was addressed in [another issue](https://github.com/jaszhix/icingtaskmanager/issues/67) a few weeks ago. Under Theme Settings in the applet's Preferences, you can either disable "Show active app indicators", or try "Use the panel launcher class for pinned apps". Depending on the theme, these options work. You can change the pseudo class for app buttons as well. 

I was unable to find styling changes that everyone was happy with, so I gave everyone settings they can tinker with.

**Comment by rik-shaw** [comment]
@jaszhix thanks a lot for the reply.  With "show active app indicators" disabled and also the "Number display" set to "normal" (so a number is always shown for running apps), I can now tell the following:

1. Active application: hilighted by theme (in case of Arc / Mint-Y it is underlined with the hilight color)
2. Running (non-active) application: will have a number but is not underlined.
3. Non-running pinned application: is in the "taskbar", but no number, no underlining.

So that is basically what I felt was necessary and it does work well as you indicate.  Thanks again for the quick reply.

@clefebvre thanks for pointing this issue to @jaszhix : one thing I am confused about with the new consolidated github project for all the applets is how to find out who the author is?  So is there possibly a "README.md" that each applet should have to show this?  Or?  I tried digging around and I still can't determine that jaszhix is the author even though I know it is him :-)  Good work btw consolidating the applets, I think it will help in the long term.

**Comment by clefebvre** [comment]
Yes, it's something we need to formalize. I was going to add metadata.json at the root of the spice like we did for themes, but we're also considering having that info within the files/... we're looking into that right now. It will be formalized eventually and documented and as much as possible we'll try to get authors to use their github username.

**Comment by jonorthwash** [comment]
I'm having a similar issue, but after reading through this thread I'm confused about how it was resolved.  I tried adjusting all the settings mentioned, but all my apps get a border around them as if they were running/active.  In the following screenshot, several of the apps shown are not active at all, yet they seem to be highlighted as if they were:
![screenshot_2017-03-09_232433](https://cloud.githubusercontent.com/assets/963849/23782071/9b2d901c-051f-11e7-92c9-d4b2ebf70442.png)


When I try to adjust the theme settings, I get errors like the following:
```
(cinnamon:26335): Cjs-WARNING **: JS ERROR: TypeError: _this6.metaWorkspaces[_this6.currentWs] is undefined
refreshCurrentAppList/<@/home/jonathan/.local/share/cinnamon/applets/IcingTaskManager@json/applet.js:406
setTimeout/<@/home/jonathan/.local/share/cinnamon/applets/IcingTaskManager@json/__init__.js:14
```

What I'm trying to do is to have the inactive icons not have those lighter boxes around them.  Is there some secret I'm missing to get it to work this way?  This seems to be similar to this issue that was happening here too: https://github.com/jaszhix/icingtaskmanager/issues/67

**Comment by jaszhix** [comment]
@jonorthwash I said you could open this as an issue on my repo yesterday but I need you to give me the info in the issue template.

**Comment by jaszhix** [comment]
@NikoKrause Please remove the wontfix label, I never signaled that.

**Comment by jonorthwash** [comment]
Ah, @jaszhix, I hadn't understood quite what you meant.  Will do shortly.
