### ISSUE TITLE
mylauncher@markbokil.com: No menu when clicking.

### ISSUE THREAD

**Issue by Centurix** [linuxmint/cinnamon-spices-applets#6000]
### Applet version/Build date

2024-04-23 02:14:41

### Cinnamon version

Cinnamon 6.0.4

### Distribution

Mint 21.3

### Applet name and maintainer

mylauncher@markbokil.com @Centurix

### What happened?

I've used this for several years, but since the April 22 2024 update, it doesn't work. No menu when I click , no option to edit it. Running Mint 21 Cinnamon. Did the menu location change?

@TrippHazzard

**Comment by Centurix** [comment]
Picked up this issue from the spices page from linuxmint.com: https://cinnamon-spices.linuxmint.com/applets/view/60

@TrippHazzard is there any chance I could see an extract from the ~/.xsession-errors file?

**Comment by ChooChooAl** [comment]
I have the issue too.   
Looking Glass Error: /home/alan/.config/cinnamon/spices/mylauncher@markbokil.com/mylauncher.properties”: Not a directory
The folder in /home/alan/.config/cinnamon/spices/mylauncher@markbokil.com is a file not a folder.

**Comment by rcalixte** [comment]
@Centurix This line is the cause of the bug:
https://github.com/linuxmint/cinnamon-spices-applets/blob/ad20552/mylauncher%40markbokil.com/files/mylauncher%40markbokil.com/applet.js#L30

On older installations, this directory exists at `~/.cinnamon/configs` and won't be removed unless the applet is uninstalled.

**Comment by Centurix** [comment]
This change should handle the migration of legacy directories a bit better.

**Comment by TrippHazzard** [comment]
That fixed it! THANK YOU!!!
