### ISSUE TITLE
Applet Bug: Sound 150% freezes the screen when displaying a notification

### ISSUE THREAD

**Issue by quevon24** [linuxmint/cinnamon-spices-applets#6002]
### Applet version/Build date

6.11.0

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

RTX 3070 and nvidia driver 535

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Lately there have been constant updates to the applet and lately with any attempt to increase the volume, change songs, etc. The notification causes the system to freeze for a moment, the only way to solve it is to restart the computer. With the default sound applet this does not happen, you can increase/decrease the sound, change song without any freeze due notification display.

**Comment by claudiux** [comment]
This applet does not send notifications. Are you talking about the OSD?

**Comment by quevon24** [comment]
I mean this 
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/6474994/ae868fde-4ea2-477b-9fae-ef1cce023eae)
 
and this:

![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/6474994/38ce75d2-9d6f-4c49-bf81-24bbba477ec3)

when I update the applet and I increase/decrease the volume or change a song the computer freezes momentarily, the only way to avoid it is restart the computer or use the default sound applet

**Comment by claudiux** [comment]
The first notification provides from your player, not from this applet.

The second is the OSD. Try disabling the option "Whether to play a sound when the volume is changed" which is in the Sound tab of this applet settings.

**Comment by claudiux** [comment]
Is the `sound@cinnamon.org` applet well removed from panel?

**Comment by claudiux** [comment]
Thanks for reporting this issue. I'll work on it.

**Comment by quevon24** [comment]
> Is the `sound@cinnamon.org` applet well removed from panel?

yes, originally i removed sound@cinnamon.org applet and replaced it with sound150 but due the issue then i had to go back to the old applet without problems

**Comment by claudiux** [comment]
Which player(s) do you use when this freezing occurs?
I'm trying several ones. No problem with Spotify or Firefox.

**Comment by quevon24** [comment]
> Which player(s) do you use when this freezing occurs? I'm trying several ones. No problem with Spotify or Firefox.

Spotify, it also happens when i play youtube videos with chrome

**Comment by claudiux** [comment]
Do you hear tics while changing volume?

**Comment by claudiux** [comment]
Do you have any error messages about this applet in `~/.xsession-errors`?

**Comment by claudiux** [comment]
No response for a week. I can't reproduce this problem. So I close it.
