### ISSUE TITLE
[sound150] Please remove double entry of player control

### ISSUE THREAD

**Issue by Dan-cer** [linuxmint/cinnamon-spices-applets#6008]
### Applet name and maintainer

sound150@claudiux @claudiux

### What would you like to see?

Hi claudiux! I mentioned it before in another issue that is solved: Very often the player control displays my music player lollypop twice. I remember that you said that the program is entered or can be controlled twice, but somehow I think it should be possible to avoid the duplication. Like any program, I open Lollypop by clicking on the taskbar button. I would really appreciate it if you could find a solution to this. Here is a screenshot with the issue:

![lollypop](https://github.com/linuxmint/cinnamon-spices-applets/assets/800638/151d87f6-34c1-4e1d-b8b1-e8a43db7c2d3)

**Comment by claudiux** [comment]
Hi @Dan-cer,
That's not an issue, it's because there are two ways to control Lollypop.
But I can add an option to delete extra entries.

**Comment by Dan-cer** [comment]
That would be great!

**Comment by claudiux** [comment]
@Dan-cer 
Done! v6.13.0 is for you. Check the new option to avoid displaying controllers twice.

**Comment by Dan-cer** [comment]
Thank you! The controllers of lollypop aren't twice any longer.
However, when both browser and player are paused, I can't switch. Without the new option the active source is marked by a dot.
With the new option it is only marked in the beginning - first play of anything. Later the dot isn't there and shortkey for switch doesn't work either.
Could that be fixed easily?

**Comment by claudiux** [comment]
I don't encounter this problem. My shortkey is Shift+Super+P and that works fine in both cases.

**Comment by claudiux** [comment]
Mmm... Let me the time to work on it.

**Comment by Dan-cer** [comment]
No hurry. 
It's no different with shift+super-P. 
If both youtube and lollypop are started and alternately paused, then switching is not possible.

**Comment by claudiux** [comment]
This problem is a headache. I can't solve it at the moment without compromising the stability of this applet.

**Comment by Dan-cer** [comment]
OK, no problem. 

⁣BlueMail for Android herunterladen ​
