### ISSUE TITLE
color-picker@fmete - Temporarily stuck when trying to pick colors (dragging outside icon)

### ISSUE THREAD

**Issue by Siphalor** [linuxmint/cinnamon-spices-applets#6019]
### Applet version/Build date

2024-04-20 17:22:43

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Intel Corporation UHD Graphics 620

### Applet name and maintainer

color-picker@fmete @icarter09

### What happened?

The color picking is getting temporarily stuck (clicks on the screen aren't registering anymore) when clicking on the icon and then moving the mouse off while still holding the mouse button.

1. Move mouse over the icon
2. Click and hold the left mouse button
3. Move off the icon
4. Let go the mouse button
5. Now the cursor is stuck as the cross and clicks on windows do not register
6. Performing a simple click on the icon (clicks on panels still work) and clicking somewhere else will exit the color pick mode

### Other information

First discovered by @SebastJava and described in the comments of #4331 (similar symptoms but completely different cause).

Related issue at python-xlib: https://github.com/python-xlib/python-xlib/issues/159

**Comment by SebastJava** [comment]
YES ! I confirm this, right now.

I have a totally new, clean LM Cinnamon 21.3, a fresh install performed only one month ago.

**Comment by SebastJava** [comment]
The easiest way to get out of this is to click on the color-picker icon again, and then finally get to click and pick that precious color... Easy, but just too annoying when performed frequently.

**Comment by Siphalor** [comment]
After playing around a bit and reading the documentation for longer than I probably should've I found the cause and a fix:
Grabbing the mouse pointer failed, but the fail state was ignored, and the applet still waited for a successful mouse release.

I opened a PR that just tries to grab the pointer continuously until it is available (no longer held down).
From what I can see there is no way to grab the pointer while it is already held down, so that is probably the best solution.

**Comment by SebastJava** [comment]
@Siphalor Reading your latest comment here, I found a simpler steps to reproduce. I guess you probably had already figured this out, but I put it here, so everyone can see how easy it is to get into that bug:

1. Move mouse over the color-picker icon.
2. Click and hold the left mouse button for 1 second or more.
3. Let go the mouse button.

Now you are stuck with an apparently frozen or crashed desktop...
