### ISSUE TITLE
[sound150@claudiux] Feature Request: Microphone-related features

### ISSUE THREAD

**Issue by mehdi-abdelkhalek** [linuxmint/cinnamon-spices-applets#6026]
### Applet name and maintainer

sound150@claudiux @claudiux

### What would you like to see?

Hi claudiux!
First, I would like to thank you for being so responsive in treating issues and feature requests.
I have some features in mind related to microphone control.

1- Add an option to show that the microphone is active instead of muted
I only enable enable the microphone when I need it, so I want to only see an icon when it's not muted.

2- Restore microphone volume OSD
The original sound applet show an OSD with the microphone icon when I change it's volume, would be nice to see this feature back.

3- Control microphone volume with shift+mouse wheel
I don't know if this is doable with cinnamon applets

**Comment by claudiux** [comment]
Hi @mehdi-abdelkhalek 
Ok, I've put all these FRs on my todo-list.

**Comment by claudiux** [comment]
Work progress:

- [ ] Add an option to show that the microphone is active instead of muted
- [x]  Restore microphone volume OSD (using the microphone slider)
- [ ] Control microphone volume with shift+mouse wheel

**Comment by claudiux** [comment]
It's all done, except for the translation. I'll do a PR soon.

**Comment by claudiux** [comment]
Done! In the Icon tab of this applet settings, there is a new option: "Display icon indicating that the microphone is activated, if applicable".
If you like it, please increase the score of this applet on: https://cinnamon-spices.linuxmint.com/applets/view/306
Regards
claudiux

**Comment by mehdi-abdelkhalek** [comment]
Thank you, I have done that a while ago ;)
