### ISSUE TITLE
weather@mockturtl Forecast Icons shows a mixed German - English translation

### ISSUE THREAD

**Issue by kuehhe1** [linuxmint/cinnamon-spices-applets#6040]
### Applet version/Build date

Version 3.5.0 (2024-05-25 14:12:50)

### Cinnamon version

Cinnamon v: 6.0.4

### Distribution

LinuxMint 21.3

### Graphics hardware *and* driver used

Intel UHD Graphics 620 driver: i915 v: kernel

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

If the system language is set to German, the weather applet displays the text mixed in German and English on some icons of the weather forecast, see two (2) attached screenshots.

In the Weather > Weather conditions setup, the ‘Translate weather conditions’ switch has no influence on the translation. 

The text of the weather forecast is only displayed after switching the switch: ‘Weather conditions in short form’ to: ON on all icons is displayed correctly translated into German.

Notes:
1. In the GUI the character >g< is missing in the text ‘Wetterbedingun_en’.
2. The translation error occurs with the provider Open-Meteo

Translated with DeepL.com (free version)

### Screenshots

![weather-mockturtl_OpenMeteo_denglish_Wetterbeding _Kurfassung_Aus](https://github.com/linuxmint/cinnamon-spices-applets/assets/45901795/d627bd35-2dd3-4dc5-9e75-eaeb6b31360e)
![weather-mockturtl_OpenMeteo_deutsch_Wetterbeding _Kurfassung_Ein](https://github.com/linuxmint/cinnamon-spices-applets/assets/45901795/31996623-3d5e-40ec-9a0d-c8c2125f86c1)

**Comment by kuehhe1** [comment]
Hello and thanks for the feedback.

I followed the link to the de.po file and had a look, there are some translations missing but most of the weather conditions seem to be translated.

Does every provider use different weather state texts? Somehow I don't understand this yet?

**Comment by Gr3q** [comment]
Well, the answer is it really depends. Some do - I can't do much about them - they either provide translations themselves or not. Some don't, in that case I'm trying to make all of those consistent.

Unfortunately the out of support version of the applet's strings are also included.

As a side note I have to review "Translate weather conditions" because I mostly forgot about that setting. Everything should always be translated if possible.

**Comment by Axel-Erfurt** [comment]
This is the new german translation of @kuehhe1, it works well.
[de.po](https://github.com/user-attachments/files/15525838/de.po_deutsch_ubersetzt_kuehhe1.zip)

taken from [Linuxmintusers Forum](https://www.linuxmintusers.de/index.php?topic=74154.msg1058711#msg1058711)

**Comment by kuehhe1** [comment]
Hello, > If you or someone else wants to do it, download the file, open with [POEdit](https://poedit.net/) and translate the missing strings. If you upload the file here I can open another Pull request.

I have completed the translation of the German language file  <de.po>. After correcting and saving the Poedit also creates a file as <de.mo>. I just had to put it in the directory:
`~/.local/share/locale/en/LC_MESSAGES/`
save the existing <weather@mockturtl.mo> as <weather@mockturtl.mo.old> and rename the copied <de.mo> to <weather@mockturtl.mo>. 
Paths in LM21.3 LinuxMint Cinnamon:
```
~/.local/share/cinnamon/applets/weather@mockturtl/po/de.po
~/.local/share/locale/de/LC_MESSAGES/weather@mockturtl.mo
```
With "Restart Cinnamon" the changes were applied and the texts in the GUI and at Mouse-Hover and on the weather status symbols were displayed in German.

I attach both files as *.zip.
[de.po_deutsch_übersetzt_kuehhe1.zip](https://github.com/user-attachments/files/15526349/de.po_deutsch_ubersetzt_kuehhe1.zip)
[weather@mockturtl.mo_deutsch_übersetzt_kuehhe1.zip](https://github.com/user-attachments/files/15526350/weather%40mockturtl.mo_deutsch_ubersetzt_kuehhe1.zip)

Best regards kuehhe1

**Comment by rcalixte** [comment]
@Axel-Erfurt @kuehhe1 In the future, please feel free to open a pull request with your changes so that they can be shared with the wider community much easier. Don't hesitate to ask for help if you're not familiar with this process! And thank you for your contribution!

**Comment by Axel-Erfurt** [comment]
The last update Version 3.6.1 (2024-06-03 14:01:36) broke the German translation again.

![03_06_24_17_32_11](https://github.com/linuxmint/cinnamon-spices-applets/assets/2623542/ae8d3c7f-1095-40d2-834e-413c19f6911e)

**Comment by kuehhe1** [comment]
And now the new german translation to Version 3.6.1 (2024-06-03 14:01:36)
[de.po.zip](https://github.com/user-attachments/files/15536412/de.po.zip)

**Comment by rcalixte** [comment]
> A new german translation to Version 3.6.1 (2024-06-03 14:01:36) [de.po.zip](https://github.com/user-attachments/files/15536412/de.po.zip)
> 
> Diskussion: [Linuxmintusers.de](https://www.linuxmintusers.de/index.php?topic=74154.msg1058855#msg1058855)

Are you comfortable [creating a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) for this change? This way, you would be able to make sure updates are distributed as soon as translations are complete.

**Comment by kuehhe1** [comment]
Hello, opening a pull request is very confusing and beyond my capabilities, I just can't get any further. Please open it yourself.

**Comment by Axel-Erfurt** [comment]
Why was a working solution changed again?

**Comment by rcalixte** [comment]
> Why was a working solution changed again?

That is not what happened. There were new strings and new features added. These new strings require new translations.

**Comment by kuehhe1** [comment]
The last update to 
version 3.6.1 (2024-06-03 18:25:26) 
requires again the correction of the German language package de.po
I attach two created files.
[de.po.zip](https://github.com/user-attachments/files/15538712/de.po.zip)
[weather@mockturtl.mo.zip](https://github.com/user-attachments/files/15538731/weather%40mockturtl.mo.zip)

[Diskussion:](https://www.linuxmintusers.de/index.php?topic=74154.msg1058883#msg1058883)

**Comment by rcalixte** [comment]
> The last update to
> version 3.6.1 (2024-06-03 18:25:26) , Update es.po (#6051)
> requires again the correction of the German language package de.po

It was the change before that introduced the new strings. This change here updates the Spanish translation, the same as what needs to be amended for the German translation.



> I attach two created files.

This is appreciated and I can open the pull request again but long-term, this isn't an ideal process since it requires coordination from at least two people and splits the task of updating the translation onto more individuals than needed.

**Comment by rcalixte** [comment]
> Hello, opening a pull request is very confusing, I just can't get any further. Please open it yourself.

There is documentation that was generated by the community. I'll see if I can find the link again if you want to bookmark it for another shot in the future.
