### ISSUE TITLE
[sound150@claudiux] Volume step not properly working after reboot

### ISSUE THREAD

**Issue by Zixim** [linuxmint/cinnamon-spices-applets#6054]
### Applet version/Build date

6.15.0 (2024-05-23 17:48:53)

### Cinnamon version

5.6.8

### Distribution

Debian GNU/Linux 12 (bookworm)

### Graphics hardware *and* driver used

Intel

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Set the Volume step +/- to 2%.
Works fine.
Reboot... press media key Vol +/- : volume goes +/- 5%
Click applet icon in system tray, select Reload applet.
Works as expected (2% step).

**Comment by Zixim** [comment]
That did indeed make the steps behave as expected after reboot.
Thank you !

**Comment by claudiux** [comment]
This applet v6.16.0 can help users use the same multimedia shortcuts as those defined by Cinnamon.
