### ISSUE TITLE
weather@mockturtl - Sunrise Invalid Date Time when using weather provider DMI Denmark

### ISSUE THREAD

**Issue by jorgenqv** [linuxmint/cinnamon-spices-applets#6058]
### Applet version/Build date

3.6.1 (2024-06-05 17:46:58)

### Cinnamon version

6.0.4

### Distribution

Manjaro Linux

### Graphics hardware *and* driver used

Intel Haswell-ULT Integrated Graphics Controller - i915

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

The correct sunrise time is not shown when using DMI Denmark as weather forecast provider. Instead text "Invalid Date Time" is shown where time should be shown.

### Other information

![Weather 2024-06-05 23-36-13](https://github.com/linuxmint/cinnamon-spices-applets/assets/5297223/76d82914-e440-48fc-b8c6-3fe2ca36ead3)

**Comment by Gr3q** [comment]
Let's just say I've found some more problems with it.

![Screenshot from 2024-06-06 09-21-45](https://github.com/linuxmint/cinnamon-spices-applets/assets/22377521/d15b651f-6b63-403f-91d0-4ebe8e323581)

**Comment by jorgenqv** [comment]
Oups... Not that bad for me. I noticed that they are changes going on, some old urls like http://servlet.dmi.dk//byvejr/servlet/world_image?city=2692969&mode=dag1_2 are now redirecting to a image saying that they are going over to a new super computer and closing down graph services with more info after the summer.  https://www-dmi-dk.translate.goog/info-byvejr?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=sv&_x_tr_pto=wapp

**Comment by Gr3q** [comment]
I did fuck up, big time on my picture.

Yours is just DMI having an _amazing_ response for sunrise/sunset:

`"sunrise":"339","sunset":"2017",`

Lets just say it's a bit unreliable parsing that now. I'll just calculate them myself.

**Comment by jorgenqv** [comment]
Ok! Guessing the 1 hour missing is time zone or summer time related or something, 399 = 04:39 and 2017 = 21:17
Thank you!

**Comment by jorgenqv** [comment]
Fix works fine
