### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: invisible captions

### ISSUE THREAD

**Issue by Ilis** [linuxmint/cinnamon-spices-applets#607]
Captions are invisible when light theme of Cinnamon chosen.

Can be solved by 2 ways:

1. Autodetection theme background.
2. Manual setup for captions font.

![multicore-sysmon-captions](https://cloud.githubusercontent.com/assets/1223140/25771003/fd0e3eec-325d-11e7-9db1-7a800f2bbb2d.png)

**Comment by Ilis** [comment]
Also, default colours for metrics not good for light theme. And settings become default after applet updated.

**Comment by NikoKrause** [comment]
@ccadeptic23
