### ISSUE TITLE
[Sensors@claudiux] Add support for nvidia-smi

### ISSUE THREAD

**Issue by MikeSesketcharba** [linuxmint/cinnamon-spices-applets#6078]
### Applet name and maintainer

Sensors@claudiux @claudiux

### What would you like to see?

Hi! lm-sensors does not detect the temperature of my Nvidia GPU, but nvidia-smi does. If nvidia-smi could be implemented into the sensors applet, this applet would be excellent. Thanks!

**Comment by claudiux** [comment]
@MikeSesketcharba 
https://developer.nvidia.com/system-management-interface
I'll see what I can do about that.

**Comment by MikeSesketcharba** [comment]
Thanks! Take as much time as needed

13 Jun 2024 18:32:03 claudiux ***@***.***>:

**Comment by vajdao** [comment]
> @MikeSesketcharba https://developer.nvidia.com/system-management-interface I'll see what I can do about that.

For a temporary workaround I'd suggest implementing this somehow, so it reads the raw data from nvidia-smi:
`nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader`

Gives back numeric (without ˚C symbol, but it can be concatenated easily)

Just an idea though :)

**Comment by claudiux** [comment]
Closed by #6482. Thank you @JEleniel.
