### ISSUE TITLE
weather@mockturtl: Service Error 403 on all data sources

### ISSUE THREAD

**Issue by LightningStalker** [linuxmint/cinnamon-spices-applets#6087]
### Applet version/Build date

3.6.2

### Cinnamon version

5.8.4

### Distribution

21.2

### Graphics hardware *and* driver used

NVIDIA GeForce GTX 1060

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

Service Error in panel, log says
`Gjs-Message: 08:39:14.200: JS LOG: [LookingGlass/info] [weather@mockturtl#16:Info]: Error calling URL: 403, Forbidden, <html>
Gjs-Message: 08:39:14.200: JS LOG: [LookingGlass/error] [weather@mockturtl#16:Error]: Error: API response is not JSON. The response: null`

Expected weather forecast data

### Other information

Log is too long to post here

**Comment by rcalixte** [comment]
@LightningStalker Which service are you trying to use? (There are several in the options.) How do you have it configured?

**Comment by LightningStalker** [comment]
I tried each one. Default configuration

**Comment by LightningStalker** [comment]
Uninstall, reinstall and working now. Unsure what the problem was. Thanks.

**Comment by LightningStalker** [comment]
Ok problem is manual location, can't get anything to work except GPS coordinates

**Comment by Gr3q** [comment]
Can you access https://nominatim.openstreetmap.org/ui/search.html? if you search there, does it work?

**Comment by LightningStalker** [comment]
Yes it does

**Comment by Gr3q** [comment]
A bit of a late reply, but If you enable debug logs you get the exact url that's being called (includes nominatim).

If you copy that in the browser or you use `curl` from the terminal, does it still work?

I'm just trying to narrow it down what could it be the problem. I'm sure nothing is replacing the user-agent string system-wide and you don't call nominatim.org on your own more than once a second.

**Comment by LightningStalker** [comment]
It's still happening but working in browser. Interval is default 15.

**Comment by Gr3q** [comment]
In Applet Settings->Help->User Agent string override try to put anything in and refresh, see if it works.

**Comment by LightningStalker** [comment]
I change it to Mozilla/5.0 and working.

**Comment by Gr3q** [comment]
In the next version I make the user-agent somewhat unique for each user so hopefully the applet doesn't get a blanket ban.
