### ISSUE TITLE
[weather@mockturtl] Feature Request

### ISSUE THREAD

**Issue by rabe1982** [linuxmint/cinnamon-spices-applets#6094]
### Applet name and maintainer

weather@mockturtl @Gr3q

### What would you like to see?

![Bildschirmfoto vom 2024-06-17 15-04-30](https://github.com/linuxmint/cinnamon-spices-applets/assets/157573897/e911258a-33c8-4e3a-ba4d-5321e3d5a120)

In the app the location “Germany” is displayed as “Nazi state”. This is not only wrong but also an impudence.

**Comment by Gr3q** [comment]
If you look up your original search text [here](https://nominatim.openstreetmap.org/ui/search.html), does it have the same text? If yes, report to them here https://community.openstreetmap.org/

If not, it's coming from the weather provider you are using. Please tell me which one and I'll verify that, then report it to them.

**Comment by rabe1982** [comment]
![Bildschirmfoto vom 2024-06-17 15-40-58](https://github.com/linuxmint/cinnamon-spices-applets/assets/157573897/cd4f2430-5d3c-49a0-b071-921098ad97cc)


I use "Deutscher Wetterdienst"

**Comment by Gr3q** [comment]
I'll verify when I get home.

Just in case a disclaimer...this is definitely not intended, not in the codebase nor in our translation system, it's coming or came at some point directly from either OpenStreetMap or Deutscher Wetterdienst.

How long ago did you save this location, and if you remember which provider did you use at that time?

**Comment by rabe1982** [comment]
I noticed this today around 3pm (GMT +2). I got the message that the location cannot be found. then I went to update location and suddenly it was there. I always use deutscher Wetterdienst.

**Comment by Gr3q** [comment]
I see.

I checked the provider data, it cannot come from them, so that leaves OpenStreetMap...but it returns the correct data for me now.

If you delete, restart cinnamon and resave it, does it still happen for you?

**Comment by rabe1982** [comment]
After I delete the entry, restart und resave it,  the data is now correct.

**Comment by Steffen-W** [comment]
Hi,

I had the same error a few days ago. Instead of "Deutschland" it said "Nazi state". Unfortunately, I now have the problem every day with different names for Germany. Today it says "Frederik Ramm". I haven't yet been able to find out where this comes from, but it's really annoying.

**Comment by Gr3q** [comment]
It comes from OpenStreetMap. Vandalism is rampant on it in the past week, you can find threads about it on their forums and on the internet.

Unfortunately I can't do much about it because the data is poisoned at the source.

The only thing I and (you) can do is that I fix them on OpenStreetMap as they change it.

**Comment by Steffen-W** [comment]
But I think there is a way around it. Actually, the location only has to be queried once via openstreetmap and not every day. Couldn't you prevent it from being updated regularly? I like the app and I appreciate it, but I think others would also be very happy to find a workaround to this problem.
Many thanks for the really quick reply.

**Comment by Gr3q** [comment]
I don't keep a persistent cache around, and you usually want to see changes.

But you can always save the location yourself and change the city/country yourself, those will persist
