### ISSUE TITLE
[qredshift@quintao] v2.0.0 doesn't work

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon-spices-applets#6126]
### Applet version/Build date

Version 2.0.0 (2024-06-28 08:30:35)

### Cinnamon version

Cinnamon 6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller

### Applet name and maintainer

qredshift@quintao @raphaelquintao

### What happened?

I've removed redshift, also entirely removed the old version of this applet (even config files).
Then I've installed the v2.0.0 of this applet and set all settings.
Nothing happens when I activate/deactivate this applet.

My `~/.xsession-errors` contains:
```
(cinnamon:2292): GLib-CRITICAL **: 14:39:07.442: g_child_watch_add_full: assertion 'pid > 0' failed
Gjs-Message: 14:39:07.445: JS LOG: [LookingGlass/warning] 
QRedshift: Created

(cinnamon:2292): GLib-CRITICAL **: 14:39:07.472: g_child_watch_add_full: assertion 'pid > 0' failed

(cinnamon:2292): Gjs-WARNING **: 14:39:07.483: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to use TextDecoder.
(Note that array.toString() may have been called implicitly.)
0 _parse() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":103:12]
1 spawn_command_line_async_promise/<() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":125:31]
2 spawn_command_line_async_promise() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":110:11]
3 QRedshift() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":320:15]
4 main() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":1073:11]
5 createApplet() ["/usr/share/cinnamon/js/ui/appletManager.js":597:24]
6 addAppletToPanels() ["/usr/share/cinnamon/js/ui/appletManager.js":372:33]
7 finishExtensionLoad() ["/usr/share/cinnamon/js/ui/appletManager.js":98:13]
8 _init/<() ["/usr/share/cinnamon/js/ui/extension.js":286:31]

Gjs-Message: 14:39:07.488: JS LOG: [LookingGlass/warning] 
QRedshift: ADDED TO PANEL
Gjs-Message: 14:39:07.495: JS LOG: [LookingGlass/info] Loaded applet qredshift@quintao in 128 ms
Gjs-Message: 14:39:07.495: JS LOG: [LookingGlass/warning] 
ASYNC LOADING: qredshift 0.10

Gjs-Message: 14:39:07.495: JS LOG: [LookingGlass/warning] 
UPDATE: true

(cinnamon:2292): GLib-CRITICAL **: 14:39:07.519: g_child_watch_add_full: assertion 'pid > 0' failed
```

Later:
```
(cinnamon:2292): GLib-CRITICAL **: 14:39:19.753: g_child_watch_add_full: assertion 'pid > 0' failed
Gjs-Message: 14:39:19.820: JS LOG: [LookingGlass/warning] 
UPDATE: true

(cinnamon:2292): GLib-CRITICAL **: 14:39:19.835: g_child_watch_add_full: assertion 'pid > 0' failed
Gjs-Message: 14:39:19.843: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function 696]: Too many arguments to method Clutter.InputDevice.ungrab: expected 0, got 1
Gjs-Message: 14:39:20.464: JS LOG: [LookingGlass/warning] 
UPDATE: true
```

I hope you'll can solve this issue. Your applet saves my eyes! Thank you!

### Other information

I'm using X11, not wayland.

**Comment by claudiux** [comment]
I'd tried your `bin/qredshift` command. Nothing happens; no change.

**Comment by ovexro** [comment]
Yes. After installing the required updates — on Intel and AMD — it no longer works. It is a bug, of course. But I'm sure it will be fixed soon — I'm dependent upon it. My eyes hurt badly without it.

**Comment by raphaelquintao** [comment]
Whats is the output of the command `xrandr --listmonitors`.

**Comment by ovexro** [comment]
> Whats is the output of the command `xrandr --listmonitors`.

```
root@ovidiu-PC:/home/ovidiu# xrandr --listmonitors
Monitors: 1
 0: +*DP-4 1920/698x1080/393+0+0  DP-4
root@ovidiu-PC:/home/ovidiu# 
```

**Comment by raphaelquintao** [comment]
That command work for you? 
`~/.local/share/cinnamon/applets/qredshift@quintao/bin/qredshift -t 4500`

**Comment by ovexro** [comment]
> That command work for you? `~/.local/share/cinnamon/applets/qredshift@quintao/bin/qredshift -t 4500`

I tried it. It doesn't work.

**Comment by claudiux** [comment]
> Whats is the output of the command `xrandr --listmonitors`.

```$ xrandr --listmonitors
Monitors: 1
 0: +*HDMI-1 1920/496x1080/292+0+0  HDMI-1
```

**Comment by claudiux** [comment]
> That command work for you? `~/.local/share/cinnamon/applets/qredshift@quintao/bin/qredshift -t 4500`

It does not work. No change.

**Comment by raphaelquintao** [comment]
If you install redshift `sudo apt install redshift` and run the command `redshift -m randr -P -O 4500` it works  ?

**Comment by claudiux** [comment]
`~/.local/share/cinnamon/applets/qredshift@quintao/bin/qredshift -i` returns:
```
DS:x11
DE:X-Cinnamon
WM:unknown

1:C:HDMI-1:0x0
```

**Comment by claudiux** [comment]
> If you install redshift `sudo apt install redshift` and run the command `redshift -m randr -P -O 4500` it works ?

Yes, it works.

**Comment by ovexro** [comment]
> If you install redshift `sudo apt install redshift` and run the command `redshift -m randr -P -O 4500` it works ?

```
root@ovidiu-PC:/home/ovidiu# sudo apt install redshift
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
redshift is already the newest version (1.12+mint5+vanessa).
The following packages were automatically installed and are no longer required:
  linux-headers-5.15.0-100 linux-headers-5.15.0-100-generic
  linux-headers-5.15.0-101 linux-headers-5.15.0-101-generic
  linux-headers-5.15.0-102 linux-headers-5.15.0-102-generic
  linux-headers-5.15.0-105 linux-headers-5.15.0-105-generic
  linux-headers-5.15.0-106 linux-headers-5.15.0-106-generic
  linux-headers-5.15.0-107 linux-headers-5.15.0-107-generic
  linux-headers-5.15.0-92 linux-headers-5.15.0-92-generic
  linux-headers-5.15.0-94 linux-headers-5.15.0-94-generic
  linux-headers-5.15.0-97 linux-headers-5.15.0-97-generic
  linux-image-5.15.0-100-generic linux-image-5.15.0-101-generic
  linux-image-5.15.0-102-generic linux-image-5.15.0-105-generic
  linux-image-5.15.0-106-generic linux-image-5.15.0-107-generic
  linux-image-5.15.0-92-generic linux-image-5.15.0-94-generic
  linux-image-5.15.0-97-generic linux-modules-5.15.0-100-generic
  linux-modules-5.15.0-101-generic linux-modules-5.15.0-102-generic
  linux-modules-5.15.0-105-generic linux-modules-5.15.0-106-generic
  linux-modules-5.15.0-107-generic linux-modules-5.15.0-92-generic
  linux-modules-5.15.0-94-generic linux-modules-5.15.0-97-generic
  linux-modules-extra-5.15.0-100-generic
  linux-modules-extra-5.15.0-101-generic
  linux-modules-extra-5.15.0-102-generic
  linux-modules-extra-5.15.0-105-generic
  linux-modules-extra-5.15.0-106-generic
  linux-modules-extra-5.15.0-107-generic linux-modules-extra-5.15.0-92-generic
  linux-modules-extra-5.15.0-94-generic linux-modules-extra-5.15.0-97-generic
  nvidia-firmware-535-535.146.02 nvidia-firmware-535-535.154.05
  nvidia-firmware-535-535.161.07 nvidia-firmware-535-535.171.04
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@ovidiu-PC:/home/ovidiu# redshift -m randr -P -O 4500
Authorization required, but no authorization protocol specified
`RANDR Query Version' returned error -1
Initialization of randr failed.
```

**Comment by raphaelquintao** [comment]
Try install that packages `sudo apt-get install libxcb1 libxcb1-dev libxcb-randr0 libxcb-randr0-dev` restart  and check if that `~/.local/share/cinnamon/applets/qredshift@quintao/bin/qredshift -t 4500` works.

**Comment by ovexro** [comment]
> Try install that packages `sudo apt-get install libxcb1 libxcb1-dev libxcb-randr0 libxcb-randr0-dev` restart and check if that `~/.local/share/cinnamon/applets/qredshift@quintao/bin/qredshift -t 4500` works.

```
ovidiu@ovidiu-PC:~$ ~/.local/share/cinnamon/applets/qredshift@quintao/bin/qredshift -t 4500
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  23 (RRGetCrtcGamma)
  Crtc id in failed request: 0x1bd
  Serial number of failed request:  18
  Current serial number in output stream:  18
ovidiu@ovidiu-PC:~$ 
```

**Comment by raphaelquintao** [comment]
Try download that updated binary: [qredshift](https://github.com/raphaelquintao/QRedshiftCinnamon/raw/master/files/qredshift@quintao/bin/qredshift)
And run the following commands: 
Check if that works: `./qredshift -t 4500`
if not try that `./qredshift -xcb -t 4500`

**Comment by claudiux** [comment]
`./qredshift -t 4500` works!!! Thank you!!!

**Comment by claudiux** [comment]
With the new version of your `qredshift` this applet works very well. Please make a PR.

**Comment by ovexro** [comment]
Can you make it available on Update Manager?

**Comment by raphaelquintao** [comment]
I will make a pull request in a moment.
Thanks guys!!

**Comment by ovexro** [comment]
Please tell us what the issue was. <3

**Comment by ovexro** [comment]
I made the update but it still doesn't work.

**Comment by claudiux** [comment]
> I made the update but it still doesn't work.

```
cd ~/.local/share/cinnamon/applets/qredshift@quintao/bin/
rm -f qredshift
wget https://github.com/raphaelquintao/QRedshiftCinnamon/raw/master/files/qredshift@quintao/bin/qredshift
chmod +x qredshift
```

**Comment by raphaelquintao** [comment]
> Please tell us what the issue was. <3

The problem was that i was setting the gamma ramps on all outputs including the disconnected ones, and for some reason my hardware accept that and some other don't.

**Comment by raphaelquintao** [comment]
@ovexro The version 2.0.0 was reverted back on the repository. 
For now, if you want the latest version you can follow these steps:

1. Download zip from [qredshift@quintao_2.0.0.zip](https://github.com/raphaelquintao/QRedshiftCinnamon/releases/download/v2.0.0/qredshift@quintao_2.0.0.zip).
2. Extract .zip archive to `~/.local/share/cinnamon/applets`.
3. Enable the applet in Cinnamon settings

**Comment by claudiux** [comment]
Maybe make this applet multiversion and create a 6.2 folder containing v2.0.0?

**Comment by raphaelquintao** [comment]
> Maybe make this applet multiversion and create a 6.2 folder containing v2.0.0?

It will work better on some older versions of cinnamon. Someone used some new functions that don't exist in older versions and this was causing problems in the older versions. See [#QRedshiftCinnamon-66](https://github.com/raphaelquintao/QRedshiftCinnamon/issues/66)
I think a multi version is not required.

**Comment by ovexro** [comment]
It's working now. 
Thank you!
