### ISSUE TITLE
Redshift 2.0: External screen not affected

### ISSUE THREAD

**Issue by yairmohr** [linuxmint/cinnamon-spices-applets#6128]
### Applet version/Build date

2.0

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Applet name and maintainer

qredshift@quintao @raphaelquintao

### What happened?

I'm using my laptop with an external display in addition to the built-in one. The new version of Qredshift leaves that screen on regular brightness and gama when switching the main (built-in) display to night settings.

**Comment by raphaelquintao** [comment]
The version 2.0.0 was reverted back on the repository. 
For now, if you want the latest version you can follow these steps:

1. Download zip from [qredshift@quintao_2.0.0.zip](https://github.com/raphaelquintao/QRedshiftCinnamon/releases/download/v2.0.0/qredshift@quintao_2.0.0.zip).
2. Extract .zip archive to `~/.local/share/cinnamon/applets`.
3. Enable the applet in Cinnamon settings

**Comment by raphaelquintao** [comment]
@yairmohr Let me know if that version works for you.

**Comment by yairmohr** [comment]
That did fix the issue. Thank you so much, Raphael!
