### ISSUE TITLE
weather@mockturtl: Weather applet not working

### ISSUE THREAD

**Issue by Tragedian** [linuxmint/cinnamon-spices-applets#6137]
### Applet version/Build date

3.6.2 (2024-06-25 10:39:22)

### Cinnamon version

5.2.7

### Distribution

Mint 20.3

### Graphics hardware *and* driver used

Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller (rev 09)

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

The applet doesn't start and hasn't for a while. Looking Glass information below:

info t=2024-06-29T10:41:03Z Installing settings for weather@mockturtl
info t=2024-06-29T10:41:03Z Settings successfully installed for weather@mockturtl
info t=2024-06-29T10:41:03Z [weather@mockturtl#19:Info]: Setting user agent to: Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0
info t=2024-06-29T10:41:03Z [weather@mockturtl#19:Info]: Main Loop started.
info t=2024-06-29T10:41:03Z Loaded applet weather@mockturtl in 135 ms
error t=2024-06-29T10:41:03Z [weather@mockturtl#19:Error]: Generic Error while refreshing Weather info: GeoClue.new_with_thresholds is not a function, 
error t=2024-06-29T10:41:03Z GJS Error context - Name: TypeError, domain: undefined, code: NO_SUCH_DEVICE, message: GeoClue.new_with_thresholds is not a function
error t=2024-06-29T10:41:03Z GetLocation/res<@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:16622:21
GetLocation@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:16619:27
EnsureLocation@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:17398:48
RefreshWeather@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:19637:46
WeatherLoop/this.DoCheck@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:17803:30
Start@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:17880:24
WeatherApplet@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:19599:24
main@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:19944:12
main@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/applet.js:6:26
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:597:25
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:372:34
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:101:14
_init/<@/usr/share/cinnamon/js/ui/extension.js:274:32

error t=2024-06-29T10:41:03Z [weather@mockturtl#19:Error]: Retrying in the next 15 seconds...
info t=2024-06-29T10:41:03Z [weather@mockturtl#19:Info]: Critical Error while refreshing weather.
error t=2024-06-29T10:41:18Z [weather@mockturtl#19:Error]: Generic Error while refreshing Weather info: GeoClue.new_with_thresholds is not a function, 
error t=2024-06-29T10:41:18Z GJS Error context - Name: TypeError, domain: undefined, code: NO_SUCH_DEVICE, message: GeoClue.new_with_thresholds is not a function
error t=2024-06-29T10:41:18Z GetLocation/res<@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:16622:21
GetLocation@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:16619:27
EnsureLocation@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:17398:48
RefreshWeather@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:19637:46
WeatherLoop/this.DoCheck@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:17803:30
Start@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:17880:24
async*WeatherApplet@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:19599:24
main@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:19944:12
main@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/applet.js:6:26
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:597:25
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:372:34
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:101:14
_init/<@/usr/share/cinnamon/js/ui/extension.js:274:32

error t=2024-06-29T10:41:18Z [weather@mockturtl#19:Error]: Retrying in the next 15 seconds...
info t=2024-06-29T10:41:18Z [weather@mockturtl#19:Info]: Critical Error while refreshing weather.
error t=2024-06-29T10:41:48Z [weather@mockturtl#19:Error]: Generic Error while refreshing Weather info: GeoClue.new_with_thresholds is not a function, 
error t=2024-06-29T10:41:48Z GJS Error context - Name: TypeError, domain: undefined, code: NO_SUCH_DEVICE, message: GeoClue.new_with_thresholds is not a function
error t=2024-06-29T10:41:48Z GetLocation/res<@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:16622:21
GetLocation@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:16619:27
EnsureLocation@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:17398:48
RefreshWeather@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:19637:46
WeatherLoop/this.DoCheck@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:17803:30
Start@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:17880:24
async*WeatherApplet@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:19599:24
main@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/weather-applet.js:19944:12
main@/home/del/.local/share/cinnamon/applets/weather@mockturtl/3.8/applet.js:6:26
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:597:25
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:372:34
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:101:14
_init/<@/usr/share/cinnamon/js/ui/extension.js:274:32

error t=2024-06-29T10:41:48Z [weather@mockturtl#19:Error]: Retrying in the next 30 seconds...
info t=2024-06-29T10:41:48Z [weather@mockturtl#19:Info]: Critical Error while refreshing weather.

**Comment by Gr3q** [comment]
Hi, I'll add a check for this, in the meantime could you give me your `geoclue` package version?

**Comment by Tragedian** [comment]
Thanks. Working perfectly now.
