### ISSUE TITLE
sound150@claudiux: Not loading on Arch Cinnamon

### ISSUE THREAD

**Issue by AdryanDs** [linuxmint/cinnamon-spices-applets#6143]
### Applet version/Build date

 "version": "6.17.1",

### Cinnamon version

6.2.2

### Distribution

Arch

### Graphics hardware *and* driver used

Amd gpu

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Applet is not loading. Cinnamon troubleshooting looking glass log: 
[sound150@claudiux]: entry is null
[sound150@claudiux]: Failed to evaluate 'main' function on applet: sound150@claudiux/44

**Comment by claudiux** [comment]
Works well with Cinnamon 6.0.4.
I'm upgrading to Cinnamon 6.2.2...

**Comment by claudiux** [comment]
All seems OK with Cinnamon 6.2.2.
Please check your sound parameters in Cinnamon Settings.

**Comment by claudiux** [comment]
I've rebooted my computer after Cinnamon upgrade.

**Comment by AdryanDs** [comment]
I'm using pipewire, sound settings looks fine

**Comment by claudiux** [comment]
I'm using pipewire too.

**Comment by AdryanDs** [comment]
I don't know what to do further, any clue how to make it work? Is there any package that is required by applet, or audio settings in arch? I've already installed playerctl. Thank you for this applet, i'm using it for a long time ago, it's a must have for me, but now i don't know what i'm missing, to make it work

**Comment by claudiux** [comment]
Please try that:
Edit `~/.local/share/cinnamon/applets/sound150@claudiux/5.4/applet.js`.

Line 2783 you have:
```
    passDesktopEntry(entry) {
```

Insert a line just after with:
```
        if (entry == null) return;
```

Restart this applet (or Cinnamon).
Tell me if that works.

**Comment by AdryanDs** [comment]
Still doesn't work

**Comment by claudiux** [comment]
Often, on Arch, a `sudo pacman -Suy` solves the problems. Like here: https://github.com/linuxmint/cinnamon-spices-applets/issues/5987#issuecomment-2124348946

**Comment by AdryanDs** [comment]
Again, back to the problem. Applet itțs not loading. After i've reinstalled arch, i've begin installing some software, after i i've rebooted pc, problem appears again, so i'm back to where i left initially. I don't know exactly after what apps or software i've installed, applet not loading. Maybe, if i have time, i will start over, and install one by one and test, to see where the problem start

**Comment by claudiux** [comment]
Please post the complete contents of your `~/.xsession-errors` file here.

**Comment by claudiux** [comment]
Please try v6.17.2.

**Comment by AdryanDs** [comment]
I've downloaded latest fix, sorry, for me it's not working

**Comment by AdryanDs** [comment]
** (csd-power:787): CRITICAL **: 18:33:30.317: abs_to_percentage: assertion 'max > min' failed
Gjs-Message: 18:33:30.318: JS LOG: Unknown network device type, is 32
Window manager warning: audio-prev-16 - Overwriting existing binding of keysym 1008ff16 with keysym 1008ff16 (keycode ad).
Window manager warning: volume-mute-18 - Overwriting existing binding of keysym 1008ff12 with keysym 1008ff12 (keycode 79).
Window manager warning: pause-18 - Overwriting existing binding of keysym 1008ff14 with keysym 1008ff14 (keycode ac).
Window manager warning: sound-open-17 - Overwriting existing binding of keysym 73 with keysym 73 (keycode 27).
Window manager warning: raise-volume-18 - Overwriting existing binding of keysym 1008ff13 with keysym 1008ff13 (keycode 7b).
Window manager warning: audio-next-16 - Overwriting existing binding of keysym 1008ff17 with keysym 1008ff17 (keycode ab).
Window manager warning: sound-open-18 - Overwriting existing binding of keysym 73 with keysym 73 (keycode 27).
Window manager warning: raise-volume-17 - Overwriting existing binding of keysym 1008ff13 with keysym 1008ff13 (keycode 7b).
Window manager warning: audio-prev-18 - Overwriting existing binding of keysym 1008ff16 with keysym 1008ff16 (keycode ad).
Window manager warning: audio-stop-16 - Overwriting existing binding of keysym 1008ff15 with keysym 1008ff15 (keycode ae).
Window manager warning: media-keys-9 - Overwriting existing binding of keysym 1008ff14 with keysym 1008ff14 (keycode ac).
Window manager warning: volume-mute-17 - Overwriting existing binding of keysym 1008ff12 with keysym 1008ff12 (keycode 79).
Window manager warning: media-keys-4 - Overwriting existing binding of keysym 1008ff11 with keysym 1008ff11 (keycode 7a).
Window manager warning: audio-stop-18 - Overwriting existing binding of keysym 1008ff15 with keysym 1008ff15 (keycode ae).
Window manager warning: lower-volume-16 - Overwriting existing binding of keysym 1008ff11 with keysym 1008ff11 (keycode 7a).
Window manager warning: lower-volume-17 - Overwriting existing binding of keysym 1008ff11 with keysym 1008ff11 (keycode 7a).
Window manager warning: audio-next-18 - Overwriting existing binding of keysym 1008ff17 with keysym 1008ff17 (keycode ab).
Window manager warning: audio-prev-17 - Overwriting existing binding of keysym 1008ff16 with keysym 1008ff16 (keycode ad).
Window manager warning: media-keys-11 - Overwriting existing binding of keysym 1008ff15 with keysym 1008ff15 (keycode ae).
Window manager warning: volume-mute-16 - Overwriting existing binding of keysym 1008ff12 with keysym 1008ff12 (keycode 79).
Window manager warning: media-keys-13 - Overwriting existing binding of keysym 1008ff17 with keysym 1008ff17 (keycode ab).
Window manager warning: media-keys-2 - Overwriting existing binding of keysym 1008ff13 with keysym 1008ff13 (keycode 7b).
Window manager warning: pause-16 - Overwriting existing binding of keysym 1008ff14 with keysym 1008ff14 (keycode ac).

(cinnamon:1007): Gjs-CRITICAL **: 18:35:44.727: JS ERROR: TypeError: this._output is null
_volumeChange@/home/adrian/.local/share/cinnamon/applets/sound150@claudiux/5.4/applet.js:2322:29
_setKeybinding/<@/home/adrian/.local/share/cinnamon/applets/sound150@claudiux/5.4/applet.js:2073:109


(cinnamon:1007): Gjs-CRITICAL **: 18:35:45.011: JS ERROR: TypeError: this._output is null
_volumeChange@/home/adrian/.local/share/cinnamon/applets/sound150@claudiux/5.4/applet.js:2322:29
_setKeybinding/<@/home/adrian/.local/share/cinnamon/applets/sound150@claudiux/5.4/applet.js:2073:109


(cinnamon:1007): Gjs-CRITICAL **: 18:35:46.772: JS ERROR: TypeError: this._output is null
_volumeChange@/home/adrian/.local/share/cinnamon/applets/sound150@claudiux/5.4/applet.js:2322:29
_setKeybinding/<@/home/adrian/.local/share/cinnamon/applets/sound150@claudiux/5.4/applet.js:2073:109

**Comment by claudiux** [comment]
`TypeError: this._output is null` is not the same error. Previously, it was `entry is null`.

What is your output sound device?
![image](https://github.com/linuxmint/cinnamon-spices-applets/assets/33965039/81b40241-e835-4624-8216-90560f13ddd1)

**Comment by AdryanDs** [comment]
![Screenshot from 2024-07-02 19-15-31](https://github.com/linuxmint/cinnamon-spices-applets/assets/172021284/d475c4ff-6c9c-49f0-863a-bb6b5b9d208e)

**Comment by claudiux** [comment]
Please try with other output devices.

**Comment by AdryanDs** [comment]
I tried, still no

**Comment by claudiux** [comment]
Please uninstall this applet completely and try with the `sound@cinnamon` applet. Does it work better?

**Comment by AdryanDs** [comment]
Yes, that works by default

**Comment by claudiux** [comment]
Mmmh. I'll check out the differences between the two.

**Comment by AdryanDs** [comment]
I don't understand either. It is something localy on my pc? Is it something in your code? But why as soon i've reinstalled it was working by default (without anything else install or theming)?

**Comment by AdryanDs** [comment]
I don't know what happened, but i've deleted sound150@claudiux, dowloaded again and it loads ok now. I can't beleive it.. I don't know to do further to stay like that. Thank you!

**Comment by claudiux** [comment]
Perhaps you now have the latest version of `sound150@claudiux` (6.17.3) instead of the previous version (6.17.2) which I also made today.
