### ISSUE TITLE
weather@mockturtl: + and − signs

### ISSUE THREAD

**Issue by Ilis** [linuxmint/cinnamon-spices-applets#618]
@mockturtl 

Please add settings to show “+” sign for positive temperature values.
It is a Russian tradition to show weather temperature with required plus or minis sign, i. e.:
https://yandex.ru/pogoda/yekaterinburg
due to fast changing weather.

One more issue — show minus sign as unicode MINUS SIGN “−” instead of “-” HYPEN
It will make displaying temperature more nicer :) Also − and + has equal symbol width in fonts

Examples:
Minus sign:
-2 °C → −2 °C

Plus and Minus
−20 °C
+15 °C

Range:
−7 / −2 °C
−2 / +3 °C
+13 / +18 °C
0 / +5 °C
−5 / 0 °C

0 has no sign.

Next, Russian weather forecasters uses “…” HORIZONTAL ELLIPSIS without spaces for range separator
−2…+3 °C
https://yandex.ru/pogoda/yekaterinburg/details
Is it possible to implement?

**Comment by icarter09** [comment]
@Gr3q

**Comment by Gr3q** [comment]
Yeah, I was meaning to implement this for a while now.

It is working, although the Plus sign looks like a goddamn cross for me: 
![image](https://user-images.githubusercontent.com/22377521/75630398-698ff500-5be2-11ea-8f5a-d21af24457a9.png)

Setting:
![image](https://user-images.githubusercontent.com/22377521/75630411-79a7d480-5be2-11ea-8d1e-99d9213b76ef.png)

If that's ok.

**Comment by Ilis** [comment]
If I say that

4°

looks like sitting upset man — you will newer unsee that :)

+6 is very nice and informative! Thank you, @Gr3q


And what about +6°C
It used with space between number and measure units:
+6 °C

But if you use degrees without Celsius, you should write it without spacing, say:
Angle is 45°

**Comment by Gr3q** [comment]
I'm going to put the space back in, it is a regression.

I will leave the temperature unit displayed with it.
