### ISSUE TITLE
[moonphase@techi-freki] No longer displays menu

### ISSUE THREAD

**Issue by claudiux** [linuxmint/cinnamon-spices-applets#6185]
### Applet version/Build date

Version 1.0.0 (2024-07-01 05:09:10)

### Cinnamon version

Cinnamon 6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

No matters

### Applet name and maintainer

moonphase@techi-freki @Techi-Freki

### What happened?

Every time I click on the applet, the menu is not displayed and this message appears in `~/.xsession-errors`:

```
(cinnamon:2309): Gjs-CRITICAL **: 02:30:49.823: JS ERROR: TypeError: direction is undefined
create@/home/claude/.local/share/cinnamon/applets/moonphase@techi-freki/js/ui/elements/riseSetElement.js:29:36
_createStandardLayout@/home/claude/.local/share/cinnamon/applets/moonphase@techi-freki/js/ui/riseSetUi.js:97:24
create@/home/claude/.local/share/cinnamon/applets/moonphase@techi-freki/js/ui/riseSetUi.js:41:18
rebuild@/home/claude/.local/share/cinnamon/applets/moonphase@techi-freki/js/ui/elements/uiElement.js:21:14
buildMenu@/home/claude/.local/share/cinnamon/applets/moonphase@techi-freki/js/menu.js:19:19
buildPopupMenu@/home/claude/.local/share/cinnamon/applets/moonphase@techi-freki/js/moonPhase.js:53:14
on_applet_clicked@/home/claude/.local/share/cinnamon/applets/moonphase@techi-freki/js/moonPhase.js:45:18
_onButtonPressEvent@/usr/share/cinnamon/js/ui/applet.js:284:18
```

**Comment by gruppler** [comment]
I'm getting the same error. I tried to debug it, but when I log `direction` it is not undefined, and it looks like it should work. It's also strange that the position in the error message seems to be off, since there are no references to `direction` there, but there are two in the preceding lines.

**Comment by Severga** [comment]
The same behavior after the update - no popup menu.

**Comment by gruppler** [comment]
Strange, mine is working now. I don't think I changed or updated anything.

**Comment by claudiux** [comment]
> Strange, mine is working now. I don't think I changed or updated anything. I did just replace my monitor, but I have no idea how that would have made a difference.

Mine now also works without changing anything. Maybe there's a problem with the phase calculation? I don't know.

**Comment by fredcw** [comment]
@gruppler 

>It's also strange that the position in the error message seems to be off, since there are no references to direction there, but there are two in the preceding lines.

I always find that the reported line is 2 lines more than the line the error occurred on. Seems to happen with all applet errors.

**Comment by Severga** [comment]
Still doesn't work if I fill in geolocation.

**Comment by claudiux** [comment]
> Still doesn't work if I fill in geolocation.

Can't reproduce this.

**Comment by Severga** [comment]
> Can't reproduce this.

Today it works. I don't know..

**Comment by claudiux** [comment]
Same error, again.

**Comment by Techi-Freki** [comment]
I think I've tracked down the issue. I'm not handling all the cases when it comes to the rise, set and transit times. I'm working out a solution in my free time.

**Comment by claudiux** [comment]
I've noticed that this bug appears only when "showRiseSet" is set to true.
