### ISSUE TITLE
[CinnVIIStarkMenu@NikoKrause] Incompatible with Cinnamon 3.4.x

### ISSUE THREAD

**Issue by viggy96** [linuxmint/cinnamon-spices-applets#619]
[Have you read the guidelines for contributing?]: <> (Before opening an issue, please read the guidelines for contributing linked above. Else the issue will be closed. Also don't forget to notify the author.)
@NikoKrause 
Applet is incompatible with the latest Cinnamon version (3.4.0)

**Comment by NikoKrause** [comment]
Yes I know. That's what the README says as well: https://cinnamon-spices.linuxmint.com/applets/view/281

I don't have Cinnamon 3.4 yet. As soon as I get Cinnamon 3.4, I'll test it and mark it as compatible with 3.4
