### ISSUE TITLE
Applet Bug - Better Backgrounds - Unsplash 404 - no pictures

### ISSUE THREAD

**Issue by vorlesehase** [linuxmint/cinnamon-spices-applets#6193]
### Applet version/Build date

1719803350

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Gefroce GTX 960 and Nvidia Driver 390.157

### Applet name and maintainer

better-backgrounds@simonmicro @simonmicro

### What happened?

Using "Unsplashe" as source for wallpaper produces an error 404:
"Could not download image (404)!"
All other source are working correctly. The website of Unsplash itself is working.
![unsplash404](https://github.com/linuxmint/cinnamon-spices-applets/assets/174995318/1377f304-9288-4e3f-81f1-4e53e648998c)

**Comment by simonmicro** [comment]
Known issue: https://github.com/simonmicro/better-backgrounds/issues/26

Please close this to reduce the spam of duplicates.

**Comment by vorlesehase** [comment]
Your wish is my command, master! ;) closed !
