### ISSUE TITLE
0dyseus@PopupTranslator: unmet dependencies

### ISSUE THREAD

**Issue by Ilis** [linuxmint/cinnamon-spices-applets#620]
@PopupTranslator

Applet warn about unmet dependencies and detailed error logged into glass.log.

glass.log doesn't content anything except "info".

xsel, xdg-utils, python-requests, python3-requests are installed.

[glass.log.txt](https://github.com/linuxmint/cinnamon-spices-applets/files/981340/glass.log.txt)

After reboot applet still won't work.

**Comment by Ilis** [comment]
@Odyseus

**Comment by Odyseus** [comment]
Hello, @Ilis.

Can't reproduce in neither version of Cinnamon supported by Popup Translator (2.8.8, 3.0.x, 3.2.x and 3.4.x).

Go to Popup Translator's Spices website, **READ the readme**, follow the instructions and close this issue.

**Comment by Ilis** [comment]
Hello there!

I've made everything step by step, but no success :(

ilis@deore ~ $ xsel --version
xsel version 1.2.0 by Conrad Parker <conrad@vergenet.net>
ilis@deore ~ $ xdg-open --version
xdg-open 1.1.0 rc3

ilis@deore ~ $ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> help("modules")
...
requests
...

**Comment by Odyseus** [comment]
> Go to Popup Translator's Spices website, READ the readme, follow the instructions and close this issue.

**Comment by Ilis** [comment]
Maybe version of python is a problem?

ilis@deore ~ $ which python
/usr/bin/python
ilis@deore ~ $ file /usr/bin/python
/usr/bin/python: symbolic link to python2.7
ilis@deore ~ $ 

ilis@deore ~ $ ls /usr/bin/pyth*
/usr/bin/python  /usr/bin/python2  /usr/bin/python2.7  /usr/bin/python3  /usr/bin/python3.5  /usr/bin/python3.5m  /usr/bin/python3m

**Comment by Ilis** [comment]
@Odyseus ,
do you mean it is not an issue or I should bugreport this issue at another place?

https://github.com/Odyseus/CinnamonTools ?

**Comment by Odyseus** [comment]
> I should bugreport this issue at another place?
> https://github.com/Odyseus/CinnamonTools ?

Exactly.

**Comment by Ilis** [comment]
It is not good idea about different places for groups of applets. But OK.
