### ISSUE TITLE
cinnamon-timer@jake1164: Sound alert not working

### ISSUE THREAD

**Issue by araujo2kg** [linuxmint/cinnamon-spices-applets#6202]
### Applet version/Build date

Version 1.3.1.0 (2024-04-20 12:02:26)

### Cinnamon version

Cinnamon 6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Intel, kernel 5.15.0-113-generic

### Applet name and maintainer

cinnamon-timer@jake1164 @jake1164

### What happened?

When the "Play a sound when time elapsed" option in Sound tab is activated and a timer ends, the default alert sound does not play and an error is displayed: 
![bug1](https://github.com/linuxmint/cinnamon-spices-applets/assets/146134442/7ea89ec7-c5ef-4bd6-a4ba-b8bdaa8f5ddb)
The directory and file exists and the path is correct, i did not modify anything.

### Other information

Fixed by installing the sox package

**Comment by serhiiKalchenko** [comment]
Yeah... that's works!
sudo apt install sox

**Comment by claudiux** [comment]
`apt install sox libsox-fmt-all`
