### ISSUE TITLE
Cinnamenu: Buttons that have been scrolled outside the menu can be activated

### ISSUE THREAD

**Issue by DokterKaj** [linuxmint/cinnamon-spices-applets#6219]
### Applet version/Build date

5.4.13

### Cinnamon version

6.2.2

### Distribution

Mint 22 BETA

### Graphics hardware *and* driver used

NVIDIA GeForce GTX and xserver-xorg-video-nouveau

### Applet name and maintainer

Cinnamenu@json @fredcw

### What happened?

When the menu is open, if you scroll down the application grid/list then click above the menu, it will launch the app that would be there if the menu was that large, despite the cursor not being within the menu. Hovering the cursor above the menu will also show tooltips if they are turned on.
As for the category list, if there are enough categories and you scroll down until some are outside the menu, clicking/hovering the cursor above the menu will switch the application grid/list to that category.

The expected behaviour is that hovering anywhere outside the menu should show nothing and clicking anywhere outside the menu should close it.

### Other information

Possibly related to a similar bug that occurs with the default menu applet: https://github.com/linuxmint/mint22-beta/issues/198

**Comment by fredcw** [comment]
Unfortunately, I don't know how to fix it. https://github.com/linuxmint/cinnamon/issues/11123
