### ISSUE TITLE
better-backgrounds@simonmicro: Bug

### ISSUE THREAD

**Issue by binyominzeev** [linuxmint/cinnamon-spices-applets#6227]
### Applet version/Build date

Updated on 2024-07-21 05:34:33

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Applet name and maintainer

better-backgrounds@simonmicro @simonmicro

### What happened?

No background updates since last applet update. Also, current background disappeared after first restart.

**Comment by binyominzeev** [comment]
(Two times I started it did not work, now it started worked again.)

**Comment by simonmicro** [comment]
Duplicate of https://github.com/linuxmint/cinnamon-spices-applets/issues/6193 / https://github.com/simonmicro/better-backgrounds/issues/26 ?

**Comment by rcalixte** [comment]
Duplicate of #6193
