### ISSUE TITLE
Applet Cinnamenu@json favorites sort opposite direction of standard menu

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#6278]
### Applet version/Build date

Version 5.4.14 (2024-07-25 15:35:42)

### Cinnamon version

Cinnamon 6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Intel UHD Graphics 620

### Applet name and maintainer

Cinnamenu@json @fredcw

### What happened?

The standard Cinnamon menu sorts the favorites one way top to bottom while the cinnamenu sorts the opposite direction.
I'm only calling this a bug because it's not standard.  The reversal is a headache due to muscle memory issues.  I always knew that the icon for Gimp was the 2nd down.   Nope, not now.

I love the app for the grid layout of the menu.  I can change the cinnamon.css to fix icon sizes etc but that only works for one theme, your app works for any theme. Not sure why I haven't seen this app before.

**Comment by fredcw** [comment]
I don't think I even noticed this before. In any case, you can rearrange the order using drag and drop in both applets so it shouldn't really make a difference. I set the order mainly for the sidebar at the bottom and left it in the same order for when it's at the side instead of reversing it.

**Comment by ChooChooAl** [comment]
If you think about it, it's on that list of 100 things to do when I have no time.   LOL
I'll leave it as is.  I'm getting used to it and I'm not sure I'll go back to the other (for now).   And sorting it would mean a resort if I did go back.   
Have a good one.
