### ISSUE TITLE
Applet Bugweather@mockturtl funktioniert seit Wochen nicht mehr, warum?

### ISSUE THREAD

**Issue by vlado-77** [linuxmint/cinnamon-spices-applets#6279]
### Applet version/Build date

weather@mockturtl funktioniert seit Wochen nicht mehr, warum?

### Cinnamon version

20.3

### Distribution

mint

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

weather@mockturtl funktioniert seit Wochen nicht mehr, warum?

### Other information

weather@mockturtl funktioniert seit Wochen nicht mehr, warum?

**Comment by rcalixte** [comment]
There is not enough information here for this to be actionable.
