### ISSUE TITLE
weather@mockturtl: Sun icon not showing anymore with tommorrow.io api

### ISSUE THREAD

**Issue by nikto1** [linuxmint/cinnamon-spices-applets#6281]
### Applet version/Build date

3.6.3

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

Since the last update (i think) the sun icon has gone on daily preview with the tommorrow.io api; only the moon icon is visible. no idea with other apis.

**Comment by Gr3q** [comment]
Hi,

- Are you using the applet's custom icons or your system icons?
- What is the name of your system icon-theme?
- Are you using symbolic icons in the applet settings?

**Comment by Gr3q** [comment]
They are not the custom icons but I also might've misunderstood the problem although for me it shows clear as sun.

Could you provide which Icons you are using by going to Settings->Themes->Switch on Advanced Settings momentarily (if you haven't done so before)?

You can also try using the custom icons by turning them on in the Applet settings->Other Options->Icons->Use custom icons* just to verify if it's a problem with your iconset or is is with tomorrow.io.

If the custom icons are also wrong then I need you (approximate) location you are using in the applet so I can recreate the issue on my end.

**Comment by Gr3q** [comment]
I see, for the daily forecast it used the timestamp provided for each day to get the icon should be day or night version.

For Rome (and for nothing else) the timestamp was during the night, so it was always showing night. I removed that logic it so daily forecast icons are always forced to be the day versions as it should be.

**Comment by Gr3q** [comment]
I'm trying to fix some other thing but maybe I should roll it out.

You can try it yourself with:
```
git clone https://github.com/Gr3q/cinnamon-spices-applets.git --branch 3-6-4
cd cinnamon-spices-applets/weather@mockturtl
./test.sh
```
