### ISSUE TITLE
[Sensors@claudiux] Feature Request - Vertically Align Sensors

### ISSUE THREAD

**Issue by tsposato** [linuxmint/cinnamon-spices-applets#6300]
### Applet name and maintainer

Sensors@claudiux @claudiux

### What would you like to see?

Is there any way to make the position of the applet configurable?
Just so I can make it vertically aligned with the other applets.
See here:
![image](https://github.com/user-attachments/assets/b72c0ef4-058d-4810-bdef-3ddd0abcb122)

**Comment by claudiux** [comment]
Thanks for this FR.
On my todo list!

**Comment by claudiux** [comment]
Please try v3.8.0.

**Comment by tsposato** [comment]
> Please try v3.8.0.

Hi, thanks for working on this so fast!
I'm using Version 3.8.0 (2024-08-19 04:42:00).
I don't see any difference or any new options to configure it? But looking at the commit I'm guessing it is supposed to automatically align vertically?

**Comment by tsposato** [comment]
Without Icon:
![image](https://github.com/user-attachments/assets/84b99bdc-3e5e-4b60-9916-b69dac59b9ae)

With Icon:
![image](https://github.com/user-attachments/assets/f5df96ad-cadb-4ef7-8980-fc97a20bb080)

**Comment by claudiux** [comment]
I'm trying to work on CSS, without success. Please set the character size to 100%.

**Comment by tsposato** [comment]
> I'm trying to work on CSS, without success. Please set the character size to 100%.

Even at 100% it is still slightly elevated.

100% and no icon:
![image](https://github.com/user-attachments/assets/6c6030aa-41b8-4394-a8a3-5994a58b98bf)

100% with an icon:
![image](https://github.com/user-attachments/assets/8b817ce9-87cd-4a44-8a79-e379a30dc6ed)

**Comment by claudiux** [comment]
I'm looking for a font that contains the characters temperature, fan, voltage. If you know of one, please let me know.

**Comment by tsposato** [comment]
Thanks!
