### ISSUE TITLE
[sound150@claudiux] Feature Request - Static Mute Icon when audio muted

### ISSUE THREAD

**Issue by tsposato** [linuxmint/cinnamon-spices-applets#6301]
### Applet name and maintainer

sound150@claudiux @claudiux

### What would you like to see?

When the audio is muted, allow the muted icon to stay, so at a glance you can tell whether your sound is muted or not.

**Comment by claudiux** [comment]
Done!

**Comment by tsposato** [comment]
> Done!

Thanks for this, I'm not sure if it's just me, but it seems like it works when I mute my input, or mute both input and output, but not when I just mute the output?

**Comment by claudiux** [comment]
It works on my computer muting the output.

**Comment by tsposato** [comment]
It's really strange for me, I get strange and weird results which I can't readily reproduce, depending on whether I mute via my keyboard mute, middle click on the icon, or mute from the icon or sound settings...
Sometimes when the sound is playing the mute icon is static and vice versa... not sure what is going on.
