### ISSUE TITLE
Icon shows the message "Dienst Fehler" which means "Service mistake"

### ISSUE THREAD

**Issue by thlkmoeller** [linuxmint/cinnamon-spices-applets#6311]
### Applet version/Build date

3.6.3

### Cinnamon version

5.2.7

### Distribution

20.3

### Graphics hardware *and* driver used

Intel Corporation Skylake GT2 [HD Graphics 520] [8086:1916] (rev 07), 4.6 (Core Profile) Mesa 21.2.6

### Applet name and maintainer

weather@mockturtl @Gr3q

### What happened?

After I tried to add a new city, the icon shows "Service mistake". When i type a city name in the search field, no city is found. the earlier added cities dont show the weather anymore.

### Other information

![grafik](https://github.com/user-attachments/assets/ebcfd401-969a-43bb-8159-eb0e53988f30)

**Comment by thlkmoeller** [comment]
Hello...Somebody here?

**Comment by Gr3q** [comment]
Hi, I was without a Cinnamon for more than 2 weeks.

I would still need at least some logs to see where it's going wrong?

is Auto location working? is providing coordinates instead of the city working?

**Comment by thlkmoeller** [comment]
Now, since there was an update to 3.6.4, I cannot provide anymore logs, since the problem has been solved.
The possibility of just entering coordinates was given in 3.6.3. 
Auto-location was working, but the result was not correct.
Now everything works like a charm again. Sorry for now not being able to provide more details anymore.

**Comment by Gr3q** [comment]
If it's working then it's ok.
