### ISSUE TITLE
Sensors@claudiux: information about disk temperature, fan speed and battery voltage does not show on mouseover tooltip

### ISSUE THREAD

**Issue by pxcandeias** [linuxmint/cinnamon-spices-applets#6353]
### Applet version/Build date

Version 3.8.0 (2024-08-18 19:42:00)

### Cinnamon version

Cinnamon 6.2.9

### Distribution

Linux Mint 22 Cinnamon

### Graphics hardware *and* driver used

Dual graphics Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] and NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (NVIDIA on demand) using nvidia-driver-535 (version 535.183.01-0ubuntu0.24.04.1)

### Applet name and maintainer

Sensors@claudiux @claudiux

### What happened?

Dear @claudiux,

In my laptop, the information about disk temperature, fan speed and battery voltage does not show on mouseover tooltip when selected in the applet configuration, only the temperature in the PCI and ACPI adapters show. I am pasting below a few screenshots to illustrate the configuration of the applet and then to show that the disk temperature, fan speed and battery voltage are not visible on the mouseover tooltip.

![Captura de ecrã de 2024-08-29 11-41-04](https://github.com/user-attachments/assets/38ab8974-5f9d-40c5-a1c1-f384dbc9f269)

![Captura de ecrã de 2024-08-29 11-46-17](https://github.com/user-attachments/assets/f85fd8b5-fa47-41be-8333-bd9aadc588d8)

![Captura de ecrã de 2024-08-29 11-46-58](https://github.com/user-attachments/assets/cb720f28-37b9-484b-a60f-cf73b7905df5)

![Captura de ecrã de 2024-08-29 11-47-24](https://github.com/user-attachments/assets/77a482fb-601f-4a04-8b35-3caf8f1ce2bc)

![Captura de ecrã de 2024-08-29 11-47-50](https://github.com/user-attachments/assets/66a2519c-aa42-4d6d-99ba-00a88f764ad9)

![Captura de ecrã de 2024-08-29 11-50-27](https://github.com/user-attachments/assets/f78fe77c-fd39-42b9-a149-39c15ebecfaf)

![Captura de ecrã de 2024-08-29 11-49-10](https://github.com/user-attachments/assets/8081b1ad-2f60-4c78-b06a-a156b4420ace)

**Comment by claudiux** [comment]
Thank you for reporting this issue. I will look into it.

**Comment by claudiux** [comment]
Oh yes, that's true. When no sensor is displayed on the panel, no more sensor (of same type) is displayed in the tooltip. I'll try to solve this problem.

**Comment by pxcandeias** [comment]
Maybe it is an edge case but I already have a large number of applets running and filling the notification area in the panel, so I was looking to have minimal information on your applet (the CPU temperature) and leave all the rest for the mouseover tooltip. Thank you for looking into this.

**Comment by claudiux** [comment]
Solved! I'll make a PR soon.

**Comment by pxcandeias** [comment]
Thank you @claudiux . Now it works as expected, at least for me.
