### ISSUE TITLE
Allow to set wallpapers for the light and dark mode

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/cinnamon-spices-applets#6354]
### Applet name and maintainer

auto-dark-light@gihaume @guillaume-mueller

### What would you like to see?

It would be nice to set wallpapers for the light and dark modes as well.

**Comment by guillaume-mueller** [comment]
It is not something I'm overly interested in so please let me know more precise specifications.

**Comment by anaximeno** [comment]
You can control the background through gsettings values.

- To get the background:
  ```
  gsettings get org.cinnamon.desktop.background picture-uri
  ```
- To set the background:
  ```
  gsettings set org.cinnamon.desktop.background picture-uri file:///path/to/file.extension
  ```

There are bindings to do this through CJS on applets:
```js
const Gio = imports.gi.Gio;

let backgroundSettings = new Gio.Settings({ schema_id: "org.cinnamon.desktop.background" });

// get background file path
let backgrounPath = backgroundSettings.get_string("picture-uri");

// set new background file
backgroundSettings.set_string("picture-uri", "file:///path/to/file.extension")
```

Its not something that I found to be very crucial as well, just an alternative option, so I wouldn't worry to include it yet as well. I might make a contribution with this in the future if you are open to it though.
