### ISSUE TITLE
Sensors@claudiux: Applet Bug

### ISSUE THREAD

**Issue by TheBongCoder** [linuxmint/cinnamon-spices-applets#6394]
### Applet version/Build date

3.8.2

### Cinnamon version

6.0.4

### Distribution

Linux Mint 21.3

### Applet name and maintainer

Sensors@claudiux @claudiux

### What happened?

Hello @claudiux, Here you can see , there is no data value showing up here
![Applet](https://github.com/user-attachments/assets/0202ae8c-0673-42e7-86e6-7f70a90e76f5)

### Other information

![Applet](https://github.com/user-attachments/assets/175ca1ba-133f-4b5c-8503-2525f3b48cbc)

**Comment by claudiux** [comment]
Hi @TheBongCoder 
It seems that this applet is not fully installed. Please remove it entirely, then reload it and re-install it, using System Settings -> Applets. Then reload Cinnamon (or log out / log in).

**Comment by claudiux** [comment]
@TheBongCoder 
Hi,
Any news about this issue?

**Comment by TheBongCoder** [comment]
Hii... thanks for reaching me out . I tried the things you have mentioned but it didn't worked out 
![image](https://github.com/user-attachments/assets/a74420ff-04da-4020-bc69-7ba80eb6dec3)

please check this image url

**Comment by claudiux** [comment]
Please try now: `sudo sensors-detect`. Add the returned modules at the end of `/etc/modules` then reboot computer and retry "Renew the list of sensors".

If that doesn't works, please copy here the output of the command `sensors -j`.

Thanx.

**Comment by TheBongCoder** [comment]
![image](https://github.com/user-attachments/assets/c7d38e38-fa2b-407e-b0dc-e56712c03e77)
i can't see fan related details here

**Comment by claudiux** [comment]
So, `sensors` can't detect your fans. Please try searching about "linux sensors "+YOUR_MOTHERCARD".
