### ISSUE TITLE
ScreenShot+RecordDesktop@tech71 don't work

### ISSUE THREAD

**Issue by muzena** [linuxmint/cinnamon-spices-applets#640]
This applet dosen't open Picture and Videos folder when they localized.
Screen capture also dosen't work, I think commands in bash script are invalid.

@NikoKrause 
I think this and ScreenShot@tech71 applet are "duplicate"
Difference between this two applets is, that this applet have screen capture possibility.

**Comment by NikoKrause** [comment]
Can you try localizing "Pictures" and "Videos" in applet.js?
I.e. `"xdg-open " + _("Videos")` and `"xdg-open " + _("Pictures")`

**Comment by NikoKrause** [comment]
or maybe using `"xdg-open “ + GLib.UserDirectory.DIRECTORY_PICTURES`

Need to test. Not sure if it will work.

**Comment by Odyseus** [comment]
Hello, everybody.

If you want to *kill three birds with one shot* (LOL), just use the following.

```javascript
// For the Pictures user folder
Main.Util.spawn_async(["xdg-open", GLib.get_user_special_dir(GLib.UserDirectory.DIRECTORY_PICTURES)], null);
// For the Videos user folder
Main.Util.spawn_async(["xdg-open", GLib.get_user_special_dir(GLib.UserDirectory.DIRECTORY_VIDEOS)], null);
```

1. Use of an asynchronous function.
2. No need to localize anything.
3. No need to insert spaces anywhere.

BTW, the **_()** declared in this applet only return strings from the applet's domain. And neither "Videos" nor "Pictures" are localized.

**Comment by muzena** [comment]
@Odyseus 
Do you know how to make 'notify-send' messages in line 83, 88, 95, 96 make localizable?

**Comment by NikoKrause** [comment]
@muzena 
https://github.com/linuxmint/cinnamon-spices-applets/compare/master...NikoKrause:ScreenShot+RecordDesktop-by-tech71?expand=1

This should do the trick

**Comment by muzena** [comment]
@NikoKrause 
Can you look for github-projects@morgan-design.com applet in line 45, 46, 47 
title: "GitHub Explorer",
title: "ERROR:: GitHub Explorer ::ERROR",
strings are not translatable.
I think this is similar as this in ScreenShot+RecordDesktop@tech71 applet

**Comment by NikoKrause** [comment]
@muzena 
You just need to wrap those Strings with underscore bracket, e.g. `_("GitHub Explorer")`

**Comment by NikoKrause** [comment]
@muzena 
I created a PR here https://github.com/linuxmint/cinnamon-spices-applets/pull/721 with some more improvements
