### ISSUE TITLE
power-profiles@rcalixte: Detect and notify on missing command

### ISSUE THREAD

**Issue by rcalixte** [linuxmint/cinnamon-spices-applets#6426]
### Applet name and maintainer

power-profiles@rcalixte @rcalixte

### What would you like to see?

If `power-profiles-daemon` isn't installed (check for `powerprofilesctl`), show a notification when the applet is activated that includes an option to open the README file. The "Open README" button should use the default text editor to launch the README file.

Ref: #6424

**Comment by anaximeno** [comment]
You could also put it to Open the Website (since it'll show up a formatted version of the README there) as well, the only issue is that this would only work when the user is online (which is expected if user uses the applet immediately after the installation).

**Comment by rcalixte** [comment]
Maybe two buttons? One for "Open README" and one for "Open Website"?
