### ISSUE TITLE
[SpicesUpdate@claudiux] Add option to ignore translation updates

### ISSUE THREAD

**Issue by igorsantos07** [linuxmint/cinnamon-spices-applets#6501]
### Applet name and maintainer

SpicesUpdate@claudiux @claudiux

### What would you like to see?

While I understand the importance of translations... In the end, we're only interested in the languages we use. And it's *very frequent* to get new translation updates on all spices and extensions and applets and whatnot. It gets quite annoying, very quickly, and right now we can either receive no notification at all, or everything.

Would it be possible to implement a filter to skip notifying about any change with "translation", "i18n", "t9n" and similar expressions? And then, maybe add a white-list of language keywords, I guess? haha

I might be willing to implement this, if you agree with the idea. I think I have enough Python knowledge, just could get lost with the settings UI. But it could be a fun way to get warmed up. Thoughts?

**Comment by claudiux** [comment]
@igorsantos07 
To make this effective, you'd need to download the zip containing the Spice, list its contents and compare them with those existing in the user's folder. 

If the only changes are .po files that don't interest us, then the update is not proposed. 

It's a lot of work for little gain. It doesn't seem like a very good idea, sorry. I don't plan to do that.

**Comment by igorsantos07** [comment]
I was thinking about a more basic blocklist/allowlist of words, basically, given there's no much room to innovate when you're describing "add Catalan translation" :man_shrugging: 

Inspecting the actual changes is definitely too much, but receiving daily notifications for translations you don't care about is quite detrimental for the overall system UX, don't you think?

**Comment by claudiux** [comment]
Contextual analysis based on the title alone seems questionable.

If certain titles leave no room for doubt, such as “Update es.po” or “Add Catalan translation”, what about “[Some improvements] and translation updates”?

This may even compromise the stability of the concerned Spice. I won't take that risk.

Regards
claudiux

**Comment by igorsantos07** [comment]
But anyway, thanks for the quick feedback and all activity around :D
