### ISSUE TITLE
Sound & Enhanced sound applets auto selecting everything but the right player...

### ISSUE THREAD

**Issue by ironhak** [linuxmint/cinnamon-spices-applets#6502]
### Applet version/Build date

Both last version

### Cinnamon version

Cinnamon 6.2.9

### Distribution

Mint 22

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Both Sound cinnamon applet and Enhaced sound continue to pick up every player but the one that is currently playing music... Really frutrating becasue everytime I want to control the music via the applet or keyboard I have to go back and select the right source... It keeps chaning even if there's only one source of sound...

Video example

https://github.com/user-attachments/assets/3da84017-4d99-4d7f-b9ae-7f6ad47218a4

### Other information

_On a side note_: why Enhaced sound applets takes up so much screen time compared to standard sound applet???

**Comment by claudiux** [comment]
Please use only one applet. When using the enhanced sound applet, you must remove the basic applet from the panel.

**Comment by claudiux** [comment]
I can't reproduce this problem.

**Comment by claudiux** [comment]
I'll try it.

**Comment by ironhak** [comment]
Hello, I think a found a way to reprocude:
- Open Brave browser (or any browser I guess)
- Go into a page where there is a video, or audio, player
- Play content, then pause it but do not close the tab.
- Open an audio/video player like audacious
- Play audio
- You'll see that even tough Brave is not playing and audacious is playing, the applet will switch to the browser every now and then, despite the fact that it's not playing anything.

**Comment by claudiux** [comment]
I see. Thanks for reporting this issue.

**Comment by claudiux** [comment]
The `playerctl metadata` command continues to display the browser data, even if another player is running.

I'll try to fix it, but it may be a playerctl bug.

**Comment by ironhak** [comment]
Perfect, thank you for mainting this and other amazing applets.

**Comment by claudiux** [comment]
This issue seems to have been solved.
