### ISSUE TITLE
Enhanced sound applet generating images files which fils disk space quickly

### ISSUE THREAD

**Issue by oleole39** [linuxmint/cinnamon-spices-applets#6504]
### Applet version/Build date

7.1.1 (2024-10-16 16:16:04)

### Cinnamon version

5.4.12

### Distribution

Mint 21

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Hello, 

When having a player opened (I noticed this with VLC and Celluloid playing videos), a picture is created every second or so in `/home/my_user/.config/sound150/arts/` with that kind of name `albumArt-55144413.png`.

It fills disk space quickly (like I guess 2gb in a few hours) and looks like a bug (the picture can't be previewed) that was not here in previous versions of the applet.

**Comment by claudiux** [comment]
@oleole39 Thanks for reporting this issue. I'll try to fix it soon.

**Comment by claudiux** [comment]
Done!
Improvements are planed.

**Comment by oleole39** [comment]
Thanks for the quick fix! I confirm it works here too. 
You mention improvements to come, so probably you've noticed that it currently still regenerates the same preview every few seconds (although now it delete previous one so they don't accumulate to fill the disk space). 

Are you intending to make it a live preview of the video in the applet window, i.e. generating a preview of the current video frame every few seconds ? If so, I wonder whether I would be happy to find such a feature in regards to SSD disk life expectancy which asks to limit writing (it is a small impact I believe, but all things added up...).

**Comment by claudiux** [comment]
Yes, these are the improvements I've planned.

**Comment by claudiux** [comment]
I no longer intend to preview the entire video in the applet window.

**Comment by claudiux** [comment]
If you like this applet, please add a star on https://cinnamon-spices.linuxmint.com/applets/view/306

**Comment by oleole39** [comment]
>  but when video has not tag providing its title.

I don't get what will happen in this case ?

> If you like this applet, please add a star on https://cinnamon-spices.linuxmint.com/applets/view/306

I've not only liked it, I've just re-liked it :)
 
![ksnip_20241018-205745](https://github.com/user-attachments/assets/0aafffd9-1871-460a-8ee3-ca6bd9484bb4)

**Comment by claudiux** [comment]
> > but when video has not tag providing its title.
> 
> I don't get what will happen in this case ?

A new image is created every 5 seconds. This seems transparent to the user.


> 
> I've not only liked it, I've just re-liked it :)
> 

Thank you very much!
