### ISSUE TITLE
Applet Bug - Sound icon in panel is always a musical note icon.

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#6513]
### Applet version/Build date

Version 7.2.2 (2024-10-19 04:54:52)

### Cinnamon version

Cinnamon 6.0.4 

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Intel UHD Graphics 620

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Latest update 10/19/24, the applet icon is always the musical note.  Will not change back to the sound icon.  
Log off and back on, restarting Cinnamon both do not solve the issue.

### Other information

Only change today is that update.
I had been watching a lot of cnn new and videos in Firefox browser for an hour or so, and after closing I saw the musical note in panel.
As stated, log off/on and cinnamon restart did no good, but complete reboot fix it.   I then tried CNN videos again and played music and caused a notification sound and the note did not show (except when playing).  Not sure what steps I did to get it to want to stay on persistently.

**Comment by claudiux** [comment]
@ChooChooAl 

CNN on:
![image](https://github.com/user-attachments/assets/24e14bde-7271-468b-98af-3dd470992b70)

After closing the CNN tab in Firefox:
![image](https://github.com/user-attachments/assets/7af6e58a-1c87-481a-8043-c85a185d88db)

There is no issue with my Cinnamon 6.2.9 (LM22).

I'll try on Cinnamon 6.0.4 (LM21.3).

**Comment by ChooChooAl** [comment]
I totally agree.   After I rebooted, those steps worked for me too.    I'm not sure the icon was a note from some other application of from Firefox.   
And yes, I'm still lagging back on Mint 21.3
Not sure what to say.  I was forwarding the info more in case you more feedback. 
If I can recreate this, I'll open it again if you want to close it.

**Comment by claudiux** [comment]
When any other firefox tab contains a video, the icon can still be a music note.

Thank you for reporting this issue, I'll take care of it.

**Comment by ChooChooAl** [comment]
I had closed Firefox, just FYI.

**Comment by claudiux** [comment]
This bug may be related to #6502.
