### ISSUE TITLE
[CassiaWindowList@klangman] Remove colored bands on non-active windows

### ISSUE THREAD

**Issue by torchipeppo** [linuxmint/cinnamon-spices-applets#6515]
### Applet name and maintainer

CassiaWindowList@klangman @klangman

### What would you like to see?

I've been checking out Cassia Window List to deal with my most cluttered moments, but one thing I've noticed is that it really likes the small colored band that Cinnamon's default window list reserves for the active/focused window. See the following screenshot:

![Screenshot from 2024-10-21 13-28-56](https://github.com/user-attachments/assets/cb547af1-7e08-4d71-bc73-3679d86ef7c6)
To the left of the separator is the default window list, to the right is Cassia.

I've gone through the settings, but I couldn't find an option to make the Cassia list look like the default one.
Am I missing something? If not, is it possible to have a setting to not highlight unfocused windows as much?

**Comment by torchipeppo** [comment]
Oh, in this case, sorry for the wrong label. I had based my assumption on [the screenshot on the Cinnamon Spices website](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/CassiaWindowList%40klangman/screenshot.png).

Anyway, I'm on Mint 21.3, Cinnamon 6.0.4

**Comment by klangman** [comment]
Oh... I see what you are talking about now.. This behavior is normal.  The "colored band" indicates that the application is running (shows the difference between not running pinned window-list buttons and running programs). The button highlighting shows the currently focused window. If you have no pinned buttons then all window-list buttons will have the "colored band" underlining. If you look at the website screenshot you linked to, you will see the pinned button for "Discord" (on the left, not currently running) shows up without the underlining. This is consistent with how the cinnamon grouped window-list works. 

I could consider changing the behavior so that when the "Pinning of window list buttons" option is set to "disabled" then the underlining will only apply to the focused window (the same way that the button highlighting currently works). Would that be something that you would be interested in?

**Comment by klangman** [comment]
> Your proposal sounds like a good solution.

OK.. I'll implement that in the next release.

> See the following screenshot, where button for the file manager, the only pinned one in this workspace, is still shown despite the pinning option being set to Disabled and no file manager windows being open in any workspace:

Ya, that looks like a bug to me.. I'll see if I can recreate that locally so I can fix that.

**Comment by klangman** [comment]
I was able to recreate the issue and fix it. Got some more things to do (including the work to only underline the focused window button when pinning is disabled) before I push the changes.

**Comment by klangman** [comment]
My github version (https://github.com/klangman/CassiaWindowList) now has the changes you asked for:

1. The fix the properly remove pinned buttons after disabling the pinning feature.
2. The feature to use the "active" style only for the focused window when pinning is disabled.

You can switch that version if you are in a hurry to get these changes, or you can wait for a few more days while I do more testing before I push the changes to cinnamon-spices.

**Comment by klangman** [comment]
The new version 2.3.7 should address this issue.

**Comment by torchipeppo** [comment]
Thank you very much!
I'm noticing another, possibly related "odd" behavior: if no window is currently focused, the window list still highlights the last non-minimized one that was in focus as though it is still focused. This happens regardless of the pinning setting. Is this intended?

Here's another reference screenshot, where there is no focused window (left: default grouped window list, middle: Cassia, right: default traditional window list)
![image](https://github.com/user-attachments/assets/1103e8ab-85f5-49da-b6de-14c0fec04d78)

And a minor point that came to me while making the screenshot: is it possible for the applet to know if it's on the top or bottom panel, and flip the arrow for minimized windows accordingly?

**Comment by klangman** [comment]
OK.. Version 2.3.8 was pushed to cinnamon spices which fixes the button highlighting when no window has the focus.

**Comment by torchipeppo** [comment]
It seems to work fine. Thanks again!
I expect that gathering opinions on the arrow direction will take a while more, and it's a little off-topic compared to the original request, so it might be best to close this issue for now. I'll leave the decision up to you.

**Comment by klangman** [comment]
I added a request for opinions in the cinnamon-spices comment section. Feel free to add your opinion there and I'll go with the consensus (assuming anyone else bothers to give an opinion). 

I guess we can close this issue now. I can't close it, I assume you can as the one that opened it?

**Comment by klangman** [comment]
@torchipeppo FYI. The minimized status indicator is now an "up arrow" character when the window-list is on the top panel. Version 2.3.9 has this change which was just merged.
