### ISSUE TITLE
Sensors@claudiux: Add cpu power consumption tab

### ISSUE THREAD

**Issue by fzamperin** [linuxmint/cinnamon-spices-applets#6518]
### Applet name and maintainer

Sensors@claudiux @claudiux

### What would you like to see?

@claudiux Thanks for this amazing Applet! Being using it for years!

I have a suggestion for a new Feature, I want to measure my CPU power consumption, I have a 13700K and I see that I can get the power consumption in Joules from: `/sys/class/powercap/intel-rapl/*/energy_uj`. At first I tried to tweak into `lm_sensors` to see if I can grab this value to make the Applet display it from `sensors` but it didn't work. Do you think we can work to make this happen? As of right now I just know about Raptor Lake consumption but I think other processors output the power different way.

Let me know if you find that this is interesting somehow. Thanks!

**Comment by claudiux** [comment]
@fzamperin 
Thanks for your interesting PR.
On my computer, access to this data requires root rights (with sudo). Is there any other way to get it?

**Comment by fzamperin** [comment]
I was doing some research but so far didn't find a way to fetch it :/

**Comment by fzamperin** [comment]
@claudiux After doing an extensive search it's not possible to catch the value without sudo privilege. Can we work this around? I don't know exactly the architecture and environment about applets on cinnamon but I'm willing to help with the implementation.

**Comment by claudiux** [comment]
All the solutions I envisage would create a safety problem. I prefer not to implement them. I'll keep thinking about it.

**Comment by fzamperin** [comment]
@claudiux After a quick research, I saw that only Intel cpus are supported using the PCM tool, do you want me to create a PR only for Intel? And then we can see how to support AMD or ARM?

Let me know your thoughts.

**Comment by claudiux** [comment]
@fzamperin Yes, but please only display these options when PCM tools are available and usable.

**Comment by claudiux** [comment]
No solution compatible with any architecture and without root rights has been found.
