### ISSUE TITLE
xsession installation question

### ISSUE THREAD

**Issue by MuhMuhGH** [linuxmint/cinnamon-spices-applets#6532]
### Applet version/Build date

v1.1.0~20241005

### Cinnamon version

6.2.9

### Distribution

Mint 22

### Graphics hardware *and* driver used

Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller

### Applet name and maintainer

xsession@claudiux @claudiux

### What happened?

When I run this:
username@T520i:~/Downloads/xsession@claudiux$ node applet.js 
I get this output:

home/username/Downloads/xsession@claudiux/applet.js:3
const Applet = imports.ui.applet; // ++
               ^

ReferenceError: imports is not defined
    at Object.<anonymous> (/home/username/Downloads/xsession@claudiux/applet.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49

Node.js v18.19.1

I got this far by installing various packages, but I've tried everything I can think of. I also tried running the applet.js file in Firefox, but I got this:

Uncaught ReferenceError: imports is not defined
    <anonymous> debugger eval code:3

Ok, so after tearing what's left of my hair out, what should I do?

**Comment by claudiux** [comment]
@MuhMuhGH 
Hi,

This is not the right way to install an applet on Cinnamon, which doesn't use node.

You have downloaded and extracted the zip file in `~/Downloads`. OK.

Please now run these commands:
```
cd ~/Downloads
mv xsession@claudiux ~/.local/share/cinnamon/applets/
```

Then, right-click on the panel and chose Applets. Select xsession@claudiux then [+].

You can now configure and use this applet.

**Comment by claudiux** [comment]
The best way to Download and Manage applets is to use the two tabs in Menu -> Preferences -> Applets.
