### ISSUE TITLE
Document use of Nvidia nvidia-smi feature

### ISSUE THREAD

**Issue by JEleniel** [linuxmint/cinnamon-spices-applets#6541]
### Applet name and maintainer

Sensors@claudiux @claudiux

### What would you like to see?

Add instructions to the documentation for Nvidia video card temperature readings:

The applet will now automatically detect the existence of the *nvidia-smi* tool version 550.107.02 or higher, test to ensure that the tool is compatible, and if so will present the Nvidia GPU temperature sensors. The applet will log an *info* entry if the tool is found and works, or an *error* entry if the tools is found and fails.

The *nvidia-smi* tool is part of the Nvidia closed source drivers, and only supports ["NVIDIA's Tesla, Quadro, GRID and GeForce devices from Fermi and higher architecture families"](https://docs.nvidia.com/deploy/nvidia-smi/index.html). While the tool does report fan speed, it does so as a percentage so is not compatible with the fan speed features of the applet.

When requesting help with this feature, please include the output of `nvidia-smi -L` as well as any entries in the '~/.xsession-errors' file related to 'Nvidia SMI'.

**Comment by claudiux** [comment]
> While the tool does report fan speed, it does so as a percentage so is not compatible with the fan speed features of the applet.

Please give here an example of output about this percentage, using the button in the General tab of this applet settings.

Also give a capture of the Fan sensors list (in the Fan tab).

**Comment by JEleniel** [comment]
Thank you for updating the README! I was planning to take care of that today. 

NVIDIA provides a management interface for their cards which they expose through a C library - the NVIDIA Management Library (NVML) - and several tools. The *nvidia-smi* and *nvidia-settings* tools are both capable of reading the fan speed. The *smi* tool only reports the percentage of "silent" speed as set by the drivers, and can report over 100%. The *settings* tool supports reading the fan speed in RPM, but it also consumes significant CPU doing so. 

Here is the output of the *nvidia-smi` tool:

```shell
jeleniel@localhost:~$ nvidia-smi --format=csv --query-gpu=name,pci.bus_id,temperature.gpu,fan.speed
name, pci.bus_id, temperature.gpu, fan.speed [%]
NVIDIA GeForce GTX 1080, 00000000:29:00.0, 48, 0 %
```
I am not injecting the fan speed into the sensor data, so it will not show in the applet's example. This is the output of the applet, trimmed to the NVIDIA related parts:

```json
{
	"temps": {
		...,
		"NVIDIA GeForce GTX 1080 00000000:29:00.0: temp1": {
			"input": "48"
		}
	},
	"fans": {
		...
	},
	"voltages": {
		...
	},
	"intrusions": {
		...
	}
}
```

And the screenshot you requested:

![image](https://github.com/user-attachments/assets/fb896100-80b0-4794-b2b1-f9b850e19946)

**References**

- [NVIDIA Management Library(NVML)](https://developer.nvidia.com/management-library-nvml)
- [nvidia-smi - NVIDIA System Management Interface program](https://docs.nvidia.com/deploy/nvidia-smi/index.html)
- [nvidia-settings](https://manpages.org/nvidia-settings)

**Comment by claudiux** [comment]
From: https://www.reddit.com/r/nvidia/comments/kdjdjz/nvidiasmi_linux_how_to_get_fan_rpm_not_speed/

You can have a look at [NVIDIA Management Library (NVML)](https://developer.nvidia.com/nvidia-management-library-nvml)
nvmlUnitGetFanSpeedInfo API should return you fan speed **in rpm** via nvmlUnitFanInfo_t structure.
This is a C library. It has official Perl and Python bindings.
