### ISSUE TITLE
Applet Bug

### ISSUE THREAD

**Issue by GalacticSun** [linuxmint/cinnamon-spices-applets#6547]
### Applet version/Build date

1.2.1

### Cinnamon version

6.2.9

### Distribution

Mint 22

### Graphics hardware *and* driver used

Intel Iris 5200 Pro

### Applet name and maintainer

auto-dark-light@gihaume @guillaume-mueller

### What happened?

My custom script is not functioning 100%.  It is intended to change the skin for Audacious music player using `audtool`, but that line doesn't seem to execute properly.  The line in question is `audtool config-set skins:skin "/usr/share/audacious/Skins/Default"` (and `audtool config-set skins:skin "/usr/share/audacious/Skins/Classic"`).

The script works fine and does change Audacious' skin okay when run on the command line, but not when run as a custom command through the applet.  And, again, it is only that one line that isn't working - the rest of the script does function fine when run through the applet.

Thanks for any help, @guillaume-mueller !

Script:
```
#!/bin/bash

# Get current theme
theme=$(gsettings get org.cinnamon.theme name)
#echo "Current theme is $theme"


if [ $theme = "'Mint-Y-Aqua'" ]; then
    # Set light coloured panel icon for timer applet
    cp ~/timer_cinnamon_applet_stylesheet_light.css ~/.local/share/cinnamon/applets/cinnamon-timer@jake1164/3.4/stylesheet.css

    # Change Audacious media player theme and restart it to apply the change (from https://redmine.audacious-media-player.org/boards/1/topics/3001?r=3004)
    playback_status=$(audtool --playback-status)
    #echo $playback_status

    audtool config-set skins:skin "/usr/share/audacious/Skins/Classic"

    audtool --playback-pause
    audtool --shutdown

    if [ $playback_status = "playing" ]; then
        audacious -p &  # Start Audacious playing since it was playing when it was stopped
    else
        audacious &
    fi
else
    # Set dark coloured panel icon for timer applet
    cp ~/timer_cinnamon_applet_stylesheet_dark.css ~/.local/share/cinnamon/applets/cinnamon-timer@jake1164/3.4/stylesheet.css

    # Change Audacious media player theme and restart it to apply the change (from https://redmine.audacious-media-player.org/boards/1/topics/3001?r=3004)
    playback_status=$(audtool --playback-status)
    #echo $playback_status

    audtool config-set skins:skin "/usr/share/audacious/Skins/Default"
    
    audtool --playback-pause
    audtool --shutdown
    
    if [ $playback_status = "playing" ]; then
        audacious -p &  # Start Audacious playing since it was playing when it was stopped
    else
        audacious &
    fi
fi
```

**Comment by GalacticSun** [comment]
**UPDATE:**  Well, this issue only seems to occur when Audacious is _playing_ audio when I run the applet.  When Audacious is stopped, the skin does get changed okay.

**Comment by guillaume-mueller** [comment]
So what happens ? The skin doesn't change ?

Please minimize any reproducible example you provide.

On my setup this in a terminal doesn't always reopen audacious:
```bash
audtool --shutdown
audacious &
```

But this does work reliably:
```bash
audtool --shutdown
sleep 1
audacious &
```

**Comment by GalacticSun** [comment]
Thanks, that appears to have fixed it.

The issue was that the skin wasn't changing to the new one when Audacious was playing audio, but it would change correctly when not playing audio.

Thanks again.
