### ISSUE TITLE
Applet Bug - Drawer (show/hide applets)

### ISSUE THREAD

**Issue by ironhak** [linuxmint/cinnamon-spices-applets#6559]
### Applet version/Build date

Updated on 2024-07-10 02:42:07

### Cinnamon version

6.2.9

### Distribution

Mint 22

### Applet name and maintainer

show-hide-applets@mohammad-sn @mohammad-sn

### What happened?

Sometimes the applet does not work, meaning that it does not hide other applets. Usually this happens when I reboot my machine. 
For me, strangely, a reboot does not fix, I have to shutdown and then turn on again in order to make it work again. 

### Other information

Unfortunately I've not found yet a consisten way to replicate the bug, it just happens at a random reboot.

**Comment by ironhak** [comment]
@claudiux 
Still not working.
![](https://i.imgur.com/skUGZ1M.mp4)

**Comment by claudiux** [comment]
What are your settings? Mine are:

![image](https://github.com/user-attachments/assets/d05c151a-bdc4-4724-beca-3d3aecbc10b3)

**Comment by ironhak** [comment]
@claudiux 
![image](https://github.com/user-attachments/assets/a3113980-541e-44e3-9951-d465b42b0acd)

![image](https://github.com/user-attachments/assets/c87de4a9-5e72-492d-9df4-0b11f6020def)

**Comment by claudiux** [comment]
Please try moving this one to the right side of this applet.
![image](https://github.com/user-attachments/assets/fcc3c045-8810-4672-ab66-6c70712dd3f8)

**Comment by claudiux** [comment]
@ironhak 
Any news?
Please indicate here the contents of your `~/.xsession-errors` file when this error occurs.

**Comment by claudiux** [comment]
Re-closed due to lack of information.

**Comment by claudiux** [comment]
> 
> My hypothesis is that if somehow an application set as hidden in the applet, loads before the applets itself then it causes the bug.

Hmm. Maybe. I'll do some tests.

**Comment by claudiux** [comment]
Please try with version `2024-11-28 18:03:31`.

**Comment by ironhak** [comment]
@claudiux 

> This icon is from an application called Solar, I have it on my Startup Application list and what I noticed is that it was the only one that had no delay on startup, so I set a 3s delay and I haven't experienced the bug since.
> My hypothesis is that if somehow an application set as hidden in the applet, loads before the applets itself then it causes the bug.

Since this "tweak" I've no experience the bug anymore.
