### ISSUE TITLE
[calendar@ccprog] - Add control over when to call Enrico service 

### ISSUE THREAD

**Issue by oleole39** [linuxmint/cinnamon-spices-applets#6587]
### Applet name and maintainer

calendar@ccprog @ccprog

### What would you like to see?

Hello,

I appreciate the addition of non-working days to the calendar, however I noticed that currently it pings the Enrico service (e.g. https://kayaposoft.com/enrico/json/v2.0?action=getHolidaysForYear&year=2024&country=fra&holidayType=public_holiday) everytime the applet starts/restarts.
This is not so nice privacy-wise, and I believe not so useful since the data is not likely to be updated so often. It would be great to be able to set when Enrico should be called. Options I can think about:
- new geographic zone set (load data for new country code)
- new date set (if year is modified - load data for new year)
- monthly automatic update (or any other more appropriate period)
- now (manual trigger)

**Comment by oleole39** [comment]
> The applet should cache Enrico data for a period of 50 days before downloading new data.

Is it refreshed though if user sets time to a different year (after misconfiguration for instance) or change non-working days' locale in applet settings ?

**Comment by ccprog** [comment]
The atomic cache datasets contains data for one year for one geographic area. If locale or year are changed, a new dataset should be aquired, unless there is one already present in the cache with an age of less than 50 days. Old datasets remain in the cache.

If you are interested, check the file ~/.local/share/cinnamon/applets/calendar@ccprog/5.2/enrico.json. At a first glance, the problem seems to be that the cache file is written, but fails to be read correctly.

**Comment by ccprog** [comment]
Changing the year in system settings will not do anything, unless you open the applet. Applets get no notification of _global_ system setting changes, they have to read the setting on activation each time.

**Comment by ccprog** [comment]
Thank you for the report. The applet now will load only data it does not know yet, or data that has not been updated for more than 50 days. Customization by the user will not be implemented.

A pull request #6607 has been entered.

**Comment by oleole39** [comment]
Thanks for the quick fix, I confirm that after installing v.1.3.0 and reloading the applet Enrico service is not pinged anymore! 

> Applets get no notification of _global_ system setting changes, they have to read the setting on activation each time.

Do you mean that for such case, user should disable and re-enable the applet ?

**Comment by ccprog** [comment]
No, just open it.
