### ISSUE TITLE
power-profiles@rcalixte: Add support for TuneD

### ISSUE THREAD

**Issue by rcalixte** [linuxmint/cinnamon-spices-applets#6613]
### Applet name and maintainer

power-profiles@rcalixte @rcalixte

### What would you like to see?

Implement proper support for [TuneD](https://github.com/redhat-performance/tuned) via DBus.

cc @hansingt

**Comment by hansingt** [comment]
I'm not sure, whether I get this issue right, but as I've already mentioned, TuneD provides a compatibility API for applications using PPD. 

Thus, in first place, it would be enough to make it work,even though PPD is not installed and maybe check whether the required APIs are available instead, if that is possible.

In future releases, direct support for TuneD might be a good idea though.
