### ISSUE TITLE
[sound150@claudiux] Volume control step size varies

### ISSUE THREAD

**Issue by nicknugget** [linuxmint/cinnamon-spices-applets#6622]
### Applet version/Build date

Version 7.2.4 (2024-11-21 16:01:23)

### Cinnamon version

6.2.9

### Distribution

Linux Mint 22

### Graphics hardware *and* driver used

AMD Radeon 780M,  radeonsi, gfx1103_r1, LLVM 17.0.6, DRM 3.57, 6.8.0-49-generic

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

I have been using the applet for a while now. The reason for this is that the standard step size of 5% for the volume control is too coarse for me. Thanks to the applet, 1% increments are now also possible. But unfortunately not always. Sometimes the step size is suddenly 5% again when increasing, but 1% when decreasing. And sometimes the other way round. Up 1%, down 5%. Unfortunately, the error cannot be reproduced properly. Sometimes reloading the applet helps, sometimes not. 

### Other information

My system:

Kernel : Linux 6.8.0-49-generic (x86_64)
Version : #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 4 02:06:24 UTC 2024
C-Library : GNU C Library / (Ubuntu GLIBC 2.39-0ubuntu8.3) 2.39
Distribution : Linux Mint 22

**Comment by claudiux** [comment]
This issue was already encountered and solved:

1. Open the Shortcuts tab of this applet settings.
2. Check "Redefine Multimedia Keyboard Shortcuts".
3. Click on "Use the same shortcuts as those defined by Cinnamon".
4. Eventually, restart Cinnamon.

**Comment by S3NTYN3L** [comment]
This issue is still present here in 7.3.3 on Mint 22 w/ Cinnamon 6.2.9.

**Comment by claudiux** [comment]
With which another applets, desklets, extensions? Which players?

**Comment by S3NTYN3L** [comment]
No other applets, desklets or extensions running other than the default from install.
It's doing this intermittently even just sitting on the desktop with nothing open.
I mostly having audio running through Waterfox or mpv.
CTRL+ALT+ESC (restart Cinnamon) fixes it sometimes, but mostly not today.
FWIW, it seemed to be working just fine after I updated when you fixed that OSD mute issue a few days back.
