### ISSUE TITLE
sound150@claudiux displays volume control popup on every cinnamon start/restart

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#6655]
### Applet version/Build date

Version 7.2.4 (2024-11-28 12:03:58)

### Cinnamon version

Cinnamon 6.2.9

### Distribution

OS: Linux Mint 22 x86_64

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Every time cinnamon is restarted or started, like boot and login, the sound icon and volume level pop up for a few seconds.  Software updates, applets specifically, when Cinnamon is restarted.

I call it a bug only because it's a bit annoying.  <br>
![Sound popup](https://github.com/user-attachments/assets/da12b57e-574c-4a09-8be5-e7df4030b40e)

**Comment by claudiux** [comment]
Solved! I'll do a PR soon.
