### ISSUE TITLE
sound150 not working on Cinnamon 6.4

### ISSUE THREAD

**Issue by mben42** [linuxmint/cinnamon-spices-applets#6656]
### Applet version/Build date

6.17.1

### Cinnamon version

6.4.0

### Distribution

Manjaro

### Graphics hardware *and* driver used

AMD Radeon RX 6800 and amdgpu

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Applet is no longer working after update to Cinnamon 6.4.

**Comment by claudiux** [comment]
Hi @mben42 

Please update this applet to its latest version, Version 7.3.0 (2024-11-30 18:40:02).

Your version 6.17.1 (2024-06-09) is 6 months old.

**Comment by mben42** [comment]
Thank you, I didn't see I had to update manualy…

**Comment by claudiux** [comment]
Open Applets in Cinnamon Settings, select the Download tab then sort theses applets by Upgradable. So, you can upgrade all your too old applets.
Or use the Spices Update applet.
