### ISSUE TITLE
Sound150 Applet not showing OSD when Mute toggled

### ISSUE THREAD

**Issue by S3NTYN3L** [linuxmint/cinnamon-spices-applets#6669]
### Applet version/Build date

7.3.1

### Cinnamon version

6.2.9

### Distribution

Mint 22

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Volume up/down with a step of 2 and shortcuts set to match Cinnamon seems to be working fine with Cinnamon OSD but toggling Mute on/off does not.
It does toggle the tray icon, but that's small and barely noticeable, however.
How can I get Mute to fire the OSD like Volume up/down does again?

**Comment by claudiux** [comment]
@S3NTYN3L Done!
