### ISSUE TITLE
[show-hide-applets@mohammad-sn] applet keeps hanging time after time

### ISSUE THREAD

**Issue by 666xan666** [linuxmint/cinnamon-spices-applets#6674]
### Applet version/Build date

2024-11-28 18:03:31

### Cinnamon version

6.2.9

### Distribution

Mint 22

### Graphics hardware *and* driver used

RTX4090

### Applet name and maintainer

show-hide-applets@mohammad-sn @mohammad-sn

### What happened?

Hanging whole time (even after recent update) on vertical panel showing all icons with "arrow" which is not clickable. Hanging right away even after applet restart. 

### Other information
![obraz](https://github.com/user-attachments/assets/b533dec5-4019-45db-98e2-9dd34352a0eb)

_No response_

**Comment by claudiux** [comment]
Same settings. I can't reproduce this issue with Cinnamon 6.4.2. I'll try with 6.2.9.

**Comment by claudiux** [comment]
@666xan666 
Can you list the applets/applications hidden by this applet, please?

**Comment by claudiux** [comment]
Maybe the cause is Discord having a notification, and asking to be displayed?

**Comment by claudiux** [comment]
I can't reproduce this issue with Cinnamon 6.2.9.

**Comment by 666xan666** [comment]
> @666xan666 Can you list the applets/applications hidden by this applet, please?

Heroic Game Launcher, KeePassXC, Steam, BT, System Updates, Warpinator, Mailnag, QRedshift, Flameshot.

**Comment by 666xan666** [comment]
FOUND ROOT CAUSE: This plugin interfere with **Flameshot** tray icon.

**Comment by claudiux** [comment]
@666xan666 So, the solution is to remove Flameshot from this applet. So, I close this issue.

**Comment by PlasmaMiasma** [comment]
EasyEffects 8.0.0 interferes with this applet.

(Linux Mint 22.2, Cinnamon 6.4.8, X11)
