### ISSUE TITLE
Radio3.0

### ISSUE THREAD

**Issue by archiebug** [linuxmint/cinnamon-spices-applets#6689]
### Applet version/Build date

2.5.0

### Cinnamon version

6.4.2

### Distribution

Archlinux

### Applet name and maintainer

Radio3.0@claudiux @claudiux

### What happened?

The last update causes some issues with the Radio menu.  The menu jumps around it makes it interesting to select a radio station. Also, the menu expands in a way that it goes over to my second monitor.

It seems like this [Stations are displayed beside their category. (Forced.)] and the favorites  are the cause.

I found the single column of stations easier to navigate.  

![Screenshot from 2024-12-15 14-48-49](https://github.com/user-attachments/assets/5db93726-37a6-40cc-9e8a-f6a37f434016)

Thanks-

**Comment by claudiux** [comment]
Hi @archiebug 
Thank you for reporting this issue. I'm working on it.

**Comment by naryfa** [comment]
Yeah, hit me hard too when I popped it open lol.

**Comment by claudiux** [comment]
Done with #6691. I hope you'll like it.

**Comment by archiebug** [comment]
> Done with #6691. I hope you'll like it.

looks good! Thank you. :)
