### ISSUE TITLE
Panel icon is a musical note all the time.

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-applets#6690]
### Applet version/Build date

Version 7.3.3 (2024-12-12 09:17:11)

### Cinnamon version

Cinnamon 6.2.9

### Distribution

Linux Mint 22 x86_64

### Graphics hardware *and* driver used

Intel UHD Graphics 620

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Newest update:  The panel icon is a musical note.
I have to click on the applet and select 'reload this applet' to make the sound icon reappear.   This only last about 5 seconds and the musical note returns.   No music is playing.
![image](https://github.com/user-attachments/assets/f6a6c776-c643-4813-9e1e-b1cb71f0a685)

**Comment by claudiux** [comment]
Your browser may be open on a paused video or sound.

**Comment by ChooChooAl** [comment]
I didn't think so but it's now showing now, even after a youtube video.

**Comment by claudiux** [comment]
What does this command return when the bug appears?
`playerctl -a metadata`

**Comment by ChooChooAl** [comment]
I started Youtube and it turned off when I closed firefox.
Now when I started firefox again to post this message, it showed up again.   
The playerctl command returns "No players found".

**Comment by claudiux** [comment]
Oh, a random bug! I love them! (No, it's a joke.)

Are you using an app like espeak or speech-dispatcher? Please verify your applications launched at start-up, in the System Settings.

**Comment by ChooChooAl** [comment]
Nothing like that.   I got it again and ran that playerctl command and got the same "no players" message.
I was playing many sound files with Audacious and playing with editing and playing a few in audacity.   After 20 minutes doing that I noticed the note icon.    IIRC an Alt-F2 R took care of it.     I had to reboot not for this reason and all is fine now of course.

After I reset the icon I try playing sounds, etc, etc, and it just won't reproduce.   I've got a full day of play time tomorrow so I'll try to keep and eagle eye out and see if I can see exactly when it sticks.

I do know unless there is more input from others this is next to impossible to fix if it can't be reproduced.  
Chat later I'm sure.

**Comment by claudiux** [comment]
What is the command to set the volume in rc.local?

**Comment by ChooChooAl** [comment]
This is the entire script:

#!/bin/bash
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# set volume about 60%
( sleep 10 ; amixer sset 'Master' 42500 ) &

# turn off bluetooth
( sleep 13 ; rfkill block bluetooth ) &

#cp /home/alan/.config/gtk-3.0/gtk-clean.css /home/alan/.config/gtk-3.0/gtk.css

#killall goa-daemon

exit 0

**Comment by claudiux** [comment]
You can comment the command about bluetooth and use the bluetooth app: right-click on bluetooth icon on panel, then "Deactivate".

I will add an option in "Enhanced Sound Applet" to set the volume at startup.

**Comment by ChooChooAl** [comment]
That's fine but I use that in other Systems like Zorin that isn't cinnamon based.

**Comment by claudiux** [comment]
So, you'll can uncheck this line in the list of applications launched at startup. I'll do a PR soon.

**Comment by claudiux** [comment]
Done.

**Comment by ChooChooAl** [comment]
Thanks for the sound settings.   Also haven't seen the note icon, so closing.
