### ISSUE TITLE
Cinnamenu@json: Can't open config window from applet context menu

### ISSUE THREAD

**Issue by eson57** [linuxmint/cinnamon-spices-applets#670]
**Reproduce:** Try to open configuration window from the applet context menu.
**Expected behaviour:** Cinnamenu configuration window opens
**Actual behaviour:** Nothing happens
**Consistently or intermittently:** ~~Consistently~~ Intermittently
**Cinnamon and Linux:** Linux Mint 18.1 (64 bit), Cinnamon 3.2.7

It's okay to access configuration window from Cinnamon Applets window

Edit:
After a while it suddenly started to work, I have no idea what happened.

**Comment by NikoKrause** [comment]
You should mention the author on GitHub by typing @ plus his/her username to trigger a notification and bring his/her attention to an issue or pull request.

You find the username of the author on the cinnamon spices website: https://cinnamon-spices.linuxmint.com/

**Comment by eson57** [comment]
@jaszhix

**Comment by eson57** [comment]
@NikoKrause 
Ok... I thougt that was what appname@author was for.

**Comment by NikoKrause** [comment]
No the uuid has not always the author in it's name.

**Comment by jaszhix** [comment]
Can you send a pastebin link with your ~/.xsession-errors and/or .cinnamon/glass.log?

**Comment by eson57** [comment]
I could, but there is nothing to see since I rebooted. Everything looks perfectly normal.
This must have been some temporary error on my system, because I haven't had the problem since the 5-8 first times I tried to open config window, then it suddenly just disappeared, and the applet have been working fine since then.

I think you can forget it until the error may appear again. In that case, I will immediately retrieve the logs.
Sorry to have bothered you with this.

**Comment by jaszhix** [comment]
Ah, glad its working for you then. I'll close this, but give me a mention and I'll reopen it if you find anything new about this.
