### ISSUE TITLE
Applet Bug

### ISSUE THREAD

**Issue by naryfa** [linuxmint/cinnamon-spices-applets#6703]
### Applet version/Build date

Version 7.3.4 (2024-12-21 16:45:19)

### Cinnamon version

6.2.9

### Distribution

Linux Mint 22 Cinnamon

### Graphics hardware *and* driver used

Intel Iris Plus Graphics 655

### Applet name and maintainer

sound150@claudiux @claudiux

### What happened?

Every other system reboot the Enhanced Sound applet will jump by 5% (I have it set to 1%) when using keyboard media keys (Logitech K780). 

Is there a way I could troubleshoot that and find out if anything is affecting the volume control?

The only two other applets I use are: Radio3.0 (Radio3.0@claudiux) and Weather (weather@mockturtl) Version 3.6.4; but when I disabled them, the same thing kept happening, so I doubt they impinge on the proper behavior of Enhanced Sound

**Comment by claudiux** [comment]
Hi @naryfa,

This issue was already encountered and solved:

1. Open the Shortcuts tab of this applet settings.
2. Check "Redefine Multimedia Keyboard Shortcuts".
3. Click on "Use the same shortcuts as those defined by Cinnamon".
4. Eventually, restart Cinnamon.

**Comment by naryfa** [comment]
This has worked. Thank you and sorry for not finding it.

**Comment by claudiux** [comment]
No problem. I should write a message asking the user to do that when the volume step takes a value other than 5%.
