### ISSUE TITLE
CPU sensor not available

### ISSUE THREAD

**Issue by ritzy-fox** [linuxmint/cinnamon-spices-applets#6707]
### Applet version/Build date

3.9.0 (2024-11-25 12:38:44)

### Cinnamon version

6.2.9

### Distribution

Mint 22

### Graphics hardware *and* driver used

AMD Ryzen 9 5950X

### Applet name and maintainer

Sensors@claudiux @claudiux

### What happened?

The CPU temperature sensor is not available in the list of temperature sensors in the applet's configuration.

`$ sensors -v`
`sensors version 3.6.0 with libsensors version 3.6.0`

Example of sensor values of this computer
```
{
	"temps": {
		"ISA adapter asusec-isa-0000: Chipset": {
			"input": 46
		},
		"ISA adapter asusec-isa-0000: Motherboard": {
			"input": 26
		},
		"ISA adapter asusec-isa-0000: T_Sensor": {
			"input": -40
		},
		"ISA adapter asusec-isa-0000: VRM": {
			"input": 34
		},
		"ISA adapter asusec-isa-0000: Water_In": {
			"input": -40
		},
		"ISA adapter asusec-isa-0000: Water_Out": {
			"input": -40
		},
		"PCI adapter nvme-pci-0100: Composite": {
			"input": 31.85,
			"max": 81.85,
			"min": -273.15,
			"crit": 84.85,
			"alarm": 0
		},
		"PCI adapter nvme-pci-0100: Sensor 1": {
			"input": 31.85,
			"max": 65261.85,
			"min": -273.15
		},
		"PCI adapter nvme-pci-0100: Sensor 2": {
			"input": 33.85,
			"max": 65261.85,
			"min": -273.15
		},
		"PCI adapter k10temp-pci-00c3: Tctl": {
			"input": 30.5
		},
		"PCI adapter k10temp-pci-00c3: Tccd1": {
			"input": 29.25
		},
		"PCI adapter k10temp-pci-00c3: Tccd2": {
			"input": 29.5
		},
		"NVIDIA GeForce RTX 3080 00000000:08:00.0: temp1": {
			"input": "31"
		}
	},
	"fans": {
		"ISA adapter asusec-isa-0000: CPU_Opt": {
			"input": 561
		},
		"ISA adapter asusec-isa-0000: Water_Flow": {
			"input": 0
		}
	},
	"voltages": {
		"ISA adapter asusec-isa-0000: CPU Core": {
			"input": 0.974
		}
	},
	"intrusions": {}
}
```

However, the CPU temp is available through several commands.

`$ sensors -j`
```
{
   "asusec-isa-0000":{
      "Adapter": "ISA adapter",
      "CPU Core":{
         "in0_input": 0.966
      },
      "CPU_Opt":{
         "fan1_input": 557.000
      },
      "Water_Flow":{
         "fan2_input": 0.000
      },
      "Chipset":{
         "temp1_input": 46.000
      },
      "CPU":{
         "temp2_input": 31.000
      },
      "Motherboard":{
         "temp3_input": 26.000
      },
      "T_Sensor":{
         "temp4_input": -40.000
      },
      "VRM":{
         "temp5_input": 34.000
      },
      "Water_In":{
         "temp6_input": -40.000
      },
      "Water_Out":{
         "temp7_input": -40.000
      },
      "CPU":{
         "curr1_input": 11.000
      }
   },
   "nvme-pci-0100":{
      "Adapter": "PCI adapter",
      "Composite":{
         "temp1_input": 31.850,
         "temp1_max": 81.850,
         "temp1_min": -273.150,
         "temp1_crit": 84.850,
         "temp1_alarm": 0.000
      },
      "Sensor 1":{
         "temp2_input": 31.850,
         "temp2_max": 65261.850,
         "temp2_min": -273.150
      },
      "Sensor 2":{
         "temp3_input": 33.850,
         "temp3_max": 65261.850,
         "temp3_min": -273.150
      }
   },
   "k10temp-pci-00c3":{
      "Adapter": "PCI adapter",
      "Tctl":{
         "temp1_input": 31.375
      },
      "Tccd1":{
         "temp3_input": 29.250
      },
      "Tccd2":{
         "temp4_input": 27.750
      }
   }
}
```

`$ sensors`
```
asusec-isa-0000
Adapter: ISA adapter
CPU Core:    761.00 mV 
CPU_Opt:      562 RPM
Water_Flow:     0 RPM
Chipset:      +46.0°C  
CPU:          +32.0°C  
Motherboard:  +26.0°C  
T_Sensor:     -40.0°C  
VRM:          +34.0°C  
Water_In:     -40.0°C  
Water_Out:    -40.0°C  
CPU:           5.00 A  

nvme-pci-0100
Adapter: PCI adapter
Composite:    +31.9°C  (low  = -273.1°C, high = +81.8°C)
                       (crit = +84.8°C)
Sensor 1:     +31.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +34.9°C  (low  = -273.1°C, high = +65261.8°C)

k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +31.9°C  
Tccd1:        +36.2°C  
Tccd2:        +27.8°C  
```

`$ xsensors`

![image](https://github.com/user-attachments/assets/5da6d8f5-cd6b-4a7e-8b68-ab9b006d3d08)
![image](https://github.com/user-attachments/assets/0f0070b5-8bfe-4bd1-8331-7845d9e0d594)
![image](https://github.com/user-attachments/assets/451f98be-3387-4acd-b36f-c2cf2fa15b03)

In `/etc/sensors.d/` there exists only an empty .placeholder file.

Would that be caused by a misconfig on my end or is it a bug?

**Comment by claudiux** [comment]
Hi @ritzy-fox 

Thank you for reporting this issue.

In the Temperature tab of this applet settings, what is the list of sensors? (Please include a screenshot.)

**Comment by ritzy-fox** [comment]
Hello claudix.

I thought about posting those screenshots in the original post, but I figured the "Example of sensor values of this computer" might be sufficient.

Regardless:

![image](https://github.com/user-attachments/assets/db73aafa-df30-4bcf-a41e-aa99044436cb)
![image](https://github.com/user-attachments/assets/7bf83390-6207-4c46-a095-168b330ba70f)

**Comment by claudiux** [comment]
Thank you. That's very strange! I'm trying to find out what's causing this bug.

**Comment by claudiux** [comment]
What about "asusec" in your `/etc/sensors3.conf` file?

**Comment by claudiux** [comment]
@ritzy-fox 

If there is nothing about "asusec" in your `/etc/sensors3.conf` file, please create the `/etc/sensors.d/asusec.conf` file containing:
```
chip "asusec-isa-*"
    ignore curr1
```

Then reboot your computer (not only restart Cinnamon).

Once logged in, go on the Temperature tab of this applet settings and click on the "Renew the list of sensors" button.

**Comment by ritzy-fox** [comment]
@claudiux 

There was nothing about "asusec" in `/etc/sensors3.conf`.

I followed your instructions and after rebooting I re-newed the available sensors in the applet's config and the CPU sensor appeared.
It works properly both in the tray as well as in the tooltip.

Thank you very much.

Would you mind elaborating on what just happened?
Was it a unique "me" problem or a bug that you will be able to patch?

**Comment by claudiux** [comment]
This applet is not currently designed to handle `curr` data (current in milliamperes). I therefore asked sensors to ignore this type of data, especially as `temp` and `curr` have the same name: CPU. This confusion has now been eliminated.

I will soon propose an update that will take these cases into account.

**Comment by ritzy-fox** [comment]
Ah, that's clear!
Thanks for the information.
I will close this issue, now.
