### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: Update to 1.6 applet crash

### ISSUE THREAD

**Issue by andreevlex** [linuxmint/cinnamon-spices-applets#678]
Hello @jaszhix.  I am installed updates applet to 1.6
```log
info t=2017-05-15T19:48:12Z Resized mintupdate.py with normalized size (22x22px)
error t=2017-05-15T19:50:41Z Failed to load prefs.json: GLib.FileError: Failed to open file '/home/andreevlex/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/prefs.json': No such file or directory Attempting to create it.
info t=2017-05-15T19:50:41Z Loaded applet multicore-sys-monitor@ccadeptic23 in 178 ms
info t=2017-05-15T19:50:41Z Loaded applet github-projects@morgan-design.com in 99 ms
error t=2017-05-15T19:50:41Z in onGraphRepaint: MyApplet.prototype.onGraphRepaint@/home/andreevlex/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/applet.js:243

error t=2017-05-15T19:50:42Z in onGraphRepaint: MyApplet.prototype.onGraphRepaint@/home/andreevlex/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/applet.js:243

error t=2017-05-15T19:50:42Z in onGraphRepaint: MyApplet.prototype.onGraphRepaint@/home/andreevlex/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/applet.js:243

error t=2017-05-15T19:50:43Z in onGraphRepaint: MyApplet.prototype.onGraphRepaint@/home/andreevlex/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/applet.js:243
```
File /home/andreevlex/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/prefs.json exists.

Cinnamon 3.2

**Comment by jaszhix** [comment]
Does it load for you? It will log that error before trying to create it.

**Comment by andreevlex** [comment]
after you add the are line of the form
```log
error t=2017-05-15T19:50:43Z in onGraphRepaint:
```
1 time per second when it tries to redraw the graph
statistics the tooltip is shown, but no graphs.

**Comment by jaszhix** [comment]
Do you have  gir1.2-gtop-2.0 installed? I wasn't able to reproduce this in 3.2 myself.

**Comment by andreevlex** [comment]
Yes, installed.
Update on the fly not working.
1. Removed the applet.
2. Restarted the system.
3. Installed the new version.

Works. 

Not for the first time encounter such a problem during the upgrade.

**Comment by xearonet** [comment]
HI.
I've tried this on fresh system (Cinnamon 3.4) and it crash every time.
[https://gist.github.com/xearonet/5aa193d5e12edb7eb69e384845411cd0](url)

**Comment by jaszhix** [comment]
The original version didn't work with Cinnamon 3.4, and this applet has been versioned, so the the original does run like it always has on Cinnamon 3.2 and older. Your gist points to a 404.

**Comment by xearonet** [comment]
@jaszhix 
On another machine I use Cinnamon 3.0.7 and applet crash too.
Here logs: [https://gist.github.com/xearonet/5eee8b553b7fc3baf2cc7d76f2544f80](url)

**Comment by jaszhix** [comment]
@xearonet Okay, thanks I'll look into it.
