### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: doesn't render in the tray

### ISSUE THREAD

**Issue by mainmachine** [linuxmint/cinnamon-spices-applets#690]
[Have you read the guidelines for contributing?]: <> (Before opening an issue, please read the guidelines for contributing linked above. Else the issue will be closed. Also don't forget to notify the author.)

[Notify author of applet]: <> (You should mention the author on GitHub by typing @ plus his/her username to trigger a notification and bring his/her attention to an issue or pull request. You find the username of the author on the cinnamon spices website: https://cinnamon-spices.linuxmint.com/)
@jaszhix 

[Issue]: <> (Describe your issue below.)
As of an update today, it looks like this applet is broken. It doesn't render in the tray (although it is clickable) and while I get a right click menu and can click on preferences, no menu appears. 

Here's the Looking Glass output:

```
error t=2017-05-16T10:14:11Z in onGraphRepaint: MyApplet.prototype.onGraphRepaint@/home/daver/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/applet.js:243:1
```

Ubuntu 16.04, Cinnamon 3.4, and I've been running this applet for over a year now through several upgrades on lots of machines with no problems.

Great Applet BTW, thanks for your work!

**Comment by jaszhix** [comment]
Hi, a lot of the credit belongs to @ccadeptic23, I'm just picking up where he/she left off. When this error occurs, is there any additional logging in ~/.xsession-errors? I'm not sure if you have that log there on Ubuntu, but ```cinnamon --replace``` will also retrieve the extra logging.

**Comment by mainmachine** [comment]
So as of today, it looks like this is working again for me. I didn't notice anything specifically that changed.

There was something in ~/.xsession-errors: 
```
Cjs-Message: JS WARNING: [/home/daver/.local/share/cinnamon/applets/multicore-sys-monitor@ccadeptic23/3.4/Graphs.js 316]: assignment to undeclared variable maxvalue
```
