### ISSUE TITLE
weather@mockturtl: "Temp. Felt" is better suited then "Wind Chill"

### ISSUE THREAD

**Issue by SeraphDosSantos** [linuxmint/cinnamon-spices-applets#701]
Hi @mockturtl, as I had mentioned this prior to the applets being regrouped here: "Temp. Felt" is better suited to the actually labelled "Wind Chill" temperature, as seen in this recently screen printed image:

![screenshot from 2017-05-17 22-16-31](https://cloud.githubusercontent.com/assets/3285430/26183850/7bd37216-3b4f-11e7-926b-e799b71316d3.png)

With humidity, Yahoo! weather API does augment the Wind Chill temperature above the actual temperature.

**Comment by mockturtl** [comment]
Previous discussion: mockturtl/cinnamon-weather#169

**Comment by icarter09** [comment]
@Gr3q

**Comment by Gr3q** [comment]
That property is displayed as "Feels Like" where it is used at the moment. 

I think it is better suited than either of what was proposed here as it describes the purpose of the value.

This can be closed unless @SeraphDosSantos is still unhappy with how it is displayed.
