### ISSUE TITLE
TouchpadIndicatorClassic@lusito.info: Applet does not work

### ISSUE THREAD

**Issue by kimsaehun** [linuxmint/cinnamon-spices-applets#743]
No author; Applet has been donated.

The Touchpad Indicator Classic applet does not work on Fedora 25 running Cinnamon 3.4.0.

To replicate, install the Touchpad Indicator Classic applet from the Applets settings windows. 

Screenshot after installing applet:
![error](https://cloud.githubusercontent.com/assets/5378869/26290402/07502afa-3e5c-11e7-8a9d-bc6c8a872f93.png)

Next, add applet to panel which causes the following error: "No JS module 'dbus' found in search path."

**Comment by NikoKrause** [comment]
This applet has been deleted: https://github.com/linuxmint/cinnamon-spices-applets/pull/1259
