### ISSUE TITLE
Expo icon looks like the icon for network-trying-to-connect

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/cinnamon-spices-applets#751]
(Author of the applet: I couldn't find one; the applet is built into Mint or Cinnamon, I think.)

Sorry to pick nits, but this is an irritating nit and one that can easily be squashed. Moreover:cCumulatively, cosmetic improvements can make a big difference, I feel.

    how exactly can we reproduce the error: put the Expo applet onto a panel.
    what you expected to happen: to see an icon that I can read at a glance without being misled
    what actually happened: I wonder for a moment whether my network is down, because of the resemblance between Network Manager's 'trying to connect' icon and the Expo icon,.
    the version of Cinnamon and which Linux distro you are running: Mint 18.1, Cinnamon 3.2.7.

**Comment by NikoKrause** [comment]
Which applet? UUID of applet?

**Comment by NikoKrause** [comment]
Also which icon theme do you use?

**Comment by ACinnamonUserInUK** [comment]
I was using the 'Paper' icon theme, but I find that the Expo icon looks the same in the Mint-X theme and the Mint-Y theme.

I tried to test what the Network Manager icon looks like in those other two themes, but the Network Manager is too broken for me easily to check that. (I use Network Manager 1.2.2, because the newer version - 1.2.6 - breaks my VPN. And in 1.2.2, turning off the wifi - which I did so as see the reconnecting icon when I turned it back on - means that nearly all the wifi networks disappear from the Network Manager list, such that when the wifi is turned back on, one cannot reconnect to one's usual network. I could go on. Perhaps I should file a separate bug report about that.)

**Comment by ACinnamonUserInUK** [comment]
Oh, sorry, you wanted the 'UUID' of the applet. But I don't know what that is or how to find it.

**Comment by NikoKrause** [comment]
Rightclick -> About... 
There you find the UUID

**Comment by ACinnamonUserInUK** [comment]
![new](https://cloud.githubusercontent.com/assets/9998846/26322901/6e88bf28-3f1c-11e7-91d6-819ed4ba2a4f.png)

**Comment by JosephMcc** [comment]
This repo is for the 3rd party applets hosted on the cinnamon spices site. What you're talking about it the built in expo applet so really belongs in the Cinnamon repo, not here.
