### ISSUE TITLE
weather@mockturtl: Request: Better Weatherdata

### ISSUE THREAD

**Issue by MegaV0lt** [linuxmint/cinnamon-spices-applets#780]
weather@mockturtl

The actual data for the weather is very poor. Usualy up to 8 °C off odf thew real value. There is much better data from meteogroup (www.wetter24.de). 

Is there a way to get data from that source?
What about other sources?

**Comment by NikoKrause** [comment]
You should mention the author on GitHub by typing @ plus his/her username to trigger a notification and bring his/her attention to an issue or pull request. You find the username of the author on the cinnamon spices website: https://cinnamon-spices.linuxmint.com/

**Comment by jaszhix** [comment]
@mockturtl

**Comment by SerafDosSantos** [comment]
@MegaV0lt @mockturtl http://openweathermap.org/ would maybe be a better fit. Weather is accurate to 1 degree for me. Weather data from Yahoo! is quite horrible in my opinion.

**Comment by MegaV0lt** [comment]
Openweathermap does not even find my Town (Gelnhausen). Almost no data for germany

**Comment by mockturtl** [comment]
Abstracting the data provider would be wonderful, and a lot of work.  I won't have time to do it myself.

Have a look at the [bbcwx@oak-wood.co.uk](https://github.com/linuxmint/cinnamon-spices-desklets/tree/master/bbcwx%40oak-wood.co.uk) desklet.  

http://www.oak-wood.co.uk/oss/other/bbcwx
