### ISSUE TITLE
confusing soundpath config - axos88@countdown-timer

### ISSUE THREAD

**Issue by donlencho** [linuxmint/cinnamon-spices-applets#781]
@axos88
Your fork has nice little additions to the original although such minute differences makes me wonder if it's necessary to have one more applet in the list, but well, choice is good I guess...
I see a problem with a change of yours though:
Confusing that you would do:
Util.spawnCommandLine("play " + AssetDir + "/" + this.SoundPath);
whereas the config allows to configure the absolute sound path which would only work if you did
Util.spawnCommandLine("play " + this.SoundPath);
So maybe you want to hardcode the sound file (not a good idea in my opinion) but then remove it from the settings.
Cheers,

**Comment by axos88** [comment]
Thanks. I will look into it

**Comment by jake1164** [comment]
This has been resolved in the new cinnamon-timer@jake1164 which will replace this applet. 

I moved the settings to the standard configure dialog and now you dont have to edit the source or restart cinnamon for the change to take effect.

**Comment by NikoKrause** [comment]
This applet has been deleted. Please use the new fork by @jake1164 
https://cinnamon-spices.linuxmint.com/applets/view/302
