### ISSUE TITLE
Force Quite II: this applet work for only one time not more !!!

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon-spices-applets#81]
I try Force Quit II. It has other form of bug:

Force Quite II work for only one time !! After that if you try to use it again it will never work ! Even after restart PC not work. Moreover, there is very strange thing: I try to uninstall it & reinstall it but not worked also, but when I uninstall it then restart PC then reinstall it it will work but also for one time !!! So it is useless.

**Comment by NikoKrause** [comment]
https://github.com/linuxmint/cinnamon-spices-applets/issues/69
