### ISSUE TITLE
sshlauncher@sumo Opening editor fails

### ISSUE THREAD

**Issue by d3xter** [linuxmint/cinnamon-spices-applets#821]
I've installed the latest version of the sshlauncher@sumo.

Opening the editor fails with the following error:

(cinnamon:1920): Cjs-WARNING **: JS ERROR: Exception in callback for signal: activate: GLib.SpawnError: Kindprozess ».local/share/cinnamon/applets/sshlauncher@sumo/launch_editor.sh« konnte nicht ausgeführt werden (Keine Berechtigung)

Permissions of launch_editor.sh are -rw-r--r--
After adding +x Permission opening the editor works as expected.

**Comment by d3xter** [comment]
cc: @sumo

**Comment by NikoKrause** [comment]
There are 2 SSH Launcher applets. Do they both work?

**Comment by sumo** [comment]
sshlauncher@sotiwin is not mine. It was a fork of my original to fix a pending issue. It doesn't look like it has been updated with the latest code so unlikely to work on 18+

**Comment by NikoKrause** [comment]
Then we should delete the "fixed" version.

**Comment by collinss** [comment]
They both seem to work for me, but as the 'fixed' one is no longer maintained, I figured there was no point in keeping it around so I removed it.
