### ISSUE TITLE
Time is frozen

### ISSUE THREAD

**Issue by ilariotruppa** [linuxmint/cinnamon-spices-applets#84]
Time is frozen. It shows the correct time when set but then it does not go on, just seems frozen.
Is there any workaround?

Ilario
![schermata del 2017-02-06 09-21-02](https://cloud.githubusercontent.com/assets/13014794/22639478/8cfe9656-ec4e-11e6-97d5-80c6ac6491ff.png)

**Comment by NikoKrause** [comment]
https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/CONTRIBUTING.md
