### ISSUE TITLE
sshlauncher@sumo: "unable to find a shell" when x-terminal-emulator is terminator

### ISSUE THREAD

**Issue by niko2** [linuxmint/cinnamon-spices-applets#840]
Every time I use the applet, I get same error : terminal opens with "unable to find shell" (I guess this is the right message since my desktop language is french, then my message is "impossible de trouver un shell")
I figured out x-terminal-emulator is used by the applet using -T end -e options

when reading terminator manual, we can notice :
       
        -e, --command=COMMAND
              Runs the specified command instead of your default shell or profile specified command. Note: if Terminator is launched as x-terminal-emulator -e  behaves  like
              -x, and the longform becomes --execute2=COMMAND

       -x, --execute COMMAND [ARGS]
              Runs the rest of the command line instead of your default shell or profile specified command.

So it seems it could be an issue with terminator behavior.
If you plan to add settings and we can choose a specific terminal, there should be a workaround for terminator ?
I did not find any workaround to let terminator execute a shell and allow ssh command to work, then I use terminator for app prefered and gnome-terminal as x-terminal-emulator alternative for this nice applet

        $ lsb_release -a
          No LSB modules are available.
          Distributor ID:	LinuxMint 
          Description:	Linux Mint 18 Sarah 
          Release:	18
          Codename:	sarah

       $ cinnamon --version
          Cinnamon 3.0.7

**Comment by NikoKrause** [comment]
You should mention the author on GitHub by typing @ plus his/her username to trigger a notification and bring his/her attention to an issue or pull request. You find the username of the author on the cinnamon spices website: https://cinnamon-spices.linuxmint.com/

**Comment by niko2** [comment]
@sumo

**Comment by sumo** [comment]
I will add a setting in as the terminal launching has been quite error prone especially between distributions.

**Comment by RecNes** [comment]
I'm facing with the same issue right now.

> Distributor ID:	LinuxMint
> Description:	Linux Mint 18.2 Sonya
> Release:	18.2
> Codename:	sonya
> Cinnamon: 3.4.6
> SSH Launcher: 2017-12-21, 03:35 UTC
> Terminator: 0.98

**Comment by meeeehdiiii** [comment]
I installed SSH Launchner yesterday on my Linux Mint 19.3 via the Applets interface and it works fine with terminator. The command I use in "Use custom command for opening terminal" is `terminator -x`.
