### ISSUE TITLE
multicore-sys-monitor@ccadeptic23: prefs.json not saved in ~/.cinnamon/configs/multicore-sys-monitor@ccadeptic23/

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#859]
[Have you read the guidelines for contributing?]: <> (Before opening an issue, please read the guidelines for contributing linked above. Else the issue will be closed. Also don't forget to notify the author.)

[Notify author of applet]: <> (You should mention the author on GitHub by typing @ plus his/her username to trigger a notification and bring his/her attention to an issue or pull request. You find the username of the author on the cinnamon spices website: https://cinnamon-spices.linuxmint.com/)
@jaszhix 

[Issue]: <> (Describe your issue below.)

This applets saves the configuration in `~/.local/share/cinnamon/applets/<version>/prefs.js` (along with the supporting files). I believe it should be placed in the file `~/.cinnamon/configs/multicore-sys-monitor@ccadeptic23/multicore-sys-monitor@ccadeptic23.json`.

See also #677

**Comment by jaszhix** [comment]
The settings handling will need to be rewritten for it to support Cinnamon's settings properly. It makes sense to keep this limited to #677 since it encompasses the same issue.

**Comment by sphh** [comment]
I thought bug #677 is about overwriting the configuration file on every update and not (especially) about the location of the configuration file. But if you keep track of the location change in that bug, that should be ok.
