### ISSUE TITLE
calendar@simonwiles.net: seconds since the Epoch (%s) doesn't advance regularly

### ISSUE THREAD

**Issue by mscheper** [linuxmint/cinnamon-spices-applets#869]
@simonwiles: In Version 1.2 of World Clock Calendar (and also earlier versions, and also the standard calendar@google.org applet), the `%s` strftime option seems to cause problems. It works okay on its own, but when the format string gets long, the epoch time only updates once in a while, and rather sporadically.

To reproduce:
1. Open the World Clock Calendar configuration dialogue
2. Set the date format to `%a %d/%m/%Y (%V) %s %-l:%M:%S%P`
3. Observe the behaviour of the clock

I would expect the epoch seconds to advance each second, just like the human-formatted clock does, but it seems to only advance every 100 seconds or so, or after some smaller, random number of seconds, or not at all.

The applet doesn't seem to reliably expand to accommodate this format string.

`%s` is a standard strtime option; it's included in the list if you follow the 'Complete strftime listing' link on the page that 'Show information on date format syntax' links to. I look at epoch times a lot, and it would be very helpful to tell from a glance whether a timestamp was a few seconds ago or a different time, so hopefully this can be made reliable in the applet. I find the week number helpful too, which is why I want to use such a complicated format string.

I'm currently seeing this issue in Mint 18.2, but I've seen it in earlier versions of Mint as well.

**Comment by sphh** [comment]
@mscheper: Do you still experience this problem?

I just checked this on Linux Mint 20.1 and the epoch updates every second. (Sometimes a second is skipped …)

If it works, could you close the bug?

**Comment by mscheper** [comment]
Thanks for asking. It's working in Mint 19, too. Somebody else already closed this issue.
