### ISSUE TITLE
The "Open thumbnails on click" option is not working

### ISSUE THREAD

**Issue by GecoMynx** [linuxmint/cinnamon-spices-applets#87]
When setting the option "Open thumbnails on click" to true, it should only show a thumbnail by clicking on an app icon with more than one window grouped to one icon.
Instead, this option does exactly nothing at all, even after rebooting the whole PC, not just cinnamon.

**Comment by NikoKrause** [comment]
https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github/CONTRIBUTING.md

**Comment by NikoKrause** [comment]
Oh. You could have renamed the title of the closed issue, instead of opening a new one^^ But nevermind.

**Comment by GecoMynx** [comment]
oh.. Sorry xD Didn't knew that. Well, now I do, for the next time, thanks :)
