### ISSUE TITLE
placesCenter@scollins: Does not open selected directory

### ISSUE THREAD

**Issue by sphh** [linuxmint/cinnamon-spices-applets#873]
[Have you read the guidelines for contributing?]: <> (Before opening an issue, please read the guidelines for contributing linked above. Else the issue will be closed. Also don't forget to notify the author.)

[Notify author of applet]: <> (You should mention the author on GitHub by typing @ plus his/her username to trigger a notification and bring his/her attention to an issue or pull request. You find the username of the author on the cinnamon spices website: https://cinnamon-spices.linuxmint.com/)
@collinss 

[Issue]: <> (Describe your issue below.)

After one of the two last updates entries in the USER section do not open correctly in Nemo.

I select `Home` in the USER section and `nemo` opens with another directory displayed. The same happens with all other items in the user section (but not the `Rubbish Bin` or any entry in the SYSTEM or RECENT DOCUMENTS section). It opens always the same directory and as it happens it is the last entry of my bookmarks, but this might be coincidental.

**Comment by collinss** [comment]
Hmm. You're right. I'll look into it after work today. It should be an easy fix.

**Comment by SerafDosSantos** [comment]
For me, it seems to open any bookmark as if they are the last one listed.
