### ISSUE TITLE
windowlist@cobinja.de  not worked now

### ISSUE THREAD

**Issue by murman-lexus** [linuxmint/cinnamon-spices-applets#875]
bug after yesterday Cinnamon Update

glass.log
> trace t=2017-06-09T07:52:01.945Z 
<----------------
CobiWindowList.prototype._updatePinnedApps@/home/zubovaleksey/.local/share/cinnamon/applets/windowlist@cobinja.de/3.2/applet.js:1567
CobiWindowList.prototype.on_applet_added_to_panel@/home/zubovaleksey/.local/share/cinnamon/applets/windowlist@cobinja.de/3.2/applet.js:1366
Applet.prototype.on_applet_added_to_panel_internal@/usr/share/cinnamon/js/ui/applet.js:346
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:328
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:59
loadExtension@/usr/share/cinnamon/js/ui/extension.js:451
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:235
---------------->
error t=2017-06-09T07:52:01.945Z [Applet "windowlist@cobinja.de"]: Failed to load applet: windowlist@cobinja.de/27
error t=2017-06-09T07:52:01.945Z Could not load applet windowlist@cobinja.de

**Comment by jaszhix** [comment]
@Cobinja

**Comment by Cobinja** [comment]
@murman-lexus Can you provide the contents of $HOME/.cinnamon/configs/windowlist@cobinja.de/27.json ?

**Comment by murman-lexus** [comment]
@Cobinja
Hello. Sorry for waiting.
Directory $ HOME/.cinnamon/configs/windowlist@cobinja.de/
Has 0 files and folders

**Comment by murman-lexus** [comment]
Reinstalling the applet solved the problem.
Sorry for the time spent...
