### ISSUE TITLE
rancher@centurix: Homestead Manager Applet not working after Homestead update

### ISSUE THREAD

**Issue by moretocome** [linuxmint/cinnamon-spices-applets#876]
@Centurix 

The Homestead Manager Applet is not working anymore after I updated laravel/homestead to v2.1.0.

The update moved the Homestead.yaml config file to the Homestead install dir instead of ~/.homestead. I have selected the Homestead install dir for both "Homestead project folder" and "Homestead config folder" in the applet configuration, but still the applet reports "Homestead missing or not configured", even though the vm is running.

**Comment by Centurix** [comment]
Submitted PR #878 to resolve this issue. The configuration dialog wants to prefix selected directories with file://  and stores them like that in the settings file. Thanks for the feedback, much appreciated!

**Comment by moretocome** [comment]
Thanks for the fast response! :)
