### ISSUE TITLE
Icing Task Manager: Bug: Option "Open thumbnails on click" does'n work

### ISSUE THREAD

**Issue by GecoMynx** [linuxmint/cinnamon-spices-applets#88]
When setting the option "Open thumbnails on click" to true, it should only show a thumbnail by clicking on an app icon with more than one window grouped to one icon.
Instead, this option does exactly nothing at all, even after rebooting the whole PC, not just cinnamon.

**Comment by NikoKrause** [comment]
It's always gold to notify the author:
@jaszhix

**Comment by GecoMynx** [comment]
Thanks, I'm all new to GitHub :)

**Comment by jaszhix** [comment]
If this issue is a bug report, you must list your: 

  - Cinnamon version
  - Extension version
  - Linux distribution
  - Pastbin the outputs of:
    - ~/.cinnamon/configs/IcingTaskManager@json/*.json
    - ~/.cinnamon/glass.log
    - ~/.xsession-errors
  - Describe the steps needed to be taken in order to reproduce this bug.

**Comment by jaszhix** [comment]
@GecoMynx Not reproducing this. Clicking the icons opens the thumbnail menu when more than one window is open.

**Comment by GecoMynx** [comment]
On my System (Linux Mint 18.1 Cinnamon) it displays the thumbnail instantly on mouse hover on every icon, doesn't matter if it's a single window or more windows grouped to one icon and it also doesn't matter if the option is set to true or false.
I'll provide you the other information like Cinnamon version and logs later today.

**Comment by GecoMynx** [comment]
@jaszhix 
- Cinnamon Version: 
**3.2.7+serena**
- Extension Version: 
**Installed it from the "Applets --> Available Applets (Online)"-Menu. When I click on more information, [**this**](https://cinnamon-spices.linuxmint.com/applets/view/269) Website pops up. Don't know how to find out what version it is, but regarding the Website, it has been edited 3 days ago.**
- Linux distribution:
**Mint 18.1 Cinnamon 64-Bit**
- Pastebin the outputs of:
  - ~/.cinnamon/configs/IcingTaskManager@json/*.json
  - ~/.cinnamon/glass.log
  - ~/.xsession-errors
**These files are all very long, so I've put them ("39.json", "glass.log" and "xsession-errors.txt") into the attached [Logs.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/758458/Logs.zip)
Please let me know if you want me to post the files in another way.**
- Describe the steps needed to be taken in order to reproduce this bug: 
**Done that on the Post above.**

**Comment by NikoKrause** [comment]
You get the applet version of Icing Task Manager, if you right click on the applet and select "About..."

**Comment by GecoMynx** [comment]
Ah okay. So **Extention Version is 4.1.2**

**Comment by NikoKrause** [comment]
The current Version is 4.3.2. Go to System Settings > Applets > Available Applets (online), then press "Refresh List" button and apply the available update for Icing Task Manager.

**Comment by GecoMynx** [comment]
Ah okay, now it seems to work popery.
You can close this issue then.
I'll reopen it if something still isn't okay with that option.
Thanks :)

**Comment by NikoKrause** [comment]
When I close it, you won't be able to reopen it.
Would be better, if you close it.

**Comment by GecoMynx** [comment]
A okay, then I'll lose it :+1:
