### ISSUE TITLE
sysmonitor@orcus: libgtop-2.0.so.10: undefined symbol: glibtop_init_s trace

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/cinnamon-spices-applets#930]
[Have you read the guidelines for contributing?]: <> (Before opening an issue, please read the guidelines for contributing linked above. Else the issue will be closed. Also don't forget to notify the author.)

[Notify author of applet]: <> (You should mention the author on GitHub by typing @ plus his/her username to trigger a notification and bring his/her attention to an issue or pull request. You find the username of the author on the cinnamon spices website: https://cinnamon-spices.linuxmint.com/)

[Issue]: <> (Describe your issue below.)
When I start Cinnamon, sysmonitor applet does not start. I get an error on the screen stating that some of the applets failed to load. glass.log has the following:

````
error t=2017-06-23T02:16:18.236Z Could not locate glibtop_init_s: 'glibtop_init_s': /usr/lib/libgtop-2.0.so.10: undefined symbol: glibtop_init_s
trace t=2017-06-23T02:16:18.237Z 
<----------------
Extension.prototype.logError@/usr/share/cinnamon/js/ui/extension.js:189:13
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:340:9
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:60:18
loadExtension@/usr/share/cinnamon/js/ui/extension.js:451:17
init@/usr/share/cinnamon/js/ui/appletManager.js:47:9
start@/usr/share/cinnamon/js/ui/main.js:454:5
@<main>:1:31
---------------->
error t=2017-06-23T02:16:18.237Z [Applet "sysmonitor@orcus"]: Failed to load applet: sysmonitor@orcus/55
error t=2017-06-23T02:16:18.237Z Could not load applet sysmonitor@orcus

````

I have do libgtop installed:

````
Name            : libgtop
Version         : 2.36.0-1
Description     : A library that reads information about processes and the running system
Architecture    : x86_64
URL             : http://www.gnome.org/
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : glib2  libxau
Optional Deps   : None
Required By     : gnome-system-monitor
Optional For    : psensor
Conflicts With  : None
Replaces        : None
Installed Size  : 1193.00 KiB
Build Date      : Wed 05 Apr 2017 06:20:28 AM EDT
Install Date    : Tue 25 Apr 2017 12:18:59 PM EDT
````
Cinnamon version is: `Cinnamon 3.4.2 `

What's interesting is that after I go into Applets and manually start sysmonitor, it does load up and shows up on the panel.

Not sure what's wrong. Please let me know if I can help in any way with more diagnostics. This is the only applet that's giving me issues. All other ones work fine.

**Comment by NikoKrause** [comment]
You should mention the author on GitHub by typing @ plus his/her username to trigger a notification and bring his/her attention to an issue or pull request. You find the username of the author on the cinnamon spices website: https://cinnamon-spices.linuxmint.com/

**Comment by nick-s-b** [comment]
@NikoKrause I've looked at https://github.com/orcus and https://github.com/orcuscz profiles but they don't seem to be the same author of this. I have no idea what the github name of the author of this is.

**Comment by NikoKrause** [comment]
As I mentioned before, you find the username in the Website linked above. To be more specific https://cinnamon-spices.linuxmint.com/applets/view/88

**Comment by jaszhix** [comment]
The author is @OrcusCZ, he responded in the #668.

**Comment by OrcusCZ** [comment]
I'm the author. Honestly, I've no idea why it happens. It happens only after Cinnamon init if I use network related functions from glibtop. Removing/adding the applet once the Cinnamon is running throws no error.
If I call those functions from glibtop, that error is thrown in some part of Cinnamon initialization, but if I call string match() function right after glibtop init, the error is thrown by match() (which can be caught with try-catch) and then everything works fine. It makes no sense to me, but for some reason this workaround works, at least in Fedora 25.
I am working on a patch fixing this and also using Cinnamon xlet settings api instead of gjs/cjs program as now. It should be updated soon.

**Comment by nick-s-b** [comment]
@OrcusCZ thank you so much for reading and trying to fix this! I just love this applet and I'm glad I can get it up by manually starting it. Let me know if there's a way to generate some diagnostics on my install.
